### ISSUE TITLE
Could change the intensity of the rumble 

### ISSUE THREAD

**Issue by cualquiercosa327** [Atmosphere-NX/Atmosphere#100]
It would be some similar to the speaker/screen brightness when you can choose the intensity.I know many people which disable the rumble because it is too higth (usually with the pro controller).

As i have been said (Thanks for all CTCaer ) it already exist.Only need an option is settings that controls ApplyMasterVolume is needed in atmosphere.

I would love use this post for asking about if you have found how switchos  joycons service works.I mean ,the last part where it subsamples them from 5ms to 15ms per sample in Switch.
The frequencies/amplitudes are then interpolated and sent to the joy-con.  (Again thanks to CTCaer for answering all my questions)

**Comment by hexkyz** [comment]
Closing for now. This kind of feature is still a very low priority.
