### ISSUE TITLE
Boot is broken

### ISSUE THREAD

**Issue by Anti-Apple4life** [Atmosphere-NX/Atmosphere#1005]
## Bug Report

Whenever I boot Atmosphere, it shows the black-and-white logo, but does not boot,

### What's the issue you encountered?
Whenever I boot Atmosphere, it shows the black-and-white logo, but does not boot,

### How can the issue be reproduced?
I don't know

### Crash Report

No report made

### System Firmware Version

1.2.0
### Environment?
Hekate and Fusee

**Comment by SciresM** [comment]
Closing, please reopen using the issue templates properly. "Doesn't boot" is useless; say what you observe fully when reopening.

1.2.0 is not a real firmware version.

**Comment by Anti-Apple4life** [comment]
I had a typo  and I tried to put 9.2.0 and The boot sequence goes until the black-and-white ams logo, but then freezes.

**Comment by cheesycod** [comment]
If you're still having this problem, exactly what version of atmosphere are you using?

**Comment by SciresM** [comment]
This was a troll issue, @cheesycod. Please do not give it more attention.

**Comment by SciresM** [comment]
Oh, never mind, this wasn't the 10.1.0 guy. Fwiw issue after the b/w ams logo is "typically" exfat or archive bits -- some failure to read contents on the SD.

I apologize, there was a nearly identical troll issue the other day.
