### ISSUE TITLE
Add support for verbose error codes

### ISSUE THREAD

**Issue by micah686** [Atmosphere-NX/Atmosphere#102]
Could you add support for more descriptions in error codes when something goes wrong? It would be nice to have the error descriptions from here: http://switchbrew.org/index.php?title=Error_codes shown when that particular error is triggered, alongside the 1234-5678 code format. I feel like this would be useful to both users and devs alike, to help identify issues.

**Comment by hexkyz** [comment]
There will be better error descriptions eventually. Right now this is fairly low priority.
