### ISSUE TITLE
My firmware version is 10.0.4 does the latest 0.12.0 release support it?

### ISSUE THREAD

**Issue by tk1076408** [Atmosphere-NX/Atmosphere#1028]
Thanks!

**Comment by tk1076408** [comment]
Follow up: I tried to build a emummc, not able to launch.

Error message:
```
Failed to apply 'nosigchk'
Failed to launch HOS!
```

**Comment by SciresM** [comment]
1) Please use the issue templates
2) 10.0.4 is supported
3) Those are hekate errors, not atmosphere errors.
4) Signature patches are not supported by atmosphere.

**Comment by tk1076408** [comment]
@SciresM , Thanks for reply, but can you provide more detail about how to resolve the hekate error?
I use the latest hekte v5.2.1.

**Comment by Conan179** [comment]
@tk1076408 https://github.com/CTCaer/hekate/issues
