### ISSUE TITLE
Fatal Error occurred when running atmosphere

### ISSUE THREAD

**Issue by fargostz** [Atmosphere-NX/Atmosphere#1032]
## Bug Report
TITLE ID: 01000000000000005
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_000000000018862f1.bin

### What's the issue you encountered?

I tried to install SysDVR. 
I'v put the SysDVR files where a Atmosphere folder is inside since then no way to launch CFW to eMMC or SysNand

### Crash Report

A bin file i can't open it :/

### System Firmware Version   10.0.2

**Comment by fargostz** [comment]
So after some test, my switch won't boot at all without hekare, power button won't boot my switch even in OFW.
I need to rcm my switch then inject hekate, then boot into ofw otherwise it won't boot :/
I've might screwed up the booting services of my switch :(
Since i'm kind of bothered by that i'v looked up in switchbrew.org and it tells me that title-id 0100000000000005 is built-in and is actually the boot process :/
How can i restore it if there's a way ?

**Comment by SciresM** [comment]
Help can't be provided if you don't upload your fatal error report.

**Comment by fargostz** [comment]
> 
> 
> Help can't be provided if you don't upload your fatal error report.

Here's a link posted on gofile because i can't upload directly on github :'( :
https://gofile.io/d/BHPjD2

**Comment by SciresM** [comment]
You have an improperly installed package2 -- you do not actually have 10.0.0 kernel installed. Did you use choi or something? Seems like it failed to fully install the update.

Not an atmosphere issue, use an rcm tool (hekate(?)) to flash 10.0.0 package2 to your emummc.

**Comment by fargostz** [comment]
I don't remember updating firmware in any manner :/ 
If I understand clearly, I need to download firmware 10.0.0 then flash it through Hekate ? I recently updated Atmosphere, Hekate and redone the emuMMC maybe i haven't done it right ?

**Comment by SciresM** [comment]
No, that was not what I was talking about. You're right that you'll need to dump/extract 10.0.0, and flash package2 to your emmc.

**Comment by fargostz** [comment]
First of all thanks for all the info you gave me ! Do you have a guide or a tuto to how to flash, I really don't want to make things even worse 😂
