### ISSUE TITLE
''A fatal error occurred when running Atmosphere.''

### ISSUE THREAD

**Issue by Jimbo420** [Atmosphere-NX/Atmosphere#1038]
My switch gives this error everytime it try to load into atmosphere either from the emummc or fusee primary. It worked fine until i woke up today and saw the error on the switch screen. I also just updated atmosphere and hekate just to make sure if that would fix it, but nope. Still didn't work.

<img width="555" alt="Capture" src="https://user-images.githubusercontent.com/66968943/84693852-7560b680-af48-11ea-8d6b-3678408a944f.PNG">

Error Description: std: :abort() called (0xffe)

![IMG_20200615_202955](https://user-images.githubusercontent.com/66968943/84693204-704f3780-af47-11ea-8b52-17864d06b123.jpg)

**Comment by SciresM** [comment]
Please re-open using the issue templates.
