### ISSUE TITLE
Could not boot when chainloaded with Hekate 5.3.0

### ISSUE THREAD

**Issue by dothackjhe** [Atmosphere-NX/Atmosphere#1041]
### What's the issue you encountered? 

The console goes into "black screen" after the Atmosphere logo when chainloaded with the latest iteration of Hekate (5.3.0).</br>
The issue arose when I upgraded to Atmosphere 0.13.0.</br>
The system boots fine when I reverted back to Atmosphere 0.12.0.</br>

### How can the issue be reproduced?

Chainload Atmosphere 0.13.0 with Hekate 5.3.0.</br>

### System Firmware Version

10.0.2</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 5.3.0
- Official release or unofficial build: Official build

**Comment by HookedBehemoth** [comment]
Assuming you mean launch fusee-primary by chainload:
> fusee-primary was last updated in: 0.13.0.

Did you update it from where you chainload?

**Comment by dothackjhe** [comment]
Yes, I did. @HookedBehemoth

**Comment by dothackjhe** [comment]
I do not think I was the only one who encountered it, though: https://gbatemp.net/threads/atmosphere-nx-custom-firmware-in-development-by-sciresm.496832/page-277#post-9096844

It's just funny no one made a report about it.

**Comment by HookedBehemoth** [comment]
Piracy is not supported.

**Comment by dothackjhe** [comment]
What if I say that I only run homebrews, will you even believe it?

Also, what made you think that I use Hekate for piracy purposes? Does it have something to do with Atmosphere?

**Comment by MichaelRebirth** [comment]
Im having the same problem chainloading it error code was 010notsurehowmany03 after passing the sept logo.

**Comment by ELY3M** [comment]
just use fuse-primary like me.

**Comment by xmun2k** [comment]
Having the same problem with fusee-primary. Using a completely clean install even on a new SDCard with fresh eMMC partition created.

**Comment by KiraPT** [comment]
I had the same issue and after some reading and some work I was able to fix the issue by using the fix from Hekate and rebuilding the hekate_ipl.ini file. 
Now it boots SysNand, EmuNand and Stock with no issues. 

If it is any help, here's my hekate_ipl.ini file:

[hekate_ipl.zip](https://github.com/Atmosphere-NX/Atmosphere/files/4822468/hekate_ipl.zip)

************
[config]
autoboot=2
autoboot_list=0
bootwait=2
backlight=100
autohosoff=0
autonogc=1
updater2p=0

[Atmosphere (SYSNAND)]
fss0=atmosphere/fusee-secondary.bin
kip1patch=nosigchk
emummc_force_disable=1
logopath=bootloader/bootlogo.bmp
icon=bootloader/res/icon_payload.bmp
{}

[Atmosphere (EMUMMC)]
payload=atmosphere/fusee-primary.bin
kip1patch=nosigchk
emummcforce=1
logopath=bootloader/bootlogo_emunand.bmp
icon=bootloader/res/icon_payload.bmp
{}

[Stock]
fss0=atmosphere/fusee-secondary.bin
stock=1
emummc_force_disable=1
{}
*****************

**Comment by SciresM** [comment]
This particular issue was solved by ctcaer using a fix I believe, the other one with xmun is maybe different.

**Comment by dothackjhe** [comment]
I actually had it resolved by deleting all the folders which pertains to the older version of Atmosphere and replacing everything with the ones that come with Atmosphere 0.13.0 as well as the latest sigpatch. As it appears, there are some leftover files from 0.12.0 that was in conflict with 0.13.0 that prevents the system from booting properly.
