### ISSUE TITLE
Fatal Error 

### ISSUE THREAD

**Issue by ahoytoy** [Atmosphere-NX/Atmosphere#1043]
## Bug Report
</br>
Fatal error</br>
Not sure which code it is, it happened pretty quickly.</br>
N/A</br>
### What's the issue you encountered?
I was playing a game while overclocking</br>
N/A</br>
</br>

### How can the issue be reproduced?

[ * ]</br>
Couldn't recreate issue</br>

### Crash Report

</br>
Not too sure how to use gist, but hopefully this bin file will help

[https://github.com/ahoytoy/bugbin/blob/master/report_0000062752b7f85c.bin](url)

</br>

### System Firmware Version

9.1..0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ fusee for 9.1 ]
- Do you have additional kips or sysmodules you're loading: Not sure
- Homebrew software installed: [ Checkpoint, sysclk, boot to payload ]

### Additional context?

- Additional info about your environment:
- I just want to know how to read the fatal error bin and if it can give me insight as to how the problem occured.  I was overclocking while playing a game in hot weather, so I'm thinking it might have overheated.  Just want to avoid getting that error again

**Comment by SciresM** [comment]
"AFE1" <-- this report was generated with a very old version of atmosphere.

In addition, the result is sdmmc driver -> tuning failed. Deeply unlikely that this is an atmosphere problem.
