### ISSUE TITLE
error Start DevMenu 6.x Definitive Edition v2

### ISSUE THREAD

**Issue by hamed34434** [Atmosphere-NX/Atmosphere#1049]
sorry for bad english
i run DevMenu 6.x Definitive Edition v2 app error to strat Atmosphere 13
override in this app fatal error 01592459926_0100000000012065
evry games works fine

https://mega.nz/file/Kc0GSaBR#RVouJu4K7e2heVPgBjlrmn-8VraCn0fso4V6XNs-PHc
[01592459926_0100000000012065.log](https://github.com/Atmosphere-NX/Atmosphere/files/4796753/01592459926_0100000000012065.log)

**Comment by SciresM** [comment]
1) doesn't use the issue templates
2) "DevMenu Definitive Edition" is not supported; atmosphere does not support piracy.
