### ISSUE TITLE
Atmosphere 0.13.0 prevents anything from loading

### ISSUE THREAD

**Issue by armoar334** [Atmosphere-NX/Atmosphere#1050]
after updating to 0.13.0, any modded games / title take over will get stuck on the 'nintendo switch' splash. any unmodded games will boot, but refuse to go further than the opening loading screen i.e animal crossing gets stuck on the little island and black screen. attempting to exit to the home menu brings me to a blank grey background, but for a short while the power menu and joycon pair/ attach overlay will work. i also cannot re-enter the games from here.

**Comment by SciresM** [comment]
Reopen using the issue templates.
