### ISSUE TITLE
Game Crash (Smash Bros / Mario Odyssey)

### ISSUE THREAD

**Issue by xmaurox9** [Atmosphere-NX/Atmosphere#1052]
## Bug Report 
</br>

###  What's the issue you encountered?

The atmosphere crashes, the screen turn orange and I must press the power button for more than 10 sec in order to power off.

I installed atmosphere 0.13.0 without modifications or updates. I also tried on 0.12.0 from a clean install. The switch firmware is 10.0.4. and tried with another switch on 9.1. same results.

### How can the issue be reproduced?

When I to play super smash bros ultimate in the "Smash" mode  or when I play super mario odyssey in any moment.
[ * ]</br>
### Crash Report
</br>
<a target="_blank" href="https://gist.github.com/xmaurox9/1b6254b3532dab8af08b7056d48ced2a" > Link to Gits</a>
</br>
<a target="_blank" href="https://user-images.githubusercontent.com/67122856/85073039-b393eb00-b17f-11ea-8605-c88cb0628f43.jpg" > Link to Image in file "crash_reports"</a>
</br>

</br>

### System Firmware Version

10.0.4</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release: 
  - Atmosphère 0.13.0 + master-32951329 + hbl-2.3.3 + hbmenu-3.3.0
  - Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ 3.3.0 ]

### Additional context?

- Additional info about your environment:
-Other games like "Yoshi's Crafted World", tetris 99,  works correctly.
-I tried to install the game in the Switch memory and in the SD card, the same error.
-I tried formatting the SD card on FAT32 and exFAT, same error.

**Comment by SciresM** [comment]
"the screen turn orange"

gonna say this is deeply unlikely to be an atmosphere issue, orange-screen is signal of hardware failure/error at runtime.
