### ISSUE TITLE
Error 20001-0123 when pokémon sword in-game

### ISSUE THREAD

**Issue by amine4567** [Atmosphere-NX/Atmosphere#1056]
### What's the issue you encountered?

I updated atmosphere to 0.13.0 and the switch firmware to 10.0.4 and now Pokémon Sword crashes seconds after going in-game.

### How can the issue be reproduced?

- Boot into Atmosphere 0.13.0 using fusee-primary
- Launch Pokémon Sword 
- Go in-game
- Crashes 1 second in (Error 20001-0123).

### Crash Report
2 crash reports at the same time:
https://gist.github.com/amine4567/60d3cfaac8c1c18f15b02fe0b7695fa5

### System Firmware Version

10.0.4

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusee-primary
- Official release or unofficial build: Official release
- Homebrew software installed: [ * ]

### Additional context?

N/A

**Comment by cheesycod** [comment]
Spam?

**Comment by masagrator** [comment]
> Spam?

Your post is spam if you're replying to issue closed 22 days ago by OP.
