### ISSUE TITLE
Crashes while playing Pokémon: "A fatal error has occured".

### ISSUE THREAD

**Issue by PP-theSLAYER** [Atmosphere-NX/Atmosphere#1057]
### What's the issue you encountered?

The game suddenly freezes, and leads to a crash.
Seems to occur when I load a different area, enter a raid, check the dex etc.

### How can the issue be reproduced?

To be honest, seems to occur randomly (besides loading a new area or simply performing an action). Only started happening after the update 1.2.0. Did not occur for previous updates.
Tho to be fair, I only updated Atmosphere shortly before the 1.2.0 game update, so I can't tell which is the problem here.

### Crash Report

[01592633019_0100abf008968000.log](https://github.com/Atmosphere-NX/Atmosphere/files/4808933/01592633019_0100abf008968000.log)
This is the most recent one I have. I have more and can attach them if need be.

### System Firmware Version

10.0.4

### Environment?

- fusèe through TegraRCMSmash.exe
- Official release 
  - 0.13.0
- No additional kips or sysmodules (I delete the Atmosphere folder before performing a fresh install)
- Homebrew software installed: [All via HBL: Checkpoint, ChoiDuJourNX, Firmware Dumper, EdiZon, nxdumptool, Reboot to Payload, WAINCartDumper]

### Additional context?

- No EmuMMC, SD 32GB, Class 10, ExFAT, no autosave on Pokémon, Auto RCM.

**Comment by raytan1807** [comment]
What's the issue you encountered?
The game suddenly freezes, and leads to a crash.

How can the issue be reproduced?
During the conversation with Mustard after obtaining the Max Honey (both sword & shield ver). Refer picture.
![01593018546_01008db008c2c000](https://user-images.githubusercontent.com/66457456/85607146-65528080-b686-11ea-88d3-a102859b6e10.jpg)

Crash Report
[01593018546_01008db008c2c000.log](https://github.com/Atmosphere-NX/Atmosphere/files/4827089/01593018546_01008db008c2c000.log)

System Firmware Version
9.2.0 & 10.0.4

Environment?
Hekate 5.3.0
Official release
0.13.0
No additional kips or sysmodules
Homebrew software installed: [All via HBL: Checkpoint, ChoiDuJourNX, JKSV, EdiZon, Reboot to Payload]

Additional context?
EmuMMC, 256GB, Class 10, Fat32, no autosave on Pokémon, no Auto RCM.

**Comment by SciresM** [comment]
Error code is "sdmmc driver (can't perform voltage switch)", so I'm going to close this.
