### ISSUE TITLE
Check and report on error in writing fatal error

### ISSUE THREAD

**Issue by HookedBehemoth** [Atmosphere-NX/Atmosphere#1059]
## Feature Request

Check and report on error in writing fatal error.</br>
Currently when a fatal error occurred and saving to the sd card fails nothing indicates that to the user.

#### Overview:
- The user should be warned that saving a fatal went wrong</br>

#### Smaller Details: 
- hekate already [reports an error](https://github.com/CTCaer/hekate/blob/master/bootloader/storage/nx_sd.c#L215) if opening the file fails</br>

#### Nature of Request:  
- Change
  - return error codes in [write_to_file](https://github.com/Atmosphere-NX/Atmosphere/blob/master/fusee/fusee-primary/src/fs_utils.c#L119)
  - handle and display error codes in [_check_and_display_atmosphere_fatal_error](https://github.com/Atmosphere-NX/Atmosphere/blob/master/fusee/fusee-primary/src/panic.c#L52)
### What component do you feel this would best fit within?
- [Fusée](https://github.com/Atmosphere-NX/Atmosphere#components)</br>

### Why would this feature be useful?
It would speed up getting to the cause of an issue for users that use fusee-primary.</br>

**Comment by hexkyz** [comment]
Thanks! This has been addressed in the latest commit.
