### ISSUE TITLE
Mariko support

### ISSUE THREAD

**Issue by berk-can** [Atmosphere-NX/Atmosphere#1067]
Hello, first of all thank you so much for this is amazing I love using Atmosphere on OG switch
as you may know OG switches are so old and I cant endure battery problem so I want to buy mariko with modchip so I want to ask you progress about Mariko support on Atmosphere. Is there a progress is it possible, are you working on it or trying to fid a way to launch atmosphere on sx core modchipped switches?
I am so sorry if you have a progress on any of your pages, but I couldnt find if youhave any please put direct link and close issue

**Comment by SciresM** [comment]
1) Use the issue templates
2) this shouldn't be a GitHub issue anyway
3) read the roadmap document.
