### ISSUE TITLE
std::abort() called (0xffe) atmosphere

### ISSUE THREAD

**Issue by Technosuke** [Atmosphere-NX/Atmosphere#1069]
So every time i launch atmosphere I get a fatal error. I've tried everything I can think of: Clean install, fixing archive bits with hekate, erasing unused files just in case... 

I don't know what's happening or what's messing up. I don't have any mods installed as far as I know.

Here is the report. Please, help.
[report_00000000060d338d.zip](https://github.com/Atmosphere-NX/Atmosphere/files/4871288/report_00000000060d338d.zip)

**Comment by SciresM** [comment]
You installed non-exfat firmware but have an exfat sd card. Format your sd card as fat32, or manually flash exfat firm to package2.
