### ISSUE TITLE
Atmosphere crash when JoyCon is removed from switch to play with bluetooth

### ISSUE THREAD

**Issue by DSMan97** [Atmosphere-NX/Atmosphere#1070]
## Bug Report

When I am playing Zelda Breath of the Wild and I decided to remove the Joycons to play  separatly the Atmosphere crashed
 Atmosphere version 0.13.0
 Switch version 10.0.4
 Bootloader Hekate

**Comment by SciresM** [comment]
Reopen using the issue templates.

**Comment by DSMan97** [comment]
@SciresM Is already fixed for The Next version?

**Comment by DSMan97** [comment]
@SciresM I usted The issue template, but have more information that I need yo share

**Comment by masagrator** [comment]
> @SciresM I used The issue template, but have more information that I need to share

No, you don't.

**Comment by DSMan97** [comment]
Okey I Will reopen later using the issue template and adding logs. Ithat help. Afer that I Will be forked the repo yo try to resolve by me own
