### ISSUE TITLE
A fatal error ocurred when running Atmosphére

### ISSUE THREAD

**Issue by gilvela** [Atmosphere-NX/Atmosphere#1071]
## Bug Report

A fatal error ocurred when running Atmosphére
Title ID: 010041544d530000
Error Desc: std : : abort( ) called (0xffe)

### What's the issue you encountered?
Hi community, this error came after I upgraded my switch to 10.0.4 with the lastest version of choidujour, after that I tried to run atmosphere as always but it came to a black screen with the message "A fatal error ocurred when running atmosphere". So I changed the archives version of atmosphere (atmosphere, sept, switch, hbmenu.nro carpets the first time I overwrited them, the second time I deleted them and put the new ones in te sd card) in my SD Card to the latest version (0.13), then I run Hekate 5.3.0 and select CFW and it also gives me the same error.

### How can the issue be reproduced?
Anytime I try to inyect payload fusee-primary.bin to run atmosphere.

### Crash Report

[report_0000000005ae7e7a.zip](https://github.com/Atmosphere-NX/Atmosphere/files/4875479/report_0000000005ae7e7a.zip)

Title ID: 010041544d530000
Error Desc: std : : abort( ) called (0xffe)

### System Firmware Version

10.0.4</br>

### Environment?

- Hekate 5.3.0
- Official version 5.3.0

- Do you have additional kips or sysmodules you're loading: I don´t know

### Additional context?

- Additional info about your environment:
Always run well, never had problems, but newest games needed the lastest version, so I decided to upgrade. Thanks for your help

**Comment by SciresM** [comment]
You installed non-exfat firmware but have an exfat sd card. Format your sd card as fat32, or manually flash exfat firm to package2.
