### ISSUE TITLE
Fatal error: Failed to initialize the SD card only on 256gb

### ISSUE THREAD

**Issue by monsterjj00** [Atmosphere-NX/Atmosphere#1077]
### What's the issue you encountered?

256gb sd card wont boot atmosphere.

### How can the issue be reproduced?

[ * ]</br>
Format 256gb sd card to fat 32
Drag and drop hekate and atmosphere
Launch hekate payload
launch fusee though hekate
</br>

### Crash Report

No crash reports were generated

### System Firmware Version

10.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - Hekate 5.3 (latest release)
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: N/A Clean install of Atmo

### Additional context?

My switch's sd card slot is okay due to my 128gb working just fine, and there are no errors on the 256 when testing through hekate and windows.

- Additional info about your environment:
- Nothing other than Hekate and atmosphere 13 are on the sd card and no files had been changed

**Comment by masagrator** [comment]
Can you provide brand and model of sdcard?

**Comment by monsterjj00** [comment]
> 
> 
> Can you provide brand and model of sdcard?

Its a PNY Pro Elite 256gb

**Comment by SciresM** [comment]
"Won't boot" what logos do you see?

**Comment by monsterjj00** [comment]
> 
> 
> "Won't boot" what logos do you see?

Nothing, no logos. Just a few seconds of black then fatal error.

**Comment by SciresM** [comment]
"Fatal error" you mean you get an error screen?

**Comment by monsterjj00** [comment]
> 
> 
> "Fatal error" you mean you get an error screen?

I suppose its an error screen, but its not a normal atmosphere blue screen like when it crashes while doing something.

Its just a black screen with the text rotated to be in portrait mode and it says "Fatal error: Failed to initialize the SD card"

**Comment by cheesycod** [comment]
Try running atmosphere through fusee-primary instead if hekate

**Comment by monsterjj00** [comment]
> 
> 
> Try running atmosphere through fusee-primary instead of hekate

Same thing

**Comment by cheesycod** [comment]
The error you got means that your SD card was not recognised. Can you check hekate to see if it sees your card properly

**Comment by monsterjj00** [comment]
> 
> 
> The error you got means that your SD card was not recognised. Can you check hekate to see if it sees your card properly and try booting via hekate fss0.

I dont exactly know what you mean by fss0. Though hekate sees it and runs fine but the second I enter atmosphere is just doesnt work.

**Comment by cheesycod** [comment]
Do you have a line saying fss0=<path to fusee secondary>?

**Comment by monsterjj00** [comment]
> 
> 
> Do you have a line saying fss0=<path to fusee secondary>?
If you mean add that line to the hekate ini Ill try that

**Comment by monsterjj00** [comment]
> 
> 
> Do you have a line saying fss0=<path to fusee secondary> in hekates config or are you loading fusee-primary via hekate?

That didnt work either but I also don't know if I set it up right.

**Comment by cheesycod** [comment]
can you post the contents of your hekate_ipl.ini

**Comment by SciresM** [comment]
@cheesycod Why are you trying to debug for this guy on github issues?

The issue seems pretty clearly to be the SD card (hekate supports some sd cards that fusee doesn't).

I would try booting via hekate, yes, if this fails then horizon might fail on your SD card too, but hopefully it works. Either way, not much to be done.
