### ISSUE TITLE
Can't load non-pirated digital games

### ISSUE THREAD

**Issue by poiagoboy** [Atmosphere-NX/Atmosphere#1092]
after updating I am able to play card based games and some homebrew from the HBmenu but when I try to load any of my previously purchased digital titles and some homebrew that appears on the homescreen (ppsspp), I am greeted with the error that I cannot start the software. I believe this is an issue with keys?

**Comment by SciresM** [comment]
"homebrew that appears on the homescreen" <-- piracy is not supported, this includes all unofficial installed content.

Can't reproduce, every other user with legitimately purchased digital titles reports no issues.

Also, you didn't use the issue templates.
