### ISSUE TITLE
Cant run any digital NSP game after update to Atmosphere 0.13.0 with NS 10.1.0

### ISSUE THREAD

**Issue by zsw12abc** [Atmosphere-NX/Atmosphere#1094]
Atmosphere version is 0.13.0 which downloaded from the Lastest release.
NS version is the new 0.13.0
Hekate is the lastest hekate - CTCaer mod v5.3.2 & Nyx v0.9.3

What i found in the` Hekate_ipl.ini` file is 
the missing of `kip1patch=nosigchk`
and  `kip1=atmosphere/kips/*`

Please correct me if I am wrong.
I think these two lines helped me to run the digital NSP game in CFW.
but the lacking these two cause the issue I raised.

However, I didn't see the `kips` folder under the atmosphere folder.
Will these be added in the next release?
Or is there any other ways which can run NSP game again?

**Comment by fincs** [comment]
Piracy is not supported.
