### ISSUE TITLE
Cheats Automatically on no matter which File I Edit to have them Off

### ISSUE THREAD

**Issue by Smoker1** [Atmosphere-NX/Atmosphere#1097]
Just Updated from Atmosphere 10, and FW 9.2 to FW 10.0.4 and AMS 13. I made sure to Edit the Override Config to 0, but Cheats are still being Enabled at the start.
Where is the new Configuration File? Why does it change every time???

**Comment by SciresM** [comment]
1) please use the issue templates 
2) config files must be placed in /atmosphere/config, and config lines must be uncommented to take effect.
