### ISSUE TITLE
A fatal error occured when running Atmosphere

### ISSUE THREAD

**Issue by acciardo** [Atmosphere-NX/Atmosphere#1099]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
I have firmware 9.1 and was running an older atmosphere and hekate without issue, but then I wanted to update it. So I put the newest hekate (v5.3.2 & Nyx v0.9.3) and Atmosphere 0.13 on my SD card. Now, whenever I boot into RCM, start hekate, and then launch fusee-primary.bin, I get the error:
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

[ Did you make any changes related to Atmosphère itself? ]</br>
No

### How can the issue be reproduced?
It happens every time I try launching atmosphere.

</br>
[ Include a detailed step by step process for recreating your issue. ]</br>
Start hekate </br>
Launch fusee-primary.bin

### Crash Report

I uploaded my error .bin file here: http://www.mediafire.com/file/p4ag38tc7f6biww/report_0000000006185c26.bin/file

### System Firmware Version

9.1 </br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
Hekate -> Fusee

**Comment by SciresM** [comment]
Fix the archive bits on the atmosphere folder and subfolders.
