### ISSUE TITLE
custom_splash error invalid screen dimensions - 0.14.0

### ISSUE THREAD

**Issue by deejay87** [Atmosphere-NX/Atmosphere#1105]
Hi
Got this error with custom_splash (no problem on 0.13.0), something change ?
Thanks

![IMG_0147](https://user-images.githubusercontent.com/4148145/89124760-c1a48d80-d4d9-11ea-81fb-a9cccefb9c50.jpg)

**Comment by hexkyz** [comment]
Hi!
No code changes related to the custom splash screen feature were introduced in the latest release. This message would only show up if fusee finds and reads the custom splash screen file, but it's data ends up being wrong. Could your files in the SD card be corrupted?

**Comment by deejay87** [comment]
ok, I go to try again, i do lot of tests on 2 switch and don't have any problems on my Sd Card's
