### ISSUE TITLE
Tinfoil not working

### ISSUE THREAD

**Issue by rhernandezr0930** [Atmosphere-NX/Atmosphere#1107]
Hello, neither with 0.14.0 nor 0.14.1 of Atmosphere Tinfoil works, why in version 0.13.0 if it worked and in these not? It says that the program cannot be opened from home and closes.

![IMG_20200802_195728](https://user-images.githubusercontent.com/69126825/89135676-933ca780-d505-11ea-9f85-04a79ad0367a.jpg)
![IMG_20200802_195219](https://user-images.githubusercontent.com/69126825/89135684-9b94e280-d505-11ea-9bb4-14f87f5b5501.jpg)

**Comment by fincs** [comment]
Piracy is not supported.

Also, you didn't use the issue templates.

**Comment by rhernandezr0930** [comment]
What templates are you referring to?

**Comment by rhernandezr0930** [comment]
What templates are you referring to?  If it worked normal in the version of Atmosphère 0.13.0, and in this one in none of the ones they released it works.
________________________________

**Comment by rhernandezr0930** [comment]
What templates are you referring to? If it worked normal in the version of Atmosphère 0.13.0, and in this one in none of the ones they released it works.

Dr. Reynaldo Hernández Ruiz
Odontólogo
RUT 26.826.618-6

________________________________

**Comment by rhernandezr0930** [comment]
Can you answer me, please.

**Comment by rhernandezr0930** [comment]
Thanks for nothing, for answers in this way, is that people prefer Xecuter.
