### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by thomleg50** [Atmosphere-NX/Atmosphere#111]
when i compile the source i'm unable to compile stratoshere and fusee secondary because of error : 

https://pastebin.com/qJqyX1mC

Can you help me please and not close that with no solution

**Comment by natehaxx** [comment]
its not even ready for the public , try to update to the latest DevkitPro  but again this is not ready for Endusers to Play with.

**Comment by thomleg50** [comment]
where the latest devkit ?

**Comment by thomleg50** [comment]
i updated but i've got this error : https://pastebin.com/Du5xCiuf

**Comment by TuxSH** [comment]
Update switch-tools too.

Closing.

**Comment by thomleg50** [comment]
ok thanks
