### ISSUE TITLE
Problem with settings/data management

### ISSUE THREAD

**Issue by Rodry295** [Atmosphere-NX/Atmosphere#1113]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

when I play 2 hours to any game I have and then I go to data management it crashes the atmosphere
### How can the issue be reproduced?

AFTER PLAYING TWO HOURS WHEN ENTERING DATA MANAGEMENT

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
2162-0002 

### System Firmware Version

X.X.X</br>
10.1.0/AMS 0.14.1/E

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
AMS 0.14.1 HEJKATE 5.3.2

### Additional context?

- Additional info about your environment:
Sorry for not putting the problem templates

**Comment by SciresM** [comment]
You did not actually fill out the template. You did not upload a crash report. Please re-open using the issue template correctly.
