### ISSUE TITLE
Idea Add ability to disable Nintendo network connectivity when atmosphere is running

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#112]
I suggest adding the ability to turn off Nintendo network connectivity while atmosphere runs to reduce chances of a ban.

**Comment by SciresM** [comment]
This is a native feature, just enable airplane mode.

**Comment by drofdoom** [comment]
Disable Nintendo network by blocking them from your network via router or firewall.

**Comment by fennectech** [comment]
That works.  But its not perfect. Ill look into it

**Comment by sonofskywalker3** [comment]
That only works if you want it permanent, and it's a pain to have to change it every time you boot back to OFW. I agree an option to block Nintendo network traffic on CFW would be a great future addition.

**Comment by fennectech** [comment]
He gets it!!

**Comment by fennectech** [comment]
Thanks for all the hard work on atmosphere.  Its going to be GREAT and you shal become our homebrew god!

**Comment by drofdoom** [comment]
But it's emunand ?

**Comment by fennectech** [comment]
Nah. We’re talking about users that want to not use Nintendo network only when using CFW   And boot into OFW to play online with a reduced risk of being banned

**Comment by drofdoom** [comment]
Use a proxy block the addresses with the port for your proxy added at the end for cfw and on ofw leave it open .

**Comment by fennectech** [comment]
That could work.  Using a second copy of your WiFi profile with no proxy and the main auto connect profile with a proxy.    But its still not perfect and just a setting obeyed when atmosphere launches by default.
