### ISSUE TITLE
Yet Another Fatal Error 0x4A2 (2162-0002) 0100000000001000

### ISSUE THREAD

**Issue by n3IVI0** [Atmosphere-NX/Atmosphere#1120]
**What's the issue you encountered?**

Atmosphere crashes as soon as you get to the Home Screen, with the above error message.

**How can the issue be reproduced?**

Good question.

I have tried using 9.2.0, 10.0.4 and 10.1.0, and AMS 13.0, 14.0 and 14.1 --> same fatal error no matter what I do.

I finally tried reverting to my oldest backup, 5.1.0, and it remains stable. Anything newer --> KEERASH!!

At the moment, I kept the SYSNAND at 5.1.0, unlinked my user account, erased all the games. It's a clean nand with nothing installed. Then I created the SD File version of EMUMMC for testing purposes.

**Crash Report**

https://gist.github.com/n3IVI0/e6c0e7175794bc02364841cf4badd91b

**System Firmware Version**

9.2.0, 10.0.4 and 10.1.0

**Environment?**

What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate 5.3.2

Official release or unofficial build: official release from github page

Do you have additional kips or sysmodules you're loading: only what came with Deepsea 1.5.1

However, I made a minimal version with SDSetup - no sysmodules, no Tesla, no overlays, only what was needed to get into homebrew --> same problem

With or without the sysmodules, I get the same crash.

I tried rolling back to 9.2.0 and running a minimalized AMS 13.0 --> same problem

I normally use only FAT32, but I tried it with both FAT and exFAT - same problem. I am using the FAT32 + exFAT firmwares.

I tried a full format (overwrite) of the SD card --> same problem

At no time has there been any custom themes, or NXTheme Installer. 

I tried keeping it in Airplane mode --> same problem

I have pored over this forum, and GBATemp. I tried all the advice I could find relevant to this crash. Nothing has worked for me. I am at a loss. My Switch is unusable in this state.

I really hope someone has a solution. I have attached the crash logs for both the 9.2.0 environment and the 10.1.0 environment.

**Comment by Grass0001** [comment]
delete the folder sd/atmosphere/contents/01000000001000

**Comment by n3IVI0** [comment]
That works, when that is the problem. That folder doesn't exist. There is no theme installed. There is no theme manager installed. I did an overwrite format to make absolutely sure. Nothing. It insists the folder is there - the folder is NOT there. I am baffled.

**Comment by Masamune3210** [comment]
Make sure it doesn't exist in the titles folder either if it still exists

**Comment by n3IVI0** [comment]
It's a clean install of Atmosphere. The new version uses /contents instead of /titles.

**Comment by n3IVI0** [comment]
If I can make it into the homebrew menu before it crashes, then I'm good, but as soon as I go back to the Home Menu or Settings, within about five seconds, I get that fatal error.

I was able to turn off Tesla and verify all sysmodules are inactive, so I don't think it's that. In any case, running a version with no sysmodules has the same effect, gets the same crash.

**Comment by n3IVI0** [comment]
It looks like uLaunch is still in pre-release, so probably too buggy to work as a replacement Home Menu. What could have borked my Home Menu, that persists in the face of different firmwares, different versions of Atmosphere, and when NO themes are installed?

**Comment by n3IVI0** [comment]
https://github.com/WerWolv/Tesla-Menu/issues/21 Might be overlays and sysmodules conflicting with AMS 14, but I tried a stripped down version of AMS 14.1 and still get the crash. This is so weird.

**Comment by n3IVI0** [comment]
I can update to 8.1.0. Everything works. No problems. If I go to 9.0.0 or higher, immediate crash. What changed from 8.1.0 to 9.0.0 that could be causing AMS to crash?

**Comment by n3IVI0** [comment]
Tried running only Atmosphere, not hekate, loaded fusee-primary. Installed 10.1.0 with Daybreak. Still crashes. Tried the same thing on the SYSNAND, in case the problem was EMUMMC - still crashes. I cannot upgrade past 8.1.0 without it crashing on the Home Menu.

**Comment by cheesycod** [comment]
Hmmm, can you try updating to 10.1.0 using ChoiDijourNX just to verify that this isnt a Daybreak issue

**Comment by n3IVI0** [comment]
Done. Both Choi and Daybreak give the same result.

**Comment by cheesycod** [comment]
Does your switch boot OFW? Have you tried using a different method of booting into CFW like using fusee-primary instead of hekate?

**Comment by n3IVI0** [comment]
Yes. I used only Atmosphere. It gave the same result. I have been using Auto RCM since 6.2.0.

**Comment by n3IVI0** [comment]
I have 7 burnt fuses, so that means I can go back to 6.0.1 right?

**Comment by cheesycod** [comment]
Yes, although you said your issue began with 9.2.0 so it might not appear on 6.0.1.

**Comment by n3IVI0** [comment]
Probably not. I stopped using OFW after I learned about burning fuses. I did make backups of every firmware I ran. The last one I had made was 9.1.0. When I restored the backup, which was working when I used it, it gave the fatal error. I can't figure what about Atmosphere could be causing this.

**Comment by cheesycod** [comment]
> Yes. I used only Atmosphere. It gave the same result. I have been using Auto RCM since 6.2.0.

Then you have 8 fuses, not 7.

**Comment by cheesycod** [comment]
Also, this should probably be in ReSwitched and not Github Issues

**Comment by n3IVI0** [comment]
I checked. It's 7. I must have started using CFW just before 6.2.0 came out. If I remember right, that was the update you needed to be able to play Smash Brothers, and I got the banhammer right before it came out.

**Comment by n3IVI0** [comment]
Whereabouts in ReSwitched?

**Comment by cheesycod** [comment]
#user-support

**Comment by n3IVI0** [comment]
Where can I get an invite?

**Comment by n3IVI0** [comment]
Found it.

**Comment by n3IVI0** [comment]
I can boot stock with zero issues. However, it is 6.01, not 9.00, so I am unsure what would happen at that level. I don't want to burn any fuses finding out. :)

**Comment by cheesycod** [comment]
IDK why QLaunch is crashing for you

**Comment by n3IVI0** [comment]
Somebody on ReSwitched suggested it could be an nvn crash (graphics driver).

**Comment by n3IVI0** [comment]
I can get into maintenance mode in 9.0.0, but as soon as it is allowed to boot normally and I get into Home Menu - crash.

**Comment by SciresM** [comment]
Crash occurs on stock using Nintendo's bootloader; seems to be hardware troubles (user mentioned graphical flickering in some game), and not an atmosphere bug.

**Comment by drofdoom** [comment]
Seems to me like he deactivate the wifi auto connect and be fine but he
might of messed it up rolling back .he needs to update fully and call it a
day he should be good after that
