### ISSUE TITLE
Fatal Error after Update to 9.2.0

### ISSUE THREAD

**Issue by Xenotia** [Atmosphere-NX/Atmosphere#1122]
### What's the issue you encountered?
Hello first of all my english is terrible. so i updated my switch from 9.0 to 9.2 without burning fuses and after that my switch shows the atmosphere logo and then fatal error .
i also tried to use sx os but no success.

### Crash Report
https://drive.google.com/file/d/1Bb40Ojcbv0ITicy6wV46gCoDRQ7MviD9/view?usp=sharing

### System Firmware Version
9.2.0

I really dont now what to do i have a nand backup and an emunand backup from sxos but nothing works

**Comment by HookedBehemoth** [comment]
ExFAT SD card without exFAT firmware.
Format the card to FAT32.

**Comment by Xenotia** [comment]
Thank you very much *.* <3
