### ISSUE TITLE
Fatal when sending payload

### ISSUE THREAD

**Issue by sk0pe01** [Atmosphere-NX/Atmosphere#1123]
I have the latest atmosphere files and fusee payload and I formatted my sd to fat32 but when I send it the screen goes black then a message pops up saying "[ERROR] Fatal error: [NXBOOT] Couldn't parse boot0: I/O error!" Also on firmware 10.1.0. Any help?

**Comment by Joe2603** [comment]
Could you solve the problem?  Cause I have the same one and I don't know what to do. And if you could then how please I need't

**Comment by SciresM** [comment]
The atmosphere issue tracker is not a support forum, it's for bugs.

seek help in the nintendo homebrew discord, or another discord like it.
