### ISSUE TITLE
(Yet Another) Fatal Error Screen

### ISSUE THREAD

**Issue by Zolrein** [Atmosphere-NX/Atmosphere#1131]
### What's the issue you encountered?
Back in July 12~13 I decided to update my emuMMC, the console was on firmware 9.0.1|AMS 0.12.0|E running from a fat32 micro SD, I proceded to download the latest firm files (10.0.4) and updated via ChoiDujourNX v102.
the Update installed correctly, then I took the sd and deleted my atmosphere, sept and bootloader folders along "reboot_to_payload.nro" from the switch folder, hbmenu.nro and "hekate_ctaer_530.bin" from the sd's root.
I downloaded the latest Atmosphere package at the time, hekate's latest one, the sigpatches and placed them in the SD as usual:
Atmosphere's > Hekate's > Sigpatches.

plugged the SD on the switch, launched the payload as usual, clicked emuMMC on hekate as usual and everything was fine, it loaded Atmosphere's splash screen and a second after it, the console crashed with this error message:

A fatal error occurred when running Atmosphere.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_000000000603d96f.bin

Press POWER to reboot

I proceded to do another clean install without success, clicked fix bit, again without success. fast forward today, I decided to give it another try, downloaded the newest Atmophere files, repeated my usual procedure (delete old folders, place new ones in order) and again I'm stuck with the same error screen (only difference being the report's number in this case "report_0000000006037a34.bin"

### How can the issue be reproduced?
A clean install keeps showing the same screen no matter what.

### Crash Report
here are both of them
report_000000000603d96f.bin
report_0000000006037a34.bin

### System Firmware Version
originally it was:
9.0.1|AMS 0.12.0|E
now it should be:
10.0.4|AMS 0.14.0

### Environment?
Atmosphere 0.14.0 + Hekate 5.3.2 Nyx

Thanks in advance
[FatalError.zip](https://github.com/Atmosphere-NX/Atmosphere/files/5113667/FatalError.zip)

**Comment by SciresM** [comment]
`fat32 micro sd` nope.

You installed non-exfat firmware but have an exfat sd card. Format your sd card as fat32, or manually flash exfat firm to package2.
