### ISSUE TITLE
Error launching games that used to start

### ISSUE THREAD

**Issue by Afrodit20** [Atmosphere-NX/Atmosphere#1135]
## Bug Report

When I install Untitled goose game, It works ok, but for one reason other games that used to run no longer open </br>

### What's the issue you encountered?

I install untitled Goose game, and after my pokemon shield and other 3 games dont start and say "the program could not be started"</br>

### How can the issue be reproduced?

I dont know, its the first time i encounter this and i odn know how to fix it</br>

### Crash Report

Only says: "the program could not be started"</br>

### System Firmware Version

hbmenu: v3.3.0</br>
nx-hbloader: v2.3.4</br>
Atmosphere: v0.14.1</br>
Nswich: v10.1.0</br>
### Environment?

I instal the untitled goose game and after we cant open the pokemon and other 3 games (Liberated, Little Missfortune, Wonderfull101)</br>

### Additional context?

I don't know how to read the report and it's the first time I get this error and I cannot get it anymore. If someone can help me I would appreciate it very much</br>

**Comment by Masamune3210** [comment]
exfat sd card or fat32?

**Comment by jinkjones** [comment]
Hello, did you manage to fix this? everytime i try to load a game it doesnt work and has the same error.

**Comment by jinkjones** [comment]
Resolved for me, redownload your sig patches from awoo installer.

**Comment by fincs** [comment]
Piracy is not supported.
