### ISSUE TITLE
Atmosphere not launching after update to OFW 10.1.0

### ISSUE THREAD

**Issue by Dhii1** [Atmosphere-NX/Atmosphere#1141]
Updated my switch to OFW 10.1.0 and ever since have been unable to launch atmosphere

Error Code: 2168-0002 (0x4a8)
Program:4200000000000010
Firmware:10.1.0 (Atmosphere 0.14.2-master-1cccb6ef)

When trying to launch the switch through hekate 5.3.2, it'll crash whether I boot it from CFW - sysMMC, CFW - emuMMC, or even using Fuslee-Primary
[01599531450_4200000000000010.log](https://github.com/Atmosphere-NX/Atmosphere/files/5185741/01599531450_4200000000000010.log)

**Comment by SciresM** [comment]
4200000000000010 is `ldn_mitm` -- as mentioned in the 0.14.2 release notes, the mitm api underwent a change that will require mitm modules to re-compile to work.

You can either:
* Temporarily use Atmosphere 0.14.1 while you wait for ldn_mitm to update.
* Delete the sd:/atmosphere/contents/4200000000000010 folder to remove ldn_mitm for now.
