### ISSUE TITLE
A fatal error occured when running atmosphere

### ISSUE THREAD

**Issue by malekalhalabi** [Atmosphere-NX/Atmosphere#1142]
I installed all the files i need and for some reason it keeps showing me this

Error id : 01000000000000008
Error desc : std: :abort() called (0xffe)
report saved to /atmosphere/fatal_errors/report_000000000664cf0.bin

press POWER to reboot

it was working fine about an hour ago until i put the sd card into my computer to download hb apps but when i tried to open my switch it kept showing this error.

**Comment by GGLinnk** [comment]
I'm not sure but I think it can be an archive bit issue, if you use hekate there is an option to fix that.

**Comment by Nthehunter** [comment]
Yeah , I have the same issue. I update atmosphere for the problem of freezing in mario 3d all stars, exactly when I out of mario 64 the console freezing. So, when I update this errors appear to me, I solved it, copy and paste the previous pack of atmosphere that I have.

I add the fatal error report:



[report_0000000006560c59.zip](https://github.com/Atmosphere-NX/Atmosphere/files/5245551/report_0000000006560c59.zip)

**Comment by SciresM** [comment]
Closing because the original issue creator didn't use the issue templates or upload a report. Reopen using them.

@Nthehunter re-extract latest atmosphere zip. You overwrote part of atmosphere with an outdated copy of mission control.
