### ISSUE TITLE
A fatal error occurred 

### ISSUE THREAD

**Issue by juzzash** [Atmosphere-NX/Atmosphere#1143]
![6A5FD889-FFFE-432C-8485-A17963A392CA](https://user-images.githubusercontent.com/58756437/93158349-462c3200-f74f-11ea-825f-a4fae16582b7.jpeg)

Attached is the error I’m getting when trying to launch atmosphere. Please see below details... any help as to why it’s not launching at all?

Switch firmware 10.2.0
I’ve tried both atmosphere 0.14.3 & 0.14.2
128 GB SD, formatted to exFAT

I payload it using fusee-gelee.firebaseapp.com/# and the fusee-primary.bin file that comes with atmosphere.
The only nro I use is EdiZon and Checkpoint. 

i just cant work out how to upload the report file because github is telling me the file type isnt supported

**Comment by SciresM** [comment]
Upload the report file as a zip, or to some other filehost then link it here.

**Comment by juzzash** [comment]
Actually, worked it out thanks to a previous post! 
I connected the SD to my pc, highlighted all files and folders except Nintendo, and turned off the archive. It now boots properly!
