### ISSUE TITLE
Does Atmosphère 0.14.3 include exfat driver?

### ISSUE THREAD

**Issue by zsw12abc** [Atmosphere-NX/Atmosphere#1144]
After I update to Atmosphère 0.14.3,
an error shows that 
SD card is exfat and installed hos driver only supports fat32 
failed to launch hos
Does that mean Atmosphère 0.14.3 still not support exFAT yet?

**Comment by SciresM** [comment]
You can't boot via hekate until hekate is updated.

Atmosphere itself supports exFAT totally fine, this was tested prior to release.
