### ISSUE TITLE
Help :c

### ISSUE THREAD

**Issue by Takachairo1** [Atmosphere-NX/Atmosphere#1149]
[report_0000000005a8a187.txt](https://github.com/Atmosphere-NX/Atmosphere/files/5229278/report_0000000005a8a187.txt)

**Comment by Takachairo1** [comment]
a fatal error occurred when running atmosphere 
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe

**Comment by SciresM** [comment]
You installed non-exfat firmware but have an exfat sd card. Format your sd card as fat32, or manually flash exfat firm to package2.
