### ISSUE TITLE
Daybreak hangs at 0%

### ISSUE THREAD

**Issue by Abbotta4** [Atmosphere-NX/Atmosphere#1151]
### What's the issue you encountered?

Daybreak hangs at 0% while trying to upgrade EmuMMC from 10.0.2 to 10.2.0

### How can the issue be reproduced?

I followed the steps [here](https://nh-server.github.io/switch-guide/extras/updating/) to dump firmware from my SysMMC and used that update data with Daybreak to try to update to 10.2.0. I get through all of the beginning dialogs, but Daybreak hangs for me at:
"Installing update
0% complete
Beginning update setup...
Update setup complete.
Preparing update..."

### Crash Report

N/A

### System Firmware Version

10.2.0 OFW
10.0.2 CFW

### Environment?

bootloader: Hekate 5.3.3 from release page

### Additional context?

N/A

**Comment by SciresM** [comment]
I sincerely doubt it hangs, having used daybreak to update to 10.2.0 the other day.

However, in emummc the initial Preparing Update phase can take up to a minute or two before it actually begins installing. 

Be patient.

**Comment by djshrimper** [comment]
Did you manage to get past this? It's happening to me aswell trying to update from 10.0.2

**Comment by Awalsh053** [comment]
for me it sat a 0% for about half hour then jumped to 80% just be patient
