### ISSUE TITLE
3D all stars crash

### ISSUE THREAD

**Issue by cheesycod** [Atmosphere-NX/Atmosphere#1153]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
Press minus and try to close super Mario 64. This crashes the switch and appears to be an atmosphere issue
[ Did you make any changes related to Atmosphère itself? ]</br>
Yes, sigpatches (I know piracy is not supported but it’s the only way to actually see the error which will 99.99% happen on the proper eshop release as well)
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?
1. Open Super Mario 3D All Stars
2. Open Super Mario 64
3. Click pause after the game loads and click return to title screen
4. 50% chance it will crash the whole switch and a complete shutdown and turn back on is needed (reboot doesn’t work)
[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>
None are created
### System Firmware Version
10.1.0 and 10.2.0
X.X.X</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Official release version x.x.x (or) unofficial build ] Official Atmosphere 0.14.3
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: [ * ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Known issue, piracy isn't supported. I'll get a cartridge today and fix it.
