### ISSUE TITLE
Looking for an updated version of the hbmenu loader for 5.1.0

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#116]
It was showin in this tweet https://twitter.com/sciresm/status/1002062352387260418?s=21. I’m willing to take the risk to get my save data restored. (I have it backuped up with checkpoint) but it got deleted in the game because of me reaching behind the tv to plug in my sound winding up pushing the right combination of buttons on my controller to erase my save.   Thanks for the help.

**Comment by yellows8** [comment]
Build yourself -> https://github.com/switchbrew/nx-hbloader

**Comment by fennectech** [comment]
THANK YOU FROM THE BOTTOM OF MY HEART!

**Comment by fennectech** [comment]
Doesn’t load after compiling.  Same issue as the distributed build.

**Comment by SciresM** [comment]
Not an issue in Atmosphere, and can't provide support at present.

**Comment by fennectech** [comment]
Ok   if you get time id appreciate a copy of the one that works on 5.1.0
