### ISSUE TITLE
Game specific bug:Super Smash Bros Ultimate

### ISSUE THREAD

**Issue by xPvtPancakes** [Atmosphere-NX/Atmosphere#1163]
when trying to launch into a normal smash match, the game hangs before going into the loading screen and never moves to the next preview of the fighters.

Other modes are still working such as century smash and home run contest, but normal smash and squad strike are not working.

For troubleshooting, I've tried rebooting, updating sig patches, reinstalling atmosphere, reinstalling smash and all DLCs, moving smash from SD to NAND. I have switched back to 0.10.13 for now, and boots correctly after reinstalling 0.10.13

**Comment by SciresM** [comment]
reopen using the issue templates.
