### ISSUE TITLE
Fatal error title ID 0100000000000001 when opening hbmenu

### ISSUE THREAD

**Issue by slickrasta** [Atmosphere-NX/Atmosphere#1165]
I keep getting the fatal error on title ID 0100000000000001 everytime I launch hbmenu (select Album) on the newest Atmosphere version. 

Currently on FW 9.0 and Atmosphere 0.9.4 and works fine with payload Hekate 5.0.2 including hbmenu with no issues. All I'm trying to do is update to FW 10.2.0 via Daybreak so I can play my physical copy of All-Stars. Tried deleting atmosphere/sept/switch folders and putting fresh files. Even tried with a brand new SD card formatted to FAT32 with only the atmosphere files on it literally nothing else, exact same error every time I try to open hdmenu on new Atmosphere version using the fusee primary payload. Tried Hekate archive bit fix already as well. I feel like I'm losing my mind I've tried so many things and am completely baffled how it can even happen on a brand new SD card with no other files whatsoever. Please help me.

Bin from current SD:
[report_00000000265510bc (current sd).zip](https://github.com/Atmosphere-NX/Atmosphere/files/5259519/report_00000000265510bc.current.sd.zip)
Bin from brand new SD: 
[report_00000000179ec795 (brand new sd).zip](https://github.com/Atmosphere-NX/Atmosphere/files/5259527/report_00000000179ec795.brand.new.sd.zip)

![image0](https://user-images.githubusercontent.com/28207695/93851101-60d93c00-fc64-11ea-9f72-f3261731be82.jpeg)

**Comment by SciresM** [comment]
Please re-open using the issue templates.
