### ISSUE TITLE
breath of the wild and ssbu stuck on black screen

### ISSUE THREAD

**Issue by Anxietytimmy** [Atmosphere-NX/Atmosphere#1167]
After updating to atmosphere 14.4 breath of the wild hangs on a black screen and ssbu works but after going to start a match the game just hangs on a black screen. I am in ofw 10.2. Tried reinstalling nsp,reinstalling atmosphere. using hekate to boot ams. any ideas?

**Comment by SciresM** [comment]
re-open using the issue templates.

Also, piracy is not supported.
