### ISSUE TITLE
Unable to access microSD error after updating

### ISSUE THREAD

**Issue by jlmontie** [Atmosphere-NX/Atmosphere#1170]
I just updated to the latest release and suddenly got this error.

> Error Code: 2016-0247
> Unable to access microSD card.
> Please turn off the console and reinsert the microSD card.

I am using these sigpatches.
https://gbatemp.net/threads/sigpatches-for-atmosphere-fusee-primary-only.567542/
What am I doing wrong?

**Comment by SciresM** [comment]
1) You didn't use the issue templates
2) Piracy is not supported
3) Try reformatting your SD card, or just rebooting.
