### ISSUE TITLE
Pokomon sword and shield freezing on Atmosphere 14.4

### ISSUE THREAD

**Issue by KaliXD** [Atmosphere-NX/Atmosphere#1171]
I installed the latest ams update after the update I wanted to play pokomon sword and noticed that the game was frozen I tried to downgrade ams from 14.4 to 14.1 as I did that, Pokemon Sword worked normally again 

Info:
Payload: fusee primary
Switch version:10.0.2
Emummc

**Comment by fincs** [comment]
Cannot reproduce. Make sure you don't have third party sysmodules compromising the stability of your system.

Also, please reopen using the issue templates.
