### ISSUE TITLE
Remove wifi IC check.

### ISSUE THREAD

**Issue by musiccankill** [Atmosphere-NX/Atmosphere#1179]
#### Overview:
-Bypass check of wifi IC on boot</br>

#### Smaller Details: 
- If the wifi IC (hardware component) has failed, there is no way to boot into horizon so maybe you can disable the check and allow it to boot even if the component is faulty/missing.</br>

### What component do you feel this would best fit within?
- [Exosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Fully-featured custom secure monitor.</br>
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>

### Why would this feature be useful?
A working console even without working wifi is better than a brick console, so users with faulty wifi ICs will benefit from that.</br>
Consoles with this problem need a wifi IC from a nintendo switch donor board as far as i know as commercial replacements will not work (possibly custom firmware in the wifi IC?).

**Comment by SciresM** [comment]
This sounds like it would involve heavy editing to wlan sysmodule.

I don't know how you would do this, but I would happily accept a pull request to add the patches for this feature.

**Comment by ktysol** [comment]
I know this has been closed before, and I have no experience to do this myself, but I think this could really useful and prevents needing a donor board for a dead wifi chip! Just wanted to comment to see if any of the (amazing, by the way) devs want to look at it

**Comment by hexkyz** [comment]
This actually sounds like a good solution to workaround faulty hardware. Having reverse engineered a good portion of wlan in the past, I'll re-open this while I investigate if it's doable.

**Comment by Hitori638** [comment]
This would be really helpful in my case. My console wont boot into OFW or CFW because of a partially failing chip. Bluetooth still works but WiFi does not. I am happy to help with testing or provide any info or logs if that would be useful.

**Comment by clearmoon247** [comment]
I also have a switch with a bad wifi chip that can successfully boot into Android. It would be very helpful to use a more native os to play offline games
