### ISSUE TITLE
Fatal error while trying to run atmosphere

### ISSUE THREAD

**Issue by shoaley** [Atmosphere-NX/Atmosphere#1182]
Atmosphere version: 0.14.4
Switch version: 10.2.0

I received a fatal error that read:
Title ID: 010000000000002B
Error: std::abort (0xffe)

Attached is the corresponding report
[report_07b35c5b.zip](https://github.com/Atmosphere-NX/Atmosphere/files/5344192/report_07b35c5b.zip)

**Comment by SciresM** [comment]
1) You did not use the issue templates

2) You somehow set the archive bit on the /atmosphere or /atmosphere/erpt_reports folder.

Fix this, and atmosphere will be fine.
