### ISSUE TITLE
Fatal Error Occurred When Running Atmosphere 

### ISSUE THREAD

**Issue by beaniemachinie** [Atmosphere-NX/Atmosphere#1187]
## Bug Report
I've been working on homebrewing my switch all day, but I cannot get Atmosphere to load no matter what I do. I've tried deleting and re-extracting and everything under the sun, but no matter what I do it just does not work. 

### What's the issue you encountered?

Whether I inject the hekate payload or fusee-gelee payload, I cannot load in Atmosphere. It brings up all the logos like it's going to, but then it goes to a black screen that says: 
A fatal error occurred when running Atmosphere.
Title ID: 010000000000002b
Error Desc: std: :abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_00000000080b5963.bin

### How can the issue be reproduced?

Inject Hekate/ fusee-gelee payload through RCM 
Attempt to launch through hekate CFW

### Crash Report

I don't have the crash report (because I deleted my files to go back on my switch) but if ou need one I can do it again 
### System Firmware Version

Firmare is version 10.2.0

### Environment?

I used the most recent versions of both hekate and Atmosphere straight from github, along with TegraRCMgui 

### Additional context?

I've already reformatted my SD card to FAT32 from exFAT, but that did not solve the issue of Atmosphere not loading.

**Comment by HookedBehemoth** [comment]
The crash report is very much needed to diagnose this issue.

**Comment by beaniemachinie** [comment]
Cool beans. I’ll go ahead recreate it and post it

**Comment by carcaschoi** [comment]
https://github.com/Atmosphere-NX/Atmosphere/files/5273156/atmosphere-0.14.4-erpt-fix.zip

unzip to your SD card

**Comment by beaniemachinie** [comment]
Well, I went ahead and reloaded everything to try and recreate my issue but now it's loading fine?? I'm gonna leave this thread open just in case something else happens

**Comment by SciresM** [comment]
I'm gonna close this because there's no unresolved issue.
