### ISSUE TITLE
SD card issues

### ISSUE THREAD

**Issue by MYSTlKO** [Atmosphere-NX/Atmosphere#1189]
### What's the issue you encountered?

I got several SD card problems after updating to the new official atmosphere.
It crashes during playing games like Animal Crossing or Super Mario 3D Allstars, because of SD card issues. 

### How can the issue be reproduced?

Seems to be random.

### Crash Report
 No report because can't write to SD I guess 

### System Firmware Version

10.2.0

### Environment?

Fusee let me boot into atmosphere, but crashes after several minutes,
Hekate even doesn't recognize the SD card

**Comment by SciresM** [comment]
Sounds like SD card issues/hardware issues, not like atmosphere issues.

Get a new SD card?
