### ISSUE TITLE
Atmosphere doesnt start up with 10.2.0 Exfat

### ISSUE THREAD

**Issue by disturbia96** [Atmosphere-NX/Atmosphere#1190]
hello, i recently updated my switch to 10.2.0 eXfat  and i have A.M.S 14.4. but now if i start up the AMS i get this error code:

Title ID: 010041544d53000
Error desc: std::abort()called (0xffe)
report saved to atmosphere/fatal_errors/report_0000000005F65ae9.bin

when i updated my switch with exfat32 my installed games didnt work, so i tried to install it with exfat and afterthat i keep getting this error.

does any one know how to fix this?
im desperate.. thanks!

**Comment by SciresM** [comment]
1) you did not use the issue templates
2) you did not upload the report binary. 

Please re-open using the issue templates, and with your report binary included.
