### ISSUE TITLE
Fatal error 0100000000000005 when booting sysMMC

### ISSUE THREAD

**Issue by Plop** [Atmosphere-NX/Atmosphere#1192]
## Bug Report

When launching sysCFW from Hekate

### What's the issue you encountered?

When using Hekate for launching sysMMC, it shows an error and I have to reboot.

### How can the issue be reproduced?

Launch Hekate. Click on Launch. Clic on CFW (sysMMC). Fatal error incoming.

### Crash Report

Didn't find crash report but there are multiples bin reports :

http://www.mediafire.com/file/w4za4152f2tl1ze/report_0000000000e77777.bin/file

http://www.mediafire.com/file/f4csi611ftw2v1r/report_0000000000e7de5f.bin/file

### System Firmware Version

10.2.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: 
  - Official relese v5.3.3
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: 

![IMG_20201020_223306](https://user-images.githubusercontent.com/876470/96650681-8fb20300-1333-11eb-80f8-2974d1aaa1c5.png)

**Comment by SciresM** [comment]
A partial update was improperly performed.

To fix, try manually flashing latest package2 to MMC.

For help doing this, seek support in the Nintendo Homebrew or ReSwitched discoed servers.
