### ISSUE TITLE
Multi-mod selection

### ISSUE THREAD

**Issue by MarioPossamato** [Atmosphere-NX/Atmosphere#1197]
#### Overview:
Allow the user to store multiple mods in their `sd:/Atmosphere/contents/<titleid>` folder, and install them like SDCafiine on the Wii U.
```
                  .: Atmosphere :.

Select your option, then press the A key to launch.

-> sd:  Mod 1
   sd:  Mod 2
   sd:  Mod 3
   sd:  Mod 4
   sd:  Mod 5
   sd:  Mod 6
   sd:  Mod 7
   sd:  Mod 8

Page 1/2, press L/R to change.
```

#### Smaller Details: 
The way it would work, is basically the same as SDCafiine, but with different folder names:
```
sd:
└───Atmosphere
    └───contents
        └───<titleid>
            ├───Mod 1
            ├───Mod 2
            ├───Mod 3
            ├───Mod 4
            ├───Mod 5
            ├───Mod 6
            ├───Mod 7
            ├───Mod 8
            ├───Mod 9
            ├───Mod 10
            ├───Mod 11
            └───Mod 12
```

### Why would this feature be useful?
It will allow users to store multiple mods on their SD card, and install them to their games without the hassle of going through the process of manually swapping them.

I searched through the feature requests, and didn't find any requests for this.  I don't know if it or something similar has been already implemented, but I couldn't find any info about it.

Also, I didn't realize that accidentally pressing `CTRL + ENTER` posts your issue before it is ready :)

**Comment by masagrator** [comment]
PS: there is homebrew for it

https://github.com/nadrino/SimpleModManager

**Comment by SciresM** [comment]
Yeah, this is something a user homebrew can do without needing atmosphere support.
