### ISSUE TITLE
won't boot into Hekate

### ISSUE THREAD

**Issue by manaboy** [Atmosphere-NX/Atmosphere#1198]
### What's the issue you encountered?

After replacing the atmosphere folder with the lates build of atmosphere. from pagesope I can not boot into Hekate, system boots directly to atmosphere cfw, also launching Reboot to Payload from HBL boots atmosphere. Trying to boot any software gives "can not start the software" error.

What I did.

I updated my emmcnand with daylight to 10.2.0 and I replaced the atmosphere folder with the files from the latest build. Everything worked fine in AMS 0.13.0

**Comment by fincs** [comment]
A few things:

- This is the Atmosphère issue tracker. This is not the place to report issues about Hekate, which is a separate project.
- It looks like most of the issue template was deleted when you made your post. Next time please fill it out completely.
- The error you're getting ("cannot start the software") suggests to me that this is a piracy related issue. Piracy is not supported.
