### ISSUE TITLE
Decide on a moderate to long-term custom sysmodule plan.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#12]
It'll be a while before this is urgent, but we should figure out what sysmodules we'd like to potentially re-implement/what kinds of custom services/API we'd like for our cfw to provide to the user and user homebrew.

**Comment by TuxSH** [comment]
I think it should be (3.0+ ?) loader, sm and boot at first.

A custom sysmodule seems like a nice idea as well.

**Comment by SciresM** [comment]
Yeah, I think I agree with that. Those are all _very_ light.

From an extensibility perspective, I also think we might want to tackle NCM in the moderate term. I'd be happy to take that one on, I'm very familiar with how NCM works on the inside.

**Comment by MRiCEQB** [comment]
If you don't reimplement golf, you can basically stop the entire project imho.

**Comment by Swiftloke** [comment]
I understand you were memeing, but nonetheless, that would be distribution of copyrighted content (the Golf ROM) and thus highly illegal.

**Comment by asiekierka** [comment]
@Swiftloke Nobody said they have to redistribute the golf ROM; a custom implementation of a golf game would probably be sufficient.

**Comment by SciresM** [comment]
Targeted for initial release:
sm, loader, boot. boot2?

Targeted for after initial release:
boot2? SPL, PM, NCM.

Custom sysmodules that may be desirable:
mitm (framework for man-in-the-middle attacking other services)
layeredfs (RomFS framework, based around mitm)
