### ISSUE TITLE
issue with build

### ISSUE THREAD

**Issue by thomleg50** [Atmosphere-NX/Atmosphere#120]
when i try to compile i've got error : https://pastebin.com/bC5EJJBA
can you help me or try please

**Comment by pplatoon** [comment]
I also always get similar mistakes

**Comment by thomleg50** [comment]
how to solve that ?

**Comment by atkinchris** [comment]
Live discussion on build issues, where it's possible that it's a user specific error, might be best done on Discord. Issues really should only be raised once basic troubleshooting and triage has been completed.

**Comment by borntohonk** [comment]
https://github.com/Atmosphere-NX/Atmosphere/blob/master/fusee/fusee-primary/src/main.c#L119-L124

Here's how to deal with the issue @thomleg50

**Comment by TuxSH** [comment]
Fixed.
