### ISSUE TITLE
Increase slots for title override 

### ISSUE THREAD

**Issue by cucholix** [Atmosphere-NX/Atmosphere#1203]
Currently there’s 8 slots to assign title ID and button to override game with hbmenu [0 to 7], would it possible increase these slots? 

It would be useful if you are using modified hbmenu that allows boot .nro homebrews directly from HOS menu, like a forwarder.

**Comment by HookedBehemoth** [comment]
Maybe HBL override could be moved to the program specific ``config.ini`` instead since it's already parsed on every launch.

**Comment by SciresM** [comment]
What use case requires more than eight configs?

For memory related reasons the limit must be a fixed number and not dynamic.

**Comment by fincs** [comment]
Also fwiw hbmenu is not meant to be bypassed. "Forwarders" are explicitly not a supported use case in nx-hbloader.
