### ISSUE TITLE
Games which you select the profile ingame, now freezes

### ISSUE THREAD

**Issue by matheusstaffa** [Atmosphere-NX/Atmosphere#1204]
### What's the issue you encountered?

I was playing some games which asks you to select the profile inside the game and the profile select screen doesn't appear making the game freeze. This games was working on atmosphere 0.14.4 official
Games tested: shantae half-genie hero ultimate edition. Arcade Archives MARIO BROS. Arcade Archives VS. SUPER MARIO BROS.

### How can the issue be reproduced?

1) Select any game mentioned above.
2) On title screen press the button prompt the game says to begin.
3) Game freeze but not crashes.

### Crash Report

N/A

### System Firmware Version

10.2.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusèe
- Official release or unofficial build: Official release version 0.15.0
- Do you have additional kips or sysmodules you're loading:  sys-clk, sys-ftpd-light, Tesla, SaltyNX, emuiibo, ldn_mitm.
- Homebrew software installed: HB App Store, GoldLeaf, Retroarch, sys-clk manager 1.0.0, edizon SE, Salty NX.
### Additional context?

Using latest atmosphere 0.15.0 + latest fusèe-primary + latest signpatches
It was working on atmosphere 0.14.4.

**Comment by fincs** [comment]
> GoldLeaf

> latest signpatches

Piracy is not supported.
