### ISSUE TITLE
Atmosphere crashes when trying to vinculate account in LibraryAppletLoginShare 

### ISSUE THREAD

**Issue by StartForKillerMC** [Atmosphere-NX/Atmosphere#1211]
### What's the issue you encountered?

When i try to vinculate the Nintendo Switch to Nintendo the LibraryAppletLoginShare app crash</br>

### How can the issue be reproduced?

Currently is a bit difficult but it's possible. My switch is banned and i've recreated the account server by myself, so, if anyone needs the code of the server to try this send me a request, you only need a proxy to redirect the nintendo url to your own pc.</br>

### Crash Report

https://gist.github.com/StartForKillerMC/37e3ced0ff663b174899176880c0e8ad</br>

### System Firmware Version

10.0.4</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: Official release version 0.14.3
- Do you have additional kips or sysmodules you're loading: Not at this moment
- Homebrew software installed: None/ Not relevant here

### Additional context?

N / A

**Comment by SciresM** [comment]
Not an atmosphere bug. That's assertion failure in the share app.
