### ISSUE TITLE
A fatal error occured when running Atmosphère

### ISSUE THREAD

**Issue by ac2pic** [Atmosphere-NX/Atmosphere#1216]
### What's the issue you encountered?

Program ID: 0100000000000002
Error Desc: std::abort() called (0xffe)

### How can the issue be reproduced?

Send `fusee-primary.bin` payload with TegraRCMGUI (2.6).

### Crash Report

https://gist.github.com/ac2pic/063d6fe975f0c599892eda81545925e8

### System Firmware Version

3.0.2 </br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusèe
- Official release Atmosphère 0.15.0
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: None

### Additional context?

- Using official version 0.8.4 does not give this error.
- microSD 64GB FAT32 formatted

**Comment by SciresM** [comment]
This is a known bug which was fixed yesterday, after another user triggered it. 

Wait for AMS 0.16.0, or contact SciresM#0524 on discord for a workaround/fix in the meantime.
