### ISSUE TITLE
11.0.0 erpt changes

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#1218]
Right now erpt is updated for the new ABIs, but the new context tracking logic is not yet implemented.

The new logic for tracking resource limit limit + peaks is also not yet done.

We should implement it, so that we're more accurate.

This is relatively low priority though, and should be done after 0.16.0/initial 11.0.0 support.

**Comment by ThePsycrow** [comment]
This issue (by itself at least) wouldn't cause the Switch to get "dirty" in a way that there's a ban risk when switching off of Atmosphere back to the default operating system, would it?

**Comment by Just8n12** [comment]
Can I restore if my backup file missing few rawn file?

**Comment by Just8n12** [comment]
:( my switch is currently banned from nintendo when i clicked on update software. Now my frimeware is 11.0 and my switch is banned. What a nice life :(

**Comment by Masamune3210** [comment]
One, these comments don't go here, please stop. 
Two, you always risk getting banned when using cfw, the expectation should be getting banned, not the abnormality

**Comment by cwsb69** [comment]
All i want for Christmas is i can play my switch nsp again, on firmware 11.0.0 :(
