### ISSUE TITLE
Fatal Error: [NXBOOT] Unable to identify package1!

### ISSUE THREAD

**Issue by Santiav90** [Atmosphere-NX/Atmosphere#1219]
### What's the issue you encountered?

So I tried to inject tha fusee-primary payload like always but now its giving me the Fatal Error: [NXBOOT] Unable to identify package1!

I tried to erase everything and reinstall atmosphere with the latest version and it still gives me the same error

### How can the issue be reproduced?

In my case, try to upload a payload

### Crash Report

It hasn't generated any reports, it doesn't even initialize atmosphere

### System Firmware Version

X.X.X</br>

It is updated to the latest version as of 1/12/2020 (december 1st)ºº

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Fusee-primary
- Official release or unofficial build: official version 15 (latest)
- Do you have additional kips or sysmodules you're loading: no, just loading atmosphere and nothing else
- Homebrew software installed: nothing else

### Additional context?

Nothing more to add, as I am trying to install atmosphere from 0 but it is not working

**Comment by SciresM** [comment]
11.0.0 released yesterday and isn't supported yet.

Wait for support, or restore a backup you made prior to updating.

**Comment by Santiav90** [comment]
why did my issue get closed?

**Comment by Santiav90** [comment]
ok thanks

**Comment by Zeyzers** [comment]
> 11.0.0 released yesterday and isn't supported yet.
> 
> Wait for support, or restore a backup you made prior to updating.

How long does it usually take?

**Comment by SciresM** [comment]
approximately negative five minutes from when you posted that.
