### ISSUE TITLE
Boot Process Log_level

### ISSUE THREAD

**Issue by Kai-Beast223** [Atmosphere-NX/Atmosphere#1223]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?
I'm trying to use the log_level = 5 to give onscreen debug info of loading stages for the switch. It is not providing on-screen info as it should.

### How can the issue be reproduced?
[config]
log_level = 5 in bct.ini in my atmosphere config folder. Then what I do is put the sd card back in my switch and boot and it isn't providing any debug information on boot. 

### System Firmware Version

10.2.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
Hekate official 5.3.4
Atmosphere both 0.15.0 both version Mesosphere and Non-Mesosphere have the same occurrence
- Do you have additional kips or sys modules you're loading: Ftpd
- Homebrew software installed: Checkpoint, gold leaf(Just for sd card management)

### Additional context?
I am using fss0 boot method not fss0:
also, I'm confused about using the boot_logo.bmp as well but am not sure where to ask for support on the matter.
Thank you -kai

**Comment by SciresM** [comment]
Log level is configuration for fusee primary.

You are booting via hekate.
