### ISSUE TITLE
boot2 flag presense in folder 010000000000bd00 causes a fatal error on boot

### ISSUE THREAD

**Issue by SoulBlast35** [Atmosphere-NX/Atmosphere#1224]
## Bug Report

[  ]</br>
[]</br>

### What's the issue you encountered?
Upon booting, the Switch logo will appear for half a second before going to a fatal error
[  ]</br>
Simply Updating Atmosphere to 0.16
[  ]</br>
No
[  ]</br>
N/A

### How can the issue be reproduced?
Having "boot2" in the flags folder of 010000000000bd00 in "contents" causes it. Im not sure what program ID this is
[  ]</br>
[ ]</br>
N/A

### Crash Report

[  ]</br>
[  ]</br>
[ . ]</br>
All that was generated was a fatal error report, not a regular crash report

### System Firmware Version

11.0.0</br>
[  ]</br>
[  ]</br>
[  ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
Official
Unsure about kips, however I know that I have MissionControl and sys-con installed, along with ftpd-lite
- Homebrew software installed: [ ]

### Additional context?

- Additional info about your environment:
- []
N/A

**Comment by DevYukine** [comment]
This is an issue with `MissionControl` not with Atmosphere, you should remove it and wait for them to update for latest atmosphere changes. (for reference the boot2 file in the flags folder marks it to autostart on boot)

**Comment by SoulBlast35** [comment]
Right, gotcha.
