### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by Gilgn** [Atmosphere-NX/Atmosphere#1227]
I'm having trouble trying to use atmosphere. Every time I run it I keep getting this error "[ERROR] Fatal error: [NXBOOT] Couldn't parse boot0: Illegal byte sequence!   Press POWER to reboot" and every time I do press the power button I keep getting this same message. I don't know what to do, did I install something wrong or am I missing something. Please Help!

**Comment by SciresM** [comment]
You're using hekate, which hasn't been updated for 11.0.0: use fusee primary or wait for a hekate update.

**Comment by SciresM** [comment]
Wait, misread. Reopen using the issue templates though because I need more information.

**Comment by Gilgn** [comment]
> Wait, misread. Reopen using the issue templates though because I need more information.

How do I do that?

**Comment by SciresM** [comment]
Make a new issue. Fill out the template instead of deleting it, like you did.

**Comment by Gilgn** [comment]
> Make a new issue. Fill out the template instead of deleting it, like you did.

How do I do that? 😥

**Comment by SciresM** [comment]
Use PC and not mobile.
