### ISSUE TITLE
Error when opening Tinfoil and game

### ISSUE THREAD

**Issue by Just8n12** [Atmosphere-NX/Atmosphere#1228]
I currently updated lastest version of Armosphare but I can't run Tinfoil or any games on my switch

**Comment by peterbgaming** [comment]
> I currently updated lastest version of Armosphare but I can't run Tinfoil or any games on my switch

Same problem here, i think, maybe, its a issue whit the sigpatches

**Comment by Masamune3210** [comment]
Don't ask for help with piracy

**Comment by BakedBit** [comment]
> I currently updated lastest version of Armosphare but I can't run Tinfoil or any games on my switch

I used the prerelease of of the cfw to downgrade back to 10.2.0 using choidujour so I can run my xci of smash and that worked for me

**Comment by Just8n12** [comment]
@BakedBit How did you downgrade your firmware, I did not backup my Switch on 10.2.0

**Comment by SciresM** [comment]
Piracy is not supported.
