### ISSUE TITLE
the program could not be started, try again from the home menu

### ISSUE THREAD

**Issue by peterbgaming** [Atmosphere-NX/Atmosphere#1229]
Also my switch cant read the cartridge slot, i think is something related to the sigpatches of the new versión, some anyone can help me please???!!! Thnx

**Comment by Just8n12** [comment]
Same problem here :(

**Comment by Masamune3210** [comment]
Don't ask for help with piracy

**Comment by SciresM** [comment]
@peterbgaming 
1) please use the issue templates
2) piracy is not supported
3) disable the nogc patches if you want to use gamecards and are willing to burn lotus fuses.
