### ISSUE TITLE
could not start the software 

### ISSUE THREAD

**Issue by flooki000** [Atmosphere-NX/Atmosphere#1230]
Also my switch cant read any game  i think is something related to the new version any help ??

**Comment by Szymad** [comment]
Same on my end. Tried to play with BCT.ini and sigpatches, nothing works actually. I am unable to start anything.

**Comment by Skonikol** [comment]
1. Wait for es, fs, and ldr patches to appear.
2. Piracy is not supported. You won't find it here.

**Comment by fincs** [comment]
Piracy is not supported.
