### ISSUE TITLE
Switch can't turn on without SD card

### ISSUE THREAD

**Issue by Just8n12** [Atmosphere-NX/Atmosphere#1231]
I updated my switch to 11.0 and use atmosphere 16.0
After i did it. I downgraded my switch to 10.2.0 used Choidujour

And now I still can turn on my switch with a SD card inside but when I take it out my switch can't turn on, it's like my switch missing the firmware and maybe firmware was moving to SD card, please help

**Comment by masagrator** [comment]
Atmosphere doesn't support ChoiDojourNX and is against using it becsuse of nontrivial chance in data corruption.

**Comment by fincs** [comment]
Friendly reminder that Daybreak exists.

**Comment by Just8n12** [comment]
Any changes to fix it, now it's like my switch it's dead without sd card, btw I have my backup file but could it work?

**Comment by masagrator** [comment]
If you have full backup, restoring it should help.

**Comment by SciresM** [comment]
Atmosphere does not support booting without the ads card.

Also, you did not use the issue templates.

**Comment by Just8n12** [comment]
i tried to restore my switch with a backup file and it seems like it is not working, my system firmware is disappeared. Please help me out, because if my SD card broke or something I won't able to use my switch anymore?

**Comment by SciresM** [comment]
Fill out the issue templates. More context is needed.
