### ISSUE TITLE
Game Cards are not recognized in CFW and System boots up very slowly

### ISSUE THREAD

**Issue by Roxas2712** [Atmosphere-NX/Atmosphere#1232]
Hello,

I've updated to the new Atmosphere Version. First of all - thank you for your great work.

The issue: Original Gamecards are not recognized in CFW-Mode. 
Also CFW is taking very long to boot up now. Even  when booting the OFW , aslong as CFW SD Card is insert, its very slow or not even coming up.

I would be very glad if you can fix these issues.

Thank you =)

**Comment by fincs** [comment]
11.0 updated the gamecard reader's firmware. If you're willing to burn its fuses (meaning you cannot go back to a previous version of OFW), add `nogc = 0` to atmosphere/config/BCT.ini.

Also, you didn't use the issue template.
