### ISSUE TITLE
My switch missing system Firmware and only turn on with a SD card running Atmospahere system

### ISSUE THREAD

**Issue by Just8n12** [Atmosphere-NX/Atmosphere#1234]
- I updated my switch to 11.0 and use atmosphere 16.0 After I did it
- After that, I downgraded my switch to 10.2.0 used Choidujour
- 
- And now I still can turn on my switch with an SD card inside but when I take it out my switch can't turn on,
- it's like my switch missing the firmware and maybe firmware was moving to SD card,
- please help

## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ] " I have the backup file for my switch"
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
"- I updated my switch to 11.0 and use atmosphere 16.0 After I did it
- After that, I downgraded my switch to 10.2.0 used Choidujour 
- And now I still can turn on my switch with an SD card inside but when I take it out my switch can't turn on,
- it's like my switch missing the firmware and maybe firmware was moving to SD card,"

[ Did you make any changes related to Atmosphère itself? ]</br>
"NO"
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

X.X.X</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Official release version 10.2.0 (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ 16.0 ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
You did not fill out the template. Fill out the template.
