### ISSUE TITLE
BlackScreen

### ISSUE THREAD

**Issue by gdicaterina** [Atmosphere-NX/Atmosphere#1235]
## Bug Report
When i inject the payload (fusse_primary.bin) i see NintendoSwitch logo then BlackScreen

i used the guide (https://nh-server.github.io/switch-guide/user_guide/emummc/making_emummc/) in the part when tell inject the payload

### System Firmware Version

11.0.0

Best regards!

PD: Thanks for doing this and support. Are the best team!!

**Comment by SciresM** [comment]
Re-open using the issue templates.

**Comment by gdicaterina** [comment]
sorry
