### ISSUE TITLE
Black Screen after Atmosphere Launch

### ISSUE THREAD

**Issue by AniissB** [Atmosphere-NX/Atmosphere#1238]
Good morning all

Following the release of Atmosphere 16.0 to run the switch 11.0 version, I have a black screen and I cannot access the main screen with the selection of games.

I have updated my files and my USB key with the fusee primary.bin file

The console is launched perfectly with the Atmosphere logo, recognizes the USB key but then black screen and the console crashes. You have to do a Hard reboot to restart the console

thank you for your help & your work !

**Comment by gdicaterina** [comment]
Hi, how are you?
I was the same error, use the new hekate (release now) and my problema will solve.

Best regards!!

**Comment by Grass0001** [comment]
i think the latest version of the build is broken or something, as i have installed atmosphere about ~6 hours ago and its been fine, but I've heard 3 people not have atmosphere boot in the last few hours

**Comment by glosdaz** [comment]
I have the same issue booting from Hekate launch sysmmc black screen not even booing Atmos have to hard reset

**Comment by SciresM** [comment]
Re-open using the issue templates, providing details about what custom sysmodules you use etc.
