### ISSUE TITLE
Error code 2153-1540

### ISSUE THREAD

**Issue by blue-prince** [Atmosphere-NX/Atmosphere#1242]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ ] receiving error code 2153-1540 on some titles (games) (some of them after the games starts and some at the beginning.
[ ] N/A
[ ] N/A

### How can the issue be reproduced?

[ * ]</br>
[  ] Ive listed the titles that i have a problem with in a threat in GBA temps
https://gbatemp.net/threads/error-code-2153-1540-need-help-guys.577729/page-2

### Crash Report

[ ]included in the link below 
[ ]https://gist.github.com/blue-prince/f3674bbb68493cf66b2880dd27362f47
[ ]

### System Firmware Version

10.2.0
[ ]
[ ]
[ ]

### Environment?

- bootloader (fusèe, hekate) both (tried each, getting the same error)
- Official release 0.15.0
  - Added sig patches (supports HOS firmware 10.2.0 and AMS 0.15.0)
  - [ ] 
 
- Do you have additional kips or sysmodules you're loading:N/A
- Homebrew software installed: Gold leaf and Awoo

### Additional context?

- Additional info about your environment:

N/A

**Comment by SciresM** [comment]
1) "ResultAudioDspAborted" --> you probably have some kind of hardware issue with the bpmp
2) Piracy is not supported.
