### ISSUE TITLE
Can't read my gamecard

### ISSUE THREAD

**Issue by reckendheck** [Atmosphere-NX/Atmosphere#1245]
### What's the issue you encountered?

I downloaded the pre-release of atmosphere. I laso updated my switch to the newest 11.0. Now my switch can't detect my original gamecards anymore. I have the right sig patches installed.

### How can the issue be reproduced?

idk try update the switch to the newest and then install atmosphere.

### Crash Report

N/A

### System Firmware Version

11.0.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: i only installed atmosphere and used fusee launcher on linux to "inject" the fusee primary
- Do you have additional kips or sysmodules you're loading: sys-clk and edizon
- Homebrew software installed: hb-appstore, aio switch updater, sftp, daybreak, tinfoil

### Additional context?

- Additional info about your environment:

N/A

**Comment by cheesycod** [comment]
You need to either force disable nogc in BCT.ini or boot the switch normally to burn the fuses as 11.0.0 updated GC firmware and Atmosphere uses fuses to determine nogc apparently.
