### ISSUE TITLE
I get ERROR MESSAGE when I start ANY APPLICATION 

### ISSUE THREAD

**Issue by bahrainiprog** [Atmosphere-NX/Atmosphere#1248]
I updated my firmware to 11.00 and I replaced all the necessary files in my sd card from the site.
I also replaced the primary bin file.
Everything is fine till I try to open ANY app I get an error message saying 
Cant start the app . return to HOME MENU.
My system is currently running the new software atmosphere and I am getting this message 
Any help

**Comment by Masamune3210** [comment]
Please make a new issue and fill out the issue template

**Comment by SciresM** [comment]
Reopen using the issue templates.
