### ISSUE TITLE
I updated my firmware to 11.00 

### ISSUE THREAD

**Issue by angel12455** [Atmosphere-NX/Atmosphere#1249]
I updated my firmware to 11.00 by mistake so  I replaced all the necessary files in my sd card from the site and i got this

a fatal error occurred when running atmosphere
program ID 010000000000bd00
Error Desc: std: abort () Call (Oxffe)
Report saved to /atmosphere/fatal_errors/report_00000000086ba1b.bin

i just have to wait for the final files or did i did something wrong

**Comment by bahrainiprog** [comment]
I did the same thing.
I updated the firmware to 11.0
Replaced all the Primary and Secondary files from the site.
Getting error messages when I start any application.

**Comment by Masamune3210** [comment]
Please make a new issue and this time fill out the issue template

**Comment by SciresM** [comment]
1) update mission control
2) use the issue templates
