### ISSUE TITLE
Applet mode

### ISSUE THREAD

**Issue by asam72** [Atmosphere-NX/Atmosphere#1251]
Hello everyone. I installed the atmosphere firmware on an unpatched switch. The installation succeeded but Atmosphere starts in Applet Mode and therefore some apps do not work. How do I get out of Applet mode considering I don't have any games installed? Thank you

**Comment by fincs** [comment]
You can download any random game demo from the eShop in order to use it as a host title for homebrew.
Also, next time please use the issue template.
