### ISSUE TITLE
Atmosphere crashes on boot 

### ISSUE THREAD

**Issue by EmreTech** [Atmosphere-NX/Atmosphere#1253]
### What's the issue you encountered?

When I attempt to boot Atmosphere from Hekate, it just crashes in the middle of boot.
I recently updated to Atmosphere version 0.16.0, and I updated to Firmware 11.0.0.
Before updating to Firmware 11.0.0, it worked fine with Firmware 10.2.0.

### How can the issue be reproduced?

You can reproduce this by updating to Firmware 11.0.0 after updating to Atmosphere 0.16.0.

### Crash Report

The crash report was saved to the fatal errors folder and I cannot upload it to gist.github.com.

### Environment?

I was using Hekate Ctcaer version 5.5.0.
I was using the official Atmosphere version 0.16.0.
I have sigpatches that are for Atmosphere 0.15.0 and SysDVR.

**Comment by Nold360** [comment]
Same here. But I already had firmware 11.0.0 before launching atmosphere for the first time. 

[01607247135_0100000000001000.log](https://github.com/Atmosphere-NX/Atmosphere/files/5648633/01607247135_0100000000001000.log)

[01607247135_0100000000001000.zip](https://github.com/Atmosphere-NX/Atmosphere/files/5648634/01607247135_0100000000001000.zip)

**Comment by JteMonteEnDerby** [comment]
just wait until they find out i guess

**Comment by Masamune3210** [comment]
Uninstall any sysmodules that dont come with atmosphere
Dont ask for help with sigpatches

**Comment by EmreTech** [comment]
I wasn’t asking help with sigpatches, I was just saying that they are there.

**Comment by fincs** [comment]
Piracy is not supported. Using sigpatches implies usage of piracy.

**Comment by EmreTech** [comment]
What the hell!

**Comment by EmreTech** [comment]
You can’t just close this
