### ISSUE TITLE
Atmosphere doesn’t boot

### ISSUE THREAD

**Issue by EmreTech** [Atmosphere-NX/Atmosphere#1255]
What's the issue you encountered?

When I attempt to boot Atmosphere from Hekate, it just crashes in the middle of boot.
I recently updated to Atmosphere version 0.16.0, and I updated to Firmware 11.0.0.
Before updating to Firmware 11.0.0, it worked fine with Firmware 10.2.0.

How can the issue be reproduced?

You can reproduce this by updating to Firmware 11.0.0 after updating to Atmosphere 0.16.0.

Crash Report

The crash report was saved to the fatal errors folder and I cannot upload it to gist.github.com.

Environment?

I was using Hekate Ctcaer version 5.5.0.
I was using the official Atmosphere version 0.16.0.
I have SysDVR.

**Comment by EmreTech** [comment]
Here you go inconsiderate people. An updated bug report.

**Comment by SciresM** [comment]
Does not reproduce here. Upload and link your crash report, as without it assistance can not be provided.

**Comment by EmreTech** [comment]
Will do. I’ll try to upload soon.

**Comment by EmreTech** [comment]
[Fatal Error Report.zip](https://github.com/Atmosphere-NX/Atmosphere/files/5649186/Fatal.Error.Report.zip)

Alright, this does contain a bin file of the error because that's what it saved

**Comment by SciresM** [comment]
Update mission control, which you did not mention you had, and which needs an update to be compatible with 0.16.0.

**Comment by EmreTech** [comment]
Mission Control? Okay...

**Comment by SciresM** [comment]
Yes, mission control is crashing due to 0.16.0 incompat.

**Comment by EmreTech** [comment]
Oh. Thanks for the help!

**Comment by ndeadly** [comment]
There must some AIO packages bundling MissionControl. There has been a large increase in users who deny running it lately despite the TID telling otherwise...

**Comment by EmreTech** [comment]
AIO? Like AIO Switch Updater?

**Comment by EmreTech** [comment]
I do have another error, but I'm just going to update all of my Homebrew applications that use USB and all my other Sysmodules

**Comment by ndeadly** [comment]
> AIO? Like AIO Switch Updater?

All-In-One. I don't know what AIO switch updater does, but I'm talking about zip files put together by third parties that bundle Atmosphere along with other homebrew sysmodules and applications.

**Comment by EmreTech** [comment]
Oh, those! I know of a website that kinda does that except you can customize it
