### ISSUE TITLE
Black screen if open too fast a game after close another game.

### ISSUE THREAD

**Issue by swat1990** [Atmosphere-NX/Atmosphere#1257]
Very good job everything works well except for a little thing I don't know if the other one has the same problem but when I close a game I sometimes have to wait a few seconds before opening another game or otherwise it gives me a black screen and nothing works anymore I have to turn off the console via the power button.

I have atmospher 0.16.0 and my switch is in 11.0.0 and I have the last sig-patch to install.
I have the impression that it may be a question of stabilizing, but I am not sure to check it please and thank you for the very good work.

**Comment by SciresM** [comment]
Re-open using the issue templates.

Piracy is not supported.
