### ISSUE TITLE
Switch crashes after the boot - Atmosphere 0.16.0 + FW 11.0 + Mesosphere + emummc

### ISSUE THREAD

**Issue by lucatortiglione** [Atmosphere-NX/Atmosphere#1259]
Hi,
i have updated to FW 11.0 by using daybreak.

After that, the switch crashes after boot, and as after boot i mean i see the main menu and then crashes.
![IMG_20201207_131753_DRO](https://user-images.githubusercontent.com/52408341/101350466-e85b4200-3886-11eb-8478-bb43385febc1.jpg)

**Comment by SciresM** [comment]
1) you did not use the issue templates
2) that is a custom sysmodule crash, not an atmosphere issue. Delete 42....10.
