### ISSUE TITLE
Switch Crashes trying to boot up after loading Emmu

### ISSUE THREAD

**Issue by WingedDrifter** [Atmosphere-NX/Atmosphere#1262]
### What's the issue you encountered?
The Switch crashes upon booting. I boot using Hekate, click Emunand, and it gets to the Nintendo Switch logo screen before Atmosphere's error screen pops up.

I had updated my sysnand to FW 11.0.0/Atmosphere 0.16.0 and wanted to update my emmu to match.
Since I had made a backup of the appropriate files before updating, I replaced the files with the backup, and got the same issue again.
Tried both hekate_ctcaer_5.5.0.bin and hekate_ctcaer_5.3.3.bin.
I tried a clean install (redownloaded 0.14.4 and copied files into my sd card). Still crashes.

### How can the issue be reproduced?
Booted Switch using TegraRcmGui. Used payload hekate_ctcaer_5.5.0.bin and hekate_ctcaer_5.3.3.bin.
Hekate loads. Click payload, then clicked Emmu.
Switch seems to boot like normal, and when it reaches the Nintendo Switch with logo screen, Atmosphere's error page pops up.

### Crash Report
https://gist.github.com/WingedDrifter/9d75aa6166599543995e32b299d06c97

### System Firmware Version
10.2.0 Emu / 11.0.0 Sys

### Environment?
- Bootloader: Hekate
- Official release: 1.14.4 / 1.16.0
- Do you have additional kips or sysmodules you're loading: no
- Homebrew software installed: Goldleaf, Awoo-installer, ChoiDujourNX, Daybreak, JKSV, RetroArch

### Additional context?
Apologies if I missed anything - really tired today lol

**Comment by SciresM** [comment]
Set nogc = 0 in BCT.ini, or whatever the equivalent is for hekate.

Piracy is not supported.
