### ISSUE TITLE
A Fatal Error Occured

### ISSUE THREAD

**Issue by avocaloidnerd** [Atmosphere-NX/Atmosphere#1263]
### What's the issue you encountered?

I booted to sysMMC and atmosphere immediately crashes </br>
(Not sure)</br>
</br>

### How can the issue be reproduced?

[ * ] Just boot up using sysMMC on Atmosphere 0.16.0</br>

### Crash Report

</br>
https://gist.github.com/avocaloidnerd/8998f9dbced8a83369ae004dd6544e46</br>

### System Firmware Version

11.0.0</br>

### Environment?

- Hekate
- Official release or unofficial build: 
  - Official 5.5.0
- (Not sure)
- Homebrew software installed: Arcadia, Daybreak, Arcopolis, Ultimate Mod Manager, Switch themes installer, ftpd

### Additional context?

- Additional info about your environment:

**Comment by SciresM** [comment]
"0100000000001000"

Delete your custom theme by removing /atmosphere/contents/0100000000001000.
