### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Drago-oss** [Atmosphere-NX/Atmosphere#1264]
## Bug Report

Goldleaf and mtp-server-nx don't work crash on startup

**Comment by fincs** [comment]
Not a problem with Atmosphère, but with third party software.
Piracy is not supported.
Next time please use the issue template and completely fill it out.

**Comment by Drago-oss** [comment]
I'm sorry, I'm new here, thanks for your work

Il mar 8 dic 2020, 16:29 fincs <notifications@github.com> ha scritto:
