### ISSUE TITLE
Error/Potential brick after downgrade from 11.0.0 to 10.2.0

### ISSUE THREAD

**Issue by xdCallMeCooper** [Atmosphere-NX/Atmosphere#1265]
After downgrading from 11.0 to 10.2, this error code pops up on my switch after booting into atmosphere - 

Error Code: 2002-2634 (0x149402)
Program: 010000000000001F
Firmware: 10.2.0 (Atmosphère 0.15.0-master-1c71d12d)

An error has occurred.

It's been doing this for a day now and I fear that my Switch is completely bricked. When I try to turn it on normally without booting into atmosphere, all that appears is just a black screen. It's stuck there and I'm worried.

**Comment by masagrator** [comment]
What tool you have used to downgrade FW?

**Comment by HookedBehemoth** [comment]
Eject your gamecard and try again.

You updated the gamecard controller on 11.0.0 and FS now fails to handle it.

**Comment by xdCallMeCooper** [comment]
> What tool you have used to downgrade FW?

Daybreak.

**Comment by xdCallMeCooper** [comment]
> Eject your gamecard and try again.
> 
> 
> 
> You updated the gamecard controller on 11.0.0 and FS now fails to handle it.

Gamecard?

**Comment by HookedBehemoth** [comment]
![image](https://user-images.githubusercontent.com/22580720/101536224-01084c80-399a-11eb-8309-65462fc3a883.png)

**Comment by xdCallMeCooper** [comment]
> ![image](https://user-images.githubusercontent.com/22580720/101536224-01084c80-399a-11eb-8309-65462fc3a883.png)
> 
> 

I don't even have a gamecard in my switch...

**Comment by SciresM** [comment]
Yes you do.

In any event, set nogc=1 in BCT.ini, or whatever the hekate equivalent is.
