### ISSUE TITLE
Fatal error: kernel_patcher: unable to identify kernel!

### ISSUE THREAD

**Issue by SparklySilvall-Y** [Atmosphere-NX/Atmosphere#1270]
I tried updating my switch after installing Atmosphere's 0.16.1 pre-release and downloading the fusee off of that same page, and simply get the Fatal error: kernel_patcher: unable to identify kernel! error. This happens regardless if I load up through pushing fusee or with Hekate, and I've tried reinstalling the Atmosphere pre-release as well as re downloading fusee.

**Comment by SciresM** [comment]
1) You did not use the issue template
2) I do not believe that you actually extracted 0.16.1 correctly.

Reopen using the issue templates.
