### ISSUE TITLE
Apply fatal auto reboot to panics

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#1271]
#### Overview:
- Apply fatal auto reboot to panics</br>

#### Nature of Request:  
- Addition

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>
- [**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?
It makes it so the user doesnt have to get up to reboot the console when it panics</br>

**Comment by SciresM** [comment]
No, fatal errors need the user to note the binary name.
