### ISSUE TITLE
Goldleaf not working after updating to Atmosphere 16.1

### ISSUE THREAD

**Issue by TRNR-Kelly** [Atmosphere-NX/Atmosphere#1274]
### What's the issue you encountered?

Goldleaf crashes without opening and kicks me back to the HBmenu instead of letting me do goldleaf stuff

### How can the issue be reproduced?

open goldleaf

### Crash Report

N/A

### System Firmware Version

11.0.1 

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: Official
  - [ Official release version x.x.x (or) unofficial build ] AMS 0.16.1
  - [ If using an unofficial build, include details on where/how you acquired the build. ] N/A
     - [ Ex: Self-compilation ] -
     - [ Ex: Kosmos' distribution of Atmosphère ] -
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: None

**Comment by fincs** [comment]
Piracy is not supported.
In addition, this is not a support forum for 3rd party applications.
