### ISSUE TITLE
Booting on sysnand after power  downn emmunand

### ISSUE THREAD

**Issue by rubensk8er** [Atmosphere-NX/Atmosphere#1275]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before 

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand.] 
Turn off console after emmunand in 11.0.1 fw and atmos 16.0.1 pre released and then turn on makes logo switch freeze and have to restart
Did you make any changes related to Atmosphère itself? not really did a clean install with hekate
If so, make sure to include details relating to what exactly you changed. 

Booting on stock, give a frezze on switch logo

System Firmware Version

11.0.1

###Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by
Fuse primary. Bin
- Official release 
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
Awoo checkpoint tinfoil

- Additional info about your environment:
Sd 256 gb evo select plus

**Comment by SciresM** [comment]
If I'm reading this right, stock boot requires reboot after emunand?

That sounds like an emummc issue, not an atmosphere issue -- and even beyond that, "issue occurs on stock fw" is outside of the scope of the atmosphere issue tracker.
