### ISSUE TITLE
report_0000000005766c2b.bin

### ISSUE THREAD

**Issue by sallmorais** [Atmosphere-NX/Atmosphere#1278]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
When I start Atmosphère 0.16.1, it does not start and the following sentence appears:

A fatal error occurred when running atmosphere.
program ID: 010041544d530000
error desc: std: :abort() called (0xffe)
report saved to /atmosphere/fatal_errors/report_0000000005766c2b.bin

the atmosphere directory may improperly have archive
bits set. please try running an archive bit fixer tool
(for example, the one in Hekate)

Press POWER to REBOOT

[ Did you make any changes related to Atmosphère itself? ]</br>
I just copied the files on the micro SD card and started Atmosphère 0.16.1

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>
N/D

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
N/D
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
N/D
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>
N/D

### System Firmware Version

11.0.1</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
HEKATE
- Official release or unofficial build: 
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
     N/D
- Do you have additional kips or sysmodules you're loading:
N/D
- Homebrew software installed: [ * ]
N/D

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
```
the atmosphere directory may improperly have archive
bits set. please try running an archive bit fixer tool
(for example, the one in Hekate)
```

Run the archive bit fixer tool in hekate.
