### ISSUE TITLE
Game Cards Aren't Being Read (Atm. 0.16.1)

### ISSUE THREAD

**Issue by cDOTwav** [Atmosphere-NX/Atmosphere#1280]
I've updated Hekate and Atmosphere to both the latest update and now whenever I boot into emu. FW it won't read any of my game cards. I tried this on FW 10.2.0 but RN I'm currently updating to 11.0.1 to see if it works or not.

**Comment by cDOTwav** [comment]
Well....that was a bad idea... cause now I get this 
![20201216_075614](https://user-images.githubusercontent.com/51276621/102351319-3dc4dc80-3f74-11eb-853d-ac2588e007af.jpg)

**Comment by ndeadly** [comment]
@cDOTwav update MissionControl.

**Comment by cDOTwav** [comment]
> @cDOTwav update MissionControl.

Thank you so much, it's up and running now. Gonna close this now.
