### ISSUE TITLE
A fatal error occured while running Atmosphere.

### ISSUE THREAD

**Issue by lutzyyyy** [Atmosphere-NX/Atmosphere#1284]
I installed the new ofw and atmosphere crashed.

"A fatal error occured while running Atmosphere.
Program ID: 010000000000bd00
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_000000000888d5cd.bin

Press POWER to reboot"

**Comment by SciresM** [comment]
1) you did not use the issue templates 
2) not an atmosphere issue. Update mission control.
