### ISSUE TITLE
Fusee Primary does not work with SD card in 1 bit mode

### ISSUE THREAD

**Issue by fvig2001** [Atmosphere-NX/Atmosphere#1287]
My switch has an SD card connector pin missing. If I try to use fusee-primary + Atmosphere 16.1, I get an error stating:

"[Error] Fatal error: Failed to initialize the SD card!."

Press POWER to reboot"

My SD card is fat32 and I am able to use it with Hekate 5.5.1 (Shows up with error that sd card is in 1 bit mode). I think sept is also affected as lockpick rcm ends up getting into a blackscreen when it's supposed to run sept.

For reference, I was using Atmosphere with Hekate 5.5.3 on Atmosphere 15 with 10.2 without issues before trying to update to use Atmosphere 16.1. I moved all folders to another folder and extracted Atmosphere 16.1 only.

**Comment by SciresM** [comment]
Yeah, long term this will be solved by fusee rewrite using ams::sdmmc. In the short term, "use hekate".

**Comment by SciresM** [comment]
Also, you didn't use the issue templates.
