### ISSUE TITLE
Development documentation

### ISSUE THREAD

**Issue by evilsephiroth** [Atmosphere-NX/Atmosphere#129]
Is there some written documentation or diagrams to understand better Atmosphere OS? Should be easier to get hands dirty and eventually contributing to the project

**Comment by Luro02** [comment]
Look in the source code of the project ;)

**Comment by hexkyz** [comment]
A quick rundown of Atmoshpere's components has been merged into the main README. More in depth documentation will likely become available later when the project matures.

**Comment by fennectech** [comment]
YAY     MORE STUFF TO READ :D
