### ISSUE TITLE
0.16.2 Fatal Error:  failed to read BCT0 from sd

### ISSUE THREAD

**Issue by KalenAuditore** [Atmosphere-NX/Atmosphere#1290]
## Bug Report

When injecting fusse primary with 0.16.2 (the new release) it tells me: Fatal Error:  failed to read BCT0 from sd

With 0.16.1 it doesn't happen to me. And if instead of deleting the entire atmosphere and sept folder, I simply replace the files that the computer asks me, so the error does not appear but it remains black before starting HOS

PS: Sorry for the bad English.

**Comment by SciresM** [comment]
Yeah, I updated the release build like an hour ago to fix this.

Just update/extract the latest zip.

**Comment by KalenAuditore** [comment]
Thank you very much, SciresM, everything solved.
