### ISSUE TITLE
Error code 2002—2636 (0x149402)

### ISSUE THREAD

**Issue by Zullivan1987** [Atmosphere-NX/Atmosphere#1291]
Works fine whit OF, Buy i'm CFW...
When i tried to load Emunad appear this screen:
![IMG_20201219_183301](https://user-images.githubusercontent.com/25548369/102702522-42fe8180-4229-11eb-864c-545adf15ae55.jpg)

**Comment by SciresM** [comment]
You used a gamecard on 11.0.0+. You can never use one on <11.0.0 again.

Remove your gamecard and upgrade to 11.0.0.

also, you didn't use the issue templates.
