### ISSUE TITLE
Super mario 3d collection(super mario 64)

### ISSUE THREAD

**Issue by carcaschoi** [Atmosphere-NX/Atmosphere#1292]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
idk
[ - software used to make "backups", ]</br>
awoo installer
[ - software explicitly distributed for piracy, etc ]</br>
piracy game
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
open the game(super mario 3d collection), and then choose super mario 64
[ Did you make any changes related to Atmosphère itself? ]</br>
No
[ If so, make sure to include details relating to what exactly you changed. ]</br>
NA

### How can the issue be reproduced?

[ * ]</br>sysnand version 10.2.0, emuMMC version 11.0.1 with atmosphere(mesosphere) 0.16.2 with signpatch
[ Include a detailed step by step process for recreating your issue. ]</br>
1. Inject fusee-primary.bin
2. install the games nsp file. 
3. Open it.
4. choose super mario 64
5. screen stuck
ps. If I close it, the screen will show (The software was closed because an error occurred)

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
No
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
NA
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>
If I close it, the screen will show (The software was closed because an error occurred)

### System Firmware Version
11.0.1/M.16.2/E

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: official releases
     - this is my package of atmosphere(https://github.com/carcaschoi/ShallowSea), I use atmosphere full version.
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]

### Additional context?

- Additional info about your environment:
If I use 10.2.0/M.15.0/E , the game work fine.
- [ Any other information relevant to your issue. ]
- I know you will say not support piracy, but I think you can have a try with your super mario 3d collection game card. Maybe you will have the same problem !?

**Comment by SciresM** [comment]
Piracy is not supported
