### ISSUE TITLE
SaltyNX crashes on M.16.2, not crashing on 0.16.2

### ISSUE THREAD

**Issue by masagrator** [Atmosphere-NX/Atmosphere#1294]
### What's the issue you encountered?

I have V1.
SaltyNX 0.4.0a was working without issue on M.15.0.
Updated Atmosphere today to M.16.2 to investigate some issue. And it turned out no game now wants to load.
Heap size is set correctly, nintendo logo disappears and after few seconds any game is crashing.
Issue doesn't exist on 0.16.2, also when injecting plugins is disabled the issue doesn't exist on M.16.2</br>

### How can the issue be reproduced?</br>

1. Install SaltyNX 0.4.0a and Atmosphere M.16.2 ( + FW 10.2.0, don't know if issue exists on newer firmwares), download NX-FPS as plugin example
2. Run any game</br>

### Crash Report</br>

[01608472125_010039400e8d6000.log](https://github.com/Atmosphere-NX/Atmosphere/files/5720991/01608472125_010039400e8d6000.log)</br>

### System Firmware Version</br>

10.2.0</br>

### Environment?</br>

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
 fusee sysmmc</br>
- Official release or unofficial build:
 official M.16.2</br>
- Do you have additional kips or sysmodules you're loading:
no kips;
SaltyNX, Tesla, sys-clk, Noexs.
Deleted everything except SaltyNX and issue still exists.</br>
- Homebrew software installed:
I don't think it matters in this case, but I have few of my test homebrew, Daybreak, Checkpoint, Cheats Updater, hbappstore, moonlight, mtp-server-nx, NX-Shell, nxdumptool, nxmtp, PPSSPP, reboot to payload, Reset Parental Controls, RetroArch, ReverseNX-Tool, SaltyNX-Tool</br>

### Additional context?</br>

It happens for both game cartridges and installed games with and without updates. 
Tested on Witcher 3, LA Noire and Little Busters. All of them were working before.
SaltyNX 0.3.2a also doesn't work.
SaltyNX doesn't provide any error because plugin is injected successfully and game starts booting as expected.</br>

I will understand if this report will be closed because of how SaltyNX works. But if mesosphere behaves differently than official kernel, I think it's worth investigating what is happening.

**Comment by Skonikol** [comment]
> ### How can the issue be reproduced?
> 1. Install SaltyNX 0.4.0a and Atmosphere M.16.2 ( + FW 10.2.0, don't know if issue exists on newer firmwares), download NX-FPS as plugin example
> 2. Run any game

I've tested a few games, everything works fine...

![2020122022423500](https://user-images.githubusercontent.com/5678237/102722871-2fc8e000-4315-11eb-8a53-55949d777ff9.jpg)

![2020122022431200](https://user-images.githubusercontent.com/5678237/102722886-3a837500-4315-11eb-9a68-c3689912b33b.jpg)

**Comment by masagrator** [comment]
Can you provide a list of games? Or you have checked one of games I have listed and it works for you? I want to be as much be certain as possible that this issue is on my side.

**Comment by Skonikol** [comment]
> Can you provide a list of games? Or you have checked one of games I have listed and it works for you? I want to be as much be certain as possible that this issue is on my side.

Ori 1 & 2
Catherine FB
RE 1
Mario Tennis Ases
Memoranda
FF 12 ZAge

I can check LA Noire but later, since I don't have it installed and the internet is bad. Unfortunately, I don't have a Witcher3.

**Comment by Skonikol** [comment]
> you have checked one of games I have listed and it works for you?

Witcher is OK, Little Busters! too

![2020122102214100](https://user-images.githubusercontent.com/5678237/102727134-ef795a00-4334-11eb-9ab9-fa128eaeabca.jpg)

**Comment by masagrator** [comment]
Thanks for info. So this is something from my side. I will try to clean up shit and try again. Closing issue.
