### ISSUE TITLE
Games Requiring Account Linked doesn't launch

### ISSUE THREAD

**Issue by AWKNDEAD** [Atmosphere-NX/Atmosphere#1296]
## Bug Report
N/A

### What's the issue you encountered?

After running the latest Atmosphère  (**Atmosphère 0.16.2**) i tried to play games like Bloodstained Ritual of the Night or the SNES/NES apps and it simply shows a black screen with: "Unable to start software. Return to the HOME Menu and try again".
No other major problem and even after trying to launch those games it never crashed to me the Atmosphère.

**Did you make any changes related to Atmosphère itself?**
Changed the **BCT** config file only to support game card (nogc=0) and the **system_settings** to enable deprecated software (enable_deprecated_hid_mitm = u8!0x0) for usb file tranfer using **nxmtp**

### How can the issue be reproduced?

Run Atmosphère and then try to run any account linked required game like the mentioned above.

### Crash Report
N/A

### System Firmware Version
11.0.1

### Environment?
- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: **fusèe**
- Official release or unofficial build:  **Atmosphère 0.16.2**
- Do you have additional kips or sysmodules you're loading: **no, I use the base official included in the zip file**
- Homebrew software installed: **none**

### Additional context?

- Additional info about your environment:
Also i notice the games like Astral Chain or Final Fantasy x/x-2 says the same when i try to run them on the latest Atmosphère (0.16.2) but i don't remember if those require a linked account. they worked on Firm(10.2.0) Atmosphère (0.14.4) with no issue

**Comment by SciresM** [comment]
Redownload the games from the eshop/link an account. Seems like a non-issue to me.
