### ISSUE TITLE
Mariko System save 8000000000000120

### ISSUE THREAD

**Issue by zal16** [Atmosphere-NX/Atmosphere#1297]
I have a Mariko Switch with corrupted SYSTEM partition, but i tried to rebuid this partition with suchmememanyskill's Emmchaccgen, but he generates a 800000000000120 save for Erista consoles

would you like to get this file for me?

Ia located in SYSTEM/save/800000000000120

**Comment by SciresM** [comment]
This is not what the issue tracker is for.

**Comment by zal16** [comment]
how can i get this?

**Comment by shchmue** [comment]
this is an emmchaccgen issue, not an atmosphere one, and i doubt there's any difference between this file on a particular firmware on erista vs mariko so your problems probably lie elsewhere

**Comment by zal16** [comment]
i already talked to him, but he has no mariko console to compare.

when I turn on the console without this save file, it generates one, but it has a different size.

so I would like to have a file like this from a functional mariko console, just to compare and, if possible, help the suchmememanyskill

**Comment by Masamune3210** [comment]
That's a real pickle, but this still isn't an issue with atmos. Your better off going somewhere else for help with that unless you can manage to prove somehow that atmos is related
