### ISSUE TITLE
TegraRCGUI help

### ISSUE THREAD

**Issue by ronin1071** [Atmosphere-NX/Atmosphere#1298]
Hi, I'm following a tutorial to jailbreak my switch. The tutorial had a link to your website to get the required downloads. It states that along with Atmosphere, I also need a file called TegraRCMGUI. which I can't seem to find. Is this file no longer needed? Or am I just missing it somewhere?

Thanks

**Comment by Grass0001** [comment]
https://github.com/eliboa/TegraRcmGUI/releases

**Comment by ronin1071** [comment]
Grass, you rock! thank you!
