### ISSUE TITLE
failed to apply noldrchk

### ISSUE THREAD

**Issue by Themainman1360** [Atmosphere-NX/Atmosphere#1299]
I was on the previous build, before this one and I just updated. Whenever I try to boot emmummc it gives me this error and puts me back into the hekate menu.

**Comment by SciresM** [comment]
piracy is not supported, and this is not the hekate repo.

**Comment by Themainman1360** [comment]
I'm sorry, I didn't know this was related to piracy, this only happened
when I updated to your latest release. If you could point me in the right
direction I would appreciate it.

**Comment by icyph3r** [comment]
I am also getting this error, not related to piracy (unless the guides i have been following online have pointed me in the wrong direction). Any help resolving this would be amazing! I installed a homebrew app called 'sigpatch-updater', this was the last thing I did before getting this error, maybe it has something to do with that. Help appreciated!

**Comment by Masamune3210** [comment]
N O      P I R A C Y
![image](https://github.com/Atmosphere-NX/Atmosphere/assets/1053504/951c711f-90bd-4c68-ac9f-f1bbc108ecc9)

**Comment by icyph3r** [comment]
Like I said before, (keep in mind I know nothing about switch modding) I was following a guide and appear to have been pointed in the wrong direction. I was not trying to pirate games, I was trying to install the version of a game directly from a game cart without it updating/installing the latest version. I fixed the `failed to apply noldrchk` error by starting from scratch and following a different guide.

**Comment by SciresM** [comment]
That is piracy, which is not supported.
