### ISSUE TITLE
Get a framework in place for launching homebrew from the home menu.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#13]
This may take the form of our patching qlaunch, or our replacing qlaunch's layout archives. Who knows? We'll have to figure out how we want to handle this, but it's a top priority item to support.

**Comment by iGPLTV** [comment]
the words "home menu" and "launching homebrew" make me happy.

**Comment by thomasnet-mc** [comment]
Wouldn't we just go with installing an application? I know Rei is working on that with BogInstaller. We do need an NCA generator though.

**Comment by PyroFlareX** [comment]
in my head, what would make sense would be for CFW to not require security install tickets on carts and installable, so besides making romsbuilder be able to make nca's, it'd work.

(this might not even reasonable)

**Comment by fincs** [comment]
Running homebrew shouldn't involve installing custom titles. Installing custom titles is risky because it entails a ban from Nintendo's services.

**Comment by ThatNerdyPikachu** [comment]
Oh, right. Forgot about that...
