### ISSUE TITLE
Goldleaf will not launch on Atmosphère 0.16.2

### ISSUE THREAD

**Issue by Th3Alic3** [Atmosphere-NX/Atmosphere#1300]
I wanted to report Goldleaf will not launch on Atmosphère 0.16.2.

There's a momentary black flash then the HomeBrew menu is right back up.

**Comment by masagrator** [comment]
This is not Atmosphere issue.

**Comment by joeyg8292002** [comment]
Goldleaf crashing on my Nintendo Switch and Goldleaf is not working on my Nintendo Switch. Goldleaf crash error 2001-0123 (0xf601). Goldleaf 0.8 crash and went back to Atmosphere and the homebrew menu. Goldleaf 0.9 crash and error; I got a error is a fatal error (2001-0123 (0xf601)). Is there anyway to fix this.
