### ISSUE TITLE
Error code 2001-0123 (0xf601)

### ISSUE THREAD

**Issue by TristanFlame** [Atmosphere-NX/Atmosphere#1306]
[Random crash when 10 seconds booting into cfw. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ On 10.2.0, update Hekate Atmosphere to the most recent version. Use daybreak to update to 11.0.1.]</br>

### Crash Report
Atmosphère Fatal Report (v1.1):
Result:                          0xF601 (2001-0123)

Program ID:                      00ff0000a53bb665
Process Name:                    sysmodule
Firmware:                        11.0.1 (Atmosphère 0.16.2-master-1085ccbe)
General Purpose Registers:
Start Address:                   0000000000000000
Stack Trace:
        ReturnAddress[00]:       0000000000000000
        ReturnAddress[01]:       0000000000000000
        ReturnAddress[02]:       0000000000000000
        ReturnAddress[03]:       0000000000000000
        ReturnAddress[04]:       0000000000000000
        ReturnAddress[05]:       0000000000000000
        ReturnAddress[06]:       0000000000000000
        ReturnAddress[07]:       0000000000000000
        ReturnAddress[08]:       0000000000000000
        ReturnAddress[09]:       0000000000000000
        ReturnAddress[10]:       0000000000000000
        ReturnAddress[11]:       0000000000000000
        ReturnAddress[12]:       0000000000000000
        ReturnAddress[13]:       0000000000000000
        ReturnAddress[14]:       0000000000000000
        ReturnAddress[15]:       0000000000000000
        ReturnAddress[16]:       0000000000000000
        ReturnAddress[17]:       0000000000000000
        ReturnAddress[18]:       0000000000000000
        ReturnAddress[19]:       0000000000000000
        ReturnAddress[20]:       0000000000000000
        ReturnAddress[21]:       0000000000000000
        ReturnAddress[22]:       0000000000000000
        ReturnAddress[23]:       0000000000000000
        ReturnAddress[24]:       0000000000000000
        ReturnAddress[25]:       0000000000000000
        ReturnAddress[26]:       0000000000000000
        ReturnAddress[27]:       0000000000000000
        ReturnAddress[28]:       0000000000000000
        ReturnAddress[29]:       0000000000000000
        ReturnAddress[30]:       0000000000000000
        ReturnAddress[31]:       0000000000000000

### System Firmware Version

11.0.1 </br>

### Environment?
I originally using hekate, i thought the error was caused by it. so i decided to use Atmosphere instead. Same error.

**Comment by SciresM** [comment]
Remove the custom sysmodule that's crashing by deleting the relevant folder in /atmosphere/contents.
