### ISSUE TITLE
game card not reading issue is back

### ISSUE THREAD

**Issue by butiuae** [Atmosphere-NX/Atmosphere#1312]
after the recent update my card reader stopped working and the already proposed fix with the BCT.ini and Hekate_ipl.ini doesn't work completely. The error message is removed but when you run a game it loads for a few seconds then fails with an error message. Downloaded games are not affected in any way even when using nogc=0

**Comment by Skonikol** [comment]
Since you have not used the template for issue, it is very difficult to give you the right advice.

**Comment by butiuae** [comment]
What do you mean by template?

**Comment by Skonikol** [comment]
> What do you mean by template?

https://github.com/Atmosphere-NX/Atmosphere/issues/new?template=bug_report.md

**Comment by butiuae** [comment]
## bug report
**what is the issue encountered?**
game card could not be read

**How can the issue be reproduced?**
I just updated atmosphere to version 0.16.2

**Crash Report**
N/A

**system firmware version**
11.0.1

**environment**
atmosphere version 0.16.2
hekate  version 5.5.1

**additional context**
I use the website sdsetup.com when updating using there recommended Pre-configured bundles.
This is a similar issue to issue#794 but the solution no longer works.
https://github.com/Atmosphere-NX/Atmosphere/issues/794

**Comment by Skonikol** [comment]
Do you use emummc? What is the configuration in your hekate_ipl.ini ?

**Comment by butiuae** [comment]
i use sysmmc.

**hekate_ipl.ini**
[config]
autoboot=0
autoboot_list=0
autohosoff=1
autonogc=0
backlight=100
bootwait=3
updater2p=0

[CFW (sysMMC)]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
icon=bootloader/res/icon_payload.bmp

[CFW (emuMMC)]
emummcforce=1
fss0=atmosphere/fusee-secondary.bin
icon=bootloader/res/icon_payload.bmp

[Stock]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
icon=bootloader/res/icon_switch.bmp
stock=1

[Fusee]
icon=bootloader/res/icon_payload.bmp
payload=bootloader/payloads/fusee-primary.bin

**Comment by Skonikol** [comment]
You need to show what error appears. Perhaps this has nothing to do with nogc.

**Comment by butiuae** [comment]
if nogc=1 then the standard error
![the-game-card-could-not-be-read-nintendo-switch](https://user-images.githubusercontent.com/58942557/103484607-7801fb00-4e09-11eb-88f3-0ecfe81a1614.jpg)

but if nogc=0 then the game will load for a second then:
![20210103_211816](https://user-images.githubusercontent.com/58942557/103484619-a4b61280-4e09-11eb-9dcf-76d2f4a1603a.jpg)

**Comment by Skonikol** [comment]
If you run this configuration, how does the GC run behave?

[Fusee]
icon=bootloader/res/icon_payload.bmp
payload=bootloader/payloads/fusee-primary.bin

**Comment by butiuae** [comment]
it behaves the same way

**Comment by butiuae** [comment]
i checked all configs and it looks like i can play the GC if i run the stock config but any other way it dosn't work

**Comment by butiuae** [comment]
its fine now that i am sure that that the actual switch is fine and that i have a way to play physical games i will wait for the next update and do a clean intall since i didn't have this problem with previous versions it might work on the newer versions thanks for your help
