### ISSUE TITLE
LayeredFS: Separate homescreen icon for mod

### ISSUE THREAD

**Issue by lordelan** [Atmosphere-NX/Atmosphere#1313]
What I want for ages (I hoped uLaunch might solve this at some point) is a way to seperate title icons for a vanilla game and a mod for a game on the homescreen.
Additionally I'd love to see this with an option to either **share the same save game** with the vanilla game or to give the mod of the game a different title ID (either automatically or by altering a config file?).

Examples:

1. Breath of the Wild - There's a Zelda mod where I can play the whole game as princess Zelda. I want to have it as a separate icon on the homescreen beside the usual Breath of the Wild icon.
In sd:/atmosphere/content/[titleID_of_BotW]/ there's a folder called mods in which I create subfolders for each different mods, so I create one named "Zelda Mod" where I put in all files as I would have put them in the main titleID folder of the game. This leads to a new icon on the homescreen named after the folder "Zelda Mod".
In the Zelda Mod folder there's also a config.json where I put in an altered titleID manually so if I launch Zelda Mod from the homescreen it creates a separate (new) save. Of course I could drop more small mods (like HUD mods) in the Zelda Mod folder which are all applied to the Zelda Mod as well. On the other hand, everything I put directly into sd:/atmosphere/content/[titleID_of_BotW]/ (for example cheats) applies to the vanilla game **and** all mods.
To have something apply **only** to the vanilla game I could put it in sd:/atmosphere/content/[titleID_of_BotW]/mods/base_only/ or something like that.

2. Mario Kart 8 Deluxe - I want to check out custom Mario Kart 8 Deluxe courses made by the community so I create a folder in sd:/atmosphere/content/[titleID_of_MK8D]/mods/ called "Mario Kart 8 Deluxe CT". Since I don't create/adjust a config.json in there, it appears as a second icon on the homescreen **but uses the same save game as the vanilla **game**** so I can enjoy the new courses whenever I want while still having unlocked all karts and so on.

I hope I was not too confusing with what I want and I understand that this won't be high priority but it would be a fantastic feature for a future release of Atmosphère!

**Comment by SciresM** [comment]
This is deeply out of scope for what's possible given what ams currently replaces.

I don't even know how you'd implement something like this in atmosphere lol
