### ISSUE TITLE
Random crash when installing software to NAND

### ISSUE THREAD

**Issue by micktu** [Atmosphere-NX/Atmosphere#1316]
Methods employed:

* DBI "Install to NAND."
* HOS "Move software to internal storage"
* Game Card Installer "Nand Install"

A crash stack appears a few gigabytes into transfer pretty consistently.

![103510906-bb428500-4e6e-11eb-89d2-d2f694e8fe70](https://user-images.githubusercontent.com/132598/103761117-d3f19d00-501e-11eb-8811-d0ce1872cd0f.jpeg)

**Comment by SciresM** [comment]
Piracy is not supported.

`HOS "Move software to internal storage"` --> Known issue with file-based emummc, not an atmosphere issue.

**Comment by micktu** [comment]
I understand that piracy is a thing that should not exist. I was just having fun backing up my legal copies. Thank you, I will look around for the Emummc issue, Apparently, it affects all off the NAND encoding methods.

**Comment by SciresM** [comment]
"backing up legal copies"

piracy, not supported.
