### ISSUE TITLE
The Game card could not be read. Please remove and reinsert it. 

### ISSUE THREAD

**Issue by NaturalHarmonia** [Atmosphere-NX/Atmosphere#1318]
This starting happening abruptly when I updated to 0.16.1 about a month ago. I've tried reinserting the game card but that doesn't work. I don't know what the problem is. The game I have is Breath of the Wild.

**Comment by SciresM** [comment]
Change nogc settings to disable nogc.

Re-open using the issue templates, if the issue persists.
