### ISSUE TITLE
Mesosphere: Certain Games Won't Launch

### ISSUE THREAD

**Issue by NWPlayer123** [Atmosphere-NX/Atmosphere#1320]
### What's the issue you encountered?

If I try to boot `Piczle Lines DX 500 More Puzzles!` it won't run, goes black for a moment and then pops up the "an error has occurred" screen. 

### How can the issue be reproduced?

See above, that specific game seems to crash with the Mesosphere build of 0.17.0, unsure if other games exhibit the same behaviour.

### Crash Report

[PiczleCrashReport.zip](https://github.com/Atmosphere-NX/Atmosphere/files/5781173/PiczleCrashReport.zip)

### System Firmware Version

11.0.1 FW

### Environment?

Launched directly with fusee-launcher, I rolled back to non-meso version of 0.17.0 and now it boots again. It also worked fine on 0.16.2 non-meso.

**Comment by SciresM** [comment]
What custom system modules are in play?
