### ISSUE TITLE
Atmosphere 17.0 issues with tinfoil

### ISSUE THREAD

**Issue by killernos** [Atmosphere-NX/Atmosphere#1325]
## Bug Report
So on large nsp install I can tell tinfoil is struggling to stay running, almost like the switch is running out of memory, it hasn't crashed  but after a 7 gb file installed I tried to install a 16 gb file it was so laggy, I closed tinfoil and had to reopen I was afraid it was going to crash, in atmosphere 16.2 never had an issue with this, something you might want to check into.

When I tried to copy a file in tinfoil error code 2162-0002 (0x4a2)  occurred

**Comment by SciresM** [comment]
Piracy is not supported.

**Comment by killernos** [comment]
These are my game cart files not pirary I was just running test with it one was zelda botw and the other was just dance 2020

**Comment by SciresM** [comment]
That is piracy, and not supported.
