### ISSUE TITLE
Crash after updating to Atmosphere M 0.17.0

### ISSUE THREAD

**Issue by bloggingninja** [Atmosphere-NX/Atmosphere#1331]
I just updated Atmosphere to Atmosphere M 0.17.0  following the instructions found here:
https://nh-server.github.io/switch-guide/extras/updating/

but when I try to boot my emummc I get the following error:
Error Code 2162-0002
Program 0100000000001000
Firmware: 11.0.1 (Atmosphere M 0.17.0-master-e53b9cc5)

any help would be appreciated. 
I'm going to try a fresh install next but figured I'd let you know this problem exists just in case

**Comment by SciresM** [comment]
Delete your custom theme. Fresh install will work.
