### ISSUE TITLE
RetroArch Goldleaf and TinFoil cannot be run

### ISSUE THREAD

**Issue by freezingyip** [Atmosphere-NX/Atmosphere#1334]
Goldleaf  0.8 and TinFoil  11 cannot be run , but no error,

RetroArch 1.9 error
![IMG_20210114_145452](https://user-images.githubusercontent.com/76923485/104555680-3a0e9d80-5679-11eb-94e1-81d4bf394a60.jpg)

**Comment by SciresM** [comment]
Piracy is not supported.
