### ISSUE TITLE
Game Cartridge reading doesn´t work on FW 11.0.1

### ISSUE THREAD

**Issue by Angrysonic10** [Atmosphere-NX/Atmosphere#1336]
I recently updated the console in the actual firmware 11.0.1.
But when I try to play any game cartridge for some reason it doesn't work. 
The message that appears in the console says: ''Game cartridge couldn´t be read. Try again.''
I tried every solution, like running the OFW and try to update the console normally, or replacing the value of the BCT.ini to nogc = 0 and nothing works. 
Can you give a solution to this problem, please?
Thank You in anticipation!
(I have Sysnand Hack)

**Comment by SciresM** [comment]
set nogc = 0.

If booting via hekate, which you probably are, you need to edit hekate configuration and not BCT.ini.
