### ISSUE TITLE
gamecard reader doesn't read on atmos

### ISSUE THREAD

**Issue by pcwizard7** [Atmosphere-NX/Atmosphere#1337]
### What's the issue you encountered?

The game reader doesn't read on atmos but works fine while booted from sxos

### How can the issue be reproduced?

Boot into atmos sysnand or emunand and try to insert a game cart

### System Firmware Version

11.0.1

### Environment?

- Booted by hekate
- official 17.1
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: No

**Comment by SciresM** [comment]
set nogc = 0 in BCT.ini, or edit hekate configuration to set nogc = 0 if booting from hekate.

**Comment by pcwizard7** [comment]
Still broken.

Also works fine in stock. but boot into ATMOS Sysnand read errors

**Comment by SciresM** [comment]
I guarantee you this is a failure to properly edit configuration.

Show screenshot of your atmosphere/config folder and paste the contents of your bct.ini?

If booting via hekate, paste your hekate_ipl.ini?

**Comment by pcwizard7** [comment]
atmosphere/config folder is empty 

Hekate_ipl.ini
> [config]
autoboot=0
autoboot_list=0
bootwait=2
backlight=54
autohosoff=1
autonogc=0
updater2p=0
bootprotect=0

[ATMOSPHERE (sysNAND)]
payload=bootloader/payloads/fusee-primary.bin
icon=bootloader/res/atmosphere.bmp

[ATMOSPHERE (emuNAND)]
payload=bootloader/payloads/fusee-primary.bin
icon=bootloader/res/atmosphere-emu.bmp

[SXOS CFW]
payload=bootloader/payloads/SX_Loader.bin
icon=bootloader/res/sxos.bmp

[Stock]
emummc_force_disable=1
fss0=atmosphere/fusee-secondary.bin
icon=bootloader/res/icon_switch.bmp
stock=1

**Comment by SciresM** [comment]
"atmosphere/config folder is empty"

so, as expected, you have not edited BCT.ini.

copy the template into atmosphere/config and add nogc = 0 in the right place.

**Comment by pcwizard7** [comment]
thanks, I didn't know it needed to be in there since it was in Hekate
