### ISSUE TITLE
A fatal error ocurred when running Atmosphere

### ISSUE THREAD

**Issue by Ruisusenpaii** [Atmosphere-NX/Atmosphere#1340]
i need some help,i tried to update the atmosphere version to 0.17.1 and it crashes when i try to start it.

Program ID:0100000000000004
Error desc: std: :abort () called (0xxfe)
Report saved to /atmosphere/fatal_errors_report_0000000000000bc64197.bin

**Comment by SciresM** [comment]
Please upload the report binary.

**Comment by Ruisusenpaii** [comment]
> Please upload the report binary.

https://mega.nz/file/YhUyzBLb#j6HVpGsDUh1YgtGEkNLb--B7JkaWOly1szfQoO1cA8M

**Comment by SciresM** [comment]
Update mission control.

**Comment by Ruisusenpaii** [comment]
> Update mission control.

how?

**Comment by SciresM** [comment]
mission control is a homebrew sysmodule you have installed. follow the instructions in its github repo, presumably.

**Comment by Xronium** [comment]
dude thank you so much, i've been looking for what the problem was, and mission control has a title id of 010...0db i believe? or something different tho the error i was getting so thank you


a lot

**Comment by chester4ka** [comment]
Hi, same error, tell me what to do?
Report https://mega.nz/file/f98EATxa#jOBNB6zuIGPfpCKzDNv7ChWOocthTE58tqeHu5Dl6Z4

**Comment by SciresM** [comment]
@chester4ka your error is not the same. You're using a custom sysmodule that needs to be updated to be compatible with AMS 0.18.0.

**Comment by chester4ka** [comment]
The error occurs when starting tinfoil.

**Comment by SciresM** [comment]
Piracy is not supported.
