### ISSUE TITLE
latest atmosphere is super buggy

### ISSUE THREAD

**Issue by sonic-iso** [Atmosphere-NX/Atmosphere#1341]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

everything wont load right... i tried 2 sd cards and same thing. gold leaf wont launch,tinfoil wont launch,lithium is super buggy.
i was on 10.x system software and the atmosphere related to that with no issues. once i updated everything got wierd. even the hbmenu now loads in applet mode.

### System Firmware Version

17.1</br>

### Environment?

- fusee primary
- Official release or unofficial build: 
  - [ Official release latest build ]

- Do you have additional kips or sysmodules you're loading:sys-con
- Homebrew software installed: [the basics ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Piracy is not supported.
