### ISSUE TITLE
Web Applet frozen

### ISSUE THREAD

**Issue by thaikhoa** [Atmosphere-NX/Atmosphere#1344]
### What's the issue you encountered?

Games with connecting to web applet such as in-app-purchase or terms and conditions will freeze the whole system, force to powering off.

### How can the issue be reproduced?

Game > In App Purchase or any web applet function

Such as Asphalt 9 > Shop > Purchase
Game > Home button > Album > Upload images or videos to Twitter
</br>
</br>

### Crash Report

No cash report as a whole system got forzen
### System Firmware Version

11.0.1</br>

### Environment?

Hekate Fusee Secondary
Fusee Primary

All official releases

Atmosphere 17.0.1
Hekate 5.5.3

Sysmodules: emuiibo, sysDVR, MissionControl, sys-clk

### Additional context?

Games with connecting to web applet such as in-app-purchase or terms and conditions will freeze the whole system, force to powering off.

I don't know whether the issue is just me.

**Comment by Masamune3210** [comment]
please go back and actually fill out the template

**Comment by thaikhoa** [comment]
Thanks, just done editing

**Comment by SciresM** [comment]
Does the issue occur using stock atmosphere release zip with no custom sysmodules?

**Comment by thaikhoa** [comment]
Without any sysmodules, everything works just fine. any other sysmodules that I've added could lead to the issue.

**Comment by Masamune3210** [comment]
If it works fine without sysmodules then it's very likely an issue with those sysmodules or from having too many installed at once, not with atmosphere

**Comment by AuroraWright** [comment]
It was explained here i believe: https://github.com/Atmosphere-NX/Atmosphere/issues/808#issuecomment-587184145 . So this is just a duplicate
