### ISSUE TITLE
A fatal error occurred when running Atmosphere

### ISSUE THREAD

**Issue by clasherclan1999** [Atmosphere-NX/Atmosphere#1347]
## Bug Report

When I inject the fusee-primary.bin with Hekate I get the Error message:

A fatal error occurred when running Atmosphere.
Program ID: 010000000000bd00
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_0000000009bfe74f.bin

PRESS Power to reboot

Report:

### What's the issue you encountered?

My switch was running for a while, then suddenly the HBApps werent able to start, I only got a blackscreen. I then tried to restart my switch. Thats when the Error occurred.

### How can the issue be reproduced?

Inject Hekate Payload
Boot to fusee-primary.bin

### Crash Report

https://drive.google.com/file/d/1ku22uWDQoigMfRn5IkPcKssQlnQVnDty/view?usp=sharing
Sorry, I didnt get this git gist working

### System Firmware Version

Im not sure, but NOT the newest available.

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 
- Official release or unofficial build: Official version 5.5.3
- Do you have additional kips or sysmodules you're loading: sys-ftpd I think.
- Homebrew software installed: https://imgur.com/a/tOqVW1j

### Additional context?

- Additional info about your environment:

I dont know how to open the .bin file to get the error log myself
Fusee-primary.bin is the newest one available.

Thanks for help

**Comment by SciresM** [comment]
Update mission control.
