### ISSUE TITLE
Open source RCM dongle

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#135]
I’m looking for a way to make an open source rcm dongle with OTS (off the shelf) parts that can also charge my switch.   I want to integrate it into this nyko powershell.   Ive got room for a teensy size board.   If i can get one with a right angle usbc cable soldered on it 
![a4369d8b-31de-456b-a63b-3d6cf9c68407](https://user-images.githubusercontent.com/11953665/41197891-d9ed9bd4-6c30-11e8-934e-1b281d9afb47.jpeg)

  The included cable has no data pins but the button can turn off the power  (which happens when the case is closed) and the other button turns it on.    This means i don’t need power management in the thing. But it would be nice if it only responded by sending payload (and using power) when an switch in RCM mode is detected.   Do you guys think an rcm dongle can also charge a switch that’s running horizon?

**Comment by fennectech** [comment]
Do you think this would be possible?

**Comment by Ninoh-FOX** [comment]
I maked this, but it doesn't charger the console.

https://fotos.subefotos.com/e14ee8d87d058949faddb9fde3aeeb81o.jpg

**Comment by Kozlowlw** [comment]
What did you do to that poor trinket...

**Comment by drofdoom** [comment]
I don't think so either forum or discords maybe and there's plenty of like minded projects .

**Comment by hexkyz** [comment]
This is not an actual Atmosphere issue, so I'm closing it. However, feel free to drop by IRC or Discord for exchanging ideas with other like minded people who have been working on similar stuff.

**Comment by fennectech** [comment]
cna you link the discord?

**Comment by fennectech** [comment]
Thanks    Sorry for clogging up atmosphere issues with it    I couldent find the discord for the group

**Comment by jonirrings** [comment]
@fennectech https://discordapp.com/invite/C29hYvh

is homebrew discord, had seen a hardware channel, is that the right place?
