### ISSUE TITLE
Ask for unaffiliated hid mitm sysmodule

### ISSUE THREAD

**Issue by impeeza** [Atmosphere-NX/Atmosphere#1353]
Hi I constantly use the homebrew https://gbatemp.net/threads/the-legend-of-zelda-mystery-of-solarus-dx-solarus-engine.500222/, it works fine but never was updated to latest libraries and still relies on old hid-mitm, I did try to compile using news libraries but I have no the knoledge.

Please if possible release a hid mitm sysmodule for supoort these HomeBrew.

thanks a lot.

**Comment by Masamune3210** [comment]
one could probably assume that unaffiliated would mean someone not them or official

**Comment by Slluxx** [comment]
@impeeza dont update atmosphere if you want to continue playing that game. Or ask in gbatemp for help to recompile it on your own.

**Comment by SciresM** [comment]
This doesn't need an atmosphere issue. I'm following the situation.

**Comment by impeeza** [comment]
Thanks, regards from Colombia
