### ISSUE TITLE
Hbmenu dosen't working on Album

### ISSUE THREAD

**Issue by tsukina22** [Atmosphere-NX/Atmosphere#1355]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

My issue is, my hbmenu is not showing up anymore on Appletmod when i click on Album.
I already try turn the switch off, but hbmenu doesn't come back to Album.
Now i can only access the hbmenu clicking on a game with the R pressing.
I just want the Hbmenu to return to album!
I'm using the new Atmosphere update 0.18.0 and my switch is a v1.

**Comment by SciresM** [comment]
This is just gonna be some issue with your configuration.

Seek help on discord, this isn't what the atmosphere issue tracker is for.

I recommend the nintendo homebrew discord.
