### ISSUE TITLE
Crash in emuMMC, not in ofw

### ISSUE THREAD

**Issue by Donas4Ceos** [Atmosphere-NX/Atmosphere#1363]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>

[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?
Crash
[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>
Play a game for long time
### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[crash_reports.zip](https://github.com/Atmosphere-NX/Atmosphere/files/5940486/crash_reports.zip)
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

11.0.1</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- hekate - CTCaer mod v5.5.4 & Nyx v1.0.0
- Official release or unofficial build: 
- Atmosphère 0.18.0 Official release
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]

### Additional context?

- Additional info about your environment:
- Sx Core installed
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
The crash reports seem unrelated to the issue you describe, and you don't actually explain what *causes* the crash, or even what kind of crash it is.

Re-open with the template actually filled out.
