### ISSUE TITLE
A fatal error while loading atmosphere ID:010041544d530000

### ISSUE THREAD

**Issue by Zira0711** [Atmosphere-NX/Atmosphere#1378]
### What's the issue you encountered?

Today I updated switch from 9.0.1 to 11.01(exFat since my SD card is exFat) and also the newest files from sdsetup.com. I did delete all related files and folders before moving the new ones. However, the fatal error occurs after trying to load CFW.  I searched for similar issues online and tried Fix Archive Bit but it is not fixing the issue.

A fatal error occurred when running Atmosphére.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

### How can the issue be reproduced?

Boot to RCM
Launch Hekate
Boot into CFW

### Crash Report

[report_0000000007800e4b.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6028430/report_0000000007800e4b.zip)

### System Firmware Version

11.0.1

### Environment?

hekate 5.5.4

### Additional context?

- Windows 10 is always trying to format SD card (exFat) after taking out from the switch. It complains Corruption was found while examining the boot region. I use chkdsk /F to fix the issue then it works. But I have to redo it  when the fatal error occurs in the switch.

**Comment by masagrator** [comment]
Then don't use exfat as it was 1000x said that it's corrupting sdcard.

**Comment by Zira0711** [comment]
yes, I understand fat32 should be the obvious choice right now, but back then there is an argument for exfat and I have used this card for 2-3 years. If the issue is actually caused by the sd card I will try to reformat it. Thanks.

**Comment by SciresM** [comment]
The error is fs::ResultInvalidFatFormatSd.

So, yeah, reformat your SD card. It's corrupted.

**Comment by Hakkai94** [comment]
Hello. I have this error, so formated my SD card in FAT32 mode, copied Atmosphere 1.4.0 Final on it then started my Switch : same error :(

**Comment by ElementalTJ** [comment]
Hello,
I have recently been having this same error.
I have replaced SD Card Reader, reformatted SD card, tried doing a bit-fix, checking SD card with h2testw (passes).
I am almost ready to send my device in for repair.
Does anyone have a fix? Or is my Switch basically dead?

Frequently comes up with 'SD Card Has Been Removed' error as well.
Thanks to all that can help!

**Comment by masagrator** [comment]
> Hello, I have recently been having this same error. I have replaced SD Card Reader, reformatted SD card, tried doing a bit-fix, checking SD card with h2testw (passes). I am almost ready to send my device in for repair. Does anyone have a fix? Or is my Switch basically dead?
> 
> Frequently comes up with 'SD Card Has Been Removed' error as well. Thanks to all that can help!

Hardware issues are unrelated to Atmosphere. Seek help in other sources like ReSwitched discord. This does sound like PCB socket connecting your sdcard reader is damaged. Go to repair service

**Comment by arkilis** [comment]
same error with firmware 15.0.1. SD card in FAT32 format.

**Comment by Hakkai94** [comment]
I found this solution that worked for me :
In Atmosphere, go to "tools" > "Arch bit . RCM . Touch . Pkg1/2" > "Fix
Archive Bit"

**Comment by Jrmewam** [comment]
The only working solution for me was to delete the atmosphère folder and replace it by a brand new fresh one. 
After that I was able to copy my content folder back to it.
Solution given by wonderful person on ARG guilded server

**Comment by Masamune3210** [comment]
Guys, this issue is closed. Please either go somewhere else for support or open a new one if you have a proper issue to report.

**Comment by xuanye** [comment]
> I found this solution that worked for me : In Atmosphere, go to "tools" > "Arch bit . RCM . Touch . Pkg1/2" > "Fix Archive Bit"
Thanks a lot , it worked for me
