### ISSUE TITLE
Add automatic reboot when error happens

### ISSUE THREAD

**Issue by 64dd** [Atmosphere-NX/Atmosphere#1385]
#### Overview:
- [ Add auto reboot when an error has occurred. ]</br>

#### Nature of Request:  
  - [ After few seconds console automaticly reboots after an error.] </br>

### What component do you feel this would best fit within?
- [ Idk the one handles error reports?]

### Why would this feature be useful?
[ This would be very useful if you don't want to get up everytime an error happens. ]</br>

**Comment by SciresM** [comment]
This is already supported for normal os fatals.

for atmosphere fatal errors, this is undesirable -- I want people to report atmosphere fatal errors, and auto reboot would make that less likely to happen.
