### ISSUE TITLE
Atmosphere Crashes Error Code 2002-6650

### ISSUE THREAD

**Issue by AwesomeKirito** [Atmosphere-NX/Atmosphere#1386]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br> I just went to the album and it crashed. Same goes for holding down r 
[ Did you make any changes related to Atmosphère itself? ]</br> Ive added mods to my games
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>https://gist.github.com/AwesomeKirito/c0ccda46ba163dc8a73fde2ff9aed0c1
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

X.X.X</br>11.0.1
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Fusee 
- Official release or unofficial build: Official
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading: Tesla
- Homebrew software installed: [ * ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Does the issue occur on stock atmosphere without custom symodules?

Please post a screenshot of your /atmosphere/contents folder.

The error is `fs::ResultProgramInfoNotFound`, which is an *extremely* strange error for you to be receiving, unless you have some pretty eldritch shit installed.

**Comment by AwesomeKirito** [comment]
![Screenshot (20)](https://user-images.githubusercontent.com/73203704/109255742-9a3d4700-77c2-11eb-8f6d-f1f832d8b3a5.png)
![Screenshot (21)](https://user-images.githubusercontent.com/73203704/109255743-9ad5dd80-77c2-11eb-974e-e9c4e386a4c2.png)
![Screenshot (22)](https://user-images.githubusercontent.com/73203704/109255745-9ad5dd80-77c2-11eb-9feb-a9dba4ff6339.png)
![Screenshot (23)](https://user-images.githubusercontent.com/73203704/109255746-9ad5dd80-77c2-11eb-94bd-b7a349f093c7.png)
![Screenshot (19)](https://user-images.githubusercontent.com/73203704/109255747-9b6e7400-77c2-11eb-9783-8d189ae6ff27.png)
![Screenshot (27)](https://user-images.githubusercontent.com/73203704/109255757-a1645500-77c2-11eb-8fb8-a46d60ed4249.png)
![Screenshot (24)](https://user-images.githubusercontent.com/73203704/109255760-a1645500-77c2-11eb-8e7b-afc758ba04ec.png)
![Screenshot (25)](https://user-images.githubusercontent.com/73203704/109255761-a1645500-77c2-11eb-90f6-9a4b1fb8b7b8.png)
![Screenshot (26)](https://user-images.githubusercontent.com/73203704/109255763-a1fceb80-77c2-11eb-808d-bbc9603c6d78.png)

**Comment by AwesomeKirito** [comment]
i havent tried it on stock

**Comment by SciresM** [comment]
Congrats, you now hold the record for the most custom sysmodules I have ever seen installed, with 11 (unless I'm missing some).

You're probably running into some limit on the number of programs that FS can know about simultaneously. Use fewer custom system modules at once.

**Comment by AwesomeKirito** [comment]
thank you it worked
