### ISSUE TITLE
Feature Request: Override screencap defaults

### ISSUE THREAD

**Issue by Slluxx** [Atmosphere-NX/Atmosphere#1390]
#### Overview:
- The possibility to override the ability for creating screenshots or videos either globally or per title

#### Nature of Request:  
- Addition

### What component do you feel this would best fit within?
- Probably Troposphere but i don't know.

### Why would this feature be useful?
Some games do not allow screenshots and videos to be made. Sharing those would be nice too.

**Comment by SciresM** [comment]
Closing this since this bridge will have to be crossed naturally during tma2 development anyway.

**Comment by Slluxx** [comment]
tma2 development? Whats that? And is this on the roadmap?

**Comment by SciresM** [comment]
See open PR/commit history this month, and yes it's in the roadmap.
