### ISSUE TITLE
It seems layredfs isnt working at all

### ISSUE THREAD

**Issue by pepsimaaaan** [Atmosphere-NX/Atmosphere#1393]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</ mods for any games refuse to load. all i was doing before hand was putting my sd card in, starting up my switch and launching breath of the wild>
[ Did you make any changes related to Atmosphère itself? ]</no>
[ If so, make sure to include details relating to what exactly you changed. ]</N/A>

### How can the issue be reproduced?

[ * ]</ try to load up a mod>
[ Include a detailed step by step process for recreating your issue. ]</ Step 1: got to >Atmosphère> contents> (games id)> romfs> (mod content)
Step 2: Insert sd card,Turn on switch, boot with fusee and launch a game.
Step 3: (for me at least) no mods load>

### Crash Report
no crashes

### System Firmware Version

11.0.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusee and hekate were both used at separate times
- Official release or unofficial build: Kosmos' distribution of Atmosphère aquired through the official github pages

- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ n/a ]

### Additional context?

n/a

(sorry if i misformatted anything)

**Comment by SciresM** [comment]
"Kosmos' distribution of Atmosphère"

Wat

Kosmos stopped existing a long time ago, way before 11.x released.

Anyway, can't reproduce, just use latest atmosphere release zip directly without add ons. Mods work fine over here.
