### ISSUE TITLE
LayeredFS will not load DLC when dumped into romfs folder

### ISSUE THREAD

**Issue by Hassas99** [Atmosphere-NX/Atmosphere#1394]
### What's the issue you encountered?
The game used for testing was DOAX3 Scarlet. DLC is completely broken when loading romfs mods. I'm not finding any issues when swapping main game files.
DLCs were dumped using nxdumping tool

### System Firmware Version

Latest release</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
  - Official release on the latest build using  fusèe.

### Additional context?

In the patch notes you said you addressed this issue however it is still seems to be broken.

"A bug was fixed that caused ams.mitm to incorrectly cache data storages.
This potentially broke DLC when using romfs mods, and could have caused other issues (e.g. with custom themes, and maybe other cases)."

**Comment by SciresM** [comment]
The issue you reference is completely fixed. Anything you're experiencing is necessarily a different issue.

"DLC is completely broken when loading romfs mods. I'm not finding any issues when swapping main game files."

So, what, you're attempting to modify the DLC romfs?

**Comment by SciresM** [comment]
"completely broken" in what way? Be more specific about what actions trigger what effects.

**Comment by Hassas99** [comment]
> "completely broken" in what way? Be more specific about what actions trigger what effects.

I wasn't modifying anything. DLC is kept intact without any modification.

**Comment by SciresM** [comment]
I have no idea what you're trying to do, then, and similarly have no idea what's actually wrong.

**Comment by Hassas99** [comment]
> I have no idea what you're trying to do, then, and similarly have no idea what's actually wrong.

I was trying to see if the DLC loads from romfs when dumped using nxdumptool, it doesn't.

**Comment by SciresM** [comment]
...why would you expect it to?

**Comment by SciresM** [comment]
...piracy is not supported.

I am really not sure why you thought that would work.
