### ISSUE TITLE
A fatal error occurred when running Atmosphere.

### ISSUE THREAD

**Issue by bigdesuMC** [Atmosphere-NX/Atmosphere#1397]
A fatal error occurred when running Atmosphere.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)
Report saved to [/atmosphere/fatal_errors/report_00000000490fbda8.bin

What's the issue you encountered?
After injecting the payload and running smash, the loading screen pops up but after that it's a black screen then the fatal error occurs

How can the issue be reproduced?
Boot to RCM
Launch Smash

[Crash Report](https://cdn.discordapp.com/attachments/541720022356066314/819282944413532170/report_00000000490fbda8.bin)

System Firmware Version

11.0.1

**Comment by SciresM** [comment]
Your game is corrupted. Re-download it from the eShop.
