### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by Atmospro** [Atmosphere-NX/Atmosphere#140]
i think there are a compilation syntax error introduced in latest commit please understand that. from: https://github.com/Atmosphere-NX/Atmosphere/commit/237ff0d1e7f226d5f51c3c17e306eaa844b10069

**Comment by Atmospro** [comment]
full log :https://pastebin.com/WzkD8CLF

**Comment by borntohonk** [comment]
You really need to stop submitting issues Thomas, you've been banned from this repository several times.

**Comment by GrimTech** [comment]
I think he's just trolling now to be honest, he can make so many alts to bypass the ban sadly.

**Comment by drofdoom** [comment]
Not like we cant see it's him .close this please .

**Comment by TuxSH** [comment]
Heh, I expected your new alt to be called "thomleg52"... guess I was wrong. ¯\_(ツ)_/¯
