### ISSUE TITLE
fail to determine markio warmboot firmware

### ISSUE THREAD

**Issue by theboy21-cell** [Atmosphere-NX/Atmosphere#1400]
## Bug Report
[ On boot up it come up with fail to determine markio warmboot firmware. ]</br>

### System Firmware Version

10.1.1</br>

### Environment?

- What bootloader (,hekate, etc) was Atmosphère launched by:
- Official release
- emunand
### Additional context?

- Additional info about your environment:
- [ I can mange to boot cfw sys nand but it does come up with and issue saying failed to match warmboot with fuses!
- if [continue]
![IMG_1060](https://user-images.githubusercontent.com/61985729/111058558-694f5880-84ca-11eb-991d-7ed03d5b137f.JPG)
![IMG_1062](https://user-images.githubusercontent.com/61985729/111058560-6c4a4900-84ca-11eb-8716-dbc5d975a0b2.JPG)

 sleep won't work . ]

**Comment by SciresM** [comment]
You manually installed a higher firmware to emunand or something (and burnt fuses in the process), but haven't booted it yet.

You need to boot the firmware that matches your fuse count at least once in order for downgrades to work.

Use hekate to determine what your fuse count is, boot the appropriate firmware at least once.
