### ISSUE TITLE
A fatal error ocurred when running atmosphere

### ISSUE THREAD

**Issue by fizzy1988** [Atmosphere-NX/Atmosphere#1401]
### What's the issue you encounterd

i havent used my switch in a while and was on atmosphere 0.15.0 i upbdated to atmosphere 018.1 and my card stopped working 
it was working before i upgraded i removed old atmosphere folder and sept folder and extracted atmosphere 0.18.1 to root of my sd i then borrowed a 32 gb card formated to fat 32 and fresh installed atmosphere 0.18.1 and it worked flawlessly so i reformated my 64 gb to fat 32 again fresh installed atmosphere 0.18.1 again andtried again but i still get the error when using my 64 gb card
the error is 
A fatal error ocurred when running atmosphere
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

Press POWER to reboot.

### How can the issue be reproduced?
simply by booting from my 64 gb card

### Crash Report

[report_0000000006d33312.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6138491/report_0000000006d33312.zip)

### System Firmware Version

11.0.1
### Environment?
hekate 5.5.4
also tried
fusee-primary.bin
with usb and pc tool for boot

- Homebrew software installed: 
- what comes with the zip from atmosphere GitHub release

**Comment by SciresM** [comment]
fs::ResultInvalidFatFormatSd.

Your SD card is not, in fact, FAT32.

Your SD card is formatted as exFAT, but you have FAT32 firm installed.

Format your SD as FAT32 correctly, or manually flash exFAT firm to package2.
