### ISSUE TITLE
A fatal error occured when running Atmosphere

### ISSUE THREAD

**Issue by dinkan85** [Atmosphere-NX/Atmosphere#1411]
### What's the issue you encountered?

When booting Atmosphere 0.18.1 from Hekate 5.5.4 i get this error after Atmosphere boot logo. 
A fatal error occured when running Atmosphere.

Program ID: 010000000000002B
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_00000000040582d.bin

Press POWER to reboot

### How can the issue be reproduced?

Booting into Hekate 5.5.4, using SX Pro dongle. emuMMC enabled. Booting Atmosphere thru Hekate Payloads choosing fusee-primare.bin. 

Same error occurs every time. I have never been able to boot into Atmosphere. 

### Crash Report

https://github.com/dinkan85/Bugs/blob/d9bf17114ea70f44957b766d78bccb4344223e46/report_000000000b40582d.bin

### System Firmware Version

Unsure of firmware on emuMMC. Maybe the kids updated the emunand firmware to 11.0.1. That's why I am trying to use Atmosphere.</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate_ctcaer_5.5.4.bin
- Official release or unofficial build: 
  - Official release version 0.18.1
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: No

### Additional context?

I have tried to format SD card to both fat32 and exfat. Same error occurs. I have also run the archieve bit fixer in hekate but it will not find anything to fix.

**Comment by SciresM** [comment]
You have a corrupt PRODINFO/system save.

Follow the instructions/directions in #1256 for guidance. You'll need to restore a non-corrupt backup and/or delete the system settings savedata.
