### ISSUE TITLE
Failed to Initialise SD Card

### ISSUE THREAD

**Issue by EXO5KELETON** [Atmosphere-NX/Atmosphere#1412]
### What's the issue you encountered?

 Switch SD Card reader died....had it replaced all fine but when purchased a new SD Card also clean switch updated to latest firmware all ok when I try run atmosphere I get the error failed to initialise sd card. all was working fine before the SD card reader died I have made sure the sd card reader is secure etc. ]<

- What bootloader  fusèe

**Comment by Masamune3210** [comment]
Please actually fill out the template instead of deleting it....

**Comment by SciresM** [comment]
Re-open with the issue template properly filled out.
