### ISSUE TITLE
Animal Crossing New Horizons Crashes on Nintendo Switch Logo

### ISSUE THREAD

**Issue by Daniseis4** [Atmosphere-NX/Atmosphere#1413]
Animal crossing new horizons does not load me with update 1.9.0 (with the 2 DLCs), I have tried to do it with atmosphere stock completely but it still does not load. I have it installed on my sd (exFAT). FW: 11.0.1, AMS: M.18.1, Sysnand.

Translated text

**Comment by nwhiteman42** [comment]
Don't use exFAT.  Use issue template

**Comment by Daniseis4** [comment]
still not working

**Comment by Masamune3210** [comment]
Make a new issue and fill out the issue template this time

**Comment by fincs** [comment]
Please reopen using the issue templates. Also, preemptively stating that piracy / unsigned content installation of *any* kind under *any* circumstances is not supported.
