### ISSUE TITLE
Help with the project

### ISSUE THREAD

**Issue by DSMan97** [Atmosphere-NX/Atmosphere#1416]
Just Help as Developer with Code or testing

@SciresM I am 4 years of Java Developer, and I want to help because I want to learn C++. If you need Beta Tester or something just tell me :blush:

Thanks in advanced

**Comment by erwinc1** [comment]
It’s github, you don’t need permission :) If you can contribute, then contribute with a PR.

**Comment by hexkyz** [comment]
Not a valid issue. Closing down as part of cleanup.
