### ISSUE TITLE
error compile mitm disord

### ISSUE THREAD

**Issue by thomas-50** [Atmosphere-NX/Atmosphere#142]
there are syntax error in discord mitm by @SciresM please listen do not close .

log paste :https://pastebin.com/uVMXxKDy

**Comment by SapphireExile** [comment]
Why do you insist on opening issues continuously? If Scires had a syntax error, he would fix it. Not tell you to open your thousandth issue.

**Comment by borntohonk** [comment]
you again? lol

**Comment by foskon** [comment]
Just ignore him. And, if you can, close.

**Comment by simonmkwii** [comment]
At this point I'm starting to think there's a syntax error in your brain.
I'm assuming you're referring to this, this was reposted in my server:
![image](https://user-images.githubusercontent.com/35590998/41422490-5b0b22c2-703c-11e8-898d-95c167a67447.png)
What part of "needs a lot of testing" do you not understand?
