### ISSUE TITLE
12.0.0 - Greater Accuracy

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#1420]
This issue is for tracking things that we should do to properly reflect 12.0.0 behavior, but which won't make it into the initial 12.0.0 support release because they're not necessary/have no impact.

* [x] erpt now has additional logic for managing `save:/forced-shutdown`, we should reverse engineer and implement this.
* [x] erpt now has additional logic for managing applet activity/suspend durations, we should reverse engineer and implement this.
* [x] FS now has additional logic for IFile->OperateRangeWithBuffer(), we should reverse engineer and implement this.

**Comment by OmaGamer** [comment]
Hello, 
I have the problem [NXBOOT]Unable to identify package1, after the update.
I tried reinstalling Atmosphere but it didn't work.

**Comment by SciresM** [comment]
This is now done as of 355010ad.
