### ISSUE TITLE
logo freeze

### ISSUE THREAD

**Issue by tomoya1230** [Atmosphere-NX/Atmosphere#1423]
What's the issue you encountered?
I updated to 0.19, but my switch freezes with the "nintendo switch" logo on startup

How can the issue be reproduced?
boot

System Firmware Version
12.0.0

Environment?
atmosphere - Latest

**Comment by Nanolx** [comment]
From the 19.0 ChangeLog:

* Homebrew which uses atmosphere extensions (including the mitm API) will need to be re-compiled in order to function on 0.19.0. 

So, disable your system modules and wait for updates to them.

**Comment by SciresM** [comment]
You did not use the issue templates.

but yeah, delete custom sysmodules.

**Comment by tomoya1230** [comment]
I'm sorry, I'll be careful after that
