### ISSUE TITLE
switch lite 12.0.0 mod not working on atmos 0.19

### ISSUE THREAD

**Issue by polizie** [Atmosphere-NX/Atmosphere#1425]
atmosphere error

**Comment by MonsieurKimYong** [comment]
When excute Non applet mod "Hbmenu",  Error occured. Games are going well...but that cause....I can't use install app 'TinLeaf'

**Comment by mbamber1986** [comment]
> atmosphere error

What's the error ?

**Comment by LordElrond1903** [comment]
Hey  my  aubjecy cloaee because of a miuaed word. But my system emunand

**Comment by Nanolx** [comment]
> 
> 
> When excute Non applet mod "Hbmenu", Error occured. Games are going well...but that cause....I can't use install app 'TinLeaf'
> 
> Using 19.0.0....

Piracy or tools that can be used for piracy aren't supported here.

**Comment by fincs** [comment]
Piracy is not supported.
