### ISSUE TITLE
upt 12.0.0 and AMS 0.19.0 dont work

### ISSUE THREAD

**Issue by LordElrond1903** [Atmosphere-NX/Atmosphere#1426]
I updated my switch to 12.0.0
Then applied what you released
I download Hekate and Sigpatches.
But I cant make Tinfoil work or install my games.
I have some reports and gonna send them to you.
Thanks in advance for your great work.
[01618153993_0100000000001000.log](https://github.com/Atmosphere-NX/Atmosphere/files/6292158/01618153993_0100000000001000.log)
[01618154340_010000000000003a.log](https://github.com/Atmosphere-NX/Atmosphere/files/6292159/01618154340_010000000000003a.log)

**Comment by mbamber1986** [comment]
I don't think there are any sigpatches out yet for 12.0.0 your best sticking with 11.0.1 till they are available

**Comment by LordElrond1903** [comment]
Downgrade causes brick your console ?

**Comment by mbamber1986** [comment]
Are you using emunand or sysnand

**Comment by TheDogMatt** [comment]
> 
> 
> I don't think there are any sigpatches out yet for 12.0.0 your best sticking with 11.0.1 till they are available

There Are SigPatchs Out Already

**Comment by mbamber1986** [comment]
Are there when did they release couldn't find them for 12.0.0

**Comment by MonsieurKimYong** [comment]
When excute Non applet mod "Hbmenu", Error occured. Games are going well...but that cause....I can't use install app 'TinLeaf'

Using 19.0.0....

**Comment by LordElrond1903** [comment]
> Are you using emunand or sysnand

Im a newbie about hacking. How can I understand it is emunand or sysnand ?

**Comment by fincs** [comment]
Piracy is not supported.
