### ISSUE TITLE
Non Applet mod Hbmenu not work

### ISSUE THREAD

**Issue by MonsieurKimYong** [Atmosphere-NX/Atmosphere#1427]
When excute Non applet mod "Hbmenu", Error occured. Games are going well...but that cause....I can't use install app 'TinLeaf'

Using 19.0.0....

**Comment by mbamber1986** [comment]
This might not get answered as it's related to playing games unless you own the games it's called as piracy you may need to Google this one

**Comment by fincs** [comment]
Piracy is not supported.
