### ISSUE TITLE
Atmosphere 0.19 Crash

### ISSUE THREAD

**Issue by manzipan** [Atmosphere-NX/Atmosphere#1428]
### What's the issue you encountered?

Just tried to delete a title from the homescreen and through settings and i get fatal error ocured in atmosphere reboot screen

###Error Description

Data abort (0x101)

### System Firmware Version

12.0.0

### Environment?

- fusèe
- Official release
  - Atmosphère 0.19.0

**Comment by substanc3-dev** [comment]
The release has been reuploaded to try to solve this issue, please try redownloading and replacing the files.

**Comment by manzipan** [comment]
ooops  sry mised the -c67c29eb file all good now
