### ISSUE TITLE
Could not start the software. Please try again from the HOME Menu.

### ISSUE THREAD

**Issue by NeoGoku** [Atmosphere-NX/Atmosphere#1434]
pls help me 

Environment

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: **Fusee**
- Official release or unofficial build: **Atmosphère 0.19.0**
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]

**Comment by fincs** [comment]
Piracy is not supported. Otherwise, redownload from eShop.
