### ISSUE TITLE
after downloading apex from eshop got fatal error

### ISSUE THREAD

**Issue by tenc3nt** [Atmosphere-NX/Atmosphere#1435]
### What's the issue you encountered?

I get an fatal error screen with Error DABRT (0x101)
Program: 0100000000000002
Firmware: 12.0.0
Atmosphere: 0.19.0-88dd4147

### How can the issue be reproduced?

just finish installing, then suddenly appear those fatal error

### Crash Report

[report_1c9aa55bd1.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6292574/report_1c9aa55bd1.zip)

### System Firmware Version

12.0.0|AMS.19.0|S

### Environment?

- bootloader : hekate 5.5.4

- Do you have additional kips or sysmodules you're loading : sys-ftp-light

- Homebrew software installed : tesla overlays, edizon, kosmos toolbox, daybreak, retroarch, nxthemes (disable), nx-shell, nxdumptool and jksv

### Additional context?

after restart then, it still need to redownload again from eshop, but data management, is already used

**Comment by SciresM** [comment]
Redownload the latest release zip, this was fixed about 6 hours ago.
