### ISSUE TITLE
Don't want to start the game

### ISSUE THREAD

**Issue by piero8783** [Atmosphere-NX/Atmosphere#1436]
## Bug Report
Can't start a game, send me to HOME

### What's the issue you encountered?

Update my console to version 12.0.0 and update the atmosphere 0.19.0. try to enter a game but it does not enter

### How can the issue be reproduced?

[ * ] entering the game

### System Firmware Version

12.0.0|AMS M.19.0|E

### Environment?

- CFW with version: [ e.g. Atmosphere 0.19.1 ]

 -Goldleaf version: [ e.g. 0.8, 0.9 (nightly) ]

 - Bootloader: Hekate 5.5.4

### Additional context?

![image](https://user-images.githubusercontent.com/82226524/114318119-27b5cb80-9ad1-11eb-9f73-fdd1a99adf27.png)

**Comment by fincs** [comment]
Piracy is not supported. Otherwise, redownload from eShop.
