### ISSUE TITLE
Data Abort (0x101) Can't uninstall Tinfoil

### ISSUE THREAD

**Issue by deedeeshime** [Atmosphere-NX/Atmosphere#1439]
### What's the issue you encountered?

When I am trying to uninstall Tinfoil (via + or data management settings) and it is crashing with:

```
A fatal error occurred when running Atmosphere
Program ID: 010000000000002
Error Desc: Data Abort (0x101)
```

I understand that contents folder is removed, but Tinfoil folder, which is I believe 010000000000002B, is there. 
And whenever I add contents folder, Atmosphere won't continue to boot. 
I still have the backup folder.

### System Firmware Version

On 12.0 and Atmosphere 0.19.0 </br>

**Comment by fincs** [comment]
Piracy is not supported.
