### ISSUE TITLE
im new  to this and i think i may have a issue

### ISSUE THREAD

**Issue by Holybutler02** [Atmosphere-NX/Atmosphere#1440]
For me it says this 
[A fatal error occurred when running atmosphere .
Program ID: 010041544d530000
Error Desc: std: :abort() called (0xffe)
Report saved to/atmosphere/fatal_errors/report_000000000666db3d.bin

The atmosphere directory may improperly have archive bits set. please try running a archive bit fixer tool (for example, the on in hekate).

Press power to reboot.]
i have a unpatched switch but im new to this it got updated to firmware 12.0.0 so i searched and found this before i started but  don't know what im doing i used this guide (https://switch.homebrew.guide/index.html). help me please!

**Comment by SciresM** [comment]
The atmosphre directory may have archive bits set improperly. Please try running the archive bit fixer tool (for example, the one in hekate).
