### ISSUE TITLE
BRING BACK MODDING SUPORT

### ISSUE THREAD

**Issue by mjcox244** [Atmosphere-NX/Atmosphere#1448]
## Feature Request

[ Please search for existing [feature requests](https://github.com/Atmosphere-NX/Atmosphere/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22features%2Ffeature-request%22) before you make your own request. ]</br>
[ Duplicate requests will be marked as such and you will be referred to the original request. ]

#### Overview:
The latest atmosphere limits/prevents game modding

#### Smaller Details: 
Due to the latest version of atmosphere includeing

> Atmosphère no longer uses the /contents/ folder for its own programs.
> Atmosphère's system modules are now bundled together in the single file "stratosphere.romfs".
> For those working on developing for atmosphère, executables inside the /contents/ directory will be preferred to those in "stratosphere.romfs".
> Please Note: In order to facilitate this change (and the desired behavior), the first time you boot after extracting a release zip, atmosphère system modules inside /contents/ will be deleted.
> This will have no impact on user programs (it only removes programs with specific program ids).

This prevents romfs modding that used this contents folder

#### Nature of Request:  
- Change
BRING THIS CONTENT FOLDER BACK FOR MODDING

### What component do you feel this would best fit within?
IDK whatever handled that contents foldeer

### Why would this feature be useful?
This will allow people to use the many romfs mods avalible without haveing to resort to an old version of atmosphere or editing NSP/XCI files

**Comment by pixel-stuck** [comment]
you realize that you can still use the contents folder, correct? Just that the sysmodules that atmo ships no longer reside there. This is all the changelog says.

**Comment by Conan179** [comment]
@mjcox244 Which mod shouldn't go?

**Comment by mjcox244** [comment]
ah I was confused for a second as someone on the 3D world modding server was saying it no longer worked for their mods then noticed that

**Comment by mjcox244** [comment]
NVM false alarm the person in the 3D world modding server just didn't lay the mod out correct

**Comment by mjcox244** [comment]
I feal stupid now lul

**Comment by SciresM** [comment]
Do not create all caps issue please.
