### ISSUE TITLE
atmosphere 0.19.1 - Can't enter homebrew apps!!!

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [Atmosphere-NX/Atmosphere#1449]
Describe the bug:

The switch crashes upon entering homebrew apps like FTPD or Retroarch (EdiZon, oddly enough, still works).  If I try to enter the apps via the menu when entering the game while holding down R, I get just a simple error message and get sent back to the Home screen.  But at the menu via the Album, after entering the aformentioned apps I get error message 2144-0001 and the whole thing reboots.  This all happened after I installed the latest atmosphere (0.19.1)

Switch:
Firmware 12.0.0, Atmosphere 0.19.1, FAT32 128 GB SD card

**Comment by SciresM** [comment]
Please re-open using the issue templates, and without "!!!" in the title.
