### ISSUE TITLE
help

### ISSUE THREAD

**Issue by CrazyFloof** [Atmosphere-NX/Atmosphere#1456]
## Bug Report
So I'm running the latest version of Atmosphere and every time I launch it it crashes and i have no idea why its doing this. Does anyone else have the same problem? If anyone can help please help! my discord CrazyFloof#1336 I said this because I don't know any other way if someone were to contact me with the help.
Error code (2162-0002) (0x4a2)
Program 0100000000001000
Firmware: 11.0.1 (Atmosphere M 0.19.1-master-997e4dd6)

**Comment by Masamune3210** [comment]
recreate the issue and this time follow the issue template plesse

**Comment by SciresM** [comment]
You didn't use the issue templates.

Also, delete your custom theme.
