### ISSUE TITLE
I'm Not Sure What To Do At This Point 

### ISSUE THREAD

**Issue by jatthom** [Atmosphere-NX/Atmosphere#1457]
## Bug Report

Error Code 2001-0123 (0xf601) Atmosphere Error

### Crash Report

Atmosphère Crash Report (v1.5):
Mesosphere:                      Enabled
Result:                          0x25A0B (2011-0301)

Process Info:
    Process Name:                am
    Program ID:                  0100000000000023
    Process ID:                  000000000000005a
    Process Flags:               00001137
    User Exception Address:      0000002dcff7c000
Exception Info:
    Type:                        User Break
    Address:                     0000005ba285f7a8 (am + 0x5f7a8)
    Break Reason:                0x0
    Break Address:               00000059f5c8cd90
    Break Size:                  0x4
Crashed Thread Info:
    Thread ID:                   000000000000007f
    Stack Region:                00000059f5c89000-00000059f5c8d000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   0000000000000000
        X[02]:                   0000000000000000
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000059f5c8cbe0
        LR:                      0000005ba283d6c8 (am + 0x3d6c8)
        SP:                      00000059f5c8cbe0
        PC:                      0000005ba285f7a4 (am + 0x5f7a4)
    Stack Trace:
        ReturnAddress[00]:       0000005ba283d3c8 (am + 0x3d3c8)
        ReturnAddress[01]:       0000005ba283d48c (am + 0x3d48c)
        ReturnAddress[02]:       0000005ba2878000 (am + 0x78000)
        ReturnAddress[03]:       0000005ba288a780 (am + 0x8a780)
        ReturnAddress[04]:       0000005ba28dd480 (am + 0xdd480)
        ReturnAddress[05]:       0000005ba28deee8 (am + 0xdeee8)
        ReturnAddress[06]:       0000005ba28dafe0 (am + 0xdafe0)
        ReturnAddress[07]:       0000005ba280190c (am + 0x190c)
        ReturnAddress[08]:       0000005ba283e434 (am + 0x3e434)
        ReturnAddress[09]:       0000005ba28000d4 (am + 0xd4)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0059f5c8cbe0 70 cc c8 f5 59 00 00 00 c8 d3 83 a2 5b 00 00 00
                                 0059f5c8cbf0 03 00 00 00 5b 00 00 00 60 cc c8 f5 59 00 00 00
                                 0059f5c8cc00 30 ae 9b a2 5b 00 00 00 30 ae 9b a2 5b 00 00 00
                                 0059f5c8cc10 30 ae 9b a2 5b 00 00 00 00 00 00 00 5b 00 00 00
                                 0059f5c8cc20 0b 5a 02 00 59 00 00 00 00 00 00 00 00 00 00 00
                                 0059f5c8cc30 03 00 00 00 5b 00 00 00 60 cc c8 f5 59 00 00 00
                                 0059f5c8cc40 30 ae 9b a2 5b 00 00 00 30 ae 9b a2 5b 00 00 00
                                 0059f5c8cc50 30 ae 9b a2 5b 00 00 00 00 00 00 00 5b 00 00 00
                                 0059f5c8cc60 30 ae 9b a2 5b 00 00 00 60 cd c8 f5 59 00 00 00
                                 0059f5c8cc70 80 cd c8 f5 59 00 00 00 8c d4 83 a2 5b 00 00 00
                                 0059f5c8cc80 00 00 00 00 00 00 00 00 08 40 c2 a2 5b 00 00 00
                                 0059f5c8cc90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0059f5c8cca0 00 00 00 00 00 00 00 00 ff 81 00 00 00 00 00 00
                                 0059f5c8ccb0 00 b0 a8 a2 5b 00 00 00 35 00 00 00 00 00 00 01
                                 0059f5c8ccc0 48 ce c8 f5 59 00 00 00 35 00 00 00 00 00 00 01
                                 0059f5c8ccd0 00 00 80 3f 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 0000002dcff7c200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 002dcff7c200 02 00 00 00 00 00 00 00 01 00 00 00 5a 00 00 00
                                 002dcff7c210 53 46 43 4f 00 00 00 00 a3 06 00 00 00 00 00 00
                                 002dcff7c220 53 46 43 49 01 00 00 00 02 00 00 00 00 00 00 00
                                 002dcff7c230 0b 5a 02 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c240 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c250 08 00 00 00 58 ce c8 f5 59 00 08 00 00 00 00 00
                                 002dcff7c260 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c270 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c280 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c2a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c2b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c2c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c2d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c2e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002dcff7c2f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

(I'm not sure how much more of the crash report you want)

(Also here's the fatal report if you need it too)

Atmosphère Fatal Report (v1.1):
Result:                          0xF601 (2001-0123)

Program ID:                      010000000000001f
Process Name:                    ns
Firmware:                        12.0.0 (Atmosphère 0.19.1-master-997e4dd6)
General Purpose Registers:
Start Address:                   00000077d8400000
Stack Trace:
        ReturnAddress[00]:       00000077d844be2c
        ReturnAddress[01]:       00000077d85655bc
        ReturnAddress[02]:       00000077d8583fd8
        ReturnAddress[03]:       00000077d8587c54
        ReturnAddress[04]:       00000077d844bd60
        ReturnAddress[05]:       0000000000000000
        ReturnAddress[06]:       0000000000000000
        ReturnAddress[07]:       0000000000000000
        ReturnAddress[08]:       0000000000000000
        ReturnAddress[09]:       0000000000000000
        ReturnAddress[10]:       0000000000000000
        ReturnAddress[11]:       0000000000000000
        ReturnAddress[12]:       0000000000000000
        ReturnAddress[13]:       0000000000000000
        ReturnAddress[14]:       0000000000000000
        ReturnAddress[15]:       0000000000000000
        ReturnAddress[16]:       0000000000000000
        ReturnAddress[17]:       0000000000000000
        ReturnAddress[18]:       0000000000000000
        ReturnAddress[19]:       0000000000000000
        ReturnAddress[20]:       0000000000000000
        ReturnAddress[21]:       0000000000000000
        ReturnAddress[22]:       0000000000000000
        ReturnAddress[23]:       0000000000000000
        ReturnAddress[24]:       0000000000000000
        ReturnAddress[25]:       0000000000000000
        ReturnAddress[26]:       0000000000000000
        ReturnAddress[27]:       0000000000000000
        ReturnAddress[28]:       0000000000000000
        ReturnAddress[29]:       0000000000000000
        ReturnAddress[30]:       0000000000000000
        ReturnAddress[31]:       0000000000000000

### Additional context?

I'm really stuck with this

**Comment by SciresM** [comment]
You have a partial update applied, where BOOT0 contains 11.x or lower but you have 12.x installed to system partition.

This seems to happen due to shutoff during the update process.

Restore NAND backup, and upgrade to 12.0.0 again.

Otherwise, you'll need to flash 12.0.0 BOOT0 to your console manually.

There's a decent guide for that [here](https://suchmememanyskill.github.io/guides/unbrick/).
