### ISSUE TITLE
Fatal error failed to init file system

### ISSUE THREAD

**Issue by trujay1** [Atmosphere-NX/Atmosphere#1462]
i run switch model xaw 10010364832 on 12.0.1 but iv had this problem before this

so i can use the sd card and inject it but it says fatal error: file system failed to init but the sd card runs fine on stock os 

iv tried other stuff like hekate but the text is distorted and no options pop up
and deep sea but it tells me the same thing

iv tried multiple versions of atmos and different cfw but the switch doesnt wanna run it and i dont see many people with the same problem and even if i do theres no answer to it

if anyone find an answer send a dm to discord !crabfestisback#9743 or post it in the thread

**Comment by SciresM** [comment]
Re-open using the issue templates.
