### ISSUE TITLE
Panic error when downloading some games

### ISSUE THREAD

**Issue by flifloo** [Atmosphere-NX/Atmosphere#1464]
### What's the issue you encountered?

I got some trouble with my emuMMC (SD files based), on some new game install (Warframe)/update (Tetris 99) my switch get a panic error (and I try to fix the archive byte multiples times).

It's always at the end, the loading bar empty and show a little cross in the middle before the panic screen.

Atmosphere 0.19.1 with mesosphere I get the black panic screen with the title ID `010000000000002B` and error `std::abort (0xFFE)`.

Older Atmosphere or 0.19.1 without mesosphere I get the blue panic screen withe the title id `010000000000000C` and the error code `2002-3502`.

The only change to Atmosphere I made is disabling `nogc` so I can play card games by adding `nogc = 0` on the `[stratosphere]` into `BCT.ini` and change `autonogc` to 0 in `hekate_ipl.ini`.

### How can the issue be reproduced?

Get a new game from the eShop or update an already downloaded one.
In some case the game occurs the crash every time you try to install/update it and other game can be downloaded without any problems.

### Crash Report

Black panic screen report [report_2cbad4195.bin](https://cdn.discordapp.com/attachments/414949821003202562/835492431268413460/report_2cbad4195.bin)

Blue panic screen report [01619276658_010000000000000c.log](https://github.com/Atmosphere-NX/Atmosphere/files/6370067/01619276658_010000000000000c.log)

### System Firmware Version

12.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: Official
  - hekate 5.5.5 and Atmosphere 0.19.1
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: No

### Additional context?

- Additional info about your environment: N/A

**Comment by SciresM** [comment]
File-based emummc has issues when files cross the 2^32 barrier inside the MMC...this isn't something readily fixable, and it's an emummc issue (not an atmosphere issue).

Best advice I can give is to use a partition-based emummc, and to make an issue on the emummc repo about the problem.

Sorry I can't do more >.>
