### ISSUE TITLE
The Noexes sysmodule stopped working with 0.19.1

### ISSUE THREAD

**Issue by MarioPossamato** [Atmosphere-NX/Atmosphere#1465]
### What's the issue you encountered?

The Noexes sysmodule no longer works for me as of the 0.19.1 update.

### How can the issue be reproduced?

I'm not sure if it can be reproduced, it may be something I have set incorrectly.  I didn't change anything after updating to Atmosphère 0.19.1, and it worked fine before.

### Crash Report

N/A

### System Firmware Version

12.0.1

### Environment

Atmosphere 0.19.1 / Hekate v5.5.5

**Comment by nwhiteman42** [comment]
https://github.com/mdbell/Noexes/issues/42

**Comment by MarioPossamato** [comment]
Ah, I didn't realize that there was already an issue on this subject!  Sorry about that.
