### ISSUE TITLE
Switch Won't Boot With Latest CFW

### ISSUE THREAD

**Issue by cDOTwav** [Atmosphere-NX/Atmosphere#1467]
I've installed both hekate version 5.5.5 and Atmosphere version 0.19.1 and now my Switch won't boot into CFW, my Switch is on firmware 11.0.1, which probably explains why it's doing that, but even so I have no clue on how to install the latest firmware since it won't boot.

**Comment by SciresM** [comment]
Re-open using the issue templates.
