### ISSUE TITLE
Incompatibility with older emuNAND

### ISSUE THREAD

**Issue by apassiou** [Atmosphere-NX/Atmosphere#1471]
Created emuNAND using Hekate 5.5.5 (latest as of today) off of sysNAND 4.1.0.
SD Card is FAT32 formatted and clean.

Vanilla Atmosphere (0.19.1) will not boot into this low of a version emuNAND and results in a black screen after the Atmosphere logo. Both File based and Partition based emuNAND is affected.

My suspicion is that an ini/config file is missing entries for such early fw builds. Not sure at what point compatibility breaks (what the earliest possible emuNAND version is).

Temporary solution is to use [Kefir, it has English interface when you run it](https://github.com/rashevskyv/kefir/releases)to load up Atmosphere, it has the necessary entries. Boot into the emuNAND and update it with Sunrise. After that vanilla Atmosphere will boot successfully.

Atmosphere packages that do NOT work: Deepsea, SDsetup, Kosmos. Those are the ones I tried, all lead to black screen. Kefir is the only one that works.

Attached is a working 0.19.1 Atmosphere created via Kefir. Hope it aids developers in identifying the issue.

[atmosphere.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6395827/atmosphere.zip)

**Comment by SciresM** [comment]
Re-open using the issue templaets.
