### ISSUE TITLE
Black Screen at start after update to 12.0.1 (Atmosphere 0.19.1)

### ISSUE THREAD

**Issue by AlejandroMHOB** [Atmosphere-NX/Atmosphere#1473]
What's the issue you encountered?
--------------------------------------
After updating Atmosphere to version 0.19.1, also updating the Hetake bootloader to version 5.5.5 (All official releases), I proceed to update the console to the latest version 12.0.1. Right after updating, when it restarts, the atmosphere logo appears and the screen goes black, having to force a hard reset to turn it off.

As I could read on other sites, atmosphere 0.19.1 is compatible with 12.0.1, but updating it stopped working. 

Crash Report
--------------
Don't generated.

System Firmware Version
---------------------------
OFW 12.0.1 / CFW Atmosphere 0.19.1 (Official release)

Environment
--------------
Bootloader hekate v5.5.5 & Nyx v1.0.2 (Official release)

**Comment by SciresM** [comment]
Re-open with the issue template actually completely filled out, instead of skipping parts of it.
