### ISSUE TITLE
Black Screen at start after update to 12.0.1 (Atmosphere 0.19.1)

### ISSUE THREAD

**Issue by AlejandroMHOB** [Atmosphere-NX/Atmosphere#1474]
What's the issue you encountered?
--------------------------------------
After updating Atmosphere to version 0.19.1, also updating the Hetake bootloader to version 5.5.5 (All official releases), I proceed to update the console to the latest version 12.0.1. Right after updating, when it restarts, the atmosphere logo appears and the screen goes black, having to force a hard reset to turn it off.

As I could read on other sites, atmosphere 0.19.1 is compatible with 12.0.1, but updating it stopped working.

How can the issue be reproduced?
--------------------------------------
From the Hekate 5.5.5 Bootloader, both starting from the Emunand main button or from the Payload section with the fusee-primary (original from 0.19.1), the result is the same; after the Atmosphere logo, the screen goes black and does not respond except hard reset. 

Crash Report
--------------
Atmosphere cannot start, so it does not generate any kind of Feedback in the corresponding folders of the SD. 

System Firmware Version
---------------------------
OFW 12.0.1 / CFW Atmosphere 0.19.1 (Official release)

Environment?
---------------
Bootloader hekate v5.5.5 & Nyx v1.0.2 (Official release)

Goldleaf 0.9
Sys-clk 1.0.1
NXthemesInstaller 2.6.1
JKSV 06.0.7.2020

Before opening the ticket, I have updated all the programs to their latest version and then tried to eliminate the different homebrew programs to see that they did not conflict due to incompatibility with new versions. 

Additional context?
---------------------
Console updated directly from 11.0.1, both OFW and CFW .

**Comment by SciresM** [comment]
Does atmosphere boot with all custom system modules removed?

**Comment by AlejandroMHOB** [comment]
No, same result, a black screen after Atmosphere's Logo :S

**Comment by SciresM** [comment]
Please post a screenshot of your /atmosphere directory, and of your /atmosphere/contents directory.

**Comment by AlejandroMHOB** [comment]
There you have it. :)

![Atmosphere](https://user-images.githubusercontent.com/83399745/116535026-91acde00-a8e3-11eb-9241-8c364576bbb6.PNG)
![Atmosphere_Contents](https://user-images.githubusercontent.com/83399745/116535027-92457480-a8e3-11eb-9f3a-91efa50eb6ca.PNG)

**Comment by SciresM** [comment]
You did not remove all custom system modules. I see three and a custom theme.

Remove them, it will solve your problem.

**Comment by AlejandroMHOB** [comment]
Please, can you tell me what I should delete specifically?

**Comment by SciresM** [comment]
Just delete everything inside /atmosphere/contents.

That'll delete the three custom sysmodules, the custom theme, and the two game mods you have.

You can add stuff back individually afterwards to determine what's the problem.

**Comment by AlejandroMHOB** [comment]
I deleted all the content from the Atmosphere / Contents folder.
Unfortunately that did not fix my problem. I keep seeing a black screen after the Atmosphere Logo.

**Comment by SciresM** [comment]
I am *very* inclined to believe this is a user error. Contact SciresM#0524 on discord, and note that this is *not* a help forum, it's a bug reporting forum.
