### ISSUE TITLE
AMS 0.19.1 Fatal Error Program ID 010...bd00 0xffe

### ISSUE THREAD

**Issue by SpaceCadet404** [Atmosphere-NX/Atmosphere#1475]
## Bug Report
Fatal Error when booting fusee-primary.bin payload.
Program ID: 010...bd00
Error Desc: std::abort() called (0xffe)

### What's the issue you encountered?
Updated from AMS 0.18.1 to 0.19.1, copied files to SD card root
Switch version 11.0.1

### How can the issue be reproduced?
Booting CFW from hekate
Booting fusee-primary.bin from hekates for recreating your issue

### Crash Report
[report_0000000009e01ced.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6398251/report_0000000009e01ced.zip)

### System Firmware Version
11.0.1

### Environment?
Hekate 5.5.5
AMS with Mesosphere
(Below has been removed, but did not resolve issue)
Checkpoint
Goldleaf
ftpd
melonDS
PPSSPP
RetroArch
devilutionx-switch

### Additional context?
I have removed most homebrew applications to see if one was causing an issue.
Does the report show any indication an app is causing the crash?

**Comment by SciresM** [comment]
Not an atmosphere issue. 

Update mission control.
