### ISSUE TITLE
Incompatibility with emuNAND (11.0.1)

### ISSUE THREAD

**Issue by Initializist** [Atmosphere-NX/Atmosphere#1476]
### What's the issue you encountered?
Switch cannot boot into EmuMMC (11.0.1) with Error code: 2002-2634, Program 010000000000001F.

### How can the issue be reproduced?
getting into cfw-EMUmmc through Hekate 5.5.5.

### Crash Report
https://gist.github.com/Initializist/03e6025140083a0b7be29da26900d207

### System Firmware Version
sysMMC: 12.0.1
EmuMMC: 11.0.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: 
  - [ Official release version 0.19.1 WITHOUT_MESOSPHERE]
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: Homebrew Appstore, Edizon, CheckPoint,

**Comment by SciresM** [comment]
Not an atmosphere bug.

you burnt the 12.x gamecard fuse, remove your gamecard.

you can never use gamecards on <12.0.0 again.

**Comment by Initializist** [comment]
Thank you!
