### ISSUE TITLE
Atmposphere doesnt boot anymore using custom override_config.ini

### ISSUE THREAD

**Issue by Redpad** [Atmosphere-NX/Atmosphere#1478]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]

### What's the issue you encountered?

Used override_config to make R button launch into applet mode from the photo album before, till atmosphere 1.7. 
Now after updating to atmosphere 1.9.1 it doesnt boot up atmosphere anymore.
Atmosphere boots fine without custom override_config.

### How can the issue be reproduced?

as stated on issue

### Crash Report

as stated on issue

### System Firmware Version

12.0.1

### Environment?

Fusee primary official release 1.7

### Additional context?

as stated on issue

**Comment by SciresM** [comment]
Please re-open with the issue template actually filled out completely, rather than simply saying "as stated".

**Comment by SciresM** [comment]
also, be sure to provide details.

"doesn't boot up atmosphere" -- what does it do? You're not providing *nearly* enough information.
