### ISSUE TITLE
error 010000000000002b

### ISSUE THREAD

**Issue by deejay87** [Atmosphere-NX/Atmosphere#1479]
Hi
0.19.2 error at start (sysnand and emummc)

![IMG_0809](https://user-images.githubusercontent.com/4148145/116745643-aa101c00-a9fb-11eb-8080-3499fbe8dac4.jpg)

**Comment by brymez1609** [comment]
I have the same Issue.

**Comment by fincs** [comment]
Please reopen after following the issue template. Otherwise we are unable to provide help.
