### ISSUE TITLE
LayeredFS function on System titles?

### ISSUE THREAD

**Issue by torunado** [Atmosphere-NX/Atmosphere#148]
I tested layeredFS function on few games, but it didn't work on system titles.
Is it just because Atmosphere doesn't support that?

**Comment by simonmkwii** [comment]
Yeah, it would be nice!
I want to replace the album icon with a homebrew one 😄

**Comment by darvell** [comment]
Pure theory but I think the MitM is registered too late to handle any of the system titles. Also UI elements aren't part of the system titles per se and more part of the OS itself.

**Comment by thomasnet-mc** [comment]
Try with modifying the function should_mitm (it's an inline so in a header file, don't remember which one).

**Comment by parrotgeek1** [comment]
it's stratosphere/fs_mitm/source/fsmitm_service.hpp Line 23 
that's definitely why it's not working.

**Comment by simonmkwii-dev** [comment]
@darvell Considering it's run as a KIP (kernel initial process), it gets registered during kernel initialisation, therefore any sysmodule or sysapplet with a RomFS section (with TID >= 0x0100000000000006) should be patchable.

**Comment by SciresM** [comment]
Support was added for this in  https://github.com/Atmosphere-NX/Atmosphere/commit/cd42f6dc18347e5e5a967c298c6caf4efd1e440c
