### ISSUE TITLE
The Software was closed because an error occurred

### ISSUE THREAD

**Issue by NaturalHarmonia** [Atmosphere-NX/Atmosphere#1480]
### What's the issue you encountered?

When playing Monster Hunter Rise I often get the "The software was closed because an error occurred" error since I updated my Switch firmware to 12.0.1 and Monster Hunter Rise to 2.0.0. The only changes I've made to Atmosphere was updating to 0.19.2.

The issue can be reproduced just by playing the game naturally or by going to the weapons shop and creating decorations and then exiting and/or trying to set the decoration. 

I don't see a crash report folder but I do see a fatal error folder with nothing in it and the erpt_folder with files that are not supported.

System firmware is 12.0.1.

Atmosphere was launched by fusee
The Atmosphere release I used was official.
Kip patches? Yes I do believe I have additional kip_patches.
I have some apps like Edizon, Goldleaf, and etc. installed.

**Comment by SciresM** [comment]
Re-open using the issue template completely filled out properly, please.

And "files that are not supported." <-- not relevant, upload them to a file host. I can't help you without crash reports.
