### ISSUE TITLE
Black screen on boot with hidden partition emuNAND clean install with Kingston Canvas React SD card

### ISSUE THREAD

**Issue by Solo761** [Atmosphere-NX/Atmosphere#1484]
## Bug Report

After I inquired about SD card compatibilty and Atmosphere some people suggested I should report an issue.

### What's the issue you encountered?

I tried installing Atmosphere on hidden partition emuNAND on **Kingston Canvas React 256GB** microSD card. When setup is done and I try running fusee-primary.bin payload, I get Athosphere bootscreen, everything looks fine, but after Nin/switch logo it stays at black screen.

### How can the issue be reproduced?

My procedure was to repartition SD card with Hekate 5.5.5, then use Hekate to copy sysNAND to emuNAND and either push fusee-primary.bin, or if I set up hekate-ipl.ini, start from hekate. 

In both cases it was the same, black screen after nin/switch logo. I tried with SD formatted as FAT32 and exFAT (switch has exFAT driver in sysNAND so it reads both).

Tried same procedure on Samsaung Evo 128GB microSD and it worked fine on first try, booted fine. 

As last resort I tried reformatting the card as one partition and using file base emuNAND and this worked without problems on this same Kingston card. Only hidden partition emuNAND seems to be the problem.

### System Firmware Version

7.0.1

SysNAND is at this version, never been CFWed, Hekate created emuNAND from this system version
</br>

### Environment?

- Tried to boot Atmosphere through fusee payload from Atmosphere itself and Hekate 5.5.5.
- Atmosphere was 0.19.2., latest version (at the moment of writing), no other addons, mods or homebrew.

### Additional context?

- Here's Hekate SD card info if that could help give some clue. Card was store bought from reputable store two years ago. Has been used in this same switch without problems (and still works, if I don't use emuNAND in partition option).
I've only blanked last three characters of S/N. 

![nyx20200411_010553](https://user-images.githubusercontent.com/15979695/117142213-bc010e80-adaf-11eb-800b-44c50e077ced.png)

**Comment by SciresM** [comment]
This seems almost certainly like an emummc/sd driver issue, not an atmosphere issue. Open an issue on the emummc repo?
