### ISSUE TITLE
Patch for "control.nacp" on a specific title

### ISSUE THREAD

**Issue by OperationNT414C** [Atmosphere-NX/Atmosphere#1488]
#### Overview:

Being able to override some properties of "control.nacp" for a specific title

#### Smaller Details: 

Add an "ini" file in "/atmosphere/contents/titleID" which describes the list of settings that we wish to override (or maybe directly the raw "control.nacp" file but it will be less user-friendly)

#### Nature of Request:  

Addition

### What component do you feel this would best fit within?

Probably the same component as layered FS ?

### Why would this feature be useful?

A plugin could require that a specific service is enabled. For example, the "nx-btred" plugin (which allow to use Bluetooth headset) needs that the game activates "audrec:u" service: https://github.com/plutooo/nx-btred
It can be done by having the video capture flag set to 0x02: https://switchbrew.org/wiki/NACP

**Comment by OperationNT414C** [comment]
Ok, thank you for your feedback.
Indeed, it seems that video capture is enough for nx-btred.

**Comment by cucholix** [comment]
Is there any reason why you are against ncapdm override?
