### ISSUE TITLE
Atmosphère 0.19.2 won't wake up from sleep mode (black screen)

### ISSUE THREAD

**Issue by ncend** [Atmosphere-NX/Atmosphere#1489]
### What's the issue you encountered?

Atmosphere does not wake from sleep mode, it goes black screen whenever it reach sleep mode (by pressing the power button or by waiting the sleep timer). It requiring the power button to be held until system shuts down (held for about 12 secs). This happens any time the system is put into sleep mode. Placing the switch in the dock also make the screen black and hang.

### How can the issue be reproduced?

Put the system into sleep mode via power button, home menu, or by placing the switch into the dock.

### Crash Report

No crash report generated.

### System Firmware Version

12.0.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:  launched by SX Gear
- Official release or unofficial build:  Atmosphère 0.19.2
- Do you have additional kips or sysmodules you're loading: none
- Homebrew software installed: Daybreak, Retroach, Goldleaf

### Additional context?

N/A

**Comment by Masamune3210** [comment]
Piracy tools are not supported
