### ISSUE TITLE
Crash reports fail to generate

### ISSUE THREAD

**Issue by CraftyBoss** [Atmosphere-NX/Atmosphere#1490]
### What's the issue you encountered?

While working on creating an exeFS mod for Super Mario Odyssey v1.0.0, I needed to study Atmosphère's crash logs that should be generated upon a game crash, from what I understand. However, when accessing my switch through FTP using sys-ftpd-light, I found that no crash reports were generated for SMO. I then checked the SD card itself by mounting it to my PC. Again, nothing there. So, I tried forcing a crash in a separate game (Super Mario 3D World + Bowsers Fury), by simply taking the main NSO from Odyssey and placing it in the exeFS folder for SM3DW, which instantly crashes the game upon loading it. This caused Atmosphère to generate a crash report. So I tried the same thing with Odyssey, except using SM3DW's main NSO instead. This also caused Atmosphère to generate a crash report. So, I figured Atmosphère might not be generating a crash report for the specific crash that I was experiencing. However, after sending the exact same mod to someone else (GRAnimated), I found their Atmosphère was generating crash reports for my mod just fine. However, they were using a dev build of HOS on 9.0.1, on the latest atmosphere version (they say their Atmosphère version is a dev build from 4/30). </br>

### How can the issue be reproduced?

</br>
Unkwown, issue possibly started when I updated atmosphere versions and never noticed until recently.</br>

### Crash Report

N/A</br>

### System Firmware Version

12.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build:  Official release version M.19.2
- Do you have additional kips or sysmodules you're loading: sys-ftpd-light
- Homebrew software installed: Edizon SE, Goldleaf 0.9.0, nx-ovlloader, Tesla-Menu, HB Appstore, Checkpoint, ChoiDujour, gcdumptool, IPSwitch, Lockpick, MissionControl, mtp-server-nx, NXShell, SkyNX, Switch_Themes_Installer, JKSV

### Additional context?

- I'm using a fork of the code injection tool, Starlight, to create these code modifications. It generates an IPS patch as well as an NSO used in place of subsdk.
- I'm running an emuNAND for all my SMO mod content, with my sysNAND being completely vanilla (not banned).

**Comment by SciresM** [comment]
Make sure that user exception handlers are disabled, other than that there's kind of nothing atmosphere can actually do.
