### ISSUE TITLE
Insistent Data Abort

### ISSUE THREAD

**Issue by WindTheGuy** [Atmosphere-NX/Atmosphere#1494]
### What's the issue you encountered?

i was using the eShop on stock firmware to install a game demo,and my console accidentally updated to 12.0.1. after that,i downgraded my console back to the version it had,11.0.1,but now,after a while of use,data aborts suddenly happen,and I'm forced to reboot the console. </br>
i used to have GomaNX on my console,but i already removed it and replaced it with a clean Atmosphere. didn't solve the problem.</br>

### How can the issue be reproduced?

[ * ]</br>
by simply booting the console,no matter the fusee,and waiting for a while. happens faster the longer a game is open.</br>

### Crash Report

due to adding a clean Atmosphere recently,the crash report was deleted. I'll add it in a comment once the error happens again.</br>

### System Firmware Version

11.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Fusèe-primary
- Official release or unofficial build: 0.19.2 (latest)
- Do you have additional kips or sysmodules you're loading: not that i know about.
- Homebrew software installed: ChoiDujourNX,Daybreak,EdiZon SE,ftpd pro 3.0.0,Goldleaf,HB App Store,NX-Shell,nxdumptool,sys-clk manager.

### Additional context?

- Additional info about your environment: none

**Comment by WindTheGuy** [comment]
here you go. i hope this helps. sorry for taking too long

[reports.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6491239/reports.zip)

**Comment by SciresM** [comment]
Huh! This is actually a really, really interesting bug, thank you.

It will be fixed in the next atmosphere release, but I'll need to think about how best to solve the problem.
