### ISSUE TITLE
Atmosphère 0.19.2 breaks with Update 12.0.2

### ISSUE THREAD

**Issue by CarlosRamirezGriego** [Atmosphere-NX/Atmosphere#1495]
### What's the issue you encountered?

For the sake of science (Ok, it was by mistake), I updated the CFW console and the 12.0.2 patch was installed.
This broke the latest version of Atmosphere.

### How can the issue be reproduced?

Have installed 0.19.2.
Update the console to 12.0.2
I was send back to the Atmosphere main page, there I selected to launch CFW using Fusee
I got an error.

### Crash Report

Couldnt get it

### System Firmware Version

12.0.2

**Comment by Masamune3210** [comment]
Restore from a backup or wait, simple as that. Its mostly expected that new updates will break atmos

**Comment by CarlosRamirezGriego** [comment]
> Restore from a backup or wait, simple as that. Its mostly expected that new updates will break atmos

Yeah, I have no rush, I will wait for the team to release a newer version. Just thought about warning other people with this bug xD

**Comment by maheer461** [comment]
Thank you for the heads up :)

**Comment by xdinko** [comment]
any update? i tried with hekate v5.5.6 & Nyx v1.0.3 but after boot go in error with
**Fatal error: [NXBOOT] Unable to identify package!**

**Comment by WokerLOL** [comment]
So I was not able to run any games because I "had to" install the newest firmware. How would you go about installing it without removing AutoRCM and not bugging Atmosphere ofc?

**Comment by SciresM** [comment]
Yeah this doesn't need a separate user issue.
