### ISSUE TITLE
Fatal error occurring constantly

### ISSUE THREAD

**Issue by Fudgecake4567** [Atmosphere-NX/Atmosphere#1496]
**What's the issue you encountered?**

a fatal error occurred while running atmosphere, program id 0100000000000005, error desc "std::abort() called (0xffe)"

**How can the issue be reproduced?**

loading into Hekate and launching atmosphere from launch menu or fusee-primary

**Crash Report**

A fatal error occurred while running Atmosphere.
Program ID: 0100000000000005
Error Desc: std::abort() called (0xffe)
*generic log location*
Press POWER to reboot

[errorreport.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6466003/errorreport.zip)

**System Firmware Version**

not actually sure, it may have updated on its own but i don't know

**Comment by WokerLOL** [comment]
So I sadly made the exact same mistake you did. You did auto update the system firmware while in Atmosphere. You now have to wait for the devs to make the CFW support the newest firmware. Do not boot anything now as there is a high chance you can brick your console.

**Comment by Fudgecake4567** [comment]
okay, tell me if you ever get it working

**Comment by WokerLOL** [comment]
Have you made a backup of your nand? If you did, launch into Hekate and restore it if you don't want to wait.

**Comment by SciresM** [comment]
Re-open with the issue template actually fully filled out, it's missing information.
