### ISSUE TITLE
Cartridge games won't be read correctly 

### ISSUE THREAD

**Issue by KAZAMMLE** [Atmosphere-NX/Atmosphere#1497]
I installed the atmosphere and hekate update and it fixed my fatal error issue and everything is working again except cartridge games that cannot be read anymore. there is an error message 

"The game card could not be read
Please remove it and reinsert it.

If this message appears repeatedly, it may mean the game card or the console is malfunctioning.

Visit the nintendo support yadayda........"

Then again. My three cartridge game won't work and all this since the updates.

**Comment by CypherNoodle** [comment]
Try Disable autoNoGc in hekate

**Comment by SciresM** [comment]
1) You did not use the issue templates
2) Disable nogc in config.
