### ISSUE TITLE
Constant Crash when loading an Owned Game

### ISSUE THREAD

**Issue by KaiserTialoc** [Atmosphere-NX/Atmosphere#1499]
I Keep getting this crash when trying to open a copy of Pokemon Shield that i bought and downloaded from the eShop

I was playing the game until 20 minutes ago and then realised there was a system update and needed to update my atmosphere build aswell so i did all that and dowloaded the new fusee.bin

![IMG_7406](https://user-images.githubusercontent.com/67152067/118031740-c8143f80-b35e-11eb-9d70-1d3a602af0c8.jpg)

I am also using the ldn_mitm 1.8.0 on this switch if that make a difference and Pokemon Shield is on v.1.3.2

any help would be appreciated

**Comment by nwhiteman42** [comment]
Reopen with the issue template filled out

**Comment by SciresM** [comment]
Re-open with issue template filled out.
