### ISSUE TITLE
Could somebody write a instruction of Atmosphere？

### ISSUE THREAD

**Issue by quank123wip** [Atmosphere-NX/Atmosphere#150]
Maybe I can write one in Chinese:) @SciresM

**Comment by quank123wip** [comment]
Maybe a user guide?I don't know,but I can help you write one after it released.

**Comment by tumGER** [comment]
Instructions will come once it's out - It's still under development and unfinished

**Comment by Benoit7413** [comment]
Documenting the source code is a good idea actually (configuration, input files, build requirements, functions and objects usage etc...)

**Comment by hexkyz** [comment]
In depth documentation and user guides are planned to be published for the first usable build of Atmosphère.
