### ISSUE TITLE
Fatal error occurs while launching atmosphere

### ISSUE THREAD

**Issue by Fudgecake4567** [Atmosphere-NX/Atmosphere#1500]
### What's the issue you encountered?
Atmosphere encounters a fatal error on attempting to launch, ofw just stays at a black screen until i reboot.
error occurs on launch after the atmosphere logo appears onscreen, and it says that there is an error with program id 0100000000000005, error desc std::abort() called (0xffe)
[ Did you make any changes related to Atmosphère itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

by launching atmosphere,
on hekate selecting and launching any of the cfw or ofw versions, it will either refuse to load or crash before allowing me to do anything.

### Crash Report

[report.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6468757/report.zip)

### System Firmware Version

I do not know my firmware version because i am unable to boot into either cfw or ofw, but i believe im on one of the newest firmwares

### Environment?

- latest version of hekate launched from tegrarcm on my computer
- using latest official release (0.19.3)
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: N/A
- EmuMMC or SysNAND: SysNAND

### Additional context?

- Additional info about your environment: fat32 256 gb sd card, lost nand backup in hard drive crash.

**Comment by SciresM** [comment]
i2c::ResultNoAck() in boot sysmodule, while doing setup.

If OFW fails, I don't think this is an atmosphere problem -- I think you have some hardware issue.
