### ISSUE TITLE
Constant Crash when trying to play game

### ISSUE THREAD

**Issue by KaiserTialoc** [Atmosphere-NX/Atmosphere#1501]
### What's the issue you encountered?

Console crashes when trying to play a game, the game is a legit owned copy of Pokemon Shield bought from the eShop last year
It was working completely fine earlier today.

i had been working on a shiny den to be used with the sysbot and i finally got the Shiny seed i wanted, that was when i perfomred the latest system update and then i updated atmoshphere and hekate
after the update when i launch Pokemon Shield, as soo as the save loads the console crashes

### How can the issue be reproduced?

Happens everytime i launch the game

### Crash Report

Atmosphère Crash Report (v1.5):
Mesosphere:                      Disabled
Result:                          0x290 (2144-0001)

Process Info:
    Process Name:                qlaunch
    Program ID:                  0100000000001000
    Process ID:                  0000000000000081
    Process Flags:               000010b7
    User Exception Address:      0000001ce5b77000
Exception Info:
    Type:                        User Break
    Address:                     000000559244ea44 (qlaunch.nss + 0x24ea44)
    Break Reason:                0x0
    Break Address:               00000007900fb868
    Break Size:                  0x4
Crashed Thread Info:
    Thread ID:                   000000000000020d
    Stack Region:                00000007900f8000-00000007900fc000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000007900fb868
        X[02]:                   0000000000000004
        X[03]:                   0000000000000008
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000007900fb6a0
        LR:                      000000559240ea28 (qlaunch.nss + 0x20ea28)
        SP:                      00000007900fb6a0
        PC:                      000000559244ea40 (qlaunch.nss + 0x24ea40)
    Stack Trace:
        ReturnAddress[00]:       000000559240dfd8 (qlaunch.nss + 0x20dfd8)
        ReturnAddress[01]:       000000559240e098 (qlaunch.nss + 0x20e098)
        ReturnAddress[02]:       000000559228c7b4 (qlaunch.nss + 0x8c7b4)
        ReturnAddress[03]:       0000005592292164 (qlaunch.nss + 0x92164)
        ReturnAddress[04]:       0000005592292208 (qlaunch.nss + 0x92208)
        ReturnAddress[05]:       0000005592b52470 (qlaunch.nss + 0x952470)
        ReturnAddress[06]:       0000005592b28788 (qlaunch.nss + 0x928788)
        ReturnAddress[07]:       000000559253c9b0 (qlaunch.nss + 0x33c9b0)
        ReturnAddress[08]:       000000559253c1dc (qlaunch.nss + 0x33c1dc)
        ReturnAddress[09]:       00000055923f1618 (qlaunch.nss + 0x1f1618)
        ReturnAddress[10]:       00000055923f4884 (qlaunch.nss + 0x1f4884)
        ReturnAddress[11]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0007900fb6a0 80 b7 0f 90 07 00 00 00 d8 df 40 92 55 00 00 00
                                 0007900fb6b0 03 00 00 00 07 00 00 00 20 b7 0f 90 07 00 00 00
                                 0007900fb6c0 23 8c d6 92 55 00 00 00 23 8c d6 92 55 00 00 00
                                 0007900fb6d0 23 8c d6 92 55 00 00 00 00 00 00 00 55 00 00 00
                                 0007900fb6e0 90 02 00 00 55 00 00 00 00 00 00 00 00 00 00 00
                                 0007900fb6f0 03 00 00 00 07 00 00 00 20 b7 0f 90 07 00 00 00
                                 0007900fb700 23 8c d6 92 55 00 00 00 23 8c d6 92 55 00 00 00
                                 0007900fb710 23 8c d6 92 55 00 00 00 00 00 00 00 55 00 00 00
                                 0007900fb720 23 8c d6 92 55 00 00 00 20 b8 0f 90 07 00 00 00
                                 0007900fb730 00 00 00 00 00 00 00 00 18 03 23 93 55 00 00 00
                                 0007900fb740 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0007900fb750 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0007900fb760 00 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00
                                 0007900fb770 e0 b8 0f 90 07 00 00 00 30 d9 23 93 55 00 00 00
                                 0007900fb780 40 b8 0f 90 07 00 00 00 98 e0 40 92 55 00 00 00
                                 0007900fb790 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 0000002381382e00
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 002381382e00 02 00 00 00 00 00 00 00 01 00 00 00 81 00 00 00
                                 002381382e10 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382e20 00 10 00 00 00 00 00 01 02 00 00 00 00 00 00 00
                                 002381382e30 90 02 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382e40 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382e50 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382e60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382e70 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382e80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382e90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382ea0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382eb0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382ec0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382ed0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382ee0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 002381382ef0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           1
    Module 00:
        Address:                 0000005592200000-0000005592ba3000
        Name:                    qlaunch.nss
        Build Id:                5937834AA1D0D40A4216C0A7503A83423E0E0D3A000000000000000000000000
Thread Report:
Number of Threads:               15
Threads[00]:
    Thread ID:                   00000000000001f2
    Stack Region:                000000073b217000-000000073b277000
    Registers:
        X[00]:                   0000000000fe4d85
        X[01]:                   000000000004e1f3
        X[02]:                   00000000ffffffff
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      000000073b276710
        LR:                      0000005592b86ef4 (qlaunch.nss + 0x986ef4)
        SP:                      000000073b2766a0
        PC:                      000000559244e920 (qlaunch.nss + 0x24e920)
    Stack Trace:
        ReturnAddress[00]:       0000005592b86be8 (qlaunch.nss + 0x986be8)
        ReturnAddress[01]:       000000559251cd58 (qlaunch.nss + 0x31cd58)
        ReturnAddress[02]:       00000055926d41e4 (qlaunch.nss + 0x4d41e4)
        ReturnAddress[03]:       000000559228ff4c (qlaunch.nss + 0x8ff4c)
        ReturnAddress[04]:       0000005592351084 (qlaunch.nss + 0x151084)
        ReturnAddress[05]:       00000055922000d4 (qlaunch.nss + 0xd4)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00073b2766a0 05 00 00 00 55 00 00 00 28 34 7e 93 55 00 00 00
                                 00073b2766b0 d0 66 27 3b 07 00 00 00 88 df 51 92 55 00 00 00
                                 00073b2766c0 48 34 7e 93 55 00 00 00 f8 32 7e 93 55 00 00 00
                                 00073b2766d0 f0 66 27 3b 07 00 00 00 88 df 51 92 55 00 00 00
                                 00073b2766e0 00 00 28 93 55 00 00 00 f8 32 7e 93 55 00 00 00
                                 00073b2766f0 00 30 18 93 55 00 00 00 60 83 3b 93 55 00 00 00
                                 00073b276700 00 b0 79 03 00 00 00 00 60 83 3b 93 55 00 00 00
                                 00073b276710 c0 6c 27 3b 07 00 00 00 e8 6b b8 92 55 00 00 00
                                 00073b276720 01 00 00 00 00 00 00 00 00 30 18 93 55 00 00 00
                                 00073b276730 ef 26 d4 92 55 00 00 00 6d 65 6d 6f 72 79 69 6e
                                 00073b276740 66 6f 00 00 00 00 00 00 02 00 9a 01 00 00 00 00
                                 00073b276750 06 41 28 c0 00 00 00 00 00 10 00 00 00 00 00 01
                                 00073b276760 b0 67 27 3b 07 00 00 00 95 04 00 00 00 00 00 00
                                 00073b276770 03 00 00 00 00 00 00 00 f8 88 1e 93 55 00 00 00
                                 00073b276780 8c 67 27 3b 07 00 00 00 1f 00 00 00 6d 65 6d 6f
                                 00073b276790 72 79 69 6e 66 6f 00 00 20 a5 37 92 55 00 00 00
    TLS Address:                 0000001ce5b77200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 001ce5b77200 00 00 00 00 09 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77210 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77220 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77230 81 00 00 00 00 00 00 00 84 4e 00 00 00 00 00 00
                                 001ce5b77240 00 10 00 00 00 00 00 01 00 00 00 00 00 00 00 00
                                 001ce5b77250 10 00 00 00 e0 64 27 3b 07 00 10 00 00 00 00 00
                                 001ce5b77260 09 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00
                                 001ce5b77270 00 00 00 00 00 00 00 00 f0 40 27 3b 07 00 00 00
                                 001ce5b77280 70 a6 3a 92 55 00 00 00 b0 42 80 93 55 00 00 00
                                 001ce5b77290 90 97 9d 93 55 00 00 00 ff ff ff ff 00 00 00 00
                                 001ce5b772a0 00 00 00 00 00 00 00 00 b0 70 9d 93 55 00 00 00
                                 001ce5b772b0 08 54 29 94 55 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b772c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b772d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b772e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b772f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Threads[01]:
    Thread ID:                   00000000000001f4
    Stack Region:                00000007768ce000-00000007768cf000
    Registers:
        X[00]:                   00000055933b67c8
        X[01]:                   00000055933b67d0
        X[02]:                   00000000000481f7
        X[03]:                   ffffffffffffffff
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000007768ceef0
        LR:                      00000055923f53d0 (qlaunch.nss + 0x1f53d0)
        SP:                      00000007768ceed0
        PC:                      000000559244e9f0 (qlaunch.nss + 0x24e9f0)
    Stack Trace:
        ReturnAddress[00]:       00000055923f02ec (qlaunch.nss + 0x1f02ec)
        ReturnAddress[01]:       000000559253c8ac (qlaunch.nss + 0x33c8ac)
        ReturnAddress[02]:       000000559253c990 (qlaunch.nss + 0x33c990)
        ReturnAddress[03]:       000000559253c1dc (qlaunch.nss + 0x33c1dc)
        ReturnAddress[04]:       00000055923f1618 (qlaunch.nss + 0x1f1618)
        ReturnAddress[05]:       00000055923f4884 (qlaunch.nss + 0x1f4884)
        ReturnAddress[06]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0007768ceed0 38 ef 8c 76 07 00 00 00 00 00 00 00 00 00 00 00
                                 0007768ceee0 c8 67 3b 93 55 00 00 00 90 67 3b 93 55 00 00 00
                                 0007768ceef0 20 ef 8c 76 07 00 00 00 ec 02 3f 92 55 00 00 00
                                 0007768cef00 00 00 00 00 00 00 00 00 cc 81 3b 93 55 00 00 00
                                 0007768cef10 90 67 3b 93 55 00 00 00 60 67 3b 93 55 00 00 00
                                 0007768cef20 40 ef 8c 76 07 00 00 00 ac c8 53 92 55 00 00 00
                                 0007768cef30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0007768cef40 60 ef 8c 76 07 00 00 00 90 c9 53 92 55 00 00 00
                                 0007768cef50 00 00 00 00 00 00 00 00 60 67 3b 93 55 00 00 00
                                 0007768cef60 80 ef 8c 76 07 00 00 00 dc c1 53 92 55 00 00 00
                                 0007768cef70 20 80 3b 93 55 00 00 00 c8 81 3b 93 55 00 00 00
                                 0007768cef80 b0 ef 8c 76 07 00 00 00 18 16 3f 92 55 00 00 00
                                 0007768cef90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0007768cefa0 00 00 00 00 00 00 00 00 20 80 3b 93 55 00 00 00
                                 0007768cefb0 d0 ef 8c 76 07 00 00 00 84 48 3f 92 55 00 00 00
                                 0007768cefc0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 0000001ce5b77400
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 001ce5b77400 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77410 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77420 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77430 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77440 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77450 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77460 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77470 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77480 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77490 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b774a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b774b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b774c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b774d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b774e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b774f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Threads[02]:
    Thread ID:                   00000000000001f6
    Stack Region:                0000000745b33000-0000000745b43000
    Registers:
        X[00]:                   00000055937e3b98
        X[01]:                   00000055937e3ba0
        X[02]:                   00000000000a81ec
        X[03]:                   ffffffffffffffff
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      0000000745b42ef0
        LR:                      00000055923f53d0 (qlaunch.nss + 0x1f53d0)
        SP:                      0000000745b42ed0
        PC:                      000000559244e9f0 (qlaunch.nss + 0x24e9f0)
    Stack Trace:
        ReturnAddress[00]:       00000055923f02ec (qlaunch.nss + 0x1f02ec)
        ReturnAddress[01]:       000000559253c8ac (qlaunch.nss + 0x33c8ac)
        ReturnAddress[02]:       000000559253c9bc (qlaunch.nss + 0x33c9bc)
        ReturnAddress[03]:       000000559253c1dc (qlaunch.nss + 0x33c1dc)
        ReturnAddress[04]:       00000055923f1618 (qlaunch.nss + 0x1f1618)
        ReturnAddress[05]:       00000055923f4884 (qlaunch.nss + 0x1f4884)
        ReturnAddress[06]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 000745b42ed0 38 2f b4 45 07 00 00 00 54 06 3f 92 55 00 00 00
                                 000745b42ee0 98 3b 7e 93 55 00 00 00 60 3b 7e 93 55 00 00 00
                                 000745b42ef0 20 2f b4 45 07 00 00 00 ec 02 3f 92 55 00 00 00
                                 000745b42f00 00 00 00 00 00 00 00 00 cc 41 7f 93 55 00 00 00
                                 000745b42f10 60 3b 7e 93 55 00 00 00 30 3b 7e 93 55 00 00 00
                                 000745b42f20 40 2f b4 45 07 00 00 00 ac c8 53 92 55 00 00 00
                                 000745b42f30 60 3b 7e 93 55 00 00 00 30 3b 7e 93 55 00 00 00
                                 000745b42f40 60 2f b4 45 07 00 00 00 bc c9 53 92 55 00 00 00
                                 000745b42f50 00 00 00 00 00 00 00 00 30 3b 7e 93 55 00 00 00
                                 000745b42f60 80 2f b4 45 07 00 00 00 dc c1 53 92 55 00 00 00
                                 000745b42f70 20 40 7f 93 55 00 00 00 c8 41 7f 93 55 00 00 00
                                 000745b42f80 b0 2f b4 45 07 00 00 00 18 16 3f 92 55 00 00 00
                                 000745b42f90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 000745b42fa0 00 00 00 00 00 00 00 00 20 40 7f 93 55 00 00 00
                                 000745b42fb0 d0 2f b4 45 07 00 00 00 84 48 3f 92 55 00 00 00
                                 000745b42fc0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 0000001ce5b77600
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 001ce5b77600 00 00 00 00 0d 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77610 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77620 53 46 43 4f 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77630 25 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77640 1c 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77650 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77660 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77670 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77680 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b77690 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b776a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b776b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b776c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b776d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b776e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 001ce5b776f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Threads[03]:
    Thread ID:                   00000000000001f7
    Stack Region:                000000078cc0f000-000000078cc23000
    Registers:
        X[00]:                   0000005593960c54
        X[01]:                   0000005593960c58
        X[02]:                   00000000000b01eb
        X[03]:                   ffffffffffffffff
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000

### System Firmware Version

12.0.2/AMS M.19.3/S</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Fusee
- Official release or unofficial build: 19.3.0
- Do you have additional kips or sysmodules you're loading: ldn_mitm 1.8.0
- Homebrew software installed: JKSV, Checkpoint (although not working), EdiZon, FTPD Pro 3.0.0, Daybreak, NXDumptool
- EmuMMC or SysNAND: SysNAND

### Additional context?

Image for context of the onscreen error

![IMG_7406](https://user-images.githubusercontent.com/67152067/118037511-dc0f6f80-b365-11eb-998a-afcbbd2dddd5.jpg)

**Comment by SciresM** [comment]
The crash report you pasted is unrelated to the crash you describe/took an image of.

ldn_mitm has some issues with latest atmosphere, remove ldn_mitm to stop getting the crash.

**Comment by KaiserTialoc** [comment]
This is the crash report from the location the screen directs me to

apologies in advance however the file is in .bin format so i zipped it to be able to post it here

[report_00000000599c9a05.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6468935/report_00000000599c9a05.zip)
