### ISSUE TITLE
Cartridges don't load in Atmosphere, but work fine when booting stock

### ISSUE THREAD

**Issue by Uzephi** [Atmosphere-NX/Atmosphere#1503]
### What's the issue you encountered?

Updated to 12.0.2, Updated Atmosphere without Mesosphere 19.3, Updated to Hekate 5.5.6. Booting CFW causes the error below. Stock loads Carts fine.
"The game card could not be read
Please remove and reinsert it"
[ Did you make any changes related to Atmosphère itself? ]</br>
No.

### How can the issue be reproduced?

I did a clean install of Atmosphere and removed all other files except the ones that get moved to the SD card from the Atmosphere zip and the Hekate zip files. Still cannot load cartridges in Atmosphere.

### Crash Report

N/A

### System Firmware Version

12.0.2</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 
- Official release or unofficial build: Official 5.5.6
- Do you have additional kips or sysmodules you're loading: No, clean install.
- Homebrew software installed: [ * ] None, cleared out SD card to make sure it wasn't a homebrew app issue.
- EmuMMC or SysNAND: SysNAND

### Additional context?

- Additional info about your environment:
Cartridges tried: Zelda: Links Awakening, Zelda: BotW, Pokemon Sword, Let's Go Eevee, and Yoshi's Crafted World.
All worked fine when choosing the "boot to stock" option in Hekate.

**Comment by SciresM** [comment]
Disable nogc.
