### ISSUE TITLE
Game stopped working

### ISSUE THREAD

**Issue by Ashuraka** [Atmosphere-NX/Atmosphere#1505]
### What's the issue you encountered?

[ Bravely Default 2 stopped working as of the latest switch update. Fails to load with an unable to load data message saying to go back to main menu and try again. ]</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Updated to latest versions of Atmosphere and switch  ]</br>

**Comment by SciresM** [comment]
Re-open using a completely filled out issue template.
