### ISSUE TITLE
Just updated to 12.2 on accident and can't go back.

### ISSUE THREAD

**Issue by jkbirds** [Atmosphere-NX/Atmosphere#1506]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</ I just drag and drop the recent files for 19.3 and used the latest Fusee but after it attempt to go to the home page it crashes and gives me the Fatal error 0100000000000004, left an image at the bottom. Don't know what to do next.  >
[ Did you make any changes related to Atmosphère itself? ]</ No>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

12.0.2</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Official release version fusèe]
  - 
![20210512_172950](https://user-images.githubusercontent.com/84109858/118077287-af108c00-b368-11eb-834c-5280d5f4fb06.jpg)

**Comment by SciresM** [comment]
Remove custom sysmodules, wait for them to update.
