### ISSUE TITLE
Changes in Atmosphere ?

### ISSUE THREAD

**Issue by manzipan** [Atmosphere-NX/Atmosphere#1507]
Thanks for the update of checkpoint is there any major changes in atmosphere?  0.19.3 and fw12.0.2 since the update i cant get your release of checkpoint to work anymore...

it was so great having it working again on 12.0.0 is there a posibility for 12.0.2 atmo 0.19.3

**Comment by Aura314** [comment]
Checkpoint works on 12.0.2 and ams 19.3 you have to hold down R and start a game that you come to the homebrew menu and from there start checkpoint and not from the album.
