### ISSUE TITLE
Hekate in readme

### ISSUE THREAD

**Issue by GomiHiko** [Atmosphere-NX/Atmosphere#151]
The hekate link provided in the readme is dead since nwert deleted/privated his repo. You might want to either remove it or point it to CTCaer's.

**Comment by quank123wip** [comment]
emmmm，we need @SciresM

**Comment by tumGER** [comment]
You could make a pull request, I don't see the reason for the Issue nor for the Scires ping.

**Comment by gerd2002** [comment]
See #152 for this.

**Comment by hexkyz** [comment]
Replied in #152.
