### ISSUE TITLE
Error code 2144-0001

### ISSUE THREAD

**Issue by ralfonso35** [Atmosphere-NX/Atmosphere#1511]
## Bug Report

I am getting Error code 2144-0001. I just updated to the latest software of atmosphere

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ 1- I updated my switch to the latest software. I uploaded the latest atmosphere software. When I clicked on albums, it gave me Error code 2144-0001]</br>
[ Did you make any changes related to Atmosphère itself? I did not make any changes to atmosphere. This was my first time performing the install of a software  ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue.I followed the steps in downloading the sdsetupzip file and dragging hekate to my dad card and atmosphere, boot loader, sept, switch.

the upload was successful and when going to my album the error occured ]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

12.0.2</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate 
- Official release or unofficial build: 
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND:
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by Masamune3210** [comment]
Try again, and this time dont ignore the issue template. Its there for a reason

**Comment by yanisdreemurr** [comment]
![image](https://user-images.githubusercontent.com/46537034/119161349-861f8380-ba59-11eb-9d3b-a8857e450e08.png)

I think that it comes from a file which was badly update, make sure you have removed the file "Atmosphere", "sept" and "switch" and to have put the new release of atmosphere
