### ISSUE TITLE
Error Code: 2002-3502 (0x1b5c02)

### ISSUE THREAD

**Issue by yaelboy36** [Atmosphere-NX/Atmosphere#1512]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>

I was playing The Legend of Zelda when suddenly the switch crashed. It shows me this error.

[ Did you make any changes related to Atmosphère itself? ]</br>

No, my emunand is on 11.0.1 and everytime I enter it always crashes.

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]</br>

Everytime I enter to atmosphere on my EmuMMC it crashes after some seconds.

### Crash Report

https://gist.github.com/yaelboy36/4e19b26a13ba311c3bf17d8440f9e2d1

### System Firmware Version

12.0.2 SysNAND, 11.0.1 EmuNAND</br>

### Environment?

I was using atmosphere fusee primary, but I tried also with hekate and stills not working.
Atmosphere Official release 0.19.3

- Official release or unofficial build: Official release 0.19.3

- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND: EmuMMC - Partition-based
 
### Additional context?

- Additional info about your environment:
I already erased themes and I don't know what else to do. I don't want to recreate an emuNand because I will lose all the saves of my games.

**Comment by yaelboy36** [comment]
![WhatsApp Image 2021-05-15 at 11 40 20 PM](https://user-images.githubusercontent.com/84259442/118385878-99a19900-b5d8-11eb-9f03-5a3a2bdbaf2a.jpeg)

**Comment by shaneshanekavanagh** [comment]
Having a similar issue myself. I'm on 10.2.0 cfw Emu, and 12.0.2 ofw. It's a Mariko switch with an sxos chip. ofw works perfect.

![20210518_210840](https://user-images.githubusercontent.com/3028210/118717373-e629e600-b81d-11eb-8df9-2c23401423f3.jpg)

**Comment by yaelboy36** [comment]
Have you figured out what to do?

**Comment by yaelboy36** [comment]
I couldn't find a solution so I make a backup of my saves with TegraExplorer, I found a tutorial. Then I remade my emunand and now I'm installing all my games again, but the error finally disappeared

**Comment by SciresM** [comment]
The error 2002-3502 indicates a failure to access mmc. My best guess would be that there's some corruption in your SD card file emummc, or something.

**Comment by Willhulle** [comment]
I had the same problem.
This error occurs due to damage to an internal component of the Nintendo switch. The SD Card FCP. A Specialized assistance can make this repair, and this component you can find for sale on the internet. After replacing this part, i had no more problems with the console. Search for a video on YouTube called "Nintendo switch SD Card FCP replacement", and you Will see the problem being solved.

**Comment by Masamune3210** [comment]
....unless I'm wrong that's just the connector on the main board for the SD reader daughter board. Should probably work easiest to hardest and make sure that issue is a issue before just telling people that they need something

**Comment by Mart189** [comment]
> I couldn't find a solution so I make a backup of my saves with TegraExplorer, I found a tutorial. Then I remade my emunand and now I'm installing all my games again, but the error finally disappeared

Can you link me the guide you used to backup the saves with Tegraexplorer, I can't find anything and I need to remake the emunand

**Comment by BennyAlex** [comment]
Hello, i also have this error. looks like my emunand got corrupted somehow.
Before a fresh install from my sysnand, is there a way to backup the saves in emunand? Since I cant boot into the system, I cant use checkpoint, so I need some tool to get them with PC or from RCM.

**Comment by yaelboy36** [comment]
> Hello, i also have this error. looks like my emunand got corrupted somehow. Before a fresh install from my sysnand, is there a way to backup the saves in emunand? Since I cant boot into the system, I cant use checkpoint, so I need some tool to get them with PC or from RCM.

This is the tutorial: https://suchmememanyskill.github.io/guides/switchextractsaves/

**Comment by BennyAlex** [comment]
Funny, I deleted all files from sd exept the nand and copied clean atmosphere and hekate files on it. Then I booted into atmosphere using fuse.bin emunand, same error appeard.
Then I tried to turn it off or to boot back into RCM, but it just restarted again into atmosphere. After doing this like 3 or 4 times, it booted in switch home screen.  I have no clue why it works now, but I will probably never turn it off again, hopefully it doesnt crash :D

**Comment by Mart189** [comment]
> Funny, I deleted all files from sd exept the nand and copied clean atmosphere and hekate files on it. Then I booted into atmosphere using fuse.bin emunand, same error appeard. Then I tried to turn it off or to boot back into RCM, but it just restarted again into atmosphere. After doing this like 3 or 4 times, it booted in switch home screen. I have no clue why it works now, but I will probably never turn it off again, hopefully it doesnt crash :D

Trust me, it will crash again the next time you reboot your Switch. Your emummc got corrupted.
Now that you are inside Atmosphere, backup all your saves with JKSV or Checkpoint, transfer them to your pc, and format and test your sdcard folllowing this guide: https://3ds.eiphax.tech/sd.html
Then partition the sdcard with tegraexplorer and remake EmuMMC with Hekate following this guide: https://nh-server.github.io/switch-guide/user_guide/emummc/partitioning_sd/
and then you can reinstall latest Atmosphere.

P.S. if you're using MacOS to prepare your sd card, please use Windows instead, cause that was the reason error 2002-3502 happened to me (supposedly).

**Comment by Masamune3210** [comment]
The main reason macOS is bad for messing with switch stuff is it doesn't know how to keep its hands off of random files and has a really bad habit of setting the archive bit on things which confuses the hell out of the switch and causes a myriad of issues

**Comment by leeberlin** [comment]
Any one can fix this error ? i have same and dont know how to fix it!

**Comment by trino7** [comment]
He probado reinstalando emunand,juegos,con otro tarjeta sd y con otro lector de micro sd y el error sigue,ahora no tengo ninguna duda de que el problema es del conector de la placa donde conecta el lector de micro sd.

**Comment by Masamune3210** [comment]
Yeah, the port on the board for the SD card reader is really sensitive to damage; it's not really designed for multiple insertions.

**Comment by smobanan** [comment]
> Yeah, the port on the board for the SD card reader is really sensitive to damage; it's not really designed for multiple insertions.

Im getting the same error. Tried reformatting my sd card several times, some other stuff I read online, doing a visual inspection of the port, but it looks perfectly fine. How would I even go about finding out if its actually damaged?

**Comment by osakilo** [comment]
![IMG_20250102_220915](https://github.com/user-attachments/assets/47a44fcb-611a-42b6-a9b7-2575aea41f5b)

It was working fine originally, but when I opened the game the next day, it turned out like this. Half of the games on the SD card show an error message and cannot run, while some games run normally. 
Even I delete the games that show this error and reinstall them, they still display the same message (the installation has no errors, but they just cannot run). 
I checked the memory card with software and found no bad sectors. I'm really at a loss now

**Comment by MYusufY** [comment]
Same, it happened to me out of nowhere. Yesterday i played some games, they were working normally and this morning they crash after playing for a couple of minitues. :/

**Comment by DavidDubinin** [comment]
> > Yeah, the port on the board for the SD card reader is really sensitive to damage; it's not really designed for multiple insertions.
> 
> Im getting the same error. Tried reformatting my sd card several times, some other stuff I read online, doing a visual inspection of the port, but it looks perfectly fine. How would I even go about finding out if its actually damaged?

Just a quick update, turns out nothing was broken- It was just a poorly seated sd card reader. Removed it, plugged it back in gently, making sure to give it a good push and it's been just fine since. GL to y'all figuring this out

**Comment by wmdhs12138** [comment]
> > > Yeah, the port on the board for the SD card reader is really sensitive to damage; it's not really designed for multiple insertions.
> > 
> > Im getting the same error. Tried reformatting my sd card several times, some other stuff I read online, doing a visual inspection of the port, but it looks perfectly fine. How would I even go about finding out if its actually damaged?
> 
> Just a quick update, turns out nothing was broken- It was just a poorly seated sd card reader. Removed it, plugged it back in gently, making sure to give it a good push and it's been just fine since. GL to y'all figuring this out

fix my problem, really appreciate
