### ISSUE TITLE
Keep Switch screen on when docked?

### ISSUE THREAD

**Issue by xthree** [Atmosphere-NX/Atmosphere#1513]
### Goal
I have removed the front plate of the stock Switch dock. I would like to use the Switch screen while docked in order to charge and use USB devices without needing to use an external display.

Is this possible?

**Comment by SciresM** [comment]
This is deeply unrelated to atmosphere, and you didn't use the issue templates.

**Comment by xthree** [comment]
My bad I somehow went to a link that didn't prompt me for a template. I see it now.  I was told that the OS is what controls the screen in this situation. So I thought here was the right place. Peace.
