### ISSUE TITLE
a fatal error form atmospehre 

### ISSUE THREAD

**Issue by Aura314** [Atmosphere-NX/Atmosphere#1514]
I received a fatal error from atmospehre, this is this one: A fatal error occrred when running Atmospehre.
Program ID: 0100000004
Error Desc: std :: abort () called (0xffe.
My system is: firmware 1202 and atmosphre 19.3E 
![IMG_1848](https://user-images.githubusercontent.com/83787307/118416837-d68d8e80-b6b1-11eb-94f7-605b5ce44855.JPG)

**Comment by SciresM** [comment]
Update your custom sysmodules.

Also, you did not use the issue templates.
