### ISSUE TITLE
The Software was closed because an error occurred on homebrew

### ISSUE THREAD

**Issue by Electric1447** [Atmosphere-NX/Atmosphere#1518]
System Firmware: 12.0.2
Atmosphere Version: 0.19.3 (emuMMC)
Loaded with fusee-primary.bin

I am getting this error on multiple homebrew ports (Doom64EX, Cannonball, ect) **I AM NOT TRYING TO PIRATE GAMES**

I am also pretty new to the switch scene, am I doing something wrong?

**Comment by SciresM** [comment]
Re-open using the issue templates.
