### ISSUE TITLE
Panic Occurred while running Atmosphere

### ISSUE THREAD

**Issue by Erionn** [Atmosphere-NX/Atmosphere#1523]
### What's the issue you encountered?

[I updated my CFW from 12.0.1 to 12.0.2 last night, and updated Atmosphere from 0.19.2 to 0.19.3. Wasn't having any issues until this morning when I rebooted my switch, and started getting this error:
![IMG_20210527_122047](https://user-images.githubusercontent.com/35086507/119913285-61705380-bf12-11eb-809e-d78e680e590e.jpg)]</br>
[ I have not made any changes to Atmosphere, and have tried fresh installs as well. ]</br>

### How can the issue be reproduced?

[ Just booting into Atsmophere I get the error every time. ]</br>

### Crash Report

[report_0c31f43e.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6557441/report_0c31f43e.zip)

### System Firmware Version

12.0.2</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: I've tried both injecting fusee-primary and hekate, same error with both.
- Official release or unofficial build: Official release 0.19.3
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: Currently nothing
- EmuMMC or SysNAND: EmuMMC partition-based

**Comment by SciresM** [comment]
Your erpt savedata is corrupted.

Mount system partition manually and delete it (80000000000000D1).
