### ISSUE TITLE
Error when booting

### ISSUE THREAD

**Issue by sweatpotato13** [Atmosphere-NX/Atmosphere#1526]
## Bug Report

when try to boot cfw, then comes out ```panic occurred while running atmosphere 010041544D530000```

I saw some solution like remove /atmosphere/content/010041544D530000 folder but there is not exist that folder

### System Firmware Version

11.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: Official release 0.19.3
- EmuMMC or SysNAND: EmuMMC, SysNAND both

**Comment by lookye** [comment]
Have you looked into already [closed issues](https://github.com/Atmosphere-NX/Atmosphere/issues?q=is%3Aissue+is%3Aclosed+010041544D530000)? You should read them and find your solution.
