### ISSUE TITLE
Black screen after updating to 0.19.3

### ISSUE THREAD

**Issue by StanMOI** [Atmosphere-NX/Atmosphere#1529]
Hello,
After that I made update to 0.19.3, I get black screen after booting .
Just after this logo image of Atmosphere
![IMG_6210](https://user-images.githubusercontent.com/38383423/120166461-e1d9d180-c1fc-11eb-9fb6-784777f5f58a.jpg)

No folder crash_reports was created.

### System Firmware Version

12.0.2</br>

Some on know how to fix it?

**Comment by SciresM** [comment]
Re-open with issue templates filled out.

**Comment by StanMOI** [comment]
> templates filled out.

Too complicate .
Many of question in templates I dont know what to write.

**Comment by SciresM** [comment]
Sorry, help cannot be provided without a filled out issue template.
