### ISSUE TITLE
Black screen after updating to 0.19.3

### ISSUE THREAD

**Issue by StanMOI** [Atmosphere-NX/Atmosphere#1530]
## Bug Report

N/A

### What's the issue you encountered?

Hello,
After that I made update to 0.19.3, I get black screen after booting .
Just after this logo image of Atmosphere
![IMG_6210](https://user-images.githubusercontent.com/38383423/120166461-e1d9d180-c1fc-11eb-9fb6-784777f5f58a.jpg)

I use RMCLoader that I updated to last **payload.bin**
![in-switch-nintendo-sen-prend-desormais-aux-loader-rcm-1](https://user-images.githubusercontent.com/38383423/120168472-2c5c4d80-c1ff-11eb-954f-5bb4ab900a8f.jpeg)

<img width="226" alt="Capture d’écran 2021-05-31 à 10 56 32" src="https://user-images.githubusercontent.com/38383423/120168206-eacba280-c1fe-11eb-8686-de2c08550e6a.png">

### How can the issue be reproduced?

After Booting via RMCLoader.

### Crash Report

No folder crash_reports was created.

### System Firmware Version

12.0.2</br>

### Environment

RMCLoader

### Additional context?

N/A

**Comment by SciresM** [comment]
Re-open with issue templates actually filled out, rather than "N/A".
