### ISSUE TITLE
Fatal error after booting "oxffe"

### ISSUE THREAD

**Issue by StanMOI** [Atmosphere-NX/Atmosphere#1532]
### What's the issue you encountered?

After updating to Atmosphere 0.19.3 I get error code "oxffe" just after booting, just after Atmosphere logo
![IMG_6210](https://user-images.githubusercontent.com/38383423/120166461-e1d9d180-c1fc-11eb-9fb6-784777f5f58a.jpg)

![IMG_6221](https://user-images.githubusercontent.com/38383423/120323055-5f790c80-c2e5-11eb-8418-8d6652bc0055.jpg)

I have updated myself files and my USB key with the fusee primary.bin file
I followed the usual procedure and it always worked before but this time i have a Black Screen.

### How can the issue be reproduced?

After updating and launching via RMC Loader

### Crash Report

[report_0000000007e1c737.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6576106/report_0000000007e1c737.zip)

### How can the issue be reproduced?

After Booting via RMCLoader.

### System Firmware Version

12.0.2</br>

### Environment?

Atmosphere official

### Additional context?

I use RMCLoader that I updated to last **payload.bin** (renamed fusee-primary.bin to payload.bin)
![in-switch-nintendo-sen-prend-desormais-aux-loader-rcm-1](https://user-images.githubusercontent.com/38383423/120168472-2c5c4d80-c1ff-11eb-954f-5bb4ab900a8f.jpeg)

<img width="226" alt="Capture d’écran 2021-05-31 à 10 56 32" src="https://user-images.githubusercontent.com/38383423/120168206-eacba280-c1fe-11eb-8686-de2c08550e6a.png">

Contents folder have those folders, but even after delating all of them, the error are still here :
<img width="216" alt="Capture d’écran 2021-06-01 à 14 13 55" src="https://user-images.githubusercontent.com/38383423/120321759-f80e8d00-c2e3-11eb-9dfd-f6ddac9ade9e.png">

Here is content inside my SD card:
<img width="235" alt="Capture d’écran 2021-06-01 à 14 28 54" src="https://user-images.githubusercontent.com/38383423/120323475-ceeefc00-c2e5-11eb-8994-102572a4c970.png">

On my SD card I have old folders:
"atmosphere-old" (I rename the old folder cause I had Black screen problem after updating to 0.19.3
"emuMMC" (I dont use it), cause I launching  directly Atmosphere via "RMC Loader"

Here is content inside Atmosphere folder:
<img width="243" alt="Capture d’écran 2021-06-01 à 14 27 30" src="https://user-images.githubusercontent.com/38383423/120323245-9b13d680-c2e5-11eb-9879-e8ced23edd61.png">

Sigpatches was updated form here  https://github.com/ITotalJustice/patches/releases
With "Fuse" file

Thanks for help

**Comment by Masamune3210** [comment]
Piracy is not supported

**Comment by StanMOI** [comment]
> Piracy is not supported

What in my post are « Piracy »?

**Comment by fincs** [comment]
You literally linked to sigcheck patches, which are exclusively used for piracy.

**Comment by StanMOI** [comment]
> You literally linked to sigcheck patches, which are exclusively used for piracy.

why you close every time !
I corrected my post

**Comment by masagrator** [comment]
> > You literally linked to sigcheck patches, which are exclusively used for piracy.
> 
> why you close every time !
> I corrected my post

Because hiding evidence won't change anything...
