### ISSUE TITLE
Fatal error after booting "oxffe"

### ISSUE THREAD

**Issue by StanMOI** [Atmosphere-NX/Atmosphere#1533]
Bug Report

What's the issue you encountered?

After updating to Atmosphere 0.19.3 I get error code "oxffe" just after booting, just after Atmosphere logo

![](https://user-images.githubusercontent.com/38383423/120166461-e1d9d180-c1fc-11eb-9fb6-784777f5f58a.jpg)

![](https://user-images.githubusercontent.com/38383423/120323055-5f790c80-c2e5-11eb-8418-8d6652bc0055.jpg)

I have updated myself files and my USB key with the fusee primary.bin file
I followed the usual procedure and it always worked before but this time i have a Black Screen.

How can the issue be reproduced?

After updating and launching via RMC Loader

Crash Report

https://github.com/Atmosphere-NX/Atmosphere/files/6576106/report_0000000007e1c737.zip

How can the issue be reproduced?

After Booting via RMCLoader.

System Firmware Version

12.0.2

Environment?

Atmosphere official

Additional context?

I use RMCLoader that I updated to last payload.bin (renamed fusee-primary.bin to payload.bin)
in-switch-nintendo-sen-prend-desormais-aux-loader-rcm-1

![](https://user-images.githubusercontent.com/38383423/120168206-eacba280-c1fe-11eb-8686-de2c08550e6a.png)

Contents folder have those folders, but even after delating all of them, the error are still here :

![](https://user-images.githubusercontent.com/38383423/120321759-f80e8d00-c2e3-11eb-9dfd-f6ddac9ade9e.png)

Here is content inside my SD card:

![](https://user-images.githubusercontent.com/38383423/120323475-ceeefc00-c2e5-11eb-8994-102572a4c970.png)

On my SD card I have old folders:
"atmosphere-old" (I rename the old folder cause I had Black screen problem after updating to 0.19.3
"emuMMC" (I dont use it), cause I launching directly Atmosphere via "RMC Loader"

Here is content inside Atmosphere folder:

![](https://user-images.githubusercontent.com/38383423/120323245-9b13d680-c2e5-11eb-9879-e8ced23edd61.png)

Thanks for help

**Comment by fincs** [comment]
Resubmitting the previous issue isn't going to make us forget that you admitted to piracy. Piracy is not supported.
