### ISSUE TITLE
Titles will not load, "Checking if game can be played"

### ISSUE THREAD

**Issue by Mewthree3** [Atmosphere-NX/Atmosphere#1534]
### What's the issue you encountered?

Whenever I try to load a game, it says "Checking if game can be played", and I can't play it.
No Nintendo account was on the system (had one before, but I system formatted)
The Nintendo account that used to be on it is on another system (it seems that the other system is designated as the secondary).
I had installed some dumps of games that I legally own, that were on my eShop account.

I'll try to go on the Nintendo website and see what's up with the accounts.
Additionally, I'll also try to go on the other Switch, delete the user, and then put the user on the system again, to see if that solves the problem for me.

### How can the issue be reproduced?

Have Nintendo account on your hacked device.
Dump legally-owned games (from eShop).
Delete Nintendo Account from system.
Format hacked system (do not add a Nintendo Account afterwards), and install games.
Notice that the games will not load, and says "Checking if game can be played".

### System Firmware Version

12.0.2

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official Hekate, v5.5.6
- Do you have additional kips or sysmodules you're loading: Not AFAIK
- Homebrew software installed: No NSPs installed
- EmuMMC or SysNAND:
SysNAND

### Additional context?
**This is not a piracy issue, nor an issue with software SPECIFICALLY DESIGNED for piracy**
- Additional info about your environment:
Latest Atmosphere and SP running

**Comment by fincs** [comment]
![image](https://user-images.githubusercontent.com/581494/120396758-6597d900-c337-11eb-90bd-9a5a61041e8e.png)

Piracy is not supported.

**Comment by SciresM** [comment]
The things you describe are piracy, on the record.
