### ISSUE TITLE
A fatal error occured when running Atmosphere - Program ID : 010041544d53000

### ISSUE THREAD

**Issue by demonium77** [Atmosphere-NX/Atmosphere#1535]
Hi,

**What's the issue you encountered?**
I shut down my switch about 5 days ago and put it on the dock, everything was working fine at this time.
I did nothing else with it from that day.

Today I wanted to play a bit, and tried to boot in Atmospehre. 

Well I first had problems with my SD (brand new, FAT32 formated) that was not recognized. 
After few tries on computer as well it worked again.

I booted hekate with RCM Loader and here is what happens after injecting fusee-primary,
I can see sept / atmosphere / atmosphere black and white logo screens, and just after this message pops :

_A fatal error occured when running Atmosphere.
Program ID : 010041544d53000
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_00000000008269e55.bin_

I then tried replacing atmosphere files on SD card with fresh ones without success, so I put back the original ones.

**How can the issue be reproduced?**
Only try to boot atmosphere normally.

**Crash Report**
The fatal_errors folder is empty, I can't find the report ..

**System Firmware Version**
OFW 12.0.2 and CFW Atmosphere 12.0.2 (running on version 0.19.3)

**Environment**
- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: RCM Loader
- Official release or unofficial build: Official release 12.0.2
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed (in switch folder): Awoo-Installer, daybreak, JKSV, reboot_to_payload

--

Thanks in advance for your help, let me know if you need anything else :)

**Comment by fincs** [comment]
> Awoo-Installer

Piracy is not supported.
