### ISSUE TITLE
A fatal error occured when running Atmosphere.

### ISSUE THREAD

**Issue by emveezz** [Atmosphere-NX/Atmosphere#1537]
### What's the issue you encountered?

When booting Atmosphere I get this error :

A fatal error occured when running Atmosphere.
Program ID : 010041544d53000
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_00000000008243988.bin

### How can the issue be reproduced?

Booting Atmosphere 0.19.3

### System Firmware Version

12.0.2

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate v5.5.6
- Official release or unofficial build: Official release version 12.0.2
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: N/A
- EmuMMC or SysNAND: EmuMMC, partition-based on FAT32 SD Card

### Additional context?

Nothing was touched on SD card, I just tried booting up as usual.

I tried to fix Arch Bit as seen in other topics without success (0 errors found).

**Comment by SciresM** [comment]
Closing this since no report was actually uploaded and you're using 0.19.3. Update to 0.19.4, and upload a report in a new issue if you're still having whatever this problem was.
