### ISSUE TITLE
Add Breakpoints and Debugging to dmnt cheats

### ISSUE THREAD

**Issue by ReclaimerShawn** [Atmosphere-NX/Atmosphere#1546]
## Feature Request

Adding breakpoints/debugging addresses and functions to dmnt cheats.

#### Overview:
Implement the ability for breakpoints/debugging to be set on addresses and functions. This would allow a user using an outside Homebrew software (like Edizon or Noexs) to debug an address, returning the functions that write to the address, returning the functions that access and address, or even setting breakpoints on functions, freezing the game whenever they're called.

### Why would this feature be useful?
Would allow for people to make ASM Cheats for the Nintendo Switch without using programs like IDA Pro, which cost thousands of dollars, or Ghidra, which some people are paranoid of due to the NSA developing it. This would also make it significantly easier to make ASM cheats, as the functions would be tied to their addresses instead of needing to be searched for in a game's main.nso.

**Comment by masagrator** [comment]
This is what tma2 is targetting with way more functions.

https://github.com/Atmosphere-NX/Atmosphere/pull/1405

**Comment by masagrator** [comment]
Breakpoints and debugging are parts of tma2 reimplementation.

**Comment by ReclaimerShawn** [comment]
I actually searched issues beforehand to see if this was there, and there was one duplicate that could no longer be commented on. Nice to know that's in the Pull Requests and was started more recently (2 months ago). I can't wait until that is implemented: it'd make my life a lot easier.
