### ISSUE TITLE
Tantei Bokumetsu LayeredFS issues

### ISSUE THREAD

**Issue by InochiPM** [Atmosphere-NX/Atmosphere#1547]
### What's the issue you encountered?

I'm trying to edit files for Tantei Bokumetsu, and when i add them to the romFS folder inside of atmosphere the changes do not reflect in game, as i think the game itself has a round-about way of pointing to the romfs folder, but im not fully sure thats the issue. 

### How can the issue be reproduced?
By making edits to any of the files inside the games romFS folder. 
for instance i edited the text in two files in the database folder and none of them reflected in the game.

### Crash Report
N/A

### System Firmware Version

12.0.3</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Hekate

**Comment by SciresM** [comment]
Update executable for Tantei Bokumetsu (0100cba014014800) just does nn::fs::MountRom(), this will be covered by LayeredFS. There is nothing abnormal about how the game points to romfs.

What makes you think that LayeredFS isn't working vs your not editing files correctly?

Please post screenshots of your relevant layeredfs directories.

**Comment by SciresM** [comment]
Closing because I don't think this is real.

**Comment by InochiPM** [comment]
<img width="1211" alt="Screen Shot 2021-06-28 at 1 37 39 PM" src="https://user-images.githubusercontent.com/13459080/123680540-d5a25d80-d816-11eb-95c8-660d94e70004.png">
