### ISSUE TITLE
TABE-O-JA LayeredFS error

### ISSUE THREAD

**Issue by InochiPM** [Atmosphere-NX/Atmosphere#1548]
### What's the issue you encountered?
I'm also trying to translate TABE-O-JA into english but the text files are all in .json format and easily editable. 
Problem is the game itself does not reflect any sort of edits made to it with the text, as it's a unity game i do not know how LayeredFS works with them. 

### How can the issue be reproduced?
Dragging any one of the translated .json files into the correct folder in the layeredFS directory.

12.0.3</br>

### Environment?

Hekate 
Official release
SysNAND

### Additional context?
The game is built in Unity and uses the files it has to point the way to the streaming assets but im guessing that Atmos doesnt support these kinds of games with LayeredFS.

**Comment by SciresM** [comment]
There is no known issue with unity games, unity/not unity will make no difference to layeredfs.

I'll look at it.

this and the other issue should have been a single issue.

**Comment by SciresM** [comment]
This game also just calls nn::fs::MountRom().

I am pretty confident it's a user-not-making-game-mod-correctly problem, and not an atmosphere problem.

**Comment by InochiPM** [comment]
<img width="1211" alt="Screen Shot 2021-06-28 at 1 37 32 PM" src="https://user-images.githubusercontent.com/13459080/123680024-3715fc80-d816-11eb-9665-ffdd3cf9314f.png">
The folder structure is correct atmosphere make the file for it in the contents folder. 
It just refuses to work.
