### ISSUE TITLE
Error code when opening certain apps, and newly downloaded cheats not showing up.

### ISSUE THREAD

**Issue by HenryHeliolisk** [Atmosphere-NX/Atmosphere#1550]
### What's the issue you encountered?

After updating atmosphere to 19.4, cheats i downloaded for new games weren't appearing for use in game through cheat mangers, while the games i had cheats for still have thier cheats. Then, when i updated AIO switch updater via the hb store, it crashes, giving me an error code in snapshot and normal hb menu.

### How can the issue be reproduced?

update atmosphere to 0.19.4, update/install AIO switch updater via the hb store; open AIO switch updater.
### Crash Report

[01624834306_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/6722457/01624834306_010000000000100d.log)

### System Firmware Version

12.0.3</br>

### Environment?

no emummc, latest atmosphere, no custom sysmodules

**Comment by SciresM** [comment]
This is an issue with whatever homebrew you're using, not with atmosphere.
