### ISSUE TITLE
Fatal error occurred when running atmosphere!!

### ISSUE THREAD

**Issue by Jayj2** [Atmosphere-NX/Atmosphere#1552]
It's a little burry!
![0701210319b_HDR_2](https://user-images.githubusercontent.com/37864709/124084118-a9582e00-da1c-11eb-91a6-67584108e594.jpg)

It told me,

A fatal error occurred when running atmosphere,
Program ID: 010041544d530000
Error Desc: std::abort() called (0xffe)
Report saved to /atmostphere/fatal_errors/report_000000000656c193.bin

The atmosphere directory may improperly have archive bit set. Please try running an archive bit fixer tool
(for example, the Hekate).

Does anybody know what this is exactly!

**Comment by SciresM** [comment]
You did not use the issue templates.

in addition, there is an explicit fix suggested in the picture. Do what it says? Google terms you don't recognize?

This issue tracker is for bugs, it's not a support forum.
