### ISSUE TITLE
Atmosphere gives 2168-0002 error every time after boot

### ISSUE THREAD

**Issue by Gamercat365** [Atmosphere-NX/Atmosphere#1553]
What's the issue you encountered?

After i updated atmosphere (and hekate) to the latest version (0.19.4) it started giving me this error.
It happens after i launch launch CFW from hekate and see the Nintendo and Atmosphere logo.

System Firmware Version
9.1.0

How can the issue be reproduced?
I updated Atmosphere by dragging and dropping the latest files into the root of the sd card and replacing all, then i updated  hekate by dragging and dropping the bootloader folder and replacing all. 

Environment?

Hekate 5.5.7 (latest version)
[02234167374_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/6762691/02234167374_010000000000100d.log)

EDIT: I deleted all the atmosphere files and copied the new ones instead of replacing them, it worked.

**Comment by masagrator** [comment]
Use issue template.
