### ISSUE TITLE
Can't jump in Game Builder Garage interactive lessons

### ISSUE THREAD

**Issue by gingerbeardman** [Atmosphere-NX/Atmosphere#1557]
### What's the issue you encountered?

Pressing B does not jump in Game Builder Garage interactive lessons. 

### How can the issue be reproduced?

1. Start Game Builder Garage for the first time
2. choose the only option available: interactive lessons
3. the first stage requires you to move with L and jump with B

### Crash Report

N/A

### System Firmware Version

12.0.3

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:

hekate

- Official release or unofficial build: 
  - official 0.19.4

- Do you have additional kips or sysmodules you're loading:

N/A

- Homebrew software installed:

N/A

- EmuMMC or SysNAND:

SysNAND

### Additional context?

- Additional info about your environment:

I've tried joycons and also switch Pro controller. B doesn't jump using either.

Game Builder Garage 1.0.1

**Comment by SciresM** [comment]
Does this issue occur only when using atmosphere...?

**Comment by gingerbeardman** [comment]
Yes

**Comment by SciresM** [comment]
Please post a screenshot of /atmosphere/contents.

if the game works in non-ams, play it under non-ams in the meantime, though.

**Comment by gingerbeardman** [comment]
Of course!

I'll upload a screenshot shortly.

**Comment by gingerbeardman** [comment]
<img width="682" alt="Screen shot 2021-07-06 at 22 23 02" src="https://user-images.githubusercontent.com/49612/124668480-d5563200-dea8-11eb-9523-42a5929d0494.png">

**Comment by SciresM** [comment]
Hm. Okay, this is super weird. 

I cannot think of a single mechanism by which normal atmosphere would interfere in controller stuff, without a contents folder.

I'll ask to see if anyone can reproduce this, since I think people have used game builder garage fine previously(?)

**Comment by SciresM** [comment]
This is reportedly part of the game. 

Try spamming it for a bit?

**Comment by SciresM** [comment]
Confirmed by watching a let's play that this not working is literally part of the game.

Discord user uploaded this: 
![](https://user-images.githubusercontent.com/8676005/124670300-a28c4980-de68-11eb-8ef5-f599afaa6524.png)

What did you mean when you said it worked on non-atmosphere?

**Comment by gingerbeardman** [comment]
OMG. 

Thanks!

**Comment by gingerbeardman** [comment]
Regarding your final question, my kids have been playing it on their stock Switch with no problems.

Totally my fault with the dodgy reporting in this instance. Apologies!
