### ISSUE TITLE
build exosphere

### ISSUE THREAD

**Issue by costelabr17** [Atmosphere-NX/Atmosphere#1558]
i try building exosphere and show this error:

C:/atmosphere/exosphere/program/source/smc/secmon_smc_info.cpp: In function 'ams::secmon::smc::SmcResult ams::secmon::smc::{anonymous}::GetConfig(ams::secmon::smc::SmcArguments&, bool)':
<command-line>: error: unable to find numeric literal operator 'operator""x'
C:/atmosphere/exosphere/program/source/smc/secmon_smc_info.cpp:258:33: note: in expansion of macro 'ATMOSPHERE_GIT_HASH'
  258 |                     args.r[1] = ATMOSPHERE_GIT_HASH;
      |                                 ^~~~~~~~~~~~~~~~~~~
make[2]: *** [/opt/devkitpro/devkitA64/base_rules:14: secmon_smc_info.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [Makefile:82: release] Error 2
make[1]: Leaving directory '/c/atmosphere/exosphere/program'
make: *** [Makefile:56: check_program_release] Error 2

any idea how i can solve this?

**Comment by HookedBehemoth** [comment]
You'll have to clone the actual repository as it sources the git hash in that marked line.
Downloading the zip won't work.

**Comment by costelabr17** [comment]
> You'll have to clone the actual repository as it sources the git hash in that marked line.
> Downloading the zip won't work.

i used git clone --recursive https://github.com/Atmosphere-NX/Atmosphere.git

**Comment by myrade** [comment]
did you build atmosphere in an environment that has git on path?

**Comment by SciresM** [comment]
Yeah, the issue here will be that the folder you're building in isn't a git repository. Closing this, but you can paste e.g. git status output, if you want to diagnose this.
