### ISSUE TITLE
atmosphere 0.19.5-master crashesh

### ISSUE THREAD

**Issue by n0201** [Atmosphere-NX/Atmosphere#1559]
my atmosphere 0.19.5-master-9df13781c crashes at start after update to 12.1.0. The Error Code is 2162-0002 (0x4a2). i tried to boot with hekate 5.8.8 and with fusee-primary, but nothing worked

**Comment by bettydreemurr** [comment]
Use full issue template, because we cannot identify the problem

**Comment by GoDev87** [comment]
Try removing the nxtheme folder inatmosphere/content

**Comment by n0201** [comment]
@GoDev87 THX it worked :)
