### ISSUE TITLE
Cartridges not recognising: Atmosphere 0.19.5 on FW 12.1.0

### ISSUE THREAD

**Issue by MikeDev101** [Atmosphere-NX/Atmosphere#1563]
## Bug Report

I can't seem to get any cartridges to recognize on my HAC-001 switch.

### What's the issue you encountered?

Cartridges aren't being recognized in the custom firmware. Cartridges only work when you boot into stock firmware mode. I was getting ready to play SSBU with my Xbox one wireless controller (My joy-cons weren't immune to the drifting issue), thanks to a fresh install of Syscon / MissionControl. However, my switch refuses to read the cartridges. No cartridges I own were recognized by the system. It only works in stock firmware mode.

### How can the issue be reproduced?

1. Accidentally update to FW 12.1.0.
2. Update Atmosphere + Hekate to latest versions (AMS 0.19.5 & H 5.58 as of this issue)
3. Push Hekate binary to Switch, running in RCM mode
4. Boot into Atmosphere payload
5. Insert any game cartridge
6. Lag?
7. "This game cartridge could not be recognized"
8. Tried cleaning cartridge + cartridge slot w/ cotton swabs & isopropyl alcohol
10. Still nothing
11. Reboot into Hekate via Reboot2RCM
12. Boot into stock FW
13. Insert the cartridge again
14. Works as normal
15. Reboot back into Hekate
17. Disabled NoGC and save settings
18. Boot back into Atmosphere
19. Insert the cartridge once more
20. Still no luck, gave up

### Crash Report

N/A

### System Firmware Version

- 12.1.0

### Environment?

- Hekate v5.58 w/ Nyx v1.0.5
- Official release 12.1.0|AMS M.19.5|S
- SysCon 0.6.3 + MissionControl 0.5.0 sysmodules

### Additional context?

- I push my payloads VIA TegraRCM GUI in Windbloat 10

**Comment by SciresM** [comment]
hekate and fusee have separate config.

if booting fusee primary, you need to edit nogc config for fusee.

if booting hekate, you need to edit hekate config.

make sure you're editing the right file.
