### ISSUE TITLE
(High Priority) The whole hack isn't working, I don't know what to do.

### ISSUE THREAD

**Issue by hum4nb3ing** [Atmosphere-NX/Atmosphere#1564]
Hello, I'm new here so I don't know how to use this forum properly but I don't know what else I could do.

Recently I started using again my NS to play again my old games and some news one using Atmosphere, the thing is that I can't start any videogame after installing the NSP file. When I try to play a game, it says "Could not start the software. Please try again from the HOME Menu."

I've tried to start with hetake and only the EMUNAND and Stock appears as an option, I don't know if it has something to do with this.

I have last version of hetake, fusee primary and atmosphere (at the date of 13/07/21), my NS version is 12.1.0/AMS M.19.5/S.

I've used the hacks before but somehow it isn't running currently. Thanks for your time.

**Comment by SciresM** [comment]
1. You did not use the issue templates.

2. Piracy is not supported.
