### ISSUE TITLE
Atmosphere crashes since latest system and atmosphere upate

### ISSUE THREAD

**Issue by Bolleke09** [Atmosphere-NX/Atmosphere#1565]
Hi,

I have never really had any issues with atmosphere but since the last update my system craches on startup. I reset my switch and reformated my SD but atmosphere can't boot. See logs for details.
[fatal_reports.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6814412/fatal_reports.zip)

**Comment by SciresM** [comment]
1. You did not use the issue templates.

2. Delete your custom theme.

**Comment by Bolleke09** [comment]
Sorry I didn't know there was a template I am new to github. I formated my
sd card is my theme stored on my system memory? And how do I remove it?
