### ISSUE TITLE
Unable to launch Atmosphere - new install

### ISSUE THREAD

**Issue by ttmob** [Atmosphere-NX/Atmosphere#1569]
I have an original day one switch running software 12.1.0, I have decided I would like to install homebrew. I have followed this guide https://nh-server.github.io/switch-guide/user_guide/emummc/sd_preparation/, when reaching the part where I boot into  Atmosphere FSS0 EmuMMC for the first time I receive a panic error.
This is the fatal error report in my atmosphere folder inside my switches sd card.
[report_0791fa56.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6834982/report_0791fa56.bin.zip)

**Comment by SciresM** [comment]
You did not use the issue templates.

Your issue is that you have archive bits set on SD. Use hekate's archive bit fixer.

This is because you use macOS, btw, which doesn't play nicely with SD card archive bits.
