### ISSUE TITLE
Suggestion, caching eMMC content to SD

### ISSUE THREAD

**Issue by Benoit7413** [Atmosphere-NX/Atmosphere#157]
It's a long process to extract keys and repack things, why not caching all processes output into the SD with integrity check and implementing a secure way to flush it ?

**Comment by HyrulianTerror** [comment]
Good Idea, but I'd like to be able to turn it off in settings to prevent wear of the flash memory and conserve space.

**Comment by SciresM** [comment]
This does not make very much sense -- the actual derivation process is next-to-instant.
