### ISSUE TITLE
Unable to boot after downgrade 

### ISSUE THREAD

**Issue by FuzzyWaffler** [Atmosphere-NX/Atmosphere#1574]
## Bug Report

On Mariko Switch lite with chip
Unable to boot after downgrade from 12.1.0 to 10.0.1 to fix a wifi issue.

### What's the issue you encountered?

Atmosphere no longer boots

FATAL ERROR: NXBOOT failed to determine mariko warmboot firmware 

then if I hit power it will dump a Stack and code dump.

### How can the issue be reproduced?

Downgrade from 12.1.0 to another 

### Crash Report

[https://gist.github.com/FuzzyWaffler/778e260578ddca3e2eb9536369971f0a]</br>

### System Firmware Version

10.0.1</br>
</br>
</br>
</br>

### Environment?

- What bootloader: Atmosphère launched by: Chip
- Official release : 0.19.5

- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND:
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]

### Additional context?

This was caused when trying to downgrade to fix a network issue  on the system that was caused when upgrading. 
- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Expected behavior. You need a warmboot_mariko cache from the firmware matching your fuses in order to boot a downgraded firmware.

restore 12.x and boot it once with hekate.
