### ISSUE TITLE
Doc and implementation don't match for the position of R in cheat VM opcode type 3

### ISSUE THREAD

**Issue by tomvita** [Atmosphere-NX/Atmosphere#1575]
## Bug Report

Documentation : 
Start Loop Encoding
300R0000 VVVVVVVV
    R: Register to use as loop counter.
    V: Number of iterations to loop.
End Loop Encoding
310R0000
    R: Register to use as loop counter.

Implementation:
https://github.com/Atmosphere-NX/Atmosphere/blob/4d430a4c61ef65fab66556788107085ca2f98b16/stratosphere/dmnt/source/cheat/impl/dmnt_cheat_vm.cpp#L400
Which would be 
3?R00000 (VVVVVVVV)

**Comment by SciresM** [comment]
Fixed the code to match documentation. 

This is a gateway instruction, so we don't have liberty/control over the format.
