### ISSUE TITLE
Switch 12.1.0 crashing after nintendo switch logo

### ISSUE THREAD

**Issue by SquirrelOn0IQ** [Atmosphere-NX/Atmosphere#1578]
Not sure what happened but I can't for the life of me get atmosphere to boot, It passes the switch logo and for a split second you can see any alerts like "low battery" and then I get this
![WIN_20210724_17_20_26_Pro](https://user-images.githubusercontent.com/85952029/126883901-d2e2c3b3-18b1-433b-a8f0-e4086a71461c.jpg)

**Comment by SciresM** [comment]
1. You didn't use the issue templates

2. Delete your custom theme.

**Comment by SquirrelOn0IQ** [comment]
> 1. You didn't use the issue templates
> 2. Delete your custom theme.

1. How do I delete the theme if I can't boot
2. Sorry, I'm new to github and didn't know about any of the template stuff

**Comment by Masamune3210** [comment]
Maybe go read a bit about how things work? Google is your friend....
