### ISSUE TITLE
fatal error title id: 010041544d530000 std::abort() called (0xfss)

### ISSUE THREAD

**Issue by SquareX12** [Atmosphere-NX/Atmosphere#1579]
Hi i'm new to modding, 2 years ago i modded my switch and installed atmosphere. After some months i tried to manually update it with choidujour (i don't remember now if was NX or not) and, when i rebooted it, it shows me this message

A fatal error occurred whem running Atmosphere
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffs)
Report saved to/atmosphere/fatal_errors/report_00000000066dd824.bin

after trying to resolve this problem with other posts of other users, without any success, i just updated the atmosphere version to the last and nothin, still doesn't work, at the end of this post you can find my error file, thanks in advance for your patience and sorry for my bad english.
[report_00000000066dd824.zip](https://github.com/Atmosphere-NX/Atmosphere/files/6874180/report_00000000066dd824.zip)

**Comment by masagrator** [comment]
ChoiDojourNX is not supported and even advised to not use it under any circumstances because it's bugged and can install updated with errors.

If you have a backup, restore it and install update using Daybreak which is included with Atmosphere.

**Comment by SquareX12** [comment]
I don’t have any backup anymore cuz my old pc destroyed my hdd, and i lost everything and can’t access homebrew so i couldn’t use daybreak and can’t update Inviato da Posta per Windows 10 Da: MasaGratoRInviato: domenica 25 luglio 2021 18:21A: Atmosphere-NX/AtmosphereCc: SquareX12; AuthorOggetto: Re: [Atmosphere-NX/Atmosphere] fatal error title id: 010041544d530000 std::abort() called (0xfss) (#1579) ChoiDojourNX is not supported and even advised to not use it under any circumstances because it's bugged and can install updated with errors.If you have a backup, restore it and install update using Daybreak which is included with Atmosphere.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by masagrator** [comment]
Yeah, I edited my previous post because I was too rushing to conclusions.

So my other question is:
Do you have anything in contents folder?

**Comment by SquareX12** [comment]
lemme check... uhm yes i have 12 folder

**Comment by masagrator** [comment]
Delete whole contents folder and try again - of course if you are on newest atmosphere.

**Comment by SquareX12** [comment]
yes i updated it thinking it was the problem... yes i'm gonna delete it, with tegra wich payload should use?

**Comment by SquareX12** [comment]
ok i rebooted the switch and give the same previous error
