### ISSUE TITLE
Unable to launch atmosphere, error code 2168-0001 & 2168-0002

### ISSUE THREAD

**Issue by oriooctopus** [Atmosphere-NX/Atmosphere#1582]
## Bug Report

Unable to launch atmosphere

### What's the issue you encountered?

This is my first time trying to hack a switch, so I hope I'm just doing something wrong. Here is a screenshot of the error
![IMG_20210730_135257](https://user-images.githubusercontent.com/20331238/127705537-1e42b8a4-f424-4a99-ae65-a6dc71a0fd4f.jpg)

I have reinstalled all the files a couple of times, and reformatted my SD card (format is MSDOS fat-32) in an effort to try every possible solution. I could really use some help as I'm totally stuck.

### How can the issue be reproduced?

I put in the SD card, the dongle on the right, and the injector, successfully loaded Hekate, went to launch > CFS (sysMMC). The Nintendo logo and Atmopshere logo loaded, and then I received the above error, with code 2168-0001

Here is a link to the exact files I downloaded: 
https://www.sdsetup.com/console?switch#atmosphere;atmos_musthave;hekate_musthave;tesla_menu;atmos_ovlloader;atmos_sys-clk;atmos_sysftpd;ovl_sysmodules;appstorenx;hbmenu;edizon;goldleaf;nxdumptool;hekate;lockpick_rcm;
--

### Crash Report
[01578260823_420000000007e51a.log](https://github.com/Atmosphere-NX/Atmosphere/files/6909812/01578260823_420000000007e51a.log)

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version
11.0.1</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?
hekate/fusee was used, and I used the files shown in the above link at sdsetup.com

### Additional context?

I bought a used switch online that has been banned from the internet. I am using RCMLoader One. The files used are the generic install recommended for fussee-gelee in switch.homebrew.guide. The SDcard is a micro-sd card

**Comment by masagrator** [comment]
You clearly didn't put all informations because what is causing crash is Tesla.
