### ISSUE TITLE
Error 2162 0002 When Starting up certain games

### ISSUE THREAD

**Issue by trextaco9** [Atmosphere-NX/Atmosphere#1583]
Been Getting an error 2162 0002 every time I start up certain games like super mario odyssey , I've seen some stuff about deleting 0100000000001000 in content folder in atmosphere and I tried it and it didn't work, Anyone got a solution?

**Comment by Aura314** [comment]
Updating Atmospehre to 19.5 and updating your Firmware to 12.1.0.

**Comment by fincs** [comment]
Reopen using the issue templates.

**Comment by trextaco9** [comment]
> Updating Atmospehre to 19.5 and updating your Firmware to 12.1.0.

well i updated both firmwares and now it's stuck at the logo

**Comment by Masamune3210** [comment]
How did you update

**Comment by trextaco9** [comment]
> How did you update

used daybreak, preserve settings and fat32 and exfat

**Comment by Masamune3210** [comment]
clean sd card of anything that isnt the Nintendo folder to a safe place, and extract a clean download of atmosphere onto the card and try pushing fusee again

**Comment by trextaco9** [comment]
I'm able to use the switch now but I'm still getting the error of the first problem on super mario odyssey, and now some of my games are unable to start software. the problems gotten worse.

**Comment by trextaco9** [comment]
scratch that all of them

**Comment by trextaco9** [comment]
except the ones that were installed before cfw

**Comment by trextaco9** [comment]
> clean sd card of anything that isnt the Nintendo folder to a safe place, and extract a clean download of atmosphere onto the card and try pushing fusee again

I now have the first problem of 2162 0002 again everythings updated and working all the games will start up but still do the first error

**Comment by Masamune3210** [comment]
reopen issue using the template and state all known information and fill out the template.
