### ISSUE TITLE
Panic Occurred while running Atmosphere (0xFFE)

### ISSUE THREAD

**Issue by bluetypewriter** [Atmosphere-NX/Atmosphere#1589]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
Power on with jig and RCMloader attached
Sept by Atmosphere graphic is displayed
Atmosphere graphic is displayed
Black screen
Atmosphere logo is displayed (white logo on black background)
Error is thrown
 
Panic occurred while running Atmosphere

Title ID: 0100000000000002b
Error: std: abort (0xFFE)

Press POWER to continue

Issue occurred after upgrade to Atmosphere 0.19.5</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
None, other than the upgrade.  Upgrade was completed as a clean install</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>
N/A</br>

### How can the issue be reproduced?
Boot into Atmosphere

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

</br>
[report_0c468170.zip]( https://github.com/Atmosphere-NX/Atmosphere/files/6958818/report_0c468170.zip )

### System Firmware Version

12.1.0</br>
</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Attempted with both.  Issue is the same regardless
- Official release or unofficial build: 
  - Official 0.19.5
- Do you have additional kips or sysmodules you're loading:
- No
- Homebrew software installed: 
- Daybreak
- EmuMMC or SysNAND:
  - EmuMMC, partition based

### Additional context?

- Additional info about your environment:
- SD Card is formatted as FAT32
- I tried resetting Arch bit in hektate
- SysNAND works without issue
- This appears to be related to https://github.com/Atmosphere-NX/Atmosphere/issues/1523 and https://github.com/Atmosphere-NX/Atmosphere/issues/1256 , however I completed the steps outlined in this issue (mount system partition and delete 80000000000000D1, 8000000000000050 and 800000000000005, restore PRODINFO from NAND backup) and issue is still occurring
- I have also seen posts about this issue being related to an outdated MissionControl.  I have updated MissionControl and issue is still occurring.

**Comment by bluetypewriter** [comment]
Issue is not with atmosphere.  Corrupted EMUNAND.  Discussed in discord and decided to export saves and rebuild a new EMUNAND

**Comment by einalrem** [comment]
I have the same problem now. Im using SysNand. But still get this message. 
Panic occurred while running Atmosphere,
Title ID: 0100000000000002b
Error: std: abort (0xFFE)
