### ISSUE TITLE
Home button stops working, then Atmosphere crashes if launching a game, then rebooting shows a fatal error and rebooting again works normally

### ISSUE THREAD

**Issue by serovar** [Atmosphere-NX/Atmosphere#1596]
### What's the issue you encountered?

The home button stops working, and if I launch a game Atmosphere crashes with Error Code: 2105-0602 (0x4b469) and Program: 0100000000001007.

After that I reboot and get a fatal error with Program ID: 010000000000102b and Error Desc: std::abort() called (0xffe).

Then I reboot again and Atmosphere starts normally.

### How can the issue be reproduced?

It happens every time a wake my Switch from prolonged sleep mode (I usually wake it once a day, and it happens every day).

### Crash Report

[Crash Gist](https://gist.github.com/serovar/6f41ac9e31b7eb8095cccf3a411608f4#file-01629651858_010000000000002f-log)

[Fatal Error Report](http://e.pc.cd/a32otalK)

### System Firmware Version

12.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusèe
- Official release or unofficial build: 
  - Official release version 0.19.5
- Do you have additional kips or sysmodules you're loading: no
- Homebrew software installed: Awoo Installer, Edizon, RetroArch, AIO Updater
- EmuMMC or SysNAND:
  - EmuMMC partition-based

### Additional context?

When searching for this issue I found [a similar one](https://github.com/Atmosphere-NX/Atmosphere/issues/1524), but I don't understand if it's the same thing. If it is so, I already tried using HacDiskMount to mount the SYSTEM partition for deleting the system settings save, but when I try to open it Windows tells me that I need to format the drive before using it, and if I refuse it tells me that it is not accessible.

**Comment by fincs** [comment]
> Awoo Installer

Piracy is not supported.
