### ISSUE TITLE
Fatal error: Failed to stat stage2 (atmosphere/fusse-secondary.bin)

### ISSUE THREAD

**Issue by Wave767** [Atmosphere-NX/Atmosphere#1597]
Error Code after ejecting payload in rcm mode

**Comment by SciresM** [comment]
You didn't use the issue templates.

**Comment by Masamune3210** [comment]
semi-related but whatever happened to implementing those issue filters?

**Comment by SciresM** [comment]
That's pending my paying attention to that.
