### ISSUE TITLE
Mariko version atmosphere v20 heat up and lag problem  after the update

### ISSUE THREAD

**Issue by skywalker454** [Atmosphere-NX/Atmosphere#1598]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

 after i update  my mariko version to the latest version  of atompsher v 20 i notice a significate improves in the  boot up process   also  i have notice  that the ram speed  increased to 1666mhz when i left my device in the standby   for 5 minutes  i found it  lags  heats   up quick  it does`t crash but that game  stuttering alot  lags 
### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

   unfortunately there`s  was  no crash occurs it was just a performance issue  after the update 
### System Firmware Version

![the current atomapher version 19 5](https://user-images.githubusercontent.com/89725437/131248506-0387b027-cf76-4358-8071-76ebb60f81af.jpeg)
![before the  update atomaosher version v19 5](https://user-images.githubusercontent.com/89725437/131248507-e257926b-e851-4d30-bc77-a2b4f39b54a7.jpeg)
![after the atomopher update v 20](https://user-images.githubusercontent.com/89725437/131248509-4513f09f-37ef-4c6c-9f45-bbd624751eea.jpg)
![boot looder](https://user-images.githubusercontent.com/89725437/131248563-51b0c1a4-d871-473c-a1ea-f5d5812c1028.png)

[
### Environment?

boot loader heakte
![boot looder](https://user-images.githubusercontent.com/89725437/131248569-cf7e80b6-15fb-4a9a-ac6a-9db40b77a17f.png)
 that`s   the boot loder ini file that  iam using  and it works fine with my pervious of  19.5 atmosphere it boot directly  
  -  official version   atmosphere version 20
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     -the atmosphere version i get from  GitHub  Atmosphere-NX
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
-ysNAND: version 

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by skywalker454** [comment]
kindly  your support is highly appreciated   the device become boot  up quick but the  problem when open  games it freez and heat up quuck   if  that r  related  ram over clocking i  have  notices that the ram speed become  1666 mhz

**Comment by masagrator** [comment]
You didn't use properly issue template.
Beside use full sentences with dots. Your comment is hard to read.

**Comment by skywalker454** [comment]
okay sorry iam still new in github  i was trying to say that my  mariko version after  it updated with the   latest  atmosphere v20 it start to heat up quick  when i open games some times freeze when i roll back to the  pervious version 19.5 it works fine what the cause   of  the issue ? 
thanks in advance

**Comment by lowburger** [comment]
Fill issue in properly... it's dumpster fire

**Comment by orbstar8** [comment]
In summary I will tell you what happens, because the same thing happens to me, I have a mariko switch, when I put the console in standby mode, for some reason, the use of the GPU does not drop below 40%, and the system both the games go with too many performance problems and even graphics !!  FW 12.0.3 EmuNAND

**Comment by skywalker454** [comment]
> In summary I will tell you what happens, because the same thing happens to me, I have a mariko switch, when I put the console in standby mode, for some reason, the use of the GPU does not drop below 40%, and the system both the games go with too many performance problems and even graphics !! FW 12.0.3 EmuNAND

  yeaa    the same thing happens to me  if i  left it in standby   mode i found it fired up and lags alots  is that due  to  ram over clocking speed   it  increase up to  1666mhz ?

**Comment by skywalker454** [comment]
> In summary I will tell you what happens, because the same thing happens to me, I have a mariko switch, when I put the console in standby mode, for some reason, the use of the GPU does not drop below 40%, and the system both the games go with too many performance problems and even graphics !! FW 12.0.3 EmuNAND



> > In summary I will tell you what happens, because the same thing happens to me, I have a mariko switch, when I put the console in standby mode, for some reason, the use of the GPU does not drop below 40%, and the system both the games go with too many performance problems and even graphics !! FW 12.0.3 EmuNAND
> 
> yeaa the same thing happens to me if i left it in standby mode i found it fired up and lags alots is that due to ram over clocking speed it increase up to 1666mhz ?
  all i concern  about will   that affects me  in an y next official  update by atmosphere ? :(

**Comment by digglife** [comment]
If you really want the maintainers to help on this issue, at least make some effort to format the bug report as the template guides you. The basic manner for raising issue: proper format and information as detailed as possible.

**Comment by skywalker454** [comment]
> If you really want the maintainers to help on this issue, at least make some effort to format the bug report as the template guides you. The basic manner for raising issue: proper format and information as detailed as possible.

i uploads attached files  is that okay with the post

**Comment by SciresM** [comment]
This issue is incoherent.

That said, it sounds like your switch (lite?) has some problems with lag due to memory defaulting to 1600MHz (since we train it to that point) or something?

I guess these are my questions.
1. Does the issue occur booting AMS 0.20.0 via hekate fss0 instead of fusee-primary?
2. Does the issue occur booting without any custom system modules? Please post a screenshot of your /atmosphere/contents folder, and make sure there is nothing in it when testing.

I guess potentially we'll need to only train switch lites to 1331MHz, depending on whether this is common for lites.

**Comment by SciresM** [comment]
Sigh, okay you closed this and opened a duplicate. I'll go copy over my comment.
