### ISSUE TITLE
mariko version heated up  after    upgrading  from  version  19.5 the latest   version  of atmosphere 20

### ISSUE THREAD

**Issue by skywalker454** [Atmosphere-NX/Atmosphere#1600]
What's the issue you encountered?
After upgraded from 0.19.5 to 0.20.0 the boot time is extremely decreased 
but the system is lag, delay or not responsive at all.
Ex. like   left  it on the stand by mood and i figured out it heated up alot and  horrible stuttering in the game 

Long press the power botton and use the dpad to select menu items, Notice the delay after press the dpad and the hilighted menu item.  one the lag examples 

game frame rate  is unplayable at all 
The worst case is Switch not response, I've holding down the power button to force shutdown.
How can the issue be reproduced?
Upgrade to 0.20.0

Crash Report
n/a, unfortunately the sdcard was formatted to rollback to 0.19.5

System Firmware Version
12.1.0
![WhatsApp Image 2021-08-29 at 1 12 27 PM](https://user-images.githubusercontent.com/89725437/131249555-990f24e5-ce17-4a83-ab83-5839696090e1.jpeg)

Environment
What bootloader?
  it  boot directly to the swtich   it works fine with the  pervious  19.5   
that`s the boot loader ini files i got in  my boot loader  folder  
![boot looder](https://user-images.githubusercontent.com/89725437/131249573-c2ed2173-390c-4811-83ca-762f12c1d678.png)

Official release or unofficial build?
Atmosphere Official release 0.20.0

Do you have additional kips or sysmodules you're loading:
n/a (overlay menu?)
i got edizon   and tesla  and they are working fine in the pervious 19.5 version 

Homebrew software installed:
EdiZon, tinfoil, chiaki, aio-switch-updater,emuiibo  day break   goldeleaf 

EmuMMC or SysNAND:
SysNAND  (file-based)

Additional context?
 your  help is highly appreciated thanks in advance

**Comment by SciresM** [comment]
It sounds like your switch (lite?) has some problems with lag due to memory defaulting to 1600MHz (since we train it to that point) or something?

I guess these are my questions.

1. Does the issue occur booting AMS 0.20.0 via hekate fss0 instead of fusee-primary?
2. Does the issue occur booting without any custom system modules? Please post a screenshot of your /atmosphere/contents folder, and make sure there is nothing in it when testing.

I guess potentially we'll need to only train switch lites to 1331MHz, depending on whether this is common for lites.

**Comment by skywalker454** [comment]
yeaa it works perfectly fine with  that speed  1331 mhz  ram  on version  19.5   
![folder 1](https://user-images.githubusercontent.com/89725437/131249867-3b99e587-7f19-4d7b-ac95-d333c2762001.PNG)
![folder 2](https://user-images.githubusercontent.com/89725437/131249868-5286d2ea-ea63-4062-823d-651019c57d70.PNG)
![folder 3](https://user-images.githubusercontent.com/89725437/131249869-605d7d2d-6ab5-44a5-bd49-2e0a6e9fc863.PNG)
![folder 4](https://user-images.githubusercontent.com/89725437/131249871-d83a08dc-adcf-43c5-8737-5fdd669b6dc3.PNG)

**Comment by skywalker454** [comment]
at the first i thought in first that it  could that happen due to memory speed  over clock as i  found it after  a couble i of minutes afer lunching game   it start to heat up quick even with any game

**Comment by SciresM** [comment]
You did not post /atmosphere/contents on your SD, or answer either of my questions.

**Comment by skywalker454** [comment]
![contents](https://user-images.githubusercontent.com/89725437/131250026-b1c35506-dcfe-431f-b387-241ddb26a7f9.PNG)

**Comment by skywalker454** [comment]
i used  the primary fuse that is what in my sd card

**Comment by skywalker454** [comment]
i  don`t use  hekate  it`s just boot directly to atmosphere

**Comment by skywalker454** [comment]
what  the folder content got  many folders when i opened it  what these files refers too i thought it something releated to atmosphere files  and  it was in  the pervious  version of  19.5

**Comment by parnz** [comment]
@skywalker454 you need to upgrade to 0.20.0 again and then provide any info/picture as requested by @SciresM 
Not your current 0.19.5

**Comment by zemixe** [comment]
@parnz if you have a Switch Lite too please provide the required information in this issue.

**Comment by parnz** [comment]
> @parnz if you have a Switch Lite too please provide the required information in this issue.
If @SciresM allowed me. I will do.

**Comment by skywalker454** [comment]
> @skywalker454 you need to upgrade to 0.20.0 again and then provide any info/picture as requested by @SciresM
> Not your current 0.19.5

 okay i will do it

**Comment by skywalker454** [comment]
![atmospher](https://user-images.githubusercontent.com/89725437/131251935-b67dd325-a4a2-4a91-95a3-45d7a38c9039.PNG)
![contents](https://user-images.githubusercontent.com/89725437/131251939-14feb458-2a19-4f49-b297-af96dc643acc.PNG)

**Comment by skywalker454** [comment]
i  used the  hekate version  hekate_ctcaer_5.6.0 this time

**Comment by skywalker454** [comment]
the pics i provided i took from my sd card   as  a backup from my hdd driver but that currently the files  found  in my sd card now 
after the update

**Comment by skywalker454** [comment]
![boot loader](https://user-images.githubusercontent.com/89725437/131252074-3c9b7875-9aaf-4ad6-b99e-30c1800a04d0.PNG)

**Comment by skywalker454** [comment]
guys   i posted all the  pics  you asked me  your  help is highly appreciated iam just what concerns me that i  won`t  be able to update switch atmosphere in future   :(

**Comment by skywalker454** [comment]
can you make a version  with   the normal  ram speed  could be the   issue  ?

**Comment by SciresM** [comment]
fwiw another user has confirmed this on his lite on discord...you aren't a native english speaker I think so I've been having him do some tests for me.

Don't worry, I'll try to fix it, and if I can't I'll at the very least add an option to disable boot-memory training on switch lite.

Also, you can just boot using hekate instead of fusee.

**Comment by SciresM** [comment]
Double fwiw, it appears this is happening (exclusively(?)) on DRAM ID 12 (Samsung Hoag).

A user with a lite on DRAM ID 14 has reported no issues in several weeks of usage.

**Comment by skywalker454** [comment]
so  what you means  that  it  occurs on some  specific switch hardware devices like mine ?

**Comment by Laurentiu-85** [comment]
I have same problem on switch lite on latest AMS when i boot via fuse-primary .if i launch with hekate fss0 work very vell.

**Comment by skywalker454** [comment]
What the best to  fuse to boot the primary or the other one ?

**Comment by vicoy032193** [comment]
I have the same issue. switch lite Dram 14. im booting using hekate fss0. so i decided to downgrade for now so i can play any game smoothly.

**Comment by SciresM** [comment]
Yes, a solution has been identified for this issue which in truth affects all lites. It will take me a day or two though.

**Comment by parnz** [comment]
My Switch Lite have DRAM ID 19 also have this issue.

**Comment by SciresM** [comment]
Yes, as mentioned all lites affected.
