### ISSUE TITLE
Fatal error: [MTC]: Failed to find timing table!

### ISSUE THREAD

**Issue by elementfan94** [Atmosphere-NX/Atmosphere#1603]
I get this weird error when try accessing my emunand on the switch. When I hit power to reboot it loads up just find. I just get this weird error when I access onto my emunand. Am I missing something or was there something Im not doing right?

**Comment by lowburger** [comment]
> Am I missing something

Yes you miss all important information from issue template which you completely delete...

**Comment by Masamune3210** [comment]
Either close this one and start a new issue and fill out the template or copy it here and edit your issue to fill out the template. Either way we need it
