### ISSUE TITLE
Error with last update 0.20.1

### ISSUE THREAD

**Issue by NathanIfinity** [Atmosphere-NX/Atmosphere#1605]
I tried updating from AIO and now every time I boot into Atmosphere with the new Fusee Primary.bin i get an errror
FATAL Error [NXBOOT] Failed to run TSEC Firmware -6 

if I reboot everything loads fine and everything works as expected?? 

not sure what to do about the error ?

**Comment by SciresM** [comment]
1. You did not use the issue templates.

2. You're probably booting via gateway's stuff, which results in invalid environment prior to reboot-to-self. Don't use gateway's stuff.
