### ISSUE TITLE
[NXBOOT] Failed to run TSEC firmware -6 with version 0.20.1

### ISSUE THREAD

**Issue by NathanIfinity** [Atmosphere-NX/Atmosphere#1606]
What's the issue you encountered?
When booting into atmosphere with 0.20.1 I receive the following error message:
[NXBOOT] Failed to run TSEC firmware -6 d0d0d0d0 d0d0d0d0!

How can the issue be reproduced?
Booting into Atmosphere with hekate v5.6.0 & Nyx v1.0.6

Crash Report
/atmosphere/crash_reports folder does not exist

System Firmware Version
12.1.0

Environment?
What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate, also tried booting Fusee primary directly, still same error message

Official release or unofficial build: official release hekate v5.6.0 & Nyx v1.0.6

Do you have additional kips or sysmodules you're loading: No

EmuMMC or SysNAND: EmuMMC, file-based : SysNAND

Additional context?
Issue only started when I updated to 0.20.1 was working fine with the old version:  0.19.5
put  0.19.5 back and everything is back like it was

I use the loader I got when I first got my Sxos to load Hekate or fusee primary
I saw on other issue you recommend spcaecraft-nx , but not sure exactly what it is.

also not sure what this means: gateway's payload loader (sorry for the noob question)

thanks

**Comment by SciresM** [comment]
Are you on a patched console? What do you use to launch hekate/atmosphere?

**Comment by SciresM** [comment]
Ah "I use the loader I got when I first got my Sxos"

yeah this is gateway's loader.

Not supported, use spacecraft-nx.

**Comment by NathanIfinity** [comment]
day 1 switch, unpatched, so something changed between 0.19.5 and 0.20.1 ?? because it worked fine before
what exactly is spacecraft-Nx? to I need to replace my loader ?

**Comment by SciresM** [comment]
If you're unpatched, just send fusee or hekate directly via the rcm bug.

the issue is that you're using gateway's loader.
