### ISSUE TITLE
Error 2001-0123 (0xf601) - first time boot

### ISSUE THREAD

**Issue by patrickmau** [Atmosphere-NX/Atmosphere#1608]
### What's the issue you encountered?
Atmosphere crashes on first-time boot immediately after final Nintendo Switch logo disappears.

Error Code: 2001-0123 (0xf601)
Program: 010000000000001F
Firmware: 12.1.0 (Atmosphere M 0.20.1-master-165c9261)

### How can the issue be reproduced?

Boot into Hekate
Open "Launch" menu
Launch default "Atmosphere CFW" entry (fusee-primary.bin)

### Crash Report

https://gist.github.com/patrickmau/6538c7a96ec84c1bcbaac0ec036b2e3b.js</br>

### System Firmware Version

Model: Erista with SXOS Pro modchip
emuMMC FW: 12.1.0
SysNand FW: 12.1.0
Hekate: 5.6.0
AMS: 20.1
SD card: Sandisk 64GB
Partition: FAT32 via Hekate, with SD Files (not partition)

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
+ Hekate 5.6.0, fusee-primary (latest)

- Official release or unofficial build: 
+ official release of Atmosphere 0.20.1 with Hekate 5.6.0. and Nyx 1.0.6.

- Do you have additional kips or sysmodules you're loading:
+ None, folder /atmosphere/contents/ does not even exist
+ latest sigpatches have been applied (iTotalJustice)

- Homebrew software installed: [ * ]
- EmuMMC or SysNAND:
+ EmuMMC, SD File based

### Additional context?
The console has a SXOS Core/Lite modchip soldered into the system, I migrated to AMS a while ago and am using SX Gear to directly boot the hekate "payload.bin", from here I launch AMS via the "Launch" menu.

There are a few more issues I noticed
- cannot boot via secondary fusee (black screen of death, no error message, have to force restart)
- cannot boot into Stock SysNand (black screen of death, no error message, have to force restart)

A few things I tried to resolve the issue:
* fresh SD card - no result
* restore backup of 12.1.0 boot0/boot1 files - no result
* wiped SD card, partitioned via Hekate - no result
* created new emuMMC - no result
* load SXOS boot loader and run "Clean Up" routine to remove any traces from BCT (this was how I managed to get AMS 0.19.5 running on my console) - no result
* created generic boot0 file through universal keys and restored them via Hekate - no result (see this guide: https://www.sthetix.info/generating-a-fresh-boot0-from-scratch-fix-your-switch-now/)

**Comment by SciresM** [comment]
package2 mismatch due to incorrect update. Manually flash correct package2 to emmc. This issue tracker is for bugs, not for support.
