### ISSUE TITLE
Failed Boot

### ISSUE THREAD

**Issue by Shenron0** [Atmosphere-NX/Atmosphere#1609]
![IMG_20210906_221919](https://user-images.githubusercontent.com/29032309/132293442-fcb3043f-6c35-4364-aff2-a3a98c10cc57.jpg)
Tried a fresh boot up of 1.0.0 but I got this error instead, I'm not sure what else I need to provide so please tell me what else you will need

**Comment by masagrator** [comment]
You didn't use issue template and upload report mentioned in this image.

**Comment by Shenron0** [comment]
How do I use the issue template?

**Comment by zerofo** [comment]
i got the same error on the branch of latest fusee_cpp , which complied by myself at about 12hours ago . ( i through it is my fault , or the unofficially released branch's issues ) .
I haven’t to try the pre-release version for now .

**Comment by carcaschoi** [comment]
use hekate to fix archive bit

**Comment by SciresM** [comment]
Reopen using issue templates.
