### ISSUE TITLE
A fatal error occurred when running Atmosphere Title ID 010000000000002b Error Desc: std: :abort() (0xFFE)

### ISSUE THREAD

**Issue by letsdudiss** [Atmosphere-NX/Atmosphere#1614]
### What's the issue you encountered?
Suddenly issue occurred. Previously was running no issue. I noticed it when it was docked for a few days.

I have tried
- updating hekate to 5.5.8 and atmosphere 0.20
- format sdcard (to exFAT) and did a fresh copy of atmosphere and hekate
- Archive bit set/unset
- Loading stock firmware doesnt work either. It just ends up being a black screen
- Checked atmosphere/content dir but there is no 010000000000002b dir

### How can the issue be reproduced?
Boot into hekate, Launch CFW

Report bin attached, added .txt to make github happy
[report_01393a341.bin.txt](https://github.com/Atmosphere-NX/Atmosphere/files/7133352/report_01393a341.bin.txt)

Apologies for posting this recurring issue

**Comment by SciresM** [comment]
You did not use the issue templates.

Regardless, you have a corrupt PRODINFO/system save.

Follow the instructions/directions in #1256 for guidance. You'll need to restore a non-corrupt backup and/or delete the system settings savedata.
