### ISSUE TITLE
NTFS support pheasable?

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#162]
How difficult would it be to add NTFS support to atmosphere  I know it would be difficult but would it be a level of difficult to make it not worth it?     Exfat is just sooo fragile.   we need a journaling filesystem.

**Comment by mariogamer2** [comment]
Honestly better implement ext* filesystem at this point. Ntfs is only useful for a few things, that ext* do better (in general). Only an opinion tho.

**Comment by fincs** [comment]
ext\* is almost *impossible* to use on Windows. NTFS can be used on all 3 major OSes.

**Comment by adamnock** [comment]
Why not go with something really obscure, like BeFS, so that everyone has difficulty with it and the project can help build global cooperation and lead to a better world?

**Comment by mariogamer2** [comment]
Well I remember the wii days where you could have a disk/sd formatted in ext*/ntfs/*fat. But I guess that's not the same at all.

(It'd be cool if a switch could read all these tho...)

@adamnock :p

**Comment by dmlemos** [comment]
Honestly `ext4` is the more compatible of the two. Let's see, `ext4` works on linux, android and bsd. `NTFS` is pretty much windows only. 

Besides `ext4` performance is better. To retain windows compatibility there is always `exFAT` already supported.

**Comment by fincs** [comment]
NTFS is not "Windows only". NTFS is supported right out of the box in most popular Linux distros (read/write, ntfs-3g & fuse), as well as macOS (read-only, unless macfuse is used). ext4 simply does not work properly outside Linux. There do not exist stable free ext4 fs drivers for Windows **at all**.

**Comment by fennectech** [comment]
Well NTFS-3g on linux provides adequate support (Read Write Repair and Create.).  While my linux box cannot repair an exfat drive and fat32 is just shite.  I say NTFS is the best option.   And I’m a *nix user.

**Comment by fennectech** [comment]
Ext4 doesnt work on windows (personally not a problem for me  but compatibility is important for a community release).  Ive found exfat to be really fragile.   Without any journaling its really not tolerant to power failures or bad shutdowns (wich happen a lot on homebrew)    Plus it would be far more tollerant of app crashes that normally botch our exfat filesystems

**Comment by fennectech** [comment]
How about fat12?  Or we can blindly write bytes to the disk so NOBODY can make sense of them. Not even us!

**Comment by parrotgeek1** [comment]
@fennectech ^ I think that's called WBFS :-p

**Comment by fennectech** [comment]
That was a huge mess.

**Comment by fennectech** [comment]
Supposedly Apple improved NTFS support on macOS     I say NTFS Is the best.  It has wid reaching support.

**Comment by SapphireExile** [comment]
ExFAT would be the best in terms of total compatibility. NTFS has issues on some linux distro (mounted read only you say?), while ExFAT is wholly compatible.

**Comment by TuxSH** [comment]
ExFAT is supported.

Implementing support for anything that FAT* and ExFat is a waste of time since HOS doesn't support it anyway.

Also please use a spell checker -- the horrible spelling mistake in the title of your 'issue' already gives a bad impression itself.

**Comment by jonirrings** [comment]
fs support is a time wasting hardwork, 

I don't think there is any necessity to implement any other fs support other than fat32 and exfat.

**Comment by fennectech** [comment]
THe reason is the fragility of bolth exfat and fat32.  Nether of them support journaling

**Comment by jonirrings** [comment]
@fennectech just forget the fragility, even ninty does not care about it.
