### ISSUE TITLE
Not compatible with update 13.0.0

### ISSUE THREAD

**Issue by Santiav90** [Atmosphere-NX/Atmosphere#1622]
### What's the issue you encountered?

I'm still not sure if this is where I'm supposed to post this, but I do it for most updates and people search for a post like this to see if an update has been released already, but yeah, atmosphere crashes with the latest switch update.

### How can the issue be reproduced?

update your switch

### System Firmware Version

13.0.0
### Environment?

Running the latest atmosphere update

**Comment by sapycola** [comment]
Confirm for me... 
Wait next Atmosphere version!

**Comment by Masamune3210** [comment]
Its well known and well announced by almost every hacking news or group setting that atmos will almost never work with a new major update. this happens literally every time

**Comment by Conan179** [comment]
https://twitter.com/SciresM/status/1437945978657468417

**Comment by jajie95** [comment]
Personaly, I'm a little new on this so I updated my switch to 13.0.0 and after that the appearing error says: A fatal error running Fusee,  unable to identify package1! 
Waiting for update xD
