### ISSUE TITLE
Failed to open sdmc:/atmosphere/package3

### ISSUE THREAD

**Issue by joey-lg** [Atmosphere-NX/Atmosphere#1625]
Running latest atmosphere version and switch firmware. Switched from fusee primary to fusée.
Latest hekate version.

**Comment by SciresM** [comment]
1) you didn't use the issue templates

2) you didn't extract the latest atmosphere release zip to sd, or you have the archive bit set on the atmosphere folder. one of the two.

**Comment by Mewthree3** [comment]
You also probably updated to 13.0.0 mistakenly. Wait for a new atmosphere release?

**Comment by SciresM** [comment]
Updating to 13.0.0 wouldn't cause this.

**Comment by jonklee99** [comment]
Yes my switch updated then it wouldnt go into CFW
