### ISSUE TITLE
Issue with system_setting.ini

### ISSUE THREAD

**Issue by Yeldah28** [Atmosphere-NX/Atmosphere#1626]
Fatal auto reboot after crash doesn't work anymore and saving cheat toogles doesn't work either seems like the config file doesn't load correctly. I have tried to delete the config file downloaded a new one and rebooted to payload with no success.

**Comment by masagrator** [comment]
1. You didn't use issue template
2. Next time upload file in question from the beginning. It will save a lot of time.
