### ISSUE TITLE
Pre-release version doesn't work.

### ISSUE THREAD

**Issue by Androphonomania** [Atmosphere-NX/Atmosphere#1630]
### What's the issue you encountered?

I was installing the pre-release version of atmosphere 1.1.0. I injected the updated version of fusee.bin, then I was greeted with the atmosphere logo, then Nintendo Switch. It shows the charging battery for a split second before it crashed. It was just before the welcome screen. It gave an error code of 2162-0002, (0X4A2).

### How can the issue be reproduced?

I have no idea how the issue can be reproduced, but it keeps happening.

### Crash Report

I tried finding my crash report for today, but it wasn't there.

### System Firmware Version

13.0.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - Version 1.10
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [Goldleaf, ThemezerNX, and I don't think anything else matters.]
- EmuMMC or SysNAND: SysNAND

### Additional context?

- Additional info about your environment: I feel like this might be related to ThemezerNX, but I'm not sure.

**Comment by SciresM** [comment]
Delete your custom theme.

you also didn't provide the relevant crags report the templates ask you for.
