### ISSUE TITLE
Unable to Start Software

### ISSUE THREAD

**Issue by KatouHaru** [Atmosphere-NX/Atmosphere#1633]
Since updating to switch 13.0 and atmosphere 1.1.0 all my downloaded games won't run.

It shows:
"Unable to start software.
Retunr to the HOME Menu and try again."

I already tried reinstalling everything.

**Comment by Mewthree3** [comment]
Get sigpatches from ITeJay’s repo

**Comment by KatouHaru** [comment]
Thank you I did forgot about the sigpatches... Again.

**Comment by j-Kode** [comment]
@KatouHaru YOu need to download the sigpatches as mentioned by @Mewthree3 .

Heres the [link ](https://github.com/ITotalJustice/patches)

**Comment by SciresM** [comment]
Piracy is not supported.
