### ISSUE TITLE
Game Card not read

### ISSUE THREAD

**Issue by jongx3** [Atmosphere-NX/Atmosphere#1639]
Accidentally  updated to the newest switch firmware, but its now working with pre release of atmosphere 1.1.0 but im experiencing an issue where my game card cant be read anymore, tried different games

**Comment by bobwareinc** [comment]
Hey! 
If you go into atmosphere>config_templates, you should see stratosphere.ini. Copy this file and paste it into atmosphere>config. Then open the file in a text editor and add this line at the end: “nogc=0”. This used to be in the BCT.ini, but was removed in the newest atmosphere release. 
Let me know if it worked!

**Comment by jongx3** [comment]
Thank you, its working perfectly now @bobwareinc
