### ISSUE TITLE
static file analyser results

### ISSUE THREAD

**Issue by lorek123** [Atmosphere-NX/Atmosphere#164]
I've ran [cppcheck](http://cppcheck.sourceforge.net) against whole repo and got results:

> [exosphere/src/bootup.h:63]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
> [fusee/fusee-primary/src/lib/ini.c:127]: (error) Deallocation of an auto-variable results in undefined behaviour.
> [fusee/fusee-primary/src/sdmmc/sdmmc.c:52]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
> [fusee/fusee-primary/src/sdmmc/sdmmc_core.c:609]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
> [fusee/fusee-primary/src/sdmmc/sdmmc_core.c:621]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
> [fusee/fusee-secondary/src/fs_dev.c:442]: (error) Uninitialized variable: f
> [fusee/fusee-secondary/src/lib/ini.c:127]: (error) Deallocation of an auto-variable results in undefined behaviour.
> [fusee/fusee-secondary/src/nxboot.c:102]: (error) Uninitialized variable: pk2file
> [fusee/fusee-secondary/src/nxboot.c:103]: (error) Uninitialized variable: pk2file
> [fusee/fusee-secondary/src/nxboot.c:112]: (error) Uninitialized variable: pk2file
> [fusee/fusee-secondary/src/nxboot.c:116]: (error) Uninitialized variable: pk2file
> [fusee/fusee-secondary/src/sdmmc.c:303]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
> [fusee/fusee-secondary/src/sdmmc.c:307]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
> [fusee/fusee-secondary/src/sdmmc.c:456]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
> [fusee/fusee-secondary/src/sdmmc.c:3319]: (error) Shifting signed 32-bit value by 31 bits is undefined behaviour
> [stratosphere/loader/source/ldr_nso.cpp:36]: (error) Resource leak: f
> [thermosphere/src/lib/ini.c:127]: (error) Deallocation of an auto-variable results in undefined behaviour.
> 

Most of them looks like false positives, but maybe you will find something useful.

**Comment by hexkyz** [comment]
The results that were not false positives have now been fixed in the latest commits.
