### ISSUE TITLE
"Fatal error: [NXBOOT]: Unable to identify package1!"

### ISSUE THREAD

**Issue by jlopez2310** [Atmosphere-NX/Atmosphere#1640]
Updated the nitendo switch to the latest version 13.0.0.
And I did the last download of the atmosfere and installed everything correctly with the "RCM Loader" and the screen goes all black and if I try again it looks like "Fatal error: [NXBOOT]: Unable to identify package1!".

What should you do to get the atmosphere back on track?

**Comment by Mewthree3** [comment]
Use the issue template next time please!
How’re you booting? Hekate or Fusee?

**Comment by Aura314** [comment]
you have not used the details of the template please open a new one because without a template it will simply be closed please folks please do yourself a favor it saves you time and you don’t have to rewrite it over and over again your problem with atmospehre!

**Comment by jlopez2310** [comment]
I'm starting with Fusee.
And how do I do this from the model details?

**Comment by abdelmoumen03** [comment]
Hi guys if u use new atmosphe downgrade the consol to 12.1 and wait atmosphere for 13.0

**Comment by Aura314** [comment]
The new atmosphere for Hos 13.0.0 has long been published!

**Comment by abdelmoumen03** [comment]
There is a loot of beugs so still waiting the final version of atmosphere

**Comment by jlopez2310** [comment]
At this moment it already appears to me "Fatal error: failed to stat stage2 (fusee-secondary.bin)!"

**Comment by SciresM** [comment]
1. You didn't use the issue templates 
2. This is because you didn't update properly.

@abdelmoumen03 there have been zero actual bugs so far. Just user errors.
