### ISSUE TITLE
I try to start atmosphere but I can't because there is a yellow screen

### ISSUE THREAD

**Issue by Pnuru** [Atmosphere-NX/Atmosphere#1643]
## Bug Report

I have updated, I have copied all the elements of the atmosphere update to the sd of my switch, and I also update sigpatches with the concordant version of 1.1.0 but when using the tegraRcmGui, the atmosphere screen is shown, but after that nothing happens and you are left with the yellow screen, is there any way to fix it?

### Additional context?

im using a 2017 switch and trying with hekate and atmosphere

**Comment by SciresM** [comment]
1) You did not use the issue templates
2) You did not properly update your hekate config, which I would also note is not related to atmosphere.
