### ISSUE TITLE
Reboot after Press the Power Button

### ISSUE THREAD

**Issue by KiidInc92** [Atmosphere-NX/Atmosphere#1646]
Hello at all
I have a Problem, i think its Atmosphere, everytime i go in Sleep Mode with my switch, its Restart my Console, i hope someone can help me

**Comment by Sci3ntia** [comment]
you need use the issue template and provide more information

**Comment by KiidInc92** [comment]
Ok then close this Thread, my English isnt good enough to understand and write correctly in english

**Comment by empithree8** [comment]
Hi sorry to reply to the closed thread. But I think I have a solution for this. Please remove nxbtred and Missioncontrol from HB. most probably nxbtred hb app causes the rebooting when sleep.
