### ISSUE TITLE
Issue updating to latest update 

### ISSUE THREAD

**Issue by trillyxri** [Atmosphere-NX/Atmosphere#1647]
So basically my little brother updated to the 13.0.0 nintendo update like an idiot and I had to wait for the latest atmosphere update went on and downloaded the update replaced all the files in the corresponding folders and booted via pc tegrarcm using the new fusse.bin and I'm getting this
![IMG_20210924_151716](https://user-images.githubusercontent.com/91345645/134728874-ac4c83f0-ae60-4f74-a38c-ba7990a4f997.jpg)

**Comment by Glitch-Code-Design** [comment]
Delete that folder , it's under atmosphere / contents , you or your brother should remove your themes before updating

**Comment by SciresM** [comment]
You didn't use the issue templates, and delete your custom theme.

**Comment by trillyxri** [comment]
Appreciate the response gonna fix it today

**Comment by trillyxri** [comment]
it wont let me delete the folder lmao i right click nothing pops up @SciresM

**Comment by trillyxri** [comment]
nevermind i got it im an idiot
