### ISSUE TITLE
Panic occurred while running Atmosphere

### ISSUE THREAD

**Issue by nooksta** [Atmosphere-NX/Atmosphere#1654]
### What's the issue you encountered?

After moving all my files out of my sd card (I had previously used atmosphere on exFAT), reformatting to FAT32, then moving back into the sd card, when I try to boot atmosphere it gives me the error:
Panic occurred while running Atmosphere
Title ID : 0100000000000002b
Error: std::abort (0xFFE)
Hekate works normally, etc. Tried mounting system partition and deleting 80000000000000d1, tried deleting the contents folder and replacing my atmosphere folder with the newest release even though I already had it. Same thing pops up.

### How can the issue be reproduced?

Not sure/possibly same thing I did.

### Crash Report

[report_0000000007547940.zip](https://github.com/Atmosphere-NX/Atmosphere/files/7277527/report_0000000007547940.zip)
(edit: had wrong file so uploaded the correct one from fatal errors folder)

### System Firmware Version

newest version

### Environment?

- hekate, atmosphere official release 1.1.1
- homebrew software: tesla, sys-clk, sys-ftpd-light, hbmenu, hbappstore, breeze, KosmosToolbox, EdiZon-SE, Goldleaf, 
nxdumptool, NxThemes Installer, ThemezerNX, SwitchPresence-Rewritten, retroarch
- SysNAND

**Comment by Aura314** [comment]
you are such a hero you are doing piracy on your main memory the switch you are banned piracy is not supported.

**Comment by masagrator** [comment]
> you are such a hero you are doing piracy on your main memory the switch you are banned piracy is not supported.

Are you okay? Your attitude is not commendable.

**Comment by nooksta** [comment]
> you are such a hero you are doing piracy on your main memory the switch you are banned piracy is not supported.

I haven't installed any nsps or done any piracy at all. I honestly don't know what some of my homebrew apps even do if some are for that purpose since I got a lot of them through sdsetup.

**Comment by fincs** [comment]
Bundles redistributes by third parties are notorious for containing all sorts of junk (some of it piracy related) that can interfere and cause system stability problems. Please try again with a clean installation using the [official release binaries](https://github.com/Atmosphere-NX/Atmosphere/releases/latest), and reopen the issue if the problem persists.
