### ISSUE TITLE
Yellow screen

### ISSUE THREAD

**Issue by Krstox** [Atmosphere-NX/Atmosphere#1655]
Hi i have a problem, i updated the system to 13.0.  -> nothing works
Then i updated atmosphere and hekate, now i get a yellow screen when i want to start atmosphere.
can anybody help me?

**Comment by j-Kode** [comment]
I'm pretty sure there's an issue template you need to use. If it's an issue.

**Comment by SciresM** [comment]
You didn't use the issue templates.
