### ISSUE TITLE
SDCard issues with new SDCard Drivers(SDXC Related?)

### ISSUE THREAD

**Issue by me2151** [Atmosphere-NX/Atmosphere#166]
I get SDCard errors using the new SDCard Drivers with fusee-primary. The error I get is Failed to send OP Cond. I Believe this is due to my card being SDXC but I cannot confirm that as I do not have any SDHC Sdcards. I have tried 2 different SDXC SDCards, one is 128gb and one is 256gb. Both cards were tested as Fat32 and exFat.

Here is a photo of the error.

https://cdn.discordapp.com/attachments/461992992232964097/465315873264238592/20180707_203839.jpg

Let me know if you need any additional information.

**Comment by hexkyz** [comment]
There was a bug in the SDMMC clock speed setup. Could you please try again with the latest commit?

**Comment by me2151** [comment]
Yes I can try again In 6 hours(at work right now so no switch).

**Comment by me2151** [comment]
Still Does not work. Same error

**Comment by me2151** [comment]
@hexkyz Fixed with latest commit https://github.com/Atmosphere-NX/Atmosphere/commit/a2104b85ceb114aa104bddbad1871121305717fc
