### ISSUE TITLE
Monster Hunter Rise DLC content and Monster Hunter Stories 2 DLC content Crash/stuck issues

### ISSUE THREAD

**Issue by TerraFlareKSFL** [Atmosphere-NX/Atmosphere#1661]
What's the issue you encountered?

After updating Atmosphere to 1.1.1, I opened MonHun Rise and when the program starts loading the DLC content it crashes. I also opened MonHun Stories2 and when its about to load dlc content it stays stuck on black screen.

How can the issue be reproduced?

Loading the Monster Hunter Rise game and Monster Hunter Stories 2 (both are digital version) with DLC content.

Crash Report

Nintendo System Error Message: The Software Was Closed Because An Error Occurred

System Firmware Version
13.0.X

Environment?
What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate v5.6.3
Official release or unofficial build:
Official release version 1.1.1
Do you have additional kips or sysmodules you're loading: No (eliminated the atmosphere/contents folder before turning on the system
Homebrew software installed: [ daybreak, awoo, Goldleaf, checkpoint, jksv, edizon ]
Sigpatches updated for 13.0

Additional context?
So far with 40 games installed + their DLCs, MonHun Rise and MonHun Stories 2 are the only games giving issues once the DLC are installed.

**Comment by masagrator** [comment]
Awoo you say? Hmm...

**Comment by SciresM** [comment]
Ah, yeah, missed that.

piracy isn't supported.
