### ISSUE TITLE
LFS Romfs + Cheats crash

### ISSUE THREAD

**Issue by sSomename** [Atmosphere-NX/Atmosphere#1663]
### What's the issue you encountered?

Upon attempting to replace Metroid Dreads config file via Layeredfs the game would crash atmos with 010...0d title error. Testing my options for example placing the original file instead of an edited one etc.  I found that removing the cheats folder would allow the loading with the romfs mod.

### How can the issue be reproduced?

1. Adding cheats to Metroid Dread contents.
2. Adding romfs mod to Metroid Dread contents.
3. Attempting to launch the game

### Crash Report

https://gist.github.com/sSomename/981e446a32d6029a4b48e50f05c630b3

### System Firmware Version

13.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build:  Official release version 1.1.1
 Do you have additional kips or sysmodules you're loading: Tesla, SaltyNX
- EmuMMC or SysNAND: SysNAND

### Additional context?
N/A

**Comment by masagrator** [comment]
Well, I have done some shenanigans to prevent this issue and there was no report of issue for every other game in the same setup.

Write issue on my fork of SaltyNX repo and I will help to find what is going on.
