### ISSUE TITLE
Can't boot into atmosphere 1.1.1 with OFW 13.0.0

### ISSUE THREAD

**Issue by erikshinner** [Atmosphere-NX/Atmosphere#1664]
using the template you commented on another issue of someone that ended up fizing it by formatting SD card to FAT32, I would like to post this to see if anyone can help me.

### What's the issue you encountered?

I recently decided to move from sxOS to atomsphere after hanging on since last sxOS release more than a year ago. The main thing preventing me from doing it was that I had almost all of my games in .xci format and didn't want to have to convert them or re-download them in .nsp

I really wanted to try out the new Wario Ware game so I decided I'd finally move over completely.

While doing it, I thought it would also be a good idea to wipe my sysNAND with Haku33 and make a 'clean slate' emuMMC backup. Until now, everything is working great. I can boot into Hekate and launch my StockFW and even play Smash Bros online (I'm really surprised my switch is not banned, as I never even set up an emuNAND before.. I guess keeping it in airplane mode for the longest time has it's benefits)
Anyway... I played a while on my SysNAND without issue, then I decided I would start playing Warioware and some other NSPs on my CFW
So, I restarted, booted into RCM with Hekate... and when I launch Atmosphere CFW I get

```
Error Code: 2002-2634 (0x149402)
Program: 010000000000001F   _//I hope the amount of zeros is correct lol_
Firmware 11.0.0 (Atmosphere 1.1.1-master-99c74469e)      _// I don't understand why it says 11.0.0 if I had my OFW updated to 13.0.0 via Nintendo servers_
```

.... a lot of more error data is there which I won't type by hand but maybe I can post a screenshot replying to main post.

### How can the issue be reproduced?

by trying to launch Atmosphere via Hekate or by stacking the fusee.bin payload via TegraRCM

### Crash Report

[_reports.zip](https://github.com/Atmosphere-NX/Atmosphere/files/7341410/_reports.zip)

### System Firmware Version

13.0.0 (OFW)
11.0.0 (Atmosphere 1.1.1) //this is the weird part. That's the last FW version I had when using sxOS because it didn't support anything beyond. I always updated using ChoiDujour and I had to downgrade once via Daybreak because I realized sxOS wasn't working (from 11.0.1 down to 11.0.0 iirc)

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate, TegraRCM (on windows PC)
- Official release or unofficial build: Official from atmosphere github
- Do you have additional kips or sysmodules you're loading: Unknown, not that I know of
- Homebrew software installed: Unknown
- EmuMMC or SysNAND: EmuMMC partition based

### Additional context?

- Additional info about your environment:
Already did the "Fix Archive Bit" having no errors displayed.
atmosphere/fatal errors is empty... **/crash_reports** and **/fatal_reports/** DO have some .log files and a **dumps** folder with some .bin files in it

I guess I gave all the context at the beginning but let me know if there's anything else you need

_Originally posted by @takoyaki99 in https://github.com/Atmosphere-NX/Atmosphere/issues/1631#issuecomment-922590064_

**Comment by SciresM** [comment]
1. Piracy is not supported.
2. You burnt gamecard fuses for 12.x, this means you can never use gamecards on < 12.x ever again. Upgrade to 12.x/13.x to resume using gamecards, or configure nogc=0 (see atmosphere/hekate docs).

**Comment by erikshinner** [comment]
> 1. Piracy is not supported.
> 2. You burnt gamecard fuses for 12.x, this means you can never use gamecards on < 12.x ever again. Upgrade to 12.x/13.x to resume using gamecards, or configure nogc=0 (see atmosphere/hekate docs).

Thanks. Can you ellaborate on how to upgrade to 13.x? That's what I thought I did when I updated on OFW via Nintendo Software Update
(When it restarted I wasn't quick enough to put my paperclip jig so it booted into OFW again and I understand that burnt the fuses, preventing me from downgrading ever again. 
But the thing is, I don't want to downgrade.. I just want to be able to run 13.0.0 on atmosphere if that makes any sense

Or what exactly do you mean by "use gamecards on <12.x"?
