### ISSUE TITLE
[REQUEST] Expanded Cheat File Structure support

### ISSUE THREAD

**Issue by Th3Alic3** [Atmosphere-NX/Atmosphere#1673]
## Feature Request
Hello to the Atmosphere-NX team!

There's some QoL aspects missing from the CHEATS file structure missing from the foundations it borrowed and/or was inspired from. The result of which is the Cheat action applications are far more limited in their usage of this OS feature.

Currently Supported Features:

- Cheat Code Title
> [ ] 

Would you be able to add support for some additional support commands as long as they immediately follow the TITLE (before the code line starts)? I would like to request some of the functionality that was available in the XML Cheat Files for the Pro Action Replay from decades ago. Things that were quality of life that seem to have disappeared in recent years.

I would like to request support for a default on/off setting for individual Cheats:

- Cheat On/Off Default
> %ON%
> %OFF%

- Mulitple Options for the Cheat (allowing for different values in memory)
The format is each of the codes will have a subtitle under the base cheat (programs would use a radio button on the individual subtitle) so any number of cheats would appear under the same base title.
_(For example: You have a cheat that enable your character to have a power-up but there's 20 different ones in the game. This would prevent the Cheat system from enabling more than one at a time.)_
> #1# 
> #20#
> #BOMB#

- Notes
This would add a note that in the cheat program that could be displayed. This would provide the option of usage instructions to be associated with the cheats. Here's some examples:
> {Does not work on Level 15}
> {Crashes game if used together with Cheat 5}
> {Requires Fire Power}

**Comment by SciresM** [comment]
> I would like to request support for a default on/off setting for individual Cheats:

No, toggles file is sufficient, the use case for cheats imagines a helper (e.g. edizon/breeze, or ams.tma in the future).

> This would add a note that in the cheat program that could be displayed. This would provide the option of usage instructions to be associated with the cheats.

No. We are memory constrained, and the introduction of comments has been much discussed/discarded in the past. These kinds of things can be presented to the user by a helper without the data being inside the cheats file. 

I am fine with helpers storing their own metadata files about cheats, which would be a way to get the feature you want without changing cheats file format, for example.

This has been discussed a lot in the past, feel free to search logs in ReSwitched discord (or hold a new conversation about it there).
