### ISSUE TITLE
Error Code: 2246-0101

### ISSUE THREAD

**Issue by Sandpie00** [Atmosphere-NX/Atmosphere#1683]
## Bug Report

It just crashed while charging in sleep mode, I had no software running. I can't find the error online

### What's the issue you encountered?

It crashed

### How can the issue be reproduced?

Charge the Switch in sleep mode

### Crash Report

I'll provide one in a sec

### System Firmware Version

13.1.0

### Environment?

- Bootloader: Hekate 5.6.5
- Atmosphere 1.2.1 stable
- Sysmodules: Tesla Menu, sys-clk, emuiibo
- Homebrew software installed: Checkpoint 3.7.5, Daybreak, FTPD classic 3.1.0, HB App Store 2.2, melonDS release 6, NX-Shell 3.2.0, nxdumptool 1.1.14, Reboot to Payload, RetroArch 1.9.2, sys-clk manager 1.0.1
- SysCFW

### Additional context?

I have Skyline, I've heard that causes issues but I didn't have Smash/ARCropolis 2.1.0 running

**Comment by zemixe** [comment]
This is a bug that was fixed in atmosphere 1.2.2, update to latest.
