### ISSUE TITLE
Black screen after sept logo

### ISSUE THREAD

**Issue by MacedoXS** [Atmosphere-NX/Atmosphere#1689]
Firmware version: 13.1.0
Atmosphere version: 1.2.2
Payload used: Fuuse (last)

After inject a fuuse payload, shows atmosphére logo, sept logo, and a black screen. The system won't start.
On OFW, system start's as normal.

**Comment by Adubbz** [comment]
You've mentioned the sept logo, however sept no longer exists in the latest version of Atmosphere. You need to update Atmosphere correctly.

**Comment by takoyaki99** [comment]
Are they not referring to a bootlogo from hekate?
But, yes, update your atmosphere and hekate configs

**Comment by Masamune3210** [comment]
Why would they say sept logo if they were referring to anything other than the big logo screen that says sept
