### ISSUE TITLE
Daybreak does not run on atmosphere 1.2.2

### ISSUE THREAD

**Issue by 3c71** [Atmosphere-NX/Atmosphere#1690]
## Bug Report

Using atmosphere 1.2.2 latest release, I extract zip to root of SD (after removing existing atmosphere folders and files). Extracted sigpatch as well.

Now booted using fusee.bin from PC, opened hbmenu and opened daybreak, just to receive this error:

Outdated Atmosphere version
Daybreak requires Atmosphere 0.14.0 or later

What does that mean and how can I avoid this error?

I tried booting with SX dongle to no avail. I'm not using hekate or anything but Atmopshere without any further changes, appart from DNS and using emunand.

Firmware version is 12.0.2|AMS 1.2.2|E. As it's not working with Atmosphere standalone (booting fusee.bin from PC), I decided to install hekate and try with Atmo EMU and Atmo Vanilla as configured below, but didn't get any better :(

Here is the configs for Atmo(s):

[Atmo EMU]
fss0=atmosphere/package3
emummcforce=1

[Atmo Vanilla]
fss0=atmosphere/package3
kip1=atmosphere/kip_patches/fs_patches/*
kip1=atmosphere/kip_patches/loader_patches/*
emummcforce=1

Any help would be much appreciated.

**Comment by SciresM** [comment]
This has been reported a few times in the past.

I would recommend deleting your atmosphere directory, and testing in a freshly extracted latest-release-zip extract with no addons whatsoever. This has resolved it in the past.

Message indicates that daybreak couldn't get version config, which suggests something very wrong.

**Comment by 3c71** [comment]
I already tried that. FWIW I own a second switch which use another SD containing a copy of the same extracted latest-release and it works perfectly. That switch is running firmware 13.0.0... Not sure what to do with all that :(

**Comment by Masamune3210** [comment]
Try formatting your sd card as well just to make sure nothing fishy with the filesystem is happening. Also, no sigpatches
