### ISSUE TITLE
"A fatal error occurred when running Atmosphére" happened while trying to start up SSBU

### ISSUE THREAD

**Issue by Littlebigdwolf** [Atmosphere-NX/Atmosphere#1695]
A fatal error occurred when running Atmosphére
Program ID: 010041544d53000
Error Desc: std::abort() called (0xffe)

Report saved to /atmosphere/fatal_errors/report_000000003ce03683
Press POWER to reboot.

Above is the error message that pops up anytime I try to start up smash with mods. I've deleted the atmosphere and switch folders as well as the hbmenu.nro and put them back in before. Any solutions?

**Comment by takoyaki99** [comment]
Update ARCropolis and Skyline please!!
