### ISSUE TITLE
Error Code: 2002-3502 (0x1b5c02) Program 0100000000001000

### ISSUE THREAD

**Issue by LukeC17** [Atmosphere-NX/Atmosphere#1702]
### What's the issue you encountered?
[Describe the issue in detail and what you were doing beforehand]
 My friend powered off my console entirely (hold power, select power off). I forgot to tell him not to. </br>

[Did you make any changes related to Atmosphere itself?]
No, emmunand I'm pretty sure my emmunand is 12.0.3 and so is sysnand </br>

### How can the issue be reproduced?

</br>
 Boot into RCM, inject fusee primary. I tried booting with hekate aswell to get into atmosphere (1.2.4 btw) and same thing. It boots all the way through the atmosphere logos to the switch logo which goes away, and just as you would think the home screen would appear, it crashes.</br>

### System Firmware Version

</br>
12.0.3 SysNand, 12.0.3 EmuNand </br>
</br>
</br>

### Environment?

I was using atmosphere fusee primary, I tried booting with hekate as well, still not working.

### Additional context?

- Additional info about your environment:
I tried TegraExplorer and it seems to be able to open EMMC and EMUMMC folders. I feel like it is corrupted still somehow, but I don't know how to figure that out. I would at least like to get my saves back.

**Comment by LukeC17** [comment]
![20211107_002201](https://user-images.githubusercontent.com/93852045/140632253-71da3ca3-445d-4951-9835-ce9a9ac6d8cf.jpg)

**Comment by masagrator** [comment]
This is qlaunch titleid. You don't have any theme installed or qlaunch replacement like uLaunch?

**Comment by SciresM** [comment]
2002-3502 is fs::ResultPortMmcNotActivated().

Sounds to me more like this guy's emummc is fucked, than anything. 

Sounds like SD corruption to me, I'm going to close this as not an atmosphere issue, I recommend re-formatting your SD as FAT32 and re-creating your emummc.

**Comment by LukeC17** [comment]
> 2002-3502 is fs::ResultPortMmcNotActivated().
> 
> Sounds to me more like this guy's emummc is fucked, than anything.
> 
> Sounds like SD corruption to me, I'm going to close this as not an atmosphere issue, I recommend re-formatting your SD as FAT32 and re-creating your emummc.

My SD was FAT32, but yeah, I've been reading that re-creating emummc is what I have to do. Is there any way to get my saves back before I do this?

**Comment by Masamune3210** [comment]
Can extract them manually on a PC but that's out of scope for this issue
