### ISSUE TITLE
Controllers won’t stay connected

### ISSUE THREAD

**Issue by Calisto02** [Atmosphere-NX/Atmosphere#1703]
Ever since updating to the latest firmware and atmosphere version my controller won’t stay connected.

This started for me on atmosphere 1.2.1 and onwards, my controllers disconnect in handheld and wireless. I’ve tried all of my 3 pairs of joy-cons (two were working fine before, I bought another pair to test) which were all working fine before I updated. I even tried factory resetting my switch and reinstalling atmosphere from scratch and that hasn’t fixed it. Before testing everything I only had 2 pairs of joycons, originally I thought it was the controllers so I went out and bought a new pair, and they do the same thing.

**Comment by SciresM** [comment]
1) You did not use the issue templates, re-open using them if you want this issue to be handled properly.

2) Make sure you don't have custom system modules which might be interfering, removing those might solve the problem without having to go through the issue process.
