### ISSUE TITLE
Sys-tune crash: error code 2168-0002 (0x4a8)

### ISSUE THREAD

**Issue by EventualLake8** [Atmosphere-NX/Atmosphere#1706]
When I try to play newly downloaded music onto sys tune and play them, my switch either ignores it or crashes. I have been trying to fix it for over a week and nothing has worked. Please let me know how to fix this.

![IMG_0182](https://user-images.githubusercontent.com/94020493/141016597-ea31d8fc-e818-4dc7-9944-08a89dfbe484.jpg)

**Comment by SciresM** [comment]
....contact the developer of sys-tune? Not an atmosphere issue.

**Comment by NaturalHarmonia** [comment]
This happens with me as well when I use cheat codes in Pokemon Brilliant Diamond.
