### ISSUE TITLE
panic occurred while running atmosphere

### ISSUE THREAD

**Issue by butawsky** [Atmosphere-NX/Atmosphere#1707]
### What's the issue you encountered?

panic occured while running atmosphere..

### How can the issue be reproduced?

i dont know just randomly

### Crash Report

https://drive.google.com/file/d/1FH45Al7q5FI2hjFy44KcKGwKxvh19To6/view

### System Firmware Version

13.1.0

### Environment?

i use hekate 5.6.5
ams 1.2.4
 
- Homebrew software installed
sys-clk
jksv
hb appstore
ftpd
nxshell
nxtheme installer
themezernx

- EmuMMC or SysNAND:

emummc - partition base

**Comment by Masamune3210** [comment]
Please go back and fill out the issue template instead of just deleting it

**Comment by butawsky** [comment]
> Please go back and fill out the issue template instead of just deleting it

done and im sorry for my mistake

**Comment by Masamune3210** [comment]
Thank you

**Comment by SciresM** [comment]
Looks like something killed the FS session being used for layeredfs mid-execution...I am just going to close this, as the most likely candidate is racey stuff that's not really fixable while doing mitm with no control over process termination.

If this triggers consistently, reach out to me on discord (`SciresM#0524`) and I'll poke at it.

Thank you for reporting!

**Comment by butawsky** [comment]
thankyou very much too for the answer...
