### ISSUE TITLE
Fatal crash

### ISSUE THREAD

**Issue by Arch9SK7** [Atmosphere-NX/Atmosphere#1712]
### What's the issue you encountered?

Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

Press POWER to reboot.

[ attempting to boot atmosphere in any capacity from hekate on my switch always will receivethe aforementioned fatal error.]</br>
[ Did you make any changes related to Atmosphère itself?
No. ]</br>
[ N/A ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ launch Atmosphere from hekate launch menu.]</br>

### Crash Report

[ N/A ]</br>
[ sorry gist doesnt let me upload an atmos report 
https://www.dropbox.com/s/mjr9g4awkk3yj43/report_00000000082d1980.bin?dl=0 ]</br>
[ N/A ]</br>

### System Firmware Version

13.1.0</br>
[ Mariko Hoag ]</br>
[ N/A]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 
- Official release or unofficial build: 
  - [ 5.6.5 official build, Atmosphere 1.2.4 latest Fusee]
  - [ N/A] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: [ Atmosphère defaults]
- EmuMMC or SysNAND: Both
  - [ File based but also attempted with it completely wiped]

### Additional context?

- Additional info about your environment:
- [ N/A ]

**Comment by SciresM** [comment]
Your system_settings.ini is in invalid format, fix it up and you'll be fine.

**Comment by Arch9SK7** [comment]
Thank you :)
