### ISSUE TITLE
Panic occured when I try to boot Atmosphere after downloading BDSP

### ISSUE THREAD

**Issue by MewtwoFanz** [Atmosphere-NX/Atmosphere#1713]
## Bug Report
N/A

### What's the issue you encountered?

I got brilliant diamond and shining pearl from gamestop and started playing them
after that, atmospere stopped booting. it always panics when trying to boot

I tried to edit some of the config files
I removed the ; 's from the system settings config files

### How can the issue be reproduced?

just boot into amosphere after installing updates and playing bdsp.

### Crash Report
I couldn't find one

### System Firmware Version

13.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: Official release version 1.2.4
- Do you have additional kips or sysmodules you're loading: yes
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND: SysNAND

**Comment by SciresM** [comment]
If you're getting crashes, reports will be generated. Post screenshots and upload the reports.

**Comment by MewtwoFanz** [comment]
[https://drive.google.com/file/d/1sx_ZcdbeZuz7tqxO1LRxWOIxsEJANvOu/view?usp=sharing](url)

I posted the report file here

**Comment by MewtwoFanz** [comment]
I'll get a screenshot in a few minutes

**Comment by MewtwoFanz** [comment]
[https://drive.google.com/file/d/1dFiHdF8Q8HX5Qh-SBXInhgiE6930cuiW/view?usp=sharing](url)

here's my screenshot of what i get when i try booting into atmosphere

**Comment by MewtwoFanz** [comment]
Are these sufficient enough to see what's going on?

**Comment by MewtwoFanz** [comment]
https://drive.google.com/file/d/1dFiHdF8Q8HX5Qh-SBXInhgiE6930cuiW/view?usp=sharing

https://drive.google.com/file/d/1sx_ZcdbeZuz7tqxO1LRxWOIxsEJANvOu/view?usp=sharing

Just copy these links into your browser, that's easier for me to do

**Comment by Masamune3210** [comment]
You can paste pictures directly into this issue, instead of uploading them to drive

**Comment by esppc** [comment]
I'm 99% sure that this is the result of a badly configured system_settings.ini

Configure it properly or just grab a fresh one from the samples

**Comment by Yooooomi** [comment]
I'm having the exact same issue as the screenshot posted

**Comment by cloud679** [comment]
why did you guys have to make a newer version of Atmosphere for

it broke my modded nintendo switch, when you guys released this newer version, the older version was not broken by any chance

**Comment by cloud679** [comment]
why did you guys have to make a newer version of Atmosphere for

it broke my modded nintendo switch, when you guys released this newer version, the older version was not broken by any chance

**Comment by cloud645** [comment]
nice try blocking me it won't work

**Comment by cloud453** [comment]
I can do this forever

**Comment by Yooooomi** [comment]
[report_00000000069414d8.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/7576247/report_00000000069414d8.bin.zip)
Here is a report of the crash

**Comment by SciresM** [comment]
Your system_settings.ini is in invalid format. Fix it up and you'll be fine @MewtwoFanz.
