### ISSUE TITLE
Ring Fit Adventure crashed while entering settings of the game

### ISSUE THREAD

**Issue by daniperez95** [Atmosphere-NX/Atmosphere#1719]
Ring Fit Adventure crashed while entering settings of the game.

Error Code: 2162-0002 (0x4a2)
Program: 010000000000100F
Firmware: 12.0.3 (Atmosphere 1.2.4-master-e256261b8)

Game: Ring Fit Adventure (1.2.0)

Other games work fine for this console, even this game if you dont enter in settings.

**Comment by zemixe** [comment]
Why did you delete the issues template?

**Comment by SciresM** [comment]
Reopen using issue templates.

**Comment by daniperez95** [comment]
Sorry, will reopen with template.
