### ISSUE TITLE
1) Piracy/signature patches not supported.

### ISSUE THREAD

**Issue by Anakin072** [Atmosphere-NX/Atmosphere#1730]
1) Piracy/signature patches not supported.
2) 2345-0007 from hbloader means sd card corruption, not an atmosphere issue.

_Originally posted by @SciresM in https://github.com/Atmosphere-NX/Atmosphere/issues/1729#issuecomment-985250726_

So how do I fix this? Why is the issue marked as "resolved," after being accused of piracy. I just want my switch to work.

**Comment by SciresM** [comment]
1) you didn't use the issue templates
2) seek further support in a discord server like nintendo-homebrew. This issue tracker is for bugs, not for support.
