### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by HumanCentiped** [Atmosphere-NX/Atmosphere#1735]
My problem is simple. I updated everything for the CFW to work (hekate and atmosphere and even Tegra to be precise) but when I try so launch atmosphere, the logo briefely appear, then an atmosphere loading screen apprear and disapear. After that my switch is on, I am sure of it because it is detected when plugged to my pc and I can turn it off while on that state but the screen just remains black and no sound comes out. Please help me

Oh, and I tried to join the discord to explain my problem there rather ythan on github but I can't figure out what I am supposed to do to access all the channels

**Comment by SciresM** [comment]
Re-open using the issue templates or try a different discord.
