### ISSUE TITLE
A fatal error occured when running atmosphere

### ISSUE THREAD

**Issue by Percyfolio** [Atmosphere-NX/Atmosphere#1739]
### What's the issue you encountered?
i updated atmosphere to 1.2.5 and everything worked fine but then i updated the console to 13.2.0 and now i can't load to RCM. 

### How can the issue be reproduced?

just by booting in RCM

### Crash Report

the program id is: 010000000000bd00
errordesc: std:: abort () called (0xffe)

### System Firmware Version

13.2.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusee
- Official release or unofficial build: official release 1.2.5
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: overlays, amiigo, appstore, awoo-installer, jksv, melonds, retroarch, mtp server, tinfoil, ftpd
- EmuMMC or SysNAND:
  - emummc

### Additional context?

- Additional info about your environment:
I tried to use Emmcchaccgen but didn't change anything.

**Comment by Masamune3210** [comment]
Go back and actually fill out the issue template

**Comment by Percyfolio** [comment]
yes sorry, missclicked

**Comment by Percyfolio** [comment]
[crash report.zip](https://github.com/Atmosphere-NX/Atmosphere/files/7668841/crash.report.zip)

**Comment by Masamune3210** [comment]
Thank you

**Comment by Percyfolio** [comment]
found the issue, sorry for your time

**Comment by danistl** [comment]
> 

I have the same error.
How did you fix it?
