### ISSUE TITLE
Twitch app

### ISSUE THREAD

**Issue by cherrymx89** [Atmosphere-NX/Atmosphere#1741]
Good, I report a bug with Twitch app v1, I want to log in but it crashes when being able to link with my profile

error code: 2162-0002 (0x4a2)
FW 13.2.0
Atmosphere 1.2.5-master-1019bc54e

please :)

[01639203087_010000000000100a.log](https://github.com/Atmosphere-NX/Atmosphere/files/7696552/01639203087_010000000000100a.log)

**Comment by masagrator** [comment]
you didn't use issue template

**Comment by SciresM** [comment]
Reopen using the issue templates.
