### ISSUE TITLE
Fusee-primary.bin won't load

### ISSUE THREAD

**Issue by zhaq15** [Atmosphere-NX/Atmosphere#1752]
When I am trying to load Fusee-primary.bin it is going to a black screen and saying " [ERROR] fatal error: unable to identify pagage1 Press Power to reboot". I uploaded Atmosphere and had the new fusee.bin on my desktop but its still not working.

**Comment by Aura314** [comment]
Please use the issue templates and fusee-primary is not longer work please update your atmospehre and your payload. Atmospehre 1.2.5 is fine!

**Comment by SciresM** [comment]
You didn't use the issue templates, and fusee-primary doesn't exist any more. Please read the release notes and use fusee.bin.
