### ISSUE TITLE
Fatal error ocurred when running Atmosphère PROGRAM ID: 010041544d530000

### ISSUE THREAD

**Issue by costelabr17** [Atmosphere-NX/Atmosphere#1755]
PROGRAM ID: 010041544d530000
Error Desc: std:: abort() called (0xffe)

report error : https://www.mediafire.com/file/mtr0ucs3c65xjfw/report_00000000038e588e.bin/file

atmosphère 1.2.5
Fw 13.2.0

**Comment by Masamune3210** [comment]
Please go back and fill out the issue template, you wont get help without it filled out

**Comment by SciresM** [comment]
re-open using the issue templates.
