### ISSUE TITLE
A fatal error occurred when running Atmosphere

### ISSUE THREAD

**Issue by derdiedustin** [Atmosphere-NX/Atmosphere#1756]
I bought an already hacked switch and i wanted to update it to the newest version. So I followed this guys Youtube tutorial and now I have this problem.
A fatal error occurred when running Atmosphere.
Program ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

Failed to save report to the sd card! (00000202)
The atmosphere directory may improperly have archive bits set.
Please try running an archive bit fixer tool (for example, the one in Hekate).

Press POWER to reboot.

Im new to this and i have no idea what to do.. Can someone please help me? :)

https://www.youtube.com/watch?v=ToMub5ZugPo&t=28s this is the youtube guide i followed

**Comment by SciresM** [comment]
You did not use the issue templates.

Also, this issue tracker is for bugs, not for support. Seek support on discord.
