### ISSUE TITLE
Crash Atmosphere

### ISSUE THREAD

**Issue by Darkdragon20101** [Atmosphere-NX/Atmosphere#1758]
### What's the issue you encountered?

Error 0x4A2 (2162-0002) atmosphere crashed and want to reboot the console

I didn't make changes to Atmosphere, i updated it and execute with Retroreloaded Pro.

### How can the issue be reproduced?

Ror recreating my issue when i open smash ultimate and comes out a pop-up and i press continue, i have this error, same with super mario odyssey in the guide and controls.

### Crash Report

https://gist.github.com/Darkdragon20101/ce7440c700a918f8a3ae9670712e5f4c

### System Firmware Version

13.2.0

### Environment?

- Bootloader: Retroreloader Pro
- Official release or unofficial build: 
  - Atmosphère 1.2.5-master-1019bc54e
- Do you have additional kips or sysmodules you're loading: I think not
- Homebrew software installed: Goldleaf, Awoo installer, Tinfoil
- EmuMMC or SysNAND:
  - I am not using EmuMMC

### Additional context?

- Additional info about your environment:
- Removing sysmodules doesn't resolve the issue

**Comment by SciresM** [comment]
Yeah, this is an issue with the mods/etc you have installed, and not a fundamental atmosphere issue.

Seek support on discord, this issue tracker is for bugs.
