### ISSUE TITLE
Fatal error to boot atmosphere 1.2.5  fw 13.02 

### ISSUE THREAD

**Issue by Lordloco23** [Atmosphere-NX/Atmosphere#1761]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

X.X.X</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND:
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]
![IMG_20220107_123243](https://user-images.githubusercontent.com/97290671/149288627-9d622dba-9427-43c0-b92c-3bed16c6f37b.jpg)

**Comment by Masamune3210** [comment]
Upload the issue report, cant do anything without it

**Comment by Lordloco23** [comment]
![16420999697887828165770942119740](https://user-images.githubusercontent.com/97290671/149391600-653c480b-427c-4902-aeb6-6c0f35522ed8.jpg)

**Comment by SciresM** [comment]
You need to actually upload the files. Also, you didn't fill out most of the details in the issue template.

**Comment by Lordloco23** [comment]
So I downloaded the latest atmospere 1.2.5 file from github along with the signature patches and the fusse.bin The nintedo switch has the latest fw 13.02 installed. Use tegrarcm 2.6 with the Windows 10 PC, each time also the appropriate fusse.bin for atmospere.

**Comment by Masamune3210** [comment]
Piracy is not supported
