### ISSUE TITLE
Fusee Payload competability on spacecraft-nx modchip

### ISSUE THREAD

**Issue by carcaschoi** [Atmosphere-NX/Atmosphere#1763]
### What's the issue you encountered?
Fusee payload cannot run on mariko modchip directly unless I remove the sd card once and play the spacecraft nx game before I turn on the switch each time.
(No problem with Hekate payload)

### How can the issue be reproduced?
1. Flash the gateway modchip to spacecraftnx v0.2.0
2. Download official atmosphere v1.2.5 fusee payload from releases pages.
3. Rename fusee.bin to payload.bin and place it to the root of the sd card
4. Turn on your switch. You will see a black screen

How can I solve the problem
1. Remove sd card from switch
2. turn on the switch without sd card 
3. Play the full game (You cannot force shutdown the switch)
4. insert back your sd card into the switch and turn it on
5. It should launch into atmosphere

I need to repeat these action for EACH TIME if I direct load the fusee payload :(

### Crash Report
NA

### System Firmware Version
It occurs before I launch into the system

13.2.0|AMS 1.2.5|S

### Environment?
Mariko (Iowa) switch with sx core installed (I have already flashed the modchip to spacecraftnx)
Fat32 sd card 
Sandisk sd card
The solder points do not have any problem.

### Additional context?
1. No problem with hekate payload
2. I still can chainload fusee payload in hekate menu
3. No problem with my non-flashed gateway modchip with sx gear

**Comment by SciresM** [comment]
Correct. Chainload it via hekate for the time being.
