### ISSUE TITLE
Can't wirelessly connect any controller

### ISSUE THREAD

**Issue by MilanCavia** [Atmosphere-NX/Atmosphere#1764]
## Bug Report

Bug related to connectivity issues

### What's the issue you encountered?

When I unrail my joycons or unplug any controller it doesn't reconnect

### How can the issue be reproduced?

Had this problem since I think 13.0.0 maybe 12.1.0 now on 13.2.0 with atmosphere 1.2.5 and a normal pair of first party joycons or a 8bitdo pro2 controller

### Crash Report

No crash

### System Firmware Version

13.2.0 emunand, atmosphere 1.2.5

### Environment?

I use an official release of fusee (latest) 
I have tinfoil, daybreak, mission controll, NXThemes (but no theme active atm)
I am using EmuNand I don't know the difference between file and partition based but my sd card has two partitions so I guess partition based

**Comment by MilanCavia** [comment]
sorry I accidentally hitted enter while writing so that's why I edited the comment

**Comment by fincs** [comment]
>tinfoil

Piracy is not supported.
