### ISSUE TITLE
Clearing Play Activity

### ISSUE THREAD

**Issue by TheExpertNoob** [Atmosphere-NX/Atmosphere#1766]
### What feature are you suggesting?
Clear Play Activity

#### Overview:
Clear Play Activity as User Settings -> Play Activity Settings fails to load when nin is blocked with DNSmitm.

#### Smaller Details: 
Unsure of what requests are made to nin servers when that is selected, could be falisified with an always-return-required to allow clearing of play history or a feature that just doesn't log play history (play history writes to null)

#### Nature of Request:  
Useful feature for hiding things from nin and friends.

### What component do you feel this would best fit within?
Probably a Troposphere component.

### Why would this feature be useful?
Girlfriend/family/kids (and online friends) dont need to know what... games... Ive been playing if they happen to pick up my switch or browse my profile after going online to update games. It would be nice to clear these before going online to update. (Naughty games specially. People need not know my business. )

**Comment by SciresM** [comment]
Write a homebrew to do this, I don't see any reason for this to be an ams thing.
