### ISSUE TITLE
Splash.bin modification

### ISSUE THREAD

**Issue by Claod44** [Atmosphere-NX/Atmosphere#1768]
Hello, can you provide a way to add, delete and constomize splash.bin images please ?

**Comment by SciresM** [comment]
1) You didn't use the issue templates
2) https://github.com/Atmosphere-NX/Atmosphere/blob/master/utilities/insert_splash_screen.py

**Comment by Claod44** [comment]
Well We can insert, but not delete in case we want to change or simply remove an image ^^'
