### ISSUE TITLE
BOTW Not working, Latest atmosphere, Latest hekate with SigPatches updated

### ISSUE THREAD

**Issue by Claod44** [Atmosphere-NX/Atmosphere#1770]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

</br>CAUTION : THIS IS NOT PIRACY I OWN THE GAME AND PLAYED IT WITH THE CARDRIDGE </br>

### What's the issue you encountered?

I played BOTW with the cardridge, and I want to play the game without this little plastic part. Everything is up to date, Atmosphere, Hekate, Sigpatches for both.</br>
My guess : It can be related to the Nintendo/Contents/registered folder, or a ticket conflict, Or something to do with the cloud save / nintendo account ?</br>
The main difference  is the format, I just wanted to play it as a digital version from now.</br>

### How can the issue be reproduced?

[</br>
Well I'll not tell what software is used to install the game, its update, and DLCs... Tell me afterward if I can and if you need to know.</br>

### Crash Report

No Crash report, the game tells "Software couldn't start, Try again from home menu" something like that when I translate it in english.</br>

### System Firmware Version

13.2.0</br>
</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- HEKATE 5.7.0
- Official release or unofficial build:  
- Official
- Do you have additional kips or sysmodules you're loading:
- I don't think
- Homebrew software installed: [ * ]
- Ask because I don't want my issue to be closed
- EmuMMC or SysNAND:
- EmuNand (partition if I remember)

### Additional context?

- Additional info about your environment:
I wish to know if it's happening to me only on this firmware, with atmosphere and hekate and the latest sigpatches ...

Thank you for you help

**Comment by fincs** [comment]
> sigpatches

Piracy is not supported.
