### ISSUE TITLE
issue with botw

### ISSUE THREAD

**Issue by Icyy1** [Atmosphere-NX/Atmosphere#1773]
[01643771038_0100000000001000.log](https://github.com/Atmosphere-NX/Atmosphere/files/7983422/01643771038_0100000000001000.log)
 happens whenever I look over a big area or a area with a lot of particles.

**Comment by Icyy1** [comment]
That's the only crash report. every other time it has frozen then turned off.

**Comment by Masamune3210** [comment]
Considering how popular that game is, im willing to bet this isn't a atmos issue. Also, please go back and actually fill out the issue template

**Comment by SciresM** [comment]
Reopen with the issue template filled out.
