### ISSUE TITLE
Downgrading from 13.X to 12.X using daybreak stuck on Switch logo

### ISSUE THREAD

**Issue by Zontex** [Atmosphere-NX/Atmosphere#1775]
# Bug Report

Downgrading with daybreak to version 13.X on EMUMMC stuck on Switch logo and can't boot after reboot

## What's the issue you encountered?

My switch was on version 12.X and later upgraded to 13.X and want to downgrade back as I found it buggy, I downloaded the firmware online and extracted it into firmware/ directly on the SD card, then loaded daybreak which verified it and seems like installed successfully. once installation is complete, daybreak will ask if to reboot or shutdown, neither of these options will lead to the same result. once reboot/shutdown and load the EMUMMC again, it will be stuck on the switch logo and will require me to delete and restore from OFW again.

I tried other versions of firmware, none of them work. I encounter the same frozen switch logo on any version I'm trying to go back to.

## How can the issue be reproduced?
1. make a clean EMUMMC on file
2. download the firmware version to downgrade to
3. put firmware into firmware/ directory on SD card
4. load daybreak and downgrade atmosphere EMUMMC

# Crash Report
N/A<br/>
The system doesn't crash it's just frozen on the switch logo.

## System Firmware Version
13.2.1

## Environment?
What bootloader (fusèe, hekate, etc) was Atmosphère launched by:

- Official release
      - Official release version: latest
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: daybreak
- EmuMMC or SysNAND: EmuMMC file-based.

## Additional context?
I found 13.X buggy with the right controller being disconnected in the middle of nowhere issue, when I had 12.X it didn't happen, through downgrading back will solve the issue, I didn't keep an EMUMMC from the previous version so I can't go bacl.

**Comment by masagrator** [comment]
```
download the firmware version to downgrade to
```
Piracy is not supported.
