### ISSUE TITLE
Atmosphere unresponsive and corrupting my SD Card

### ISSUE THREAD

**Issue by ShujaHaider-Dev** [Atmosphere-NX/Atmosphere#1777]
### What's the issue you encountered?

I was booting Atmosphere for the first time when it became unresponsive, it stays like that after 3 hours and does not persist on HoS (The default OS)
The SD card was corrupted after the issue

### How can the issue be reproduced?

Just boot up the switch in Hekate: Select Atmosphere

### Crash Report

The SD Card was corrupted so I can't get the crash reports

### System Firmware Version

1.2.6</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: 
  - Official release version 1.2.6
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ X ]
- EmuMMC or SysNAND: EmuMMC
  - File Based

### Additional context?

- Additional info about your environment: Nintendo Switch V1, Sandisk Micro SDXC 128 GB
- [ Any other information relevant to your issue. ]

The SD Card was corrupted by Atmosphere.
This does not happen on the default OS

**Comment by SciresM** [comment]
Sounds like an issue with your SD card, not with atmosphere. Seek support on discord to try to figure out if this is really an ams somehow, but I doubt it.
