### ISSUE TITLE
Unable to Launch Atmosphere After Following CFW Guide

### ISSUE THREAD

**Issue by GogaTheAcute** [Atmosphere-NX/Atmosphere#1779]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>

just been following the github guide on CFW for the Swtich. Everything had been working until the point where it asked me to launch Atmosphere. When I tried toLaunch it I saw the "A" logo popup for a few seconds before the screen went black and I got the  message in yellow saying:
"Panic Occurred while running atmosphere

Title ID: 010041544d530000
Error: std: :abort (0xFFE)

Report saved to /atmosphere/fatal_errors/report_054fbde6.bin

Press POWER to continue."

[ Did you make any changes related to Atmosphère itself? ]</br>

no

[ If so, make sure to include details relating to what exactly you changed. ]</br>

N/A

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

Follow the guide at:
https://nh-server.github.io/switch-guide/user_guide/emummc/making_emummc/

using all latest releases, try to launch Atmosphere when the guide tells you to.

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>
[report_06478bcf.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8057009/report_06478bcf.bin.zip)

### System Firmware Version

10.2.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
hekate_ctcaer_5.7.0_Nyx_1.2.0

- Official release or unofficial build: 
  - [ Official release version x.x.x (or) unofficial build ]
 atmosphere-1.2.6-master-173d5c2d3+hbl-2.4.1+hbmenu-3.5.0

- Do you have additional kips or sysmodules you're loading:
no

- Homebrew software installed: [ * ]
none yet

- EmuMMC or SysNAND:
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]
 EmuMMC raw particion based as per guide

### Additional context?

- Additional info about your environment:
N/A

[report_06478bcf.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8057060/report_06478bcf.bin.zip)

**Comment by SciresM** [comment]
1) run archive bit fixer in hekate, you use macOS which breaks stuff.
2) this is for bugs, not support -- please seek further support on discord.
