### ISSUE TITLE
Implement and add support for a gdbstub.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#178]

**Comment by miladddddd** [comment]
SciresMAN

**Comment by SciresM** [comment]
me took miladddddd, me too.

I mentioned on a stream recently I'm really blocked on cross-platform USB...

**Comment by MichiS97** [comment]
Is there any indication for an ETA on this? It's my personal most wanted feature 😄

**Comment by SciresM** [comment]
This still needs starlink to be complete and the stub needs improvements, but I'm closing it because we factually have a gdbstub that functions right now.
