### ISSUE TITLE
Add Achievement Support

### ISSUE THREAD

**Issue by david2278** [Atmosphere-NX/Atmosphere#1784]
#### Overview:
- Add a barebones achievements framework</br>

#### Smaller Details: 
- This would be a framework set up for other developers to come in and make achievements on a per-game basis</br>

#### Nature of Request:  
- Addition
  - Icon at the bottom of the home screen which opens the Achievements UI
  - A user interface for Achievements.
  - A hook system which watches for specific values in memory which when found would unlock an Achievement
  - Documentation for other developers to create achievements for Switch games
### What component do you feel this would best fit within?
Unknown, likely Troposphère

### Why would this feature be useful?
This would extend the enjoyment of our favorite Switch games</br>
This would build a community of developers around building achievements for Switch games</br>

**Comment by SciresM** [comment]
This is deeply out of scope for atmosphere.

**Comment by SciresM** [comment]
Feel free to make something like this, though!

**Comment by david2278** [comment]
Should this not exist at the OS level? Even if this was made as a pull request and merged into the project?

**Comment by SciresM** [comment]
@david2278 It's very, very out of scope for Atmosphere. I would not want to be responsible for maintaining something like that, personally -- the whole point of my reimplementation philosophy is to avoid having to maintain tons of patches for official binaries.

Atmosphere does give enough invasive control of the system for something like this to be made -- I see no reason for it to be integrated into Atmosphere, when such a system could instead be maintained by its creator.

**Comment by david2278** [comment]
Ok fair enough. Thanks.
