### ISSUE TITLE
Error on Atmosphere. COde: 2162-0002

### ISSUE THREAD

**Issue by Sewshi** [Atmosphere-NX/Atmosphere#1785]
Another person has had this same problem and the solution for them was delete a folder. ( /atmosphere/contents/0100000000001000) I did that but the problem still happens. I keep rebooting payload but it still happens. This happened after I tried to apply a modpack to super smash bros ultimate. This error appears when I open any game

**Comment by SciresM** [comment]
You did not use the issue templates. Reopen using them.
