### ISSUE TITLE
Switch Won't Boot Into Atmosphere or Hekate after OFW update

### ISSUE THREAD

**Issue by akarys47** [Atmosphere-NX/Atmosphere#1794]
What's the issue you encountered?

I've installed both hekate version 5.7.0 and Atmosphere version 1.2.6, after that I updated my OFW to 13.2.1. 
Now my Switch won't boot into Hekate or Atmosphere, running directly to OFW (even when I press vol- button to enter Hekate to change settings, nothing happens because Hekate won't load anymore). 

My NS is v2 Mariko with HWFLY modchip. 

How can the issue be reproduced?

After update to OFW 13.2.1.

Crash Report

N/A

System Firmware Version

13.2.1

**Comment by SciresM** [comment]
Re-open using the issue template actually filled out. Won't boot is not enough detail.
