### ISSUE TITLE
[Feature Request] automatically delete old erpt reports 

### ISSUE THREAD

**Issue by DraconicNEO** [Atmosphere-NX/Atmosphere#1795]
#### Overview:
 
Have Atmosphere delete erpt reports automatically after a certain amount has been reached in the folder to prevent crashing from too many erpt reports.
 
#### Smaller Details: 
- checking number of erpt reports
- Deleting old ones to prevent them from exceeding some amount i.e. 1024
 
#### Nature of Request:  
[ Remove all that do not apply to your request. ]
- Addition
- Change
 
 
### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
 
### Why would this feature be useful?
 
This feature addresses an issue where the erpt reports accumulate over time eventually exceeding the Switch's file limit and causing the error applet to crash. If this feature were implemented this crash could be avoided since old Erpt reports would be deleted and would never accumulate to the 16383 file limit.

**Comment by SciresM** [comment]
Unless a setting is switched away from default, erpt will now clean the report folder on boot if there are >= 1000 reports (or if reading the number of reports fails).

**Comment by ImanCol** [comment]
Or something better, disable creating logs, if the user is not reporting bugs. In addition, it will increase the life cycle of the MicroSD.

**Comment by Masamune3210** [comment]
Logs are on for a reason, issues don't always manifest before they become an imperative

**Comment by SciresM** [comment]
> Or something better, disable creating logs, if the user is not reporting bugs. In addition, it will increase the life cycle of the MicroSD.

I am not going to disable log creation.

**Comment by Masamune3210** [comment]
This will prevent the folder from growing past a certain point, and just because you arent getting full crashes doesn't mean errors arent happening. erpt isn't going to just spit out a log saying All is OK, if its making logs its for a reason

**Comment by ImanCol** [comment]
Well, hopefully that option to delete records when it exceeds a certain amount is added.

**Comment by Masamune3210** [comment]
The commit is already done, unless something changes its happening
![image](https://user-images.githubusercontent.com/1053504/159540068-421d4d9b-265c-48fd-ba4d-8453c94d2080.png)
