### ISSUE TITLE
Add symlink like redirection to existing file/folder in current RomFS, to LayeredFS

### ISSUE THREAD

**Issue by CaiMiao** [Atmosphere-NX/Atmosphere#1796]
#### Overview:
Enable users to redirect a file or folder, to any file/folder which already exists in the RomFS.

#### Smaller Details: 
- N/A atm

#### Nature of Request:  
- Addition
  - implement in-RomFS file redirection
  - add a dedicatd config file to control it
    - and if possible, can we also flag a file/folder in RomFS is deleted?

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>

### Why would this feature be useful?
- for some games, like the Yu-Gi-Oh! Legacy of the Duelist, they censor the card illustration like they did in real life. Though we can simply uncensor it by replacing plain jpegs from Japanese card illustration folder inside RomFS, this method end up wasting your microSD card space if we have symlink to the specific folder.
  - And potentially for other games having regional difference or voiced tied to languages, we can undub them simply if they don't make it complicated, by just putting a symlink config which is easy to distribute.

**Comment by SciresM** [comment]
The switch filesystem has no conception of symlinks, nor do I find them a desirable addition.
