### ISSUE TITLE
After Updating to Atmosphere 1.2.6 Fatal Error occured and the exFat Partition gets destroyed

### ISSUE THREAD

**Issue by ferris1000** [Atmosphere-NX/Atmosphere#1798]
## Bug Report

A fatal error occurred when running Atmosphère.
Program ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

exFat Partition needs to be formated after this error occurred.

### What's the issue you encountered?

After Updating to Atmosphere 1.2.6 the Error occured and the exFat Partition gets destroyed.

### How can the issue be reproduced?

Format an SD Card to exFat and try to Boot Atmosphere,

### Crash Report

Due to corrupted Partition it's impossible to get a log File, 

Chkdsk /F fixes the SD Card, but no Log.

### System Firmware Version

13.2.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Trinket based Modchip
- Official release or unofficial build: amsPlus 1.2.6 (173d5c2d3)
- Do you have additional kips or sysmodules you're loading: No
- EmuMMC or SysNAND: SysNAND

### Additional context?

The Partition Corruption already happened to 2 Consoles from 2 Friends I helped to Update their Switch.
Only exFat is effected, reformatting to exFat repeats the same Issue. 

![47fbca44-1f35-46f9-a005-7dc433bd55dc](https://user-images.githubusercontent.com/39735251/159595025-eb6fd9e6-d99c-4fbd-b0ac-8a93ced6dee0.jpg)

**Comment by SciresM** [comment]
Yep. Don't use exFAT, it's a nintendo driver issue.

**Comment by SciresM** [comment]
Use FAT32.

**Comment by ferris1000** [comment]
I'm aware that exFat sucks on Nintendo Switch that's why I'm using Fat32 myself, but some other People who are not Technical are buying a Second microSD Card and doesn't Care as much and that's my we Found the Bug the Hard Way.

**Comment by SciresM** [comment]
I mean, that's irrelevant. There's nothing we can do about it except tell you to use fat32.

**Comment by ferris1000** [comment]
I already did, Atmosphere worked before with exFat, only since the latest Version this happened and I thought that might be new. Now I know better, thanks.
