### ISSUE TITLE
Create and fill out a GitHub Wiki for Atmosphere.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#180]

**Comment by TheFirstAv3nger** [comment]
I'd be glad to write that up for you guys.

**Comment by Resaec** [comment]
I'm not all too good at this, but [here is a basic one](https://github.com/Resaec/Atmosphere/wiki/).
I will extend it so there are as few red pages in the sidebar as possible.

It does not meet any expectations but it could give someone an idea how to start it off.

iirc there is no PR mechanic for wikis but there is ... .wiki.git

**Comment by Resaec** [comment]
Nice! I didn't know wiki is free to edit to everyone when not disabled manualy.
Still many things left to add.

**Comment by roblabla** [comment]
I really dislike the use of github wiki for this.

- Github wiki has no PR system.
- The contribution system is either "anyone can edit" or only contributors can, making collaboration with newcomers painful.
- It has no visible history accessible from github

I believe having the docs in a dedicated docs/ folder, with files in Markdown, to be a superior option.

**Comment by Resaec** [comment]
It has been a wish by the community since ages...

**Comment by noirscape** [comment]
@roblabla While your other points remain valid, the history of a wiki page _is_ accessible through GitHub.

https://github.com/Atmosphere-NX/Atmosphere/wiki/Home/_history

**Comment by HylianMedia** [comment]
@joelc608 and I created a first draft of the Wiki [here](https://github.com/joelc608/Atmosphere/tree/master/docs). We started with the basic wiki from @Resaec and built upon it, so huge thanks to him and everyone that helped us on the Discord!

**Comment by joelc608** [comment]
> 
> 
> @joelc608 and I created a first draft of the Wiki [here](https://github.com/joelc608/Atmosphere/tree/master/docs). We started with the basic wiki from @Resaec and built upon it, so huge thanks to him and everyone that helped us on the Discord!

I put in a pull request for this.

**Comment by Resaec** [comment]
Linking issue and PR #210

**Comment by hexkyz** [comment]
PR #210 has been merged and basic documentation is now available under the docs/ folder using the Markdown format.
