### ISSUE TITLE
1.3.0 + Sigpatches Error

### ISSUE THREAD

**Issue by XiNaru** [Atmosphere-NX/Atmosphere#1801]
Hey,

Pls update this quickly.
I Have installed the latest Atmosphere 1.3.0 + the latest sigpatches FOR Atmosphere 1.3.0 and use the latest fusee but....
![image](https://user-images.githubusercontent.com/29681441/159811561-d37a7a92-93e8-498b-90b4-e88ed279c039.png)

**Comment by Conan179** [comment]
try without sig patches. with pachtes, no support here.

**Comment by sudot0ph** [comment]
Delete MissionControl from /atmosphere/contents.

**Comment by SciresM** [comment]
PIracy is not supported.

**Comment by XiNaru** [comment]
i have now fully formated my sd card, now it works...
