### ISSUE TITLE
dosent boot

### ISSUE THREAD

**Issue by Tenacity2s** [Atmosphere-NX/Atmosphere#1804]
so basically i installed the pre release and when i try to boot fusee it shows the atmosphere logo then just shuts off

**Comment by SciresM** [comment]
1) you did not use the issue templates
2) Not enough information provided, likely something wrong with your setup. This is what the issue templates are for.

If true shutoff, you may just literally not have enough battery charge.

**Comment by Tenacity2s** [comment]
1. sorry ill use the issue templates but its not my battery because my switch is at like 80%
