### ISSUE TITLE
Game Backups failing to boot on 1.4.0

### ISSUE THREAD

**Issue by vitormmatos** [Atmosphere-NX/Atmosphere#1806]
Booted Armosphere from fusèe and tried running game Backups, that were working on previous versions of Atmpsphere, but now are failing to boot on 1.4.0
Tried reinstalling them and yet no success on booting.

Homebrews seem to work fine, tried Awoo-Instaler and it's working.

**Comment by SciresM** [comment]
Piracy is not supported.
