### ISSUE TITLE
Error Code 2105-0584

### ISSUE THREAD

**Issue by joacogaleano** [Atmosphere-NX/Atmosphere#1809]
I updated to 14.0.0 and this error appears when I boot with fusse from Tegra

![50A73996-4441-44F6-AD2E-FD754EF0C745](https://user-images.githubusercontent.com/99747963/160002292-e8263c6d-66b3-4e81-9ced-4ea85366b81f.jpeg)

**Comment by Garrappa** [comment]
Probably shouldn’t use pre release and better to wait for full release. Patience.

**Comment by joacogaleano** [comment]
> Probably shouldn’t use pre release and better to wait for full release. Patience.

Ok, I’ll wait, thanks

**Comment by SciresM** [comment]
This is a prodinfo corruption issue. Restore a valid backup.
