### ISSUE TITLE
Implement a framework for an AR Code/Gameshark analog.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#181]

**Comment by Paffo** [comment]
Sorry for useless comment, but an integrated cheat search engine will definitely make this the best for our switches

**Comment by thedax** [comment]
With the advent of dmnt:cht, would you say this goal has been met?

**Comment by Paffo** [comment]
Well, we still dont have Float and Double search, but yes, we can count this as solved.

**Comment by SciresM** [comment]
@thedax Yeah, this is pretty much closable. The Cheat VM ISA will be extended in the future with new shit as needed, and will be controllable from PC via ams.tma once the debugger is done.
