### ISSUE TITLE
Daybreak EmuMMC update Error 0x00007889

### ISSUE THREAD

**Issue by Kingslayer9988** [Atmosphere-NX/Atmosphere#1812]
Hello i encounterd an error when updating my EmuMMC to HOS 14.0.
I'am using: AMS 13.0 | Hekate 5.7.2 | TegraExplorer Second hotfix | 

I have updated my SysMMC fine to 14.0 then i dumped the firmware with Tegraexplorer - 0 errors.
After that i boot in EmuMMC HOS 13.2.1 | AMS 13 - install the update via daybreak it checks the file and says its good.
But after that the installer erros out with code 0x00007889.

![daybreak](https://user-images.githubusercontent.com/61237620/160106321-2858d21c-ef1a-43f3-8c9c-fd500eaac46d.jpg)

**Comment by SciresM** [comment]
re-open using the issue templates.
