### ISSUE TITLE
Support?

### ISSUE THREAD

**Issue by Goldenwolfz21** [Atmosphere-NX/Atmosphere#1817]
i put the files including hekate and the sigpatches to the root and used the hekate .bin to launch and its just showing a black screen

**Comment by masagrator** [comment]
Piracy is not supported.
Next time use issue template and write proper title

**Comment by pegast73** [comment]
> i put the files including hekate and the sigpatches to the root and used the hekate .bin to launch and its just showing a black screen

payload.bin
