### ISSUE TITLE
Clean up Fusee UI for 0.7 release.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#182]

**Comment by ThatNerdyPikachu** [comment]
@SciresM What exactly do you need to clean up in it? I'd be happy to help with cleaning it up!

**Comment by HylianMedia** [comment]
@SciresM @ThatNerdyPikachu You guys need any extra help with this? I'd be glad to lend a hand if needed.

**Comment by hexkyz** [comment]
Splash screen is now available as part of fusee. Please discuss here what other features/cleanup would be desirable for release.

**Comment by hexkyz** [comment]
Fusee UI's clean up has now been concluded.
