### ISSUE TITLE
std::abort() called (0ffe)

### ISSUE THREAD

**Issue by dodgypast** [Atmosphere-NX/Atmosphere#1820]
### What's the issue you encountered?

Booting Atmosphere crashes the switch with the error:
std::abort() called (0ffe)

### How can the issue be reproduced?

Mariko Switch with SX mod chip
Was at 13.2.1 HOS with 1.26 Atmospher updated as follows:
Hekate
Atmosphere
Get the latest fusee and put in your payloads directory
Sigpatches
Download 14.0
Install with daybreak

When I select fusee it shows the atmosphere splash screen, then the nintendo spash screen, then crashes.

### Crash Report

https://gist.github.com/dodgypast/726f48d029c6e1bd08cc6fbabe2fbe5e

### System Firmware Version

14.0.0

### Environment?
Hekate 5.7.2 used to load fussee.bin
SysNAND

**Comment by Masamune3210** [comment]
Piracy is not supported

**Comment by dodgypast** [comment]
I gotg rid of the contents folder and it fixed so my stupidy.

Apologies for wasting time.
