### ISSUE TITLE
crash on boot after pre-release update

### ISSUE THREAD

**Issue by Apep-the-snek** [Atmosphere-NX/Atmosphere#1821]
quick story: i accidentally updated hos to 14.0.0, then went and installed newest hekate and latest non-pre-release atmosphere, and got a yellow screen when loading firmware from hekate, tested sysmmc and stock multiple times, i figured i needed the pre-release, so i did:

Using atmosphere 1.3.0, latest hekate and hos 14.0.0, i booted sysmmc, and got an atmosphere error screen, error code: 2021-0003 ( 0x615); program: 0100000000001000; firmware: atmospere 1.3.0 master. i do not have any camera (no, i don't even have a smart phone atm), but i can say that the stuff under the line how it looks, pc says something; bactrace says something; X0 to X28 says nothing; fp, lr and sp says something; bt[00] to bt[17] says something.

### How can the issue be reproduced?

just do this, i do not know if it will happen this way, but i have done nothing wrong as far as i know, read the release notes and did what it said i should do

### Crash Report
about that, is there a log file on my switch somewhere so i don't have to write it all out?
### System Firmware Version

14.0.0
### Environment?

hekate official and latest
no additional sys modules, i don't know what kips is/are
- Homebrew software installed: a lot, nothing that has made it crash on boot ever before, just the usual suspects, like edizon se, aio updater (i have used it to update my system before, maybe that's an issue) and some open source games, and the mgba emulator, nxthemes installer but no themes installed atm, and some others i don't remember, very sure these don't cause any problem here, but who knows?
- EmuMMC or SysNAND: sysnand, no emummc installed

### Additional context?
hekate.ini is up to date.

**Comment by SciresM** [comment]
Remove custom sysmodules/custom theme.

You do in fact have them, it's what causes that.
