### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by jeikun1111** [Atmosphere-NX/Atmosphere#1824]
## Bug Report

Game Launching Bugs and controller disconnecting

### What's the issue you encountered?

-Fire emblem Three houses v.1.2.0 Stuck on black screen wont even budge the switch loading screen
-God eater 3 v.2.5.1 wont start comes with an error *Software was close because of an error occurred.*
-Xenoblade Chronicles 2 v.2.1.0 stuck on black screen then gets corrupted if you close the game then if you recheck there was no corrupted data.
-Controller Disconnects while playing .. maybe an hour or so rarely occurred.. no issues on my rails..

### How can the issue be reproduced?

Just by playing the game..

### Crash Report
n/a
### System Firmware Version

14.0.0</br>

### Environment?

Atmosphere v.1.3.0
Hekate Bootloader v.5.7.2

### Additional context?

had all these after the update to switch 14.0.0 and atmosphere 1.3.0

**Comment by SciresM** [comment]
You didn't properly fill out the issue template. Please actually provide all requested information.
