### ISSUE TITLE
Error Code: 2001-0123 (0xf601) When installing Atmosphere 1.3 for Switch Update 14.0 

### ISSUE THREAD

**Issue by JarlTheKing** [Atmosphere-NX/Atmosphere#1825]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

### What's the issue you encountered?

Since the Switch updated to 14.0, I needed the latest Atmosphere update (which at this time is 1.3). When installing the update I was given this as a result. I've tried to do some digging on this, seemed like it happed within the past couple years, but I'm still new to this stuff so I don't really know what to do, besides a friend trying to help me out.

![IMG_2807](https://user-images.githubusercontent.com/102709826/160965480-455bf8da-ce39-4358-8232-10cb5a000189.jpg)

### Crash Report

[01648689446_0100000000000081.log](https://github.com/Atmosphere-NX/Atmosphere/files/8385511/01648689446_0100000000000081.log)

### Environment?

-  Bootloader usedc (fusèe & hekate) was Atmosphère launched by:
- Official release 
- Homebrew software installed: [ * ]
- EmuMMC on SD Card

**Comment by SciresM** [comment]
Delete the custom system module. It probably needs to be updated.

**Comment by JarlTheKing** [comment]
> Delete the custom system module. It probably needs to be updated.

Where would I find that, and what would it be called?

**Comment by SciresM** [comment]
Delete the atmosphere/contents/0100000000000081/ folder you added.

**Comment by takoyaki99** [comment]
In the atmosphere/contents folder delete the one that says 010…..81, and you’ll be good! Make sure to check for updates to that title too, the sysmodule may have been updated for 14.0.

**Comment by ndeadly** [comment]
For the record, `0100000000000081` is nx-btred, which was rendered obsolete by the official bluetooth audio support introduced in 13.0.0. It is unlikely to receive further updates and shouldn't be used on firmwares other than 12.x.x.

**Comment by JarlTheKing** [comment]
Okay so I deleted the 0100000000000081 Folder, by mistake, without checking what was in the folder itself. Now I am left with this.

[01648770674_0100000000001000.log](https://github.com/Atmosphere-NX/Atmosphere/files/8393845/01648770674_0100000000001000.log)

![thumbnail_image0](https://user-images.githubusercontent.com/102709826/161173681-5066ef95-f23a-479d-9521-7532801e818b.jpg)

**Comment by takoyaki99** [comment]
Delete your custom theme using the same process at atmosphere/contents/010….0100.

**Comment by Masamune3210** [comment]
Honestly it's probably easier at this point and quicker to just put a clean install of Atmosphere on instead of playing whack-a-mole

**Comment by JarlTheKing** [comment]
Just started working, thanks everyone. You really help a brother out, glad you all know the ins & outs of this.
