### ISSUE TITLE
after update to 14.0.0 with atmosphere 1.3.0 rc can't boot

### ISSUE THREAD

**Issue by joebnb** [Atmosphere-NX/Atmosphere#1827]
![0094a859191a2f531d78d2c98c8e38b](https://user-images.githubusercontent.com/1646883/161200039-f0364629-5769-4c70-ad46-9ba5bb871271.jpg)

there is no nand backup,could give me some suggestion to solve this?

**Comment by Masamune3210** [comment]
Please go back and actually fill out the issue template
