### ISSUE TITLE
Labo VR app crashes on startup

### ISSUE THREAD

**Issue by bflat127** [Atmosphere-NX/Atmosphere#1829]
### What's the issue you encountered?

"Nintendo Labo Toy-Con 04: VR Kit" freezes on startup for ~20 seconds, then crashes.

### How can the issue be reproduced?

- Launch "Nintendo Labo Toy-Con 04: VR Kit" (cartridge)
- Observe Nintendo logo
- Observe solid black screen for ~20 seconds
- Observe crash screen

### Crash Report

[01648855765_0100165003504000.log](https://github.com/Atmosphere-NX/Atmosphere/files/8401388/01648855765_0100165003504000.log)

### System Firmware Version

14.0.0

### Environment?

- Fusee
- Official release (atmosphere-1.3.0-prerelease-b69fa1357+hbl-2.4.1+hbmenu-3.5.0.zip)
- No custom sysmodules
- No custom themes
- No ExeFS or LayeredFS patches
- Homebrew software installed: None (yet)
- SysNAND

### Additional context?

N/A

**Comment by SciresM** [comment]
Cool.
