### ISSUE TITLE
Daybreak crash

### ISSUE THREAD

**Issue by jlavoieqc** [Atmosphere-NX/Atmosphere#1830]
When I launch daybreak Atmosphere crashes.
Error code : 2144-0001 (0x290)
Program : 0100000000001000
Firmware : 14.0.0 (Atmosphère 1.3.0-master-b69fa1357)

**Comment by jlavoieqc** [comment]
![2022040216105100-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/97467718/161399637-03373e2e-2a6f-4dfc-9d33-e3009555d610.jpg)

**Comment by Masamune3210** [comment]
Go back and actually fill out the issue template please

**Comment by SciresM** [comment]
re-open using the issue templates.
