### ISSUE TITLE
Holding L while booting a game does not disable IPS Patches

### ISSUE THREAD

**Issue by Mars2032** [Atmosphere-NX/Atmosphere#1841]
### What's the issue you encountered?

While trying to boot a game that normally as mods installed via both the contents folder and exefs_patches folders, only the contents folders will be disabled. For games that use an IPS patch for external code, this causes the game to crash, as the external code portion in contents is not enabled, but the IPS patch still is. Manually renaming the IPS patch to be invalid fixes the crash.

### How can the issue be reproduced?

Install any mod for any game that has a .ips file and a file named subsdk1, and boot it while holding L. 

### Crash Report
[01649379419_0100000000010000.log](https://github.com/Atmosphere-NX/Atmosphere/files/8447112/01649379419_0100000000010000.log)

### System Firmware Version

13.2.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
  - Hekate
- Official release or unofficial build: 
  - 5.7.0
- Do you have additional kips or sysmodules you're loading:
  - N/A
- Homebrew software installed: 
  - Goldleaf v0.9
  - sys-ftpd-light
  - IPSWitch
- EmuMMC or SysNAND:
  - SysNAND

### Additional context?

- Additional info about your environment:
  - I mainly mod Super Mario Odyssey, so for some reason this could be game specific, but based on how the crash works, I do not think it is.

**Comment by SciresM** [comment]
"Use an ips patch for external code"...what?

**Comment by Mars2032** [comment]
> "Use an ips patch for external code"...what?

I may have just worded it poorly. What I mean is using ips patches to place branch instructions to the subsdk1 in the original code.

**Comment by SciresM** [comment]
That is...not really how stuff is designed to be used. I can think on it, there are some really big problems with keypress controlled patching though.

**Comment by yourboid** [comment]
![123](https://user-images.githubusercontent.com/105564423/168446071-5e7c4a92-4f72-461a-986f-932a34594802.jpg)

**Comment by ruje0504** [comment]
Therefore, this kind of IPS generated for mod should be done as little as possible, and it is more stable to directly modify exefs
