### ISSUE TITLE
Atmosphere 1.3.1 HOS 14.1.0 crash with tinfoil 14.0

### ISSUE THREAD

**Issue by sonyalc** [Atmosphere-NX/Atmosphere#1843]
## Bug Report

Since I update to ams 1.3.1 and hos firmware to 14.1.0 i get an error related to tinfoil. The issue only occurs when I open tinfoil whether I install content or not. 

### What's the issue you encountered?

When i launch tinfoil it open when i close i get an atmosphere crash or when try to install content i get an error "Failed to commit content records" . When i reboot all everything is back to normal but issue are  comes back as soon as I try to start tinfoil also sometimes I have an atmosphere crash or i can't access hb menu from photo album after i get this error. 

I've the problème on 2 unit who have exactly the same configuration, SD card tested and not corrupted (1Tb FAT32)

### How can the issue be reproduced?

Just open tinfoil and quit or open tinfoil and install content 

### Crash Report

(https://gist.github.com/sonyalc/cca09e09b1f258dee5c964a8f576a9f2)

### System Firmware Version

14.1.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 5.7.2
- Official release or unofficial build: 1.3.1|S
- Do you have additional kips or sysmodules you're loading: I don't Know
- Homebrew software installed: FTPD, JKSV, NX-Shell, NXThemes Installer, SwitchTime
- EmuMMC or SysNAND: SysNAND

### Additional context?

NO

**Comment by SciresM** [comment]
Piracy is not supported.
