### ISSUE TITLE
Chrono Cross crash

### ISSUE THREAD

**Issue by testergithuba** [Atmosphere-NX/Atmosphere#1848]
Hello I a new to bug report and github so sorry for post but I want to report issue
### How can the issue be reproduced?
I can't play chrono cross, after loading I encounter error 2162 and they say it's cfw issue, maybe it is

[ * ]</br>
Include a detailed step by step process for recreating your issue. ]</br>
Download any version of Chrono Cross

### Crash Report
]https://gist.github.com/testergithuba/c048eff6497a97dfd3dfa2e57578afa0
firmware
newest atmosphere, payload, and MissionControl
### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
You didn't fill out the issue template correctly. Re-open with the template actually filled out, including details on your custom sysmodules and ideally a screenshot of your atmosphere/contents folder.
