### ISSUE TITLE
Feature: Per-user LayeredFS

### ISSUE THREAD

**Issue by AnalogMan151** [Atmosphere-NX/Atmosphere#185]
Since the Switch is much more family oriented than individual oriented like the 3DS was, having mods be loaded based on profile played would be an appreciated feature. Something as simple as adding a username to the end of a title folder like so:

```
titles
├── 01007ef00011e000_User01
│   └── romfs
└── 01007ef00011e000_User02
    └── romfs
```

If a folder has no user name after it then the mod is loaded for all user accounts. This would allow one to add mods only for their own profile or add different mods based on who loads the title.

**Comment by Luro02** [comment]
this would cause problems, if someone has their name in for example kanji....so using (alternatively) the account ID should be an option too ?!

**Comment by griest024** [comment]
This would certainly be helpful but it wouldn't have to be implemented in CFW. You could accomplish essentially the same behavior with some good homebrew.

**Comment by CobaltTiger** [comment]
As I recall, there was a homebrew app on the 3DS that did exactly that, minus the multi-user thing. Conceptually, it's really similar, so I wonder if it couldn't just be ported?

**Comment by griest024** [comment]
It might work out fine for some minor content but for LFS files that change major things (i.e. the executable), I can't see how that could be dynamically injected and actually work as intended.

**Comment by AnalogMan151** [comment]
While a homebrew can certainly do this, it's outside the scope of this request. This is for benefitting the end users, especially those who are not familiar with homebrew. With the Switch being a household unit, there will be instances were the people playing it are not the person who hacked it and thus will not know to to first open a homebrew and adjust the installed mods. Having it built right into the CFW would be ideal for a non-technical person's standpoint. 

Plus, if this is implemented it would make creating a homebrew to manage per-user mods much easier.

**Comment by ThatNerdyPikachu** [comment]
I'll implement this, look out for a PR soon...

**Comment by ThatNerdyPikachu** [comment]
(only thing i may not be able to do is the part where one folder gets loaded always..)

**Comment by AnalogMan151** [comment]
For clarification, I didn't mean both a universal folder and also a user folder getting loaded, I mean, check to see if a user specific folder exists and load the romFS from that, if it doesn't, then check to see if a non-user specific folder exists, then load that. Kind of like a fall back.

**Comment by ThatNerdyPikachu** [comment]
@AnalogMan151 Oh, that's what I thought you meant initially. Thanks for the clarification!

I'll PR later today.

**Comment by SciresM** [comment]
This turns out to be basically not feasible due to a lack of good way to represent users inside filepaths (user names not unique, user ids inconvenient and unintuitive, special characters are a problem, etc)

**Comment by bakugo** [comment]
> user ids inconvenient and unintuitive  

How are user ids more inconvenient or unintuitive than title ids?

**Comment by SciresM** [comment]
@shchmue user IDs are actually 128 bits.

**Comment by AnalogMan151** [comment]
True. Unless we did something that like matching only the first 32 or 64 bits. It’s unlikely two accounts on one Switch would have similar enough IDs to have multiple matches.

**Comment by SciresM** [comment]
We're not using user-ids.

**Comment by SciresM** [comment]
@roblabla as mentioned, usernames are not unique

**Comment by roblabla** [comment]
Is that really a problem though? Transliterated names are not unique either. Worse-case scenarios, two users will share the same mod path. It won't cause crashes, but it might cause confusion.

**Comment by SciresM** [comment]
In addition, this creates a huge amount of cruft throughout codebase -- suddenly *all* of loader needs to run twice, checking both `exefs` and `exefs_<identifier>`, and code needs to be written to only run a second path after account has been initialized and can be connected to. It sounds super, super gross from a code maintenance perspective.

**Comment by AnalogMan151** [comment]
I understand. I only suggested it because the current approach is carried over from the 3DS which was a single user system and isn’t quite suited for the multi-user system of the Switch. It just feels odd to have a single-user solution on a multi-user platform. I’m sure it would have been more useful to have approached this from the beginning rather than adapting the current system.

**Comment by SciresM** [comment]
I mean I think fundamentally user-profile stuff is just extremely weird to integrate into loader/FS -- it requires talking to account, which is launched fairly late and itself heavily dependent on loader/FS...and the only way the active user gets set is when the profile selector runs, and the whole thing just gets messy.
