### ISSUE TITLE
Panic occurred when running Atmosphere (after updating to 14.1.0)

### ISSUE THREAD

**Issue by jimmyjohnjr1203** [Atmosphere-NX/Atmosphere#1853]
### What's the issue you encountered?

I updated firmware and Atmosphere as I always had by downloading and installing the most recent version of atmosphere and hekate (by dragging and dropping into the sd card), and then in sysmmc going to settings, system, update system, after which it downloads and successfully installs firmware 14.1.0. Then it reboots into hekate and when I try to boot into sysmmc, it says 

```
Panic occurred while running Atmosphere.

Title ID: 010000000000BD00
Error: std::abort (0xFFE)
```

### How can the issue be reproduced?

trying to boot atmosphere from hekate is all it takes (after updating to 14.1.0)

### Crash Report

from atmosphere/fatal_errors
[report_0acce1a0.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8500604/report_0acce1a0.zip)

### System Firmware Version

old: 13.2.1
new: 14.1.0

### Environment?

hekate 5.7.2
Atmosphere 1.3.1

### Additional context?

Also tried updating emummc (partition based) and had the same issue.
Tried fusee.bin to see if that helped, it did not
Atmosphere 1.3.1 was working fine before I tried updating the firmware.

**Comment by masagrator** [comment]
You didn't update MissionControl.
