### ISSUE TITLE
Games crashes after sometime in Atmosphere

### ISSUE THREAD

**Issue by AnnaNX1996** [Atmosphere-NX/Atmosphere#1855]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ] I use Switch with Atmos 1.3.1 but after sometime the games just not open (the system says there's an error and closes the game).
[ Did you make any changes related to Atmosphère itself? ] I updated Atmos to last version, along with Hekate, Nyx and sigpatches.
[ If so, make sure to include details relating to what exactly you changed. ] After updating atmosphere, I updated the system itself to 14.0, all using AIO Updater.

### How can the issue be reproduced?

[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

[01649973007_050000baddad0000.log](https://github.com/Atmosphere-NX/Atmosphere/files/8500832/01649973007_050000baddad0000.log)

### System Firmware Version

14.0</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate with RCM Loader
- Official release or unofficial build: Official 5.7.2
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND: SysNAND
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]

### Additional context?

- Additional info about your environment: The problem supposely started after doing a backup with the update 14.0 system, but i'm not totally sure.
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Piracy is not supported.
