### ISSUE TITLE
Bluetooth delays startup

### ISSUE THREAD

**Issue by mgt1309** [Atmosphere-NX/Atmosphere#1857]
### What's the issue you encountered?

Decided to use Bluetooth audio from the switch settings this caused a noticeable lag and or delay of startup when waking up from sleep m9de

### How can the issue be reproduced?

Connect headphones to switch under switch settings and put into sleep mode and turn back on

### System Firmware Version

14.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
Hekate

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
...okay? Why do you believe this is an atmosphere issue. What custom sysmodules do you have. Post a screenshot of atmosphere/contents?

I don't know why you think this is a problem in atmosphere.
