### ISSUE TITLE
Error while loading fss0: atmosphere/package3

### ISSUE THREAD

**Issue by pastelaura** [Atmosphere-NX/Atmosphere#1858]
I am trying to update my Switch's CFW and I keep getting this error. I have tried just about everything to fix it and nothing is working. 

I have:

Updated the Atmosphere files on my SD card
Updated the Sigpatches on my SD card
Updated Hekate on my SD card

Updated hekate_ipl.ini to the following:

[config]
autoboot=0
autoboot_list=0
bootwait=0
verification=1
backlight=100
autohosoff=0
autonogc=1
updater2p=0

[Atmosphere]
fss0=atmosphere/package3
kip1patch=nosigchk
atmosphere=1
emummc_force_disable=1

[Atmosphere_emummc]
fss0=atmosphere/package3
kip1patch=nosigchk
atmosphere=1
emummcforce=1

[Original]
fss0=atmosphere/package3
stock=1
emummc_force_disable=1

And freshly installed everything. 
After all of that, I still get the error "fss0:atmosphere/package3" and it has started to leave me frustrated. I could really use some help.

**Comment by SciresM** [comment]
1) you did not use the issue templates 
2) this is the atmosphere repo and you are describing a hekate problem 
3) piracy is not supported.
