### ISSUE TITLE
Panic occured while running Atmosphere Title ID: 010000000000BD00 Error: std::abort (0xFFE)

### ISSUE THREAD

**Issue by Rejoinable** [Atmosphere-NX/Atmosphere#1866]
### What's the issue you encountered?

I accidentally updated my system and upon rebooting I got this error. 
I updated both hekate and atmosphere and had no success fixing the issue.

### How can the issue be reproduced?

Launching any form of atmoshere in hekate or using the fusee payload.
### Crash Report

[01649526024_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/8550329/01649526024_010000000000100d.log)

### System Firmware Version
Version 14.1.1 
### Environment?

Attempted fusee and hekate with no success on either payload.

I have tried fixing the archive bit in Hekate and this has not worked.

**Comment by masagrator** [comment]
You didn't update MissionControl.
