### ISSUE TITLE
Crash Error Code (2105-0584) after update 14.1.1

### ISSUE THREAD

**Issue by Poop81** [Atmosphere-NX/Atmosphere#1869]
hi, i want to ask for your help pls, after updating the switch to 14.1.1, this one crashes on a screen, see photo below.

Before the update, I was on FW 13.0.0 and AMS 1.2.5.
I started by doing the update with daybreak of the console before wanting to update AMS. 

Before that, I had no theme installed, and to update,
I removed all my files to put the new ones from AMS and Hekate.

I left only the emuMMC folder and it still doesn't work.
Can you help me to solve the problem pls . THX

![SWITCH error after update](https://user-images.githubusercontent.com/104696004/166121536-ef1e3ec5-8203-4e37-a9b6-9cec72f583e6.png)

**Comment by Masamune3210** [comment]
Please go back and fill out the issue template correctly

**Comment by SciresM** [comment]
Reopen using the issue templates.
