### ISSUE TITLE
updated switch while running atmosphere on accident

### ISSUE THREAD

**Issue by negative-son** [Atmosphere-NX/Atmosphere#1873]
## Bug Repot

every time i try to run atmosphere now i get  this a  error with this file report
[report_00000000094f6110.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8606309/report_00000000094f6110.zip) 
![20220502_175212](https://user-images.githubusercontent.com/84262874/166335148-17216e3c-1c9b-4312-ba34-0d4a0ce7d2f0.jpg)

**Comment by SciresM** [comment]
1) you did not use the issue templates
2) remove or update mission control

**Comment by negative-son** [comment]
sorry but what is mission control

**Comment by SciresM** [comment]
It is a custom system module you have installed. Remove it.

**Comment by negative-son** [comment]
i deleted  mission control but i still get a error but there not gray screen

**Comment by SciresM** [comment]
The issue tracker is for bugs, not support. Get further help on discord.
