### ISSUE TITLE
update while using atmosphere

### ISSUE THREAD

**Issue by negative-son** [Atmosphere-NX/Atmosphere#1874]
## Bug Report

crash
n/a
n.a

### What's the issue you encountered?
when  booting up atmosphere  i would get a error message   

a fatal error occurred when running atmosphere 
program,  ID: 010000000000bd00
Error Desc : std : : abort() called (0xffe)

then so on 

when  I reboot it would take me to a gray screen and would stay like that 

i was using  atmosphere bout to play a game but then my joycon was sideways and push the update button and i got a error after  but i dont know what it was about   but  ii think the update didnt go though but after i just updated after om ofc

### How can the issue be reproduced?

[ *this cant really be reproduce not that i know of

### Crash Report
[report_00000000094f6110.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8606447/report_00000000094f6110.zip)

### System Firmware Version
14.1.1
### Environment?
 fuse
offacal 1.3.2
SysNAND:
do have homebrew

**Comment by SciresM** [comment]
I already closed your previous issue with instructions.

If you open another one, I will block you from the tracker.
