### ISSUE TITLE
You did not actually fill out the issue template.  reopen with the issue template filled out and the relevant report file uploaded. Support cannot be provided without a report file.

### ISSUE THREAD

**Issue by JrRamos1524** [Atmosphere-NX/Atmosphere#1877]
[Uploading report_0000000006924bfd.bin…]()

**Comment by Masamune3210** [comment]
Please go back and actually fill out the issue template

**Comment by SciresM** [comment]
This does not have a filled out issue template and does not have a link to the report file. It just has a self-link to the issue.
