### ISSUE TITLE
infinite reboot on boot 

### ISSUE THREAD

**Issue by Manouzr** [Atmosphere-NX/Atmosphere#1879]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

when you launch ams from fusee primary the console reboot

### How can the issue be reproduced?

use switch with kernel 10.0 go to rekado or other payload launcher and start fusee-primary.bin

### Crash Report
N/A
### System Firmware Version

10.0.0</br>

### Environment?

say a the top

### Additional context?

for more information my discord:
Manou#6760

**Comment by SciresM** [comment]
Re-open with the issue template actually properly filled out.

Also, fusee-primary doesn't exist any more.
