### ISSUE TITLE
Games like okami hd and minecraft bedrock crashin an odd way

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#188]
If you try to save in okami HD or use the store in bedrock the console will crash But you can still get the power menu to appear by holding the power button but you cannotinteract with it.   This happens on normal homebrew enabler as well as atmosphere not loading SM seem s to prevent the problem from appearing.

**Comment by plasmafart** [comment]
Did you have online disabled?

**Comment by fennectech** [comment]
This happens on all homebrew enablers      I do not have online disabled. i however use a DNS server to sinkhole a couple URLs.

**Comment by aroooo** [comment]
Crashes on GO VACATION too btw

**Comment by aroooo** [comment]
Happen also with and without Online (on ReiNX)

**Comment by aroooo** [comment]
I've found a (temporary) fix! Removing fs_mitm sys module should work!

**Comment by hexkyz** [comment]
Closing this down as it appears to be related to old bugs in fs_mitm.
