### ISSUE TITLE
Program ID 524850534f53454d. error desc karnel panic (0xf00)

### ISSUE THREAD

**Issue by JrRamos1524** [Atmosphere-NX/Atmosphere#1880]
What's the issue you encountered?
I'm on atmos at 1.3.2, I updated fusee.bin ofc. I got this message when I inject fusee-primary.bin:
"A fatal error occured when running Atmosphere.
Program ID: 524850534f53454d
Error Desc: Kernel Panic (0xf00)
Report saved to /atmosphere/fatal_errors/report_0000000001def6bd.bin"

How can the issue be reproduced?
It happened when I wanted to play and my switch restarted. When I wanted to start my switch and injecting the oficial fusse.bin from my computer or phone “Rekado” appears as an error.

Environment?
Atmosphere 1.3.2 with its fusee.bin
Additional context?

**Comment by JrRamos1524** [comment]
>
[report_0000000001d6cf9d.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8666542/report_0000000001d6cf9d.zip)

**Comment by JrRamos1524** [comment]
[report_0000000001d6cf9d.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8666605/report_0000000001d6cf9d.zip)

**Comment by SciresM** [comment]
You have Atmosphere 1.2.5 installed, for some reason. Please re-open with the issue template filled out if the error still occurs using the latest atmosphere.

**Comment by SciresM** [comment]
If you have a file at sd:/atmosphere/mesosphere.bin, delete it. The fatal report you posted was generated from an Atmosphere 1.2.5 kernel.

**Comment by SciresM** [comment]
Oh, "inject fusee-primary.bin" <-- do not use fusee-primary.bin. It doesn't exist any more. Use fusee.bin.

**Comment by JrRamos1524** [comment]
[Uploading report_00000000007af555.zip…]()

**Comment by SciresM** [comment]
@JrRamos1524 That is not a file upload, it is just self-referential blue text.

**Comment by JrRamos1524** [comment]
[report_00000000007af555.zip](https://github.com/Atmosphere-NX/Atmosphere/files/8673692/report_00000000007af555.zip)

**Comment by SciresM** [comment]
Issue with INI, this has been "user's console has bad RAM" in the past.

Does stock boot without using Atmosphere?

**Comment by JrRamos1524** [comment]
No, I can’t turn it on, not even with the stock mood, what can I  do?

**Comment by JrRamos1524** [comment]
what can I do?
help me

**Comment by Masamune3210** [comment]
If the console wont boot, even without Atmosphere loaded and trying to just run stock, its a good sign that there is some kind of hardware malfunction unfortunately
