### ISSUE TITLE
ADD: native restart and shutdown "app" that can be enabled in system settings getting displayed as a normal game bubble

### ISSUE THREAD

**Issue by AntiFly** [Atmosphere-NX/Atmosphere#1885]
#### Overview:
+ add reboot and shutdown bubble possiblity to atmoshpere natively and getting support it through next updates.
+ setting to enable bubble on/off via *.ini for peeps that do not want it.

#### Smaller Details: 
+ available stand alone here.
https://github.com/dezem/Safe_Reboot
https://github.com/dezem/Safe_Shutdown

#### Nature of Request:  
+ sounds like a basic feature ?

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>
- [**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?
This is a native feature which brings convinience to everybody using the switch.
Its better way than press and hold power button on the switch, cause one click and is shown on the recently used apps which makes it easy to use and is present for daily / common use.

**Comment by SciresM** [comment]
Out of scope.

1) The native shutdown is "safe".
2) The native reboot is "safe".
3) Modification to the UI is *deeply* complicated and Atmosphere doesn't touch qlaunch/etc.
4) Anything that touches the UI in any way is *not* a basic feature.
