### ISSUE TITLE
Atmophere makes Ultimate crash

### ISSUE THREAD

**Issue by R-son** [Atmosphere-NX/Atmosphere#1893]
According to my error logs, Atmosphere crashed. I have no idea why it started crashing, I didn't do anything and it suddenly crashed. I sent the log file. I'm also sending the error on the switch screen.
[01653754315_0100000000000023.log](https://github.com/Atmosphere-NX/Atmosphere/files/8791467/01653754315_0100000000000023.log)
![1653754776222](https://user-images.githubusercontent.com/45995983/170833875-8f9ed33c-95e1-4803-a602-4d11430a23cf.jpg)
[error_log.txt](https://github.com/Atmosphere-NX/Atmosphere/files/8791473/error_log.txt)

**Comment by R-son** [comment]
[error_log.txt](https://github.com/Atmosphere-NX/Atmosphere/files/8791472/error_log.txt)

**Comment by SciresM** [comment]
Reopen using the issue templates.

**Comment by R-son** [comment]
Where is it ?

**Comment by Masamune3210** [comment]
Might want to go ahead and just make a new issue with the template filled out instead of editing this one retroactively
