### ISSUE TITLE
Black screen when booting new Fusee version

### ISSUE THREAD

**Issue by GLippenholz** [Atmosphere-NX/Atmosphere#1894]
I replaced my very old fusee_primary.bin payload with the new fusee.bin one and after booting into hekate and trying to boot into fusee I get a completely black screen. Not only that but when I went to boot back into hekate, I cant and Rekado doesnt even recognize the swithc being plugged in. Worried I might have bricked my switch but I'm not sure how.

**Comment by Masamune3210** [comment]
Please go back and actually fill out the issue template

**Comment by GLippenholz** [comment]
I checked and could not find the template

**Comment by SciresM** [comment]
When you create an issue, it is prepopulated with the template for you to fill out.
