### ISSUE TITLE
Console softlocks when trying to open applet

### ISSUE THREAD

**Issue by Alexlin465** [Atmosphere-NX/Atmosphere#1899]
Edit: title was originally supposed to be 'Console softlocks when trying to open applet'
## Bug Report

Atmosphere crashed/soflocked while trying to open applet from album

### What's the issue you encountered?

I was trying to enter applet after opening Pokémon Shining Pearl and when I did, the screen was stuck after pressing A. I was able to power off, but I think it would be a problem after a long time.

### How can the issue be reproduced?

Opening a game, going to HOME menu then entering applet from album.

### Crash Report

None, it just leaves the screen hanging

### System Firmware Version

14.1.1

### Environment?

- Bootloader: Hekate
- Atmosphere ver 1.3.2
- Homebrew software installed: Super Mario 64 v8

**Comment by SciresM** [comment]
Post a screenshot of your atmosphere/contents dir?

**Comment by StickIT** [comment]
I have the same problem.
[01655130711_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/8892002/01655130711_010000000000100d.log)

**Comment by StickIT** [comment]
Nothing on atmosphere/contents
