### ISSUE TITLE
GDBStub errors when trying to connect to Pokemon Quest

### ISSUE THREAD

**Issue by Lincoln-LM** [Atmosphere-NX/Atmosphere#1904]
### What's the issue you encountered?
When attaching to Pokemon Quest via gdb, it spits out the error ``Reply contains invalid hex digit 34``. Trying to run any command (continue, step, monitor get bases) after this causes gdb to crash. I have not encountered this error in any other application I have tried to attach to (Pokemon Sword/Shield/Lets Go Eevee/Legends Arceus). I am using the latest atmosphere release on the latest switch update and the only modification to system_settings.ini I have made is to enable the gdbstub (``atmosphere!enable_standalone_gdbstub = u8!0x1``).

### How can the issue be reproduced?
1. Launch Pokemon Quest
2. Press A through the title screen, past the controller connection, until you are in the main game
3. Launch aarch64-none-elf-gdb
4. Run ``target extended-remote 192.168.0.18:22225`` (replacing 192.168.0.18 with the switch's local ip)
5. Run ``info os processes`` to get the pid of the application
6. Run ``attach 183`` (replacing 183 with the pid of the application)

### Crash Report
N/A

### System Firmware Version

14.1.2</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: Official
  - 1.3.2
- Do you have additional kips or sysmodules you're loading: sys-botbase, ldn_mitm, and sysdvr are running, though the issue is present even without them
- Homebrew software installed: Nothing running while attempting to connect
- EmuMMC or SysNAND: SysNAND

### Additional context?
N/A

**Comment by SciresM** [comment]
Pokemon Quest has a thread name containing the character `#` (`Worker Pool Thread #0`) which wasn't being escaped and therefore caused gdb to misparse packet.

Fixed in latest commit.
