### ISSUE TITLE
Heketate boots after Switch Logo

### ISSUE THREAD

**Issue by NoahYTK** [Atmosphere-NX/Atmosphere#1906]
Hello Guys, My Switch is always Booting back into Hekate after the Switch Logo, basically like an infinite Loop. I launch Atmosphere, it shows the Logos, and back into Hekate.

**Comment by Shinjikuro95** [comment]
What are you using to boot it into hekate? Your pc or the rcm loader? Either way, try to instead of booting hekate, directly load the atmosphere package. If it reboots to hekate even like this it means there is a file missing or corrupted
