### ISSUE TITLE
NS Update jun 22

### ISSUE THREAD

**Issue by jdroo** [Atmosphere-NX/Atmosphere#1907]
There is an update being pushed out on my system Ver. 14.1.2 (Released June 13, 2022), will the current version of atmosphere still work if I update?

**Comment by SciresM** [comment]
There is not, to my knowledge, any new system update right now.

The latest update I am aware of is 14.1.2, which Atmosphere 1.3.2 works fine with.

**Comment by SciresM** [comment]
Also, you did not use the issue templates. Please do not make issues for this sort of thing.

**Comment by jdroo** [comment]
Sorry, was not sure how to ask otherwise, thanx for letting me know it works on the latest NS update.
