### ISSUE TITLE
1bit mode sd but no broken/missing pin, I can no longer access to atmosphere

### ISSUE THREAD

**Issue by Yungdaime** [Atmosphere-NX/Atmosphere#1910]
Hello all I need help, I cant access to my cfw on my switch because 1bit mode.
I buy a new sd card reader and change the old one, but nothing change, after I open my switch because I see some peoples who have broken or missing pin on the motherboard but all seems good on mine.
I test all the pin with a voltmeter but everything look good.
I test the new sd reader on a friend switch and he work good.
My switch seems to read my sd well in ofw but hekate boot in 1bit mode and when I launch fusee I have a fatal error.
I dont try to factory new reset my switch already idk if it can change something.
I test with another clean sd card with only importants files but it's the same.
I use Atmosphere in his latest build and my firmware is 13.1.
If somebody have a solution or something your help is welcome, thanks in advance.

**Comment by masagrator** [comment]
1. You didn't use issue template
2. It's not related to Atmosphere since it's a hardware issue

On side note: I would check pins on motherboars. Probably they are damaged

**Comment by SciresM** [comment]
Re-open using the issue templates.
