### ISSUE TITLE
Crashes when using Awoo installer. error code is 2168-0002 (0x4a8). Unable to fix on my own.

### ISSUE THREAD

**Issue by Alt-Ctrl-Crash** [Atmosphere-NX/Atmosphere#1911]
## Bug Report
error code is 2168-0002 (0x4a8).

### What's the issue you encountered?

I was trying to install a game via ns-usbloader  and Awoo-Installer. Before the game could finish installing atmosphere crashed and I received an error message.  The error code is 2168-0002 (0x4a8). I have made multiple attempts to fix the issue but have been unable to do so.

![messages_0](https://user-images.githubusercontent.com/58786225/176495191-cdfa2982-3f4a-4b82-a969-8664ad387492.jpeg)

Did you make any changes related to Atmosphère itself?
N/A

### How can the issue be reproduced?
I'm not sure how it can be reproduced but I have gotten this specific error message multiple times. The error always appears when I am trying to install  a game via usb and Awoo or gold leaf.

### Crash Report
[<script src="https://gist.github.com/Alt-Ctrl-Crash/9abaf60eb73008265d9178e0fbe487fb.js"></script>](url)

### System Firmware Version
14.1.1 Atmosphere (1.3.2-master-e96972c93)

### Environment?

- What bootloader:  hekate 5.7.2 Official build

- Do you have additional kips or sysmodules you're loading: 
 I do not have any additional sysmodules.

- Homebrew software installed:
Tinfoil, Goldleaf, Awoo, Breeze, EdiZon, Gamecard Installer nx, nxdumptool, NX Shell, Homebrew App Store, Retro Arch.

- EmuMMC or SysNAND:
EmuMMC partition based 

### Additional context?
I tried fixing the problem by updating the Sig-patches but that didn't work. I read a post online that said this problem could be fixed by deleting the program file( in this case file 01000000000100D) from the the contents folder within the atmosphere folder, however I was unable to fix this issue by deleting the file as there was no file ending in 00100D in the contents folder. I searched the entire sd card but I couldn't find a file or program named 01000000000100D.

**Comment by SciresM** [comment]
Piracy is not supported.
