### ISSUE TITLE
A fatal error while running atmosphere ID:010041544d530000

### ISSUE THREAD

**Issue by BASgamer** [Atmosphere-NX/Atmosphere#1914]
### What's the issue you encountered?

The switch was booting up fine until i updated atmosphere to the latest release then after that when i push the payload i get a fatal error. 

A fatal error occurred when running Atmosphére.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

Was on a 13.x firmware and when updating the atmosphere files. Got a crash then.
Used older atmosphere again and it booted correctly.
Thought maybe updating the firmware would help so updated switch to 14.1.2 and updated atmosphere to the latest and got the crash again.

### How can the issue be reproduced?

Pushing Fusee.bin with tegraRCM

### Crash Report

[report_0000000005c22b52.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9035292/report_0000000005c22b52.zip)

### System Firmware Version

14.1.2

### Environment?

Pushing Fusee.bin with tegraRCM
Atmosphère 1.3.2
No kips or sysmodules
Nothing in the contents folder
SysNAND
Fat32

### Additional context?

Ive tried multiple things to fix it
Removing the content folder
reformating the sd
tried with a different sd and still crashes
archive bit in hekate
had incognito rcm on and restoring that

**Comment by BASgamer** [comment]
on a whim i tried 1.3.1 atmosphere and that worked... so if any help figuring out why 1.3.2 didnt would still be helpful so it wont be an issue in the future would be nice

**Comment by BASgamer** [comment]
https://gbatemp.net/threads/error-010041544d530000-when-booting-atmosphere-cfw.590522/ 
solved my issue guess for some switches power_menu_reboot_function = str!payload crashes it?

**Comment by SciresM** [comment]
`settings::InvalidFormatSettingsItemValue` just indicates malformed user-configuration INI. I can look at the file itself if you want to upload it, but not a bug.

**Comment by BASgamer** [comment]
[system_settings.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9074320/system_settings.zip)
think this was it

**Comment by Masamune3210** [comment]
Maybe your editor is inserting some invisible characters and it's confusing the parser? Try recreating the issue using a different text editor

**Comment by ObscenityIB** [comment]
necro, just had this same issue, I was using VSCodium on Linux to edit the text files.

**Comment by samputu** [comment]
Fatal error occurred when running Atmosphere 
Program ID: 010041544d30000

What do I do?

**Comment by Masamune3210** [comment]
You gave almost literally the least amount of information you could give on a two-year-old closed issue. Exactly how many people do you think are going to be able to help you?
