### ISSUE TITLE
A fatal error while running atmosphere ID:010041544d530000

### ISSUE THREAD

**Issue by JakeJewsbury** [Atmosphere-NX/Atmosphere#1915]
## Bug Report

Error when trying to load atmosphere after loading hekate

### What's the issue you encountered?

trying to load atmosphere by hitting launch on the left from hekate, then I got that error. It is the same error as the last poster in this issues thread I believe.

### How can the issue be reproduced?

trying to launch atmosphere from hekate. Same error each time.
### Crash Report

You guys said to make a gist but I didnt completely understand how to do that so I uploaded the fatal_error folder that was made in the atmosphere folder to google drive. Here is the link:
https://drive.google.com/drive/folders/13mHXmp9UIFOQR8woZt_8fKfsTYlvxgWc?usp=sharing

### System Firmware Version

X.X.X</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: 
  -Official release

- Do you have additional kips or sysmodules you're loading: No
- EmuMMC or SysNAND: trying to launch SysNAND

### Additional context?

I was following this video: https://www.youtube.com/watch?v=aRa0auMaxCI
right after 10:07 is when I get the error.

I am very sorry if this report is missing information or unclear, I am not familiar with modding or any of this. I will be checking this frequently in the next few days to better answer any questions if you have them for me, thank you.

**Comment by SciresM** [comment]
Use the archive bit fixer tool in hekate; your reports indicate archive bit issues.

The issue tracker is for bugs, not support, so if you need help doing this seek support on discord.
