### ISSUE TITLE
Panic Occured while Running Atmosphere Error Upon Opening Pokemon Sword

### ISSUE THREAD

**Issue by whiteglovian** [Atmosphere-NX/Atmosphere#1916]
### What's the issue you encountered?

[ I've tried everything from the Hekate Fix to checking my formatting(Fat32), even uninstalling and reinstalling my CFW from the ground up, removing my Sword contents folder, uninstalling and reinstalling the 3GB update from my Switch/SD card, removing all my saves for Sword from JKSV and even deleting the save I've been cultivating for years-- no results, sadly. The only thing I've seen work is booting from Stock, ]
[ I'm booting from a game card. Booting other games from game cards does not reproduce the same results. Booting other modded games works, unlike Pokemon Sword. Removing mods, as stated previously, do nothing.
The error information reads the following, ]
[ "A fatal error occurred while running Atmosphere, ]
[ Title ID: 01004154D53000, ]
[ Error: std::abort (0xFF3)". ]</br>
[ I did not modify Atmosphere whatsoever, ]</br>

### How can the issue be reproduced?

[ Boot CFW, ]</br>
[ Load Pokemon Sword from Gamecard, ]</br>

### Crash Report

[report_02cc27177.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9065116/report_02cc27177.zip)

### System Firmware Version

[ 14.1.2, ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Hekate (5.8.0) and Fusee (1.3.2) both cause the crash
- Do you have additional kips or sysmodules you're loading: No
- SysNAND

### Additional context?

- Additional info about your environment:
- I have a hard copy of Pokemon Sword
- Other hard copies do not cause it to crash
- Other modded games do not crash
- Removing my LayeredFS does nothing

**Comment by SciresM** [comment]
The crash is occurring because fs::ResultPathNotFound() is returned when trying to open a subdirectory while creating layeredfs romfs image.

"Removing my LayeredFS does nothing" I do not believe you, post the report generated with your mod fully deleted if you want me to re-open and investigate that case.

This is almost certainly just an archive bits problem, or perhaps a non-ascii filename. Either way.

**Comment by whiteglovian** [comment]
Okay, thank you! The problem was probably me cutting and pasting it to the root instead of fully removing it
Going through all my mods, it seems like it could've been a lack of exefs or something, I really appreciate it. I just needed a fresh look at it!
Now, this is 100% common sense, I was frustrated and annoyed and didn't want to do the basics, and this is 100% on me.
