### ISSUE TITLE
Randomly got this Crash while loading a theme in Theemzer

### ISSUE THREAD

**Issue by lando07** [Atmosphere-NX/Atmosphere#1917]
### What's the issue you encountered?

I encountered a strange error when loading Themezer themes to download them.

### How can the issue be reproduced?

All I was doing was loading and searching themes, when I clicked on one of them and the crash happened, I haven't found any way or any clue on how to reproduce it.

### Crash Report

[01657382859_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/9079878/01657382859_010000000000100d.log)

### System Firmware Version

14.1.2</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: I booted Fusee.bin via Hekate
- Official release or unofficial build: 
  - Official release
- Do you have additional kips or sysmodules you're loading:
- No
- Homebrew software installed:
- Themezer, nxdumptool, sys-clk, NX themes installer, reboot to payload
- EmuMMC or SysNAND:
  - Running on bare metal hardware everything is booted via SD and I think I'm in SysNAND mode

### Additional context?

That's about it.

**Comment by Masamune3210** [comment]
Go back and fill out the issue template please, also this log just says that the homebrew died which caused hbloader to crash

**Comment by lando07** [comment]
Where do I find it?

**Comment by Masamune3210** [comment]
It would have been pre-populated in the issue when you first created it

**Comment by lando07** [comment]
Strange, It didn't do that for me, I'm going to repost it

**Comment by masagrator** [comment]
Looks like memory leak - either because of homebrew bug or using it in applet mode when it requires more ram than applet mode gives.
Not Atmosphere related

**Comment by lando07** [comment]
Oh yea I was in applet mode
