### ISSUE TITLE
Crashing when launching smash ultimate

### ISSUE THREAD

**Issue by SAB236YT** [Atmosphere-NX/Atmosphere#1919]
Title ID 0141544D530000
Error: std: : abort (0xFFE)

please help

**Comment by SciresM** [comment]
1) you didn't use the issue template
2) this issue tracker is for bugs, not for support
3) you deleted the report you uploaded
4) The report you linked has fs::ResultInvalidFatFormatSd(), indicating your sd card isn't formatted correctly as fat32.
