### ISSUE TITLE
Using LayeredFS with progs using selfmade TitleIDs always leads to a crash

### ISSUE THREAD

**Issue by 20Phoenix** [Atmosphere-NX/Atmosphere#1925]
Hello :)

I've made a NSP myself and gave it an own TitleID. The app works wonderfull.
But if I want to change something by using LayeredFS, the app always crashes after 2 seconds,
only the first black loading screen appears.
I know how to use LayeredFS correct. With official apps I have no problems at all, only with those using selfmade Title-IDs.
Even just using one unchanged file which would never occur an error (for testing) fails.
Also my SDcard is formated correct with FAT32 + 32kb clusters.
And there's nothing corrupt on SD. I reformated it extra for testing, no changes.

### Crash Report

error message:
```
Panic occurred while running Atmosphere.
Title ID: ...
Error: std::abort (0xFFE)
```

![grafik](https://user-images.githubusercontent.com/31387801/181229031-05a6cbae-0067-4eb3-a91d-7de992decc79.png)

### System Firmware Version

newest FW 14.1.2 + Atmo 1.3.2

**Comment by SciresM** [comment]
Piracy (which by Atmosphere-NX's judgment includes unofficial content installation of any kind, including your own homebrew software) is not supported.

Homebrew should be launched through the homebrew menu.
