### ISSUE TITLE
Panic occured while running Atmosphere.

### ISSUE THREAD

**Issue by UntitledOutput** [Atmosphere-NX/Atmosphere#1934]
### What's the issue you encountered?

I was just trying to get the Splatoon 3: Splatfest World Premiere by using a New Zealand account, but then my switch suddenly came up with a atmosphere error.

### How can the issue be reproduced?

I have no idea how the issue was produced, so i can't explain how it can be reproduced

### Crash Report

I don't have one. On the error screen it said it would make an error report in the fatal-errors folder, but there's just one error which I think is unrelated.

### System Firmware Version

14.1.2

### Environment?

- What bootloader  was Atmosphère launched by: hekate/fusee
- Official release or unofficial build: 1.3.2
- Do you have additional kips or sysmodules you're loading: I do not remember.
- Homebrew software installed: Atmosphere? (There was no explanation for this)
- EmuMMC or SysNAND: EmuMMC (partition)

### Additional context?
 
N/A

**Comment by SciresM** [comment]
I cannot help you without the report file. The fatal error message gives you a full file path. Upload it, or this will have to be closed.

**Comment by UntitledOutput** [comment]
Okay.

**Comment by UntitledOutput** [comment]
[report_00000b59fd1dd6a8.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9417990/report_00000b59fd1dd6a8.zip)

**Comment by UntitledOutput** [comment]
Rename it to a .bin file because I couldn't upload it.

**Comment by SciresM** [comment]
Post a screenshot of your atmosphere/contents folder? The error is out of range in layered romfs read, which suggests you have a broken mod of some kind.

**Comment by UntitledOutput** [comment]
![2022-08-24 (1)](https://user-images.githubusercontent.com/79727016/186480888-7b06fec7-b539-4e1e-ae00-bb6005372581.png)

**Comment by SciresM** [comment]
...that looks like custom sysmodule + mods, yes.

Does the error go away if you delete your mods/custom sysmodules?

For testing, you can rename the contents folder to "contents.old" to ensure clean status.

If this fixes it (and I expect it will), one of your mods is broken, you'll have to test to determine which.

**Comment by UntitledOutput** [comment]
It still comes up with the error.

**Comment by SciresM** [comment]
I do not actually believe you. Show me a screenshot of your atmosphere directory with no contents dir whatsoever and upload the new report.

**Comment by SciresM** [comment]
(the relevant codepath in your report is impossible to trigger without a contents dir)

**Comment by UntitledOutput** [comment]
I just went back to hekate, and did the usb SD card mount, and for some reason if I change the SD card (rename a file. etc.) then it reverts the changes.

**Comment by SciresM** [comment]
Check that your sd card isn't write locked, I guess. Or it might be an sd card failure otherwise...I'm going to close this because it seems obvious to me this is an issue with your stuff and not an atmosphere bug, and the issue tracker is for bugs, not for support.

You may get further support on discord ^^
