### ISSUE TITLE
0100000000000001 Breath of the Wild Fatal Error

### ISSUE THREAD

**Issue by jayvenem** [Atmosphere-NX/Atmosphere#1935]
### What's the issue you encountered?

A fatal error occurred when running Atmosphère
Program ID: 0100000000000001
Error Desc: std::abort () called (0xffe)
Report saved to /atmosphere/fatal errors/report_0000000029fb71b1.bin
Press POWER to reboot

 Whenever I launch botw, i get an fatal error 0100000000000001. </br>

### How can the issue be reproduced?

I just launched breath of the wild.</br>

### Crash Report

[ https://gist.github.com/jayvenem/d7140ee9bb1d5b9862cd3956bfb0edcc ]</br>

**Comment by SciresM** [comment]
Your crash report is completely unrelated to the report you're making.

Pleasae upload `atmosphere/fatal errors/report_0000000029fb71b1.bin` as mentioned in your issue.

**Comment by jayvenem** [comment]
> Your crash report is completely unrelated to the report you're making.
> 
> Pleasae upload `atmosphere/fatal errors/report_0000000029fb71b1.bin` as mentioned in your issue.

Apologies!

**Comment by jayvenem** [comment]
[report_0000000029fb71b1.zip](https://github.com/Atmosphere-NX/Atmosphere/files/9420599/report_0000000029fb71b1.zip)

**Comment by jayvenem** [comment]
It wouldn't allow me to send the bin file.

**Comment by SciresM** [comment]
Out of bounds error when applying an ips patch.

I think your game mod is corrupted, please delete it + verify issue is fixed, then re-download.

This isn't a bug, and the issue tracker is for bugs (not support) so closing -- further support is available on discord as needed.

**Comment by SciresM** [comment]
(Your mod will presumably be at atmosphere/contents/01007ef00011e000)

**Comment by jayvenem** [comment]
> (Your mod will presumably be at atmosphere/contents/01007ef00011e000)

Nothing was there oddly, reinstalled and just crashed again, strange.

**Comment by SciresM** [comment]
Post a screenshot of your atmosphere/contents folder?

**Comment by jayvenem** [comment]
![2022-08-25 (1)](https://user-images.githubusercontent.com/65187787/186574742-329895d4-dac6-468c-90f9-eaecda506208.png)
![2022-08-25](https://user-images.githubusercontent.com/65187787/186574744-0a56f821-1a9d-4cf4-9c2e-8bd7374976d7.png)
