### ISSUE TITLE
Write Directly to ARM Registers with Code Type 0xB

### ISSUE THREAD

**Issue by ReclaimerShawn** [Atmosphere-NX/Atmosphere#1936]
## Feature Request: 

Make a Code Type that can change ARM Registers at a given instruction address. I suggest using Code Type 0xB, as it's currently unused. This is something that can also be done directly with IDA Pro without the use of Atmosphere's gdbstub, but that's not going to doable by a basic user.

#### Overview:
A Code Type 0xB with the following syntax:
BTRR00XX XXXXXXXX YYYYYYYY (YYYYYYYY)

T = Register Type (1 = 32-Bit Register, 2 = Float Register, 3 = 64-Bit Register, 4 = Double Register)
RR = ARM Register Number (Anything from 0-30, or 0x00-0x1E)
X = Offset of Instruction in MAIN
Y = What to Set Register To

For example:
B2100000 0067C894 7F800000 - Sets Register S16 to 0x7F800000 once PC Register is MAIN+0x0000067C894

#### Smaller Details: 
The code could work by waiting for the PC register to match the X address in the code type. After it reaches this address, write the register to the value given by Y. When the PC register doesn't match the X address, don't do anything to the ARM Register.
 
I feel this would be particularly difficult, as dmnt_cheat and gdbstub cannot currently attach at the same time. dmnt_cheat would be needed to load cheats and gdbstub would be needed to mess with anything ARM-related. You'd also have to make the codehandler calculate what PC needs to be, as PC in the above example wouldn't be 0x0000067C894, rather, it'd be 
MAIN+ 0x0000067C894

### Why would this feature be useful?
A majority of codes I've made (and others) simply involve setting a register in ARM to something or preventing a value in a register from being stored/loaded to memory. It's often necessary to create a codecave if there's no space in the current function, all just to load a value to a register. Doing this with float and double registers is particularly annoying, as you have to use the instruction FMOV alongside the typical MOV in order to get the value of your choice in the float/double register. Furthermore, MOV isn't able to accommodate many float values, as MOV only works with 16-bit values and a few others. This could also prevent crashes associated with trying to write over multiple instructions in memory just to change a register to be what you want it. As a result, codes that may be impossible or difficult to make due to space constraints would now be either possible or a lot easier to make.

**Comment by SciresM** [comment]
This is fundamentally incompatible with the cheat virtual machine architecture, which executes at a fixed interval and does not have the ability to take actions on certain instructions.

I am open to technical discussion, please contact me on discord if interested (`SciresM#0524`)

Have you considered making code mods instead of cheats?
