### ISSUE TITLE
still have to launch with fusee primary in newest realese settings still says im on ams 0.16.2

### ISSUE THREAD

**Issue by blo0dyteeth** [Atmosphere-NX/Atmosphere#1937]
### What's the issue you encountered?
still have to launch with fusee primary in newest realese settings still says im on ams 0.16.2 if i launch with fusee the screen goes black
[ Describe the issue in detail and what you were doing beforehand. ]</br>
decided to update cfw and then it happened
### How can the issue be reproduced?
n/a
### System Firmware Version
9.1.0
### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- hekate
- Official release or unofficial build: 
  - [ Official release version 1.3.2
- Do you have additional kips or sysmodules you're loading:
i dont think so
- EmuMMC or SysNAND:
  - idk

### Additional context?
switch works fine with fusee primary still

**Comment by SciresM** [comment]
fusee-primary is not supported. Do not use it. 

Use fusee.bin from the latest release.

Delete your entire atmosphere directory, then extract latest release zip. If fusee-primary works, your atmosphere directory is old and won't work.
