### ISSUE TITLE
[Feature Request] LayeredFS replace entire directory suppressing existing contents 

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#1938]
#### Overview:
- Replace entire directory contents with contents on SD 

#### Smaller Details: 
- I would like a way that i can replace the entire contents of a directory instead of just replacing / adding individual files in it so that files that were there are not seen by the game.

#### Nature of Request:  
- Addition
  - Custom system modules.</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?
This would be useful to replace entire directories in games with different contents and completely suppress the existing files.

**Comment by fennectech** [comment]
Because its simper    There are some games that load all contents in a spesific directory and being able to suppress files without replacing them would be great

**Comment by SciresM** [comment]
I don't actually agree or believe that it's simpler.

**Comment by fennectech** [comment]
It’s easier to pull off for those with limited programming abilities.  It also is less maintaince for games with frequent updates.Sent from my iPad On Sep 6, 2022, at 12:33 PM, SciresM ***@***.***> wrote:﻿
I don't actually agree or believe that it's simpler.
