### ISSUE TITLE
Error booting system (after changing system language)

### ISSUE THREAD

**Issue by Krouwndouwn** [Atmosphere-NX/Atmosphere#1941]
## Bug Report

![crash-photo](https://user-images.githubusercontent.com/74251059/190220302-896dd1a6-779a-4b87-b793-f3beb0746ccd.jpeg)

Crash when booting Atmosphere after changing system language.

### What's the issue you encountered?

Setup at this moment: "Switch firmware 14.1.1" + "Atmosphère 1.3.2" +  hekate v5.7.2 & Nyx v1.2.2 + MissionControl 0.7.0.

1. I was playing a game (on EmuMMC) and wanted the system language to be changed.
2. I navigated to the settings menu and changed the system language from "Dutch" to "English".
3. A reboot was needed so i did a reboot (rebooted to hekate because i changed the "reboot_payload.bin" to hekate bin file) and then tryed to open the system (EmuMMC, fusee.bin) again.
4. After the Nintendo switch logo a Atmosphere crash was shown.

I thought maybe it has something to do with "MissionControl 0.7.0" or something else so deleted the atmoshpere, bootloader, config folders and files: daybreak.nro, reboot_to_payload.nro and hbmenu.nro,

After this I downloaded the latest atmosphere (Atmosphère 1.3.2) and hekate (hekate v5.8.0 & Nyx v1.3.0) files to get a fully clean setup. After moving the new files and folder i tryed to start the system (EmuMMC, fusee.bin) again but still got the crash after the Nintendo switch logo.

The crash report i provided are after doing all these steps.

### How can the issue be reproduced?

Not sure... but maybe possible to reproduce when changing the language (When the "reboot_payload.bin" file is changed to the hekate bin file).

### Crash Report

Somehow i got two crash reports.

Crash report 1: https://gist.github.com/Krouwndouwn/30a6a340b4835ce85b073000e06e7581
Crash report 2: https://gist.github.com/Krouwndouwn/abaa4e702095e6a74949929d5c84e695

### System Firmware Version

14.1.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:

hekate v5.8.0 & Nyx v1.3.0 for booting fusee.bin (EmuMMC).
Atmosphère 1.3.2

- Official release or unofficial build: 

Official release version 1.3.2 (Atmosphère)

- Do you have additional kips or sysmodules you're loading:

MissionControl 0.7.0 (Only when the first error was shown).
ITotalJustice - patches (Supports HOS firmware 14.1.0+ and AMS 1.3.2).

- Homebrew software installed:

Awoo-Installer, Checkpoint, Goldleaf, JKSV, mGBA, NX-Shell, SuperHaxagon and tinfoil.

- EmuMMC or SysNAND:

EmuMMC (partition-based + fat32)

### Additional context?

As mentioned before i changed the "reboot_payload.bin" file inside the Atmosphere folder to the hekate one.

**Comment by SciresM** [comment]
fs::ResultPortMmcNotActivated()

Sounds like emummc corruption, not an atmosphere issue. Reformat your emummc/etc.

Also, piracy not supported.
