### ISSUE TITLE
Crash when call appletCreateLibraryApplet or appletHolderStart

### ISSUE THREAD

**Issue by Povstalez** [Atmosphere-NX/Atmosphere#1943]
## Bug Report
Hi, I'm newly for switch homebrew developbent.
I'm compiled my program as AppletType_SystemApplet and when call appletCreateLibraryApplet or appletHolderStart atmosphere crashes after some time (about 30 sec).

Code snipped:
`	Result rc = 0;

	rc = appletCreateLibraryApplet(&currentApplet, AppletId_LibraryAppletOfflineWeb, LibAppletMode_AllForeground);
	if(R_SUCCEEDED(rc))
	{
		rc = appletHolderStart(&currentApplet);
		if(R_SUCCEEDED(rc))
		{
			return rc;
		}
	}`

**Comment by SciresM** [comment]
1) This is likely an issue with the Nintendo side of the OS, not atmosphere.

2) Your issue report cannot be acted on because you did not include the crash report.

3) Re-open using the issue templates.
