### ISSUE TITLE
How to solve Panic? Title ID : 524850534F53454D. I cant fix it. please help me.

### ISSUE THREAD

**Issue by qkrrhsjgrh** [Atmosphere-NX/Atmosphere#1944]
=============================================================================
Panic occurred while running Atmosphere.

Title ID : 524850534F53454D
Error : KRNL (0xF00)

Report saved to /atmosphere/fatal_errors/report_0fc3784.bin

Press POWER to continue._**
=============================================================================
I already Googling and found same issue on here. but I cant find "How to solve that problem"

Please, Please... 
I want to know how to solve it....

**Comment by Masamune3210** [comment]
Piracy is not supported
