### ISSUE TITLE
Package1 error, tried to reboot. Pressed power button for 5 seconds, now my Switch won't turn on.

### ISSUE THREAD

**Issue by whiteglovian** [Atmosphere-NX/Atmosphere#1947]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Absolutely not! ]</br>
[N/A]</br>

### How can the issue be reproduced?

[1. Boot into Atmpsohere with 1.3.2, on 15.0.0]</br>
[2. At the Package1 error, press the Power button until the Switch appears to turn off.]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

[1.5.0]</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Official release version 1.3.2]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ N/A ]
     - [ N/A ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND:
  - [ SysNAND ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Wait for 15.0.0 support. It's being worked on.

**Comment by whiteglovian** [comment]
Thank you!!
