### ISSUE TITLE
Broken link in README

### ISSUE THREAD

**Issue by Railf** [Atmosphere-NX/Atmosphere#195]
The "naehrwert and st4rk for the original hekate project and its hwinit code base" line contains a broken link for the hekate project.

**Comment by tumGER** [comment]
Yes, this is intentional

**Comment by xorinzor** [comment]
I'm gonna guess it's because the project is dead and continued by someone else.

But why would you keep a dead link? A 404 page doesn't add any credit to the original authors. Just their names would do and look cleaner too.

**Comment by SciresM** [comment]
Broken link is kept out of respect for nwert.
