### ISSUE TITLE
A fatal error has occurred  when running Fusee Unable to identify package1!

### ISSUE THREAD

**Issue by GreenMar1** [Atmosphere-NX/Atmosphere#1950]
## Bug Report

When using fusee.bin to initialize atmosphere the error of the title pops up

### What's the issue you encountered?

So when I got home i wanted to play smash and a advertice showed up, it was the latest update i think is the 15.0.0 i clicked on it and the switch was supposed to restart but intead that error popped up, at first i thought I just needed to use tegra so I turned of the switch into RCM mode and injected fusee again, but when i tried that the same thing happened I searched online the error and all the solutions were the same "just update atmosphere and hekate and use the latest fusee.bin" so I did that and nothing changed, the same error keeps showing up over and over again and when I entered the section of issues here it said something like this "Reverse engineer potential new boot sysmodule changes." but I dont know what that means 

### How can the issue be reproduced?

How this happened was something like this:
Start the switch
download the latest version of the switch but without having the latests versions of atmosphere and hekate (having your switch in outo RCM everytime you fully turn it off)
And wait for the error to show up

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

15.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Fusee
- Do you have additional kips or sysmodules you're loading: no
- Homebrew software installed: no

### Additional context?
And this minor detail happened to and its when I push the power botton to put the switch in out RCM the logo of atmosphere flashes during like the 12 seconds

**Comment by Adubbz** [comment]
Please wait for 15.0.0 support, it is currently in development.
