### ISSUE TITLE
15.0.0 unable to start software

### ISSUE THREAD

**Issue by Killua0017** [Atmosphere-NX/Atmosphere#1955]
### What's the issue you encountered?
I accidentally update my software from 14.2 to 15.0.0 the latest software.
I replace my atmosphere to latest one (pre-release version)
I successfully replace the atmosphere to my sd card with new version and inject the new fusee.bin.
my console is starting but all software inside is not working it says
Unable to start software.
Return to the HOME Menu and try again.
 

### System Firmware Version

current version : 15.0.0/AMS 1.4.0S

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: FUSEE
- Official release or unofficial build: 
  - [ Official release version x.x.x (or) unofficial build ] Pre release
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:  I dont know
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND:
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ] file based i think

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]
![WhatsApp Image 2022-10-13 at 11 06 43](https://user-images.githubusercontent.com/115570122/195535817-c675c633-f76d-407a-81f9-8a6281e99c85.jpg)
![WhatsApp Image 2022-10-13 at 11 07 50](https://user-images.githubusercontent.com/115570122/195535825-f2824b7f-8c5f-4fb1-a0df-180b0647c259.jpg)
![WhatsApp Image 2022-10-13 at 11 07 45](https://user-images.githubusercontent.com/115570122/195535827-a4807acf-2934-4832-a28b-9291646f39c7.jpg)

**Comment by JustNightBG** [comment]
Did you tried updating the sigpatches?
https://jits.cc/patches

**Comment by Killua0017** [comment]
Thank you very much.
i tried this one . now its working but only tinfoil is not working. when i open the tinfoil it stuck on black screen. but other saved software is working

    On Thursday, October 13, 2022 at 12:50:32 PM GMT+4, JustNightBG ***@***.***> wrote:  
 
 


Did you tried updating the sigpatches?
https://jits.cc/patches

**Comment by masagrator** [comment]
Piracy is not supported
