### ISSUE TITLE
Bluetooth controllers dont work

### ISSUE THREAD

**Issue by PistonTomas** [Atmosphere-NX/Atmosphere#1959]
### What's the issue you encountered?

I updated to 15.0.0 and atmosphére 1.4.0 a when i want to connect my pro controller using bluetooth didn connects

### How can the issue be reproduced?

Connecting a bluetooth controller

### System Firmware Version
15.0.0 and atmosphére 1.4.0 
### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build:  Official build 1.4.0
- Do you have additional kips or sysmodules you're loading: sys-con ,sys-clk
- Homebrew software installed: [ All SDSetup  ]
- EmuMMC or SysNAND: SysNAND

**Comment by SciresM** [comment]
I would bet this is to do with your custom sysmodule that impacts controller connections.

Atmosphere doesn't touch hid/Bluetooth stuff.

**Comment by Masamune3210** [comment]
Make sure you update Mission Control if you are using it, it recently got a tentative update to support 15.0.0
