### ISSUE TITLE
Error Code on boot after updating to 1.4 (error code 2162-0002 (0x4a2)

### ISSUE THREAD

**Issue by GlutenCanKill** [Atmosphere-NX/Atmosphere#1960]
Updated my switch and atmosphere would no longer launch, so I figured I needed to update and now it'll launch, but this this error.

**Comment by SciresM** [comment]
You didn't use the issue templates, and probably need to delete your theme. The issue tracker is for bugs, if you want support go on discord.

**Comment by GlutenCanKill** [comment]
I cant find the discord link anywhere here, sorry. Can I get a link to it?

**Comment by SciresM** [comment]
When you hit new issue, the bottom most option is a link to the discord, with instructions to ask questions there.
