### ISSUE TITLE
Issue - Unable to identify package1

### ISSUE THREAD

**Issue by solomani** [Atmosphere-NX/Atmosphere#1961]
**Error**
A fatal error occurred when running fusee.
Unable to identify package1!
Press POWER to reboot.

**What's the issue you encountered?**
After booting up Atmosphere 1.3.2, through Hekate 5.9.0 and fusee in the same package (April 30, 2022), via payload option in hecate. 

**How can the issue be reproduced?**
Boot to RCM
Launch Hekate
Boot Atmosphere through fusèe
.
**Crash Report**
n/a just the error message above.

**System Firmware Version**
14.1.1

**Environment?**
Switch/sdcard.

**Comment by SciresM** [comment]
Atmosphere 1.3.2 does not support 15.0.0. 

Update to the 1.4.0 prerelease.

**Comment by solomani** [comment]
Great, thank you, this worked.
