### ISSUE TITLE
Fails to boot into FW 15 (emunand) if using Fusee.bin via hekate or TegraRCMGui

### ISSUE THREAD

**Issue by mrdude2478** [Atmosphere-NX/Atmosphere#1963]
CLEAN install - Latest AtmosphereNX + Hekate installed, using emunand + NO patches, booting via hekate.
FW11 -
boots from package3 - good
boots from fusee.bin - good

FW 14.1.2 -
boots from package3 - good
boots from fusee.bin - good

FW 15.0.0
boots from package3 - good, but sometimes fails to boot and sometimes takes a long time to boot and gets stuck on switch logo.
boots from fusee.bin - fail, shows Atmosphere boot screen, fails to get to switch logo - requires hard reset.

TEST 2:
Fresh SD card, formatted exfat. Clean Latest Atmosphere install - no hekate/no patches - payload sent via TegraRCMGui. (Using emunand)

FW11 - boots.
FW 14.1.2 - boots.
FW 15 - Flashes Atmosphere boot screen - Fails to boot into switch logo. Requires a hard reset.

**Comment by SciresM** [comment]
"boot from package3" wat

1) you did not use the issue templates
2) this indicates you do not understand how atmosphere's boot process works, "package3" isn't bootable unless you mean hekate, in which case go use hekate.

fusee.bin works fine locally (and with everyone on discord who has reported using it correctly).

If you want to debug, message me on discord (`SciresM#0524`).
