### ISSUE TITLE
Smash mods problems

### ISSUE THREAD

**Issue by Kacchan2002** [Atmosphere-NX/Atmosphere#1967]
i accidently updated my switch to 15.0.0 & now that i installed the pre release of atmosphere 1.4.0 i cant download mods for smash anymore, do i relly have to wait until the full release is out ?

**Comment by SciresM** [comment]
This is not an atmosphere problem. Talk to whoever makes smash mod stuff.

**Comment by Kacchan2002** [comment]
yes since its with atmoshpere that u can download mods

**Comment by SciresM** [comment]
Atmosphere has no mod downloading logic. Atmosphere is a custom firmware.

I'm locking this.
