### ISSUE TITLE
Panic occurred while running Atmosphere

### ISSUE THREAD

**Issue by codetakki** [Atmosphere-NX/Atmosphere#1969]
### What's the issue you encountered?
I wanted to update to 15.0 firmware. So i updated to latest atmosphere and sigpatches.
(update: replace bootloader and atmos folder on sd card)
After injecting fusse.bin i get the following error:

Panic occurred while running Atmosphere.

Title ID: 4200000000000010
Error: std::abort (0xFFE)

### System Firmware Version

15.0</br>

### Environment?
- bootloader: Fusse
- atmos , 1.4.0
- EmuMMC- file based (unsure)

### Additional context?
N/A

**Comment by zemixe** [comment]
Piracy is not supported.

**Comment by SciresM** [comment]
Remove your custom sysmodule.
