### ISSUE TITLE
Problem when launching Atmosphere

### ISSUE THREAD

**Issue by Crooxy** [Atmosphere-NX/Atmosphere#1971]
## Bug Report

Error code : 2162-0002 (0x4a2)
Program : 0100000000001000
Firmware : 15.0.0 (Atmospĥere 1.4.0-master-36a33617a)

### What's the issue you encountered?

I've updated my Atmosphere recently and now, when I'm launching EmuMMC I got an error message showing up on my screen.

### How can the issue be reproduced?

I don't know

### Crash Report

Everything is show on the picture I link to the post

### System Firmware Version

Atmosphere 1.4.0
Hekate v5.9.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: **Hekate**
- Official release or unofficial build: **I don't know**
- Do you have additional kips or sysmodules you're loading: **I don't think so** 
- Homebrew software installed: **Yes**
- EmuMMC or SysNAND: **EmuMMC**
 
### Additional context?

**Please if you can help me via this post or via discord Crooxy#5803**

Thanks!!

![Switch problem](https://user-images.githubusercontent.com/116129942/196807949-6dcda982-1cd9-4fa6-89a2-b789ca5dfeaa.jpg)

**Comment by SciresM** [comment]
The issue tracker is for bugs, not for support.

delete or update your custom theme.
