### ISSUE TITLE
Force enable dock usb ports while sleeping

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#1973]
## Feature Request

Id like a way to force the system to keep the USB ports awake while the console sleeps in docked mode.  This would allow periferals like the MAGIC NS and such to wake the console from sleep even without the ethernet adapter being used

#### Overview:
The switch currently allows the console to keep the USB ports awake if you connect to the internet via a USB ethernet adapter.  This enables you to wake the console via a USB controller adapter like the magic NS.  
The feature request is to be able to keep it awake without that ethernet adapter. 

#### Smaller Details: 
I dont know any more detailed

#### Nature of Request:  
[ Remove all that do not apply to your request. ]
- Addition

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>
[ Note: **Bolded components are not implemented** or are still at the prototyping phase. ]

### Why would this feature be useful?
To let usb controler adapters wake the console without having an ethernet adapter   This would also allow users to access sys-ftpd while the console is asleep

**Comment by SciresM** [comment]
Sounds like a good idea for a custom sysmodule! I recommend doing the research and writing one to do this, I don't think it makes sense for built in integration in atmosphere.

**Comment by fennectech** [comment]
Could you link to a switchbrew article that shows it worksSent from my iPadOn Oct 20, 2022, at 4:32 PM, SciresM ***@***.***> wrote:﻿
Closed #1973 as completed.

**Comment by SciresM** [comment]
There is no such article. I don't even know how you'd do this. You'll have to do the research.

**Comment by fennectech** [comment]
Found how you’d do it.   https://switchbrew.org/wiki/Network_Interface_services#SetKeptInSleep

**Comment by SciresM** [comment]
Closing, since this is no longer an atmosphere problem. Good luck implementing!
