### ISSUE TITLE
system doesn't fully boot

### ISSUE THREAD

**Issue by Monjgurt** [Atmosphere-NX/Atmosphere#1977]
### What's the issue you encountered?

if i try to boot my switch up after the latest system update it doesn't boot, when it reaches the switch logo an error pops up, it reads as following: "A fatal error occurred when running Atmosphere. Program ID: 010000000000bd00. Error Desc: std::abort() called (0xffe)" the report file is named "report_000000000a4d82dd.bin"
 

### How can the issue be reproduced?

hard to explain, as it seems to only be an issue with my switch

### Crash Report

no report can be found, only the fatal error bin file

### System Firmware Version

15.0.0

### Environment?

i boot via the fusee.bin and i use Atmosphere ver 1.4.0

### Additional context?

[N/A]

**Comment by SciresM** [comment]
Remove/update mission control, not an atmosphere issue.
