### ISSUE TITLE
Crash on boot every time after accidentally updating firmware to 15.0.0

### ISSUE THREAD

**Issue by LazyLux** [Atmosphere-NX/Atmosphere#1978]
My friend accidentally updated my switch to 15.0.0, and so to be able to use smash mods again I had to update both atmosphere and hekate to the newest versions since they're both supposed to support 15.0.0. However, despite following all the directions and trying to solve the problem myself, it still persists and refuses to boot.

I have attached the crash report below. I'm not sure how to interpret it and figure out what the problem is, so hopefully someone could help me.
[01666753360_0100000000001000.log](https://github.com/Atmosphere-NX/Atmosphere/files/9865655/01666753360_0100000000001000.log)

**Comment by SciresM** [comment]
1) you did not use the issue template
2) delete your custom theme
