### ISSUE TITLE
Fatal error on boot up

### ISSUE THREAD

**Issue by yomeny1** [Atmosphere-NX/Atmosphere#1979]
This might be from me accidentally updating my switch trying to run the homebrew menu, but I've updated Atmosphere, Fusee, and Hekate to see if any of them were the issue with no solution.

Program ID is 010000000000bd00
Error Desc is std::abort() called (0xffe)

**Comment by SciresM** [comment]
1) you didn't use the issue templates 
2) update or remove mission control
