### ISSUE TITLE
atmosphere fatal error

### ISSUE THREAD

**Issue by valelisa** [Atmosphere-NX/Atmosphere#1982]
a fatal error occurred when running Atmosphere program id 10041544d530000

report saved to /atmosphere /fatal_error/report_00000000057067r6.bin

what does that mistake mean?and what can I do to solve?

**Comment by tomlinux** [comment]
权限问题。 在mac 操作就会有这个问题。 解决方法如下连接：https://blog.csdn.net/weixin_41108690/article/details/117628189

**Comment by Masamune3210** [comment]
It means you can go back and fill out the issue templates so we can actually try to help you. They arent there just to waste time typing, we need that info to help you correctly in most cases

**Comment by SciresM** [comment]
Closing this, because issue template wasn't filled out and report was never uploaded.
