### ISSUE TITLE
Crash While Running Error Code 2110 0350

### ISSUE THREAD

**Issue by AnthonieZ87** [Atmosphere-NX/Atmosphere#1984]
### What's the issue you encountered?

Seems to occur while running pokemon sword /shield perhaps while integrated with pkhex using the live hex option
but i can't say for certain.  It's happened to me once and honestly, I don't think I was using pkhex at the time but is possible. another person I know who received this error and has gotten it a bunch of times now but hasn't mentioned what they were doing exactly that led to it. I just can't seem to find anything related to that error code and we have been looking everywhere
Crash Error Code 2110 0350 ]</br>
[ No]</br>
[ N/A. ]</br>

### How can the issue be reproduced?
I haven't noticed entirely myself since it only occurred once so far and my friend also states it's kind of at random but has happened to him several times now</br>

### Crash Report
<script src="https://gist.github.com/AnthonieZ87/2d992340ba8fbf181fd265ea4123328d.js"></script></br>
<script src="https://gist.github.com/AnthonieZ87/5af23625af0a8504ff0f60e1c5eebb51.js"></script>

### System Firmware Version
15.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate latest build
- Official release or unofficial build: 

Official hekate v5.9.0 Latest Build
Official Atmosphere Latest build

- Do you have additional kips or sysmodules you're loading: JKSV, FTPD, NXTheme installer, NX-Shell, HP Appstore, Sysbotbase, Ovlmenu
- Homebrew software installed: NO
- EmuMMC or SysNAND: SysNAND

### Additional context?

- Additional info about your environment:
310670396_518729536770801_2489010055462678509_n](https://user-images.githubusercontent.com/84002494/200166461-d19fb54c-ed8b-4bae-9a1e-215c5bfdbbd8.jpg)
I myself and 2 others I know of have been experiencing a crash with the same error.
Nintendo switches error codes for 2110 start at 2110-1000 so I can't find any info related to what is causing it.
[01667761108_010000000000002f.log](https://github.com/Atmosphere-NX/Atmosphere/files/9971374/01667761108_010000000000002f.log)

**Comment by Masamune3210** [comment]
Please go back and fill out the rest of the issue template. The information is asked for a reason

**Comment by Masamune3210** [comment]
Also, you didnt wait long enough for the crash report to upload, please reupload it

**Comment by AnthonieZ87** [comment]
OK I still think I messed up but hoped that helps

**Comment by Masamune3210** [comment]
Just upload the error report as a file, don't stick it in a gist

**Comment by Masamune3210** [comment]
Hmm, 010000000000002F is npns, the service that handles Notifications

**Comment by AnthonieZ87** [comment]
> Just upload the error report as a file, don't stick it in a gist


![Screenshot_20221109-184718_Chrome](https://user-images.githubusercontent.com/84002494/200973081-32cf7f0e-e3b7-498b-87b5-616177be47a5.png)


I did, it’s literally the last line lol

**Comment by Masamune3210** [comment]
You can zip the file and upload it that way

**Comment by SciresM** [comment]
`nifm::ResultResourceNotFound()` -- this isn't an atmosphere issue, it will be arising from whatever custom network stuff you're using.
