### ISSUE TITLE
Cant load in Atmosphere

### ISSUE THREAD

**Issue by ghost** [Atmosphere-NX/Atmosphere#1989]
![PXL_20221110_200934266](https://user-images.githubusercontent.com/117939629/201186144-af415dee-b54c-4169-8376-7f3e2d89ceb3.jpg)
I wanted to install Atmosphere, I did everything according to the instructions, but there was an error. Before that, there was sx os, but I cleared the SD card and there were no files left(official firmware version 11.0.1, don't remember exactly)

**Comment by Masamune3210** [comment]
Go back and actually fill out the issue template

**Comment by Masamune3210** [comment]
Also, orient your picture so people dont have to crane their neck to try to read it

**Comment by mirkavlad228** [comment]
> Вернитесь назад и заполните шаблон задачи

What do you mean?

**Comment by Masamune3210** [comment]
When you first opened the issue, the box was pre-populated with a issue template. It is required, as it lists a bunch of information people need to even begin to try to help you in most cases. Either close this issue and go back and make a new one, correctly filling out the template this time. Or, go open a new issue, copy the template into this issue, and fill it out.

**Comment by mirkavlad228** [comment]
> Когда вы впервые открыли выпуск, поле было предварительно заполнено шаблоном выпуска. Это необходимо, так как в нем перечислено множество информации, которая нужна людям, чтобы даже начать пытаться помочь вам в большинстве случаев. Либо закройте эту тему и вернитесь и создайте новую, на этот раз правильно заполнив шаблон. Или откройте новый выпуск, скопируйте шаблон в этот выпуск и заполните его.

do you need a bug report file?
