### ISSUE TITLE
Error 524850534F53454D

### ISSUE THREAD

**Issue by genjiow2** [Atmosphere-NX/Atmosphere#1991]
[report_000000000073c067.ZIP](https://github.com/Atmosphere-NX/Atmosphere/files/10000434/report_000000000073c067.ZIP)
Trying to load Atmosphere I get an error 524850534F53454D
OFW 15.0.1

**Comment by masagrator** [comment]
Nobody will write to you on DM. 

Use issue template, fill it properly and upload reports here.

Your issue in current form is useless.

**Comment by genjiow2** [comment]
> Nobody will write to you on DM.
> 
> Use issue template, fill it properly and upload reports here.
> 
> Your issue in current form is use
For some reason the file cannot be attached.

**Comment by genjiow2** [comment]
> Nobody will write to you on DM.
> 
> Use issue template, fill it properly and upload reports here.
> 
> Your issue in current form is useless.

For some reason the file cannot be attached.

**Comment by masagrator** [comment]
"For some reason" that is clearly explained?

![image](https://user-images.githubusercontent.com/8557858/201594744-4ad998eb-2f8e-4a9e-8589-3f392a7e08bd.png)

Just zip it.

**Comment by genjiow2** [comment]
> "Почему-то" это понятно объяснено?
> 
> ![изображение](https://user-images.githubusercontent.com/8557858/201594744-4ad998eb-2f8e-4a9e-8589-3f392a7e08bd.png)
> 
> Просто застегните его.

Thank you

**Comment by hexkyz** [comment]
Please fill out the issue template.
