### ISSUE TITLE
A fatal error occurred when running Fusee. Abort called, lr=0x40012b5b

### ISSUE THREAD

**Issue by ARSolution-github** [Atmosphere-NX/Atmosphere#1992]
## Bug Report

I install Hwfly Lite v4.1. I try run Atmosphère with fusee.bin over SX menu and from Hekate menu i get the same error

### How can the issue be reproduced?

On launch  fusee.bin i get A fatal error occurred when running Fusee. Abort called, lr=0x40012b5b screen

![IMG_5840](https://user-images.githubusercontent.com/78070763/201790924-44db4ac3-c399-4ad7-b5d6-1ebe7b1bc959.jpg)

### System Firmware Version

15.0.1 (current), also get the same error on 15.0.0. </br>

### Environment?

Using Atmosphère 1.4.0,  Hekate v5.9.0 & Nyx v1.4.0

### Additional context?

Hekate is working.

![IMG_5841](https://user-images.githubusercontent.com/78070763/201791060-14ce8a9a-2a92-4eba-86a0-09c7111a43f0.jpg)

**Comment by SciresM** [comment]
The relevant abort is incorrect security engine flags in se::ExecuteOperation...I'm at a loss here.

If hekate works, use hekate.
