### ISSUE TITLE
524850534f53454d error Trying to Load Pokémon 

### ISSUE THREAD

**Issue by kinseta** [Atmosphere-NX/Atmosphere#1995]
### What's the issue you encountered?
I recently just downloaded and installed some games. Every-time I try to start them I get a Panic Error, and have to reboot. Everything else on Works Fine, the only problem I’m having is with starting the Games I downloaded from the shop. (Yes I have sig patches etc)
[ Describe the issue in detail and what you were doing beforehand. ]</br> Tried to play a game 
[ Did you make any changes related to Atmosphère itself? ]</br> no
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

15.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: 
  - [ Official release version CURRENT

**Comment by masagrator** [comment]
Piracy is not supported.

**Comment by kinseta** [comment]
Fixed

**Comment by Masamune3210** [comment]
Not even slightly. Piracy is still not supported.

**Comment by kinseta** [comment]
Nah problem on my end is fixed. Lol move round

**Comment by kinseta** [comment]
> Not even slightly. Piracy is still not supported.

It’s my Game goofy
