### ISSUE TITLE
Switch black screen with sound after a few minutes of playing

### ISSUE THREAD

**Issue by Whitesttax** [Atmosphere-NX/Atmosphere#1998]
### What's the issue you encountered?

I get black screen after a few minutes of playing a game, the switch is working fine other than that, with sound and joycon movement. To fix I need to press power, wait a few seconds in sleep mode, then wake the console. This will return image, but it'll happen again soon after.
- I don't get any black screen when playing on sysnand.  (tested exactly the same cartridge)
- So I thought it could be a software issue. I reinstalled everything, created a new emunand, clean install with your package, following a guide. Then it worked, played for a couple days, no problem at all. Then today it started happening again. 

### Crash Report
N/A

### System Firmware Version

15.0.0
AMS 1.4.0|E

### Environment?

Hekate as bootloader, hekate_ctcaer_5.9.0.bin (in bootloader/payloads there's fusee.bin)
Homebrew software installed: battery desync fix nx, hbapp store, daybreak, reboot to payload
emuMMC created on sd, used resizing with NxNandManager_v4.1.1_x64 (just in case it's important)
used clean SD with fat32

edit: heavily testing on sysnand, it happened there as well so it's probably a hardware issue, sorry to take your time

**Comment by Masamune3210** [comment]
Please go back and fill out the issue template correctly
