### ISSUE TITLE
Fatal error occured Kernel Panic

### ISSUE THREAD

**Issue by BladeML** [Atmosphere-NX/Atmosphere#2001]
### What's the issue you encountered?

[ I've been getting an atmosphere crash, not sure what is triggering the issue,  but its always the same message "A fatal error occurred when ruming Atnosphere.
Progran 1D: 524850534f53454d
Error Desc: Kernel Panic (0xf00)]</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
[ Everytime I get the error I replace the atmosphere folder from scratch and the issue keeps on happening]</br>

### How can the issue be reproduced?

[ * ]</br>
[ I've got the issue while installing  dump game cartridges or even while playing more recently]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

15.0.1 System Firmware Version

</br>
</br>

1.4.0 Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 0.5.9
- Official release or unofficial build: 
  - [ Official release version 1.4.0 (or) unofficial build ]
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND: EmuMMC  in a Partition 

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Reach out to me on discord, (SciresM#0524) with the crash report.

Fair warning, though, all kernel fatal errors to date have been caused by the user having bad RAM/hardware.

If stock doesn't boot without atmosphere, there's likely nothing I can do.
