### ISSUE TITLE
Panic Occured while running Atmosphere (another one...)

### ISSUE THREAD

**Issue by ALLZOKU** [Atmosphere-NX/Atmosphere#2003]
Hi ! so heres my issue,

When i try to load atmosphere in sysnand, i have the yellow error message (as you probably know), the : 

"Panic Occured while running Atmosphere.
Title ID : 524850534F53454D
Error : KERNEL (0xF00)"

My sd card (128gb) is in FAT32
![IMG_20221208_124538](https://user-images.githubusercontent.com/34982034/206440025-22e817f6-1d11-4c09-b9b8-173ae2c32a4e.jpg)

i tried two times, but same problem

**Comment by Masamune3210** [comment]
1. Please actually fill out the issue template instead of just deleting it
2. #1994
