### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by svr925** [Atmosphere-NX/Atmosphere#2004]
- The problem

My switch recently had a system update which I had downloaded, then I re-jigged my switch and updated the files for atmosphere, upon booting it crashes.

- Recreation

By updating the system to the latest version, rcm jig again and updating atmosphere and fusee.bin to the latest software and then booting into fusee.bin

- Crash Report

https://gist.github.com/svr925/efc4c63d4a29da9c06a3e44cbd229ffb

- System Firmware Version

15.0.1

- Environment?

What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
Official release or unofficial build: v5.9.0
Do you have additional kips or sysmodules you're loading: N/A
Homebrew software installed: [ Y ]
EmuMMC or SysNAND: N/A

- Additional context?

When I did the RCM Jig again I was using the foil method.

**Comment by Masamune3210** [comment]
Delete your custom theme from the SD card.
