### ISSUE TITLE
exosphere not hiding prodinfo

### ISSUE THREAD

**Issue by supaplexer** [Atmosphere-NX/Atmosphere#2005]
### What's the issue you encountered?

Prodinfo is visible in emummc system settings after enabling option to hide prodinfo.

### How can the issue be reproduced?

Set the option to blank prodinfo emummc to 1 in exosphere.ini and make sure it's in /atmosphere/config. Boot to emuMMC and check serial numbers in system settings. Your original serial shows up.

### Crash Report

N/A

### System Firmware Version

15.0.1

### Environment?

Hekate 5.9.0 booting CFW EmuMMC with Atmosphere 1.4.0.

### Additional context?

Was working just fine on 1.2.5 and firmware 13.2.0. Issue started After updating firmware to 15.0.1 and AMS to 1.4.0

**Comment by masagrator** [comment]
Because exosphere.ini should be on root of sdcard and is like that for a long time.
