### ISSUE TITLE
emuMMC won't load with basic setup

### ISSUE THREAD

**Issue by SeanPerras** [Atmosphere-NX/Atmosphere#2006]
Hekate: 5.9.0, Atmosphere: 1.4.0
System FW: 13.2.1

I just followed [this guide](https://switch.homebrew.guide/hacking/fuseegelee/sdsetup)  to initially setup Atmosphere a couple weeks ago so everything is up to date (I assume). I've been using sysMMC, since, with no issues. I just tried to setup emuMMC from the [end of that guide](https://switch.homebrew.guide/emummc/emummc)  2 days ago and it loads up to the Switch logo and it sits at a back-lit black screen.

I formatted a 128Gb sd card as FAT32 for Atmosphere and partitioned ~30Gb for the emuMMC. I apologize if this has been asked or I'm asking the wrong Hub; I looked for my specific issue in Issues here and the Hub for emuMMC, but couldn't find it.

Please let me know what other info you need from me, if any.

**Comment by SciresM** [comment]
I would open the issue on the emummc repo. This sounds like a support issue, btw, and the ams issue tracker is for bugs, not for support. You can also try to get support on discord.
