### ISSUE TITLE
A fatal error occurred when running Fusée. Abort called, lr=0x40012b5b

### ISSUE THREAD

**Issue by ClementNerma** [Atmosphere-NX/Atmosphere#2010]
Hi!

I tried installing Atmosphere on a Switch Lite (which has a SX Lite chip) and I get the following error message on boot:

```
A fatal error occurred when running Fusée.
Abort called, lr=0x40012b5b

Press POWER to reboot.
```

The boot process is SX OS boot menu => Payloads => "hekate.bin" => Payloads => "fusee.bin"
And then I get this error.

I don't get why, and I haven't found any help online. Do you have any idea of what could be causing this?

Thanks in advance for your help!

**Comment by SciresM** [comment]
Security Engine operation execution is failing --> that sounds like a hardware issue to me. If you can boot via hekate or stock, use those I guess, but yeah.

**Comment by ClementNerma** [comment]
I ended up using another method from a video that was provided to me on a forum (https://youtu.be/mH8osmtPFlA) as my Switch Lite was fully bricked (in case someone else needs this :) )
