### ISSUE TITLE
Switch do not charge in cfw (emummc) 

### ISSUE THREAD

**Issue by CarlosGamer98YT** [Atmosphere-NX/Atmosphere#2011]
Well like the tittle says i have this switch that do not charge in the cfw mode in emunand, i dont know if work in sysnand but it works y ofw, if i connect the same cable to another switch it charges but if i connect the hacked switch to a dock its charges but do not charges with a simple cable that have 5 volts (connected to electricity)

**Comment by SciresM** [comment]
1) you didn't use the issue templates 
2) this is pretty much definitely a user config or hardware issue.
