### ISSUE TITLE
Daybreak - Delete 0100000000001000 folder if exists during update

### ISSUE THREAD

**Issue by pekempy** [Atmosphere-NX/Atmosphere#2017]
#### Overview:
- Delete contents/0100000000001000 folder if it exists before rebooting to prevent custom Horizon themes from crashing switch

#### Nature of Request:  

- Addition
  - After performing a successful update within Daybreak, automatically delete contents/0100000000001000 prior to rebooting console.

### What component do you feel this would best fit within?
- [**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)(I think, searched the Repo for Daybreak but didn't find much)

### Why would this feature be useful?
- A large number of users regularly get stuck after system update and ask for help on Reddit, Discords etc.     
- The folder will _always_ need to be deleted after an OS update, so automatically removing it if it exists wouldn't cause any issues.     
- Would reduce user confusion/users incorrectly blaming Atmosphere

**Comment by SciresM** [comment]
I am not going to delete people's themes for them. And it doesn't need to be deleted, if people have updated their themes for the new OS.
