### ISSUE TITLE
Fatal error while running Fusee

### ISSUE THREAD

**Issue by rezzarr** [Atmosphere-NX/Atmosphere#2018]
## Bug Report

Hi folks, I was just updating my switch to FW 15.0.1. And wanted to update the CFW as well. Unfortunately, Atmosphere no longer works since the update. First I had the problem (0xffe) which I fixed afterwards. Then I uploaded a new fusee file where it said at the first launch that the fusee primary was missing. I then used another payload from Atmosphere and Hekate which was only called Fusee. As a result, Atmosphere crashed again and again with the error code "a fatal error occurred while running Fusee. Incorrect version (program=0xd40bf51f, mtc=0xb6b6ac70. But I have the latest version of Fusee in the folder and I have updated all the other folders like Atmosphere and Hekate. And there is nothing in the Atmosphere Content folder either. 

Please help, thank you.

**Comment by SciresM** [comment]
1) You didn't fill out the issue templates
2) This is user error, you need to update the fusee payload you're running and the atmosphere package3 on your SD card to be from the same version.
