### ISSUE TITLE
fs mitm causes some games to crash upon launch

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Atmosphere-NX/Atmosphere#202]
for example, the messanger is one that i know of.

**Comment by bakugo** [comment]
It also causes some older games to crash if you have many files.

For example, simply extracting Splatoon 2's entire romfs and applying it back with layeredfs (no updates or dlc installed) will cause it to crash on startup.

**Comment by SciresM** [comment]
Yeah, this is because fs.mitm doesn't use domains at present. It's planned for the future but a lot of work.

**Comment by duckbill007** [comment]
Also games can not start if there are 8 or more DLC installed.

**Comment by ThatNerdyPikachu** [comment]
we probably could, yeah

**Comment by fennectech** [comment]
MITM causes the bedrock Minecraft to crush.

**Comment by duckbill007** [comment]
And if this can be configured through text file (I mean tid list) it can be perfect solution for now.

**Comment by AnalogMan151** [comment]
Actually, a better work around would be just to not activate LayeredFS if there's no mods present on the SD card. Example tested and working here: https://github.com/Reisyukaku/NX_Sysmodules/blob/3c12add04883b893698cfa04451c834e34bcbe66/fs_mitm/source/fsmitm_service.hpp#L24-L33

**Comment by fennectech** [comment]
This is even better!
