### ISSUE TITLE
Screen stays Black while boot-up (AMS 1.4.1)

### ISSUE THREAD

**Issue by neomhor** [Atmosphere-NX/Atmosphere#2023]
### What's the issue you encountered?

Updated AMS fom 1.4.0 to 1.4.1
While booting up the Switch, the AMS Logos appear but the Switch Logo doesn't.
Screen stays black, Switch has to be turned off hard.
Falling back to AMS 1.4.0, everything works fne again

### How can the issue be reproduced?

N/A

### Crash Report

No report was created

### System Firmware Version

15.0.1

### Environment?

- Tried Fusee and Hekate
- Official release
  - AMS 1.4.1, Hekarte 6.0.1
- additional kips or sysmodules: don't know
- Homebrew software installed: [ * ]
- EmuMMC  on partition
- - 

### Additional context?

N/A

**Comment by SciresM** [comment]
Just leave it like that for a little while, that's actually kind of expected, as a one-time thing. See the release notes.

Alternatively, delete the atmosphere/erpt_reports folder manually from your PC.

If the issue continues after doing that, re-open.
