### ISSUE TITLE
Atmosphere Error 0100000000000002b

### ISSUE THREAD

**Issue by Tbryan4** [Atmosphere-NX/Atmosphere#2024]
Hello,

I recently got my Nintendo Switch fixed at a repair shop because the fan was not working. After they fixed it I tested my switch in CFW and my switch would constantly crash with the atmosphere error code 2002-3502. After some research, I figured out that it was an SD card reader issue. I went back to the repair shop and told them that they broke the sd card board while trying to replace the fan and they fixed it. After I got my switch back I tried to load up Atmosphere and I got a new error

ProgramID: 010000000000002B
Error Desc: std::abort() called (0xffe)

Now I can't load into CFW at all and I have no idea on how to fix it. I have read multiple forums about this issue but none of them have a conclusive answer on how to fix this issue.

**Comment by SciresM** [comment]
You did not use the issue template. Please re-open with the issue template filled out, and especially please upload the report generated by your crash. The filename will be visible when the screen tells you it crashes.
