### ISSUE TITLE
Atmosphere 1.4.1 crashes a LOT of games

### ISSUE THREAD

**Issue by heyjeyS** [Atmosphere-NX/Atmosphere#2026]
Hello! i had to create a new account just to report this since im not seeing any..
but after installing Atmosphere 1.4.1 , a LOT of games such as FE Three Houses, Skyward Sword, Hollow Knight, Mario All Stars, DQ Builders 2  , from what i tested ALL crash and say the game cannot run.  I thought it was Atmosphere mods in Three Houses and Skyward swords, but i removed mods there and nothing.  Hollow Knight, Mario etc on my Switch have no mods...

Message says : "Could not start software , please try again from Home menu".   (sorry i dont know how to attach screenshots on github)

Some other games like Astral Chain, FE Engage (not surprisingly- even with the mods) do work well on 1.4.1 .. so im not sure what's going on with all the others.

I did update Fusee as well as instructed.  After testing and failing , i reverted back to 1.4.0 that i had and everything works just like before.  
Please if this can be addressed/ fixed.  Thanks!

**Comment by SciresM** [comment]
1) you did not use the issue templates
2) This reads to me like pretty classic piracy, and piracy is not supported. 

Re-download any legitimate purchases from the e-Shop, they should still work that way.
