### ISSUE TITLE
Crash when initializing console in EMUnand

### ISSUE THREAD

**Issue by pmnlla** [Atmosphere-NX/Atmosphere#2027]
### What's the issue you encountered?

When I initialize my console (without deleting user data) through the maintenance mode on emunand, the OS crashes with error code 2005-0005.

### How can the issue be reproduced?

Ensure you have the latest firmware and AMS. 

Boot to emunand while holding down both the volume buttons.

Select "Initialize without deleting save data", or an option along the lines of.

Go through with the initialization.

### Crash Report

Will upload later

### System Firmware Version

15.0.1
### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build:  Official
- Do you have additional kips or sysmodules you're loading: Teknik kips, missioncontrol, sys-clk, sysdvr
- Homebrew software installed: Inapplicable 
- EmuMMC or SysNAND: Partition based EmuMMC

**Comment by SciresM** [comment]
This is a known issue in emummc, it's not actually an atmosphere issue.

**Comment by pmnlla** [comment]
Good to know. Is it possible to still use the initialization function on emunand?

**Comment by SciresM** [comment]
I'm not aware of any workaround for initialize failure in emummc, though it doesn't always happen.

**Comment by SciresM** [comment]
fwiw, if you're getting a true fatal report (a binary report in the fatal_errors folder), you're welcome to upload it and I will look at it, but I wouldn't expect any resolution.
