### ISSUE TITLE
Kirby and the Forgotten Land cant be played in ATS 1.4.1

### ISSUE THREAD

**Issue by jagurxe** [Atmosphere-NX/Atmosphere#2028]
## Bug Report

i use a switch 1.0 whitout patch, hekate 6.0.1 abn firmware 15.0.1, I updated the switch with Atmosphère 1.4.1 a few days ago, I was using version 1.4.0 and I was playing the Kirby Forgotten Land game with my son, no game gave me a problem in 1.4.0, but I updated to 1.4.1, and I launched the game and it didn't come in, it just told me to launch it from the menu, it was the only game that gave me an error, download sigpatches, change them, uninstall the game, download it again and nothing, then I changed to Atmosphère 1.4.0 As the last option and it worked as always. I hope you check that, regards

**Comment by SciresM** [comment]
Piracy is not supported. Try redownloading the game from the eshop.
