### ISSUE TITLE
Panic occurred while running Atmosphere: Title ID 010000000000002B (again)

### ISSUE THREAD

**Issue by pintcat** [Atmosphere-NX/Atmosphere#2029]
### What's the issue you encountered?

emuMMC stops loading right after the Atmosphere splash screen with this notorious error message...

Panic occurred while running Atmosphere:
Title ID: 010000000000002B
Error: std::abort (0xFFE)

### How can the issue be reproduced?

At first I start Hekate (using the RCMloader device) and from there I start Atmosphere either by script or by payload. It happens every time.

### Crash Report

[report_087eb780.zip](https://github.com/Atmosphere-NX/Atmosphere/files/10575057/report_087eb780.zip)

### System Firmware Version

15.0.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 6.0.1
- Official release or unofficial build: Official release 1.4.1 (it first appeared with 1.4.0; update didn't help)
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: daybreak, dbi, ftpd, Goldleaf, NX-Shell, reboot_to_payload, Switch_90DNS_tester, Awoo-Installer, retroarch_switch, vgedit
- EmuMMC or SysNAND: emuMMC partition-based

### Additional context?

I tried several (if not all) suggestions I could find (except setting all up from scratch), but nothing helped. Despite the familiar error message, this might be a new issue.
This whole thing came out of nowhere. One day I was suddenly unable to start any game. When I tried to reboot the Switch this error appeared.

**Comment by SciresM** [comment]
You have a corrupt PRODINFO/system settings save.

Follow the instructions/directions in https://github.com/Atmosphere-NX/Atmosphere/issues/1256 for guidance. You'll need to restore a non-corrupt backup and/or delete the system settings savedata.
