### ISSUE TITLE
warmboot not working

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Atmosphere-NX/Atmosphere#203]
as of https://github.com/Atmosphere-NX/Atmosphere/commit/fa0e9061299eff22095923125ba82ca118e2b5d2, warmboot on 5.1.0 has stopped working for some reason.

**Comment by SciresM** [comment]
Are you sure you're setting target firmware appropriately?

In particular, I changed the default firmware from 5.x to 6.x. See [here](https://github.com/Atmosphere-NX/Atmosphere/commit/fa0e9061299eff22095923125ba82ca118e2b5d2#diff-a0b3c028118b80a8a9b1f9bcac5fd95cR38).

This firmware value affects the warmboot security magic number.

**Comment by ThatNerdyPikachu** [comment]
hekate master: nope 🤔

**Comment by ThatNerdyPikachu** [comment]
this now seems to just be an issue with hekate, is it not setting target fw correctly?
(works fine on fusee^^)

**Comment by thedax** [comment]
Also unable to reproduce with hekate 4.0/latest hekate master.
