### ISSUE TITLE
Smash Ultimate Crashing

### ISSUE THREAD

**Issue by MikeyProHD** [Atmosphere-NX/Atmosphere#2030]
Smash Ultimate Crashing

I was adding mods to Smash Ultimate but I think I added too many and my game crashed.

I was just dragging and dropping mods over to my SD card  like I usually do and the game crashed
I didn't make any changes to Atmosphere

The issue can most likely be reproduced by adding a bunch of mods (Not sure in terms of GB storage) and see if the game will crash or not

The process is pretty much just adding a bunch of mods to your SD card and seeing what will happen in terms of crashing

Crash Report below

Link to the gist: https://gist.github.com/MikeyProHD/3d9d6cb750d537e91b33be4c52d88782

### Switch ver 15.0.1

15.0.1

Atmosphere ver 1.4.1

### Bootloader was fusee
No additional kips or sysmodules
SysNAND

**Comment by SciresM** [comment]
This isn't an atmosphere issue. "User break" = smash encountered an error, probably due to your mods. Talk to the mod developers.
