### ISSUE TITLE
Game "The Great Ace Attorney Chronicles" crash while using layeredFS

### ISSUE THREAD

**Issue by GachaFan** [Atmosphere-NX/Atmosphere#2035]
I use layeredFS/atmosphere with Yuzu emulator and while i modify the game with layeredFS, the game crash (even when I replace with the original files)

(and he's not crashing with the other game that play with yuzu)

**Comment by SciresM** [comment]
1) You did not use the issue templates
2) A crash occurring in yuzu is not relevant to atmosphere.
