### ISSUE TITLE
Got Error Code 2162-0002 on a XAK1000052XXXX console which bought in Taiwan

### ISSUE THREAD

**Issue by jnxfzhzx** [Atmosphere-NX/Atmosphere#204]
![20180916232207](https://user-images.githubusercontent.com/36022364/45602705-4c4e8180-ba55-11e8-8020-0aafec5ca4ae.jpg)
After I enter Atmospherer CFW and press A to unlock console , the error show up.
I bought this console in 2017.12 and any method to solve the problem?
I also tried to boot in TX OS , it works ,no Error , but no response when I click the Album.

**Comment by Resaec** [comment]
Hurry up and shorten your SerialNr. Also remove it from the picture.
Why do you post this online?

**Comment by noirscape** [comment]
@Resaec - Switch bans aren't issued with the serial number, they're issued
through console specific data. Merely posting a serial number online isn't
dangerous afaik.

As to why he posted this: Maybe it's to... oh I don't know: submit a bug
report to the issue tracker?

**Comment by jnxfzhzx** [comment]
@Resaec OK , I have changed the content as you suggested . But , how to solve this problem?

**Comment by jnxfzhzx** [comment]
@noirscape Yes , I want to know how to solve this problem.

**Comment by hexkyz** [comment]
This is a general crash error that is often triggered by installed applications and not by the CFW itself. Have you tried a factory reset?

**Comment by jnxfzhzx** [comment]
@hexkyz I solve this problem by upgrade tf card when the system promt a request. Thanks all.
