### ISSUE TITLE
1.5.0 Prerelease bug report

### ISSUE THREAD

**Issue by ElementalTJ** [Atmosphere-NX/Atmosphere#2040]
## Bug Report
</br>
### What's the issue you encountered?

</br>
Crashing while trying to boot.
</br>
Updated to Atmosphere 1.5.0
</br>
Updated Switch to 16.0.0
</br>
### How can the issue be reproduced?
</br>
Use SX RCM Loader to boot Hekate.
Load fusee.bin
See Atmosphere logo, see Switch logo.
See crash.
</br>
### Crash Report

</br>
https://drive.google.com/file/d/1ft0JECzz5sXEPRgWxS8EAtIqv0sg6odI/view?usp=sharing
</br>
(report_0000000009417712.bin found in fatal_error folder)
</br>

### System Firmware Version

16.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
fusee.bin using hekate

- Official release or unofficial build: 
  prerelease build
- Do you have additional kips or sysmodules you're loading:
none
- Homebrew software installed:
'HATS'
- EmuMMC or SysNAND:
SysNAND, FAT32 

### Additional context?
</br>
A fatal error occurred when running Atmosphere.
</br>
Program ID: 010000000000bd00
</br>
Error Desc: std:abort() called (0xffe)
</br>
</br>
- Additional info about your environment:</br>
Hope this helps development. Thanks!
</br>
</br>
Edit: Fixed by deleting atmosphere/content items.
Thanks all

**Comment by shae23** [comment]
010000000000bd00 is the folder for Mission Control located in atmosphere/contents. Delete that folder and you should be good. Though it goes to say, Mission Control will no longer work.

**Comment by BKING1992** [comment]
![WhatsApp Image 2023-02-24 at 02 03 59](https://user-images.githubusercontent.com/126193604/220991998-43fb29fe-24a5-4ba8-b0a0-f1b084f575f5.jpg)

**Comment by masagrator** [comment]
All tesla overlays require update.

This will solve your crash issue at boot 
https://github.com/ELY3M/Tesla-Menu/releases/

**Comment by BKING1992** [comment]
> masagrator

Thanks , solve the first problem . but get another error came again.
![Uploading WhatsApp Image 2023-02-24 at 02.11.38.jpg…]()

**Comment by BKING1992** [comment]
> > masagrator
> 
> Thanks , solve the first problem . but get another error came again. ![WhatsApp Image 2023-02-24 at 02 11 38](https://user-images.githubusercontent.com/126193604/220994239-115eb071-9b61-4748-8123-c6730dcbeded.jpg)

solve the problem after deleted 0100000000001000 folder , working fine now. thanks only themes missing for now
