### ISSUE TITLE
atmosphere/fatal_error/report_047614a46.bin

### ISSUE THREAD

**Issue by reual1** [Atmosphere-NX/Atmosphere#2046]
I was trying to play my Game and than this happend
Panic occured while running Atmosphere.

Title ID:010041544D530000
Error:std::abort (0XFFE)

Report saved to/atmosphere/fatal_error/report_047614a46.bin

Press Power to continue:

Can pls someone help me

sry for my english

**Comment by SciresM** [comment]
You did not use the issue templates, and did not upload the file.

Additionally, the issue tracker is for bugs, not support requests -- you may wish to try discord first.
