### ISSUE TITLE
1.5.0 Pre-release

### ISSUE THREAD

**Issue by PixieDustDGE** [Atmosphere-NX/Atmosphere#2047]
Gets stuck on Switch logo screen when booting. Attempted to put in a clean atmosphere folder and it does the same thing. Copying files from sd card mounted on pc then using tegrarcmgui to launch.

**Comment by Left-Humor** [comment]
So when can release?

**Comment by Left-Humor** [comment]
So when can it be officially released?

**Comment by XModxGodX** [comment]
I had the same issue but figured out that I needed to delete some outdated folders that effect system files in content and possibly some exefs patches for the system menu. Basically delete any folder in 'contents' that you don't recognize the contents of.

**Comment by PixieDustDGE** [comment]
> I had the same issue but figured out that I needed to delete some outdated folders that effect system files in content and possibly some exefs patches for the system menu. Basically delete any folder in 'contents' that you don't recognize the contents of.

I just deleted contents. The problem persists. Unless there's something I need in contents?

**Comment by XModxGodX** [comment]
You might need to delete 'exefs_patches' as well if you have one.

**Comment by PixieDustDGE** [comment]
I have deleted both and still have the problem...

**Comment by XModxGodX** [comment]
Only other solution I can think of now is to delete the entire 'Atmosphere' folder and then copy the folder with the same name from the prerelease.

**Comment by PixieDustDGE** [comment]
I'm screwed

**Comment by ELY3M** [comment]
I only have sysDVR / sys-ftpd / tesla / sysbot-base  in my contents   I am fully updated to 16  
atmosphere have been slow booting and I was stuck on switch logo screen for like one min or so.  
on my other switch fully updated to 16 too - same setup but fast booting up.

**Comment by ELY3M** [comment]
might wait for few mins and see if atmosphere boot up.

**Comment by ELY3M** [comment]
I am using emummc as SD partition.   are you using emummc?

**Comment by Masamune3210** [comment]
This isn't a support forum, nor is it a chat thread. Please go figure out your issues somewhere else. Once you narrow down the issue, you can follow the steps to make a issue report

**Comment by SciresM** [comment]
You didn't use the issue templates, also.
