### ISSUE TITLE
New Atmosphere Updated Won't Boot

### ISSUE THREAD

**Issue by Ballistikun** [Atmosphere-NX/Atmosphere#2051]
### What's the issue you encountered?

</br>
1 - I updated Atmosphere after after updating my switch's OFW, and now when I try to boot through Hekate, it tells me</br>
Unknown PK91 version.</br>
HOS version not supported!</br>
Trying to Backup bootloader...</br>
Found PK91 ('20230111100014').</br>
Unknown PK91 version.</br>
HOS version not supported!</br>
Failed to launch HOS!</br>
Press any key...</br>

2 - If I try to boot through fusee instead, I get the standard atmosphere crash screen with the error code 2001-0123

### How can the issue be reproduced?
1:</br>
Boot switch into RCM</br>
Inject Hekate 6.0.1 using TegraRCM</br>
Press Launch</br>
Press CFW (sysMMC)</br>

2:</br>
Same as before, but instead of pressing CFW, Press fusee

### Crash Report

I have no crash reports. but I have attached a fatal report that was made at the same time as the Issue</br>
NX/Atmosphere/files/10832087/01677352577_420000000007e51a.log)</br>

### System Firmware Version

16.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: 
[01677352577_420000000007e51a.log](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.5.0-prerelease

- Do you have additional kips or sysmodules you're loading: I have the overlays: ovlmenu, ovlSysmodules, Status-Monitor-Overlay, sys-clk-overlay,sysdvr-overlay,sys-tune-overlay.
- Homebrew software installed: Breeze, EdiZon, Ftpd. Ftpd-classic, Goldleaf, Nxdumptool, Switch themes installer, ThemezerNX
- EmuMMC or SysNAND: Sysnand

### Additional context?

- Additional info about your environment: 
- 1:
![20230225_132756](https://user-images.githubusercontent.com/98759810/221376312-b12b76e0-4362-4327-96a0-d6e1ffd864df.jpg)
- 2:
- ![20230225_132826](https://user-images.githubusercontent.com/98759810/221376311-0e56f410-ae03-4ae1-89e6-a164466cb8b6.jpg)

**Comment by SciresM** [comment]
Update your hekate, this isn't an atmosphere issue.

the second screenshot is Tesla crashing, remove or update Tesla...
