### ISSUE TITLE
2168-0002 (0x4a8) Error on Nintendo Switch after trying to install games through DBI

### ISSUE THREAD

**Issue by Ana2266** [Atmosphere-NX/Atmosphere#2053]
This happens every time I try to install a game through DBI, on the pc.
I copy the game folder to the switch and then this screen appears.

![20230227_155344](https://user-images.githubusercontent.com/126515551/221668682-c6b93a9b-cb31-43f9-8f25-5503e34e9fd3.jpg)

This problem has been occurring after I have updated to the new firmware version 16.0.0

Firmware: 16.0.0 (Atmosphere 1.5.0-master-356d89244)

**Comment by SciresM** [comment]
Piracy isn't supported.
