### ISSUE TITLE
2168-0002 (0x4a8) error on switch

### ISSUE THREAD

**Issue by Ana2266** [Atmosphere-NX/Atmosphere#2054]
This problem has been occurring after I have updated to the new firmware version 16.0.0

![20230227_155344.jpg](https://user-images.githubusercontent.com/126515551/221676869-52526be0-6b1a-45aa-ae70-f128f1c0224a.jpg)

Firmware: 16.0.0 (Atmosphere 1.5.0-master-356d89244)

**Comment by SciresM** [comment]
Piracy is not supported.
