### ISSUE TITLE
Atmosphere Hangs At Switch Logo

### ISSUE THREAD

**Issue by PixieDustDGE** [Atmosphere-NX/Atmosphere#2056]
### What's the issue you encountered?

Atmosphere hangs at the Switch logo

### How can the issue be reproduced?

Launch Atmosphere with Fusee

### Crash Report

N/A

### System Firmware Version

16.0.0

### Environment?

Fusee, Official

### Additional context?

Contents folder was deleted, replaced all necessary folders with clean versions. I've launched via TegraRcmGUI and Hekate.

**Comment by SciresM** [comment]
You did not include all the relevant information requested by the issue report, for example e.g. emummc status. Is this issue occurring on an emummc, and if so what kind? Does it occur on sysmmc if occurring on emummc, or emummc if sysmmc? Does the issue occur with file-based if partition-based?
