### ISSUE TITLE
Error code 2001-0123 0xf601

### ISSUE THREAD

**Issue by Minecraftplayer20** [Atmosphere-NX/Atmosphere#2065]
Program: 420000000007E51A
Firmware: 16.0.0 (Atmosphere 1.5.0-master-356d89244)

I got the latest version of hekate atmosphere and sdsetup plus fusee and I did the whole thing again and the same thing happened

**Comment by masagrator** [comment]
1. You did not use issue template.
2. You did not update Tesla Menu. This is not an atmosphere issue.
