### ISSUE TITLE
Time system does not work correctly

### ISSUE THREAD

**Issue by manolo754** [Atmosphere-NX/Atmosphere#2069]
Time system does not work correctly

I started Twitch app and the app has a time certificate error.
You can be reproduced error starting Twitch app.
If you have time system automatic, the hour and the date it is not correct.
System Firmware Version: 16.0.0
Atmosphere version: 1.5.0 pre-release
Bootloader: hekate v6.0.2
   Do you have additional kips or sysmodules you're loading: yes
- Homebrew software installed: [ some applicattions ]
- EmuMMC partition-based

**Comment by masagrator** [comment]
> Do you have additional kips or sysmodules you're loading: yes

That's actually pretty important to list them all. Atmosphere doesn't touch time sysmodule, so whatever happens should not be related to Atmosphere itself.
And question - does it work with OFW correctly?

**Comment by Masamune3210** [comment]
There is a reason the template is there, generalizing what kips and homebrew you have as "yes" and "some applications" helps absolutely no one

**Comment by ELY3M** [comment]
I have zero issues with twitch and I am online in atmosphere.  My switch clock is always synced.   
I downloaded twitch from e-shop as normally.

**Comment by happywolf** [comment]
> 
I'm surprised you manage to get 1.5.0 pre-release working at all o.o

**Comment by happywolf** [comment]
> Time system does not work correctly
> 
> I started Twitch app and the app has a time certificate error. You can be reproduced error starting Twitch app. If you have time system automatic, the hour and the date it is not correct. System Firmware Version: 16.0.0 Atmosphere version: 1.5.0 pre-release Bootloader: hekate v6.0.2 Do you have additional kips or sysmodules you're loading: yes
> 
>     * Homebrew software installed: [ some applicattions ]
> 
>     * EmuMMC partition-based

I'm surprised you even got the pre-release to work at all :o

**Comment by SciresM** [comment]
Closing this because of lack of info.
