### ISSUE TITLE
Holding HOME button "UI" gets laggy and unusable.

### ISSUE THREAD

**Issue by vegedb** [Atmosphere-NX/Atmosphere#2070]
## Bug Report
Holding HOME button "UI" gets laggy and unusable. 
(Quick settings UI)
(Power Off UI)

### What's the issue you encountered?
1) Holding HOME button "UI" gets laggy and unusable.
2) This only happens during fresh boot.
3) Doesn't happen always so replication is hit or miss, but it hits more than it misses.

To note! This lag is fixed after any game is launched, so its not a big deal, but you might wanna explore it.

### Environment?

Switch OLED 16.0 emuNAND w/ latest hekate/Atmosphere/sigpatches
No plugins installed.

**Comment by SciresM** [comment]
1) piracy is not supported
2) I don't think atmosphere has literally any impact on these menus, since they're rendered by Nintendo code and we don't do any graphics stuff.

Closing, since I don't really know how ams could be involved with this.
