### ISSUE TITLE
Atmosphere 15.0 boot error 2991-0123 (0xF1601)

### ISSUE THREAD

**Issue by faerghast** [Atmosphere-NX/Atmosphere#2071]
### What's the issue you encountered?

Recently had to update my switch and tried to update Atmosphere's pre-release 15.0 version. Did what I usually do in taking the folder contents and updating my SD card. I also used the updated fusee payload. All seemed like I was going normal. 

[01678333844_0100000000000045.log](https://github.com/Atmosphere-NX/Atmosphere/files/10927836/01678333844_0100000000000045.log)

[ Crash reports can be found 
![541a22a5daa71b6e1a76b24a11b597e3](https://user-images.githubusercontent.com/58541944/223918729-038bfb59-f32f-4b32-98dc-a8ad9945f6c2.png)
under ``/atmosphere/crash_reports``. ]</br>

The atmosphere logo pops up like normal, everything seems OK until after the Nintendo Switch logo/animation plays, until the crash screen appears. It seems like nothing is getting booted up with all the 0s?

### Environment?

I'm injecting the fusee payload that came with 15.0. Not sure if I made a mistake replacing the atmosphere folders. Its been a while since I updated my Atmosphere but maybe this helps?

![4256bf7686e41d1508aed9793ee98e2a](https://user-images.githubusercontent.com/58541944/223919357-e6f7366a-ba45-4851-931d-d83db5096b3c.png)

![747c484d71015f7ed388ffcd3189d9a0](https://user-images.githubusercontent.com/58541944/223919369-edfe97ae-ab1d-48d1-855b-adf167a2f624.png)

**Comment by Coxxs** [comment]
You need to update all Tesla menu `.overlays` to 16.0.0
