### ISSUE TITLE
Error 0x4A8 (2168-0002). Help required =)

### ISSUE THREAD

**Issue by SigfridoGaming** [Atmosphere-NX/Atmosphere#2072]
Hello there, today I wanted to use a Game Boy Advance emulator "VBA-Next" I followed a tutorial and all seemed fine until i got to the booting part, when I tried to boot it up it crashed, and i thought it was ok, I tried again and it still crashed, then i tried to boot it up with the "Album Version" of the homebrew menu (Before I used to open a game and hold R) and it gave me the crash error, I tried deleting the Atmosphere folder from my SD card but it still gave me the error. Have you got some tip to fix this problem? Thanks in advance =)

Here is the crash report
[01678480665_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/10945987/01678480665_010000000000100d.log)

**Comment by SciresM** [comment]
1) you didn't use the issue templates
2) this is an issue with the homebrew you're running, not with atmosphere.

I recommend speaking to whoever made the port you're using.
