### ISSUE TITLE
Bootloop!?

### ISSUE THREAD

**Issue by SAB236YT** [Atmosphere-NX/Atmosphere#2073]
## Bug Report

Bug Report</br>
</br>

*</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

I've got a bootloop, i think. </br>
Because i deleted some contents witch i dont remember and got this. I also re-installed it</br>
Said it. up there.</br>

### How can the issue be reproduced?

Um. Booting it?-</br>
DELETE CONTENT</br>

### Crash Report

How? it does not report</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version
Latest</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - Official release
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: Goldleaf, retroarch. also Tesla.
- EmuMMC or SysNAND:
  - SysNAND

### Additional context?

- Additional info about your environment:
- Its bootloop is on the nintendo switch logo. not on the atmosphere one

**Comment by SciresM** [comment]
There is nowhere near enough info. Also, this is going to be a user setup problem and not ab ams bug, and the issue tracker is for bugs, not support. Seek help on discord.
