### ISSUE TITLE
Fatal Error running Fusee.bin

### ISSUE THREAD

**Issue by ggdpp** [Atmosphere-NX/Atmosphere#2074]
### What's the issue you encountered?

When attempting to inject Fusee.bin I receive the following error message:

A fatal error occurred when running Atmosphère.
Program ID: 010041544d530000
Error Desc: std::abort() called (Oxffe)
Failed to save report to the SD card! (00165802)

### How can the issue be reproduced?

Let the battery drain while in CFW on microSD. After recharging the battery, inject fusee.bin over USB

### Crash Report

https://gist.github.com/ggdpp/7b39a1bb37fe6f222cd8bea6902f25d0

### System Firmware Version

1.4.1

### Environment?

- What bootloader was Atmosphère launched by: fusee
- Official release or unofficial build: 
  - Official release version 1.4.1
- Do you have additional kips or sysmodules you're loading: I don't think so
- Homebrew software installed: Checkpoint, Daybreak, DBI, JKSV, Lockpick, MissionControl, NXDumpTool, sys-con, TinFoil, TinLeaf,
- EmuMMC, partioned

### Additional context?

-Injecting from a Mac: ns-uploader
-no custom themes
-tried finding a folder with same Program ID in atmosphere/contents. It was not there
-tried running Unset archive bit, did not resolve

**Comment by SciresM** [comment]
The report you linked is unrelated to the message you describe. The report for the message you describe would be a binary file, not a human-readable txt.

Also, ah, "tinfoil/tinleaf/dbi". Piracy is not supported.
