### ISSUE TITLE
Implement switch lite hdmi output to tv

### ISSUE THREAD

**Issue by ryan1109** [Atmosphere-NX/Atmosphere#2075]
It's very interesting to make the Switch Lite output HDMI video through a dock. 

Currently, I have a hardware solution where I can connect several sets of signal lines, but it seems that the HOS has restrictions on different models, blocking DP and HDMI output functions. 

According to the manual, there should be restrictions in the NV service or display service. I need help and want to research this together with everyone.

**Comment by SciresM** [comment]
1) you didn't use the issue templates 
2) I personally don't have interest in this. 

I certainly invite you to try to organize community research, but that's not what the atmosphere issue tracker is for.
