### ISSUE TITLE
Custom NSP forwarders broken with 1.5.1

### ISSUE THREAD

**Issue by PiranhaMayhem** [Atmosphere-NX/Atmosphere#2076]
After updating to 1.5.1 on FW 16, all my custom forwarders have broke. I have confirmed that this is not just an issue for me and my system. Forwarder all work on previous atmosphere version 1.5.0

**Comment by SciresM** [comment]
Piracy is not supported.

**Comment by PiranhaMayhem** [comment]
How are custom forwarders piracy?

**Comment by SciresM** [comment]
Unofficial content installation of all kinds (anything requiring warez modifications to atmosphere) is considered piracy by both Atmosphere and Nintendo.
