### ISSUE TITLE
Can we change this Atmosphere official boot logo for custom? 

### ISSUE THREAD

**Issue by dorminirko** [Atmosphere-NX/Atmosphere#2081]
#### Overview:
- [can we change this boot logo for custom?]</br>

#### Smaller Details: 
- [ ![cd9eccb522e9bb223e05653f9320de9](https://user-images.githubusercontent.com/32114453/226249332-61fc954a-701b-4f70-8db5-d6f3e0d91414.jpg) ]</br>

Request:change this as a png or include in something file

**Comment by SciresM** [comment]
No, doing so is greatly discouraged and help will not be provided.

You will forgive me this one small mark of pride, I hope.
