### ISSUE TITLE
Atmosphere crashes after reopening suspended game

### ISSUE THREAD

**Issue by Xarber** [Atmosphere-NX/Atmosphere#2083]
System Version: 1.5.1 | 16.0.0 | E
Steps to replicate: 

1. Open any game
2. Go to the home menu
3. Reopen the game
4. Atmosphere crashes
PS: Also opening the homebrew menu from the images section crashes the switch (Usually with a game open)

**Comment by andrea-ap** [comment]
I try and not have issue. System Version: 1.5.1 | 16.0.1 | E

**Comment by Xarber** [comment]
> I try and not have issue. System Version: 1.5.1 | 16.0.1 | E

16.0.0 sorry, anyways i dont know how to solve and i cant find anything online

**Comment by masagrator** [comment]
You did not use issue template.

**Comment by Xarber** [comment]
> You did not use issue template.

i dont know how to use them and where to find them

**Comment by SciresM** [comment]
I am closing. Create new issue. It will have a template in the text box. Fill it out.
