### ISSUE TITLE
Mirror wifi database to SD

### ISSUE THREAD

**Issue by benwa** [Atmosphere-NX/Atmosphere#2088]
#### Overview:
Similar to the recently added Bluetooth database feature, it would be useful to have the Wifi database mirrored to the SD card for other applications to use.

#### Smaller Details: 
Unknown

#### Nature of Request:  
- Addition
  A file under `/atmosphere/wireless.db`
  A system setting to enable the feature

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>

### Why would this feature be useful?
This would possibly allow users who use alternate operating systems to have the same wireless networks without having to connect to them in each OS.

**Comment by ndeadly** [comment]
Conceptually it would be nearly identical to my Bluetooth PR but for setsysGetNetworkSettings/setsysSetNetworkSettings. It's more a question of whether @SciresM would accept such a feature. I imagine the argument for syncing wifi information is much weaker than for Bluetooth given how infrequently one would typically update their wifi settings. Additionally. many people running emummc explicitly _don't_ want their wifi settings synced. A simple homebrew to dump the current pairing information may be considered more practical.

**Comment by SciresM** [comment]
I would be willing to look at a pull request.
