### ISSUE TITLE
Keep showing Error Code: 2168-0002 (0x4a8) in my Nintendo Switch

### ISSUE THREAD

**Issue by iixxazoz** [Atmosphere-NX/Atmosphere#2091]
Sorry I'm a noob for programming or gaming. My issue is when i run any game in retroArch it just get crashed and the atmosphere show the error code 2168-0002 (0x4a8) i have load the core and done everything but i don.t what to do i wish you could help me

**Comment by masagrator** [comment]
1. You didn't use issue template
2. You didn't run game in application mode, but in applet mode and you're exhausting RAM pool. This is not an atmosphere issue. For help with RetroArch go to RetroNX discord.
