### ISSUE TITLE
Error Code: 2002-4153 (0x207202) when trying to launch atmosphere

### ISSUE THREAD

**Issue by axcelmo** [Atmosphere-NX/Atmosphere#2092]
### What's the issue you encountered?

my kid was gaming and suddenly atmosphere crashed and wont start up anymore

### How can the issue be reproduced?

by trying to launch atmosphere directly using fusee of hekate

### Crash Report

 [gist](https://gist.github.com/axcelmo/9a91abfb30ad30544f8c01facf770148)

### System Firmware Version

15.0.1</br>

### Environment?

-  fusee atmosphere-1.5.1-master-
 - Hekate official release version 6.0.2
- partitionbased EmuMMC

**Comment by Masamune3210** [comment]
qlaunch crash makes me think custom theme, try cleaning out the sd card folder named the same as the titleid in atmosphere\contents, if the folder exists just delete the entire folder

**Comment by axcelmo** [comment]
tried that, there is no folder named with the titleid that I can delete

**Comment by SciresM** [comment]
`fs::ResultUnclearedRomRealDataVerificationFailed()` -- emummc is corrupted, back up your data and re-clone.
