### ISSUE TITLE
Switch keeps crashing unexpectedly (error report and error code screen included in zip)

### ISSUE THREAD

**Issue by KamiSquadX** [Atmosphere-NX/Atmosphere#2093]
- [ Ex: Kosmos' distribution of Atmosphère ]
  - [ [Atmosphère 1.5.1](https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.5.1) ]
- Do you have additional kips or sysmodules you're loading:
  - How do I find out if I have any loading? (I do have Smash mods. But Themes are the newest thing installed, everything else was installed before with minor to no issues
- Homebrew software installed: [ * ]
  - Don't know, how do I find out if any are installed?
- EmuMMC or SysNAND:
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]
    - EmuMMC, partition-based

### Additional context?

I do have themes on, and on fw 16.0.0. During one of the crashes it gave an error: 

"Panic occurred while running Atmosphere.

Title ID: 010041544D530000
Error: std: :abort (oxFFE)
Report saved to /atmosphere/fatal_errors/report_89124d0a7.bin"

[report_89124d0a7 + Atmosphere Error Screen.zip](https://github.com/Atmosphere-NX/Atmosphere/files/11197295/report_89124d0a7.%2B.Atmosphere.Error.Screen.zip)

Can anyone help? This latest cfw for 16.0.0 has been really buggy since installed.
Can't play a game for a long time before the game freezes (I can press home and go back to home menu while it's frozen) and then the whole Switch eventually crashes, prompting me to press a VOL to reboot to a payload etc.

Edit: It seems even in sleep mode, while docked, it still eventually crashes. smh. 
Also btw the Title ID: 010041544D530000 doesn't exist in the atmosphere/contents folder. No idea what that error was referring to.
I thought Smash Bros was playing without freezing, I turned it on the check again, after it started up left it on the menu for over 15+ mins, no freeze, proceeded to start a match, and it freezes. Smh.

Edit: Updated with the Issue Template.

**Comment by Masamune3210** [comment]
Please go back and fill out the issue template. It's there for a reason. 

Check your SD card's filesystem for corruption

**Comment by KamiSquadX** [comment]
Template now filled out.

You mean put my SD card in my windows pc and let it check for errors? Windows detected errors, Scanned and Fixed. Tried to use the save data cloud, and launch Smash Ultimate, both crashed Atmosphere.

**Comment by SciresM** [comment]
Your report indicates `fs::ResultPortSdCardNotActivated()`. Use another SD card; if this doesn't resolve, you may have SD card connector problems.

**Comment by KamiSquadX** [comment]
What to do for SD card connector problems?

**Comment by SciresM** [comment]
Dunno, visit a repair shop, I guess. Either way, not an atmosphere issue.

**Comment by KamiSquadX** [comment]
I switched SD cards, one that's on EmuMMC 15.0.0. Everything seems fine from this restore point so to speak. I can't redownload games cause it promps me to update, which I think would give the issues.
