### ISSUE TITLE
Connecting to the Switch using gdb-multiarch causes a panic

### ISSUE THREAD

**Issue by WuBoytH** [Atmosphere-NX/Atmosphere#2099]
### What's the issue you encountered?

After updating to 1.5.2, attempting to use Windows's Ubuntu to run gdb-multiarch causes an Atmosphere panic.</br>

### How can the issue be reproduced?

Update to Atmosphere 1.5.2 and attempt to connect with GDB.</br>

### Crash Report

Included here are my Atmosphere configs, my .gdbinit file, and the fatal report.
[Relevant Files.zip](https://github.com/Atmosphere-NX/Atmosphere/files/11267324/Relevant.Files.zip)

### System Firmware Version

16.0.2</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - Official release version 1.5.2
- Do you have additional kips or sysmodules you're loading:
  - nx-ovlloader/Tesla
- Homebrew software installed: N/A
- EmuMMC or SysNAND:
  - SysNAND

### Additional context?

- Additional info about your environment:
- N/A

**Comment by SciresM** [comment]
`pm::ResultDebugHookInUse()` -- you have another custom sysmodule/homebrew already in place as a debugger. Maybe noexes. Remove it, and the issue will go away.
