### ISSUE TITLE
Error code 2168-0001 (Instruction Abort)

### ISSUE THREAD

**Issue by Bondrewd1998** [Atmosphere-NX/Atmosphere#2104]
### What's the issue you encountered?

Hello, I'm not very knowledgeable in modding or coding, still new. I've been getting mods for Smash Ultimate, been following instructions and placing them in my ultimate/mod folders, and also making sure to go through the archive bit in hekatate. Even reformatted my SD card. I do have plugins that caused crashes, which I could see in the crash report, but I removed them. Now I'm stuck with this error, which is 2168-0001, can't find online what it means nor how to fix it. I had already updated Atmosphere to the latest version and it worked properly, it only started to not function after I got many new mods, I have a total of 178 mods atm. I did remove all mods and left the bare minimum, and it worked. 

### How can the issue be reproduced?

I inject the payload, which boots up the Switch normally, then I start Super Smash Bros Ultimate, I get the Switch loading screen, and then after a bit, the Switch notifies me that the software was aborted, therefore crashing. Sometimes, it does detect new mods and even creates shows me what mods conflict (which I fix when it happens), but it aborts later still in the loading screen anyways.

### Crash Report

https://gist.github.com/Bondrewd1998/97cfaebac0f90e98f6412f205a5f6fa9

### System Firmware Version

16.0.2

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusee, the one that came with the latest one.

- Official release or unofficial build:
  -Official release version 1.5.2 (or) unofficial build ]
  
- Do you have additional kips or sysmodules you're loading: I'm not sure what this means. I have arcopolis and skyline installed along with many Super Smash Bros mods on. I also have Hekatate installed.

- Homebrew software installed: Other than Hekatate, atmosphere, arcopolis and skyline, I have not used other programs. I did however installed all of the software in this guide just in case I needed it for hekatate to function https://nh-server.github.io/switch-guide/user_guide/sysnand/sd_preparation/.

- EmuMMC or SysNAND:
  -I legitimately have no clue what this means. If it's relevant, point me in the right direction because I tried googling this and I don't know what it means.

### Additional context?

- Additional info about your environment:
-I did have to reformat my SD during this process because it had corrupted files in it as I was trying to troubleshoot, so I did a clean reinstall of all of the files, which did fix the corruption issue but didn't fix this error code above. Sorry if I left out important info, I'm new to this, hope I can be helped

**Comment by SciresM** [comment]
You should talk to whoever makes those mods/the mod framework, it's an issue with the mods and not with atmosphere.
