### ISSUE TITLE
0100152000022000 Mario Kart - patch 2.3.0

### ISSUE THREAD

**Issue by Footsmeik** [Atmosphere-NX/Atmosphere#2105]
## Bug Report

N/A</br>
0100152000022000 Mario Kart 8 deluxe</br>

### What's the issue you encountered?

Until patch 2.2.1 + DLC booster pack i've never experienced any problem. After last patch (2.3.0) + DLC wave 2 everytime i try to open the game it turns out the following error: The message is displayed The software was closed because an error occurred, along with a ! mark at the top of the screen.</br>
since I believed the problem was related to AMS I've decided to update AMS to the last version 1.5.2 but nothing changed.. Plus I've also updated the original firmware to the version 16.0.0 </br>
I tried all the possible combination of AMS 1.5.2 + CFW but the problem is still the same...</br>

### How can the issue be reproduced?

</br>
i use awoo installer ver 1.3.5 and the last sigpatches for AMS 1.5.2 but everytime i end up at the same point: the game is not working</br>

### Crash Report

https://gist.github.com/Footsmeik/2686f775971a8db842fd191667632b9b</br>

### System Firmware Version

16.0.0|AMS 1.5.2|S</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Fusèe (AMS 1.5.2)
- Official release AMS 1.5.2

**Comment by SciresM** [comment]
Piracy is not supported.
