### ISSUE TITLE
Switch Update 16.0.2 Broke Atmosphère?

### ISSUE THREAD

**Issue by Fruitybrute** [Atmosphere-NX/Atmosphere#2109]
### What's the issue you encountered?

Updated my Switch when prompted, 'cuz new games need to be on the new firmware, but I get a fatal error message.

### How can the issue be reproduced?

Update to Switch firmware 16.0.2.

### Crash Report

Atmosphère Fatal Report (v1.1):
Result:                          0xF601 (2001-0123)

Program ID:                      420000000007e51a
Process Name:                    ovlloader
Firmware:                        16.0.2 (Atmosphère 1.5.2-master-434c8cefc)
General Purpose Registers:
Start Address:                   0000000000000000
Stack Trace:
        ReturnAddress[00]:       0000000000000000
        ReturnAddress[01]:       0000000000000000
        ReturnAddress[02]:       0000000000000000
        ReturnAddress[03]:       0000000000000000
        ReturnAddress[04]:       0000000000000000
        ReturnAddress[05]:       0000000000000000
        ReturnAddress[06]:       0000000000000000
        ReturnAddress[07]:       0000000000000000
        ReturnAddress[08]:       0000000000000000
        ReturnAddress[09]:       0000000000000000
        ReturnAddress[10]:       0000000000000000
        ReturnAddress[11]:       0000000000000000
        ReturnAddress[12]:       0000000000000000
        ReturnAddress[13]:       0000000000000000
        ReturnAddress[14]:       0000000000000000
        ReturnAddress[15]:       0000000000000000
        ReturnAddress[16]:       0000000000000000
        ReturnAddress[17]:       0000000000000000
        ReturnAddress[18]:       0000000000000000
        ReturnAddress[19]:       0000000000000000
        ReturnAddress[20]:       0000000000000000
        ReturnAddress[21]:       0000000000000000
        ReturnAddress[22]:       0000000000000000
        ReturnAddress[23]:       0000000000000000
        ReturnAddress[24]:       0000000000000000
        ReturnAddress[25]:       0000000000000000
        ReturnAddress[26]:       0000000000000000
        ReturnAddress[27]:       0000000000000000
        ReturnAddress[28]:       0000000000000000
        ReturnAddress[29]:       0000000000000000
        ReturnAddress[30]:       0000000000000000
        ReturnAddress[31]:       0000000000000000

### System Firmware Version

16.0.2 (Atmosphère 1.5.2-master-434c8cefc)

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusèe
- Official release or unofficial build: Atmosphère 1.5.2
- Do you have additional kips or sysmodules you're loading: Not to my knowledge.
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND: EmuMMC, I believe? Might be partition-based. Should be a standard install just to make it work, anyway.

### Additional context?

N/A

**Comment by SciresM** [comment]
remove or update tesla, not an atmosphere problem.
