### ISSUE TITLE
Game unplayable after system reboot.

### ISSUE THREAD

**Issue by johnvinsongo** [Atmosphere-NX/Atmosphere#2110]
The game (Skinny and Franko) constantly wants to connect to the net to check the user account's eligibility once the console has been rebooted.

When I tried to check its integrity after system reboot... It had the following error:
Titlekey cannot be initialized
Titles with errors:
0100D9A01A278000

FW 16.0.1
Atmos 1.5.1
16.0.1 Sigpatches
DBI 551
Microsd Install - issue persisted
Nand Install - issue persisted

**Comment by Masamune3210** [comment]
Piracy is not supported.
