### ISSUE TITLE
a fatal error occurred when modding TOTK

### ISSUE THREAD

**Issue by BanhMi939** [Atmosphere-NX/Atmosphere#2111]
I'm trying to mod TOTK with layerFS, but got a error after applying the patch.

### Crash Report

attached below.

### System Firmware Version

16.0.2</br>

### Environment?

- fusèe
- Official release 1.5.2
- tesla menu, salty nx
- SysNAND

[report_00000000af612c55.zip](https://github.com/Atmosphere-NX/Atmosphere/files/11378799/report_00000000af612c55.zip)

only TOTK got this error, other games work fine.

**Comment by SciresM** [comment]
Piracy is not supported.

**Comment by frimeone** [comment]
> I'm trying to mod TOTK with layerFS, but got a error after applying the patch.
> 
> ### Crash Report
> attached below.
> 
> ### System Firmware Version
> 16.0.2
> 
> ### Environment?
> * fusèe
> * Official release 1.5.2
> * tesla menu, salty nx
> * SysNAND
> 
> [report_00000000af612c55.zip](https://github.com/Atmosphere-NX/Atmosphere/files/11378799/report_00000000af612c55.zip)
> 
> only TOTK got this error, other games work fine.

the same here

**Comment by SciresM** [comment]
@frimeone Piracy is not supported. If you comment again, I will block you from the issue tracker.
