### ISSUE TITLE
Game crashing when trying to load mods in romfs

### ISSUE THREAD

**Issue by BruhLookAtThis** [Atmosphere-NX/Atmosphere#2114]
![CertainGameModError](https://user-images.githubusercontent.com/58442192/236514647-492c9898-ccde-46c2-a25f-e1d1382b48f9.jpg)

**Bug Report**

a fatal error occurred when running atmosphere
program id: 010041544d530000
error desc: Data Abort (0x101)

**What's the issue you encountered?**
When I launch the game with mods in atmos/content/GamesTitleID/romfs/, it crashes to this black screen

**How can the issue be reproduced?**
Launch this Certain Game with any mods in that directory (tried 3 different mods, all failed. Work fine in Ryujinx)

**Environment?**
version

16.0.2
1.5.2

**Do you have additional kips or sysmodules you're loading:**
Lemme check...

**Additional context?**
That Program ID is NOT the Title ID of the game. In fact, a folder with that Program ID in the picture doesn't even exist in my contents folder...

**Additional info about your environment:**
[ Any other information relevant to your issue. ]

I understand if this post gets locked/deleted, just shooting in the dark here in the off chance someone's familiar with this style of error and has a solution

**Comment by zemixe** [comment]
Piracy is not supported.

**Comment by Masamune3210** [comment]
Missing the "not supported" part of that a little bit...

**Comment by SciresM** [comment]
Piracy is not supported.
