### ISSUE TITLE
build exosphere

### ISSUE THREAD

**Issue by jacobfernando** [Atmosphere-NX/Atmosphere#212]
Makefile:114
exosphere/exosphere.elf] Error 1
Makefile:114: recipe for target 'build' failed
i get this error and ithink libnx is up to date

**Comment by slinger360** [comment]
Unrelated to Atmosphere. Currently compiles fine. Tested and running mostly stable with all currently implemented functionality. Make sure to get the pkgbuild helpers and source them before running make (read the build environment setup guide). Read any errors and install whatever it says is missing (in my case devkitARM for the base_rules). Ask on the Discord under user-support if you need any further help.
