### ISSUE TITLE
Atmosphere crashing with Amiibos

### ISSUE THREAD

**Issue by BigBoss320** [Atmosphere-NX/Atmosphere#2123]
### What's the issue you encountered?

Atmosphere is crashing when wanting to scan an Amiibo in certain apps.

### How can the issue be reproduced?

Connect a controller without the Amiibo scan feature, start an app that includes Amiibos, like Zelda:Breath of the Wild, start the scan.
Atmosphere gives the followed error code : 2002-0001 (0x202)

### Crash Report

https://gist.github.com/BigBoss320/6c39744531907b64d619dc353496982c

### System Firmware Version

16.0.3</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Fusée and Hekate 6.0.4
- Official release or unofficial build: 
  - Official release version 1.5.3
- Do you have additional kips or sysmodules you're loading: I just completely redo the SD to see if it was the Sysmodules. So, no.
- Homebrew software installed: FTPD Pro
- EmuMMC or SysNAND:
  - SysNand

### Additional context?

- Additional info about your environment:
- No

**Comment by Masamune3210** [comment]
Piracy is not supported.

**Comment by BigBoss320** [comment]
Piracy??

**Comment by Masamune3210** [comment]
![Screenshot_2023-05-13-10-39-39-91_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Atmosphere-NX/Atmosphere/assets/1053504/e3034dfa-c942-4850-b9bf-7f30a3c06bd3)

**Comment by BigBoss320** [comment]
That's not because of that! I have the physical game

**Comment by Masamune3210** [comment]
Doesn't matter, Atmosphere considers anything that involves installing NSP's to be piracy and will not offer support.

**Comment by BigBoss320** [comment]
And so? Will removing the hemobrew solve the problem?

**Comment by Masamune3210** [comment]
Really struggling with the whole "No Support" part of this equation, arent you
