### ISSUE TITLE
pkg2 decryption failed! pkg1/pkg2 mismatch or old hekate!

### ISSUE THREAD

**Issue by zbuger** [Atmosphere-NX/Atmosphere#2124]
![image](https://github.com/Atmosphere-NX/Atmosphere/assets/11701693/324276b4-0798-4628-846a-b1b08fcdec22)

hekate: v5.7.0
Mariko: 13.2.1

**Comment by masagrator** [comment]
1. You didn't use issue template.
2. This is not an Atmosphere issue
3. Update your shit since nobody will help you with outdated stuff
