### ISSUE TITLE
Fatal error on bootup

### ISSUE THREAD

**Issue by yomeny1** [Atmosphere-NX/Atmosphere#2125]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?
Fatal error on bootup. Just downloaded and moved the latest update onto my switch's sd card, replacing the files as needed from dragging the updated zip contents over to the sd card's root. Made sure to update fusee as well.
Program ID: 010000000000bd00
Error description reads: std::abort() called (0xffe)
[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?
Happens automatically upon bootup with Atmosphere
[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report
https://gist.github.com/yomeny1/0baa8d818016753a1ebbf79f3cc51273 
Could not drag the bin file to copy code, so had to open in  notepad to copy and paste
[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

15.0.0</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Launched with both fusee and hekate, same result both times.
- Official release or unofficial build: Used official build 1.5.3
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND:
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
update mission control, not an atmosphere problem.
