### ISSUE TITLE
USB File Transfer (haze.nro) not working in Atmosphere 1.5.3

### ISSUE THREAD

**Issue by laurekamalandua** [Atmosphere-NX/Atmosphere#2126]
### What's the issue you encountered?

Since updating to 1.5.3 my device is not recognized (either PC or MAC) using the built in haze.nro application. I tested MTP transfers with the same device/cable in Android and have no issues connecting this way. Can someone verify whether this piece of functionality was tested in the latest release and verified to be working?

### How can the issue be reproduced?

1. update rom 1.5.2 to 1.5.3 using AIO Switch Updater
2. connect device to USB,  open USB File Transfer app from hbmenu.nro

### Crash Report

No crash reported. Host reports issue. 

### System Firmware Version

16.0.3

### Environment?

 | Component | Value |
| -- | -- |
| Atmosphere Version | 1.5.3 |
| OFW version | 16.0.3 |
| Bootloader | Hekate 6.0.4  |
| System | EmuMMC - partition based |

### Additional context?

**Screenshots** 

<img width="712" alt="android-mtp" src="https://github.com/Atmosphere-NX/Atmosphere/assets/12623827/db7c266b-39b2-47fc-8e91-807c105a2250">
<img width="712" alt="atmo-mtp" src="https://github.com/Atmosphere-NX/Atmosphere/assets/12623827/ecc54c79-f92e-4cee-a0d8-41e993847aae">

**Comment by SciresM** [comment]
I did in fact test it and have used it on both 1.5.3 (and the 1.5.4 pre-release).

**Comment by SciresM** [comment]
You also, notably, didn't fill out the issue template. Please fill out the issue template.

**Comment by shingoxray** [comment]
Same problem on macOS. Android File Transfer and OpenMTP not recognizing the device. But on Windows it is OK.

**Comment by AuroraWright** [comment]
Works here with both OpenMTP and go-mtpfs on macOS

**Comment by laurekamalandua** [comment]
It was resolved with a clean reinstall.

**Comment by shingoxray** [comment]
> 

Reinstall the ATM?

**Comment by sourcec0de** [comment]
Uninstalling Google Drive did the trick for me.

**Comment by lcn918** [comment]
Same issue when using a newer version (1.7.1). Quitting the Google Drive app then reconnect Switch worked for me. The Android File Transfer app recognized Switch correctly.
