### ISSUE TITLE
TotK mod error

### ISSUE THREAD

**Issue by tsurugikengo** [Atmosphere-NX/Atmosphere#2127]
When I install the mod and start the game, it crashes and this screen appears.
![A1EFA723-93D6-498B-BC4F-198FF0E04FE4](https://github.com/Atmosphere-NX/Atmosphere/assets/133575898/d7a4ce6e-6f52-4a5c-88c5-dece8938f639)

**Comment by SciresM** [comment]
Please upload the report file, and fill out the issue templates.

**Comment by SciresM** [comment]
Also, provide details on the mod you're using?

**Comment by SciresM** [comment]
...also, are you using the 1.5.4 prerelease? "Fatal error" is expected on 1.5.3.

**Comment by tsurugikengo** [comment]
I use 1.5.4
mod is Edited weapon parameters by myself

**Comment by SciresM** [comment]
Please upload the error report binary. And the mod, I guess.

**Comment by SciresM** [comment]
And a screenshot of atmosphere/contents in general?

**Comment by tsurugikengo** [comment]
Give Up.
thank you very much.

**Comment by SciresM** [comment]
...okay, I'll close this, I can't help you unless you upload the report binary.
