### ISSUE TITLE
Atmosphere Fatal Error - Program ID: 524850534f53454d

### ISSUE THREAD

**Issue by aytimothy** [Atmosphere-NX/Atmosphere#2130]
Similar to #2117 except I can still boot to stock (both via Hekate and skipping RCM; the normal way).

> "A fatal error occured when running Atmosphere."
> Program ID: 524850534f53454d
> Error Desc: Kernel Panic (0xf00)
> 
> Report saved to /atmosphere/fatal_errors/report_0000000000a8e66d.bin"
> 
> Switch failed to boot after updating to latest firmware version from 14.0, CFW failed to boot. tried reflashing nand, and then got this issue, latest atmosphere still fails to boot now.

Initially had a yellow screen when attempting to anything via Hekate (all; EMMC CFW, stock and stock CFW) after an update of the OS, but updatingAtmosphere made that go away. But to get to the error, I had to push another payload (Hekate again) via [RCM](https://github.com/eliboa/TegraRcmGUI), otherwise it remains blank screen.

**Switch Firmware Version:** 14.1.2 -> 16.0.4  
**Hekate:** 6.0.4  
**Atmosphere:** 1.4.0 -> 1.5.3 -> 1.5.4  
**Environment:** Stock CFW, though technically all

[report_017c67c.zip](https://github.com/Atmosphere-NX/Atmosphere/files/11495460/report_017c67c.zip)

I forgot which one was the crash from 1.5.3, so I can only provide a 1.5.4 crash.

**Comment by SciresM** [comment]
Yeah, this is a spurious data abort exception taken during innocuous kernel code.

This is a hardware error, sorry.

**Comment by aytimothy** [comment]
> Yeah, this is a spurious data abort exception taken during innocuous kernel code.
> 
> This is a hardware error, sorry.

Just double-checking, my 14.x booted fine; still hardware error?

**Comment by SciresM** [comment]
...yes?
