### ISSUE TITLE
Panic occured while running Atmosphere / Error std:abort (0xFFE) after install 16.0.3 FW on EmuNAND

### ISSUE THREAD

**Issue by DeeJayz23** [Atmosphere-NX/Atmosphere#2131]
## Bug Report

Panic occured while running Atmosphere
Title ID : 010000000000BD00
Error:      std::abort (0xFFE)
Report saved to /admosphere/fatal_errors/report_0a437d91.bin

### What's the issue you encountered?

After a successful Hekate update to 6.0.4 and Atmosphere Update to 1.5.3, running perfectly my EmuNAND under FW 14.0.1 I have Install FW 16.0.3 with Daybreak.
At restart, I optain this fatal error

### How can the issue be reproduced?

Just have to try to boot on Atmosphere EmuNAND from Hekate launcher

### Crash Report

Crash reports can be found under ``/atmosphere/fatal_errors``. 

### System Firmware Version

Switch FW 16.0.3

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
  - Hekate 6.0.4 official release
  - Atmosphere 1.5.3 official release

- Homebrew software installed: [ ? ]
- EmuMMC

### Additional context?

Coming from SXOS, I have past year proceed to transition to Atmosphere. I was on FW 14.0.1. 
Transition perfectly done and all switch work like a charm. 
On this same FW, it works fine after recent updates of Hekate and Atmosphere.
Crash occurs just after FW update to 16.0.3
Perhaps a issue or mistake with fusee.bin.
I have just copy the new one into SDXCroot\bootloader\payloads. I haven't perform another particular action with fusee.bin

**Comment by ndeadly** [comment]
Update Mission Control

**Comment by DeeJayz23** [comment]
Hello. thanks for the information.

I have perform it, and now i got another error :

Error Code: 2001-0123 (0x601)

Program: 42000000000751A

Firmware: 16.0.3 (Atmosphère 1.5.3-master-8042226)

An error has occurred.

Please press the POWER Button to restart the console normally, or a VOL button to reboot to a payload (or RCM, if none is present). If you are unable to restart the console, hold the POWER Button for 12 seconds to turn the console off.

If the problem persists, refer to the Nintendo Support Website.

**Comment by SciresM** [comment]
Remove or update Tesla. Not an atmosphere problem.

**Comment by DeeJayz23** [comment]
I don't know what is Tesla (for swich)
I have made a search, I find Tesla Menu (overlay),  but I don't have it at all

**Comment by masagrator** [comment]
> 42000000000751A

Delete folder named like this from atmosphere/contents 

This quote is a proof you have tesla sysmodule aka nx-ovlloader

**Comment by DeeJayz23** [comment]
> 



> 

Excellent, I've detele it and it work fine now. 

Thanks a lot

**Comment by DeeJayz23** [comment]
Swich boot well on emunand FW 16.0.3, but all installed games fail to start, explaining that data on SD card are corrupt ...

Have you an idea ?

**Comment by Masamune3210** [comment]
Reinstall them from the eShop.
