### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by GithubUser4161** [Atmosphere-NX/Atmosphere#2137]
When I'm in the hekate menu and boot it says "A fatal error occurred when using Fusee.
Incorrect fusee version!"
I'm using the fusee version thats in 1.5.4 assets

**Comment by Masamune3210** [comment]
Atmosphere has nothing to do with hekate. If you have a issue with it, take it over to that repo, or figure out the issue yourself considering its telling you exactly what the issue is. 
Also, you didn't use the issue template. Its pre-filled for a reason.

**Comment by SciresM** [comment]
There is no need

**Comment by SciresM** [comment]
*no need to berate them as such. I can handle it.

**Comment by Masamune3210** [comment]
Sorry

**Comment by SciresM** [comment]
Don't worry about it. Your commentary is usually fairly helpful.
