### ISSUE TITLE
Atmosphere kernel panic/fatal error when loading a mod from Contents directory.

### ISSUE THREAD

**Issue by n0w33d** [Atmosphere-NX/Atmosphere#2139]
Installing the following Tears of the Kingsom mod will crash Atmosphere: https://gamebanana.com/mods/445269

Device: Nintendo Switch v1, model Erista
Software: Switch device firmware version 16.0.3, Hekate version 6.0.4 & Nyx version 1.5.3, Atmosphere NX version 1.5.4|E with fuseé pre-release.

I can post the error dump as well, please let me know what additional info you require to help troubleshoot.

**Comment by SciresM** [comment]
Please show a screenshot of your atmosphere/contents directory.

**Comment by SciresM** [comment]
1) "DBI" piracy not supported
2) You have too many custom sysmodules using too much memory so zelda mods can't load, this isn't an atmosphere issue.
