### ISSUE TITLE
Fatal Error when booting Tears of the Kingdom with mod.

### ISSUE THREAD

**Issue by n0w33d** [Atmosphere-NX/Atmosphere#2140]
### What's the issue you encountered?

Installing the following Tears of the Kingdom mod will crash Atmosphere: https://gamebanana.com/mods/445269</br>
No changes related to Atmosphère itself.</br>

### How can the issue be reproduced?

Having no other content inside the Contents folder,  install the above linked mod into the Contents folder.</br>

### Crash Report

No crash report is dumped. Only a fatal error report is dumped into a directory and a reboot is required.</br>

### System Firmware Version

16.0.3</br>

### Environment?

- fuseé bootloader was launched by:
- Official release build: 
  - Official release version 1.5.4|E
- Additional kips or sysmodules loaded: Tesla Overlay, QuickNTP, Sysmodules, sys-clk
- Homebrew software installed: AIO Sw Updater, Chiaki, Daybreak, HB App Store, Moonlight, NXS-Shell, NXMP, RetroArch, sys-clk manager, vgedit. (Note: DBI "piracy" software has been removed from device.)
- EmuMMC:
  - file-based.

### Additional context?

- Additional info about my environment:
- no memory overclocks, nor other components have overclock values enabled in sys-clk.

**Comment by SciresM** [comment]
Why are you opening duplicate issues?

I already said "You have too many custom sysmodules using too much memory so zelda mods can't load, this isn't an atmosphere issue".

Remove custom sysmodules.

**Comment by SciresM** [comment]
How many sysmodules isn't the question, it's how much memory they use. One would be too many if it used too much memory. The problem should go away if you remove all modules.
