### ISSUE TITLE
Error code 2002-4373 

### ISSUE THREAD

**Issue by braybray124** [Atmosphere-NX/Atmosphere#2155]
## Bug Report
Program 010000000024
When I boot up my switch with us chipped withw the hwfly rp2040 an when it is going to boot in the emmnand I get the error code after the Nintendo logo an I put in on the sd card with the NEXT aio pack an it an it is working fine ani can not use it anymore so can you pls help fix this

**Comment by Masamune3210** [comment]
Please go back and actually fill out the issue template.....

**Comment by Cam396** [comment]
if you want a guaranteed working homebrew download the latest release of Atmosphere (https://github.com/Atmosphere-NX/Atmosphere/releases) hekate (https://github.com/CTCaer/hekate/releases/tag/v6.0.5) and grab some packages on sdsetup.com

**Comment by SciresM** [comment]
This didn't use the issue templates.
