### ISSUE TITLE
Black screen after booting to Atmosphere

### ISSUE THREAD

**Issue by Switchbruh** [Atmosphere-NX/Atmosphere#2156]
Hey guys, been using Atmosphere for years at this point and never encountered any issues

Just updated to 1.5.4 and booted into Atmosphere, the Atmosphere logo flashes up and its like it's booted into the switch CFW but its a black screen, the only thing I can do is hold power and reboot to hekate. I've tried booting fusee directly from Tegra and it's the same

I've never had any issues before so please be gentle with my lack of knowing what other info might be needed to help

thanks

**Comment by SciresM** [comment]
Please re-open with the issue template filled out.
