### ISSUE TITLE
A fatal error occurred when running Atmosphere

### ISSUE THREAD

**Issue by BetterThanYo** [Atmosphere-NX/Atmosphere#2172]
so i tried modding my switch for the first time and i followed all the steps but when i go to launch my switch it says “ A fatal error occurred when running atmosphere
Program ID: 010041544d530000
Error Desc: std::abort() called (0xffe)”
how do i fix this, is my switch now broken?

**Comment by Masamune3210** [comment]
Go back and fill out the issue template instead of just wiping it away, please. Its there for a reason.
