### ISSUE TITLE
Pikmin 4 Stuttering

### ISSUE THREAD

**Issue by explosiveshrooms** [Atmosphere-NX/Atmosphere#2175]
### What's the issue you encountered?

Pikmin 4 full game stutters badly when playing. Some areas are worse than others.</br>

### How can the issue be reproduced?

For me, the issue is always present in Pikmin 4
Have tried installing as XCI, and as NSP. Tried installing using a few different options (Tinfoil, Goldleaf, and one other) but the problem is always the same

### Crash Report

No crashing is happening

### System Firmware Version

16.0.3

### Environment?

- EmuMMC or SysNAND:
  - Partition-based EmuMMC

### Additional context?

- Additional info about your environment:
- Others are having this issue too, but their comments are on a forum that I was just informed should maybe be removed from the text here. Commenters there are saying that the issue is present on Emunand, but not on Sysnand
- Another commenter there is saying the issue exists on their v2 switch running on Emunand, but not on their v1 switch running on emunand.

**Comment by explosiveshrooms** [comment]
The reason i specified "Pikmin 4 full game" is because some people have said the issue isn't present on the Pikmin 4 Demo

**Comment by zemixe** [comment]
Piracy is not supported.

**Comment by explosiveshrooms** [comment]
> 

thanks, i didn't pirate it but i removed a couple of links that may have been against anti-piracy rules

**Comment by SciresM** [comment]
Piracy is not supported. You did in fact pirate it, per `tried installing as XCI, and as NSP`.

Anyway, I've been playing Pikmin 4 a lot, and have like 30 hours in the game using Atmosphere.

No stuttering problems whatsoever.
It's gonna be an issue with your setup, not an atmosphere issue.
