### ISSUE TITLE
Atmosphere Crash in Sys and Emu

### ISSUE THREAD

**Issue by madmaxen9** [Atmosphere-NX/Atmosphere#2177]
## Bug Report

Can't load CFW or OFW Error 0xff0 Title ID 524850534f53454d

### What's the issue you encountered?

Atmosphere is crashing, screenshot of issue here. Unable to load sys or emu
![image](https://github.com/Atmosphere-NX/Atmosphere/assets/140773150/2e838d23-063d-41cd-92a1-222dfdb46347)

### How can the issue be reproduced?

Loading into Hekate 6.0.5 and boots to Atmosphere screen, then Nintendo and either get the fatal error message or freezes at NS logo

### Crash Report

(https://gist.github.com/madmaxen9/4f8a8ec78f7f91730af62ccb50761345)

### System Firmware Version

X.X.X</br>
16.0.3

### Environment?

Off Hekate 6.0.5
- Do you have additional kips or sysmodules you're loading: N
- Homebrew software installed: N/A
- EmuMMC or SysNAND: Both

### Additional context?

- Additional info about your environment:
Contents folder screenshot
![image](https://github.com/Atmosphere-NX/Atmosphere/assets/140773150/49cc7b85-3077-44d2-8b04-19ae06f8d9d2)

**Comment by SciresM** [comment]
Piracy is not supported. I just closed your other issue.

**Comment by madmaxen9** [comment]
I'm sorry but where did I say anything about piracy, I'm simply trying to solve my Atmosphere crash issues

**Comment by SciresM** [comment]
`Was loading a game onto the switch via DBI installer`. As I said, piracy is not supported.
