### ISSUE TITLE
A fatal error occurred when running Fusée

### ISSUE THREAD

**Issue by FxntyHS** [Atmosphere-NX/Atmosphere#2182]
### What's the issue you encountered?

"A fatal error occurred when running fusèe
Failed to inituialize the SD card: 0x00004a18

Press POWER to reboot."

### How can the issue be reproduced?

After the jig procedure and injecting fusee.bin using TegraGUI.

### System Firmware Version

16.0.3

### Environment?

Atmosphère 1.5.4
fusee.bin (same from the update).

**Comment by Masamune3210** [comment]
Either your sd card is faulty, the filesystem is damaged or the wrong filesystem, your sd card daughterboard is damaged, or the port on the motherboard is damaged. Try a different SD card, its the easiest option to start with
