### ISSUE TITLE
Panic

### ISSUE THREAD

**Issue by BlankDolphin** [Atmosphere-NX/Atmosphere#2187]
Panic occurred while running Atmosphere.

Title ID Error:  010000000000BD00 

Error: std::abort (0xFFE)

Report saved to /atmosphere/fatal errors/report_a60cefd.bin

Press POWER to continue. 

I tried deleting the folder in /atmosphere/contents but there is no folder for that

**Comment by masagrator** [comment]
1. You didn't use issue template
2. "but there is no folder for that" - then check again until you find it. There is no possibility that it doesn't exist there.

**Comment by SciresM** [comment]
You didn't use the issue templates.

Also, as said, the folder exists, you're just not finding it.
