### ISSUE TITLE
Error 2113-6009 - Help me find the issue!

### ISSUE THREAD

**Issue by brendongl** [Atmosphere-NX/Atmosphere#2191]
![wolfbuf](https://github.com/Atmosphere-NX/Atmosphere/assets/31434186/e7430a52-7299-4a8b-af62-dab4f7cb5d96)

Sysmodules on my switch are
MissionControl
Nxtheme
sys-ftpd-light 1.0.4

Using Hekate as bootloader. EmuMMC as partition,
Happened intermittently while browsing games.
I googled before to find some previous cases where the issue may have been a corrupt game save? Can anyone read the hex and help me find the culprit? (So i dont have to do a complete wipe/re-emunand)

**Comment by masagrator** [comment]
1. You didn't use issue template
2. This error is related to bluetooth, so I would point out everything about what you are doing with bluetooth

**Comment by brendongl** [comment]
MissionControl with WiiU Pro Controllers may have been attached, I'm not sure.
Other than that, nothing else related to Bluetooth is being used.
What part of the screenshot helps you know it has to do with Bluetooth?

**Comment by masagrator** [comment]
> What part of the screenshot helps you know it has to do with Bluetooth?

Error code
