### ISSUE TITLE
Incorrect fusee version!- Error when directly injecting fusee (not using hekate)

### ISSUE THREAD

**Issue by duskshadowbrony** [Atmosphere-NX/Atmosphere#2192]
### What's the issue you encountered?

Updated to latest Switch OS (16.1.0). Downloaded the latest fusee release (1.5.5) used TegraRCMGui to inject it. I get the following error: 
A fatal error occurred when running Fusee.
Incorrect fusee version! (program=0x4aa02b53,, mtc=0xd40bf61f)

This also might be related to the black screen error (#2157), as I get that exact issue when launching it through hekate. However, for some reason, injecting fusee directly through tegra causes an entirely different issue.

### How can the issue be reproduced?

Update Switch to 16.1.0, download fusee version 1.5.5. Try to inject it with tegra, and this error shows up. Black screen issue is documented in #2157 , so I will not mention it any further here unless needed.

### Crash Report

No crash reports in the folder

### System Firmware Version

16.1.0 </br>

### Environment?

- Attempted to launch through fusee and Hekate
- Official release 1.5.5
- No additional kips or sysmodules
- Homebrew software installed: [ JKSV, retroarch, Edizon, Goldleaf, breeze, nxdumptool ]
- EmuMMC or SysNAND:
  - Attempted both file-based EmuMMC and SysNAND.

### Additional context?

- Additional info about your environment:
- N/A

**Comment by SciresM** [comment]
"Incorrect fusee version" -- the version of fusee you're injecting does not match the version on SD card. You need to make sure they're the same. Extract the latest release zip to the SD card, then inject the fusee.bin from latest release.

**Comment by duskshadowbrony** [comment]
> "Incorrect fusee version" -- the version of fusee you're injecting does not match the version on SD card. You need to make sure they're the same. Extract the latest release zip to the SD card, then inject the fusee.bin from latest release.

Hi there, thanks for the reply.

I've tried this but get the same error. I made sure that the version I'm using to inject is the same on my SD card by deleting fusee from my hard drive and SD card, then extracting a fresh download onto them both.

**Comment by SciresM** [comment]
No, you didn't. `mtc=0xd40bf61f` --> you have atmosphere 1.5.2 on your SD card and are injecting >= atmosphere 1.5.3. You need to update atmosphere on your SD card, your package3 is factually outdated.

These issues are for bugs, not for support, so I'm going to lock this.
