### ISSUE TITLE
unable to boot atmosphere

### ISSUE THREAD

**Issue by PurplGTag** [Atmosphere-NX/Atmosphere#2198]
i accidentally when trying to load a game offline clicked update console and noting usually happens when online except for reloading software but when i did it this time i kicked me off and then gave me the error "fatal error occurred when running fusee unable to identify package1!

**Comment by PurplGTag** [comment]
why was this closed

**Comment by SciresM** [comment]
#2197 

You updated your switch and will have to wait for atmosphere to support the new firmware.

**Comment by PurplGTag** [comment]
it didnt actually update as the switch was not on wifi or online
