### ISSUE TITLE
A fatal error occurred when running Atmosphère (0100000000000005)

### ISSUE THREAD

**Issue by SignorUpB** [Atmosphere-NX/Atmosphere#2202]
A fatal error occurred when running Atmosphère
Program ID: 0100000000000005
Error Desc: std : :abort() called (0xffe)

This issue happened while updating atmosphere to the 1.6.0 pre-release

Report File:
https://drive.google.com/file/d/1sfLhAYBasLuCHMu6CGpkJCpqQeIDve7R/view?usp=sharing

**Comment by paraiasaigr-jpg** [comment]
@SciresM  can you add me on discord? i need help with the same error iam trying to reach you and i cannot.
iv tried everything.
https://sendvid.com/dhuu0vgd 
please comment when you see it i also send you on twitter.

**Comment by deapoquitonma-rgb** [comment]
> ¿Puedes añadirme en Discord? Necesito ayuda con el mismo error; estoy intentando contactarte y no puedo. He probado de todo. https://sendvid.com/dhuu0vgd por favor, comenta cuando lo veas, también te envío por Twitter.

Hey friend, did you find a solution? I'm in the same boat and I'm out of ideas.

**Comment by hookanagr** [comment]
Yes mate in this video
https://m.youtube.com/watch?v=fjyCAI31KAY&t=270s&pp=2AGOApACAQ%3D%3D

**Comment by deapoquitonma-rgb** [comment]
> Yes mate in this video https://m.youtube.com/watch?v=fjyCAI31KAY&t=270s&pp=2AGOApACAQ%3D%3D

Thank you so much, my friend, you have no idea how much I appreciate it.

**Comment by hookanagr** [comment]
I know bro that is why iam helping it took me 3 months for this
