### ISSUE TITLE
Crash on 17.0.0 

### ISSUE THREAD

**Issue by Alvyssy** [Atmosphere-NX/Atmosphere#2208]
### What's the issue you encountered?

I updated to 17.0.0 and updated atmosphere and hekate, it wasn't working so I took a clean sd and put only atmosphere and hekate.
It booted but crashes almost instantly giving me error code 2123-0011 (0x167b) Program: 0100000000000025

### How can the issue be reproduced?

[ * ]</br>Update to 17.0.0 and get a clean sd with hekate and atmosphere only.
Edit: Found out it's connecting to a wifi network so boot with wifi activated and wait for it to connect</br>

### Crash Report

(https://gist.github.com/Alvyssy/d87d4ce80d381cf7dc2691f39d2be8f7)</br>

### System Firmware Version

17.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
 Hekate Official release 6.0.7

**Comment by Mciver1991** [comment]
I'm getting the same issue when trying to run a game

**Comment by Alvyssy** [comment]
For me is just staying in the home screen for a bit

**Comment by Alvyssy** [comment]
It's wifi, connecting to a wifi network makes it crash. Use airplane mode for now

**Comment by Alvyssy** [comment]
It's actually exosphere. This is already a known issue

**Comment by Mciver1991** [comment]
@Alvyssy Thanks turning aeroplane mode on is now allow me to play games. Do you know why Tinfoil is courrpt after installing the new update? I have tried reinstalling.

**Comment by Masamune3210** [comment]
No piracy

**Comment by ANTONIOPSD** [comment]
> No piracy

LoL, Is it even illegal to talk about piracy?

**Comment by SciresM** [comment]
What is and isn't legal isn't relevant to the no piracy support policy.
