### ISSUE TITLE
'fsGetProgramId' error when compiled atmosphere

### ISSUE THREAD

**Issue by metalex10** [Atmosphere-NX/Atmosphere#2210]
## Bug Report
error compiled beacuse error on fs_remote_file_system_proxy.hpp
log of error, whats happen here?

error: 'fsGetProgramId' was not declared in this scope; did you mean 'GetProgramId'?
  325 |                 R_RETURN(fsGetProgramId(reinterpret_cast<u64 *>(out.GetPointer()), path.str,
 static_cast<::FsContentAttributes>(static_cast<u8>(attr))));

![image](https://github.com/Atmosphere-NX/Atmosphere/assets/3173507/44b4b3fe-e12c-4986-9441-3b357845a158)

**Comment by metalex10** [comment]
i clone the repository and write make ....

**Comment by SciresM** [comment]
Atmosphere requires a work in project branch of libnx right now. This is usually the case during major update prereleases.

**Comment by metalex10** [comment]
ok, i wait or can help?
