### ISSUE TITLE
Add 2160p video output

### ISSUE THREAD

**Issue by CasperMcFadden95** [Atmosphere-NX/Atmosphere#2219]
#### Overview:
- Add the ability to output 2160p so apps like https://github.com/proconsule/nxmp can show 4k videos without downscaling

#### Smaller Details: 
The standard dock supports 4k30, I think the new oled dock supports 4k60

### What component do you feel this would best fit within?
Not sure

### Why would this feature be useful?
Allow full playback of video without booting into Android

Thanks for your hard work!

**Comment by SciresM** [comment]
This is deeply out of scope for atmosphere. I literally have no idea how you would do this, if it's even possible.

Note that atmosphere does not really touch the horizon graphics stack whatsoever
