### ISSUE TITLE
Example loader.ini?

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#222]
Ive comipled my own atmo for that loader.ini fix  Where can i find an example loader.ini?

**Comment by fennectech** [comment]
Im trying to use titleid redirection for hbmenu.nsp so i can access full memory.

**Comment by SciresM** [comment]
This isn't what issues are for.

That said:

```
[config]
hbl_tid=010000000000100D
hbl_path=hbl.nsp
override_key=!ZL
```
