### ISSUE TITLE
Request to add support for external USB flash drive or mobile hard disk

### ISSUE THREAD

**Issue by izhima** [Atmosphere-NX/Atmosphere#2221]
Request to add support for external USB flash drive or mobile hard disk

**Comment by masagrator** [comment]
1. This is out of scope for this project. 
2. Atmosphere doesn't include any type of File Explorer, so dunno what you want to achieve with that support in Atmosphere. 
3. There already exists library for homebrew that allows reading external hard disks, so nobody stops homebrew devs from implementing it.
https://github.com/DarkMatterCore/libusbhsfs/
