### ISSUE TITLE
Right Joycon disconnecting when docked to Switch

### ISSUE THREAD

**Issue by JMR185** [Atmosphere-NX/Atmosphere#2222]
### What's the issue you encountered?

I installed the latest Atmosphere update 1.6.2 on a firmware updated 17.0 Switch. I'm having trouble with my right joycon disconnecting when docking it onto my Switch console. It's only when I detach the right joycon its recognized by the console. I've tried disconnecting and resyncing my joycons multiple times without success. I've also tried other right Joycons with similar results. Also, when attaching the right joycon to the console it makes the clicking sound effect and flashes the correct associated joycon color but it appears as disconnected.</br>
[I didn't do any changes to Atmoshere 1.6.2 ]</br>
[ I did see a similar thread #2113 about deleting Sys-clk sysmodule from an older Atmosphere build but unable to find the folder.]</br>

![3](https://github.com/Atmosphere-NX/Atmosphere/assets/149634560/7d8547e8-a82e-4e90-977e-7636f50c4261)
![4](https://github.com/Atmosphere-NX/Atmosphere/assets/149634560/848936e4-f444-4fb1-8625-647e5f9164a1)

### How can the issue be reproduced?

[ * ]</br>
When docking my right joycon to the console it will disconnect. Will make a clicking sound effect and flash the right color on screen but will not be recognized. Only when removing my joycon (wireless) it will detect it and sync with the console. Tried multiple other right joycons with similar effect.</br>

![2](https://github.com/Atmosphere-NX/Atmosphere/assets/149634560/aae9d4d5-6c60-49d6-af95-36a3d63d73fb)

### System Firmware Version

17.0.0| AMS 1.6.2|E</br>

### Environment?

- Used Fusee as bootloader
- EmuMMC

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by masagrator** [comment]
This doesn't happen in OFW?
What sysmodules you have installed?

**Comment by JMR185** [comment]
Did not happen in OFW... it only occurred after installing CFW (17.0.0| AMS 1.6.2|E)
For Sysmodules all I have is Tinfoil

**Comment by Masamune3210** [comment]
Piracy is not supported
