### ISSUE TITLE
EdiZon on Tesla overlay (no support for firmware 17.0.0)

### ISSUE THREAD

**Issue by greargon285** [Atmosphere-NX/Atmosphere#2224]
![1699104082595](https://github.com/Atmosphere-NX/Atmosphere/assets/149879621/4249b975-5d38-4e53-9c35-98026a5b4f24)

Error Code: 2001-0123 (0xf601)
Program: 420000000007E51A
Firmware 17.0.0 (Atmosphere 1.6.2-master-f7bf379cf)

### What's the issue you encountered?
crashed after clicking EdiZone in Tasle-overlay menu

### How can the issue be reproduced?

1. install Tesla-Overlay prerequisites:
         nx-ovlloader(1.0.7), ovlmenu(1.2.3), EdiZonOverlay(4.0.0)
2. launch Tesla-Overlay --> EdiZone
3. Crash

### Crash Report

could not generate crash report

### System Firmware Version

17.0.0|AMS 1.6.2|E

### Environment?

hekate(6.0.7)

using EmuMMC(patition based)

nx-ovlloader(1.0.7)
ovlmenu(1.2.3)
EdiZonOverlay(4.0.0)

**Comment by Masamune3210** [comment]
This is not an issue with atmosphere, please take it to the respective repo instead
