### ISSUE TITLE
Allow arbitrary homebrew to be launched via parameters given to hbl.nsp

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#2232]
#### Overview:
- Provide parameters on what nro to launch through override_config.ini</br>

#### Smaller Details: 
-NA</br>

#### Nature of Request:  
- Addition
  - [ Allow HBL.nsp to accept peramaters on launch ]
  - [ Allow atmosphere to pass parameters specified in override_settings.ini ]

### What component do you feel this would best fit within?
- [Exosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Fully-featured custom secure monitor.</br>

[ Note: **Bolded components are not implemented** or are still at the prototyping phase. ]

### Why would this feature be useful?
[it would allow the end user to add custom homebrews to various buttons and applications. ]</br>
[ the ability for developers to add their own homebrew to various icons without generating their own exefs.nsp to launch their homebrew.]</br>

**Comment by SciresM** [comment]
I do not particularly intend to implement forwarder functionality.
