### ISSUE TITLE
Boot Error/Brick when updating to Firmware 17.0.0

### ISSUE THREAD

**Issue by L4now** [Atmosphere-NX/Atmosphere#2234]
## Bug Report

After updating to Firmware 17.0.0, booting the console throws Error 2002-3005 on both OFW and latest Atmosphere.

### What's the issue you encountered?

Yesterday I tried updating my switch (v1) from 16.0.2 to 17.0.0. 
Before updating, I made sure to install the latest atmosphere release (1.6.2-master-f7bf379cf) to not encounter any issues after the update.
After Daybreak confirmed the install was successful, I rebooted directly into atmosphere and found myself at this crash screen: 
![20231116_202123](https://github.com/Atmosphere-NX/Atmosphere/assets/87015825/736c1674-e086-412c-a9d4-34f1eab2f5b3)
Normally I would then reboot to OFW to turn the console off safely and remove the sd card, but an OFW boot only gets to the Nintendo logo and then prints a similar error message 
![20231116_202309](https://github.com/Atmosphere-NX/Atmosphere/assets/87015825/6aa430b9-fcd0-4300-8fb6-c9d042dec51c)
which suggests that the console is probably bricked.
Some other people with similar issues said they fixed it by updating to the latest atmosphere version but unfortunatly this has not worked for me. I saw someone claiming deleting EMMC/SYSTEM/SAVE/8000000000000120 and then booting atmosphere could fix the issue but I want to see if anything else can be done before trying that out.

### How can the issue be reproduced?

Fully wiping the sd card and unpacking the latest atmosphere release zip on it and injecting fusee.bin with TegraRcmGUI.
OR
Booting the switch without sdcard into OFW.

### Crash Report

fatal_reports folder: [fatal_reports.zip](https://github.com/Atmosphere-NX/Atmosphere/files/13389974/fatal_reports.zip)
crash_reports folder: [crash_reports.zip](https://github.com/Atmosphere-NX/Atmosphere/files/13389978/crash_reports.zip)
The folders fatal_errors and erpt_reports are both empty.

### System Firmware Version

17.0.0

### Environment?

fusee and atmosphere from the latest release.
No sysmodules/patches/kips used.
SysNAND, never touched EmuMMC ever.

### Additional context?

N/A

**Comment by SciresM** [comment]
Yeah, this isn't an atmosphere issue. Seek support on discord. You'll need to wipe your console (and do so in a way that doesn't trigger the 17.x save issue)
