### ISSUE TITLE
Stuck on nintendo switch logo

### ISSUE THREAD

**Issue by Dzonkins** [Atmosphere-NX/Atmosphere#2235]
### What's the issue you encountered?
After month of atmosphere 1.5.5 working on my partition based emunand with 128gb FAT32 sandisk microsd this week started getting stuck on nintendo switch logo on emunand. If I boot stock sysnand everything boots fine

### How can the issue be reproduced?
N/A

### Crash Report

N/A

### System Firmware Version

16.1.0

### Environment?

Booting using fusee with atmosphere 1.5.6
- Homebrew software installed: Linkalho, sys-clk, missioncontrol, ftpd-pro, tinfoil, SaltyNX, SysDVR, FPSLocker, Tesla overlay, DBI
- EmuMMC or SysNAND:
  -Partition based emuMMC

### Additional context?
Happens also when deleting contents folder only temporary fix is to install clean atmosphere but issue starts happening after few hours again. I also noticed it boots normally if I delete erpt reports folder

**Comment by SciresM** [comment]
Yeah, this isn't going to be an atmosphere issue. I'd try a different SD card, or recreate your emummc, or use fewer custom sysmodules.
