### ISSUE TITLE
Error Code: 2162-0002 Program 010000000000100C

### ISSUE THREAD

**Issue by AtumCone12** [Atmosphere-NX/Atmosphere#2236]
### What's the issue you encountered?
When I try to boot into CFW I get the atmosphere error screen, I didn't make any changes to atmosphere.

### How can the issue be reproduced?
The way to reproduce it would be to boot into CFW. Turning off the console and booting to the payload.

### Crash Report
There isn't a crash report.

![Crash](https://github.com/Atmosphere-NX/Atmosphere/assets/151410670/a2f5e8f4-1269-426f-8cb3-17c3920b8193)

This image is the crash screen I get when trying to boot into CFW

### System Firmware Version

17.0.0 OFW
16.0.2 CFW

### Environment?

I used TegraRCMGui and the bootloader is hekate.
I have the latest version of both hekate and atmosphere. The only homebrew software installed would be tinfoil, HB menu, Retroarch, Missioncontrol.
I am using a file-based EmuMMC

### Additional context?

Whenever I try to boot into it sometimes, I will be able to boot into CFW I don't know what triggers it. The first time it happened I was using Rekado to boot and thought that it was a problem with it then I used my pc and it worked fine but then I went back to OFW and after trying to boot into CFW after that I got the error again this time using TegraRCMGui on my pc.

**Comment by Masamune3210** [comment]
Please go back and actually fill out the issue template.

**Comment by AtumCone12** [comment]
> Please go back and actually fill out the issue template.

Done.

**Comment by SciresM** [comment]
Crash in overlay is with high certainty due to extra stuff you have installed like Tesla or whatever. Remove all custom sysmodules.
