### ISSUE TITLE
Fatal error after update to 17.0.0  | 1.6.2

### ISSUE THREAD

**Issue by Krypton1506** [Atmosphere-NX/Atmosphere#2237]
## Bug Report
I updated to 17.0.0 and 1.6.2 and after reload i got a fatal error.

A Fatal error occurred when running atmosphere.
Program ID: 4200000000000010
Error Desc: std: :abort( ) called (0xffe)

Report saved to /atmosphere/fatal_errors/report_0000000008cc43e7.bin
Press power to reboot.

### Crash Report
[report_0000000008cc43e7.zip](https://github.com/Atmosphere-NX/Atmosphere/files/13403901/report_0000000008cc43e7.zip)

### Environment?

- Bootloader: fusèe 
- Atmosphère launched by: Official release
- Do you have additional kips or sysmodules you're loading: Signatur-Patches
- SysNAND

**Comment by Masamune3210** [comment]
Delete the respective folder in atmosphere/contents.

**Comment by Krypton1506** [comment]
After i deleted the respective folder 4200000000000010 in atmosphere/contents i get this ne
![20231119_182310](https://github.com/Atmosphere-NX/Atmosphere/assets/151458674/b892d7ee-fbaa-422d-8c98-a820deb73767)
w error

**Comment by Krypton1506** [comment]
ok now its working
