### ISSUE TITLE
Crash when using title ID redirection for game title

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#224]
If you use title id redirection on a game you get a console crash that forces a restart.   
(talking about HBL nsp titleid redirection )
I am attempting to use the title id redirection to open the hbmenu in the context of an title so i can use retroarch with more memory and play N64 games.   however if you change hbl_tid=010000000000100D to be the ID of a title the console will crash.   Is this expected?  If not    is it possable im doing something wrong?

**Comment by mariogamer2** [comment]
I think it's a restriction of the replacement system (from the sdfiles discord). Don't remember on what tho.

**Comment by yellows8** [comment]
Latest nx-hbloader git?

**Comment by fennectech** [comment]
nx-hbloader is from the sdfiles.   it launches when opening via album but not an app like kitten squad

**Comment by SciresM** [comment]
Using HBL-as-application still needs HBL support for e.g. ApplicationType_Application as far as I know....

**Comment by yellows8** [comment]
*Needs* to be latest one from git.

**Comment by fennectech** [comment]
Okay   will update.

**Comment by yellows8** [comment]
"Using HBL-as-application still needs HBL support ..." <- Latest one from git does.

**Comment by fennectech** [comment]
@yellows8 okay after getting a new nx-hbloader.nsp from here http://bsnx.lavatech.top/nx-hbloader/ i get a different error "Unable to start software Return to the home menu and try again"  Sorry for the ping but i dont think closed issues get notifications

**Comment by yellows8** [comment]
"dont think closed issues get notifications" they do.

Is Home Menu displaying that? What title are you using / try a different one?

**Comment by fennectech** [comment]
good to know   im using kitten squad    what title should i try?     tried pokemon quest   No dice    trying skyrim

**Comment by fennectech** [comment]
The atmo build is from this morning   so    yeah

**Comment by fincs** [comment]
>  okay after getting a new nx-hbloader.nsp from here http://bsnx.lavatech.top/nx-hbloader/ 

That site isn't producing actual ExeFS NSPs, it's producing "installable" titles (akin to 3DS CIAs). Atmosphère expects ExeFS NSPs, which are what nx-hbloader's Makefile are supposed to build. Please try compiling nx-hbloader on your own, the generated hbl.nsp should be around 40KB (unlike the hundreds of KB of the NSPs in above link)

**Comment by fennectech** [comment]
Ive tried compiling but i get /home/fennectech/nx-hbloader/source/main.c:341:38: error: 'EnvAppletFlags_ApplicationOverride' undeclared (first use in this function); did you mean 'AppletType_Application'?
         entry_AppletType->Value[1] = EnvAppletFlags_ApplicationOverride;

I opened an issue there

**Comment by fennectech** [comment]
okay   That works   Kind of.    There is ui elements from the loading screen covering the hb menu   Shal i elaborate here or spit it into a seperate issue.

**Comment by fennectech** [comment]
-nevermind-  It only happened once.

**Comment by fennectech** [comment]
As a side effect most errors are cought by the title error handler (wich we can recover from by simply pressing okay and restarting.
