### ISSUE TITLE
Daybreak error 

### ISSUE THREAD

**Issue by taoufikkazay** [Atmosphere-NX/Atmosphere#2240]
I use a modded switch lite with chip 
Just updated my atmosphere fusee and Hecate to the latest version i want to update my emulated os to 17.0.0 and i got this error 
![RDT_20231119_2019426103939497953277372](https://github.com/Atmosphere-NX/Atmosphere/assets/10504892/b95c39d6-54d4-46d2-b90d-8ede9a7e490b)

**Comment by SciresM** [comment]
fs::ResultPortMmcDataCrcError().

Try a different SD card, this is a hardware issue.
