### ISSUE TITLE
Cheatcode feature: give me a way to increment and decrement float damn it

### ISSUE THREAD

**Issue by ImanCol** [Atmosphere-NX/Atmosphere#2243]
I need to rotate and move objects and most are represented as floats

**Comment by SciresM** [comment]
Duplicate of #934, which stalled on someone giving me a real spec. Also, you didn't use the issue templates.

**Comment by ImanCol** [comment]
You solved it right?  This article is from 4 years ago.

**Comment by ImanCol** [comment]
Modify Transform or 3-axis Vectors that are float.

Ah, that's what I meant by objects and their properties.  I also see many uses for it that I stopped being able to implement because floats cannot be increased or decreased in cheatcode.
