### ISSUE TITLE
Could not start the software. Please try again from the HOME Menu.

### ISSUE THREAD

**Issue by LapsTimeOFF** [Atmosphere-NX/Atmosphere#2244]
### What's the issue you encountered?

Animal Crossing (Legally obtained through eShop before the hack) cannot start, `Could not start the software. Please try again from the HOME Menu.` error message.
The game can be run through Stock - SysNAND, i use CFW - emuMMC

### How can the issue be reproduced?

- Boot up in CFW - emuMMC Atmosphere 1.6.2 FW 17.0.0
- Try launching Animal Crossing

### Crash Report

N/A

### System Firmware Version

FW 17.0.0, Atmosphere 1.6.2

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: official
  - 1.6.2
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: [ * ]
- EmuMMC or SysNAND: EmuMMC
  - I belive file based

### Additional context?

N/A

**Comment by SciresM** [comment]
Try re-downloading the game from the e-shop.
