### ISSUE TITLE
Homebrew crashing with error.  DXX Switch and tetriswitch

### ISSUE THREAD

**Issue by HexNoob2** [Atmosphere-NX/Atmosphere#2245]
### What's the issue you encountered?

Attempting to launch homebrew results in error code 2168-0002 for tetriswitch and 2144-0001 for DXX Switch
Instant, complete failure to boot.

### How can the issue be reproduced?

Load fusee as payload in Hekate and do Sys boot of Atmosphere, choose gallery in Atmosphere and get to hbmenu.  Choose a homebrew such as tetriswitch and instant error screen.  (Verified with sonic 1 2013 mobile port that homebrew does work)

### Crash Report
NA
![crash](https://github.com/Atmosphere-NX/Atmosphere/assets/137001513/b52b6928-a85c-4dba-9a48-e86ce254c5a0)
</br></br>

### System Firmware Version

17.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 6.07, Atmosphere 1.6.2 (fusee payload from release 1.6.2).  
- Do you have additional kips or sysmodules you're loading: NA
- Homebrew software installed: DXX Switch and tetriswitch
- SysNAND

### Additional context?

- Additional info about your environment: Lite with PicoFly 2.73

**Comment by HexNoob2** [comment]
[01701390584_0100000000001000.log](https://github.com/Atmosphere-NX/Atmosphere/files/13519162/01701390584_0100000000001000.log)
[01701390506_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/13519165/01701390506_010000000000100d.log)

**Comment by Aura67** [comment]
YOU have a custom theme active that says your error message 10000000001000000 delete the file 100000001000000 in the contents folder and then try to boot again. This is not an atmospheric error or a problem.

**Comment by HexNoob2** [comment]
> Do you have additional kips or sysmodules you are loading?

No, I even got a second SD card and only unzipped hekate+Atmosphere and the game (tetriswitch), same result

**Comment by SciresM** [comment]
If this is happening with specific homebrew, it is probably a problem with that homebrew and not with Atmosphere.

**Comment by HexNoob2** [comment]
> If this is happening with specific homebrew, it is probably a problem with that homebrew and not with Atmosphere.

I'm starting to get that impression, maybe I'll try retropie
