### ISSUE TITLE
After updating emuMMC to 17.0 via daybreak getting black screen after splashscreen.

### ISSUE THREAD

**Issue by brennschlus** [Atmosphere-NX/Atmosphere#2246]
### What's the issue you encountered?

After updating to 17.0 via Daybreak with latest atmoshere 1.6.2, I am getting black screen after splashscreen until full reset.

### How can the issue be reproduced?
1. Launch Daybreak
2. Press update on 17.0 firmware, preserve settings, reboot
3. Expected loading to atmoshere with 17.0 HW
4. Actual - black screen.

### System Firmware Version
Before updating system version is 16.1.0, atmoshere 1.6.2

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: tried both amtoshere 1.6.2 or kefir 714 with same atmoshere, same result.
- Do you have additional kips or sysmodules you're loading: none
- Homebrew software installed: [ dbi, daybreak, hb store, linkalho, nx themes]
- EmuMMC or SysNAND: EmuMMC, file based, FAT32 SD Card

### Additional context?

- Additional info about your environment: after completely new installment of atmoshere on fresh formated SD card with new emuMMC still same result.
- After system update via sytem menu in semi-stock it shows black screen on both semi-stock and full stock

**Comment by TTghostsemir** [comment]
1. kefir has piracy tools in it (@SciresM Piracy alert)

2. try to delete the complete Atmosphere folder and download the latest Atmosphere and put the folder in the Sd, and try to boot
