### ISSUE TITLE
Error 2001-0123(0xf601)

### ISSUE THREAD

**Issue by Sirethief2525** [Atmosphere-NX/Atmosphere#2253]
Ever since updating to ofw 17.0.1 atmosphere has been erroring out with the code seen in the title, I've updated all of the files to the latest version and still get this error as soon as the Nintendo screen appears, am I doing something wrong? And sorry about the last issue, I tried to move my keyboard to be more comfortable to type and must have hit enter on what was already there.

**Comment by SciresM** [comment]
I already responded to you in the other issue.
