### ISSUE TITLE
Atmosphere crash when running games with too many DLCs

### ISSUE THREAD

**Issue by gzwtidus46** [Atmosphere-NX/Atmosphere#2256]
### What's the issue you encountered?

When launching the game "Taiko No Tatsujin Nintendo Switch Version!", Atmosphere crashes with code 2162-0002.

### How can the issue be reproduced?

Simply launching the game "Taiko No Tatsujin Nintendo Switch Version!" (TitleId: 0100D9A005ED6000), version 1.4.13 (v2949210, BuildID: F9BD76E931737102), with all 325 DLCs. 

### Crash Report

https://gist.github.com/gzwtidus46/d21c24fd997ad03399477fca2a9adc1d

### System Firmware Version

17.0.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusee.bin
- Official release or unofficial build: official build Atmosphere 1.6.2, build f7bf379cf.
- Do you have additional kips or sysmodules you're loading: All have been disabled.
- Homebrew software installed: dbi, Hekate Toolbox
- EmuMMC or SysNAND: SysNAND.

### Additional context?

Fatal program ID is: 010000000000001f, however no folder "010000000000001f" in atmosphere/contents, and no custom theme applied. Also, no folder "0100D9A005ED6000" (game TitleId) in atmosphere/contents, i.e. no LFS mod for this game.

However, after uninstall all 325 DLCs, the game can be launched without problems.
The game work previously with firmware 16.1.0 and atmosphere 1.5.5.

- Additional info about your environment: Erista hardware.

**Comment by SciresM** [comment]
This looks like a crash in ns code...which isn't actually atmosphere code. 

Anyway, I suspect what's happening is that you're not actually installing this through the eshop, you're using some piracy software, and bypassing a built-in limit.

Piracy is not supported.

If this issue occurs using purchased DLC from the eShop, I'll investigate, but somehow I suspect that's not the case.
