### ISSUE TITLE
Brazillian portuguese language override not working

### ISSUE THREAD

**Issue by brenodantas10** [Atmosphere-NX/Atmosphere#2264]
### What's the issue you encountered?

Cannot override game locale to pt-BR (Brazillian Porturguese), only pt (Portuguese) using per-game override settings. Though changing the Switch's settings to Portuguese on region The Americas provides Brazillian Portuguese language to the game.

Tested on Super Marios Bros. Wonder's digital version (010015100B514000).

### How can the issue be reproduced?

Brazillian Portuguese Working
 - System settings config: region The Americas, language Português
 - No config.ini on the game's content folder
 - Result: Game is in Brazillian Portuguese

Brazillian portuguese not working
 - Change System Settings Language to English
 - Create a config.ini on game id's content folder with section override_config and key override_language to pt-BR
 - Result: Game is in English

Game in Portuguese (pt)
 - Create a config.ini on game id's content folder with section override_config and key override_language to pt
 - Result: Game is in Portuguese, but not Brazillian Portuguese

Region override does nothing to the language.

### Crash Report

N/A

### System Firmware Version

17.0.0

### Environment?

- Bootloader: fusèe
- Official release 1.6.2
- Sysmodules
  - Mission Control
  - sys-ftpd-light
  - Tesla
 - EmuMMC partition-based (32 GB)
 - Homebrew installed?
   - NX Locale Switcher
   - JKSV
   - NX-Shell
   - NXThemes (no themes installed though)
   - vgedit
   - RetroArch

### Additional context?

N/A

**Comment by SciresM** [comment]
Yep. That language was added in 10.1.0, and the settings-language stuff was last updated before that. Should be good now.
