### ISSUE TITLE
error code 2168 0002 programm 01000000FAF

### ISSUE THREAD

**Issue by Mefic21** [Atmosphere-NX/Atmosphere#2267]
Hi! I'm sorry that I may be writing incorrectly, but I just recently bought a console and there is such an error. I'm panicking and hysterical.

I didn't update it, it just took a reboot one day and that's it. After rebooting, it gives this error. It won't start, I can't log in. It's just this screen forever, and then a reboot and so on forever.
I haven't tried to do anything yet, delete, reset
![1zUFgDwyKgU](https://github.com/Atmosphere-NX/Atmosphere/assets/156136272/f501e72d-caac-4a44-b72a-faa69d75e350)

**Comment by Aura67** [comment]
go back and fill out issue templates

**Comment by Mefic21** [comment]
I framed it incorrectly.. Kill me.. If anything, I've solved the problem. Just delete the 01000000FAF file from the atmosphere
