### ISSUE TITLE
Mariko 17.0.1 Atmosphere stuck at Switch Logo (CFW/OFW and sysmmc/emummc)

### ISSUE THREAD

**Issue by Playasene94** [Atmosphere-NX/Atmosphere#2276]
### What's the issue you encountered?

From hekate 6.0.7 CFW or OFW Boot with fw 17.0.1 the switch logo gets stuck. 
In all boot modes same behaviour. Cannot enter Maintenance Mode too.

### How can the issue be reproduced?

Install/Rebuild Nand with 17.0.1 on both sysmmc/emummc (e.g. via TegraExplorer).
Then Boot via Atmosphere.

### Crash Report

I didnt get any crash report from AMS.

### System Firmware Version

17.0.1

### Environment?

Hekate and also fuse payload.
partition-based, emummc and sysnand

**Comment by borntohonk** [comment]
Ever messed with "Incognito", "Incognito_RCM", or have exosphere.ini with "blank_prodinfo_sysmmc/blank_prodinfo_emummc" set, or hekate with "cal0blank=1"?

if yes, restore original prodinfo or backup of nintendo switch, or disable those options listed.

if you cannot do either of those then:
https://suchmememanyskill.github.io/guides/unbrick/#early-boot-errors
https://suchmememanyskill.github.io/guides/unbrick/#mmc-rebuild

**Comment by Playasene94** [comment]
exosphere.ini those two parameters having set now to 0. trying it now. 
I did try sometimes with the network cables detached, but they are attached now. 
Where do i find cal0blank?

mmc i had rebuild earlier.

**Comment by Playasene94** [comment]
Issue still persists.

**Comment by Playasene94** [comment]
my hekate_ipl.ini

[config]
autoboot=0
autoboot_list=0
bootwait=0
verification=1
backlight=100
autohosoff=2
autonogc=0
updater2p=1


{--- Custom Firmware ---}
[CFW (SYSMMC)]
fss0=atmosphere/package3
kip1patch=nosigchk
emummc_force_disable=1
icon=bootloader/res/sysnand.bmp
{}

[CFW (EMUMMC)]
fss0=atmosphere/package3
kip1patch=nosigchk
emummcforce=1
icon=bootloader/res/emummc.bmp
{}

**Comment by Playasene94** [comment]
I did exactly that. but i cannot pass the logo screen.

**Comment by Playasene94** [comment]
i rebuilded my nand now once more following the lv2 guide from sthetix, and i can still not pass the logo screen.

**Comment by borntohonk** [comment]
> i rebuilded my nand now once more following the lv2 guide from sthetix, and i can still not pass the logo screen.

Are the prod.keys you're using to "rebuild the nand" dumped from your console? Because them not being from your console probably might probably be the root cause of your problems.

I suppose you're going to have to find a version of lockpick_rcm that is capable of outputting 17.0.0+ keys, as some of the keys EmmcHaccGen uses are console unique.

**Comment by Playasene94** [comment]
i rebuilded nand with my prod.keys.

**Comment by Playasene94** [comment]
This was a HW flaw, we got fixed, now i am able to boot into atmosphere on 17.0.1.
