### ISSUE TITLE
Atmosphere crashes on boot

### ISSUE THREAD

**Issue by plasticocelot123** [Atmosphere-NX/Atmosphere#2277]
## Bug Report

So, one day, I installed ovlloader, and some apps. I played some games on my switch, and everything was ok. I went into ovl-tune to pause my music. I clicked the button to exit the app, and atmosphere crashed.  So, I rebooted atmosphere, it crashed right after the switch logo. This continued to happen, every time I booted up atmosphere. If you are curious, the Program that is crashing the console has the id of: 420000000007E51A

### How can the issue be reproduced?

I have no idea how this happened. Therefore, I cannot recreate it currently.

### Crash Report

Strangely, when I went to find the crash report, there was no crash report, only ones I saw were from older crashes.

### System Firmware Version

17.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: Official
  - [ Official release version 1.6.2]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading: Yes, I am running a sysmodule, when I exited out of the sysmodule, it crashed.
- Homebrew software installed: [ yes ]
- EmuMMC or SysNAND: SysNAND

### Additional context?

- Additional info about your environment: I am banned from Nintendo, My console crashes when parental controls are enabled, Also running a few mods, as well as a couple of homebrew. My console is generally new, so I am very sad to see it already pretty much bricked.

**Comment by Aura67** [comment]
Is not a problem with Atmospehre there is a problem with nx-ovlloader, go to the developer who created this tool and report the problem to them. :--> https://github.com/WerWolv/nx-ovlloader/releases there report my Atmosphere on the switch it doesn't crash everything ok with Atmospehre alone.
