### ISSUE TITLE
A fatal error occurred when running Fusee - Invalid GPT Signature / Switch Logo Freeze

### ISSUE THREAD

**Issue by ghost** [Atmosphere-NX/Atmosphere#2278]
FW 17.0.1
Mariko
Hekate and Atmosphere Latest. 

After NAND Rebuild, can boot to OFW, but both CFW and Warmboot Fix fail to boot. 
In CFW, get fatal error (GPT Signature invalid)
In Warmboot Fix, Switch Logo Freeze.

512 GB Fat32 Sandisk Extreme Pro.

**Comment by NMakin-TCAM** [comment]
I am getting the same issue.  I can run Atmosphere with the Lockpick_RCM.bin payload but fusee.bin shows that GTP error.  Same versions as the OP

**Comment by SciresM** [comment]
Closing due to lack of issue templates, but I note "NAND rebuild" -- GPT header needs to be in two places, probably you didn't re-build NAND correctly.
