### ISSUE TITLE
wake from sleep crash on 4.1.0

### ISSUE THREAD

**Issue by mexxs** [Atmosphere-NX/Atmosphere#228]
I was really excited today when I found out you released 0.7. So I had to try it right away.
It booted up and worked perfectly. But when I sent my Switch to sleep and removed the USB cable it turned on the screen which was black and I could only force it to shutdown by holding the power button. Then I booted 0.7 a second time and removed the USB cable from the Switch before going to sleep. That was no problem. But when I sent it into sleep mode and tried to wake it up again I got the same black screen as before. If you need more info let me know. I appreciate all your hard work on this. Thank you very much!

**Comment by SciresM** [comment]
@mexxs I believe this is fixed by f9f9997d -- can you test?

**Comment by mexxs** [comment]
Works perfectly now. Thanks very much!
