### ISSUE TITLE
Error 0x4A2 (2162-0002)

### ISSUE THREAD

**Issue by piwyyy** [Atmosphere-NX/Atmosphere#2281]
![17076563291565888533282715679861](https://github.com/Atmosphere-NX/Atmosphere/assets/159700181/750b326e-bc76-425e-b432-41a38a42fc7f)
It was fine yesterday. I woke up and wanted to play but my internet was off, when I open my net settings it just crashes and it does the same when I open a game.

**Comment by Masamune3210** [comment]
please go back and actually fill out the issue template
