### ISSUE TITLE
Incorrect fusee version! (program=0x4aa02b53,  mtc=0x00000000)

### ISSUE THREAD

**Issue by cantindylan** [Atmosphere-NX/Atmosphere#2283]
## Bug Report

Injecting fusee to launch atmosphere and consistently run into this failure.

### What's the issue you encountered?

After replacing the fusee, atmosphere version, and hekate making sure everything was correct, I still run into the message in the title. I'm using TegraRCM mostly but i did try through hekate too. 

### System Firmware Version

17.0.1

### Environment?

Official builds, using Fusee, file based EmuMMC

### Additional context?

This is the 3rd switch I've homebrewed and haven't encountered this issue before.

**Comment by Masamune3210** [comment]
Invalid fusee/atmosphere combo. Either you are launching atmos with a old fusee or you are launching fusee with a old atmos. Make sure that you update the payload in the correct places, it sounds like you are accidentally still using the old fusee.

**Comment by cantindylan** [comment]
> Invalid fusee/atmosphere combo. Either you are launching atmos with a old fusee or you are launching fusee with a old atmos. Make sure that you update the payload in the correct places, it sounds like you are accidentally still using the old fusee.

You would think. I’ve triple checked. I don’t understand how. Used the latest Atmos and the corresponding fusee :/

**Comment by Masamune3210** [comment]
Well, afaik, that's the only codepath that would cause that error. Not sure what else to tell you really, somehow, you are causing a mismatch

**Comment by Aura67** [comment]
Download the latest releases from Atmospehre and the fusee.bin and unpack them on your SD card. If he asks you if you want to overwrite it, just say yes, done. Then simply start atmospehre with fusee.bin.

**Comment by cantindylan** [comment]
I've done this time after time still being met with the same screen. Is ther anything I could be overlooking to cause the misalignment? I've overwritten everything and using the most current version of fusee.

**Comment by borntohonk** [comment]
> I've done this time after time still being met with the same screen. Is ther anything I could be overlooking to cause the misalignment? I've overwritten everything and using the most current version of fusee.

put fusee.bin in /bootloader/payloads/fusee.bin
launch hekate, click the payloads button on the screen, click fusee.bin

if it launches successfully then you're definitively not injecting the correct payload.

**Comment by beyondmeat** [comment]
You have to replace the fusee.bin that you are using as your payload in tegra, my guess is you didn't do that and still sending an old fusee with tegrarcm
