### ISSUE TITLE
nim patch to allow PRODINFO blanking on 17.0.0+

### ISSUE THREAD

**Issue by fruityloops1** [Atmosphere-NX/Atmosphere#2284]
#### Overview:
- A patch that disables the user abort in the nim service caused by blanking your PRODINFO and enabling Wi-Fi.

#### Smaller Details: 
- I've implemented a simple version of the patch myself [here](https://github.com/fruityloops1/nim-prodinfo-blank-fix), it just stubs a function in nim dedicated to causing this abort.

#### Nature of Request:  
- Addition

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)

### Why would this feature be useful?
- This allows those who use PRODINFO blanking to use 17.0.0+

**Comment by SciresM** [comment]
I'm not interested in maintaining or making official this patch, sorry. You can always use it locally yourself, though.

**Comment by fruityloops1** [comment]
makes sense
