### ISSUE TITLE
Error Code: 2162-0002 (0x4a2)

### ISSUE THREAD

**Issue by Monster2239** [Atmosphere-NX/Atmosphere#2286]
### What's the issue you encountered?

I was trying to load the TI-83 RetroArch core, which caused the app to crash. 
I then attempted to restart RetroArch via overriding Sonic Superstars, but as soon as the game tried to open, the system crashed.

This same crash now happens as soon as I try to boot into any official software or homebrew software, as well as happening across both Horizon and Atmosphere. 
All applets still work, but when trying to open anything through the Homebrew Launcher applet, it also immediately crashes the whole system.

No changes were made to Atmosphere.

### How can the issue be reproduced?

N/A

### Crash Report

https://gist.github.com/Monster2239/468f3dfc67eba3790cbaf890fd8ca910

### System Firmware Version

17.0.1</br>

### Environment?

- Hekate
- Official Build
  - Atmosphere Ver. 1.6.2

### Additional context?

I checked if deleting the custom theme folder (D:/atmosphere/contents/0100000000001000) would fix the issue as said in post #736, but it didn't.

Unsure if it's related, but I'm unable to download software updates for any games even after disabling 90DNS.
Not that it matters since I can't get into a game anyhow.

**Comment by borntohonk** [comment]
> This same crash now happens as soon as I try to boot into any official software or homebrew software, as well as happening across both Horizon and Atmosphere.

By horizon do you mean booting without atmosphere...?

Are you an emummc/emunand user? 
is your microSD card exfat formatted? Because retroarchs usage instructions very specifically asks for it to be fat32, or face risk of corrupting your microSD card. (if yes, do a full reformat of sd card to fat32)

**Comment by Monster2239** [comment]
> > This same crash now happens as soon as I try to boot into any official software or homebrew software, as well as happening across both Horizon and Atmosphere.
> 
> 
> 
> By horizon do you mean booting without atmosphere...?
> 
> 
> 
> Are you an emummc/emunand user? 
> 
> is your microSD card exfat formatted? Because retroarchs usage instructions very specifically asks for it to be fat32, or face risk of corrupting your microSD card. (if yes, do a full reformat of sd card to fat32)
> 
> 
> 
> 

I already formatted it to Fat32 beforehand.

**Comment by LNLenost** [comment]
Got same error when booting on emummc on 18.0.

**Comment by SciresM** [comment]
user-break in playerSelect shouldn't be anything atmosphere related, it'll be user-setup related. Not that that matters, given how old this is, heh...
