### ISSUE TITLE
The dreaded 0xffe fatal error!  

### ISSUE THREAD

**Issue by baqlias** [Atmosphere-NX/Atmosphere#2287]
I have a V1 Switch with an SD file emuMMC set up. I had made a full backup of the sd card's contents. The sd card is in FAT32 format. I accidentally wiped that card, thinking it was another card. I then copied all the files and folders of my backup back onto the sd card. When I booted the Switch into RCM and then launched the emuMMC, I started encountering this error. 

I am running the latest Hekate and Atmosphere.  

I have tried the archive bit fix (since I use a Mac) and that didn't solve the problem. I have deleted the Atmosphere folder and reinstalled it. Same problem.  Maybe the fatal error report will show you something helpful!  
[report_000000000aa8ec9f.bin.zip](https://github.com/Atmosphere-NX/Atmosphere/files/14467762/report_000000000aa8ec9f.bin.zip)

**Comment by SciresM** [comment]
`fs::ResultInvalidFatFormatSd()`

I'm sure you've resolved this by now, since I'm only responding to it...4 months late...but you just need to reformat your SD card, which has a corrupted fat partition. Or, it's formatted as exFAT and you're booting with FAT32 firm.
