### ISSUE TITLE
USB Microphones not working on AMS CFW but works on OFW (lot of tests)

### ISSUE THREAD

**Issue by MrCanan** [Atmosphere-NX/Atmosphere#2289]
### What's the issue you encountered?

On CFW, there is no more input sound detected from any USB microphones on the Switch dock, so I can't play anymore to all Let's Sing games
> No change to Atmosphere itself

### How can the issue be reproduced?

Every time I want to use a USB microphone in a game on CFW, like Let's Sing (all versions)
> Simply connect it and start any song

### Crash Report

N/A
> No log, simply no input sound from USB microphone in-game

### System Firmware Version

17.0.1 AMS (lastest actually)

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: 
  - Official release version 1.6.2 (lastest actually)
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: N/A
- EmuMMC or SysNAND:
  - file-based EmuMMC

### Additional context?

- Additional info about your environment:
N/A

### My tests

I have tested :
- all USB ports on the dock
- with three different dock
- with two official Let's Sing USB microphone
- with various versions of Let's Sing XCI/NSP games
- with two best-seller USB microphones for Switch from Amazon (5 stars with 5000+ reviews)
- with three differents Switch (all under the same AMS and CFW)
> All USB microphones work on PCs, consoles, etc.

Results on the CFW :
> Never works

Results on the OFW :
> Always works

### Additional informations

It works with both Companion applications for OFW/CFW
- Android: https://play.google.com/store/apps/details?id=com.voxler.letssingcompanionapp
- Apple: https://apps.apple.com/us/app/lets-sing-companion/id6450531685

> I found a lot of different people with the same issue, but still no answers on Reddit, Github, etc.

**Comment by borntohonk** [comment]
I guess you don't want this to be resolved as you mention piracy in your github issue again, too bad.

**Comment by MrCanan** [comment]
Hi,

I see no problems with piracy in my post
The aim is to help to solve this issue, so if you see some, simply tell me it to let me edit them

> I edited to add all tests and asked informations/tests

**I have the original games, so I have the right to play to XCI/NSP versions**

**Comment by zemixe** [comment]
Piracy is not supported.

**Comment by borntohonk** [comment]
> **I have the original games, so I have the right to play to XCI/NSP versions**

again, too bad you have to mention that in this github issue, and don't want this to be resolved. Unfortunate.

**Comment by MrCanan** [comment]
Hi,

If that's the only thing that bothers you, then the real problem is that you don't know the law

> **There is nothing illegal about owning and using XCI/NSP, if and only if you bought the game, so no problem using these terms**

So I still don't see any privacy issues, and if anyone sees a real one, tell me to solve it, otherwise, I can't guess it

> It would be good if an Atmosphere Team could participate because it would certainly be more useful for this topic and for the community (a lot person have the problem, have a look on Reddit)

Thank in advance

**Comment by SciresM** [comment]
Piracy is not supported.
