### ISSUE TITLE
Cart launching crash on firmware 1.0.0

### ISSUE THREAD

**Issue by yuukieve** [Atmosphere-NX/Atmosphere#229]
With the latest release of Atmosphère, cart titles do not seem to be able to be launched normally on firmware 1.0.0; attempts to launch a cart will result in the console crashing with 2001-0106. I tested with a Japanese Puyo Puyo Tetris S cart that launches normally on OFW.  This issue may also effect digital titles, but I do not have any myself to test. The issue can be mitigated temporarily by launching a cart title while holding R; after that the cart title can be launched normally (without holding R). However, if hbmenu is launched and then exited, the problem will return.

**Comment by SciresM** [comment]
Addressed by https://github.com/switchbrew/libnx/pull/188.
