### ISSUE TITLE
Could not start the software. Please try again from the HOME Menu

### ISSUE THREAD

**Issue by The-Dark-Ranger28** [Atmosphere-NX/Atmosphere#2297]
Updated atmosphere to the latest release. Switch turns on just fine, but I cannot open any game, always getting the error message in the title of this post. 

Anyone know a solution for this? I’ve tried updating sigpatches through the app, to no avail.

**Comment by masagrator** [comment]
Piracy is not supported.

**Comment by The-Dark-Ranger28** [comment]
> Piracy is not supported.

When did I say I pirated? I own these games. I’ve been banned from the eshop though, so can’t redownload them.

**Comment by SciresM** [comment]
Signature patch usage is piracy.
