### ISSUE TITLE
Kip only version?

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#230]
Would you consider providing an update with the kips instaid of a single fusee-secondary.bin so we can directly load from hekate instaid of having to chainload it/

**Comment by tumGER** [comment]
We have other CFWs for that (or packages ;^) ) - Atmosphere is focused on using fusee

**Comment by SciresM** [comment]
Hekate is for advanced users. I don't think it's unreasonable to ask hekate users to aggregate stuff themselves -- keep in mind, Atmosphere is more than just the stratosphere KIPs, it's also exosphere (+ thermosphere, mesosphere in the future).

**Comment by ThatNerdyPikachu** [comment]
Mesosphere?

**Comment by mariogamer2** [comment]
Future re-implementation of the switch kernel.
