### ISSUE TITLE
No longer able to use Switch-OC-Suite I think

### ISSUE THREAD

**Issue by MrSuperdudly1** [Atmosphere-NX/Atmosphere#2300]
In 17.0.1 I was using Switch-OC-Suite because default sys-clk (as far as I know) doesn't allow for ram overclocking and switch-oc-suite can overclock higher.

To use it there is a kip file you have to add in atmoshphere\kips\loader.kip and you have to add a few lines in bootloader\hekate_ipl.ini

I think this is preventing the switch from booting. 

Plz help, sys-clk is nice but switch-oc-suite is sooooo much nicer. Thank you <3

**Comment by borntohonk** [comment]
> To use it there is a kip file you have to add in atmoshphere\kips\loader.kip and you have to add a few lines in bootloader\hekate_ipl.ini

neither of those are atmosphere related issues, go here https://github.com/hanai3Bi/Switch-OC-Suite/issues
