### ISSUE TITLE
Normal sys-clk manager crashes immediately upon launch in 18.0.0

### ISSUE THREAD

**Issue by MrSuperdudly1** [Atmosphere-NX/Atmosphere#2301]
The sys-clk module shows up using the Tesla Overlay but when trying to launch the sys-clk manager the switch crashes immediately.

**Comment by borntohonk** [comment]
why would you file an issue at the appropriate git repository and then make another issue here when it clearly isn't atmosphere related?

**Comment by josete2k** [comment]
2.0.0 rc working here...

Not an AMS issue

https://github.com/retronx-team/sys-clk/releases/tag/2.0.0-rc

**Comment by SciresM** [comment]
None of this is an atmosphere problem.
