### ISSUE TITLE
Crash when loading edizon

### ISSUE THREAD

**Issue by secfault** [Atmosphere-NX/Atmosphere#2303]
Check my error page it happen after loading last version of tesla and Edizon.
![IMG_20240331_030405](https://github.com/Atmosphere-NX/Atmosphere/assets/37829347/cb76c236-92f1-43db-aead-bfd9cca3ac92)

**Comment by borntohonk** [comment]
Why file this issue here, and not at the github repository where you obtained edizon / tesla?

**Comment by SciresM** [comment]
This is a tesla issue, not an atmosphere issue.
