### ISSUE TITLE
Black Screen After Booting AMS 1.7.0

### ISSUE THREAD

**Issue by NotOnii** [Atmosphere-NX/Atmosphere#2304]
### What's the issue you encountered?

After updating to firmware 18.0.0, I installed Atmosphère 1.7.0 Pre-release. I also updated Hekate Bootloader to v6.1.1 and made sure I'm using the latest Hekate and fusee payloads. I booted into Hekate and launched my EmuMMC CFW boot config that I've been using for a while with no prior issues whatsoever, only to see the Atmosphère logo appear for a split second before my Switch went into a soft-brick state. Attempting a power cycle didn't work, booting into maintenance mode yields no results, and TegraRCM doesn't detect RCM no matter what I try. Draining the battery hasn't worked, nor has charging the console for three hours. Docking the console makes the dock's green LED flash for a split second before turning back off.

### How can the issue be reproduced?

- Install OFW 18.0.0
- Update Atmosphere from 1.6.2 Release to 1.7.0 Pre-Release and replace old fusee.bin with latest (Pre-release 1.7.0)
- Update Hekate Bootloader to v6.1.1
- Inject latest Hekate payload and launch EmuMMC CFW
- Wait for the Atmosphère logo to appear for a split second before the Switch no longer displays anything on-screen

### Crash Report

N/A (No crash reports found)

### System Firmware Version

18.0.0</br>

### Environment?

- Bootloader used: Hekate
- Official Pre-Release 1.7.0
- EmuMMC CFW
- Homebrew Apps Installed: Default (whatever comes with 1.7.0)
- No additional sysmodules
- Updated to 18.0.0 through Nintendo Servers

### Additional context?

N/A

**Comment by SciresM** [comment]
The issue templates is for bugs, not for support...this kind of thing is resolved 99% of the time by re-cloning a fresh emummc. If that doesn't fix it, come seek support on discord.
