### ISSUE TITLE
Crash on Atmosphere boot-up :[

### ISSUE THREAD

**Issue by Lukey10** [Atmosphere-NX/Atmosphere#2305]
Error code: 2162-0002 [0x4a2]
Program: 010000000001000
Firmware: 18.0.0 [Atmosphere 1.7.0 master-31ad4eec1]

idk what I'm doing wrong.
Environment: fuseé.bin latest version

**Comment by Aura67** [comment]
It's not an Atmosphère problem for me, Atmosphère boots without any problems. You have a custom theme active, delete 010000000001000 then it should boot and work again. And you're supposed to fill out the form, but you didn't.

**Comment by SciresM** [comment]
You didn't use the issue templates, also this is a custom theme issue.
