### ISSUE TITLE
Atmosphere Blue Screen

### ISSUE THREAD

**Issue by 1994mazda** [Atmosphere-NX/Atmosphere#2308]
after loading into hekate and launching the CFW EMUMMC it loads a blue screen   
and when i try loading into fusee.bin as a payload it says  a fatal error occurred when running fusee unable to identify package1! 
I had accidentally updated to latest switch update and as such I stared by up dating atmosphere and hekate and now I have these problems  help would be apricated  btw i have a modded lite so i cant boot into RCM with a jig

**Comment by Shadow322** [comment]
update fusee.bin

**Comment by 1994mazda** [comment]
i did but it says  A fatal error has occurred when running Fusee Unable to identify package1! 
so idk what to do next

**Comment by 1994mazda** [comment]
idk how but i fixed it
