### ISSUE TITLE
Stuck while loading CFW

### ISSUE THREAD

**Issue by Insaane91** [Atmosphere-NX/Atmosphere#2312]
## Bug Report

Atmosphere stucks on SWITCH logo while loading

### What's the issue you encountered?

The problem occurs when I turn off the console for a long time and then turn it back on. In HEKATE I choose CFW (OFW works without any problems) and it hangs on the SWITCH logo. When I upload the ATMOSPHERE folder from the latest HATS package, everything works without any problems, but when I upload the ATMOSPHERE folder from the official package, it throws error 2123-0011. I used 90dns SETTER and everything works fine, after 15 seconds there is no error. I managed to use it in 15 seconds :).

The problem with SWITCH logo freezing exist only when I turn off console. This problem came suddenly but I can connect it with my try using "linkalho.nro"

### Crash Report

No crash reports on console 

### System Firmware Version

hekate 6.1.1
Atmo 1.7.0
FW 17.0.0
Sysnand
Tinfoil

**Comment by borntohonk** [comment]
Apparently "hats package" you've mentioned is a pirate package, as is tinfoil.

no support for piracy.
