### ISSUE TITLE
It keeps crashing while giving this error code

### ISSUE THREAD

**Issue by Archangeljay** [Atmosphere-NX/Atmosphere#2314]
It's crashing anytime i try to enter the applet/nonapplet page however that started after trying to connect to wifi for awoo also giving this error code 2123-0011 (0x167b)

**Comment by borntohonk** [comment]
> 2123-0011
https://github.com/Atmosphere-NX/Atmosphere/issues/2225#issuecomment-1831441277

undo incognito (?) or disable blanker in exosphere.ini
