### ISSUE TITLE
Status Monitor Overlay causes switch to softlock

### ISSUE THREAD

**Issue by djasindra** [Atmosphere-NX/Atmosphere#2316]
After updating my switch to 
Hekate 6.11
AMS 1.7
Firmware 18.0

My switch will softlock/hang when I open Status Monitor with Tesla Overlay while running games, it happens most of the time and rarely runs fine.

I am running the latest version of tesla and status monitor.

I'm not sure if it's caused by the overlay itself or Atmosphere. I couldn't get any error report because the switch screen just stuck there and can only be force shut down by holding the power button.

**Comment by SciresM** [comment]
1) you didn't use the issue templates
2) talk to the developer of the custom stuff you're using.
