### ISSUE TITLE
2105-0602

### ISSUE THREAD

**Issue by iblu90** [Atmosphere-NX/Atmosphere#2317]
Crash happens when I wake up system from sleep.

Latest atmosphere, latest hekate.

Not using any themes

Error code: 2105-0602
Program: 
![20240417_204416](https://github.com/Atmosphere-NX/Atmosphere/assets/99559585/68076b5c-fe48-427d-b1eb-925634657233)
0100000000001000

**Comment by antonwe** [comment]
you either have corrupt files on your sdcard or a picofly chip with wrong resistors interfering with emmc communication. not an atmosphere issue
