### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by impeeza** [Atmosphere-NX/Atmosphere#2319]
### What's the issue you encountered?

My current setup is an unpatched Erista Console with Hekate 6.1.1 and Atmosphère 1.7.0 prerelease, both downloaded from their GitHub releases pages.  Firmware 17.0.1

I mainly uses File Based EmuNAND

I start my console using original RCM Loader.

Randomly with the console on original deck on sleep during games weird crashes occurs, the console remain on black screen but get warm and completely unresponsive.

The only way to make it get back working is pressing the power button for 20 secs and power it again.

With the exactly same setup but going back to Atmosphère 1.6.2 the crashing stopped

Tested my card making a backup of all files, formatting the card, and tested completely using H2TestW and no errors found,  I used the Hekate to format back the card to FAT32 and restore the files, no need to archive bit repair.

I don't know if is something weird on my setup or some type of memory leak on Atmosphère, making the bug report just for let people to know my problem and be take in account if something could be happening.

**Comment by SciresM** [comment]
Closing this due to lack of details...I would guess this is most likely some kind of custom sysmodule problem, black screen during sleep is usually a psc acknowledgement failure.
