### ISSUE TITLE
0100000000000001 Error

### ISSUE THREAD

**Issue by naldo29** [Atmosphere-NX/Atmosphere#2320]
### What's the issue you encountered?

Heres what happenend. After successfully modding my console and closing it up. I went into atmosphere and used it for a bit but then out of no where my console turned off, and now when i turn it on its now showing error 0100000000000001.

### How can the issue be reproduced?
By turning on the console

### Crash Report
[report_0000000006113d3f.zip](https://github.com/Atmosphere-NX/Atmosphere/files/15145086/report_0000000006113d3f.zip)

### System Firmware Version
18.0.0

### Environment?
Official Release
EmuMMC or SysNAND:
Sysnand

**Comment by SciresM** [comment]
That report does not match the official pre-release's loader binary, and I think it's likely bogus.

Please try deleting your atmosphere directory and using the latest pre-release zip with absolutely zero add-ons or modifications?

**Comment by naldo29** [comment]
[report_000000000810d6b5.zip](https://github.com/Atmosphere-NX/Atmosphere/files/15145150/report_000000000810d6b5.zip)
My bad for uploading the wrong file. I think this one should be the correct one

**Comment by SciresM** [comment]
Do you have custom sysmodules? Please post a screenshot of atmosphere/contents and atmosphere/kips, if either dir is present.

**Comment by naldo29** [comment]
i have kip_patches, but this is a brand new atmosphere install. all i did was download atmoshpere and hakete and thats it. thas all on the sd card. Nothing else

**Comment by SciresM** [comment]
remove kip_patches, delete literally everything.

**Comment by SciresM** [comment]
Please post screenshots of your unmodified atmosphere directory to confirm.

**Comment by naldo29** [comment]
![image](https://github.com/Atmosphere-NX/Atmosphere/assets/35706559/fe751360-821f-4887-b6b3-cc6249e0a23a)
like this?

**Comment by SciresM** [comment]
...okay, extract the latest pre-release zip. You do need to have atmosphere present, just no add-ons.

**Comment by naldo29** [comment]
![image](https://github.com/Atmosphere-NX/Atmosphere/assets/35706559/c2bc394d-a904-4234-95fd-53a88fe1063e)
i deleted everything and extracted the latest release.

**Comment by SciresM** [comment]
Okay. What happens when you try to boot the console?

**Comment by naldo29** [comment]
Dont i need hakete to boot it up? i tried renaming the fusee.bin file as payload.bin so that the chip could use it but it does nothing.

**Comment by SciresM** [comment]
If you are booting on a mariko unit, fusee must be chainloaded via hekate, yes. I did not assume you were booting on a mariko unit.

**Comment by naldo29** [comment]
My apologies for not stating that. anyways the same issue did happen. but now its a different error id
[report_000000000e02e4f3.zip](https://github.com/Atmosphere-NX/Atmosphere/files/15145367/report_000000000e02e4f3.zip)

**Comment by SciresM** [comment]
That report is yet another case of https://github.com/Atmosphere-NX/Atmosphere/issues/1256.

You have a corrupt PRODINFO or system settings save, you'll need to delete the system settings save and/or flash a non-corrupt PRODINFO. Anyway, this isn't an atmosphere bug, at this point.

**Comment by SciresM** [comment]
I am guessing that your previous loader crash resulted from corruption-on-sd-card causing bad loader kip .text.
