### ISSUE TITLE
If you accidentally make hosts folder a file it will make atmosphere emuMMC panic on startup

### ISSUE THREAD

**Issue by obnoxiousish** [Atmosphere-NX/Atmosphere#2323]
I am not 1000% sure this is the cause, but i fixed it and it removed my panic, i guess its technically not a bug because its meant to be a folder and i made it a file but, at the very least maybe shipping the release with a hosts folder inside incase someone more dumb then me does it and cant figure out how to fix it or add a proper error message instead of FATAL ERROR with a bin file as a log 

Thanks for ur consideration, and thanks for your work on the project

**Comment by SciresM** [comment]
I think a fatal error with a log is the right thing to do in this case.
