### ISSUE TITLE
Cannot boot into CFW after Installing 18.0.0 update using Daybreak

### ISSUE THREAD

**Issue by Yorisoft** [Atmosphere-NX/Atmosphere#2326]
### What's the issue you encountered?

Unable to boot unto emuMMC. I downloaded the 18.0.0 firmware update to my sd, used day break to install it. I believe I choose an incorrect option. I choose exFat+Fat32, I believe I should have choosen FAT32. Now Im unable to boot into emummc or Fusee. 

[ Did you make any changes related to Atmosphère itself? ]</br>
None. 

### How can the issue be reproduced?

While emuMMC is on 17.0.1, and hetake on 6.1.1 launch into emuMMC and use Daybreak to install firmware 18.0.0. Select exFAT+FAT32. Im not positive but I believe the issue was selecting the incorrect option for sdcard format.

### Crash Report
Atmosphère Fatal Report (v1.1):
Result:                          0x4A2 (2162-0002)

Program ID:                      010000000000100a
Process Name:                    LibAppletWe
Firmware:                        17.0.1 (Atmosphère 1.7.0-master-31ad4eec1)
General Purpose Registers:
         FP:                     0000001a1fae9b90
         LR:                     000000316b7804e0
         SP:                     0000001a1fae9b90
         PC:                     000000316b79dcc8
Start Address:                   000000316b200000
Stack Trace:
        ReturnAddress[00]:       28e52b316b49ac7c
        ReturnAddress[01]:       aa66d1316b49a524
        ReturnAddress[02]:       cff400316b49a694
        ReturnAddress[03]:       3cbd53316b30454c
        ReturnAddress[04]:       fa5458316b302bb4
        ReturnAddress[05]:       d7eb20316b302d60
        ReturnAddress[06]:       d60e94316b302da0
        ReturnAddress[07]:       115b76316b302dec
        ReturnAddress[08]:       2e60b1316ba38000
        ReturnAddress[09]:       78569d316ba017e8
        ReturnAddress[10]:       0b9ff6316ba01758
        ReturnAddress[11]:       3d38ec316b49a2a4
        ReturnAddress[12]:       ff4ecd316b2000d8
Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                             001a1fae9b90 30 9c ae 1f 1a 00 00 00 7c ac 49 6b 31 2b e5 28
                             001a1fae9ba0 01 01 00 00 00 00 10 00 0c 00 00 80 01 00 00 00
                             001a1fae9bb0 03 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             001a1fae9bc0 05 00 00 00 00 00 00 00 00 00 00 00 08 00 00 00
                             001a1fae9bd0 00 00 00 00 14 00 00 00 00 00 20 6b 31 00 00 00
                             001a1fae9be0 00 d0 86 00 00 00 00 00 03 00 00 00 00 00 00 00
                             001a1fae9bf0 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             001a1fae9c00 18 9c ae 1f 1a 00 00 00 15 00 00 00 00 00 00 00
                             001a1fae9c10 00 81 d9 6b 31 00 00 00 50 02 00 00 00 00 00 00
                             001a1fae9c20 a0 9b ae 1f 1a 00 00 00 00 02 41 38 73 00 00 00
                             001a1fae9c30 a0 9c ae 1f 1a 00 00 00 24 a5 49 6b 31 d1 66 aa
                             001a1fae9c40 60 2d 30 6b 31 20 eb d7 98 9e ae 1f 1a 00 00 00
                             001a1fae9c50 76 2c a9 6b 31 00 00 00 00 00 00 00 00 00 00 00
                             001a1fae9c60 30 52 d0 6b 31 00 00 00 40 53 d0 6b 31 00 00 00
                             001a1fae9c70 d8 9c ae 1f 1a 00 00 00 00 00 00 00 00 00 00 00
                             001a1fae9c80 70 52 d0 6b 31 00 00 00 ec 2c af 6b 31 00 00 00
TLS Address:                 0000007338410200
TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                             007338410200 06 00 10 00 0c 00 00 80 01 00 00 00 fc 01 02 00
                             007338410210 00 00 00 00 50 02 00 00 00 81 d9 6b 0c 00 00 10
                             007338410220 53 46 43 49 01 00 00 00 02 00 00 00 00 00 00 00
                             007338410230 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             007338410240 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             007338410250 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             007338410260 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             007338410270 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             007338410280 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             007338410290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             0073384102a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             0073384102b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             0073384102c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             0073384102d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             0073384102e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                             0073384102f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

### System Firmware Version

report says 17.0.1, I tried installing 18.0.0 </br>

### Environment?
Hetake 6.1.1, launch option emuMMC

**Comment by SciresM** [comment]
Re-clone your emummc.

that's the wrong report, btw.
