### ISSUE TITLE
Fatal error  010000000000002b Std::abort <0xFFE>

### ISSUE THREAD

**Issue by Purpld** [Atmosphere-NX/Atmosphere#2329]
### What's the issue you encountered?

Keep getting error code labeled 
 title Id: 010000000000002b
Error:     Std::abort<0xFFE>

I didn't have a backup of my eMMC due to not big enough storage on my computer so I decided to just clean wipe and redo my switch mod I did it but then I get the exact same error message

### How can the issue be reproduced?
To be honest I don't know what has happened I clicked load on a game I went to the bathroom came back and I spit me this but I had literally just put my switch out of sleep mode then loaded it so I really don't know
If it helps the game was unturned

### Crash Report

github wont let me upload the file as a gist for some reason but if you need it its in a file.io https://file.io/tuvdLtXqqU6G
### System Firmware Version

I can't find this out because I can't even load into atmosphere
### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
Official release
Atmosphère 1.7.0-prerelease
This github page
loading:
eMMC

### Additional context?

N/A

**Comment by Purpld** [comment]
And if your wondering yes I looked at the other closed GitHub issue that was solved but I tried it all before I reset it didn't work

**Comment by borntohonk** [comment]
> And if your wondering yes I looked at the other closed GitHub issue that was solved but I tried it all before I reset it didn't work

see https://github.com/Atmosphere-NX/Atmosphere/issues/2029#issuecomment-1414732456
