### ISSUE TITLE
Is there a guide to install this to a real Nintendo switch device?

### ISSUE THREAD

**Issue by garymaxallen** [Atmosphere-NX/Atmosphere#2333]

**Comment by Aura67** [comment]
yes it is for the Nintendo Switch you can check here: https://ismyswitchpatched.com/ whether your console is patched or not if it is patched you need a modchip to run this. And no, the CFW is not fake.

**Comment by SciresM** [comment]
Atmosphere doesn't provide guides on running it, yeah.
