### ISSUE TITLE
SSBU/PKMN SW/SH both crash when launching 

### ISSUE THREAD

**Issue by Mrgamer2240** [Atmosphere-NX/Atmosphere#2334]
The mods work, but when I put them in atmosphere/contents/01008DB008C2C000 And 01006A800016E000. When I do this it follows up with "The Software was Closed due to an error" I'm stuck on this and I can't get in without removing the file from contents which defeats the purpose.

**Comment by SciresM** [comment]
This isn't an atmosphere issue.

**Comment by Mrgamer2240** [comment]
Then what is it then? I can't launch my mods.

**Comment by Moddedmyth** [comment]
Same here.

**Comment by masagrator** [comment]
Ask mods authors. And provide them more info than you did here.
