### ISSUE TITLE
All Modified Games Crash when in Atmosphere/Contents folder

### ISSUE THREAD

**Issue by Moddedmyth** [Atmosphere-NX/Atmosphere#2335]
What's the issue you encountered?
Having mods active when launching a game results in the "The software was closed due to an error*  

How can the issue be reproduced?
This happens when ever I do these following steps, Atmosphere/Contents/Any game title Id. I have no knowledge on how to slove this issue this only happens specifically when the mods are placed in a title id folder.

**Comment by Masamune3210** [comment]
No Template, No help. Go back and fill it out please.
