### ISSUE TITLE
Error Code: 2162-0002 (0x4a2) Program: O100000000001000 Firmware: 18.0.0 

### ISSUE THREAD

**Issue by luna2709** [Atmosphere-NX/Atmosphere#2337]
## Bug Report

I don't understand a lot about the nintendo switch hacked but this channel was the closest that got to my problem, I have a problem while I try to enter the hacked system of NS (Atmosphere - CNX PACK - emunand/sysnand incognito on), that it gives me the error screen said in the title. However when I try to enter the original system it goes normal, I heard that I need to delete an folder/archive of the sd card to solve this issue, but I don't know how to access the inner storage through the nyx hekate menu.

### What's the issue you encountered?

First I tried to update the hacked system through CNX UPDATER, I updated the atmosphere first then the cnx, because previously I was only able to enter the hacked system, the original used to crash and I wanted to solve this. After I updated the hacked system, I was able to launch the original system, but I wanted to play MK8D online, and the game said that for using online features I needed to update the (original) system, then I got to the original nintendo Settings, and updated the system through there, now I can't open the hacked system.

### How can the issue be reproduced?

N/A

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

IM SORRY BUT I DON'T KNOW HOW TO DO THIS. I LEFT A PIC OF THE ERROR SCREEN ATTACHED TO THIS ISSUE.

### System Firmware Version

18.0.0

### Environment?

- Hekate
- Unofficial build: v6.1.1.
- Homebrew software installed: [ CNX UPDATER - HEKATE ]
- SysNAND

### Additional context?

Before I tried to update the hacked system, I did installed themes to my menu, lock screen and all apps layout.
![20240602_213257](https://github.com/Atmosphere-NX/Atmosphere/assets/101946084/691e25e7-309e-4fb2-9007-22c8c3f76617)

**Comment by Aura67** [comment]
you probably have a custom theme active delete:O100000000001000 from your sd card it is not an atmosphere error. And you should not block nintendo with incognito set the value 1 back to 0. with the deleted: :O100000000001000 and then try to boot again.

**Comment by luna2709** [comment]
> you probably have a custom theme active delete:O100000000001000 from your sd card it is not an atmosphere error. And you should not block nintendo with incognito set the value 1 back to 0. with the deleted: :O100000000001000 and then try to boot again. What you can also do is simply a clean install of Atmospehre, simply download it from the source here and put it on the SD card and simply boot again, then the system should start again.

How do I access the sd card? I plug it into my pc and it doesn't show the Switch folder.

**Comment by Aura67** [comment]
your error is not in your Switch folder either, it is under Atmospehre :--> contents and from there you simply delete: O100000000001000. you can also access your SD card with Hekate by mounting it with Hekate. but the issues tracker is not really intended for help, but for bugs. And your problem is not a bug. Otherwise just delete the CFW from the SD card again and format it properly in fat32 and reload Atmospehre and Hekate and then try to boot, but first make sure your Nintendo folder is safe.
