### ISSUE TITLE
switch oled mariko not loading game cartridge need fixing

### ISSUE THREAD

**Issue by BladeTechBlade** [Atmosphere-NX/Atmosphere#2338]
I have got a modchip switch oled but one of my switch games does not load with hats pack need to check other packs to see if it is not a problem.

Iam on the latest switch 18.0.1 and the latest hekate build.
A software for the switch should be made to identify if the problem is the game or the switch itself.

**Comment by borntohonk** [comment]
> I have got a modchip switch oled but one of my switch games does not load with hats pack need to check other packs to see if it is not a problem.
> 
> Iam on the latest switch 18.0.1 and the latest hekate build. A software for the switch should be made to identify if the problem is the game or the switch itself.

HATS is a piracy package, piracy is not supported.

**Comment by borntohonk** [comment]
> It has got my game to work thanks from the people that made the cfw and I do not like anyone saying anything bad that helps people out.

The "people who made the cfw" are the contributors of this repository that you've submitted an issue to.

H.A.T.S. is an acronym for Hekate, Atmosphere, Tinfoil and Signature patches.

HATS is not a cfw, it's a piracy package, which is not supported. This github iissue does not belong here.

**Comment by BladeTechBlade** [comment]
> > It has got my game to work thanks from the people that made the cfw and I do not like anyone saying anything bad that helps people out.
> 
> The "people who made the cfw" are the contributors of this repository that you've submitted an issue to.
> 
> H.A.T.S. is an acronym for Hekate, Atmosphere, Tinfoil and Signature patches.
> 
> HATS is not a cfw, it's a piracy package, which is not supported. This github issue does not belong here.

OK thanks
