### ISSUE TITLE
Mod do not launch when enabled 

### ISSUE THREAD

**Issue by Mrgamer2240** [Atmosphere-NX/Atmosphere#2339]
What's the issue you encountered?
After placing the mods into Atmosphere/Contents/01008DB008C2C000/RomFS Etc, the mods don't launch at all I'm not sure if my file structure is incorrect 

System Firmware Version

Atmosphere version 1.7.0

**Comment by Mrgamer2240** [comment]
My file structure is Atmosphere/Contents/01008DB008C2C000/RomFS. There are folders in RomFS do I separate the mods from said folder or keep them in?

**Comment by SciresM** [comment]
The issue tracker is for bugs. Seek support on discord.
