### ISSUE TITLE
Corrupted apps

### ISSUE THREAD

**Issue by CorruptHomie** [Atmosphere-NX/Atmosphere#2344]
### What's the issue you encountered?
 When I updated to 1.7.1, all nsp's were completely corrupted.

### How can the issue be reproduced?

1. Update Atmosphere
2. Update Switch
3. Update Hekate
4. Launch AMS
5. Attempt to launch any app

### Crash Report

N/A

### System Firmware Version

18.1.0</br>

### Environment?

Official Hekate Build 6.2.0 on SysNAND

### Additional context?

N/A

**Comment by SciresM** [comment]
piracy is not supported
