### ISSUE TITLE
Built in 8gb ram mode

### ISSUE THREAD

**Issue by caden3ds** [Atmosphere-NX/Atmosphere#2346]
#### Overview:
A toggle for enabling a 8gb ram mode so you don't have to compile Atmosphere yourself

#### Smaller Details: 
I'm referring to the MemoryMode and MemorySize properties seen in this video https://www.youtube.com/watch?v=J4oXmQGZgzU at 22:52.

#### Nature of Request:  
Addition
### What component do you feel this would best fit within?
Not sure
- [Fusée](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Atmosphère's custom bootloader.</br>
- [Exosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Fully-featured custom secure monitor.</br>
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>
- [**Thermosphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Atmosphère's emuNAND implementation.</br>
- [**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?
Convenience and not having to rebuild atmosphere every time there is a new update

**Comment by gh0sti** [comment]
This feature request is for specific hardware mod. There is probably very few users who can mod their device to add more ram.

**Comment by SciresM** [comment]
I think I would prefer that people just compile with the relevant changes...this shouldn't be a big deal to the kind of people willing to manually install bigger RAM, and it would be confusing/problematic for normal users to change.
