### ISSUE TITLE
Corrupted data after updating to ams 1.7.1 and cfw 18.1.0

### ISSUE THREAD

**Issue by lionhartono** [Atmosphere-NX/Atmosphere#2348]
Please help I just update my switch cfw to AMS 1.7.1 and CFW 18.1.0 and suddenly I have a lot of games that corrupted.
I tried to uninstall and clean the leftover files from dbi installer and tried to install the game again but still won't work. When I installed the game it's saying corrupted. I've tried to reset my switch and install the atmosphere again format my sd card and still happened what should I do?

**Comment by lionhartono** [comment]
It looked like it didn't delete all the files on my switch so how do I fully reset my switch?

**Comment by borntohonk** [comment]
> I tried to uninstall and clean the leftover files from dbi installer and tried to install the game again but still won't work. When I installed the game it's saying corrupted. I've tried to reset my switch and install the atmosphere again format my sd card and still happened what should I do?

This usually is a symptom of piracy... which in your case mentioning "dbi installer" makes it a certainty.

No support for piracy.

**Comment by m4rtini2** [comment]
Use hekate to boot athmosphere, then reinstall your game.

**Comment by borntohonk** [comment]
> Use hekate to boot athmosphere, then reinstall your game.

Don't attempt to provide support to piracy issues.

**Comment by Tigo1233** [comment]
> Please help I just update my switch cfw to AMS 1.7.1 and CFW 18.1.0 and suddenly I have a lot of games that corrupted. I tried to uninstall and clean the leftover files from dbi installer and tried to install the game again but still won't work. When I installed the game it's saying corrupted. I've tried to reset my switch and install the atmosphere again format my sd card and still happened what should I do?

Have you found a way to fix it?

**Comment by lionhartono** [comment]
> > Please help I just update my switch cfw to AMS 1.7.1 and CFW 18.1.0 and suddenly I have a lot of games that corrupted. I tried to uninstall and clean the leftover files from dbi installer and tried to install the game again but still won't work. When I installed the game it's saying corrupted. I've tried to reset my switch and install the atmosphere again format my sd card and still happened what should I do?
> 
> Have you found a way to fix it?

Yes I did! using syspatch
https://gbatemp.net/download/sys-patch-1-5-2-binary-fw-18-1-0-atmosphere-1-7-1.38686/

**Comment by SoraJrUpdate** [comment]
I have my grandmother's switch I did for her. After reading through stuff I found through google. Her switch is on FW 17.0.0. I downgrade AM from 1.10.2 to 1.6.2, ran the "searching for corrupted data" process, and the game loads just fine after that.
