### ISSUE TITLE
Error  0xC287D802 (2002-1004)

### ISSUE THREAD

**Issue by DOU456** [Atmosphere-NX/Atmosphere#2349]
### What's the issue you encountered?

[ I installed mods to my smash with archopolis, one day a notification appeared before starting the game that I could update to a newer version of archopolis, it was updated and the game closed, when I tried to open it again the message "it has closed" appeared program due to an error" , the error is (2002-1004)  ]</br>

### How can the issue be reproduced?

[ install, smash bros, mods and outdated archopolis, archopolis will ask you to update and you accept, for me it did not happen well and it does not want to start the game]</br>

### Crash Report

[01719114079_01006a800016e000.log](https://github.com/user-attachments/files/15942530/01719114079_01006a800016e000.log)

### System Firmware Version
18.0.1
### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:Hekate
- Official release or unofficial build: 6.2.0
- Do you have additional kips or sysmodules you're loading: None, all is atmosphere
- Homebrew software installed: ARCropolis for Smash Mods 
  
- Homebrew software installed: [ Archopolis, i installed mods]

### Additional context?

- Additional info about your environment: I installed mods to my smash with archopolis, one day a notification appeared before starting the game that I could update to a newer version of archopolis, it was updated and the game closed, when I tried to open it again the message "it has closed" appeared program due to an error" It should be noted that I already tried to delete the mods folder, the contents folder, the titles, I deleted it, I formatted the SD, the error still appears even when the folder is deleted
I also mention that, I just checked that it works with a Smash cartridge, but the version that I am trying to download (tinfoil and internet pages) does not work
I've been trying to remove the error for more than 4 months and I can't find it.

**Comment by masagrator** [comment]
Piracy is not supported.
