### ISSUE TITLE
About the impact of USB3.0 on the dock mode Bluetooth controller

### ISSUE THREAD

**Issue by NHAO39** [Atmosphere-NX/Atmosphere#2350]
Sorry for not editing according to the template.I want to ask if turning on USB 3.0 will affect the dock mode. I found that turning it off can enhance the Bluetooth signal. I want to use USB 3.0, but it affects my signal. Is there a way to solve it? This may be a very simple question. I am sorry for this, but I still want to know.

**Comment by masagrator** [comment]
Enabling USB 3.0 causes creating interference on 2.4 GHz bandwidth which is used by Bluetooth and Wi-Fi. This is a hardware issue with every unit and it's not possible to fix with software other way than just not enabling it.
