### ISSUE TITLE
Panic occurred while running Atmosphere after updated to atmosphere-1.7.1-master-39c201e37+hbl-2.4.4+hbmenu-3.6.0 then updated firmware from 17.0.1 to 18.0.1 then updates emuMMC via https://nh-server.github.io/switch-guide/extras/updating/ guide

### ISSUE THREAD

**Issue by jimmiejoe** [Atmosphere-NX/Atmosphere#2351]
## Bug Report

</br>
</br>

</br>
</br>
</br>
</br>
</br>

### What's the issue you encountered?

</br>
</br>
/br>
Followed the guide "https://nh-server.github.io/switch-guide/extras/updating/" to update prior to updating the Switch firmware. Updated to atmosphere-1.7.1-master-39c201e37+hbl-2.4.4+hbmenu-3.6.0
Update Hekate
Then updated Switch firmware from 17.0.1 to 18.0.1
Then updated emuMMC via TegraExplorer.bin firmware backup and DayBreak.
Upon restart got an error, restarted again and got a panic error.

Rebuild the emuMMC by following the "https://nh-server.github.io/switch-guide/user_guide"as though starting CFW from scratch.
wrote the new emuMMC partition over the existing emuMMC partition, but this time the switch was on 18.0.1, instead of 17.0.1.
Launched Atmosphere and again got panic error:
Tried to launch Atmospere from both Hekate (Atmosphere FSSO emuMMC) and from fusee.bin payload

Panic occurred while running Atmosphere

Title ID: 010000000000BD00
Error:     std: :abort  (0xFFE)
Report saved to atmosphere/fatal_error/report_0a1bc77a.bin

### How can the issue be reproduced?
Simply launching Atmosphere creates the fatal error.
</br>
/br>

### Crash Report

</br>
</br>
</br>

### System Firmware Version

18.0.1</br>
</br>
</br>
</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate and fusee
- Official release or unofficial build: official release
  - 1.7.1
  -  
     - 
     - 
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: 
- EmuMMC or SysNAND:
  - 
Partition emuMMC
### Additional context?

- Additional info about your environment:
-

**Comment by jimmiejoe** [comment]
[report_0a1bc77a.zip](https://github.com/user-attachments/files/15964849/report_0a1bc77a.zip)

**Comment by borntohonk** [comment]
> [report_0a1bc77a.zip](https://github.com/user-attachments/files/15964849/report_0a1bc77a.zip)

delete folder 010000000000BD00 in atmosphere/contents/ or update mission-control ( https://github.com/ndeadly/MissionControl/releases )

**Comment by jimmiejoe** [comment]
Updating Mission Control did not fix the issue, get the same error. I saw that in the previous Panic error.

**Comment by borntohonk** [comment]
> Updating Mission Control did not fix the issue, get the same error. I saw that in the previous Panic error.

010000000000BD00 is missioncontrol related and is not an official titleid belonging to any atmosphere components nor nintendo, it is entirely related to the custom homebrew missioncontrol.
Delete the folder or update it properly. You claim to have updated it, and it doesn't work for you, which leaves you with the option of deleting it.

**Comment by SciresM** [comment]
The issue reported is an abort in Mission Control; update it. This isn't an atmosphere issue.

**Comment by jimmiejoe** [comment]
I do not know what Mission Control is and obviously do not use it.
I have deleted the folder and that appears to have corrected the issue.

not sure why the conflict only surfaced after I updated the emcMMC to 18.0.1.

**Comment by masagrator** [comment]
It doesn't change the fact that you had MissionControl. You should get more aware of what you have installed on sdcard if you didn't know you had it.
