### ISSUE TITLE
Switch lite blue led joycon home button always on

### ISSUE THREAD

**Issue by MrPopsdu46** [Atmosphere-NX/Atmosphere#2358]
### What's the issue you encountered?

The lite console crashed during the night and since the blue LED on the joycon is on I can never stop it.
No, the installation is very fresh, I hadn't put much on it since it was late, I was going to continue today.

Error  0100000000001000

I don't use a theme, everything was just installed a few hours before

### Crash Report

https://gist.github.com/MrPopsdu46/905fc8155aaeafd30c71a5f3f46b01e7
https://gist.github.com/MrPopsdu46/b02ccfc4264677e319d04490c48984f6

### System Firmware Version

18.1.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: 
By the versions present on Github for Atmosphere and hekate.
- Official release or unofficial build: Officiel 
- Do you have additional kips or sysmodules you're loading:
I don't think so because the installation is very fresh I didn't do much before installation.
- Homebrew software installed: [ Idem ]
- EmuMMC or SysNAND: EmuMMC partition

**Comment by SciresM** [comment]
this isn't an atmosphere issue, this is a user config issue. Delete the atmosphere dir and replace it with clean release zip.
