### ISSUE TITLE
Fatal error 0100000000000005 (std:abort() called (0xffe) on startup

### ISSUE THREAD

**Issue by afij** [Atmosphere-NX/Atmosphere#2360]
### What's the issue you encountered?

During Atmosphere startup, the following fatal error occurs:

Program ID: 0100000000000005
Error Desc: std::abort() called (0xffe)

Atmosphere was functional without any changes but received this error after being on the Switch dock for a month.

### How can the issue be reproduced?

Launch Atmosphere via Hekate or fusee.bin directly

### Crash Report

Fatal Error bin file: https://gist.github.com/afij/5c2961c7097b533906bd046e20edaaa6

### System Firmware Version

14.1.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate v6.2.1 & latest fusee
- Official release or unofficial build: 
  - Official release version 1.7.1
- Do you have additional kips or sysmodules you're loading: N/A
- Homebrew software installed: N/A
- EmuMMC or SysNAND:
  - EmuMMC Partition based (Fat32 format)

### Additional context?

Updated Atmosphere, Fusee, and Hekate after receiving the error for the first time. As noted, the Switch was functional but left unattended on the dock for a while. Drained battery completely and recharged and still receive the same error. SD card appears functional when plugged into the PC.

Atmosphere folder deleted and re-added but issue still occurs. 

If the Switch's base firmware (14.1.1) needs to be updated, I can give it a try. Sysnand works correctly.

**Comment by SciresM** [comment]
`fs::ResultInvalidFatFormatBisSystem()`

Your emummc is corrupt. Re-clone fresh from sysmmc.
