### ISSUE TITLE
0100000000000005

### ISSUE THREAD

**Issue by 5936956** [Atmosphere-NX/Atmosphere#2365]
18.1.0
![Uploading 722E97C5-F2DC-4710-9DC2-71FF0183F30C.j
![89D8FA06-3982-4257-A078-B9E5F0252ED4](https://github.com/user-attachments/assets/281cca15-4ca8-4b07-974d-3bd8e81a3cee)
peg…]()

**Comment by masagrator** [comment]
Use issue template.
