### ISSUE TITLE
Right Joy Con Lagging then disconnecting

### ISSUE THREAD

**Issue by Choccy-vr** [Atmosphere-NX/Atmosphere#2369]
### What's the issue you encountered?

While playing any game I found it to be most prominent in Mario kart it lags and then disconnects 

### How can the issue be reproduced?

Play any game wait a few minutes and the controller will lag and then disconnect

### Crash Report

N/A

### System Firmware Version

18.1.0|AMS 1.7.1|E

### sysmodules
Have none currently but at one time I had installed sys-clk

### Environment?

- What bootloader (fusèe, hekate, etc) latest version of hekate 
- Official release or unofficial build: 
official release 

- EmuMMC or SysNAND:
  EmuMMC partition based

**Comment by masagrator** [comment]
Why did you delete point about used sysmodules? It's very important.

**Comment by Choccy-vr** [comment]
> Why did you delete point about used sysmodules? It's very important.

I did not know I needed it. At one point I had sys-clk but I deleted it.

**Comment by sthetix** [comment]
did it happen when docked? if docked then try to disable the usb3 function inside the atmosphere config

**Comment by Choccy-vr** [comment]
Seems to be fixed on 1.8.0
