### ISSUE TITLE
Atmosphere crash on 1.0.0, needs some help guys. 

### ISSUE THREAD

**Issue by Hayato213** [Atmosphere-NX/Atmosphere#237]
![img_20181022_150837](https://user-images.githubusercontent.com/37278480/47313477-09139f80-d60d-11e8-957b-5d52086565c4.jpg)

**Comment by Hayato213** [comment]
https://noirscape.github.io/SwitchGuide/sdcard.html

I was following this, crash report wasn't generated. It crash after atmosphere load and go into the home menu. Does it has to do with 1.0.0?

![1](https://user-images.githubusercontent.com/37278480/47314371-71638080-d60f-11e8-8730-81cacd419b0b.PNG)

**Comment by SciresM** [comment]
It looks like you're using sys-ftpd.kip. If you remove that from the kips folder, does the crash still occur?

**Comment by Hayato213** [comment]
Okay, it stop crashing, thanks SciresM, you helped me again. Last time was on ProjectPokemon Cyber Gadget Save Editor, been years.

**Comment by SciresM** [comment]
:) -- sounds like this isn't an atmosphere problem.

**Comment by noirscape** [comment]
FWIW, fixed this in my guide too.

Didn't know sys-ftpd was broken on 1.0.0.
