### ISSUE TITLE
Atmosphere Continuously Crashing

### ISSUE THREAD

**Issue by rayyana2** [Atmosphere-NX/Atmosphere#2373]
### What's the issue you encountered?

After working completely normally for months, atmosphere has started crashing extremely quickly upon loading the emummc. There are a variety of error codes that are given, but a common one is 524850534f53454d, kernel panic. Another (maybe more common) one is 01000000000001A. I tried entering the sysmmc and it appears to function as normal, but the emummc has started crashing either instantly or soon after booting. There were a few recent changes that I made to my switch. First, I updated the Ultrahand overlay, which I was using to help overclock and undervolt but hadn't updated in a few weeks. Second, I installed new themes, but I determined these were unlikely to be the culprit as the issue persisted after removing the theme folder. Also, I recently installed way too many smash mods like a couple months ago, but my switch wasn't crashing until now.

Sometimes the screen gets corrupted first and then it crashes.

### How can the issue be reproduced?

Simply booting into the emunand will either immediately cause a crash (right after seeing the lock screen), or result upon a crash shortly after launching a game (or sometimes even doing nothing).

### Crash Report

[01726533390_010000000000000a.log](https://github.com/user-attachments/files/17021376/01726533390_010000000000000a.log)
[01726533329_010000000000001a.log](https://github.com/user-attachments/files/17021377/01726533329_010000000000001a.log)

### System Firmware Version

18.1.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: 
Hekate (fss0) as well as fusee.bin
- Official release or unofficial build: 
Official  - 1.7.1
- Do you have additional kips or sysmodules you're loading:
several, like sys-clk OC, salty-NX
- Homebrew software installed: [ * ]
Ultrahand overlay, smash mods, retroarch
- EmuMMC or SysNAND:
  - emuMMC partition based

### Additional context?
Let me know if you need more info.

**Comment by SciresM** [comment]
Yeah, it sounds like you've got bad custom sysmodules. I don't think the atmosphere issue tracker is the right place for that -- you can always ask further on discord, but I try to keep this for actual bugs in atmosphere.
