### ISSUE TITLE
HBMenu applet mode softlocking Switch when playing Luigi's Mansion 3

### ISSUE THREAD

**Issue by Arales03482** [Atmosphere-NX/Atmosphere#2378]
### What's the issue you encountered?

Console was getting softlocked every time (this issue did not happen on 13.x.x version where i downloaded the game through eshop with a older atmosphere ver)
All i had in atmosphere was tickets so i could launch games (yes i did buy them)

### How can the issue be reproduced?

1. Launch Luigi's Mansion 3 (1.4.0 preferably)
2. Open the hbmenu through applet mode
Now you have a softlocked console

### Crash Report

N/A

### System Firmware Version

16.0.2</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate v6.2.1
- Official release or unofficial build: 
  - v1.7.1 of Official Atmosphere
  - From Atmosphere-NX/Atmosphere and from the releases tab
- Do you have additional kips or sysmodules you're loading: not sure about kips and Noexes, sys-ftpd-10k, sys-clk, ldn_mitm (enabled), Tesla, emuiibo, MissionControl (i forgot what this does)
- Homebrew software installed: N/A
- EmuMMC or SysNAND:
  - EmuMMC file based

### Additional context?

- Additional info about your environment:
- Hosts file for emummc (its a 90dns hosts file)
- I have serial number blanking on emummc enabled

**Comment by masagrator** [comment]
You have too much custom sysmodules. And that's probably why you have this issue.

**Comment by Arales03482** [comment]
It works now
I think it was the MissionControl from the uLaunch pack?

**Comment by masagrator** [comment]
It doesn't matter. Issue was you had too much sysmodules. Deleting one was enough to free enough space for hbmenu to load.
