### ISSUE TITLE
[request] Explicitly say if fusee-primary has been updated

### ISSUE THREAD

**Issue by lunks** [Atmosphere-NX/Atmosphere#238]
Could we state in the release if fusee-primary has changed or not? It's good to know whether it's the case to use the new one or if the old one is just fine. If the old one is _never_ just fine, this information should be listed in the release to avoid people not updating it.

**Comment by SciresM** [comment]
Done.

There's now a `fusee-primary was last updated in: <>` line in 0.7.1 and 0.7.2, and I will maintain this going forwards.
