### ISSUE TITLE
Native support for Mod Switcher/Multimods selector

### ISSUE THREAD

**Issue by LiderKonmils** [Atmosphere-NX/Atmosphere#2381]
#### Overview:
-Native support for Mod Switcher/Multimods selector </br>

#### Smaller Details: 
- Why not use SimpleModManager:
    SimpleModManager have to copy all the files to the atmosphere mods folder to work. Just to install CTGP-DX for MK8DX through this homebrew, it takes me half an hour... to copy files... A native function giving a Switcher/Selector would reduce this need for copy.</br>

#### Nature of Request:  
- Addition
  - Having an option to add to a file in the sd card or in an app in the gallery to enable/disable the mods switcher, </br>
  - When enabled, while lunching the game, if mods are added to atmosphere mods folder, a selector appear and let the user choose mods in the list to load, also letting the user to save the modpack created for easier loading for futur game start.</br>

### What component do you feel this would best fit within?
- I have no idea on wich level Atmosphere load the mods.</br>

### Why would this feature be useful?
It will heavily reduce the copy time that cannot bypass homebrews like SimpleModsManager</br>

**Comment by SciresM** [comment]
Yeah, sorry, showing menus on game launch is not actually a thing that's viable for atmosphere to do. I think this is just one of those things that has to be a homebrew add-on. I wouldn't in principle object to someone writing a mod manager homebrew for atmosphere and integrating it to the distribution package, but that's not what you're asking ^^
