### ISSUE TITLE
Atmosphere get error after smash update ( 13.0.3 )

### ISSUE THREAD

**Issue by levyathandragon** [Atmosphere-NX/Atmosphere#2389]
Hi 
after smash bros ultimate has been updated to the version 13.0.3 ( also switch update ). When I inject the payload ( fusee bin ) I get an error says “ Fatal error occurred when running fusee. Unable to identify package1! “

I have the latest version of atmosphere,fuse and achropolis as well, some one have the same issue after the update of those ? 

What I need to do ? 

Thank you 
![IMG_5871](https://github.com/user-attachments/assets/5e5f719d-bc57-4c85-84d0-47fdbdc12e6a)
![IMG_5871](https://github.com/user-attachments/assets/5fd73e92-7e79-47df-8711-e7b3c016d604)

**Comment by SciresM** [comment]
You have to wait for 19.0.0 to be supported. See #2386.
