### ISSUE TITLE
System Crashes/screen goes black while playing BoTW

### ISSUE THREAD

**Issue by Hauteknits** [Atmosphere-NX/Atmosphere#239]
After updating to Atmosphere 7.2, now playing BoTW triggers a crash during certain events, logged so far: *Leaving a shrine *Headshot on Black Moblin. Im not sure if its a crash because they'res no report and the system seems to still be on, but the backlight is off, the screen is black and wont turn back on until the power is held for 10-12 seconds. BoTW was installed via .NSP and the events listed didnt trigger crashes before the update. (Note: SDFiles updater may be to blame, havent tested.) After the first, I got the error "Stage2 is outside of the range of Stage2!" or something along the lines, but every crash after that, the atmosphere launches normally via TegraRCMSmash.exe

**Comment by SciresM** [comment]
This indicates that Exosphere panicked in some way. Is the crash reproducible? If so and if you can come on ReSwitched's discord I can give you debug builds of Atmosphere that will allow me to identify where the exosphere panic is occurring.

**Comment by Hauteknits** [comment]
@SciresM the crash is reproducable, what is the link for the discord

**Comment by Hauteknits** [comment]
Also, selecting singleplayer on Mario Kart 8 has triggered a "crash." The system will also not power cycle until it is plugged into a power source. It doesn't seem to matter whether it the included adapter or USB power via my tower.

**Comment by fennectech** [comment]
See if holding power button for 15 seconds makes it reboot

**Comment by SciresM** [comment]
Talked to @Hauteknits on discord -- it seems like this is a bona fide hardware problem, as his switch crashes whether or not Atmosphere is being used. If it seems like this actually is an ams problem after all, issue will be reopened.
