### ISSUE TITLE
Atmosphere album dont wanna load

### ISSUE THREAD

**Issue by Armandowrld** [Atmosphere-NX/Atmosphere#2392]
I updated fuse bin and even deleted atmosphere and extracted the new file but atmosphere keep saying this (image) WHAT DO I DO MAN my switch is banned so without atmosphere I'm doomed 
![RDT_20241012_1220382694935393161946933](https://github.com/user-attachments/assets/067de095-0c7c-48b8-a772-022e9e0bb7e0)

**Comment by SciresM** [comment]
Delete your custom theme. But this is for bugs, not support. Get support on discord.

**Comment by Armandowrld** [comment]
I have no themes installed

**Comment by Armandowrld** [comment]
I have no themes and on discord I can't get past newcomers

**Comment by SciresM** [comment]
Delete anything inside /atmosphere/contents
