### ISSUE TITLE
sleep mode error

### ISSUE THREAD

**Issue by Valou5231** [Atmosphere-NX/Atmosphere#2394]
### What's the issue you encountered?

after  i have update Atmosphere the bug has spawn

### How can the issue be reproduced?

when i turn my switch into sleep mode and  i want to turn on it , the switch reboot on hekate.

### System Firmware Version

19.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:

Atmosphere was lauched by hekate on the v6.2.2

**Comment by ELY3M** [comment]
Do you have sys-clk or any sys-modules?       make sure you update all of your sys-modules.

**Comment by Valou5231** [comment]
yes i have a sys-modules and all is update

**Comment by redilsnn** [comment]
Having this same problem after updating, but for me it totally blacks out when trying to wake up, and the only option Is holding the power button down for several seconds to shut down the consoles completetely, which Is annoying because i have to re-do the joycon jig and send payload with tegra everytime to boot into hekate 

Will the "Turning on AutoRCM" option serve as a workaround in the meantime? (For me to not do the jig thing everytime this happens?)

**Comment by Valou5231** [comment]
me too the switch is totally off once in two

**Comment by Yellowpandasomething** [comment]
I am also having the same issue as redilsnn where once I put it to sleep the system becomes completely unresponsive and I'm forced to force shut it down and rejig it. I'm on atmosphere 1.8.0, switch os 19.0.0, and hekate 6.2.2.

**Comment by Fa1lnaught** [comment]
Same here and when I try to boot into OFW I get warning saying "unknown pkg1 version hos version not supported"

**Comment by whossein** [comment]
I also have a problem on my device, OLED

**Comment by masagrator** [comment]
sys-clk is not the only tool that you must update after updating to atmosphere 1.8.0 to not have sleep issues.

List of tools that can cause this issue:
- sys-clk (fixed the issue in newest release)
- Status Monitor Overlay (fixed the issue in newest release)
- Edizon Overlay (not fixed, don't go to Stats menu if you don't want this to happen)
- nx-fancontrol (was not fixed yet)
And any other tool that reads temperatures for whatever reason.

**Comment by masagrator** [comment]
> when I try to boot into OFW I get warning saying "unknown pkg1 version hos version not supported"

You didn't update Hekate.

Update everything folks, this is the best advice whenever new firmware is released.

**Comment by Fa1lnaught** [comment]
Yeah this is the first time I've gotten CFW on something so I don't know much

**Comment by Valou5231** [comment]
ok i wil try this

**Comment by ToxiClay** [comment]
Cheers to @masagrator for saving my dumb ass from opening a useless, redundant issue. Updating sys-clk fixed it.

**Comment by javoerro** [comment]
im having the same issue on 19.0.1. OFW works fine, the problem is in CFW and EMU.

**Comment by ToxiClay** [comment]
> im having the same issue on 19.0.1. OFW works fine, the problem is in CFW and EMU.

Update your shit.

**Comment by javoerro** [comment]
ISSUE UPDATE: updating sys-clk homebrew solved my problem!
