### ISSUE TITLE
Atmosphere crashes 1.8.0 crashes when connecting to wi fi

### ISSUE THREAD

**Issue by LeilaFlowers** [Atmosphere-NX/Atmosphere#2398]
## Bug Report

Atmosphere crashes when Connecting to internet

### What's the issue you encountered?

When i entered atmosphere in a new made emummc it crashed when Connecting to Internet, i know its because of the Internet because it happend in sys cfw too, and when i put it in airplane mode it dosent crash.

### How can the issue be reproduced?

Connect to wi fi in atmosphere 1.8.0, emummc ver 19.0.0

### Crash Report

https://github.com/user-attachments/assets/ae535f48-c514-43c7-bff8-2fa265eec94b

### System Firmware Version

Emummc 19.0.0

### Environment?

Hekate lastest

**Comment by 228hal** [comment]
Try disabling blanked product ID in exosphere if you have it enabled

**Comment by Ogurez123** [comment]
This is most likely due to the fact that your nintendo switch is trying to connect to the nintendo servers. Follow these instructions https://switch.hacks.guide/extras/blocking_nintendo /
it helped me.

**Comment by wakoyname** [comment]
if both are already at 0 in exosphere.ini:

try to check if theres another exosphere.ini in root folder and delete it
go to atmosphere > config > system_settings
find: enable_dns_mitm = u8!0x1
and change it to: ; enable_dns_mitm = u8!0x1
find: add_defaults_to_dns_hosts = u8!0x1
and change it to: ; add_defaults_to_dns_hosts = u8!0x1

go to atmosphere > config_templates > system_settings
find: enable_dns_mitm = u8!0x1
and change it to: ; enable_dns_mitm = u8!0x1
find: add_defaults_to_dns_hosts = u8!0x1
and change it to: ; add_defaults_to_dns_hosts = u8!0x1

also delete atmosphere > hosts > default.txt

**Comment by LeilaFlowers** [comment]
Is incógnito mode not working then?

**Comment by Masamune3210** [comment]
it hasnt for at least two updates. It's not that it doesn't work, its that the Big N started specifically checking for issues with getting the information and the system panics if the information is missing or modified

**Comment by wakoyname** [comment]
then downgrade is your only option. you can still play games on fw version 18.1.0 using atmos 1.7.1, why update?

**Comment by Masamune3210** [comment]
risky as in you might have to start fresh and wipe all your saves and profiles, not risky as in brick

**Comment by C1p86** [comment]
hello! I have the same problem, a switch that was updated to 19.0.1 and now downgraded to 18.0.1.
It crashes as it connect to wifi, but mitm is working (in the log I see redirects enabled). Any clues?

**Comment by ZeroSynn-zip** [comment]
Do i disable blank product id of sysmmc or emummc
