### ISSUE TITLE
All installed games give 'Unable to start software' 

### ISSUE THREAD

**Issue by TroubledGamer** [Atmosphere-NX/Atmosphere#2399]
I am on FW 19.0.0 and atmosphere 1.8.0
Everything was working fine until the update.. Not sure what to do.

**Comment by masagrator** [comment]
1. You didn't use issue template.
2. Reinstall games from eshop.

**Comment by TroubledGamer** [comment]
> 1. You didn't use issue template.
> 
>     2. Reinstall games from eshop.

I am afraid this does nothing.. Every single game I've tried is unable to open.

**Comment by Ogurez123** [comment]
If your games are pirated, then most likely there is a problem with sigpatches.
Try using this archive with gbatemp 
https://gbatemp.net/threads/sigpatches-for-atmosphere-hekate-fss0-fusee-package3.571543/post-10517797

**Comment by HunterMario** [comment]
Piracy is not supported.

**Comment by borntohonk** [comment]
> > 1. You didn't use issue template.
> >    
> >    2. Reinstall games from eshop.
> 
> I am afraid this does nothing.. Every single game I've tried is unable to open.

He told you to go to eshop and pay for the games, the ones not opening are games you didn't pay for.

Piracy is not supported.
