### ISSUE TITLE
Error 2162-0002 on pre-release 18.0.1, crashes on launch

### ISSUE THREAD

**Issue by mason321** [Atmosphere-NX/Atmosphere#2404]
> ## Bug Report
I tried out the Atmosphere via, fusse, normal methods, newer hekate, and what not, but no such luck.

**Comment by Masamune3210** [comment]
Go back and fill out the template. Until you do, nobody is going to help you. It's there for a reason.

**Comment by mason321** [comment]
where is the template?

**Comment by borntohonk** [comment]
> where is the template?

the one you removed in its entirety to create this github issue, instead of filling it out.
