### ISSUE TITLE
Homebrew unable to start

### ISSUE THREAD

**Issue by sand-undertale** [Atmosphere-NX/Atmosphere#2406]
### What's the issue you encountered?
When attempting to use any homebrew app it says "Unable to start software.", then says it's corrupted.

### How can the issue be reproduced?
Run homebrew through Title Takeover or Applet.

### Crash Report

N/A

### System Firmware Version

19.0.0

### Environment?

-Hekate with Atmosphere Pre-Release 18.0.0
-Attempted, failed.
-SysNAND

**Comment by borntohonk** [comment]
> When attempting to use any homebrew app it says "Unable to start software.", then says it's corrupted.
Piracy is not supported.

**Comment by sand-undertale** [comment]
as stated in the issue, it's homebrew, not piracy.

**Comment by SciresM** [comment]
Piracy is not supported. This includes homebrew installed to the home menu using piracy patches.
