### ISSUE TITLE
Tinfoil and Games don´t work anymore after Athmosphère update

### ISSUE THREAD

**Issue by vDotMoe** [Atmosphere-NX/Atmosphere#2409]
I need help...

**Comment by masagrator** [comment]
Piracy is not supported.

**Comment by jacobg32** [comment]
thats what they all say 😭😭😭😭😭

**Comment by impeeza** [comment]
> I need help...

This is not a support site, and piracy is not supported, please go to GBATemp or Discord.  and close this issue.
