### ISSUE TITLE
Homebrew for Editing Atmosphere Settings via GUI on Switch

### ISSUE THREAD

**Issue by PoloNX** [Atmosphere-NX/Atmosphere#2410]
#### Overview:
- A homebrew that will allow users to modify the Atmosphere settings through a graphical interface. This homebrew enables modification of the Exosphere, Stratosphere, and all configurable .ini files.</br>

#### Smaller Details: 
- A library like [borealis ](https://github.com/xfangfang/borealis)can be used to create a good interface</br>

### What component do you feel this would best fit within?
- [**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?
The user will be able to modify certain Atmosphere settings directly from their Switch.</br>

### Additionnal note
I can develop this homebrew and open a pull request. But if your against I don't want to create this tool for nothing so I prefer ask before starting the dev

**Comment by wakoyname** [comment]
we would love to test it. start with the version 18.1.0 support atmos 1.7.1 for less bug

**Comment by masagrator** [comment]
I was thinking about it few days ago, and I won't care if it's needed or not, I would use it almost every day. 
Remember that there are more settings than are included with template system_settings.ini, some of them are not even listed on switchbrew.

**Comment by PoloNX** [comment]
Happy to ear that. Is it an obligation to use makefile directly ? Maybe I can use xmake and you can add this homebrew with a submodule.
Where can I find a list of all settings ?

**Comment by masagrator** [comment]
I was thinking about making each entry with smaller height since by default imo they are too high + f.e. pressing + on highlighted setting to popup explanation what this setting does.

**Comment by PoloNX** [comment]
I will try to improve the ui after doing something which is usable, but you're right

**Comment by PoloNX** [comment]
@masagrator I implemented this quickly, what do you think?
![2024112616001700](https://github.com/user-attachments/assets/aea77671-793a-4307-ba0c-28602cf707dc)

**Comment by SciresM** [comment]
I don't think this especially needs to be happening in the issue tracker for atmosphere.

**Comment by PoloNX** [comment]
> I don't think this especially needs to be happening in the issue tracker for atmosphere.

I sent you a pm on discord

**Comment by impeeza** [comment]
A suggestion from one which do not use discord:

the description could appears on the left side for each item you select on the right side.
