### ISSUE TITLE
Unable to identify package1

### ISSUE THREAD

**Issue by Alherak** [Atmosphere-NX/Atmosphere#2413]
I accidently updated my Switch and every time I try adding the homebrew back it keeps give the unable to identify package1 error no matter what I do, how do I fix this?

**Comment by impeeza** [comment]
upgrade your payload, on the method you use to boot your console, if you use a modchip upgrade SDMC:/payload.bin  .   if you use a payload injector like RCMloader device or TegraRCM or similar, upgrade the payload.bin on that devices.  if you use a payload chaninloader, update the payload on that chainloader.

please for support, go to discord or GBATemp, please close this issue, the issues are for report bugs or ask features.
