### ISSUE TITLE
Games will not open after update

### ISSUE THREAD

**Issue by Fa1lnaught** [Atmosphere-NX/Atmosphere#2415]
### What's the issue you encountered?

I updated to the newest atmosphere and now my games won't open. It says "Failure to start software. Return to home menu and try again. It seems like any program or game not already on the switch (Tinfoil, retroarch, castlevania symphony of the night or other games for prior consoles

### How can the issue be reproduced?

Update switch to the newest update by accident. Try to update atmosphere

### System Firmware Version
OFW: 19 .0
AMS: 1.8.0
Hekate 6.2.0

**Comment by masagrator** [comment]
Piracy is not supported.
