### ISSUE TITLE
Can´t Connect to game servers on Sysnand (with atmosphere)

### ISSUE THREAD

**Issue by joaoluizmbm** [Atmosphere-NX/Atmosphere#2417]
### What's the issue you encountered?

[ Can´t connect to games server on sysnand with atmosphere. I tryed to play fortnite on sysnand with atmosphere, but it shows the following error message: "An error ocurred while connecting to Epic servers. Please try again later" (ESP-DIST-001).]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Just try to play fortnite on sysnand with atmosphere. ]</br>

### Crash Report

[ N/A ]</br>

### System Firmware Version

19.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: Official
  - Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: [ No ]
- EmuMMC or SysNAND:
  - [SysNAND with atmosphere ]

### Additional context?

- Additional info about your environment:
- [ N/A]

**Comment by borntohonk** [comment]
> [ Can´t connect to games server on sysnand with atmosphere. I tryed to play fortnite on sysnand with atmosphere, but it shows the following error message: "An error ocurred while connecting to Epic servers. Please try again later" (ESP-DIST-001).]

I saw this github issue so i tested the following:

1. Downloaded atmosphere https://github.com/Atmosphere-NX/Atmosphere/releases/tag/1.8.0-prerelease
2. booted into atmosphere with fusee.bin
3. went to eshop, downloaded fortnite (23.2GB)
4. started fortnite, paired my epic account when prompted
5. started a ranked royale game

I cannot reproduce your issue, you probably are using 90dns/dns mitm config of sorts / cal0 blanker in hekate / exosphere.ini blanker/ your location is banned from reaching epic servers or similar.

If you're pirating it, despite it being a FREE TITLE on eshop, then that'd be your own self-caused problem.


![2024102422130700-F489C99A244DF57DCBDC4BFD2DB926F1](https://github.com/user-attachments/assets/f57e4f31-2ef3-407d-95e3-d4f7a29f2b97)
