### ISSUE TITLE
Fatal error while running Atmosphere

### ISSUE THREAD

**Issue by tangerine-aarch64** [Atmosphere-NX/Atmosphere#2418]
## Bug Report

What's the issue you encountered?
While using the GDB debugger to debug a program on my Nintendo Switch, I detached dmnt before starting the debugging session to avoid known conflicts. When I attempt to connect to the Switch using GDB and start the debugging session, the system crashes immediately, even before reaching the point where the program would stop at a breakpoint.

An error message appears:

**A fatal error occurred when running Atmosphère.
Program ID: 010000000000100D609
Error Description: std::abort() called (0xFFE)**

### How can the issue be reproduced?

Detach dmnt before starting the debugging session (with [PointerSearcher-SE](https://github.com/tomvita/PointerSearcher-SE))

Use GDB to connect to the Nintendo Switch:
1. (gdb) target extended-remote 192.168.2.20:22225
2. (gdb) monitor wait application

Observe that the system crashes immediately with the error message before any breakpoint is reached.
This issue didn't occur before it started happening after this update.

### Crash Report
N/A

### System Firmware Version
Atmosphere 1.8.0 pre-release

### Environment?
What bootloader was Atmosphère launched by: **Hekate**
Official release or unofficial build: **Atmosphere-1.8.0-prerelease-c6014b533**
Do you have additional kips or sysmodules you're loading: **Noexes** (Dynamic), **MissionControl** (Static)

Homebrew software installed: I am using HATS, and have the following homebrew software installed:
- Switch 90DNS tester
- Hekate+AMS-package3-sigpatches-1.8.0P2-cfw-19.0.0_V4
- hekate_ctcaer_6.2.2_Nyx_1.6.4
- Atmosphere-1.8.0-prerelease-c6014b533
- Tinfoil 18.0 V1 Applet Mode
- DBI 658
- Homebrew Appstore 2.3.2
- FTPD Pro 3.1.0
- NX-Shell 4.0.1
- Tesla Menu (ovlmenu.ovl) 16.00
- JKSV 08.06.2024
- Edizon SE 3.8.37
- AIO-Switch-Updater V2.23.2
- Goldleaf 1.0.0
- Mission Control 0.12.0
- Linkalho 2.0.1
- Tinwoo 1.0.26

EmuMMC or SysNAND: **SysNAND**

### Additional context?
N/A

Thank you in advance, I really appreciate it! 😊

**Comment by SciresM** [comment]
...ah. Also, piracy is not supported.
