### ISSUE TITLE
Blue Screen issue in Stock /Sys Mmc 

### ISSUE THREAD

**Issue by FixwitRaj** [Atmosphere-NX/Atmosphere#2422]
Switch version : 19.0
Atmosphere: pre release 
Downgraded to 18.1.0
Tinfoil works in cfw

Whenever launching Stock /Sysmmc blue screen appears, However after removing sd card, stock boot working.

All other functions working normally in CFW
![Uploading image.jpg…]()

**Comment by borntohonk** [comment]
Piracy not supported

**Comment by SciresM** [comment]
Even ignoring the piracy, this is an issue about a problem with "stock", which is not atmosphere, and shouldn't be on the atmosphere repo.
