### ISSUE TITLE
stuck in a black screen while in sleep mode

### ISSUE THREAD

**Issue by Astr4l1ty** [Atmosphere-NX/Atmosphere#2425]
### What's the issue you encountered?

When my switch goes in sleep mode it stays stuck on a black screen until i restart by holding the power button.

### How can the issue be reproduced?

Just put your Switch in sleep mode

### Crash Report

It doesn't save any crash reports when this happens.

### System Firmware Version

19.0.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: Official
  - version : 6.2.2
- Do you have additional kips or sysmodules you're loading: yes
    sysmodules: sysclk, sys-patch
- Homebrew software installed: hbmenu official v3.6.0; nx-hbloader official v2.4.4
- EmuMMC or SysNAND: EmuMMC
  - partition-based

### Additional context?

This happens on a modchipped OLED
I tried disabling additional kips and sysmodules
I didn't tested on file-based emuMMC, I will test
I have 19.0.0 installed as OFW and CFW
This only happens on 19.0.0

**Comment by impeeza** [comment]
Seems is a problem of FW 19 not of Atmosphère:

https://gonintendo.com/contents/41253-switch-firmware-update-19-0-0-now-available-updates

**Comment by Astr4l1ty** [comment]
Well your right bcoz it just happened to me without Atmosphère...
I hope Nintendo will fix this asap.

**Comment by WestonGuidero** [comment]
I updated Sysclk to the latest and it fixed it for me.

**Comment by schizofrog** [comment]
I deleted Atmosphere, Bootloader, Sigpatches and reinstalled them, I no longer black screen in sleep and it works fine for me

**Comment by Astr4l1ty** [comment]
Fixed it by updating sys-clk thanks @WestonGuidero
