### ISSUE TITLE
NSP to NRO forwarders not working

### ISSUE THREAD

**Issue by resurrecta** [Atmosphere-NX/Atmosphere#2426]
Since the change to the 1.8.0 pre-release, the forwarders no longer work.
https://nsp-forwarder.n8.io/
These used to work well on the previous version. This means right now that for example the Homebrew Store can't be displayed on the main menu anymore.
When I try it, just crashes... Black screen, it can not be started.

**Comment by SciresM** [comment]
Piracy is not supported.

**Comment by resurrecta** [comment]
Hey, I normally don't fall in discussions over piracy. But could you explain how building a forwarder with own keys to reference the homebrew app itself is considered piracy?

Thank you for your attention
Op 28 okt. 2024, om 00:10, SciresM ***@***.******@***.***>> schreef:

Closed #2426<https://github.com/Atmosphere-NX/Atmosphere/issues/2426> as completed.

**Comment by Masamune3210** [comment]
It requires sigpatches, its considered piracy.

**Comment by SciresM** [comment]
All installed content requiring signature patches is indistinguishable from piracy to Atmosphere (and  Nintendo), so support is provided for none of it.
