### ISSUE TITLE
Fatal Error (Program ID 690000000000000d

### ISSUE THREAD

**Issue by illuminatusdeus** [Atmosphere-NX/Atmosphere#2429]
Faced issue of fatal error / crash. Atmosphere does not boot at all.

![Error](https://github.com/user-attachments/assets/37f658ae-6188-4ead-92f5-7cca14ab052b)
[report_000000001ca36d3b.zip](https://github.com/user-attachments/files/17557685/report_000000001ca36d3b.zip)

I deleted the folder from Atmosphere content folder and the problem was resolved. Just thought I'd report this problem to devs.

**Comment by borntohonk** [comment]
> I deleted the folder from Atmosphere content folder and the problem was resolved. Just thought I'd report this problem to devs.

You can go ahead and close this issue as your report is filed in the wrong github repository. The error you're experiencing belongs to sys-con, which i belive current maintainer is this one https://github.com/o0Zz/sys-con/issues

**Comment by Ishi25** [comment]
Thank you, it deletting the folder solved the problem for me too

**Comment by illuminatusdeus** [comment]
I am closing the issue, as the problem has been solved and as advised. For the same problem, do use this thread as reference to resolve this problem if faced in the future. Thank you to all contributors in the scene!
