### ISSUE TITLE
white screen after CFW launch

### ISSUE THREAD

**Issue by fculpo** [Atmosphere-NX/Atmosphere#243]
In hekate, when launching Atmosphere 0.7.0 to 0.7.3, I only get a white screen just after the end loading kips.

I got all setup files from SDSetup Default (homebrew only)

**Comment by SciresM** [comment]
This occurs for all Atmosphere versions?

Could you delete the atmosphere folder on your SD card, and try using a fresh copy of the latest release? Does the issue occur when launching via fusee-primary and not hekate?

**Comment by fculpo** [comment]
Switch 6.0.1
Atmosphere 0.7.3
Booted via fusee-primary

Result: ok BUT hbmenu does not find switch folder

**Comment by fculpo** [comment]
Archive bit cleared
Now works fine.

I will try to add more sdfiles and see if i can reproduce the white screen.
