### ISSUE TITLE
Support for Switch Firmware 19.0.1 After Forced Update

### ISSUE THREAD

**Issue by Spenzeus** [Atmosphere-NX/Atmosphere#2430]
Hello Atmosphere team,

First of all, thank you for all your hard work on Atmosphere and your support for the community. I'm reaching out to request support for Switch firmware version 19.0.1 in a future update.

Recently, my Switch was automatically updated to version 19.0.1 due to a forced update, and since then, I've encountered compatibility issues when trying to run Atmosphere CFW. I understand that the current version of Atmosphere supports up to firmware 19.0.0, but not for 19.0.1.

Could you please provide an update on when Atmosphere might support 19.0.1? Any information on a timeline or possible workarounds would be greatly appreciated.

Thank you for your assistance and for everything you do!

![IMG_20241101_164333_NR](https://github.com/user-attachments/assets/0e372b3b-d61e-4cb6-ab48-f60205a3436b)

**Comment by SciresM** [comment]
The latest prerelease already has support.
