### ISSUE TITLE
Crash Report error code 2002-1004

### ISSUE THREAD

**Issue by conscript86** [Atmosphere-NX/Atmosphere#2435]
### What's the issue you encountered?

Getting error code 2002-1004 when DRAGON BALL Z: KAKAROT is executed. It only happens with this game.
The Nintendo screen shows the this message: The software closed because an error occurred.

### How can the issue be reproduced?

Same result after each time the game starts

### Crash Report

Atmosphère Crash Report (v1.7):
Result:                          0xD407D802 (2002-1004)

Process Info:
    Process Name:                AT
    Program ID:                  010051c0134f8000
    Process ID:                  0000000000000175
    Process Flags:               00000877
    User Exception Address:      00000036418eb000
Exception Info:
    Type:                        User Break
    Address:                     0000002a3ee624d4 (nnSdk + 0xfc4d4)
    Break Reason:                0x0
    Break Address:               00000070e522bbd8
    Break Size:                  0x4
Crashed Thread Info:
    Thread ID:                   000000000000ad4d
    Thread Name:                 GameThread
    Stack Region:                00000070e512c000-00000070e522c000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000070e522bbd8
        X[02]:                   0000000000000004
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000070e522ba20
        LR:                      0000002a3edbc518 (nnSdk + 0x56518) (_ZN2nn4diag6detail5AbortEPKNS_6ResultE + 0x18)
        SP:                      00000070e522ba20
        PC:                      0000002a3ee624d0 (nnSdk + 0xfc4d0)
    Stack Trace:
        ReturnAddress[00]:       0000002a3edbae10 (nnSdk + 0x54e10)
        ReturnAddress[01]:       0000002a3edbaed8 (nnSdk + 0x54ed8)
        ReturnAddress[02]:       0000002a3edee168 (nnSdk + 0x88168)
        ReturnAddress[03]:       0000002a35cc9290 (AT-Switch-Shipping.nss + 0x20c5290)
        ReturnAddress[04]:       0000002a33c110e0 (AT-Switch-Shipping.nss + 0xd0e0)
        ReturnAddress[05]:       0000002a3ee35b48 (nnSdk + 0xcfb48)
        ReturnAddress[06]:       0000002a3ee3a314 (nnSdk + 0xd4314)
        ReturnAddress[07]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0070e522ba20 00 bb 22 e5 70 00 00 00 10 ae db 3e 2a 00 00 00
                                 0070e522ba30 00 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00
                                 0070e522ba40 a8 ba 22 e5 70 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522ba50 e9 5d 71 3f 2a 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522ba60 00 00 00 00 00 00 00 00 02 d8 07 d4 00 00 00 00
                                 0070e522ba70 00 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00
                                 0070e522ba80 a8 ba 22 e5 70 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522ba90 e9 5d 71 3f 2a 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522baa0 00 00 00 00 00 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522bab0 a0 bb 22 e5 70 00 00 00 50 25 f5 3f 2a 00 00 00
                                 0070e522bac0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0070e522bad0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0070e522bae0 00 00 00 00 00 00 00 00 9c df a7 1a 71 00 00 00
                                 0070e522baf0 18 bf 22 e5 70 00 00 00 02 d8 07 d4 00 00 00 00
                                 0070e522bb00 c0 bb 22 e5 70 00 00 00 d8 ae db 3e 2a 00 00 00
                                 0070e522bb10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 00000036418eb600
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0036418eb600 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb610 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb620 53 46 43 4f 00 00 00 00 00 00 00 00 0e 61 f9 21
                                 0036418eb630 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb640 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb650 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb660 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb670 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb680 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb690 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Module Info:
    Number of Modules:           4
    Module 00:
        Address:                 0000002a33c00000-0000002a33c02000
        Name:                    nnrtld
        Module Id:               31A2773EA6928FFE3D32B17B3AD08F54826DA39F000000000000000000000000
    Module 01:
        Address:                 0000002a33c04000-0000002a38861000
        Name:                    AT-Switch-Shipping.nss
        Module Id:               389E38618E93A5E08C7703019E863B6100000000000000000000000000000000
    Module 02:
        Address:                 0000002a3e659000-0000002a3e9c4000
        Name:                    multimedia
        Module Id:               5A7ADA8DD7447C10AA244944F64D0AFF17C50539000000000000000000000000
    Module 03:
        Address:                 0000002a3ed66000-0000002a3f2a6000
        Name:                    nnSdk
        Module Id:               AD3FDFBD62A5F4B082D385FFE420D4400ABB831D000000000000000000000000
Thread Report:
Number of Threads:               03
Threads[00]:
    Thread ID:                   000000000000ad40
    Thread Name:                 MainThread
    Stack Region:                000000711aa6e000-000000711aa7e000
    Registers:
        X[00]:                   000000711aa7dd9c
        X[01]:                   000000711aa7dd98
        X[02]:                   0000000000000001
        X[03]:                   ffffffffffffffff
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      000000711aa7ddb0
        LR:                      0000002a3ee3a4d4 (nnSdk + 0xd44d4) (_ZN2nn2os6detail26ThreadManagerImplByHorizon17WaitForExitThreadEPNS0_10ThreadTypeE + 0x34)
        SP:                      000000711aa7dd70
        PC:                      0000002a3ee6243c (nnSdk + 0xfc43c)
    Stack Trace:
        ReturnAddress[00]:       0000002a3ee35ccc (nnSdk + 0xcfccc) (_ZN2nn2os6detail13ThreadManager10WaitThreadEPNS0_10ThreadTypeE + 0x1c)
        ReturnAddress[01]:       0000002a33c10758 (AT-Switch-Shipping.nss + 0xc758) (nnMain + 0x78)
        ReturnAddress[02]:       0000002a3ee071ec (nnSdk + 0xa11ec) (_ZN2nn4init5StartEmmPFvvES2_ + 0x4c)
        ReturnAddress[03]:       0000002a33c000c0 (nnrtld + 0xc0)
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 00711aa7dd70 9c dd a7 1a 71 00 00 00 00 00 00 00 00 00 00 00
                                 00711aa7dd80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00711aa7dd90 80 b0 f5 3f 2a 00 00 00 f2 01 07 00 00 00 00 00
                                 00711aa7dda0 70 12 c0 33 2a 00 00 00 f0 dd a7 1a 71 00 00 00
                                 00711aa7ddb0 e0 dd a7 1a 71 00 00 00 cc 5c e3 3e 2a 00 00 00
                                 00711aa7ddc0 00 40 c0 33 2a 00 00 00 00 00 00 00 00 00 00 00
                                 00711aa7ddd0 70 12 c0 33 2a 00 00 00 00 00 10 00 00 00 00 00
                                 00711aa7dde0 c0 df a7 1a 71 00 00 00 58 07 c1 33 2a 00 00 00
                                 00711aa7ddf0 00 90 f5 3f 2a 00 00 00 50 b2 f5 3f 2a 00 00 00
                                 00711aa7de00 00 de a7 1a 71 00 00 00 00 de a7 1a 71 00 00 00
                                 00711aa7de10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00711aa7de20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 00711aa7de30 03 01 00 00 10 00 01 00 00 00 a9 41 4f 00 00 00
                                 00711aa7de40 00 c0 12 e5 70 00 00 00 00 00 10 00 00 00 00 00
                                 00711aa7de50 00 00 00 00 00 00 00 00 70 07 c1 33 2a 00 00 00
                                 00711aa7de60 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 00000036418eb200
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0036418eb200 00 00 00 00 14 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb210 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb220 53 46 43 4f 00 00 00 00 00 00 00 00 95 c8 f5 88
                                 0036418eb230 e8 07 0b 04 13 12 1b 00 01 00 00 00 34 01 00 00
                                 0036418eb240 43 45 54 00 00 00 00 00 00 00 00 00 10 0e 00 00
                                 0036418eb250 00 00 00 00 00 00 00 00 90 e4 b2 a1 06 00 00 00
                                 0036418eb260 10 df b2 a1 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb270 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb280 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb290 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb2a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb2b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb2c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb2d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb2e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb2f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Threads[01]:
    Thread ID:                   000000000000ad4b
    Thread Name:                 NxSystemThread
    Stack Region:                00000071030ea000-00000071030eb000
    Registers:
        X[00]:                   00000071030eab5c
        X[01]:                   00000071030ead74
        X[02]:                   0000000000000001
        X[03]:                   ffffffffffffffff
        X[04]:                   ffffffffffffffff
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000071030eab60
        LR:                      0000002a3ee39df4 (nnSdk + 0xd3df4) (_ZN2nn2os6detail22MultiWaitImplByHorizon20WaitSynchronizationNEiPjil + 0x24)
        SP:                      00000071030eab40
        PC:                      0000002a3ee6243c (nnSdk + 0xfc43c)
    Stack Trace:
        ReturnAddress[00]:       0000002a3ee37304 (nnSdk + 0xd1304) (_ZN2nn2os6detail13MultiWaitImpl19InternalWaitAnyImplEbNS_8TimeSpanE + 0x134)
        ReturnAddress[01]:       0000002a3ee37568 (nnSdk + 0xd1568) (_ZN2nn2os6detail13MultiWaitImpl11WaitAnyImplEbNS_8TimeSpanE + 0xa8)
        ReturnAddress[02]:       0000002a3ee33ca4 (nnSdk + 0xcdca4)
        ReturnAddress[03]:       0000002a3ee33c0c (nnSdk + 0xcdc0c)
        ReturnAddress[04]:       0000002a3ee33bfc (nnSdk + 0xcdbfc)
        ReturnAddress[05]:       0000002a3ee35b48 (nnSdk + 0xcfb48)
        ReturnAddress[06]:       0000002a3ee3a314 (nnSdk + 0xd4314)
        ReturnAddress[07]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0071030eab40 5c ab 0e 03 71 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eab50 ac cc 12 7a 27 84 f8 7f 00 00 00 00 00 00 00 00
                                 0071030eab60 d0 ae 0e 03 71 00 00 00 04 73 e3 3e 2a 00 00 00
                                 0071030eab70 c8 13 fb 3f 2a 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eab80 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eab90 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eaba0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eabb0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eabc0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eabd0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eabe0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eabf0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eac00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eac10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eac20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0071030eac30 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 00000036418eb400
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0036418eb400 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb410 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb420 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb430 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb440 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb450 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb460 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb470 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb480 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb490 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb4a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb4b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb4c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb4d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb4e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb4f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
Threads[02]:
    Thread ID:                   000000000000ad4d
    Thread Name:                 GameThread
    Stack Region:                00000070e512c000-00000070e522c000
    Registers:
        X[00]:                   0000000000000000
        X[01]:                   00000070e522bbd8
        X[02]:                   0000000000000004
        X[03]:                   0000000000000000
        X[04]:                   0000000000000000
        X[05]:                   0000000000000000
        X[06]:                   0000000000000000
        X[07]:                   0000000000000000
        X[08]:                   0000000000000000
        X[09]:                   0000000000000000
        X[10]:                   0000000000000000
        X[11]:                   0000000000000000
        X[12]:                   0000000000000000
        X[13]:                   0000000000000000
        X[14]:                   0000000000000000
        X[15]:                   0000000000000000
        X[16]:                   0000000000000000
        X[17]:                   0000000000000000
        X[18]:                   0000000000000000
        X[19]:                   0000000000000000
        X[20]:                   0000000000000000
        X[21]:                   0000000000000000
        X[22]:                   0000000000000000
        X[23]:                   0000000000000000
        X[24]:                   0000000000000000
        X[25]:                   0000000000000000
        X[26]:                   0000000000000000
        X[27]:                   0000000000000000
        X[28]:                   0000000000000000
        FP:                      00000070e522ba20
        LR:                      0000002a3edbc518 (nnSdk + 0x56518) (_ZN2nn4diag6detail5AbortEPKNS_6ResultE + 0x18)
        SP:                      00000070e522ba20
        PC:                      0000002a3ee624d0 (nnSdk + 0xfc4d0)
    Stack Trace:
        ReturnAddress[00]:       0000002a3edbae10 (nnSdk + 0x54e10)
        ReturnAddress[01]:       0000002a3edbaed8 (nnSdk + 0x54ed8)
        ReturnAddress[02]:       0000002a3edee168 (nnSdk + 0x88168)
        ReturnAddress[03]:       0000002a35cc9290 (AT-Switch-Shipping.nss + 0x20c5290)
        ReturnAddress[04]:       0000002a33c110e0 (AT-Switch-Shipping.nss + 0xd0e0)
        ReturnAddress[05]:       0000002a3ee35b48 (nnSdk + 0xcfb48)
        ReturnAddress[06]:       0000002a3ee3a314 (nnSdk + 0xd4314)
        ReturnAddress[07]:       0000000000000000
    Stack Dump:                               00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0070e522ba20 00 bb 22 e5 70 00 00 00 10 ae db 3e 2a 00 00 00
                                 0070e522ba30 00 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00
                                 0070e522ba40 a8 ba 22 e5 70 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522ba50 e9 5d 71 3f 2a 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522ba60 00 00 00 00 00 00 00 00 02 d8 07 d4 00 00 00 00
                                 0070e522ba70 00 00 00 00 00 00 00 00 03 00 00 00 00 00 00 00
                                 0070e522ba80 a8 ba 22 e5 70 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522ba90 e9 5d 71 3f 2a 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522baa0 00 00 00 00 00 00 00 00 e9 5d 71 3f 2a 00 00 00
                                 0070e522bab0 a0 bb 22 e5 70 00 00 00 50 25 f5 3f 2a 00 00 00
                                 0070e522bac0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0070e522bad0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0070e522bae0 00 00 00 00 00 00 00 00 9c df a7 1a 71 00 00 00
                                 0070e522baf0 18 bf 22 e5 70 00 00 00 02 d8 07 d4 00 00 00 00
                                 0070e522bb00 c0 bb 22 e5 70 00 00 00 d8 ae db 3e 2a 00 00 00
                                 0070e522bb10 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
    TLS Address:                 00000036418eb600
    TLS Dump:                                 00 01 02 03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
                                 0036418eb600 00 00 00 00 0c 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb610 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb620 53 46 43 4f 00 00 00 00 00 00 00 00 0e 61 f9 21
                                 0036418eb630 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb640 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb650 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb660 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb670 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb680 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb690 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6b0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6c0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
                                 0036418eb6f0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

### System Firmware Version

18.1.0</br>

### Environment?

Running off Atmosphere 1.8.0 via fusee.bin
Hekate version v6.2.2
Switch v1

### Additional context?

I first installed a XCI file with Awoo that failed.
I try later with a NSP version with DBI.
I try installing only v0, with last update 1.51, with and without DLCs (always uninstalling the app before).
I also remove save files.

**Comment by SciresM** [comment]
Piracy is not supported. The error is that it's pirated.

**Comment by conscript86** [comment]
I also bought the game digitally in the eshop and have the same problem.
