### ISSUE TITLE
Battery Drain in Sleep Mode after Updating to Switch Firmware 19.0.1 and Atmosphere 1.8.0 (pre-release)

### ISSUE THREAD

**Issue by weakvar** [Atmosphere-NX/Atmosphere#2436]
After updating the Nintendo Switch firmware to version 19.0.1 and Atmosphere to version 1.8.0 (pre-release), the console experiences rapid battery drain while in sleep mode. Within 2 hours, the battery level dropped from 100% to 72% in sleep mode, with no games or applications running in the background. The console was connected to Wi-Fi during this time.

### How can the issue be reproduced?
1. Update Nintendo Switch firmware to 19.0.1.
2. Update Atmosphere to 1.8.0 (pre-release).
3. Update Hekate to v6.2.2 and Nyx to v1.6.4
4. Charge the console to 100%.
5. Put the console into sleep mode.
6. Wait for approximately 2 hours.
7. Check the battery level after this period.

### Crash Report
N/A (No crash occurred).

### System Firmware Version
19.0.1

### Environment?
- **Bootloader**: fusèe
- **Official release or unofficial build**: Official release version 1.8.0 (pre-release)
- **Additional kips or sysmodules loaded**: 
  - sigpatches (updated for Atmosphère 1.8.0-prerelease)
  - sys-patch (updated for Atmosphère 1.8.0-prerelease)
- **Homebrew software installed**: 
  - Daybreak
  - DBI 719
  - Goldleaf 1.0.0
  - Haze
  - JKSV 11/05/2024
  - Linkalho
  - AIO Switch Updater 2.23.2
  - HB App Store 2.3.2
  - Fizeau 2.8.0
  - Sys-patch 1.5.4
  - Tesla Menu 1.2.3
  - nx-ovlloader 1.0.7
  - Hekate v6.2.2 & Nyx v1.6.4
- **EmuMMC or SysNAND**: EmuMMC 

### Additional context?
There was a clean install.

**Comment by SciresM** [comment]
1) piracy is not supported 
2) I do not believe this is an atmosphere issue, I think it affects unpacked consoles using the stock os.
