### ISSUE TITLE
switch sleep mode issue 

### ISSUE THREAD

**Issue by jtetak** [Atmosphere-NX/Atmosphere#2439]
## Bug Report

when i put my switch into safe mode i have to hold my power button for 15 seconds, then i have to reinject my payload to reuse my switch again, ive heard it was an issue that has happened with previous firmwares so should be an easy fix but i figured it would be worth reporting!

**Comment by Tetsuya-Takashi** [comment]
The sleep mode issue, it wasn't an issue with Atmosphère at all, but instead it was an issue with the firmware itself which was fixed in version 19.0.1.

**Comment by GenoCL** [comment]
Did 19.0.1 really fix the issue? I've seen people reporting their consoles are still overheating and draining battery just like that in 19.0.1

**Comment by SciresM** [comment]
It was improved but not fixed in 19.0.1. Either way, it's not an atmosphere issue.
