### ISSUE TITLE
2162-0002 (0x4a2)

### ISSUE THREAD

**Issue by MintyHeal** [Atmosphere-NX/Atmosphere#2440]
### What's the issue you encountered?

After rolling back hos 19 to hos 18, I encountered errors, scored and rearranged everything. When I start atmosphere after a few seconds, I get this: ![photo_2024-11-07_13-43-09](https://github.com/user-attachments/assets/d659fb61-f3fd-4958-8a08-0e1aa9a6655a), in full stock: ![photo_2024-11-07_13-43-04](https://github.com/user-attachments/assets/e0ebf255-a94f-45dd-abce-5c614041b418). 

### Crash Report
https://gist.github.com/MintyHeal/d632ae98af488cf2f1cd6331de22fa30#file-gistfile1-txt

### System Firmware Version

18.1.0</br>

### Environment?
- Hekate
- Unofficial build(https://github.com/Ultra-NX/UltraNX)
- EmuMMC and SysNAND:
  - EmuMMC file-based.

### Additional context?

As explained to me, this happened because I did not reset the old settings, I do not have a backup, the system may shut down after about 15 seconds, after which I receive error messages.

**Comment by borntohonk** [comment]
> * Unofficial build(https://github.com/Ultra-NX/UltraNX)

Uh... your atmosphere crash report says -dirty and ontop of that you even list that...

Why did you even file this github issue here? https://github.com/Ultra-NX/UltraNX/issues

**Comment by MintyHeal** [comment]
> Зачем вы вообще подали эту заявку на github здесь? https://github.com/Ultra-NX/UltraNX/issues
I applied here because I knew the problem and I needed help (the problem is not related to the build)

**Comment by MintyHeal** [comment]
Solving the problem: holding down + - reset the system, and then go to full stock, format the cd, install the firmware
