### ISSUE TITLE
black screen after booting into atmosphere

### ISSUE THREAD

**Issue by LakeCharlesCountyDev** [Atmosphere-NX/Atmosphere#2441]
accidentally updated to firmware 19.0 and my switch will not boot up into atmosphere. I've tried updating atmosphere, and hekate, and sigpatches, so far nothing works. if anyone comes across this post please help me out.

**Comment by Whovian9369** [comment]
Piracy is not supported.

**Comment by LakeCharlesCountyDev** [comment]
how is this related to piracy im just asking a question on how i can fix this issue.

**Comment by LakeCharlesCountyDev** [comment]
i never mentioned anything about piracy

**Comment by impeeza** [comment]
> i never mentioned anything about piracy

Because anything related to sigpatches is piracy. 

Also THIS IS NOT A SUPPORT site, if you need support go to Discord or GBATemp.

This site is only for report Atmosphère issues or bugs. This is not 

Please close and leave this post closed

**Comment by LakeCharlesCountyDev** [comment]
well many other people have opened issues related to atmosphere and they have asked for support and recieved answers. IM ONLY STATING THAT I'VE UPDATED MY SIGPATCHES. I DO NOT NEED ANYTHING SIGPATCHES RELATED FROM ANYONE IM JUST ASKING FOR A SOLUTION.
