### ISSUE TITLE
Mario & Luigi Brothership Crashes Atmosphere

### ISSUE THREAD

**Issue by TheMarioMan24** [Atmosphere-NX/Atmosphere#2442]
Bug Report

What's the issue you encountered?

After booting up Mario & Luigi Brothership through from my physical copy of the game, Atmosphere crashes a little after 5 second of the loading screen with the ship.
![Screenshot 2024-11-07 225546](https://github.com/user-attachments/assets/761a9e3f-a682-421d-b3b4-7307c9937fd5)

I tested this in Atmosphere 1.17.1 and then updated my Firmware to V19.0.1 and Atmosphere to V18.0.0 and the game still crashed.

### How can the issue be reproduced?

1. Boot up Atmosphere.
2. Start up Mario & Luigi Brothership

Crash Report

(https://gist.github.com/TheMarioMan24/32d5ccd7d20754dd6c9832840862cd55)

System Firmware Version

19.0.1

Environment

Tested by using both Hekate and Fusee
Official release V18.0.0
SysNAND

Here is an image of the error
![Screenshot 2024-11-07 22-46-59](https://github.com/user-attachments/assets/8012767e-8dbe-4b2c-9057-b0e4f9de79fc)

**Comment by impeeza** [comment]
> Bug Report
> 
> What's the issue you encountered?
> 
> After booting up Mario & Luigi Brothership through from my physical copy of the game, Atmosphere crashes a little after 5 second of the loading screen with the ship.
> 
> I tested this in Atmosphere 1.17.1 and then updated my Firmware to V19.0.1 and Atmosphere to V18.0.0 and the game still crashed.
> ### How can the issue be reproduced?
> 
>     1. Boot up Atmosphere.
> 
>     2. Start up Mario & Luigi Brothership
> 
> 



You have installed a Audio SYS-Module, by example [TriPlayer](https://github.com/tallbl0nde/TriPlayer), [sys-tune](https://www.gamebrew.org/wiki/Sys-tune_Switch) or [NX-BootSound](https://gbatemp.net/threads/bootsoundnx-boot-sound-on-nintendo-switch.547488/), disable them and reboot your console.

also can try backing up and deleting the folder SDMC:/atmosphere/content/0100000000000014

Please remember this is not a support forum, is solely for report issues and bugs.

for further support please go to Discord or GBATemp, and please close this issue.
