### ISSUE TITLE
Kernel Panic Error

### ISSUE THREAD

**Issue by 4elovek13** [Atmosphere-NX/Atmosphere#2443]
![KernelPanicPhotoError](https://github.com/user-attachments/assets/11d17c86-1587-4114-b7e7-01da3fdc7b1c)
I have error on running atmosphere 
After booting Atmosphere, the logo is show
for a short moment, then black screen with this error:
Error Desc:Kernel Panic(0xf00)
[report_00000000068a7080.zip](https://github.com/user-attachments/files/17734043/report_00000000068a7080.zip)

Programm ID:524850534f53454d
EmuMMC version:18.1.0
Semi-Stock version:18.1.0
4ifir version: 2.4

**Comment by impeeza** [comment]
IS NOT an Atmosphère issue,  DELETE your SDMC:/atmosphere/contents folder and try again.

This is no a support site, please go to GBATemp and search there the ultimate guide to upgrade your firmware/atmosphere

please close the issue.
