### ISSUE TITLE
Keeps getting corrupt installations of recent game or update

### ISSUE THREAD

**Issue by dothackjhe** [Atmosphere-NX/Atmosphere#2448]
Installing any of the recent dumps of games and updates (Farmagia, Dragon Quest III HD-2D, Shin Megami Tensei V: Vengeance 1.0.3) results in a corrupted installation.

The issue occurs whether using DBI 658 via DBI Backend or MTP or via Tinleaf + NSUSBLoader.

FW 19.0.0

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 6.2.2 & Nyx 1.6.4
- Official release or unofficial build: Official build (Hekate 6.2.2)
- Do you have additional kips or sysmodules you're loading: None
- Homebrew software installed: [ Checkpoint, Daybreak, DBI, FTPD Classic, FTPD Pro, JKV, Goldleaf, Tinleaf ]
- EmuMMC or SysNAND: SysNAND

Uses Atmosphere 1.8.0.

**Comment by SciresM** [comment]
Piracy is not supported.
