### ISSUE TITLE
Crash while enabling Airplane Mode 

### ISSUE THREAD

**Issue by ramthescnd** [Atmosphere-NX/Atmosphere#245]
Enabling Airplane Mode while running Atmosphere crashes the System with Error Code 2277-0003. Switch is on 5.1.0, Atmosphere is on 0.7.3 (Crash happend also on earlier versions..).

**Comment by ramthescnd** [comment]
@SciresM Had some additional kips, removed Switch-Presence (Basically People can see what you are playing on your Switch on Discord), was launching via fusee. You can probably close this one now.
Thank you for the fast help/reply!

**Comment by SciresM** [comment]
Cool :)
