### ISSUE TITLE
Panic occurred while running Atmosphere. Title ID: 4200000000000010

### ISSUE THREAD

**Issue by Kikkman** [Atmosphere-NX/Atmosphere#2450]
Every time I go to atmosphere it gives an error:

**Panic occurred while running Atmosphere.

Title ID:420000000000010
Error:std::abort (0xFFE)**

What should I do?

**Comment by masagrator** [comment]
Remove "420000000000010" folder from `atmosphere/contents`

Next time don't ask such questions here, it's for bugs, not user support.
