### ISSUE TITLE
Death Road to Canada not running on latest CFW

### ISSUE THREAD

**Issue by Albarosie** [Atmosphere-NX/Atmosphere#2454]
## Bug Report

 "N/A". ]</br>
</br>

</br>
</br> yes, Atmosphere
</br> N/A
</br> N/A
</br> N/A

### What's the issue you encountered?

</br> I installed the new Bluepack and updated to 19.0.1 everything went well
</br> N/A
</br> N/A

### How can the issue be reproduced?

</br> i tried to start the Game "Death Road to Canada" we tried on two cfw Consoles with 19.0.1 on it on Both it did not work. It say's; there was a Mistake. The Game has been shut down"
</br>Just start Death Road to Canada

### Crash Report

</br> N/A
</br> N/A
</br> N/A

### System Firmware Version

19.0.1</br>
</br> 1.8.0 Blue
</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: Official Relase 19.0.1
  
  https://github.com/glitched-nx/blue_pack_NX/releases/tag/3.0.0
 
- Do you have additional kips or sysmodules you're loading: no
- Homebrew software installed: everything thats in the Blue Pack and the newest fizeau
- EmuMMC or SysNAND:
  Partition Based EmuMMC

### Additional context?

- Additional info about your environment: N/A

**Comment by Albarosie** [comment]
It would be Awesome to make the game playable again. Its one of my favorites

**Comment by masagrator** [comment]
> * Official Relase 19.0.1

This pack doesn't use official release. Please be better informed next time when making an issue report.
How I know? Compare stratosphere.romfs, they are different

**Comment by impeeza** [comment]
> ## Bug Report
> 
> "N/A". ]
> 
> 
> yes, Atmosphere
> N/A
> N/A
> N/A
> ### What's the issue you encountered?
> 
> I installed the new Bluepack and updated to 19.0.1 everything went well N/A N/A
> ### How can the issue be reproduced?
> 
> i tried to start the Game "Death Road to Canada" we tried on two cfw Consoles with 19.0.1 on it on Both it did not work. It say's; there was a Mistake. The Game has been shut down" Just start Death Road to Canada
> ### Crash Report
> 
> N/A N/A N/A
> ### System Firmware Version
> 
> 19.0.1 1.8.0 Blue
> ### Environment?
> 
>     * What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
> 
>     * Official release or unofficial build: Official Relase 19.0.1
>       https://github.com/glitched-nx/blue_pack_NX/releases/tag/3.0.0
> 
>     * Do you have additional kips or sysmodules you're loading: no
> 
>     * Homebrew software installed: everything thats in the Blue Pack and the newest fizeau
> 
>     * EmuMMC or SysNAND:
>       Partition Based EmuMMC
> 
> 
> ### Additional context?
> 
>     * Additional info about your environment: N/A

You didn't fill the form correctly AND PIRACY IS NOT SUPPORTED, PLEASE CLOSE THE ISSUE.

**Comment by impeeza** [comment]
By the way I just buy on the nintendo store and works fine with Atmosphère 1.8.0 and FW 19.0.1

**Comment by Albarosie** [comment]
Thanks for the reply. I own the game but want to play it with a Mod. Ok i'll try to change the Atmosphere Blue with the prerelease of Atmosphere. Is it safe to just switch them in Copy Paste? Thanks a lot after the reply i'll close it. If that is ok

**Comment by impeeza** [comment]
It's no a atmosphère issue, please close the issue, for support go to Discord or GBATemp.
