### ISSUE TITLE
Crashes when connected to wifi

### ISSUE THREAD

**Issue by PSERUM** [Atmosphere-NX/Atmosphere#2456]
### What's the issue you encountered?

</br>When Wifi is on Emummc will boot but after a while it just crashes. Tried with airplane mode on Emummc worked perfectly</br>
No, just stock Atmosphere</br>

### How can the issue be reproduced?

[ * ]</br>
Boot Emummc, wait for a while with wifi on and crashes</br>

### Crash Report
[01732379159_010000000000002f.log](https://github.com/user-attachments/files/17881814/01732379159_010000000000002f.log)

### System Firmware Version

19.0.0, Atmosphere 1.8.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: Official 1.8.0
- EmuMMC or SysNAND: EmuMMC
  - [ If using an EmuMMC, include whether it's partition-based or file-based. ]

**Comment by masagrator** [comment]
> ### How can the issue be reproduced?
> [ * ] Boot Emummc, wait for a while with wifi on and crashes

If you would install fresh Atmosphere, you would see this cannot be reproduced.

Issue happens because you have blanking prodinfo enabled which crashes from some FW version. Disable blanking prodinfo in exosphere.ini

**Comment by PSERUM** [comment]
I tried a fresh install and also disabled blanking prodinfo, still no luck

[01732414645_010000000000002f.log](https://github.com/user-attachments/files/17891401/01732414645_010000000000002f.log)

**Comment by impeeza** [comment]
RTFM

this issue was explained several times, if you use the search  on the issue you will find the answer, APPLY ATMOSPHÈRE'S DNSMiTM.

PLEASE CLOSE THE ISSUE

IF YOU NEED SUPPORT GO TO DISCORD.

**Comment by PSERUM** [comment]
I followed all the guides and was pretty sure I did everything right but it's still crashing on me, that's the reason why I posted the problem here to begin with. I ended up having to take my switch to my local repair shop. They said the wifi chip was desoldered and had to replace them for me at a cost. After replacing everything worked out. Closing the thread.
