### ISSUE TITLE
Retroarch blocked by Firmware 18.0.1 and atmosphere 18.0.1

### ISSUE THREAD

**Issue by IsraelCarry22** [Atmosphere-NX/Atmosphere#2468]
Hi.
I need your help, install retroarch from the official page, copy and paste the files from the root of the sd card and it gives me this error.

This error still persists if I follow the steps I read about the same problem, here on GitHub, but it doesn't work, it still gives the same "block"

attached link https://github.com/Atmosphere-NX/Atmosphere/issues/2322

![40599eb6-ec8e-41d0-bda5-615227c84839](https://github.com/user-attachments/assets/7799946a-6c52-423d-8eb7-f787d5c9feaf)

**Comment by impeeza** [comment]
This is not a support forum, please go to Discord or GBATemp. close the issue

**Comment by IsraelCarry22** [comment]
#821
