### ISSUE TITLE
[Feature request] Ability to overclock/underclock the cpu/gpu in handheld/dock mode. 

### ISSUE THREAD

**Issue by NightlyFox** [Atmosphere-NX/Atmosphere#248]
## Feature Request
Give the user the ability to overclock/underclock their cpu/gpu

### Why would this feature be useful?
Allows for better performance on emulators and get rid of framerate drops.
If you dock your switch, when you overclock you wont have to worry about battery life. 

Underclocking for less demanding titles/emulators would allow the switch to conserve battery life in handheld mode

**Comment by NightlyFox** [comment]
> It would be nice to be able to underclock too. Some games (like stardew valley) barely even push the switch at all. It be nice to be able to save that power.
Good idea, didnt think of that! Would be nice to improve battery life in handheld mode.

Edited it so it includes both :)

**Comment by NightlyFox** [comment]
Now, here is a crazy idea. Maybe also include the ability to have unique preset clock rates for individual games/hombrew? So every time you launch that specific title/homebrew it automatically overclocks/underclocks the gpu/cpu to the speed you set it to. That way we can also have a preset cpu/gpu clock speed for the home menu, and if the user wants to they can maximize the use out of their device based on the title/homebrew. 

Also as a possibility, give the user an option to choose clock rates based on whether the switch is in handheld or docked mode.

**Comment by m4xw** [comment]
You guys have no patience, do you?

**Comment by fennectech** [comment]
I’m curious.  How would changing the clock speed brick the device (other than the obvious overheating.).   But the switch has decent thermals and will shut down if it overheats.

**Comment by Specced** [comment]
Ine thing is supporting underclocking but overclocking is not needed.

30. okt. 2018 kl. 23:19 skrev FennecTECH <notifications@github.com<mailto:notifications@github.com>>:


I’m curious. How would changing the clock speed brick the device (other than the obvious overheating.). But the switch has decent thermals and will shut down if it overheats.

**Comment by fennectech** [comment]
why not?   More processor performance is always good   Alot of games on switch chug a good bit (like skyrim)      if someone has a large battery bank or plays on dock power isnt an issue.

**Comment by misson20000** [comment]
Playing with power and clock settings is a very easy way to cause permanent hardware damage if you get anything wrong a single time. We don't know what settings we can safely play with and don't want to find out the hard way.
