### ISSUE TITLE
switch wont turn on after sleep mode for several hrs

### ISSUE THREAD

**Issue by Aighttttt** [Atmosphere-NX/Atmosphere#249]
i put my switch into sleep mode and it wont turn on i was running atmpahere 0.7.2

**Comment by ZachyCatGames** [comment]
What firmware are you on, 6.0.0 just kinda does that sometimes

**Comment by drofdoom** [comment]
Hold power for 16 seconds .

**Comment by noirscape** [comment]
What RCM method are you using?

**Comment by Aighttttt** [comment]
i know but its a bit annoying to have to inject the payload everyday

On 29 Oct 2018 14:19, drofdoom <notifications@github.com> wrote:

Hold power for 16 seconds .

**Comment by CTCaer** [comment]
Use the template already:
https://github.com/Atmosphere-NX/Atmosphere/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

(edit your first comment)
