### ISSUE TITLE
Is creport actually working?

### ISSUE THREAD

**Issue by marco-calautti** [Atmosphere-NX/Atmosphere#251]
### What's the issue you encountered?
Errors seem to be still logged to flash memory, even though creport is correctly placed in its titleid directory. Going to System settings -> Health and Safety -> Error History, I can see a 2144-0001 error recorded.

### How can the issue be reproduced?
My sd just contains the atmosphere directory structure with fusee-seconday.bin+BCT.INI in the root, exefs.nsp in atmosphere/titles/0100000000000036 and hbl.nsp+loader.ini in /atmosphere/.
What caused that error to occur was a mismatch between the path in loader.ini and hbl.nsp position in the sd, as I wanted to move it to another directory. Then, I moved it again to the right one. However, this should have not prevented creport from running.
### Crash report?

(If a crash report was created under /atmosphere/crash_reports/, please upload it to 
[gist](https://gist.github.com/) and paste the link here.)

No, this indeed the issue, crash reports don't seem to be created on the sd, rather on the internal memory.
### Environment?

- What bootloader (fusee, hekate, etc) was Atmosphère launched by:
Fusee-primary.bin
- Official release or unofficial build:
official 0.7.3 build.
- Do you have additional kips you're loading:
sys-ftp.kip only
- Additional info about your environment:
FW 6.0.1

### Additional context?
Since eclct is disabled by default, I believe this error has not been reported to Nintendo. Is there a way I can delete this report only, before going online without Atmosphere?

**Comment by yellows8** [comment]
creport is only for *crash* reports.

**Comment by marco-calautti** [comment]
> creport is only for _crash_ reports.

Right, so this does not count as a crash. As far as I remember, 2144-0001 is an error code relating to libnx. So does it mean that the real only way we have to prevent Nintendo finding out I am using homebrew software is via disabling eclct? Hence, I will never be able to boot my Switch without Atmosphere running?

**Comment by fincs** [comment]
It is not. libnx errors are 2345-xxxx

**Comment by marco-calautti** [comment]
> It is not. libnx errors are 2345-xxxx.
> As long as you have disabled 'Send error reports' under system settings you should be fine, even on stock.

Perfect, thanks for the clarification!

**Comment by The0919** [comment]
I also had a similar experience, but the error was 2345-0021 and it was a full system crash

**Comment by fincs** [comment]
That's LibnxError_BadGfxDequeueBuffer. Are you running an application compiled with very old libnx (1.3.x or earlier)? If so, then the application needs to be recompiled with latest libnx.

**Comment by SciresM** [comment]
Closing either way, since this isn't an ams issue.
