### ISSUE TITLE
fatle error

### ISSUE THREAD

**Issue by osbodav** [Atmosphere-NX/Atmosphere#257]
i am getting : [ERROR] Fatal error: [NXBOOT]: Key derivation failed!

my boot1/0 is corrupted so not sure if thats why, no i dont have a backup of it.

**Comment by fennectech** [comment]
If you can get into horizon a fw update should fix your boot0/1

**Comment by SciresM** [comment]
This isn't an atmosphere issue -- seek help on various discords.

**Comment by Khriskh** [comment]
I am testing and it shows me the following error
ERROR Fatal error : [SSMU] Failed to enable SMMU.

**Comment by SciresM** [comment]
already fixed in master.
