### ISSUE TITLE
[Request] set:sys mitm 

### ISSUE THREAD

**Issue by misson20000** [Atmosphere-NX/Atmosphere#268]
I've heard that on newer firmwares, the set:fd service for tweaking settings has been disabled. Even on firmwares where it is enabled, it doesn't let you set settings that don't exist but are queried (`am.debug!dev_function_enabled`), and it may be desirable to not actually commit settings changes to save data. It would be very nice to have an MITM that would read system setting overrides off the SD card. Useful for overriding things like `fatal!show_extra_info` or `am.debug!dev_function_enabled`

**Comment by SciresM** [comment]
Good idea.
