### ISSUE TITLE
Moonlighter error at launch

### ISSUE THREAD

**Issue by Zriel88** [Atmosphere-NX/Atmosphere#269]
### What's the issue you encountered?
Moonlighter game does not boot with atmosphere 0.7.5
### How can the issue be reproduced?
Install NSP from moonlighter and moonlighter update (v131072).
Launch game.
Switch will report there was a problem when launching the game
Afterwarsd it will report there is corrupt game data

### Crash report?
No crash

### Environment?
- What bootloader (fusee, hekate, etc) was Atmosphère launched by: hekate-ctaer 4.2
- Official release or unofficial build: 0.7.5 from SDFiles/Kosmos
- Do you have additional kips you're loading: None
- Additional info about your environment: FW 6.1.0 burned with ChoiDujour-NX

### Additional context?
Uploaded the issue here because the game is working correctly under ReinX. I don't really know if I'm breaking any rule here, just wanted to have the devs known of this issue (in case they are not aware of)

**Comment by Skonikol** [comment]
I can confirm that some users of version 075, running through hekate42, there is a problem with this game. After launching on consoles users AMS via fuse 1-2 game included correctly.

**Comment by misson20000** [comment]
Does it work if you buy the game

**Comment by hexkyz** [comment]
I've edited your original report solely to remove the allusion to sharing of pirated content. In the future, please refrain from adding such remarks.

Could you please take a picture of each error message displayed on the Switch?

**Comment by Zriel88** [comment]
Thanks for the heads up.
First try to run
https://imgur.com/EMVdHX8
Translates to 
"Couldn't launch the program
Try it again from the HOME menu"

And second try to run after that.
https://imgur.com/BTf8V7m

Translates to
"Damaged data has been found
It is recommended to use the function "Search for damaged data"
Cancel/ Search"

**Comment by tiliarou** [comment]
The switch OS found corrupted data. This looks like it's not atmosphere issue... You should ask on discord or open an issue on whatever CFW pack you use (anyway you shouldn't be able to install the game with stock atmo).

**Comment by Zriel88** [comment]
Ok, thanks for the info.
