### ISSUE TITLE
stratosphere: fs.mitm and set.mitm do not compile successfully

### ISSUE THREAD

**Issue by ThatNerdyPikachu** [Atmosphere-NX/Atmosphere#276]
### What's the issue you encountered?
fs.mitm and set.mitm do not compile successfully on the latest commit

### How can the issue be reproduced?
1. run ``make``
2. ???
3. profit

Build log: https://hastebin.com/uhisobuboy.rb

**Comment by SciresM** [comment]
Yes they do.
