### ISSUE TITLE
Failed to enable SMMU!

### ISSUE THREAD

**Issue by RaneyDay5** [Atmosphere-NX/Atmosphere#278]
## Bug Report
cant boot
### What's the issue you encountered?
whenever i inject the payload it errors with 
[ERROR] Fatal error: [SMMU]: Failed to enable SMMU!
### How can the issue be reproduced?
injecting the payload
### Crash report?

(If a crash report was created under /atmosphere/crash_reports/, please upload it to 
[gist](https://gist.github.com/) and paste the link here.)

### Environment?
Tried fusee and hekate 6.2, Atmosphère version 0.8 
- What bootloader (fusee, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: offical
- Do you have additional kips you're loading:
- Additional info about your environment:

**Comment by TheProvider0** [comment]
The patches found in the latest sdfiles atomsphere folder got me to boot after getting the same error. Just remember to drag the "exefs_patches" folder itself into "atmosphere." If that folder already exists, then delete it and replace it with this one.

**Comment by RaneyDay5** [comment]
i got it to work after several formats. Now none of my homebrew apps are showing up in the launcher

**Comment by TheProvider0** [comment]
That's another problem to open up, you can close this one since you managed to get it to boot, and remember to always try looking into the discussion thread: https://gbatemp.net/threads/atmosphere-0-8-released-6-2-0-working.524769/page-5#post-8405810

**Comment by RaneyDay5** [comment]
okay thanks!
