### ISSUE TITLE
NSP Install error 0x00234c02

### ISSUE THREAD

**Issue by vr6syncro** [Atmosphere-NX/Atmosphere#282]
### What's the issue you encountered?
NSP Install error 0x00234c02
### How can the issue be reproduced?
just install NSP
### Crash report?

(If a crash report was created under /atmosphere/crash_reports/, please upload it to 
[gist](https://gist.github.com/) and paste the link here.)

### Environment?

- What bootloader (fusee, hekate, etc) was Atmosphère launched by: fusee
- Official release or unofficial build: official
- Do you have additional kips you're loading: no
- Additional info about your environment: nothing special

**Comment by SciresM** [comment]
We do not provide support for warez installation.
