### ISSUE TITLE
Compile error 0.8.1

### ISSUE THREAD

**Issue by jamb84** [Atmosphere-NX/Atmosphere#283]
I receive the following errors when compiling. I've got the latest libnx, boost and devkitpro and I can't find the issue.

stratosphere/fatal/source/fatal_task_screen.hpp:27:9: error: 'NWindow' does not name a type
stratosphere/fatal/source/fatal_task_screen.hpp:28:9: error: 'Framebuffer' does not name a type; did you mean 'setbuffer'?

**Comment by SciresM** [comment]
Building ams right now is kind of jank. There's no single branch you can use. Shoot me a DM on discord if you want help building it.

**Comment by marceloneil** [comment]
I fixed this exact error by using the source version of libnx, seems like NWindow and Framebuffer are new additions.
