### ISSUE TITLE
problems again with smmu failed to enable

### ISSUE THREAD

**Issue by pkeios** [Atmosphere-NX/Atmosphere#285]
i injected de new atmosphere 0.8.1 and this work ok the first time but when started to up in sd i had a problems and appeared a massage i needed to restarted the switch and try again. i put again the files in the sd but this time when i try to inject again throw failed to enable smmu

**Comment by SciresM** [comment]
This will happen spuriously if not launched via cold-boot. It is guaranteed to never happen twice in a row.
