### ISSUE TITLE
Compilation error with Fatal

### ISSUE THREAD

**Issue by jlozes** [Atmosphere-NX/Atmosphere#286]
### What's the issue you encountered?

The compilation of the Fatal module fail.

### How can the issue be reproduced?

Clone the repository with all submodules and try to make.

### Crash report?

make -C fatal all
make[2]: Entering directory '/f/0/a/Atmosphere/stratosphere/fatal'
fatal_task_screen.cpp
aarch64-none-elf-g++ -MMD -MP -MF /f/0/a/Atmosphere/stratosphere/fatal/build/fatal_task_screen.d -g -Wall -O2 -ffunction-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE -DDISABLE_IPC -DATMOSPHERE_GIT_BRANCH=\"master\" -DATMOSPHERE_GIT_REV=\"master-bd76e73-dirty\" -I/f/0/a/Atmosphere/stratosphere/fatal/include -I/f/0/a/Atmosphere/stratosphere/fatal/../../common/include -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I/f/0/a/Atmosphere/stratosphere/fatal/../libstratosphere/include -I/f/0/a/Atmosphere/stratosphere/fatal/build -D__SWITCH__ `freetype-config --cflags` -fno-rtti -fno-exceptions -std=gnu++17 -c /f/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp -o fatal_task_screen.o 
In file included from F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:21:
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.hpp:27:9: error: 'NWindow' does not name a type
         NWindow win;
         ^~~~~~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.hpp:28:9: error: 'Framebuffer' does not name a type; did you mean 'setbuffer'?
         Framebuffer fb;
         ^~~~~~~~~~~
         setbuffer
In file included from C:/devkitPro/libnx/include/switch.h:13,
                 from F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:17:
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp: In member function 'Result ShowFatalTask::SetupDisplayInternal()':
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:60:57: error: 'ViPowerState_On' was not declared in this scope
     if (R_FAILED((rc = viSetDisplayPowerState(&display, ViPowerState_On)))) {
                                                         ^~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:60:24: error: 'viSetDisplayPowerState' was not declared in this scope
     if (R_FAILED((rc = viSetDisplayPowerState(&display, ViPowerState_On)))) {
                        ^~~~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:60:24: note: suggested alternative: 'viGetDisplayResolution'
     if (R_FAILED((rc = viSetDisplayPowerState(&display, ViPowerState_On)))) {
                        ^~~~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:65:24: error: 'viSetDisplayAlpha' was not declared in this scope
     if (R_FAILED((rc = viSetDisplayAlpha(&display, 1.0f)))) {
                        ^~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:65:24: note: suggested alternative: 'viOpenDisplay'
     if (R_FAILED((rc = viSetDisplayAlpha(&display, 1.0f)))) {
                        ^~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp: In member function 'Result ShowFatalTask::SetupDisplayExternal()':
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:87:24: error: 'viSetDisplayAlpha' was not declared in this scope
     if (R_FAILED((rc = viSetDisplayAlpha(&display, 1.0f)))) {
                        ^~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:87:24: note: suggested alternative: 'viOpenDisplay'
     if (R_FAILED((rc = viSetDisplayAlpha(&display, 1.0f)))) {
                        ^~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp: In member function 'Result ShowFatalTask::PrepareScreenForDrawing()':
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:103:5: error: 'viSetContentVisibility' was not declared in this scope
     viSetContentVisibility(false);
     ^~~~~~~~~~~~~~~~~~~~~~
In file included from C:/devkitPro/libnx/include/switch.h:13,
                 from F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:17:
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:117:24: error: 'viGetDisplayLogicalResolution' was not declared in this scope
     if (R_FAILED((rc = viGetDisplayLogicalResolution(&this->display, &display_width, &display_height)))) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:117:24: note: suggested alternative: 'viGetDisplayResolution'
     if (R_FAILED((rc = viGetDisplayLogicalResolution(&this->display, &display_width, &display_height)))) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:120:24: error: 'viSetDisplayMagnification' was not declared in this scope
     if (R_FAILED((rc = viSetDisplayMagnification(&this->display, 0, 0, display_width, display_height)))) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:120:24: note: suggested alternative: 'viGetDisplayResolution'
     if (R_FAILED((rc = viSetDisplayMagnification(&this->display, 0, 0, display_width, display_height)))) {
                        ^~~~~~~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:143:28: error: 'viSetLayerSize' was not declared in this scope
         if (R_FAILED((rc = viSetLayerSize(&this->layer, layer_width, layer_height)))) {
                            ^~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:143:28: note: suggested alternative: 'svcSetHeapSize'
         if (R_FAILED((rc = viSetLayerSize(&this->layer, layer_width, layer_height)))) {
                            ^~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:149:31: error: 'viGetDisplayMaximumZ' was not declared in this scope
         if (R_SUCCEEDED((rc = viGetDisplayMaximumZ(&this->display, &layer_z)))) {
                               ^~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:10:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)==0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:149:31: note: suggested alternative: 'viGetDisplayResolution'
         if (R_SUCCEEDED((rc = viGetDisplayMaximumZ(&this->display, &layer_z)))) {
                               ^~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:10:30: note: in definition of macro 'R_SUCCEEDED'
 #define R_SUCCEEDED(res)   ((res)==0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:150:32: error: 'viSetLayerZ' was not declared in this scope
             if (R_FAILED((rc = viSetLayerZ(&this->layer, layer_z)))) {
                                ^~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:150:32: note: suggested alternative: 'viCreateLayer'
             if (R_FAILED((rc = viSetLayerZ(&this->layer, layer_z)))) {
                                ^~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:156:28: error: 'viSetLayerPosition' was not declared in this scope
         if (R_FAILED((rc = viSetLayerPosition(&this->layer, layer_x, layer_y)))) {
                            ^~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:156:28: note: suggested alternative: 'viSetLayerScalingMode'
         if (R_FAILED((rc = viSetLayerPosition(&this->layer, layer_x, layer_y)))) {
                            ^~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:161:57: error: 'class ShowFatalTask' has no member named 'win'
         if (R_FAILED(rc = nwindowCreateFromLayer(&this->win, &this->layer))) {
                                                         ^~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:161:27: error: 'nwindowCreateFromLayer' was not declared in this scope
         if (R_FAILED(rc = nwindowCreateFromLayer(&this->win, &this->layer))) {
                           ^~~~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:161:27: note: suggested alternative: 'viCreateLayer'
         if (R_FAILED(rc = nwindowCreateFromLayer(&this->win, &this->layer))) {
                           ^~~~~~~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:164:52: error: 'class ShowFatalTask' has no member named 'fb'
         if (R_FAILED(rc = framebufferCreate(&this->fb, &this->win, raw_width, raw_height, PIXEL_FORMAT_RGB_565, 1))) {
                                                    ^~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:164:63: error: 'class ShowFatalTask' has no member named 'win'
         if (R_FAILED(rc = framebufferCreate(&this->fb, &this->win, raw_width, raw_height, PIXEL_FORMAT_RGB_565, 1))) {
                                                               ^~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:164:27: error: 'framebufferCreate' was not declared in this scope
         if (R_FAILED(rc = framebufferCreate(&this->fb, &this->win, raw_width, raw_height, PIXEL_FORMAT_RGB_565, 1))) {
                           ^~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:164:27: note: suggested alternative: 'nvBufferCreate'
         if (R_FAILED(rc = framebufferCreate(&this->fb, &this->win, raw_width, raw_height, PIXEL_FORMAT_RGB_565, 1))) {
                           ^~~~~~~~~~~~~~~~~
C:/devkitPro/libnx/include/switch/result.h:12:30: note: in definition of macro 'R_FAILED'
 #define R_FAILED(res)      ((res)!=0)
                              ^~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp: In member function 'Result ShowFatalTask::ShowFatal()':
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:183:70: error: 'class ShowFatalTask' has no member named 'fb'
     u16 *tiled_buf = reinterpret_cast<u16 *>(framebufferBegin(&this->fb, NULL));
                                                                      ^~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:183:46: error: 'framebufferBegin' was not declared in this scope
     u16 *tiled_buf = reinterpret_cast<u16 *>(framebufferBegin(&this->fb, NULL));
                                              ^~~~~~~~~~~~~~~~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:193:34: error: 'class ShowFatalTask' has no member named 'fb'
     for (size_t i = 0; i < this->fb.fb_size / sizeof(*tiled_buf); i++) {
                                  ^~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:401:21: error: 'fb' was not declared in this scope
     framebufferEnd(&fb);
                     ^~
F:/0/a/Atmosphere/stratosphere/fatal/source/fatal_task_screen.cpp:401:5: error: 'framebufferEnd' was not declared in this scope
     framebufferEnd(&fb);
     ^~~~~~~~~~~~~~
make[3]: *** [/opt/devkitpro/devkitA64/base_rules:14: fatal_task_screen.o] Error 1
make[2]: *** [Makefile:125: build] Error 2
make[2]: Leaving directory '/f/0/a/Atmosphere/stratosphere/fatal'
make[1]: *** [Makefile:12: fatal] Error 2
make[1]: Leaving directory '/f/0/a/Atmosphere/stratosphere'
make: *** [Makefile:18: stratosphere] Error 2

### Environment?

Windows 7 X64, last version of Devkitpro and LibNX. I also have others Switch libraries of the Devkit repository.

### Additional informations?

Compilation of Atmosphere worked before Fatal implementation.

I know that it's not realy an Atmosphere bug but I can't use Discord to report this, the last version seems to bug with my screen reader.

Thanks.

**Comment by tiliarou** [comment]
https://github.com/Atmosphere-NX/Atmosphere/issues/283

You can use discord from a web browser. Ask Ave or SciresM.
