### ISSUE TITLE
[6.2.0] Atmosphere can't boot, crashes after (Nintendo) logo.

### ISSUE THREAD

**Issue by GiovanH** [Atmosphere-NX/Atmosphere#288]
Edit: The problem turned out to be mismatched ExFat firmware. Using a FAT32 card fixed the issue and allows you to install ExFat firmware properly. This is unrelated to firmware 6.2.0.

### What's the issue you encountered?

Atmosphere can't boot on 6.2.0.

Sequence of events:
1. I load the 0.8.1 atmosphere primary payload via fusee
2. Atmosphere gives the friendly message and then loads fusee-secondary.bin
3. Fusee-secondary gives log information that it is beginning NXBoot and rebuilding package 2
4. Fusee-secondary shows several patched kips, as it normally would during a successful boot.
5. The Nintendo logo fades in and out, as it would normally during a successful boot
6. The Switch logo never loads. 
7. At this point, if connected to the computer, the computer loses connection to the switch, indicating some change in power state.

### How can the issue be reproduced?

Issue occurs consistently on my console.

### Crash report?

(If a crash report was created under /atmosphere/crash_reports/, please upload it to 
[gist](https://gist.github.com/) and paste the link here.)

Unfortunately, no crash reports were generated.

### Environment?

- What bootloader (fusee, hekate, etc) was Atmosphère launched by:
Originally loaded the atmosphere chainloader (fusee-primary) via Hekate, but injecting the fusee-primary.bin had the same result. 
- Official release or unofficial build:
Running files from official build 0.8.1
- Do you have additional kips you're loading:
Originally loaded with SysFTPD, disabling sysftpd (moved to different folder) had no effect.
I first ran it with a theme as a LayeredFS patch, but deleting the theme had no effect.
- Additional info about your environment:
Upgraded from 6.1.0 to 6.2.0 using ChoiDejour.

The following environment produced the result:
- Smashed the fusee-primary bin directly via fusee
- SD card with no custom sysmodules or menu themes

### Additional context?

Upgraded from 6.1.0 (with 6.2.0 fuses) to 6.2.0 using ChoiDejour.
**Stock firmware boots correctly.**

Filesystem:

```
$ tree atmosphere
atmosphere
├── exefs_patches
│   └── Signature Patches by Rajkosto
│       ├── 7135C20E752183914606CCE81293F24B738C3AEF.ips
│       ├── 76935CA6235CA150D790D4DDF09CA3488AEF50D8.ips
│       ├── A6E7D98BD335371E1B9A96F6241EA3E83B0C36F4.ips
│       ├── C0BFC6518707AC975295A0B656A051DA885A9045.ips
│       ├── CBF2D40A2210C4EE1137F80098DB776EAC7DDCC1.ips
│       ├── E581B1898637E5BC40DBC4AB8F0C6324447E05D1.ips
│       ├── F86D615F9FC6F0D16C3458BE58C64594DBDAB0DF.ips
│       └── F92CFF283777465AFBCC6E160C10EFE7AADC4D3C.ips
├── hbl.nsp
├── kip_patches
│   └── default_nogc
│       ├── 02D5ABAAFD20C8B0633AA0DBAEE0377EF526CE6AD2AC6F2CAD7180CE69E74311.ips
│       ├── 06E90719595A010C6246FF70946F10FB367A00BBD8B7D8D1F25CCE0B458D7E89.ips
│       ├── 10B2D81605488599DF2242CB6BAC2DF1E2BCAB3BC19DC5CD63DB6FAEC0947097.ips
│       ├── 330553F6B5FB55C4C2D7B736240276B3EAD664DA79826FA936F99803B6C28F3B.ips
│       ├── 3A574D436186191D1788EB2C0F076B11737132EBB1484CF906B6A8EB3B1BF459.ips
│       ├── 549B0F8D6F72C4E9F3FD1F19EACE4A5A1DA2D5C393F74224F8BC09DE4AAA4217.ips
│       ├── 76F87402C9387C0F0A2FAB1B45CEBB93E3E9695C7CFD390F00509B1204101C24.ips
│       ├── 8096AF7C6A35AA8271F3916995413B0B64CE03BD9BBFEB26F2B3E01C5427C69E.ips
│       ├── A6F27AD9AC7C73AD419B63B23E785A0CD7AA9DC1A63C57D10049423DE7B77E2C.ips
│       └── CE3ECBA2F2F062F575F8F360842B32B432340DD2C7590CDEFC03E51B844AE805.ips
├── kip_patches_disabled
│   ├── ftpd
│   │   └── C1D296651CEDCA2D549D5FD41DE2B45B25080D08A54D8E080FB8A85729F46B40.kip
│   └── sysnetcheat
│       └── sys-netcheat.kip
├── loader.ini
└── prod.keys
```

```
$ ls -s .
total 8064
   0  atmosphere           1536  hbmenu.nro        128  README.txt
   0  backup                  0  JKSV                0  ReiNX
 128  BCT.ini               128  keys.bin          128  ReiNX.bin
 128  biskeydump.bin        128  keys.txt            0  retroarch
   0  bootloader              0  lakka               0  switch
   0  config                  0  modules             0 'System Volume Information'
 128  device.keys             0  Nintendo            0  tinfoil
   0  EdiZon                128  prod.keys           0  uboot
   0  Firm                    0  pypatches         128  ums_boot0.ini
   0  FOUND.000               0  RajNX             128  ums_boot1.ini
   0  FOUND.001             128  rajnx_ipl.bin     128  ums_emmc.ini
   0  ftpd                  128  rajnx_ipl.ini     128  ums_sd.ini
4608  fusee-secondary.bin   128  rawpfso.zerotwo
```
(There are some old ReiNX files, but they are not being used and should not be affecting anything, as far as I'm aware.)

**Comment by GiovanH** [comment]
Update: This is not exactly true. If left alone for a *long* time (~10 minutes), the switch will occasionally show the Switch logo, boot for another few minutes, and then crash with 2162-0002.

**Comment by ZachyCatGames** [comment]
Did you have an exfat card and if so did you install the exfat version of 6.2.0

**Comment by GiovanH** [comment]
> This sounds to me like the SD card is failing to mount. Future versions of AMS will have [bbed781](https://github.com/Atmosphere-NX/Atmosphere/commit/bbed78149c7a176a3687dc081f6a34063a603f8e), which will make it take less time to get to the sad state you're in.
> 
> But, yeah, format your SD card as FAT32, or else manually install exFAT firm by fucking with NAND. I'd say use choidujournx, but in order for HBL to load the SD card needs to be readable, which isn't the case.

This was exactly the case. I was able to boot into full atmosphere by using a second SD card with a bare minimum homebrew setup, and from there installed 6.2.0 ExFat with ChoiDejourNX.

Hopefully others who have this problem will see this and be able fix it quickly. Also, apparently atmosphere loads between the Nintendo logo and the switch logo, so that'll be handy to know for future debugging.

Please mark as resolved.

**Comment by AbdullahAl-Hajjar** [comment]
Just update hekate to the latest version don't delete the bootloader folder rather replace it or you will lose your content in the menu page. if it still doesn't work add the latest patches this should work.
I know this is a bit late however I had the same issue and haven't figure it out till recently.
