### ISSUE TITLE
LayeredFS incorrect functionality on override_key=R on subsequent game loads

### ISSUE THREAD

**Issue by fullmetal1** [Atmosphere-NX/Atmosphere#292]
### What's the issue you encountered?
With loader.ini has override_key=R (override contents only on R press), and I try to load a game with layeredFS content, it works correctly the first time, but in any subsequent attempts, it will fail, and the game will be loaded with no overridden content. 

### How can the issue be reproduced?
Play any game with any mod with override_key=R and try to load the game with R, confirm layeredFS content loads, close the game, reopen the game, and confirm layeredFS content no longer loads (I used BotW and the Linkle title menu mod as it was quickest to confirm)
### Crash report?
N/A
(If a crash report was created under /atmosphere/crash_reports/, please upload it to 
[gist](https://gist.github.com/) and paste the link here.)

### Environment?
Atmosphere 0.8.1 (Kosmos 11.1 pre-release, but has been this way at least since 11)
- What bootloader (fusee, hekate, etc) was Atmosphère launched by: fusee-launcher hekate-ctcaer_4.2.bin
- Official release or unofficial build: Whichever Kosmos is.
- Do you have additional kips you're loading: FTPd
- Additional info about your environment: N/A

### Additional context?
N/A

**Comment by SciresM** [comment]
@fullmetal1 Does the error occur when loading with fusee? I doubt it changes anything, but please check.

**Comment by SciresM** [comment]
@fullmetal1 Can you come on discord to test? I think I have an idea about how to potentially fix.

**Comment by kmarsh92** [comment]
Also suffering same issue with same game and same mod for testing.  only difference is fw 6.2 and using kosmos 11.5 pack and hekate to load the kips and cfw not fusee-primary.

**Comment by theedward1** [comment]
Same problem here, with BOTW it's easily reproducible.

**Comment by fullmetal1** [comment]
@SciresM I'm L A I N『レインを好きになりましょう！』#9784
