### ISSUE TITLE
Partition mount error with fatal

### ISSUE THREAD

**Issue by jjbNX** [Atmosphere-NX/Atmosphere#294]
### What's the issue you encountered?

During boot via RCM (using Fusee) the following fatal error is encountered:
[ERROR] Fatal error: Failed to mount at least one partition: Invalid argument

### How can the issue be reproduced?

Boot via RCM using Fusee, on a device with a 64GB emmc, on 6.2.0-1 FW.

### Crash report?

Fusee does not generate crash reports.

### Environment?

- What bootloader (fusee, hekate, etc) was Atmosphère launched by:
Fusee
- Official release or unofficial build:
Official 0.8.1
- Do you have additional kips you're loading:
N/A
- Additional info about your environment:
Using TegraRCMSmash, 128GB Sandisk microsd. 
HAT-002

**Comment by SciresM** [comment]
Dev hardware not supported, can't really be supported until I have my hands on a unit.
