### ISSUE TITLE
"failed to decrypt package 2 header (master key revision 4)"

### ISSUE THREAD

**Issue by tobelele** [Atmosphere-NX/Atmosphere#297]
### What's the issue you encountered?
Can't boot atmosphere, "failed to decrypt package 2 header (master key revision 4)"
### How can the issue be reproduced?
Everytime I try to boot atmosphere.
### Environment?
Used both fusee and hekate, same error. Used the official release. No additional kips.

**Comment by Ginnung** [comment]
All I could do to fix this problem is to restore the original nand from backup and do the whole process first using foil and so on.
