### ISSUE TITLE
Spoof airplane mode for games like minecraft

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#298]
### What feature are you suggesting?
I would like the ability to have HOS tell games like minecraft that airplane mode is on because it will suppress this message when starting a game that try’s to connect to Nintendo network on startup.  

![image](https://user-images.githubusercontent.com/11953665/50047374-4890c200-0079-11e9-8984-c1a46eb03952.jpg)

**Comment by SciresM** [comment]
Just use airplane mode...?
