### ISSUE TITLE
Unable to boot the HB

### ISSUE THREAD

**Issue by Ackons** [Atmosphere-NX/Atmosphere#300]
### What's the issue you encountered?
When I inject the payload, it continues to stage 2 but there is no "Done" message. It cuts out while loading kips. It just cuts to the nintendo logos and when I open the album it opens the normal album.
### How can the issue be reproduced?
Inject the payload with an ns-atmosphere injector or tegrarcm
### Crash report?

(If a crash report was created under /atmosphere/crash_reports/, please upload it to 
[gist](https://gist.github.com/) and paste the link here.)

My atmosphere folder doesn't have a crash_reports folder in it

### Environment?

- What bootloader (fusee, hekate, etc) was Atmosphère launched by: I assume this is the payload used (fusee-primary.bin)
- Official release or unofficial build: 0.8.2
- Do you have additional kips you're loading: Not that I know of
- Additional info about your environment: Switch 6.2.0

### Additional context?

I can provide you my SDfiles if you wish to see if anything is wrong via a google drive link (I don't know if there's any sensitive info in there for whatever reason so I don't want to post it publicly, only to the dev if he requests)

**Comment by Oreo639** [comment]
Sounds like you are missing some files. This isn't a support forum, this is a bug tracker. I would recommend checking out the Nintendo Homebrew discord and make sure that this is an issue with Atmosphere and not the files on your sd card. (check to make sure you have both hbl.nsp in the /atmosphere folder and that you have hbloader.nro on the root of your sd card)
