### ISSUE TITLE
Update sm extension docs

### ISSUE THREAD

**Issue by misson20000** [Atmosphere-NX/Atmosphere#303]
There have been a few changes to Atmosphere's sm-extensions that have not yet been documented.

- [ ] Removal of smhax
- [ ] `sm:m` commands

**Comment by misson20000** [comment]
`sm:m` extensions are still undocumented

**Comment by SciresM** [comment]
Yeah, those are commands explicitly for Atmosphere's PM (and no other process).

I don't think there's much to gain from bothering to write blurbs on them, but I'd accept a PR.
