### ISSUE TITLE
failed to mount

### ISSUE THREAD

**Issue by JhonJhonny** [Atmosphere-NX/Atmosphere#315]
What's the issue you encountered?
During boot via RCM (using RCMsmash with fuse primary.bin) the following fatal error is encountered:
[ERROR] uSD: Failed to send if cond!
[ERROR] Fatal error: Failed to mount at least one partition: I/O error

How can the issue be reproduced?
Boot via RCM using RCMsmash with fuse primary.bin, , on 4.1.0 FW.

Official release or unofficial build:
Official 0.8.2
Do you have additional kips you're loading:
N/A
Additional info about your environment:
, 128GB Samsung microsd.(sdxc) tried in fat32 and exfat (installed the drivers manually)

**Comment by SciresM** [comment]
Seems like SD card/IO problems, not fusee problem...
