### ISSUE TITLE
creport can give misleading result codes on 5.0.0+ (2000-000)

### ISSUE THREAD

**Issue by misson20000** [Atmosphere-NX/Atmosphere#320]
### What's the issue you encountered?

On 5.0.0+, nintendo sdk puts an `nn::Result*` in the break address for svcBreak and creport reads the result stored within back out. Unfortunately, the default value for this result code is 0, which makes for a confusing error screen.

![Crash log](https://cdn.discordapp.com/attachments/269333940928512010/518629875058343936/image1.jpg)
(image stolen from Adubbz)

### How can the issue be reproduced?

Cause an official SDK app to abort without an error code.

### Crash report?

https://gist.github.com/misson20000/3527d3f21672f40b440b561571b290a0

### Environment?

- What bootloader (fusee, hekate, etc) was Atmosphère launched by: fusee
- Official release or unofficial build: built from latest master
- Do you have additional kips you're loading: [twili](https://github.com/misson20000/twili)
- Additional info about your environment: firmware version 6.1.0 (should be reproducible on any 5.0.0+)

**Comment by SciresM** [comment]
Talked to misson on discord, sounds like it's due to creport/nnSdk behavior -- should occur for Nintendo crash reports, too. I proposed a workaround (only use the user break result if it is non-zero), will commit once it's verified to fix the problem.
