### ISSUE TITLE
Request: Open HB Menu when any title is started while pressing "R"

### ISSUE THREAD

**Issue by DavidOliM** [Atmosphere-NX/Atmosphere#325]
### What feature are you suggesting?
Open Homebrew Menu when you start any installed title while pressing "R"
### Why would this feature be useful?
I think it would be easier and faster than editing the loader.ini when you want to replace a selected title with HB Menu to have no RAM limitations. It could be optional and maybe replace the current behavior of opening the Title itself when R is pressed.

**Comment by SciresM** [comment]
Already supported thanks to a PR a few days ago.
