### ISSUE TITLE
Boot issues/HBL launch problems

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#327]
### What's the issue you encountered?

People have observed issues launching HBL (2347-0009), and issues booting AMS on certain firmwares.

### How can the issue be reproduced?

Unclear! TBD.

### Crash Report

Mostly not relevant.

### System Firmware Version

Again, not really relevant.

### Environment?

This has been observed using completely stock AMS.

**Comment by thedax** [comment]
Unable to reproduce with 6.2.0, ams 0.8.3, hbloader 2.1, and hbmenu 3.0.1. It's really curious that it seems to mainly happen with 5.1, based on reports in RS..

**Comment by SciresM** [comment]
fixed.
