### ISSUE TITLE
Wii and Wii U Controller Support (Mainly Wii Classic Controller Pro support instead of Switch Pro Controller)

### ISSUE THREAD

**Issue by switchItLikeItsHot** [Atmosphere-NX/Atmosphere#340]
#### Overview:
- Let's support Wii and Wii U Controllers via Bluetooth firstly without working motion control. </br>

#### Smaller Details: 
- It should be possible to play all Switch games that you can play with a GameCube Controller, also with a Wii Remote and Nunchuk or with a Wii Classic Controller that is attached to a Wii Remote. </br>
- Wii Balance Board support and other "specials" are not needed. </br>

#### Nature of Request:  
- Addition
  - Make it possible to "switch" the button mapping of a GameCube-Controller so you can play Donkey Kong Country: Tropical Freeze like on a Classic Controller. Running with B instead of X and jumping with A instead of B. The standard button layout of GameCube-Controllers are not very useful for Jump'n'run Games like Donkey Kong.

### What component do you feel this would best fit within?
- Stratosphère(https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>
- **Troposphère**(https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?
With this feature all of our dozens of controllers from the Wii and Wii U era would be working on the switch. So on parties with a lot of people it's easier to get enough controllers to work. It's also much cheaper to reuse the controllers that you already bought, instead of buying new controllers to each new console. </br>

**Comment by tumGER** [comment]
This was asked before already. 
The simple answer is that this is way too advanced and takes too much time for what it is worth and Atmosphere is not at the stage where it can focus on such optional features.

**Comment by SciresM** [comment]
I think if I did something this frivolous before emunand the people following this project would lynch me.

Ask another developer, or else poke me about it in a year or two.

**Comment by Swiftloke** [comment]
For what it's worth, the [GBros](http://www.8bitdo.com/gbros/) adapter already does exactly what you're asking for (excluding Wii U Pro Controllers, which do not send data over their Mini-USB ports).

**Comment by switchItLikeItsHot** [comment]
Oh thank you very much! That's a very good alternative.
