### ISSUE TITLE
creport hangs system.

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#341]
### What's the issue you encountered?
The console hangs when launching cities skylines with modern creport.  however when downgrading to the creport included with 0.7.4 the hang vanishes and i get a "the software was closed because an error occored" 

Launching various games including "cities skylines" where this hang occors
[ Did you make any changes related to Atmosphère itself? ]</br>
no

### How can the issue be reproduced?
Launch cities skylines with current update
open cities skylines with current version of creport.
### Crash Report
crash report was generated with creport 1.1
https://pastebin.com/2WcGcPTH

### System Firmware Version

6.2.0</br>
### Environment?
standard kosmos with FTPD 
- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
Hekate 
- Official release or unofficial build: 
Unofficial build:Kosmos
Kosmos V11.9

- Do you have additional kips or sysmodules you're loading:
FTPD
- Homebrew software installed: [ * ]

### Additional context?
When using the older version (1.1) of creport the hang does not occor   but when using 1.2 of creport it hangs forcing a reboot.
- Additional info about your environment:

**Comment by thedax** [comment]
>standard kosmos with FTPD

Does the issue persist with the latest official release (i.e. https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.8.3)?

**Comment by fennectech** [comment]
Yes.

**Comment by fennectech** [comment]
Have i done that right?

**Comment by thecogdoctor** [comment]
> 
> 
> Have i done that right?

In the majority yes.

>Launching various games including "cities skylines" where this hang occors
>no

Please include the context to the why you said no. It is present within the issue template but it's nonsense without context

> (https://gist.github.com/) and pasting the link here. ]
>
>]
...

Cheers.

**Comment by fennectech** [comment]
I’m not sure why i said no. But i removed it.

**Comment by fennectech** [comment]
But the issue seems to be fixed for now.  Ill reopen if i come across it again
