### ISSUE TITLE
Fatal error: [NXBOOT] Failed to detect target firmware!

### ISSUE THREAD

**Issue by edmoncu** [Atmosphere-NX/Atmosphere#342]
Fatal error: [NXBOOT] Failed to detect target firmware!

This is the message that appears when i boot into Atmosphere.
My Switch is using FW 7.0.0

**Comment by aveao** [comment]
Atmosphere doesn't support 7.0.0 (on non-BYOD) yet.

**Comment by imPRAGMA** [comment]
Im actually having this occur on v6.2.0 o.O (Latest Atmosphere Used)
