### ISSUE TITLE
Can't boot Horizon OS with CFW

### ISSUE THREAD

**Issue by niko1point0** [Atmosphere-NX/Atmosphere#345]
Hi. I am trying to boot CFW on Nintendo Switch for the first time. I got Atmosphere 0.83, I sent the payload to switch, I saw the Atmosphere Logo, then the Nintendo Logo, and then only a black screen eternally. Can you help me? Firmware 5.1.0, Switch was built in 2017

**Comment by pixel-stuck** [comment]
what files are on your SD card?

**Comment by niko1point0** [comment]
I figured it out. The SD card was not formatted as FAT32
