### ISSUE TITLE
Fix microSD formatting

### ISSUE THREAD

**Issue by Agusyc** [Atmosphere-NX/Atmosphere#347]
Attempted to format my microSD from Settings while using the latest version of Atmosphere, and now my Switch is totally bricked. It won't turn on at all, not even into RCM. I'm sure it's not just frozen on a black screen because my PC won't recognise it as an USB device and I tried force turning it off by holding the power button down for as long as 45 seconds.

**Comment by fennectech** [comment]
Sorry mate.  This looks like hardware issue.    Has nothing to do with atmosphere or scared formatting.      If it was a brick you could still boot into RCM.   Try taking your switch apart and disconnecting the battery.
