### ISSUE TITLE
/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/source/firmware_version.cpp:129:19: error: 'MAKEHOSVERSION' was not declared in this scope

### ISSUE THREAD

**Issue by sandhoners123** [Atmosphere-NX/Atmosphere#353]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?
/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/source/firmware_version.cpp:129:19: error: 'MAKEHOSVERSION' was not declared in this scope

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>
I tried to add common/include/boost to INCLUDE in libstratosphere
### How can the issue be reproduced?
By building in Fedora Rawhide
[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>
Just run make and you will see it (you need to first do the submodule checkout)
### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>
This is a gcc issue
make -C thermosphere all
make[1]: Entering directory '/home/sandlahonerla/Atmosphere/thermosphere'
make[2]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/sandlahonerla/Atmosphere/thermosphere'
make -C exosphere all
make[1]: Entering directory '/home/sandlahonerla/Atmosphere/exosphere'
make[2]: Entering directory '/home/sandlahonerla/Atmosphere/exosphere/sc7fw'
make[3]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/sandlahonerla/Atmosphere/exosphere/sc7fw'
make[2]: Entering directory '/home/sandlahonerla/Atmosphere/exosphere/lp0fw'
make[3]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/sandlahonerla/Atmosphere/exosphere/lp0fw'
make[2]: Entering directory '/home/sandlahonerla/Atmosphere/exosphere/rebootstub'
make[3]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/sandlahonerla/Atmosphere/exosphere/rebootstub'
make[2]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/sandlahonerla/Atmosphere/exosphere'
make -C stratosphere all
make[1]: Entering directory '/home/sandlahonerla/Atmosphere/stratosphere'
make -C libstratosphere all
make[2]: Entering directory '/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere'
firmware_version.cpp
aarch64-none-elf-g++ -MMD -MP -MF /home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/release/firmware_version.d -g -Wall -O2 -ffunction-sections -march=armv8-a -mtune=cortex-a57 -mtp=soft -fPIE  -I/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/include -I/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/../../common/include -I/opt/devkitpro/portlibs/switch/include -I/opt/devkitpro/libnx/include -I. -iquote /home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/include/switch/ -D__SWITCH__ -I../../common/include -fno-rtti -fno-exceptions -std=gnu++17 -I../../common/include -c /home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/source/firmware_version.cpp -o firmware_version.o 
/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/source/firmware_version.cpp: In function 'void SetFirmwareVersionForLibnx()':
/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/source/firmware_version.cpp:129:19: error: 'MAKEHOSVERSION' was not declared in this scope
     hosversionSet(MAKEHOSVERSION(major, minor, micro));
                   ^~~~~~~~~~~~~~
/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere/source/firmware_version.cpp:129:5: error: 'hosversionSet' was not declared in this scope
     hosversionSet(MAKEHOSVERSION(major, minor, micro));
     ^~~~~~~~~~~~~
make[3]: *** [/opt/devkitpro/devkitA64/base_rules:14: firmware_version.o] Error 1
make[2]: *** [Makefile:100: lib/libstratosphere.a] Error 2
make[2]: Leaving directory '/home/sandlahonerla/Atmosphere/stratosphere/libstratosphere'
make[1]: *** [Makefile:10: libstratosphere] Error 2
make[1]: Leaving directory '/home/sandlahonerla/Atmosphere/stratosphere'
make: *** [Makefile:20: stratosphere] Error 2

### System Firmware Version
7.0.0
X.X.X</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Offical release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
Attempt of Self compilation
### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
update libnx
