### ISSUE TITLE
Open power menu via sleep button/icon

### ISSUE THREAD

**Issue by Strat00s** [Atmosphere-NX/Atmosphere#358]
#### Overview:
Kinda self-explanatory. When clicking the sleep button/icon on home screen, instead of opening the annoying dialog if I really want to sleep the console, simply open the power menu.

### Why would this feature be useful?
A faster way of shutting down the console. Instead of holding the power button for 5 seconds, just click the sleep button/icon and chose power off.
Also very useful to shut down the console when it is docked. You can click power off right from your couch.

**Comment by misson20000** [comment]
You mean the buttons on the home menu and overlay menus, not the actual physical button on the console, right?

Sounds to me like it might be a little out of scope for ams, but I like the idea.

**Comment by Strat00s** [comment]
> You mean the buttons on the home menu and overlay menus, not the actual physical button on the console, right?
> 
> Sounds to me like it might be a little out of scope for ams, but I like the idea.

Exactly. I should have said sleep icon. The button or whatever on the home screen.

**Comment by james-d-elliott** [comment]
I don't know why Nintendo didn't do this themselves, rather annoying having to hold the power button to restart. I think it'd be rather useful for restarting into hekate for removal of microSD for example.

**Comment by fennectech** [comment]
Or restarting when connected to TV

**Comment by SciresM** [comment]
Yeah, this is a little out of scope due to it involving actual code changes to system applets.
