### ISSUE TITLE
ERROR FATAL ERROR : FAILED TO STAT STAGE2 (ATMOSPHERE/FUSEE-SECONDARY.BIN)!

### ISSUE THREAD

**Issue by omarrimawi** [Atmosphere-NX/Atmosphere#360]
We would like to use GitHub to keep track of problems/feature requests.  
If you have a question, please join the ReSwitched discord for help. 
- Discord link: https://discordapp.com/invite/DThbZ7z

**Comment by SciresM** [comment]
Please use the correct issue template.

Also sounds like sd card corruption.

**Comment by omarrimawi** [comment]
SORRY I AM NEW HERE , SHALL I REFORMAT MY SD CARD ? AND IN WHICH FORMAT TYPE ?

**Comment by DavidBuchanan314** [comment]
There is a key to the left of the "A" key on your keyboard labelled "CapsLock", please press it once before continuing.

**Comment by darkpickles** [comment]
I have the same problem:-(

**Comment by aveao** [comment]
Extract the zip properly.

**Comment by cristianmiranda** [comment]
@omarrimawi @darkpickles Maybe too late, but better late than never 😄 

The problem should be the SD card format. If you're using FAT32 as I'm doing, check the scheme to be **FDisk_partition_scheme** and not **GUID_partition_scheme**

* _Green:_ correct
* _Red:_ wrong

![Screen Shot 2019-08-20 at 14 37 31](https://user-images.githubusercontent.com/972572/63370322-514c3d00-c358-11e9-91f7-6671cd08d0c2.png)

Those are two 128GB cards with different format. If you're using macOS you can use the following command:

`sudo diskutil eraseDisk FAT32 SWITCH MBRFormat /dev/disk3`

(replace /dev/disk3 with your SD, you can check it with `sudo diskutil list`)

Hope it helps! 🙏

**Comment by Conan179** [comment]
You are saying, switch donst load a fat32 from a gpt fort. SD card?

**Comment by SciresM** [comment]
Please don't necro issues that have been resolved for half a year; it's bad etiquette.
