### ISSUE TITLE
can't boot into CFW with 0.8.4

### ISSUE THREAD

**Issue by BaZZtian** [Atmosphere-NX/Atmosphere#361]
### How can the issue be reproduced?

Everytime i load the 0.8.4 the Error shows up

### Crash Report

https://gist.github.com/BaZZtian/1965ea2bcffefaee426a815e53031ca5

### System Firmware Version

6.2.0

**Comment by BaZZtian** [comment]
nvm delete latest titel folder on SD fixed it ...

**Comment by BaZZtian** [comment]
#close

**Comment by powmaya** [comment]
Weren't you the one who was always playing, datamining and leaking Omega Ruby (and other Pokemon games) on 3ds ahead of release? If that's not piracy I'm not sure what is friend. 

Glass houses and all that.

https://projectpokemon.org/index/news/ultra-sun-and-ultra-moon-datamining-r66/
http://227.149.197.104.bc.googleusercontent.com/2016/11/08/pokemon-sun-and-moon-is-leaked-datamined/

**Comment by bakugo** [comment]
@powmaya what exactly does this have to do with the issue submitted?

**Comment by powmaya** [comment]
I posted it on the wrong one, thanks github.
