### ISSUE TITLE
Missing file from release

### ISSUE THREAD

**Issue by Lorenzooone** [Atmosphere-NX/Atmosphere#362]
hbl.nsp is not present in the latest release, so if a user has to wipe out their previous atmosphere folder, they won't be able to open the homebrew menu.

**Comment by DavidBuchanan314** [comment]
hbl is not a component of Atmosphere.

**Comment by Lorenzooone** [comment]
Atmosphere refers to it though in the config files...

**Comment by thedax** [comment]
Get it from https://github.com/switchbrew/nx-hbloader/releases , it's intentionally not distributed with atmosphere.

**Comment by SciresM** [comment]
Yeah, not actually an issue.

**Comment by SciresM** [comment]
Also, you can just drag/drop the folder in zip onto SD, it should normally work fine without explicit delete.
