### ISSUE TITLE
Homebrew 

### ISSUE THREAD

**Issue by SaviorZeus** [Atmosphere-NX/Atmosphere#364]
EveryTime i open homebrew and click on Lockpick to dump my keys it crashes all the time idk why 

error code :2168-0002(0x4a8)
Title :0100000000001D
Firmware:7.0.1 (Atmosphere 0.8.4- master-37161c5d)

**Comment by ZachyCatGames** [comment]
lockpick doesn't work on 7.0.x

**Comment by SciresM** [comment]
Lockpick bugs are not Atmosphere bugs, also this doesn't use the issue template.
