### ISSUE TITLE
Can I load reinx.bin through sept

### ISSUE THREAD

**Issue by sandhoners123** [Atmosphere-NX/Atmosphere#366]
i was banned from the reswitched discord so I can’t post there. Can sept load Reinx.bin and where do I place it

**Comment by fennectech** [comment]
If your putting it in /sept/payload.bin that’s not what sept is for.   That isn’t loaded like a Hecate payload so no.  You cannot use that to load a cfw.

**Comment by sandhoners123** [comment]
Then can sept print out the derived keys

**Comment by fennectech** [comment]
That I don’t know.    Sorry.

**Comment by sandhoners123** [comment]
Is there a way to have sept load reinx

**Comment by SciresM** [comment]
ReiNX needs to add support for being loaded by sept.

**Comment by SciresM** [comment]
Also @fennectech is wrong.

**Comment by fennectech** [comment]
i am?  my apoligies.
