### ISSUE TITLE
HDCP seems broken ( connected screen goes blank when opening hdcp enabled app)

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#368]
### What's the issue you encountered?

[ When opening youtube the screen goes blank and returns after going to home menu]</br>
[ no ]</br>
[ NA ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ 1. Simply open youtube app and screen goes blank. ]</br>

### Crash Report

[NA ]</br>

### System Firmware Version

7.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
fusee-primary.bin chainloaded with hekate.
- Official release or unofficial build: 
  - [ Official 0.8.4 ]
- Do you have additional kips or sysmodules you're loading:
SysFTPD
sys-clk 
- Homebrew software installed: [ Sys-clk applied to home menu but not the application.  This did not occor before 0.8.4 and 7.0.1 ]

### Additional context?

- Additional info about your environment:
- [ The issue only occored when i updated atmosphere  all settings and things previously existing with sys-clk and sys-ftpd worked fine in atmosphere 0.8.3]
 I hope i have done the thingy right this time.

**Comment by SciresM** [comment]
Have you verified the issue occurs on stock 0.8.4 release without additional modules? Please always verify that.

**Comment by fennectech** [comment]
I have just confirmed it happens on stock 0.8.4.

**Comment by SciresM** [comment]
Does the issue occur in handheld mode, or only when docked?

**Comment by SciresM** [comment]
Similarly: does the issue occur on 0.8.4 and downgraded-to-6.1.0?

**Comment by fennectech** [comment]
Only in docked mode.  I’d rather not downgrade. Sorry.    Can you reproduce it on your end?

**Comment by SciresM** [comment]
I do not own a television (by choice), and so cannot test anything involving docked mode.

My development switch also has a banned certificate, so I can't really download youtube...

**Comment by SciresM** [comment]
(Sorry, meant to hit "comment", not "close and comment")

**Comment by fennectech** [comment]
There is a modded YouTube that patches out the need for Nintendo network.

**Comment by SciresM** [comment]
That does not solve the fact that I do not have a way of obtaining youtube, as I can't connect to the eshop.

**Comment by fennectech** [comment]
Iirc its an NSP.

**Comment by SciresM** [comment]
Atmosphere doesn't have signature patches, and I can't/don't provide support for warez.

**Comment by fennectech** [comment]
Ill ask about for somebody to test :)

**Comment by SciresM** [comment]
Could you also verify whether issue is specific to 7.0.1, or also affects 7.0.0?

**Comment by fennectech** [comment]
Will do.

**Comment by nebulakl** [comment]
Can confirm 7.0.0 is not affected.

**Comment by fincs** [comment]
Cannot reproduce. My console is on 7.0.1 & docked & running AMS 0.8.4 without any extra kips or any other modifications. YouTube app works and I can play videos.

**Comment by WinterMute** [comment]
Can't reproduce here either. 7.0.1 with ams 0.8.4, no kips or other mods, booted using latest fusee-primary via cortex M4 based dongle

**Comment by fennectech** [comment]
Can comfirm 6.2.0 is not affected   (had some users try on discord.

**Comment by fennectech** [comment]
Hmm  on 7.0.1 bone stock booted from tegrarcmgui  it flashes the HDMI icon a bunch of times (like its revebing signal and then not receving it) then eventualy starts working after a few minutes.   This is wierder.  Perhaps its my TV?  But everything worked before.

**Comment by SciresM** [comment]
Sounds like a hardware problem.

**Comment by fennectech** [comment]
ill downgrade
