### ISSUE TITLE
CANT INSTALL NSP!!!!! on new fw 7.0

### ISSUE THREAD

**Issue by Nefith** [Atmosphere-NX/Atmosphere#372]
error when try to install nsps....

**Comment by maciak** [comment]
You need new patches. Not available in AMS.

**Comment by fincs** [comment]
No piracy supported here

**Comment by gjimenezf** [comment]
Even with ES and FS patches it is still not possible to install any nsp files: 
https://github.com/XorTroll/Goldleaf/issues/235#issuecomment-466674546

**Comment by ZachyCatGames** [comment]
> Even with ES and FS patches it is still not possible to install any nsp files:
> [XorTroll/Goldleaf#235 (comment)](https://github.com/XorTroll/Goldleaf/issues/235#issuecomment-466674546)

Atmosphere doesn't support warez

**Comment by gjimenezf** [comment]
It doesn't install Retroarch.nsp, Goldleaf.nsp they are not warez...

**Comment by ZachyCatGames** [comment]
> It doesn't install Retroarch.nsp, Goldleaf.nsp they are not warez...

I read your previous message incorrectly

**Comment by fincs** [comment]
Homebrew is distributed in NRO format (launchable with nx-hbloader + nx-hbmenu), not "NSP". Locking this issue.
