### ISSUE TITLE
Crash on lauching HBL with Album menu

### ISSUE THREAD

**Issue by OniriCorpe** [Atmosphere-NX/Atmosphere#373]
### What's the issue you encountered?

When I lauch the HBL with the Album menu, the console crash

I tried with the default "switch" folder, same crash

### How can the issue be reproduced?

- Start the Sitch with Fusée Gelée and Atmosphère 0.8.4
- Click on the Album menu
- Crash

### Crash Report

https://gist.github.com/OniriCorpe/fdc55d94dbdd74a0edde0b5623c746ca

### System Firmware Version

7.0.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusee
- Official release or unofficial build: Offical
  - Offical release version 0.8.4
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: None

### Additional context?

- Additional info about your environment: None 

![photo_2019-02-23_01-49-29](https://user-images.githubusercontent.com/6963387/53278988-4730e500-370d-11e9-9e6b-201bb79446be.jpg)

**Comment by yellows8** [comment]
Delete the *100D directory under the atmo titles/ directory.
