### ISSUE TITLE
Atmosphere 0.8.4 won't boot

### ISSUE THREAD

**Issue by Kalos90** [Atmosphere-NX/Atmosphere#374]
A couple of weeks ago I​ accidentally upgraded to firmware 7.0.0 via choidujour; now that Atmosphere 0.8.4 is out, I put it on my SD root, but it still won't boot. The Atmosphere logo is displayed, then nothing happens and the screen goes black. I have already tried using a fat 32 SD card with no results 

​

**Comment by SciresM** [comment]
Please use issue template.
