### ISSUE TITLE
Feature request: Block Nintendo servers

### ISSUE THREAD

**Issue by gjimenezf** [Atmosphere-NX/Atmosphere#377]
Please integrate an option to block Nintendo servers to avoid ban as SX OS does.
90 DNS does not works for me.

**Comment by leo60228** [comment]
@DavidBuchanan314 is working on this, but I don't think it will be included in Atmosphère.

**Comment by designgears** [comment]
There is already a great solution for this, would be nice to see something integrated tho.
https://gbatemp.net/threads/incognito.531924/

**Comment by designgears** [comment]
Why was that deleted?

**Comment by fennectech** [comment]
People dont trust blarwar

**Comment by fincs** [comment]
Please do not link to closed source tools produced by people of questionable reputation.

**Comment by fennectech** [comment]
i would like to see it possable to disable specific domains as I’ve been disabling only the telemetry domains allowing me to ‘safely’ play online. (Have done it for over a year without a ban)

**Comment by designgears** [comment]
> People dont trust blawar

People don't like him, I haven't seen him post anything malicious outside of a naming dispute and some other silly drama. But Ok.

**Comment by fennectech** [comment]
It wasn’t a dispute.  He basically stole the name tinfoil from an existing project.
