### ISSUE TITLE
Atmosphere 0.8.4 seems to boot but no HB menu

### ISSUE THREAD

**Issue by YellowLemon571** [Atmosphere-NX/Atmosphere#386]
Bug Report

What's the issue you encountered?

I recently updated to 7.0.1 and accordingly installed Atmosphere 0.8.4. It seems to boot fine, but the homebrew menu doesn't load when going to albums.

How can the issue be reproduced?

I deleted everything on the SD card except for the "Nintendo" folder, and freshly installed Atmosphere 0.8.4.

Crash Report

N/A

System Firmware Version

7.0.1

Environment?

fusèe, the payload included with Atmosphere 0.8.4.
No homebrew software installed.

Additional context?

N/A

**Comment by SciresM** [comment]
Use Atmosphere 0.8.5, which is bundled with HBL. Previous releases were not bundled.
