### ISSUE TITLE
setsys_firmware_version.cpp compiler warnings

### ISSUE THREAD

**Issue by urherenow** [Atmosphere-NX/Atmosphere#388]
## Bug Report

Compiler warnings for setsys_firmware_version.cpp

### What's the issue you encountered?

home/urherenow/projects/Atmosphere/stratosphere/ams_mitm/source/set_mitm/setsys_firmware_version.cpp:40:64: warning: ' (AMS ' directive output may be truncated writing 6 bytes into a region of size between 1 and 24 [-Wformat-truncation=]
 intf(display_version, sizeof(display_version), "%s (AMS %u.%u.%u)", g_fw_version.display_version, major, minor, micro);
                                                ^~~~~~~~~~~~~~~~~~~

/home/urherenow/projects/Atmosphere/stratosphere/ams_mitm/source/set_mitm/setsys_firmware_version.cpp:40:64: note: directive argument in the range [0, 255]
/home/urherenow/projects/Atmosphere/stratosphere/ams_mitm/source/set_mitm/setsys_firmware_version.cpp:40:64: note: directive argument in the range [0, 255]
/home/urherenow/projects/Atmosphere/stratosphere/ams_mitm/source/set_mitm/setsys_firmware_version.cpp:40:64: note: directive argument in the range [0, 255]
/home/urherenow/projects/Atmosphere/stratosphere/ams_mitm/source/set_mitm/setsys_firmware_version.cpp:40:21: note: 'snprintf' output between 13 and 42 bytes into a destination of size 24
             snprintf(display_version, sizeof(display_version), "%s (AMS %u.%u.%u)", g_fw_version.display_version, major, minor, micro);
             ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
bpcmitm_main.cpp


### How can the issue be reproduced?
clone current source and compile with latest devkit tools installed.

### Crash Report

N/A

### System Firmware Version

N/A

### Environment?

Self-compilation with latest devkit tools and libraries

### Additional context?

Ubuntu in a VMWare VM

**Comment by SciresM** [comment]
Not a bug -- the truncation is the desired result in the case that the string is too long.

Per snprintf: "If the resulting string would be longer than n-1 characters, the remaining characters are discarded and not stored".
