### ISSUE TITLE
Implement warmboot support in Exosphere

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#4]
Step one of re-implementing TrustZone will just be getting the CPU state up and running after a wakeup.

**Comment by SciresM** [comment]
I think when I made this issue, I meant for it to represent coldboot. That's worked for months, but the only feature left before exosphere is complete is making warmboot work.

**Comment by YihaoMa** [comment]
will it support all firms?

**Comment by SciresM** [comment]
Yes.

**Comment by YihaoMa** [comment]
Thx for your work.

**Comment by SciresM** [comment]
With latest commits, warmboot works on at least 5.x. Needs testing on other fw, but :)

**Comment by SciresM** [comment]
Will close following verification/debugging.

**Comment by SciresM** [comment]
:)
