### ISSUE TITLE
overwrite multiple titles with hbl

### ISSUE THREAD

**Issue by justinjustin7** [Atmosphere-NX/Atmosphere#458]
#### Overview:
- Allow multiple titles to be used to launch hbl.

#### Smaller Details: 
- Use loader.ini to specify multiple titles to be used for launching hbl.

#### Nature of Request:  
- Change

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>

### Why would this feature be useful?
This will allow for use of the new cheat engine through overwriting a system title while still benefiting from the increased memory of overwriting a game title. May also open the possibility of using the cheat engine with homebrew?

**Comment by bottmint** [comment]
As an immediate solution, make a copy of your hbl.nsp, put it in `atmosphere/titles/010000000000100D` and rename it to `exefs.nsp` to have hbmenu on the album applet, and use loader.ini to overwrite a game title.

**Comment by justinjustin7** [comment]
Nice, that works. It still would be good to have a more straightforward way of doing it through the ini though.

**Comment by Crissal1995** [comment]
In atmosphere/loader.ini change title_id to "app", and every game will instead boot hbl with the combination you use

**Comment by bottmint** [comment]
I believe what @justinjustin7 is wanting is to be able to define a game title to overwrite _in addition to_ being able to define and applet to overwrite in the loader.ini, unless I'm mistaken.

**Comment by SciresM** [comment]
The use case that wants this should be totally resolved by 9e1e9ff8.
