### ISSUE TITLE
Games install on atmosphere 0.8.0 won't run on atmosphere 0.8.4 or 0.8.5

### ISSUE THREAD

**Issue by Lassall** [Atmosphere-NX/Atmosphere#480]
Error message: corrupted data
Examples: Super Smash Bros Ultimate and Mario Party

**Comment by fincs** [comment]
> Games install

Are these eShop downloads? If so, then try popping in a fresh new SD card & redownloading the games from your eShop list of purchases.

**Comment by Lassall** [comment]
> 
> 
> > Games install
> 
> Are these eShop downloads? If so, then try popping in a fresh new SD card & redownloading the games from your eShop list of purchases.

I think they all are. But only the two mentioned games won't work. The other games are running fine.

**Comment by fincs** [comment]
Still, I think it would be good if you tried a clean install of those games fresh from the eShop, to rule out SD card corruption.

**Comment by Lassall** [comment]
At first, thank you for your support! I'll try that. What constellation/combination would you recommend?
I have firmware version 6.2.0. Will that work stable with AMS 0.8.5 and which TinFoil/Goldleaf version should I use?

**Comment by profi200** [comment]
Atmosphere or it's devs don't support piracy.

**Comment by Lassall** [comment]
> 
> 
> Atmosphere or it's devs don't support piracy.

Who said anything about piracy, I didn't ask for games or download links?! I'm new to the scene and really don't know what tools I need to run my game backups from SD-card. Sadly theres not only one knowledgebase where everything is properly described. I'll make one myself if I know enough.There are plenty of tools and versions.  The scene is like "Here you go with our new whatever version, teach yourself what you can do with it".

**Comment by Daniel0Wellby** [comment]
Atmosphere's devs don't support piracy, at all
