### ISSUE TITLE
sort the home menu items

### ISSUE THREAD

**Issue by toxic9** [Atmosphere-NX/Atmosphere#492]
will it be possible to implement a way to sort the home menu items?
It's so boring not to have an official way to do that.
No alphabetical order, no custom order... just a stupid order that keeps changing when you click an item.
I hope you will bring this in the future for the homebrew comunity!
an many thanks for you work.

**Comment by hippydave** [comment]
Patches to qlaunch (home menu) might be in the scope of Troposphère, but you've also got people working on custom qlaunch replacements, so that might come sooner.

**Comment by misson20000** [comment]
I think you can reorder them with ns commands? Would probably be pretty easy to keep them from being reordered after that.

**Comment by SciresM** [comment]
The order is "most recently accessed, in any way".

Anyway this sounds more like an organizational homebrew thing than an ams thing, for now.
