### ISSUE TITLE
Replace Support (or any other option) with Atmosphere configuration

### ISSUE THREAD

**Issue by Strat00s** [Atmosphere-NX/Atmosphere#507]
## Feature Request
Atmosphere configurator in System Settings.
#### Overview:
I have no idea how feasable/doable this is. I just love how it works with PS Vita and Henkaku.
"Simply" replace the "Support" option (or any other) in "System Settings" with some sort of Atmosphere configurator (just how Hekate replaces "System Update" on PS vita)

#### Smaller Details: 
- Is it actually possible?
- Is it possible to change and apply the atmo config on the go?

#### Nature of Request:  
Whenever new feature is introduced, which has to be enabled by user I become to lazy to do it or easily forget about some...

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)
or/and
- [**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
Not really sure...

### Why would this feature be useful?
User firendly, easy Atmosphere configuration.
There aren't many options yet, but I am sure that how atmo grows. the list of features that can be enabled would grow as well.

**Comment by SciresM** [comment]
Not really feasible due to level of invasive modification of qlaunch this requires, for now.

Re-open when atmosphere has things to configure/when qlaunch is more readily modifiable, in that way? Not opposed in the future.
