### ISSUE TITLE
Unable to boot recovery/maintenance mode on 7.0.1 & AMS 0.8.4 through 0.8.7

### ISSUE THREAD

**Issue by thedax** [Atmosphere-NX/Atmosphere#511]
### What's the issue you encountered?

Trying to boot into maintenance/recovery mode results in the console hanging on the Switch (Joycon + Nintendo Switch) logo. Issue persists with both Hekate and Fusee-primary. Issue does not persist if Hekate is told to boot semi-stock (i.e. using only exosphere & lp0fw as required).

### How can the issue be reproduced?

Send fusee-primary or hekate and observe that maintenance mode will not boot (while holding the appropriate volume buttons).

### Crash Report

N/A

### System Firmware Version

7.0.1

### Environment?

Bootloaders: Hekate (via FSS0) & Fusee-primary (as in, f-p launched on its own, not chainloaded)
Self built: Yes
Tested with official releases: Yes
(Persists with both self-built and official releases)
4GB FAT32 SD card
64GB FAT32 SD card

Tested official releases from 0.8.4 through 0.8.7 and it persists through all 4

Additional sysmodules: sys-clk and sys-ftpd, but the issue persists even with them removed

Homebrew installed: N/A

Console has been updated through system settings while under atmosphere ever since it became safe to do so.

**Comment by Krude** [comment]
Just tried it myself (AMS 0.8.7, FW 7.0.1) and can confirm, it hangs on the Nintendo Switch logo.

**Comment by SciresM** [comment]
Resolved.

**Comment by thedax** [comment]
Thank you!
