### ISSUE TITLE
Typo in 0.8.8 changelog

### ISSUE THREAD

**Issue by M1CR0H4CK3R** [Atmosphere-NX/Atmosphere#514]
At the end of the changelog for 0.8.8, it says: "For information on the featureset supported by 0.8.**0**, please see the official release notes.". The link that comprises the text "the official release notes" also leads to a page with the 0.8.0 tag. Oopsies.

**Comment by shchmue** [comment]
That's always included to document the broader featureset in the major rev

**Comment by HookedBehemoth** [comment]
Not a typo

**Comment by SciresM** [comment]
Not a typo
