### ISSUE TITLE
OFW 8.0 Homebrew running, but game wont start

### ISSUE THREAD

**Issue by lajax01** [Atmosphere-NX/Atmosphere#515]
OFW 8.0, with latest Atmosphere.
Boot up just fine.
 Homebrew running. I can install games, but in main no games start up.
Give me a various errors like, corrupted data, download again, etc.. 
What is missing?
(Still using lockpick generated keys from 7.0.1)

**Comment by ZachyCatGames** [comment]
All of my legitimately purchased physical and digital games work without any issues 🤔

**Comment by lajax01** [comment]
Point taken, but fck yourself. ;)
My legit titles wont start under latest atmosphere, only if I start a console in factory state.
In sort: no legit or pirate content wont start, only hb apps under album.

**Comment by fincs** [comment]
> Homebrew running. I can install games, but in main no games start up.

> My legit titles wont start under latest atmosphere, only if I start a console in factory state.

???

**Comment by lajax01** [comment]
Seriously? I cant say more about this issue.
Only hb apps works, nothing else.

**Comment by DankanTsar** [comment]
Your pirate patches are a bit faulty. I think this is not a problem of atmosphere.

**Comment by lajax01** [comment]
Any suggestions? 
I want play a particular game.. :/
Kip and sigpaches are fully working on Atmosphere on fw 8.0?

**Comment by SciresM** [comment]
we don't support warez.
