### ISSUE TITLE
Atmosphere 0.8.8 Crash upon startup

### ISSUE THREAD

**Issue by Austin70000** [Atmosphere-NX/Atmosphere#516]
## Bug Report

Atmosphere crashes at Nintendo Switch logo upon injecting Fusee Primary. Had just updated atmosphere on Switch SD for FW 8.0.0

Updated/changed CFW and payload
Can be reproduced upon every startup

![20190421_122816](https://user-images.githubusercontent.com/49841011/56472792-17fad380-6431-11e9-90c1-6ada638f56c5.jpg)

### Crash Report

Crash screen attached.
### System Firmware Version

8.0.0</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by masagrator** [comment]
Do you have maybe custom theme?

**Comment by sorenbug** [comment]
This is most likely due to a custom theme. Delete any `01000000000010xx` folders under `/atmosphere/titles/`, then open NXThemes Installer and uninstall + reinstall your themes. Make sure to say "yes" when it asks you about re-dumping the home menu files.

**Comment by Austin70000** [comment]
Thank you! Closing issue.
