### ISSUE TITLE
Fatal auto reboot after countdown

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#518]
#### Overview:
Simple auto reboot timer in fatal.

#### Smaller Details: 
 allow fatal to automaticly reboot 
also for those who want to use the information a fatal providing  a "norebootonfatal.flag" in the atmosphere directory or specify it via config
#### Nature of Request:  
- Change

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>

### Why would this feature be useful?
It would allow users of docked switches not to have to get up to reboot a fataled switch.

**Comment by HookedBehemoth** [comment]
[ Lines between [ ] (square brackets) are to be removed before posting. ]

**Comment by fennectech** [comment]
That better?

**Comment by HookedBehemoth** [comment]
Yes

**Comment by SciresM** [comment]
I don't see why this would be desirable. Hit a button...?

**Comment by fennectech** [comment]
if the console is docked and im sitting back on the couch i'd rather wait a timeout than get up to hit the power button

**Comment by SciresM** [comment]
Implement yourself, make it not the default, and use the setting "atmosphere!fatal_auto_reboot_interval", expressed in milliseconds.

I will accept your PR.

**Comment by fennectech** [comment]
This aint bash      ill see if i can make it but i doubt i will be able to.
