### ISSUE TITLE
NRO Patches don't work properly with FF X/X-2

### ISSUE THREAD

**Issue by masagrator** [Atmosphere-NX/Atmosphere#522]
### What's the issue you encountered?
    I'm trying to apply NRO patches for Final Fantasy X/X-2.
    I've used sips for IPS32 patches and Lunar IPS for IPS patches.
    
    For IPS32 patches I got different results:
    1st and 2nd NRO are crashing with 0xC8A error.
    3rd NRO is glitched.
    
    For IPS patches:
    1rd NRO is glitched
    3rd is crashing with 0x4A8 error
    2nd is not possible without IPS32.
### How can the issue be reproduced?
    One of examples:
    Download FF X/X-2 game, edit romfs\nro\SideStory.nro
    offset: 0x002D22A0
    change
    21 D8 17 91 42 06 80 52
    to
    21 08 17 91 82 06 80 52
    
    Made patch with Lunar IPS,
    name it as
    01FEE8A3289603061B8B40850E99B039.ips
    
    It will change video from US to Asia
    It's working with files in layeredfs with properly modified .nrr, but not as patch.

### Crash Report
    Crash from applying NRO patch for SideStory.nro
    https://gist.github.com/masagrator/f7d3637384bc25a66dae7950170933e2

### System Firmware Version
    7.0.1

### Environment?
- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
    fusee
- Official release or unofficial build: 
    unofficial build
    > BuildServNX (bsnx.lavatech.top)
- Do you have additional kips or sysmodules you're loading:
    no
- Homebrew software installed: 
    Nothing that is modifying how system works. RetroArch, Goldleaf, nxmtp, etc.

### Additional context?
    Only that this patches are applied to NRO that is launched from other NRO. Maybe this makes some issues.

**Comment by SciresM** [comment]
Fixed by 83136697168dfabf1f36725fbbf5e08c46b9231e.
