### ISSUE TITLE
AutoRCM protection seems to be broken on 4.x/5.x when updating through System Settings

### ISSUE THREAD

**Issue by thedax** [Atmosphere-NX/Atmosphere#523]
### What's the issue you encountered?

Updating to 8.0.1 through system settings while on 4.x or 5.x crashes the console with title ID
010000000000001f, error code 0x25A0B (2011-0301)

### How can the issue be reproduced?

1. Format the console (whether it's through system settings/maintenance or by using hacdiskmount to wipe all the saves except for `120` on the SYSTEM partition)
2. Go through the initial setup
3. Try to update the console through system settings while Atmosphere is running
4. Observe how it crashes just before the reboot
5. Rebooting to fusee from `fatal` will then take you to stock (i.e. AMS does not show up next to the system version, and trying to launch the hbl will not work, indicating stock), and autoRCM will have been wiped.

### Crash Report

5.1.0 https://gist.github.com/thedax/3b730e14ceb2ebbf2944393680e852d9
4.1.0 https://gist.github.com/thedax/9328fc78255245ca70428393e2b80d53
### System Firmware Version

4.1.0 / 5.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Both Hekate & Fusee-primary (not chainloaded)
- Official release or unofficial build: Official 0.8.8
- Do you have additional kips or sysmodules you're loading: None
- Homebrew software installed: N/A

### Additional context?

- Additional info about your environment:
64GB SD card formatted to FAT32, 64k clusters/allocation unit size

**Comment by SciresM** [comment]
Fixed by libstrat commits.
