### ISSUE TITLE
Unable to access HBMenu with Switch Joycon when a Pro Controller is connected

### ISSUE THREAD

**Issue by eXhumer** [Atmosphere-NX/Atmosphere#524]
### What's the issue you encountered?

Unable to access HBMenu with Switch Joycon when a Pro Controller is connected, instead shows Album.

### How can the issue be reproduced?

Connect a secondary controller to Switch. While R+Album is pressed on the joycons, it opens album. But it shows HBMenu normally if you use the Pro Controller to access.

### Crash Report

N/A (No file/folder under /atmosphere with crash_report.)

### System Firmware Version

8.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
Chainloaded Atmosphere v0.8.8 fusee-primary.bin using CTCaer Hekate v4.10.1.
- Official release or unofficial build:  Official Release Atmosphere v0.8.8
- Do you have additional kips or sysmodules you're loading: sys-ftpd
- Homebrew software installed: Stock that comes with Atmosphere

### Additional context?

- Additional info about your environment: N/A (Feel free to ask any more info if needed)

**Comment by SciresM** [comment]
Atmosphere uses P1_CONTROLLER_AUTO for key detection -- you just need to change the order of your controllers, I think.
