### ISSUE TITLE
How do i install Senran Kagura Feet fetish dlc?

### ISSUE THREAD

**Issue by Reiisgei77** [Atmosphere-NX/Atmosphere#525]
hi first of all dont judge me and also im using the latest version of atmosphere and i own a japanese cart of Senran Kagura but i dont know how could i get this dlc

**Comment by ZachyCatGames** [comment]
> hi first of all dont judge me and also im using the latest version of atmosphere and i own a japanese cart of Senran Kagura but i dont know how could i get this dlc

open the eshop —> buy the dlc —> download the dlc 

also this isn’t an atmosphere issue :P

**Comment by Reiisgei77** [comment]
yea but im using an european account

**Comment by ZachyCatGames** [comment]
> yea but im using an european account

You can add a japanese account to your system and use that :P 

still not an atmosphere issue though

**Comment by Reiisgei77** [comment]
**Hi to my friends at reswitched and hi to my bruddas at reiswitched**

**Comment by fincs** [comment]
Closed due to off-topic.

**Comment by Reiisgei77** [comment]
:feelsbad:

**Comment by jamescallen246** [comment]
You will need a Japanese account
