### ISSUE TITLE
Atmosphere crashes when closing a title.

### ISSUE THREAD

**Issue by HaveSumFaith** [Atmosphere-NX/Atmosphere#529]
My situation:
New titles require the latest system to play, so i had to upgrade using choijur from 6.0 to 7.0 ( previously i had my system downgraded to 6.0 because my little brother updated it to 7.1 but it was working fine for months) So i have upgraded to 7.0 yesterday, and i have this weird issue: atmosphere crashes every time i close a game. No matter which game.  I have tried all 3 of the "pre configured bundles" at sdsetup. (kosmos defaults, reinx defaults and "minimal") Reinx is unusable, its incredibly buggy and unstable, kosmos with atmosphere is crashing, and the minimal package is holding out a little better, but it starts to act up after some time too.

Not sure what could be the problem, with the pre-configured package i got the sig patches as well...

Also, i have tried different payloads too, but it don't make a difference.
![D48iUuIW4AA0YII](https://user-images.githubusercontent.com/50000255/56772995-58888300-678a-11e9-9bac-b682ea79fa49.jpg)

**Comment by TuxSH** [comment]
Did you try latest Atomsphère release? (properly setting it up, *without* sdfiles)? https://github.com/Atmosphere-NX/Atmosphere/releases

**Comment by TuxSH** [comment]
> Reinx
>  sig patches as well...

We don't support warez.

**Comment by HaveSumFaith** [comment]
@TuxSH OMG once of the programming wizards replied to my post :O But Yes sir, i did. Deleted everything except my nintendo folder. See, i have over 100gb of games on my nintendo folder, if i delete it im gonna have to spend a whole day reinstalling and moving them back :(

**Comment by HaveSumFaith** [comment]
Mr.Wizard, please don't close it :( I need help.

**Comment by fincs** [comment]
Piracy or warez is *not* supported by Atmosphère. "Your" over 100gb of games, plus the fact that you have used warez oriented distributions of Atmosphère (including signature check patches) is a giveaway of the fact that they are all pirated.

**Comment by TuxSH** [comment]
If you have bought the games you can redownload them (assuming you're not on a metered connection).

In fact you do not need to touch the Nintendo folder at all.

**Comment by fennectech** [comment]
Redownloading on a /fast/ connection over a hundred gigs of games takes
24h+.  All of that time most games cannot be played as that will stop
downloads.
-- 
FennecTECH

**Comment by TuxSH** [comment]
With the ethernet stuff capped at 50MB/s (which is a speed you can easily get with proper optical fiber) this just takes a good night.

Also don't tell me you need to play all 100 in the same day :).

**Comment by HaveSumFaith** [comment]
Okay. I didn't know you guys don't support the ol " take what ya can and don't give it back" philosophy, but i'm genuinely need some help. As i said, the "minimal" package from sdsetup works best, and it doesnt freeze when i close a game (during a fresh install) but after a couple hours, it freezes just like the other packages.

**Comment by DavidBuchanan314** [comment]
Did you even try the first troubleshooting step that the "programming wizard" told you to try?

If you haven't replicated the issue with a vanilla, up-to-date atmosphere install, I'm not sure what you're doing here.

**Comment by HaveSumFaith** [comment]
@DavidBuchanan314 Not sure what you mean? He suggested me to try the latest build, which as a human with a brain, was my first thought. Of course i tried it man, it was the first package.

**Comment by fincs** [comment]
Locking due to the warning that piracy is not supported being repeatedly ignored.
