### ISSUE TITLE
Use built-in controller HOME button light

### ISSUE THREAD

**Issue by cucholix** [Atmosphere-NX/Atmosphere#530]
## Feature Request
Cosmetic fun request, the right Joy Con, and Switch Pro Controller have a built-in light blue ring in the HOME button, it seems Nintendo have them for some use in the future but they are sitting there in both controllers. When connected to PC and using them as Steam controller the light turns on.

It could be cool to have an option to turn on/off this light upon Switch boot.

### Why would this feature be useful?
It could be implemented in homebrew stuff, for example when there's no screen output the light blinking could be indicate a game/app loading, or in case of homebrew apps that doesn't have screen overlay (emuibo, sys-clk, freebird) there's no means to know if the hacks/new settings are being applied to the Switch game, it could be helpful as light could act as a cue.

@yellows8 mentioned there's a command available in 7.0.0+ https://github.com/switchbrew/libnx/issues/240

**Comment by SciresM** [comment]
This isn't something for atmosphere to do -- see #350. I'm not really thinking I want ams to be making LEDs light up on controllers.
