### ISSUE TITLE
Crash when i launch game and it's running, i try to open album then crash all system

### ISSUE THREAD

**Issue by serpinu** [Atmosphere-NX/Atmosphere#535]
### What's the issue you encountered?

The Problem is that when i launch a game and i try to open album then crash all.</br>
[ Did you make any changes related to Atmosphère itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?

[ * ]</br>
N/A</br>

### Crash Report

![20190507_212130](https://user-images.githubusercontent.com/35550620/57327976-7651d280-7110-11e9-9485-4d59ec3ffcd5.jpg)

### System Firmware Version

8.0.1</br>

### Environment?
Official release version 0.8.9 of atmposhere
 
- Homebrew software installed: Edizon, Freebird, Tinfoil, HBG, Checkpoint, Choidujournx, Goldleaf, ftpd, nx-shell, hb app store, lockpick, melonDS, mGBA

**Comment by austin5623** [comment]
Uh, you were supposed to edit the template, not just copy and paste it.

**Comment by serpinu** [comment]
ok thanks

**Comment by SciresM** [comment]
you probably have too many sysmodules or something -- that's LibnxError_InitFail_AM. But this also does not sound like an atmosphere problem (sounds like user problem), and you didn't use the issue templates correctly.
