### ISSUE TITLE
autoupdate logger

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#539]
#### Overview:
- I would like to see an autoupdate logger that would log title updates.

#### Nature of Request:  
- Addition

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>
- [**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?
Knowing what titles were updated and when and how large the update was would be a cool feature  Knowing the delta from the previous update would also be a nice bonus

**Comment by SciresM** [comment]
This doesn't really sound like an Atmosphere job, nor is there an obvious mechanism by which to implement this.
