### ISSUE TITLE
Allow holding override key on any controller for HBL

### ISSUE THREAD

**Issue by leo60228** [Atmosphere-NX/Atmosphere#541]
#### Overview:
- Currently, player 1 must be holding R to start hbl, even though all players can launch applications.</br>

#### Smaller Details: 
- This could possibly be implemented by doing a bitwise OR on all controllers in https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/loader/source/ldr_hid.cpp.</br>

#### Nature of Request:  
- Addition
- Change

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>
    - Specifically, in https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/loader/source/ldr_hid.cpp.

### Why would this feature be useful?
In most situations, this is a matter of convenience. However, in some (very) rare cases, this is required. I'm attempting to build an AVR-based device that launches HBL automatically in some cases, and this is required for it to function properly.

**Comment by HookedBehemoth** [comment]
Possible duplicate of this:
https://github.com/Atmosphere-NX/Atmosphere/issues/524
