### ISSUE TITLE
[Feature request] Per-user language/region config

### ISSUE THREAD

**Issue by sqrg** [Atmosphere-NX/Atmosphere#547]
#### Overview:
- Ability to set a game's language/region on a per-user basis</br>

#### Smaller Details: 
Unknown

#### Nature of Request:  
- Addition
  - Might work like v0.8.10's ability to configure language/region on a per-game basis

### What component do you feel this would best fit within?
Unknown

### Why would this feature be useful?
Most games set up their language with the OS language. A user might like to play a game on its original language, while another user might need to play on another language. With this feature, there is no longer needed to change the OS language</br>

**Comment by SciresM** [comment]
Theoretically a good idea, however -- we still have no good way of representing users as text since user ids are ridiculously cumbersome. If that problem ever gets solved, sure.
