### ISSUE TITLE
i 've got an erorr code  2000-2000 (0x0)

### ISSUE THREAD

**Issue by gamingtheohd** [Atmosphere-NX/Atmosphere#549]
![HPWebcamPicture_0217](https://user-images.githubusercontent.com/51205032/58643050-3644d080-8307-11e9-8026-7d411f7d5815.jpg)
I have updated my console with choidujor to version 8.0.0(exfat) and then I put all files from the new atmosphere version.PLEASE, i need a respond today.EMERGENCY
i use hekate
i update from 6.x.x to 8.0.0

**Comment by ZachyCatGames** [comment]
if you have any themes, delete them

**Comment by HookedBehemoth** [comment]
iirc this can be caused by old themes. Delete the folders from /atmosphere/titles that are not from atmosphere.

**Comment by gamingtheohd** [comment]
THANKS!!GOD BLASS YOU!
