### ISSUE TITLE
You have a TODO in thermosphere main.c

### ISSUE THREAD

**Issue by sandhoners123** [Atmosphere-NX/Atmosphere#553]
// TODO: This should probably induce a reboot,
    // rather than sticking here.
Put a panic or reboot to payload here

**Comment by sandhoners123** [comment]
Will make a pr to fix

**Comment by sandhoners123** [comment]
I already forked, so cant make pr

**Comment by sandhoners123** [comment]
Just replace while(1) with panic("An error has occurred"). This will prevent people from seeing a bsod

**Comment by sandhoners123** [comment]
No, not panic

**Comment by sandhoners123** [comment]
Actually yes panic

**Comment by sandhoners123** [comment]
That loops the console in an indefinite panic loop but we should just abort the cpu

**Comment by fincs** [comment]
Thermosphère is not maintained at the present time.
