### ISSUE TITLE
Input Redirection (+ i2c Support for Home)

### ISSUE THREAD

**Issue by Bappsack** [Atmosphere-NX/Atmosphere#556]
### What feature are you suggesting?

Input Redirection like Luma3DS

### Why would this feature be useful?

to allow Controllers that aren't supported or usage for small Bots (Shiny Hunt for Pokemon for ex,).

**Comment by jakibaki** [comment]
check out [hid-mitm](https://github.com/jakibaki/hid-mitm)

**Comment by Bappsack** [comment]
i know hid-mitm, it works great, but something thats build it would be better and it won't allow the Home Button nor JoyCons(yet).

**Comment by SciresM** [comment]
Closing due to existence of alternate solutions and this being encapsulated by broader TMA goal anyway.
