### ISSUE TITLE
[1.6.0 UPDATE] can't be installed - 《The Legend of Zelda™: Breath of the Wild》

### ISSUE THREAD

**Issue by Tiande** [Atmosphere-NX/Atmosphere#565]
### What's the issue you encountered?
《The Legend of Zelda™: Breath of the Wild》's [1.6.0 UPDATE] can't be installed.
Which's full name: [01007EF00011E800][v786432].nsp

### How can the issue be reproduced?
Install this update through [Goldleaf v0.5] or [Goldtree v0.5]

### Crash Report
1. When use Goldleaf(through USB), it says 'this title already installed on this console'
2. When use Goldtree, it will uninstall all of Zelda and just install the UPDATE

### System Firmware Version
official 8.0.1
KosmosV12-2

### Environment?

hekate
Official release version 8.0.1
no more kips or sysmodules
Homebrew software installed: [ Goldleaf appstore EdiZon KosmosToolbox KosmosUpdater Ldnmitm_config Lockpick ]

### other infomation
It seems that SX OS is no problem: [LINK](https://gbatemp.net/threads/zelda-botw-1-6-0-using-firmware-7-01-what-will-happen.537288/)

Can you figure out what's the problem?
What can i do to make it be installed?
Thans!

**Comment by TuxSH** [comment]
We don't support piracy.
