### ISSUE TITLE
failed to run sept

### ISSUE THREAD

**Issue by siege86** [Atmosphere-NX/Atmosphere#570]
i can load atmosphere but when i try to run cfw i cant because it wont run the sept file

**Comment by TuxSH** [comment]
Are you using the sept files from the release archive?

**Comment by siege86** [comment]
yes

**Comment by siege86** [comment]
what else should i do

**Comment by WerWolv** [comment]
- Make sure the SD card is formatted to FAT32. Use GuiFormat for that.
- Try wiping your card clean by deleting everything but the Nintendo folder and copy the Atmosphere files back on the SD.
- "Won't run the sept file" Are you injecting the right payload? You either need `hekate_ctcaer_4.10.1.bin` or `fusee_primary.bin`

**Comment by siege86** [comment]
ok i fixed lol but in the process gropped my switch and now the latch is chipped and wont stay on
