### ISSUE TITLE
error code 2168-0002 (ox4a8)

### ISSUE THREAD

**Issue by siege86** [Atmosphere-NX/Atmosphere#571]
getting this error code i dont know what to do

**Comment by aveao** [comment]
Where are you getting this error code?

**Comment by divicioso** [comment]
Me too, randomly minutes after turn on. Sometimes when power on the switch. Coming back from sleep Mode tiggers It out, not always the first time but second or thirth .

**Comment by SciresM** [comment]
reopen using issue templates, in particular with crash reports.
