### ISSUE TITLE
error code 2345-0031(0x3f59)

### ISSUE THREAD

**Issue by IThinkIGottaGo** [Atmosphere-NX/Atmosphere#572]
### What's the issue you encountered?

I met some strange crash scene, it happened when I start any game, and press "home" button back to the main screen (game running in background). Then I go through the photograph try to getting in hbm menu, crash just happended. And It's 100% could re-happened again, but scene it's so simple. 

More, if before I get into hbm, I totally close the game first, the I could access hbm menu sccessful again, strange.

But it seems only happened on switch 8.0.1 version, when I downgrade to 7.0.1 all works normal, and no crash.

by the way, actually I used kosmos all-in-one package but also atmosphere at back, so that must something wrong. so at the end I post the crash screen capture, hope that useful.

And kosmos seems run the `fusee-secondary.bin` first in the `hekate_ipl.ini`, so I don't know would that correct?

### Crash Report

Here is my crash reports also.

[01560782388_010000000000100d.log](https://github.com/Atmosphere-NX/Atmosphere/files/3297730/01560782388_010000000000100d.log)

### System Firmware Version

8.0.1(AWS 0.9.0)</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
from hekate then boot fusee-secondary

- Official release or unofficial build: 

Kosmos' distribution of Atmosphère ( I upgrade atmosphere to 0.9.0 handy, but I don't think it that cause the problem, because even before I upgrade atmosphere, it aslo happend before when i run in 8.0.1 system, I had to downgrade to 7.0.1 then I could normally use hbm that games run in background. And I upgrade to 0.9.0 just hope this version maybe could solve that problem, but seems not.)

Kosmos itself provider some kips (like netcheat etc.), but I all off them and no run.

- Do you have additional kips or sysmodules you're loading:
it carryed

### Additional context?

From crash  capture I cound know `010000000000100D` cause the crash, but that's the photograph app itself right?

Hope the issue report could useful.

![IMG_20190617_224502](https://user-images.githubusercontent.com/20919271/59617434-eebca200-9158-11e9-8be3-4297b11d48de.jpg)

**Comment by SciresM** [comment]
Not an atmosphere bug, update your hbl.
