### ISSUE TITLE
sysNAND boot stalls after emuMMC shutdown

### ISSUE THREAD

**Issue by aedalzotto** [Atmosphere-NX/Atmosphere#573]
### What's the issue you encountered?
After using emuMMC and shutting down the Switch stalls its normal boot and needs to be shut down in the "Nintendo Switch" splash screen. Then, retrying a normal boot works again.

### How can the issue be reproduced?
Boot emuMMC (separate partition mode) with fusee-primary.
Shutdown (hold power button -> power options -> turn off)
Power up without payload
Now, the Switch will hang forever in the Nintendo Switch splash screen. Short press power to shut it off.
Press power again to normal boot (no payload).
The Switch will boot properly.

### System Firmware Version

8.0.1

**Comment by hippydave** [comment]
I had this too.

**Comment by m4xw** [comment]
This doesn't happen if you inject with a payload?

**Comment by m4xw** [comment]
Regulator issue, related to https://github.com/m4xw/emuMMC/issues/2
Not a atmo issue.
