### ISSUE TITLE
how to install or update? in NS-Atmosphere 190513 version

### ISSUE THREAD

**Issue by dc1ps2** [Atmosphere-NX/Atmosphere#574]
I would like to ask, I currently have the atmosphere of version 0.8.9 installed. I have previously updated hekate_ctcaer_4.10.1.bin to my injector, but I want to manually upgrade the 0.9.0 version of the atmosphere. What should I do? I tried Updated the file in atmosphere-0.9.0-master-aa289410+hbl-2.1+hbmenu-3.0.1.zip to overwrite the file in the SD card, and also re-update fusee-primary.bin to my injector, execute the crack After the program, click on the personal icon in the upper left corner, and did not enter the hbmenu homemade menu. What am I missing?

**Comment by NickHam13** [comment]
You have to hold R and launch a game.
