### ISSUE TITLE
atmosphere will not start up on 6.2 FW

### ISSUE THREAD

**Issue by ELY3M** [Atmosphere-NX/Atmosphere#580]
### What's the issue you encountered?
I just updated my atmosphere cfw on my switch with 6.2 FW 
I am not planning to update that switch.     

It boot up and showed my custom splash screen then black screen with the white logo then get back to RCM mode.  I try injecting payload again and it go same way again.  
I also tried using hekate payload to start atmosphere.  

[ Describe the issue in detail and what you were doing beforehand. ]
updated my atmosphere to 0.9.1 and tried to reboot. 
it wont boot all way. it kept coming back to RCM mode.   

[ Did you make any changes related to Atmosphère itself? ] No </br>
[ If so, make sure to include details relating to what exactly you changed. ]</br>

### How can the issue be reproduced?
try to start atmosphere on switch with 6.2 FW  
then try to inject fusee-primary or hekate payload.   

### Crash Report
here are 3 error bins on my dropbox 
https://www.dropbox.com/sh/jzu4zqox248xftf/AAAMPrjEEKC4G1Tk5Qb8gv1Ra?dl=0

I tried to use gist.github.com but I cant upload the bin files...  
hope my dropbox is ok here.  

### System Firmware Version
6.2.0 

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
I used both fusee and hekate payloads.  
I use 1 at a time.  I use fusee most of the time.  
when it keep coming back to RCM. 
I tried hekate and see if it work.    

- Official release or unofficial build: 
  - [ Official release version 0.9.1 

- Do you have additional kips or sysmodules you're loading:
Nope
- Homebrew software installed: [ * ]
ftpd and variety of my homebrew apps in /switch on my sd card 

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

here is pic of the error on my switch screen.  
https://www.dropbox.com/s/ef0jmzt8fvnnp9i/20190619_170839.jpg?dl=0

**Comment by SciresM** [comment]
Fixed by 241b8f4627e009e8114f9f021bd94ca667c25ac4.
