### ISSUE TITLE
Atmosphere 9.1 black screen on 8.1.0

### ISSUE THREAD

**Issue by zany130** [Atmosphere-NX/Atmosphere#581]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

[ booting with the fussgee  payload shows a messages staying welcome to atomowhphere then a black screen]</br>
[ No changes to atmosphere]</br>
[ N/A ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ insert and sd card with the atmosphere files and boot into rcm. Inject the fusegelee payload. You will get a welcome message and black screen]</br>

### Crash Report

[ Crash reports can be found under ``/atmosphere/crash_reports``. ]</br>
[ If your issue caused Atmosphère to crash, include the crash report(s) by creating a [gist](https://gist.github.com/) and pasting the link here. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]</br>

### System Firmware Version

8.1.0</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusee
- Official release or unofficial build: 
  - [ Official release version 9.1.0(or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading: no
- Homebrew software installed: none [ * ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
1) you filled issue template out incorrectly

2) If self compiling, as you indicated, you need to use the release sept builds as you don't have keys.
