### ISSUE TITLE
Failed to run sept

### ISSUE THREAD

**Issue by JackTGarland** [Atmosphere-NX/Atmosphere#590]
### What's the issue you encountered?

 When Trying to launch Atmosphere from RCM is get "failed to run sept. Failed to launch firmware. </br>
 I am running 8.0.1 stock and have the latest's versions of Atmosphere and Hekate. </br>
I can run the latests version of lockpick_RCM.bin no problem.</br>

### How can the issue be reproduced?

[ * ]</br>
Boot into RCM, select launch and select Atmosphere.</br>
I wish I could give more, but that's all I am doing. I have followed this guide https://nh-server.github.io/switch-guide/user_guide/sd_preparation/ To get to this stage.
### Crash Report

N/A

### System Firmware Version

8.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - Hekate, Offical build 0.9.1

### Additional context?

My CD card is formatted as exFAT, it is my understanding that it is supported.

**Comment by SciresM** [comment]
Hekate currently doesn't support atmosphere 0.9. You can either use fuses or chainload fusee from hekate.
