### ISSUE TITLE
i get the code error when i want to enter homebrew

### ISSUE THREAD

**Issue by gamingtheohd** [Atmosphere-NX/Atmosphere#604]
i get the code error when i want to enter homebrew :error code 2168-0002 (0x4x8)
firmware: 8.0.0 (atmosphere 0.8.10-master-422dce69)
and sometime i get 2144-001 (0x290) error
PLS HELP

**Comment by WerWolv** [comment]
Segfault. It's a generic error and says absolutely nothing about the reason for. Most likely a homebrew error and not Atmosphere
