### ISSUE TITLE
Hangs on Stock with EmuMMC open

### ISSUE THREAD

**Issue by DanielC-08** [Atmosphere-NX/Atmosphere#607]
### What's the issue you encountered?

If EmuMMC isn't disabled when booting stock, it will cause a hang.

### How can the issue be reproduced?

1. Create an EmuMMC partition
2. Boot Stock
3. It will sometimes hang

### System Firmware Version

8.1.0

**Comment by SciresM** [comment]
"booting stock"

"emummc"

huh?

I don't really think that can work right, since the Nintendo folder won't be redirected for non-FS...

**Comment by SciresM** [comment]
Also, I'm not sure that issues that occur when booting without atmosphere are atmosphere issues.
