### ISSUE TITLE
Re-implement the Loader sysmodule.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#61]
Loader will need to be re-implemented, and extended to support loading executables from the SD card.

**Comment by SciresM** [comment]
Loader is fully re-implemented as of right now, and works on hardware.

Keeping this issue open until it's fully extended/"done", though.

**Comment by roblabla** [comment]
Just to avoid confusion: Loading from SDcard loading is already implemented. See https://github.com/Atmosphere-NX/Atmosphere/blob/master/stratosphere/loader/source/ldr_nso.cpp#L22.
