### ISSUE TITLE
Atmosphère 0.9.2, BUG on IPATCHED Switches

### ISSUE THREAD

**Issue by alimao10** [Atmosphere-NX/Atmosphere#613]
Atmosphère 0.9.2, BUG on IPATCHED Switches . Freezes on Nintendo Switch Logo
when I go back to Atmosphère 0.9.1 it works perfectly

**Comment by PabloGBarcelo** [comment]
Same issue here:
https://github.com/Atmosphere-NX/Atmosphere/issues/608

**Comment by alimao10** [comment]
tranks without solution

**Comment by SciresM** [comment]
Duplicate.
