### ISSUE TITLE
Amend version string to show SD number in EmuMMC mode

### ISSUE THREAD

**Issue by Specced** [Atmosphere-NX/Atmosphere#614]
### Overview: 

Since distinguishing between EmuMMC and SysNAND can be challenging I propose that the SD-number(SD00, SD01) etc is added to the system strung to make it easier to identify if you have booted into EmuMMC. 

### Nature of Request:  

- Change to the version string

### Where:

[**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?

It would help to verify if EmuMMC is working and prevent accidental use of SysNAND or a unclean NAND for online activities.

**Comment by SciresM** [comment]
There's insufficient space. We may sacrifice one character, but the version string format is fully spec'd and being treated cautiously for future proofing. Right now we have zero remaining characters.
