### ISSUE TITLE
Gamecard error on FW 1.0.0

### ISSUE THREAD

**Issue by Razorbacktrack** [Atmosphere-NX/Atmosphere#617]
Switch with AutoRCM, Hekate that loads fusee-secondary, 1.0.0 Sysnand and 8.1.0 RAW Emunand.
Automatic nogc (I can't use gamecards on CFW 8.1.0, but this is normal).

I got a fatal error when I insert the gamecard with OFW 1.0.0 (using stock=1 option) and CFW 1.0.0 (with fusee-secondary).

[01561989881_010000000000001f.log](https://github.com/Atmosphere-NX/Atmosphere/files/3346024/01561989881_010000000000001f.log)

**Comment by SciresM** [comment]
Turn off auto nogc, I guess -- you burnt your gamecart controller's fuses. 2002-2634 is "Gamecard controller did not accept the firmware that was sent."

Not really sure how you did that, you must have booted into a higher firmware version without nogc. somehow? Were you using non-fusee solutions or something?

Anyway, forcibly set nogc = 0 in your config, and you'll be able to use gamecards on 8.1.0 emummc. You'll never be able to use them on sysnand.
