### ISSUE TITLE
[4.0.1] Can't boot emuMMC (Stock)

### ISSUE THREAD

**Issue by Lordmau5** [Atmosphere-NX/Atmosphere#618]
### What's the issue you encountered?

When tying to boot into emuMMC (Stock) the Switch it shows the Nintendo logo for a moment and afterwards goes into a black screen.

### How can the issue be reproduced?

Try to boot into emuMMC (Stock) whilst on version 4.0.1 (potentially the 4.X range)

### System Firmware Version

4.0.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: Official, 0.9.2 (hotfix)
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: None

### Additional information

The hotfix that was uploaded today actually allows me to boot into emuMMC CFW, so that's nice to see already

**Comment by SciresM** [comment]
Stock --> not supported by atmosphere.

Emummc stock doesn't really make sense, since redirection of Nintendo dir by non-FS won't work...
