### ISSUE TITLE
Atmosphere Error 2000-000 on Launch

### ISSUE THREAD

**Issue by lung9** [Atmosphere-NX/Atmosphere#622]
### **What's the issue you encountered?**

Starting up Atmosphere only shows Error Message after Nintendo Logo. (Error 2000-0000)
![IMG_20190706_184120](https://user-images.githubusercontent.com/27688473/60759011-8efe3c00-a01e-11e9-92c9-fb6b028b1f54.jpg)

### **How can the issue be reproduced?**

To be honest Im not sure. It started after i downgraded to 6.2.0

### **Crash report?**
[01562431238_010000000000003e.log](https://github.com/Atmosphere-NX/Atmosphere/files/3364862/01562431238_010000000000003e.log)
### 
**Environment?**

- What bootloader (fusee, hekate, etc) was Atmosphère launched by: fusee
- Official release or unofficial build: Atmosphere 0.9.2
- Do you have additional kips you're loading: no
- Additional info about your environment: firmware version 6.2.0

**Comment by SciresM** [comment]
You downgraded in a way that caused the olsc system module to have invalid savedata.

Delete the relevant savedata or restore a backed up copy from before you updated -- this is a requirement for downgrading.

**Comment by lung9** [comment]
Where can i find these savefiles?
