### ISSUE TITLE
BOTW not running

### ISSUE THREAD

**Issue by m1chael1995** [Atmosphere-NX/Atmosphere#626]
Hi I recently started using atmosphere and downloaded a load of games and installed them using gold leaf (sorry if I'm not aloud to mention names of apps) but I'm able to play all games no issue after downloading the title key files but the only one so far not working is botw even with the game card. It just tells me that I need to purchase the game. Would this be an issue with atmosphere or goldleaf?

**Comment by DankanTsar** [comment]
Strange, legally purchased eshop games work great.

**Comment by fincs** [comment]
Piracy is not supported.

**Comment by m1chael1995** [comment]
Ahh okay please forgive me if I said something wrong I'm new to Nintendo stuff
