### ISSUE TITLE
Atmosphère crash after activating emuiibo and other sys modules

### ISSUE THREAD

**Issue by j-james** [Atmosphere-NX/Atmosphere#627]
### What's the issue you encountered?

Atmosphère crashed.

### How can the issue be reproduced?

It can be reproduced by going to sdsetup.com](https://www.sdsetup.com/console?switch) and selecting the same packages, then turning on emuiibo, sys-ftpd, and sys-clk and rebooting into CFW.

### Crash Report

I have two crash reports, one after booting from fusee-primary and the other after booting from hekate. [Gist](https://gist.github.com/j-james/ec1a7b6b13f9ad1c207557bd8d5e76b7)

### System Firmware Version

8.1.0

### Environment?

I launched Atmosphère by fusèe first, then hekate.\
I used Kosmos's (13.0.1) latest build of Atmosphère (0.9.2).

sysmodules:
- emuiibo
- hid-mitm
- sys-clk
- sys-ftpd
- sys-netcheat
- ldn_mitm

homebrew:
- Kosmos Updater
- Kosmos Toolbox
- AmiiSwap
- Checkpoint
- Goldleaf
- NxThemes Installer
- Retroarch
- MelonDS

### Additional context?
I activated emuiibo, sys-clk, and sys-ftpd before the error.\
I'd guess that this is an emuiibo issue. 

![Screenshot_20190708-150938_Camera](https://user-images.githubusercontent.com/35242550/60846925-e07d0700-a195-11e9-9fb6-57836f0f7464.jpg)

**Comment by j-james** [comment]
#595

**Comment by SciresM** [comment]
sure doesn't sound like an atmosphere problem.
