### ISSUE TITLE
Use ccache to improve compilation performance

### ISSUE THREAD

**Issue by fennectech** [Atmosphere-NX/Atmosphere#631]
#### Overview:
- We can use ccache to improve performance significantly for users who have ccacne installed.</br>

#### Smaller Details: 
- Ccache caches source compilation meaning if a module doesn't change the system does not have to compile and can instead pull from the cache making compilation significantly faster</br>

Ccache is used by for example calling it before the compiler of choice  
EX  `` ccache gcc`` or ``ccache cxx``
#### Nature of Request:  
- Addition
### What component do you feel this would best fit within?
- [Fusée](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Atmosphère's custom bootloader.</br>
- [Exosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Fully-featured custom secure monitor.</br>
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Custom system modules.</br>
- [**Thermosphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Atmosphère's emuNAND implementation.</br>
- [**Troposphère**](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
  - Application-level patches to the Horizon OS.</br>

### Why would this feature be useful?
This will make recompiling it atmo MUCH faster after compiling once.  </br>

**Comment by friedkeenan** [comment]
Isn't it already that files that weren't modifed aren't recompiled?

**Comment by fennectech** [comment]
It is isnt it :shrek:
