### ISSUE TITLE
Feature Request: Config Generation

### ISSUE THREAD

**Issue by SunTheCourier** [Atmosphere-NX/Atmosphere#632]
### What feature are you suggesting?
Generating Atmosphere's configuration files instead of packaging in release.<br>

#### Details: 
Somewhere during initializing of boot or of the config's component, the component should create the config file if it does not exist with default values.<br>

#### Nature of Request
- Addition
- Change

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - Boot component or respective to each individual config's system module.<br>

### Why would this feature be useful?
Prevents users from accidentally reverting their configuration if it has been modified from default. </br>

**Comment by SciresM** [comment]
Atmosphere explicitly has a policy of never writing configuration -- so far as it is concerned, configuration files are read-only.

**Comment by SciresM** [comment]
There are plans to use default values instead of erroring when config isn't present, though, and moving default configuration to an examples folder (so that it wouldn't overwrite people's config any more).
