### ISSUE TITLE
Can't boot CFW after 8.1.0 update

### ISSUE THREAD

**Issue by kingafro000** [Atmosphere-NX/Atmosphere#642]
What's the issue you encountered?
Starting up Atmosphere only shows Error Message after Nintendo Switch Logo. (Error 2000-0000)

How can the issue be reproduced?
Update to 8.1.0(exfat) using ChoidujourNX and my own dump and then boot into CFW

Environment?

What bootloader (fusee, hekate, etc) was Atmosphère launched by: same result both hekate and fusee
Official release or unofficial build: Atmosphere 0.9.2
Do you have additional kips you're loading: no
Additional info about your environment: firmware version 8.1.0

**Comment by SciresM** [comment]
Crash report? Deleted your custom theme?

**Comment by stuie1** [comment]
Do u have a theme install delete titles for the damn themes or back everything up on sd card find a fat 32formatted and format sd card 2 32fat if u have a 500gb sd lower with out fat 32 will have errors best to be on fat 32

**Comment by flightcoin** [comment]
Same here, how would you be able to clear out the themes after the update?

**Comment by austin5623** [comment]
Literally just delete /atmosphere/titles/0100...100 (not 1000, that's mario odyssey)

**Comment by flightcoin** [comment]
Works, thank for this.

**Comment by shchmue** [comment]
note ...1000 is qlaunch, ...10000 is Mario Odyssey
