### ISSUE TITLE
transfer instaled nsp to SD

### ISSUE THREAD

**Issue by darkobag** [Atmosphere-NX/Atmosphere#648]
Hi, I admire your work, thank you very much for it.
I would like to ask you how I can do to transfer my installed nsp games, from the switch memory to the SD, I have my firmware 8.1.0 and atmosphere 0.9.1) I know that I should only have installed you in the SD, please don't be hard on me.

I'm a little new to this but I'm still learning things

**Comment by mbhakta15** [comment]
This is a place for issues regarding atmosphere. The creators and devs of Atmosphere will never discuss piracy related topic with you on this GitHub page. Please redirect your question to a reddit page more suited for this question.

Plus this is not an 'issue'

P.S. no way to transfer, just uninstall and reinstall where you want it
