### ISSUE TITLE
Error Code 2000-0000 (0x0)

### ISSUE THREAD

**Issue by junyjeffers** [Atmosphere-NX/Atmosphere#649]
Switch Firmware: 8.1.0 > 6.1.0
Yes, I downgraded not knowing about fuses at the time... 

This error code appears after the Nintendo Switch logo and, no, there is NOT a theme that was installed when downgrading (at least on my current SD card). I need to upgrade back to 8.1.0 to fix and use my switch again and to do that, all I need to do is bypass/fix this error. Any help?

**Comment by bakugo** [comment]
Just restore the backup you made before downgrading.

... you DID make a backup, right?

**Comment by HookedBehemoth** [comment]
Please follow the issue template.

What Atmosphere version are you on?
Could you please send the fatal/crash report.

Did you try cleaning your sd card and especially your atmosphere folder?

**Comment by SciresM** [comment]
please reopen using issue templates.

Also, please update to Atmosphere 0.9.3. 2000-0000 can never occur on newer atmosphere, it will display as 2162-0002.

**Comment by stuie1** [comment]
Well I’m just saying I got the same error possible.. when I upgraded to 8.1.0 from 7.0.1 so I was on sx os and I guess I had themes installed so I downgraded with the backup I had right but guess what when I made nand backup on sx os I didn’t have just enough space never backed up only boot files so I did back up now system gives me error right after Nintendo sign right so I had to switch to atmospheres fixing system I guess that’s what the person did to
Fix it but I can not use sx os anymore on this system...

**Comment by stuie1** [comment]
U might have to switch to sx os idk they selling for
Like 150 now... unless u buy a payload injector on amazon and change the file that’s on the sd injector idk if that works but I’m use it does the injector on amazon is only 12$ from China get it while
It last

**Comment by fincs** [comment]
Promotion of hostile Atmosphère forks and/or warez hardware/software is not allowed.
