### ISSUE TITLE
9.0.0 STOP ATMOSPHERE FUSEE PAYLOAD no longer able to boot atmosphere

### ISSUE THREAD

**Issue by racerx8967** [Atmosphere-NX/Atmosphere#655]
As the title says, I accidentally update as i was starting a game as it just dropped and though i shut off my system immediately I'm now on 9.0.0 DON'T UPDATE till atmosphere guy makes new CFW just a warning to all.  Take caare

**Comment by SciresM** [comment]
this isn't the place.
