### ISSUE TITLE
9.0.0 uptade dont work with atmosphère

### ISSUE THREAD

**Issue by JoPitYT** [Atmosphere-NX/Atmosphere#656]
-Atmosphere do not work on the new uptade

Its been 2 month my switch is hacked. I forgot using incognito and my little brother uptaded my switch wen he was starting a game so I cant access the cfw.
Ps: you guys doing great job!

**Comment by Axodique** [comment]
You have to wait for atmosphere to update.

**Comment by JoPitYT** [comment]
Ok sry i just wanted To be sure and advice the dev. If they didnt know
