### ISSUE TITLE
Nintendo switch v.9.0

### ISSUE THREAD

**Issue by advenger005** [Atmosphere-NX/Atmosphere#657]
Me gustaría saber cuando saldrá la nueva versión de Atmosphere para la nueva versión 9.0? Me actualizaron la switch por accidente y ninguno de los patch me funciona se queda la pantalla en negro😓😓

**Comment by D3fau4** [comment]
Eta 5h

**Comment by fincs** [comment]
Por favor rogamos paciencia. Estamos todavía poniendo todo a punto para las nuevas versiones de Atmosphère y libnx.

> OP said:
> I'd like to know when will the next version of Atmosphère come out for the new {system} version 9.0. My Switch got updated by accident and none of the patches work for me, screen stays black 😓😓
>
> I replied:
> Please be patient. We are still getting everything ready for the next versions of Atmosphère and libnx.
