### ISSUE TITLE
0.9.4 crashes the switch

### ISSUE THREAD

**Issue by Axodique** [Atmosphere-NX/Atmosphere#660]
### What's the issue you encountered?

I replaced hekate and atmosphere to the latest versions in the file (hekate or not it crashes) and it crashes just after the nintendo switch screen
### Crash Report

https://gist.github.com/Axodique/3a27075a8dd348a9e03f64e4a52efe2f

### System Firmware Version

9.0.0</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

tegra rcm Environment

**Comment by Axodique** [comment]
UPDATE: I tried with just atmosphere and it worked. i'll try putting homebrew one by one to find the one that crashes me.

**Comment by SciresM** [comment]
Cool, not an ams issue then.

**Comment by friedkeenan** [comment]
Might be because of https://github.com/jakibaki/hid-mitm

**Comment by Axodique** [comment]
It was actually the nintendo folder. people who installed games on their sd card ilegally be careful

**Comment by Axodique** [comment]
Actually,i was with the fact that i was just replacing the files and not reseting the atmosphere folder to 0.

**Comment by Axodique** [comment]
Last update i swear! it was the titles folder.

**Comment by Shenron0** [comment]
For me it just freezes on the Nintendo Switch logo
