### ISSUE TITLE
Joycons wont work on some nsp games

### ISSUE THREAD

**Issue by NickN0rth** [Atmosphere-NX/Atmosphere#663]
Hello,

After the latest update of Atmosphere my joycons wont work on some of the nsp games.
I can launch the game but when i must press L+R my joycons wont react.
Only the home button works.
What can i do to fix this, please help!!

**Comment by fincs** [comment]
> nsp games

Piracy is not supported. Homebrew is loaded through hbloader, which has the hid-mitm temporary workaround applied; and *not* by other means which are 100% unsupported and discouraged.
