### ISSUE TITLE
Freezes on Nintendo Switch Screen on 9.4.0

### ISSUE THREAD

**Issue by Nomercyman1** [Atmosphere-NX/Atmosphere#664]
I just downloaded all the files for 9.4.0 to work on system update 9.0.0. It loads up fine, goes through the Atmosphere and Sept splash screens, then it freezes at the Nintendo Switch screen. Is there something I'm missing or need to change with the new version?

**Comment by ThatNerdyPikachu** [comment]
Please use the [issue template](https://github.com/Atmosphere-NX/Atmosphere/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to report bugs.
