### ISSUE TITLE
Freezes on Nintendo Switch Screen on 9.4.0

### ISSUE THREAD

**Issue by Nomercyman1** [Atmosphere-NX/Atmosphere#672]
## Bug Report

[ * ]

### What's the issue you encountered?

[ Injected fusee primary on the Switch, to boot into homebrew. It loaded up the Atmosphere and Sept splash screens, but seems to freeze at the Nintendo Switch splash screen.   ]</br>
[ I changed the fusee primary used to boot into homebrew to the latest version, and replaced all the 9.3.0 files with those for 9.4.0, since I updated to software version 9.0.0 ]</br>
[ updated files from "atmosphere-0.9.4-master-a750e55f+hbl-2.2+hbmenu-3.1.1.zip"
and "fusee-primary.bin" used to inject the payload ]</br>

### How can the issue be reproduced?

[ * ]</br>
[ Inject the "fusee-primary.bin" to load homebrew ]</br>

### Crash Report

[ N/A]</br>
[ N/A ]</br>

### System Firmware Version

9.0.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Official release version 9.4.4 ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Might be Kosmos, not sure]

### Additional context?

- Additional info about your environment:
- [ Only changed/copied the files within the Atmosphere, Sept, Switch and the hbmenu files ]

**Comment by DanielC-08** [comment]
Do you mean 0.9.4 atmosphere and 9.0.0 horizon os?

**Comment by SciresM** [comment]
Please remove your custom system modules/custom theme. If you have files under atmosphere/titles/0100000000001000, delete them. If that doesn't work, please list the folders under /atmosphere/titles to be told what to delete.

**Comment by Nomercyman1** [comment]
9.0.0 switch software. But I realized it was the Game Cartridge in the slot
causing the problem. Though it only seemed to be an issue on the first boot
up into Homebrew. Now, working fine with game cartridge inserted.
