### ISSUE TITLE
ERROR 2002-1002

### ISSUE THREAD

**Issue by SANALVES** [Atmosphere-NX/Atmosphere#673]
Firmware 9.0.0 , Using Cosmos  with Atmosphere 0.9.4 and GoldLeaf 

I can create Emunand using Hekate and start unlocking normally and install NSP games. However when I turn off the video game and start unlocking again by Emunand the installed games do not start and present the error 2002-1002 which says I must download the game again.

Uninstalling the game and installing again does not work. the only solution i found was to delete emunand, create a new one and install it all over again. But I have to repeat this every time I turn off the switch.

Does anyone know why this is happening

**Comment by SciresM** [comment]
Atmosphere doesn't support piracy, sorry.
