### ISSUE TITLE
Save Data corruption while using CFW

### ISSUE THREAD

**Issue by crisftw** [Atmosphere-NX/Atmosphere#675]
Latest version of Atmosphere causes an issue to a game called Castle Crashers (Not pirated). The game run well. No crashes. The one issue that is being reported around is that after making progress and quitting the application, it will delete character progress. Running OFW, the game will not delete character progress after starting the game up. All this was done on 8.1.0, 9.0.0 and 9.0.1.

**Comment by SciresM** [comment]
In the future, please use issue templates.

What happens if you enable the experimental save redirection to SD for the game?

**Comment by xPrinny** [comment]
I'll write a bug report.

## Bug Report

In the game Castle Crashers, save data does not get loaded properly after loading or switching profiles in game. (Loading a second profile for a second player works fine.)</br>

### What's the issue you encountered?

Save data does not get loaded properly after loading or switching profiles.</br>

### How can the issue be reproduced?

Launch the game and load a profile.</br>
Play the game normally, exit to map to save data.</br>
After game is closed and reopened or profile is switched save will not be loaded properly.</br>


### Crash Report

N/A

### System Firmware Version

8.1.0</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: hekate
- Official release or unofficial build: 
  - Unofficial build
  - Komos distruption of Atmosphère (0.9.3)
- Do you have additional kips or sysmodules you're loading: hid_mitm, ldn_mitm
- Homebrew software installed: N/A

### Additional context?

- Additional info about your environment: N/A
- As for mentions about it deleting progress is mostly false. Game does not load data properly and trying to play will overwite it with current playthrough.
- Experimental save redirection to SD does nothing. (I might have not done this right.)

**Comment by crisftw** [comment]
My apologies SciresM. I have enabled the experimental save data redirection to the SD but it doesn't seem to work for me. I got support to see if I enabled it properly but it didn't work in the discord server. I also wanted to use older versions of Atmosphere and I only got down to 0.9.1 and nothing worked. Character progress was still deleted

**Comment by ItsCinnabar** [comment]
For what it's worth, this exact process appears to allow the game to properly save while under atmosphere : 
https://streamable.com/ptiur
https://gbatemp.net/threads/castle-crasher-remastered-player-1-save-issue.548517/#post-8800872

**Comment by xPrinny** [comment]
> 
> 
> For what it's worth, this exact process appears to allow the game to properly save while under atmosphere :
> https://streamable.com/ptiur
> https://gbatemp.net/threads/castle-crasher-remastered-player-1-save-issue.548517/#post-8800872

Oh, that's my video. It actually allows it to load properly not save properly. I think I forgot to mention that achievement do get loaded when you pick your profile but not character data while that mini-game somehow makes the data load properly.

Saving does not seem to be the issue, it's loading. You can prove this by playing and saving normally, reload the game with a different profile or swap profile in game, then pick the first profile as player 2 and you can see it loads properly.

**Comment by crisftw** [comment]
🤔 Well if the game doesn't load properly due to the CFW and it has a solution, then I guess there isn't much SciresM can do as the issue is unknown. But I can tell you by experience that SXOS 2.8 worked fine with this game until you update to 2.9. Its been proven SXOS is using Atmosphere source. I just don't want many other games to bug out because of CFW

**Comment by ItsCinnabar** [comment]
Just because someone found a work around doesn't mean it can't be fixed atmosphere side. I only posted that to hopefully give a bit of a starting point to the issue, so it can been seen what changes from normal loading vs post workaround loading.

**Comment by SciresM** [comment]
Is this still a problem?

**Comment by crisftw** [comment]
@SciresM Yes it is

**Comment by reminon** [comment]
I'm not understanding the issue you are having. I'm on 9.0.1, with ams 0.10.1, and I've had no save/load issues in either single player or co-op.

**Comment by crisftw** [comment]
> I'm not understanding the issue you are having. I'm on 9.0.1, with ams 0.10.1, and I've had no save/load issues in either single player or co-op.

That's because it seems like the latest update of Atmosphere fixed the issue

**Comment by reminon** [comment]
My bad, I'm an idiot. Sorry for the intrusion. Lol
