### ISSUE TITLE
Fails to boot from emuMMC/Hekate 5.0.2

### ISSUE THREAD

**Issue by YetAnotherOrc** [Atmosphere-NX/Atmosphere#676]
Needs to be addressed, if it's not Atmospheres' problem (likely since it boots from another card), issue already posted in detail on Hekate thread: https://github.com/CTCaer/hekate/issues/296

**Comment by CTCaer** [comment]
Problems like that are always 100% user problems
when editing the hekate ini,
or killing emuMMC partitions that still appear on emummc.ini,
or not updating all atmosphere files.

There's a brief error message before going to Nyx that you should always read.

Can be closed from here.
