### ISSUE TITLE
Full Atmos crash with modded botw

### ISSUE THREAD

**Issue by DarkWolfInsanity** [Atmosphere-NX/Atmosphere#680]
## Bug Report

Using mods inside BoTW has caused a full crash of the atmosphere cfw. Press power to restart.

### What's the issue you encountered?

*Have botw mods inside the title/01007EF00011E000/romfs folder
*open BotW
*firmware crashes instead of a usual title error
*system believes botw has corrupted data and amounts it as an sd card error

### How can the issue be reproduced?

see above

### Crash Report

https://gist.github.com/DarkWolfInsanity/091e598e76c67c6c435122023b811ed0

### System Firmware Version

9.0.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate
- Official release or unofficial build: unofficial?
  - 0.9.4
  - Kosmos Distribution (which i thought was official atmosphere)
- Homebrew software installed: [ * ] Goldleaf, Retroarch, Checkpoint, whatever Kosmos has added

### Additional context?

- BotW installed on MicroSD card. Console runs firmware through SysNand, console already banned months and months ago.

**Comment by SciresM** [comment]
Linked crash report is 2002-4690 (fs::ResultFatFileSystemCorrupted()).

I am going to assume this is exFAT problems, tentatively. Talk to me if it still reproduces on FAT32?
