### ISSUE TITLE
3 problems with 9.0.1

### ISSUE THREAD

**Issue by hmax42** [Atmosphere-NX/Atmosphere#682]
i am using atmosphere 0.9.4 on ofw 9.0.1

the game carts darkside detective and voez (both touch enabled) do not accept inputs via the joycons. only home works. i did not test the screenshot function.
the game cart witcher 3 produces a popup during the second screen (the logos)
"The software was closed because an error occured."
with a button, which pressed exits the game

all 3 bugs do not happen if i run the game carts natively under 9.0.1 without atmosphere.

**Comment by SciresM** [comment]
Please re-open using issue templates.

The controls thing sounds like other sysmodules interfering, so try removing custom sysmodules.
