### ISSUE TITLE
Updated to 8.1.0 with ChoiDujourNX and atmosphere crash

### ISSUE THREAD

**Issue by MarxRoyal** [Atmosphere-NX/Atmosphere#685]
So, I was updating my switch to 8.1.0 before 9.0.1 beacause I wanted to see if there was glitches.

I make the update, I re-enable auto rcm that I have diabled before the update in ChoiDujourNX.
I start my switch with fusee primary payload and after the Nintendo Switch logo, Atomsphere crash screen with hexadecimal numbers, etc...

I have made the Update from 7.0.1 to 8.1.0(exFAT) and I have a microSDcard with exFAT format.

Can someone help me please !
![IMG_20191020_183427](https://user-images.githubusercontent.com/46058202/67162880-073c0380-f369-11e9-94fa-80d0eccdfae4.jpg)

**Comment by SciresM** [comment]
Remove your custom theme by deleting the /atmosphere/titles/0100000000001000 folder.
