### ISSUE TITLE
Don't swith to local wireless

### ISSUE THREAD

**Issue by Bocelli** [Atmosphere-NX/Atmosphere#688]
### What's the issue you encountered?

 Trying to play local wireless with Digimon and Puyo Puyo Tetris the console does not switch to local wireless giving error "network error". </br>

### How can the issue be reproduced?

After starting the game, I tried to play with a friend on a local wireless, but it continues to fail. If I am connected to my home connection in Wifi, it simply does not switch to the local (it does not even change the wifi icon). If it's not connected to wifi, the games give me "network error".</br>

### Crash Report

N/A</br>

### System Firmware Version

8.1.0</br>
Atmosphere 0.9.4 on Emunand

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate Bootloader latest version, but I tried also with fusee-primary
- Official release or unofficial build: Official 0.9.4
- Do you have additional kips or sysmodules you're loading:  No
- Homebrew software installed: Hbl latest version.

### Additional context?

N/A

**Comment by SciresM** [comment]
(local wireless works fine for me in pokemon shield).
