### ISSUE TITLE
Fatal error FW 9.0.1

### ISSUE THREAD

**Issue by mint-xoxo** [Atmosphere-NX/Atmosphere#690]
When i try and start my switch on FW 9.0.1 i get a fatal error when running Atomosphere.

I have attached the crash dumb and a picture of the switch .

[fatal_errors.zip](https://github.com/Atmosphere-NX/Atmosphere/files/3778308/fatal_errors.zip)
![IMG_0087](https://user-images.githubusercontent.com/21077832/67673471-10812d80-f972-11e9-8a90-5822a425182c.jpg)

**Comment by fincs** [comment]
Title ID looks non-official. Please remove all custom sysmodules and try again.

**Comment by Dcnigma** [comment]
I removed title 00FF747765616BFF and it's working again, I accidentally updated to 9.0.1
and the Title ID is from  supernag patcher for BrowseNX by @crc-32
