### ISSUE TITLE
does the latest relese support 9.0.1 ??

### ISSUE THREAD

**Issue by saltybutter24** [Atmosphere-NX/Atmosphere#692]
hey guys im wondering if the latest version suports the system version 9.0.1 i was looking at the reslese notes and it said 9.0.0 added support. and after i looked in the issues someone said they where running 9.0.1 with the latest relese. 

regards salty

**Comment by N3MIS15** [comment]
Yes. https://twitter.com/SciresM/status/1178828607931613184?s=20

**Comment by saltybutter24** [comment]
> Yes. https://twitter.com/SciresM/status/1178828607931613184?s=20

thank you so much
