### ISSUE TITLE
emummc corruption whit reboot to payload

### ISSUE THREAD

**Issue by takashi1kun** [Atmosphere-NX/Atmosphere#699]
The reboot to atmosphere feature seems to corrupt the emummc partition if done from the emummc, it does not happens usually but it had happen 2 times already for me, the two times i rebooted to payload and the emummc corrupted and was unable to boot, i had to recreate it, also this is happening with a sd whit FAT32.

If there is any log file i can upload to see what happens tell me.

The first time it corrupted it was not able to boot past the atmosphere black and white logo, and the second time it corrupted it was not able to boot past the nintendo logo, last atmosphere version firmware 8.1.0

This is related whit this issue https://github.com/Atmosphere-NX/Atmosphere/issues/650 this is the first time it corrupted to me, i had a different atmosphere version and firmware version

**Comment by friedkeenan** [comment]
Are you using file-based emuMMC? Because if so, uh, don't; use partition based.
