### ISSUE TITLE
Just Updated Atmophere, Error Desc: Data Abort (0x101)

### ISSUE THREAD

**Issue by kriemhild3ds** [Atmosphere-NX/Atmosphere#708]
hello, first time updating Atmosphere, I´m doing something wrong?
I put the new files on the sd, and I´m using the new fusee-primary.bin in TegraRCM
I tried on 2 different switch and I got the same error, what should I do!? please helpp

**Comment by kriemhild3ds** [comment]
"Atmosphere can now display a fatal error screen significantly earlier in the boot process, if things go wrong early on."

what does this mean? I´m getting this screen :(

**Comment by SciresM** [comment]
Please use the issue templates in the future. I've got a report of this elsewhere, though -- it looks like a custom theme triggered problem.

Delete your custom theme for a quick fix, or wait for a bug hotfix.

**Comment by kriemhild3ds** [comment]
Just unistalled the custom themes on my switch and I got the same error :(, I put the old files and it works normally
the other switch doesnt have any custom themes installed and its on 9.1.0, and I get the same error :( I´m sorry x.x

**Comment by SciresM** [comment]
Custom theme files are at /atmosphere/contents/0100000000001000. You may not have deleted the right folder.

**Comment by kriemhild3ds** [comment]
thanks it works now, that was the problem I was unsinstalling the theme on NXThemes Installer and I had to do it deleting the folder you just said, thank you so much!!

**Comment by kriemhild3ds** [comment]
on the console on 9.1.0 I keep getting a crash after 10 seconds on CFW, I run HB through the album and everything works perfect, but after 10 seconds it crashesss x.x

**Comment by kriemhild3ds** [comment]
![image](https://user-images.githubusercontent.com/58643706/70382571-2c96c800-193d-11ea-8061-7f68f7e686fa.jpg)

😭

**Comment by SciresM** [comment]
Delete the custom system module ^^

**Comment by poketradecenter** [comment]
hi please can you help me im unsure of what to do i downloaded all the files for 9.1 but not sure where to put them on my sd card ?? could you please explain to me what to do
