### ISSUE TITLE
Atmosphere v0.10 Will Not Boot in Firmware 8.1.0

### ISSUE THREAD

**Issue by dothackjhe** [Atmosphere-NX/Atmosphere#709]
### What's the issue you encountered?

Tried updating to the latest version of Atmosphere (version 0.10), but found it unable to boot. Never had this issue using Atmosphere v0.94.</br>

### System Firmware Version

8.1.0</br>

**Comment by dothackjhe** [comment]
I reverted to using the files for Atmosphere 0.9.4 and everything worked perfectly again.

**Comment by friedkeenan** [comment]
I can boot successfully on 8.1.0. Disable any sysmodules you might have running and please give more information than "I can't boot"

**Comment by dothackjhe** [comment]
I do not know how to put it differently. 

Initially, it got stuck after the Kosmos splash screen. My second attempt, on the other hand, loops me back to the screen where I get to choose to boot the system into CFW (Sysnand) [I do not know how this part of the system is called, TBH].

**Comment by SciresM** [comment]
This sounds like "hekate doesn't support 9.1.0 yet" to me.

**Comment by dothackjhe** [comment]
Sounds likely.

**Comment by dothackjhe** [comment]
The latest update of Hekate addressed the issue for me.
