### ISSUE TITLE
Game Carts not readable on v0.10.0

### ISSUE THREAD

**Issue by xgorinx** [Atmosphere-NX/Atmosphere#710]
### What's the issue you encountered?

Updated atmosphere to 0.10.0, but physical game carts can not be read.  

### How can the issue be reproduced?

Updated BCT.ini text with nogc = 0, but still having same issue

### System Firmware Version

9.1.0

### Environment?

fusee primary

### Additional Information
BCT.ini

BCT0
[stage1]
stage2_path = atmosphere/fusee-secondary.bin
stage2_mtc_path = atmosphere/fusee-mtc.bin
stage2_addr = 0xF0000000
stage2_entrypoint = 0xF0000000

[exosphere]
; Note: Disabling debugmode will cause parts of ams.tma to not work, in the future.
debugmode = 1 
debugmode_user = 0
; Note: Disabling usermode exception handlers will cause atmosphere to not fail gracefully under error conditions.
; Support will not be provided to users who disable these. If you do not know what you are doing, leave them on.
disable_user_exception_handlers = 0

[stratosphere]
; To force-enable nogc, add nogc = 1
; To force-disable nogc, add nogc = 0
nogc = 0

**Comment by SciresM** [comment]
You probably edited the wrong file. 

BCT.ini is no longer stored in /atmosphere, it's stored in /atmosphere/config.

**Comment by xgorinx** [comment]
Thank you @SciresM, that worked!  Should I delete the extra BCT.ini that is just in /atmosphere, or leave it?
