### ISSUE TITLE
atmosphere 0.10.0 +master-7e6ff1f3+hbl-2.2+hbmenu-3.1.1  album applet  freeze FW 4.1 emuMMC

### ISSUE THREAD

**Issue by alimao10** [Atmosphere-NX/Atmosphere#712]
master-7e6ff1f3+hbl-2.2+hbmenu-3.1.1 album applet  freeze FW 4.1 emuMMC

**Comment by SciresM** [comment]
Please re-create this issue using the issue templates. I have no idea what you're saying.

Also, please download the updated pre-release binary, an issue was fixed involving memory corruption.
