### ISSUE TITLE
Fatal Error While Rebooting Atmosphere

### ISSUE THREAD

**Issue by AlinMGupta** [Atmosphere-NX/Atmosphere#713]
### What's the issue you encountered?

When Rebooting atmopshere using the reboot to payload NRO in the homebrew menu, i got the error:
A Fatal Error occured when running Atmosphere.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)
Press Power to reboot.

Before hand i installed the FTPD service which i tested and worked. 

### Crash Report

[report_000000000fa4718a.zip](https://github.com/Atmosphere-NX/Atmosphere/files/3935827/report_000000000fa4718a.zip)

### System Firmware Version

Switch 9.1.0</br>

### Environment?

- Hekate, Using the FuseePrimary.bin file:
- Official release or unofficial build: 
  - Atmopshere Official release version 10
 

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]
I Can boot to Hetake by holding the power button, but using fusee primary sends me back into the loop.

I can also boot to stock by removing the SD card as trying to do it through Hetake doesnt do anything.

When i press power it gives me the same error.

**Comment by NWPlayer123** [comment]
for the bin, if you're on Windows, you can right click, send to -> zipped folder and GitHub will let you upload the zip
![Screenshot_420](https://user-images.githubusercontent.com/3280345/70383813-6c57b280-1931-11ea-8672-8b0d9234d316.png)

**Comment by SciresM** [comment]
What exactly did you do to trigger this problem?

**Comment by AlinMGupta** [comment]
Thanks NWPlayer123

ScieresM,
I used the reboot to payload Button in the Homebrew menu.

**Comment by AlinMGupta** [comment]
Heres a strange thing. I installed ULaunch before using the button, and deleted it afterwards incase that was the problem. but the folder keeps appearing again, when plugged into the switch.

**Comment by NWPlayer123** [comment]
are you using FAT32 or exFAT?

**Comment by AlinMGupta** [comment]
I am using FAT32.

**Comment by SciresM** [comment]
Cannot reproduce. I successfully used the reboot to payload with no problems twice in a row just now.

**Comment by AlinMGupta** [comment]
> Cannot reproduce. I successfully used the reboot to payload with no problems twice in a row just now.
Can you provide a fix for my switch? i cant use home-brew at this rate.

**Comment by SciresM** [comment]
1) Make sure you're using a clean copy of atmosphere from the release branch

2) What do you even need reboot to payload for? Atmosphere provides a mitm so that just selecting reboot from the power menu does a reboot to payload, to the NRO is basically completely superfluous.

**Comment by AlinMGupta** [comment]
> 1. Make sure you're using a clean copy of atmosphere from the release branch
> 2. What do you even need reboot to payload for? Atmosphere provides a mitm so that just selecting reboot from the power menu does a reboot to payload, to the NRO is basically completely superfluous.

1. I am, should i just reinstall?
2. Thanks, i did not know this, will take note for the future.

**Comment by SciresM** [comment]
I would try re-installing -- I can't reproduce your problem at all though

**Comment by AlinMGupta** [comment]
> I would try re-installing -- I can't reproduce your problem at all though
Okay thanks.

**Comment by AlinMGupta** [comment]
> I would try re-installing -- I can't reproduce your problem at all though

Sorry to bother you, but after some testing, i have linked the problem to ULaunch. There is already an issue open on their feed, but maybe warn people that something as widely used as it causes a fatal error on startup.
