### ISSUE TITLE
0.10.0 crashes in EdiZon>Cheats

### ISSUE THREAD

**Issue by Nomercyman1** [Atmosphere-NX/Atmosphere#715]
### What's the issue you encountered?

Opened EdiZon to use its Cheats (RAM Editor) and the system crashed to a blue error screen.

### How can the issue be reproduced?

Open EdiZon, with game open. Go to Cheats.

### Crash Report
https://gist.github.com/Nomercyman1/53b8f8cb80de74ff3e9010aef4ecf73e

### System Firmware Version

0.9.1</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
fusee
- Official release or unofficial build: 
0.10.1 Atmosphere from site
- Do you have additional kips or sysmodules you're loading:
No
- Homebrew software installed: [ * ]
EdiZon, Checkpoint, App Store

### Additional context?

- Additional info about your environment:

**Comment by SciresM** [comment]
This is an edizon problem, not an atmosphere problem. WerWolv is aware.
