### ISSUE TITLE
0.10.0 failed to boot. Error 2003-0008 (0x1003)

### ISSUE THREAD

**Issue by DitDitGitHub** [Atmosphere-NX/Atmosphere#716]
### What's the issue you encountered?

An error code on the boot screen after trying to update Atmosphere. Error code is: 2003-0008 (0x1003) and the program is 010000000000100C. I am on FW 9.0.1.

### How can the issue be reproduced?

1. Install Atmosphere 0.10.0 files over 0.9.4 files.
2. Using the fusee-primary payload, boot into Atmosphere, either inside or outside of Hekate.
3. Receive the error.

### Crash Report

[01575795127_010000000000100c.log](https://github.com/Atmosphere-NX/Atmosphere/files/3936007/01575795127_010000000000100c.log)

### System Firmware Version

9.0.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
      TegracmGUI and Hekate.
- Official release or unofficial build: 
      Official release 0.10.0
- Do you have additional kips or sysmodules you're loading:
      No, I have uninstalled them.
- Homebrew software installed: [ AmiiSwap, AppStore, Checkpoint, Goldleaf, HekateBrew, Incognito, KipSelect, LDNMitm Config, MMLinx, NX-Activity-Log, NX-Shell, SwitchPresence,Rewritten, Sys-Clk Editor, Tinfoil, VGEdit, FTPD, Retroarch.]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by DitDitGitHub** [comment]
I can confirm that downgrading to Atmos 0.9.4 works.

**Comment by SciresM** [comment]
This is an error due to custom sysmodules.

**Comment by DitDitGitHub** [comment]
Yeah, I just realized that I didn't delete the sysmodules. I'm gonna try again.

**Comment by DitDitGitHub** [comment]
I've deleted the sysmodules from the titles folder, still doesn't work.

**Comment by SciresM** [comment]
you need to delete from the contents folder. Atmosphere no longer uses the titles folder.

**Comment by pixel-stuck** [comment]
titles was moved to contents now. Read the release notes; a small utility was added to move the titles foleder's contents into contents, so you'll have to delete the contents folder.

**Comment by DitDitGitHub** [comment]
Ok

**Comment by DitDitGitHub** [comment]
After deleting the folders from content, I don't get to the Nintendo Switch screen.

**Comment by SciresM** [comment]
You don't want to delete every folder -- some of them are atmosphere's system modules. Delete folder, extract clean latest release zip.

**Comment by DitDitGitHub** [comment]
Ok

**Comment by DitDitGitHub** [comment]
Thank you, it has worked ! :)
