### ISSUE TITLE
(9.1.0) Fusee Primary boots into black screen

### ISSUE THREAD

**Issue by RowanHall** [Atmosphere-NX/Atmosphere#718]
### What's the issue you encountered?

After injecting `fusee-primary.bin` (latest, from /releases) the backlight turns on, but the lcd displays black. If the power button is pressed, the backlight turns off, then after a short delay turns back on. (it should be noted that the windows disconnect sound plays from my laptop, and TegraRCMGUI (v2.6) displays NO RCM.

This black screen does not go away untill the switch is force shut-down by holding the power button.

### How can the issue be reproduced?

1. Boot switch into RCM.
2. Inject fusee-primary

### Crash Report

The folder crash_reports does not exist.

### System Firmware Version

9.1.0</br>

### Environment?

fusee (v latest, atmos release 0.10.0)

### Additional context?

Note the SD card is inserted.

**Comment by Webbeh** [comment]
Exactly the same here.
SD card formatted as exfat.

**Comment by RowanHall** [comment]
I don't get any splashes, it just directly goes to black

**Comment by Webbeh** [comment]
Launching it with Fusee-Primary gets splashes and blackscreen.
Launching it from Hekate just reboots straight to hekate.

**Comment by RowanHall** [comment]
mine goes directly to black with the effects i provided above, weather or not i launched directly or through hekate.

**Comment by SciresM** [comment]
@RowanHall this sounds like a "your SD card doesn't have fusee-secondary" problem.

Extract clean release zip to SD?

**Comment by death2all110** [comment]
Getting a black screen when booting 0.10.0 from Hekate 5.1.0. Nothing in fatal_errors, no crash reports directory. SDCard is in exfat format.

**Comment by ELY3M** [comment]
can you try deleting sept folder and replace with new sept folder from atmosphere zip?

**Comment by death2all110** [comment]
I think i may have attempted that , but I'll give it a shot after work. Thanks.

**Comment by death2all110** [comment]
Ok. so tried deleting sept and copying again. same issue.

**Comment by SciresM** [comment]
@death2all110 send picture of the root of your SD card, and of your atmosphere folder?

**Comment by death2all110** [comment]
Sure. Here you go:

Also, i guess its not really a black screen but its actually turning the switch off.

![Screen Shot 2019-12-09 at 8 09 24 PM](https://user-images.githubusercontent.com/1055037/70488965-ec138780-1abf-11ea-84e9-9cb629c839a4.png)
![Screen Shot 2019-12-09 at 8 09 14 PM](https://user-images.githubusercontent.com/1055037/70488966-ec138780-1abf-11ea-8008-5aceb8e563fb.png)

**Comment by SciresM** [comment]
>macOS

It's almost certainly an archive bit problem.

Use hekate's archive bit fixer?

**Comment by death2all110** [comment]
Son of a b*tch. 

I am so sorry. I completely forgot about all that.

**Comment by relativenukes** [comment]
I have the exact same issue as RowanHall.
Switch version 9.1.0
Everything is on the newest update
When I try to boot the Fusee primary payload, the screen stays on and black. Pressing the power button turns screen off temporarily.
Any help would be appreciated, thanks.

**Comment by burgerkingrei024** [comment]
> > macOS
> 
> It's almost certainly an archive bit problem.
> 
> Use hekate's archive bit fix

Using the bit fix was what caused the issue for me

**Comment by TheDiggleGod** [comment]
It seems I have the exact same problem as described in the OP. 

Something he didn't mention that I think might be helpful, is when I try to launch through Hekate's CFW (emuMMC) some text appears saying "unknown pkg1 version. failed to launch HOS." And when I inject fusee-primary, either via hekate or TegraRCMGUI, the screen cuts off, and it'll turn out, but the screen is still black.

I've tried the archive bit fix and reinstalling hekate and atmosphere, but I'm still having the problem.

**Comment by tklitschi** [comment]
I had the same Problem after updated my atmosphere. I'm using FAT32. After updating my atmosphere directly via PC and updated hole boot loader I got it kinda working again, but my switch didn't found any game. 
After formatting hole SD Card I got it working again.

**Comment by hscuddera** [comment]
My advice when it comes to issues like these is to redownload all the standard SD setup type stuff. Then go through your sd card and replace the maximum u can without getting rid of stuff that looks different. Then try to boot switch.

**Comment by Zaneoi** [comment]
Im having a similar issue to, i can boot to emummc through hekates configs but i cant boot using fusee primary from payloads or by using tegrarcmgui on my pc. Every time i try its just a splash screen then black screen with a backlight.

**Comment by keinushi** [comment]
Installed atmosphere 0.18.0 and it booted right up. Been having issues with 0.16.2 since I installed it, this seemed to fix everything.

**Comment by makermelissa** [comment]
> > macOS
> 
> 
> It's almost certainly an archive bit problem.
> Use hekate's archive bit fix

I'm new to this and I was having the same issue after formatting to ExFat on MacOS. This fixed it for me as well. Thanks for the suggestion.
