### ISSUE TITLE
Error atmosphere 0.10.0

### ISSUE THREAD

**Issue by Yasss91** [Atmosphere-NX/Atmosphere#721]
### What's the issue you encountered?

I can't launch atmosphere 0.10.0. The error code is 2168-0002.

### System Firmware Version

9.1.0

**Comment by fincs** [comment]
Still not the issue template. Please fill out every single field in the issue template and try again.

https://raw.githubusercontent.com/Atmosphere-NX/Atmosphere/master/.github/ISSUE_TEMPLATE/bug_report.md

Feel free to post a followup comment with this template completely filled in.
