### ISSUE TITLE
Fatal Error: Unable to read (fusee-secondary.bin) 

### ISSUE THREAD

**Issue by RoyallyOblivious** [Atmosphere-NX/Atmosphere#723]
I get this error message pop up, i don't know what to do and I've exalted everything I could come up with.
![8E815538-4A07-461D-8AB1-BC1C5DCFEAC6](https://user-images.githubusercontent.com/58615377/70391644-6b606880-19a5-11ea-968f-b3bd2e439109.jpeg)

**Comment by SciresM** [comment]
Make sure the release zip is extracted to your sd card...?

**Comment by RoyallyOblivious** [comment]
I have it in my SD card, but it won't load it, I'm not really good at doing this, I'm new to this

**Comment by SciresM** [comment]
What does the atmosphere folder on your SD look like? Post a screenshot.

**Comment by RoyallyOblivious** [comment]
![03D466F6-C743-4852-98B6-CD6E35AED51E](https://user-images.githubusercontent.com/58615377/70394360-7f669300-19c2-11ea-8740-c167e33b61bb.jpeg)

**Comment by shchmue** [comment]
move everything from the `sd` folder onto the root of your sd

**Comment by SciresM** [comment]
You need to extract to the root of your sd card, not a "sd" folder.

**Comment by RoyallyOblivious** [comment]
I already did that too

**Comment by RoyallyOblivious** [comment]
![Uploading 936A4666-2985-45C5-A81C-6A1C8380B163.jpeg…]()
