### ISSUE TITLE
Atmosphere crashes after the switch logo when loading emunand

### ISSUE THREAD

**Issue by flopglop** [Atmosphere-NX/Atmosphere#724]
### What's the issue you encountered?

After installing atmosphere and loading fusee-primary.bin atmosphere crashes after the switch logo with the error code 0x149402 (2002-2634) when booting from Emunand.

### How can the issue be reproduced?

1. Boot switch into RCM.
2. Enable Emunand.
3. Inject (or chainload) fusee-primary.bin.

### Crash Report

https://gist.github.com/flopglop/1d76c88be710cff4e621c50fdd603c15

### System Firmware Version

8.1.0 Emunand
9.1.0 Sysnand

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
This issure occurs both when loading fusee-primary.bin or chainloading it.

- Official release or unofficial build: 
Official release version 0.10.0.

### Additional context?

The switch boots to recovery mode, and I use a partition based Emunand.

Edit: This also happens with Atmosphere 0.9.4 with sigpatches
https://gist.github.com/flopglop/3fa08359f793ddda5c7a3672f6277f0d (0.9.4 crash report)

**Comment by EdwardElric64** [comment]
Same issue here. Loading hekate and trying to boot cfw from SysNAND just crashes back to the payload

**Comment by Koha1297** [comment]
> Same issue here except I get a different error code. Loading hekate and trying to boot cfw from SysNAND just crashes back to the payload

Hekate doesn't support 9.1.0 yet. Booting SysNand or Stock will revert back to Hekate.
https://github.com/CTCaer/hekate/issues/314

**Comment by SciresM** [comment]
This error code means you don't have nogc enabled and are booting into a version with incompatible gamecard firmware.

Turn on nogc.
