### ISSUE TITLE
Firmware 9.1.0 Atmosphere 0.10 crashes on start, error code 2168-0002

### ISSUE THREAD

**Issue by EdwardElric64** [Atmosphere-NX/Atmosphere#725]
I had updated the switch firmware to use the built in browser used by Goldleaf, and updated to atmosphere 0.10 as I heard that 9.1 broke cfws and that the new atmosphere update added support for firmware 9.1, but upon installation of this cfw update it boots into the cfw, all seems fine, until it crashes right after the initial switch logo on startup with the error code as said in the title. I had never setup emmuNAND so I've just been booting from SysNAND if that adds anything

**Comment by SciresM** [comment]
Please use the issue templates.

Help cannot be provided if you do not upload your crash reports.
