### ISSUE TITLE
Fatal error when booting up

### ISSUE THREAD

**Issue by MegaSuperab** [Atmosphere-NX/Atmosphere#726]
### What's the issue you encountered?

Booting up Atmosphere causes a fatal error to occur. The only changes made to Atmosphere were changing the applet override key to R and changing the cheat enable key to X.

### How can the issue be reproduced?

1. Boot up Atmosphere

### Crash Report

A fatal error occured in this issue, so I will provide the bin file here.  [report_00000000175078b0.zip](https://github.com/Atmosphere-NX/Atmosphere/files/3936553/report_00000000175078b0.zip)

### System Firmware Version

9.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Both fusèe and hekate were tested
- Official release or unofficial build: Official release 0.10.0
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: I'm honestly too lazy to list them all in text so here's an image instead:
![image](https://user-images.githubusercontent.com/7158344/70392490-3bfe2b80-19a6-11ea-9f95-d26519ce774f.png)
uLaunch v0,2 is also installed.

### Additional context?

- Additional info about your environment: I'm using FAT32 this time.

**Comment by SciresM** [comment]
The crash is happening due to an assertion failure in romfs building code.

Do you have a custom theme? I suspect it may be corrupted.

Could you post your /atmosphere/contents folder?

**Comment by MegaSuperab** [comment]
After a quick test I found out that uLaunch was causing the issue. Uninstalling it makes Atmosphere work correctly. Thank you for your help.
