### ISSUE TITLE
 fsmitm remains always active 

### ISSUE THREAD

**Issue by Kronos2308** [Atmosphere-NX/Atmosphere#727]
## Bug Report

fsmitm remains active even if fsmitm.flag does not exist

### What's the issue you encountered?
These are the files I have
"atmosphere\contents\0100000000001000\romfs\lyt\Flaunch.szs"
"atmosphere\contents\0100000000001000\romfs\lyt\ResidentMenu.szs"
"atmosphere\contents\0100000000001000\romfs\lyt\Notification.szs"
and 
"atmosphere/contents/0100000000001000/fsmitm.flag" 
should enable and disable the fs
also try "atmosphere/contents/0100000000001000/flags/fsmitm.flag"

even if you delete the .flag it always remains active

### System Firmware Version
9.1.0
### Environment?
fuse primary

**Comment by SciresM** [comment]
This isn't a bug, it's intended behavior.

Qlaunch should always be redirected.

**Comment by Kronos2308** [comment]
ok

**Comment by SciresM** [comment]
(this is, I believe, also how it worked on 0.9.4.)

**Comment by Kronos2308** [comment]
but if you use custom themes is a problem ,
cant we have a flag to disable ?

**Comment by SciresM** [comment]
Rename the romfs directory...?

The flags were complicated for no real benefit.

**Comment by Kronos2308** [comment]
ok, thanks
i will rename then
