### ISSUE TITLE
Game with a mod installed freezes just after launch

### ISSUE THREAD

**Issue by JaviSS4** [Atmosphere-NX/Atmosphere#730]
**What's the issue you encountered?**
After (accidentally updating to 9.10) and installing the latest Atmosphere, a game (The Witcher 3) with a mod installed (Enhanced settings) now causes my switch to freeze just after lunch, during the "Licensed by Nintendo, Nintendo Switch" logo black screen.

**System Firmware Version**
9.1.0

**Environment?
What bootloader (fusèe, hekate, etc) was Atmosphère launched by:**
Fusee

**Official release or unofficial build:**
Official release version 0.10.0.

**Comment by SciresM** [comment]
This issue was fixed yesterday. Please re-download the updated release binary.
