### ISSUE TITLE
Mods in titles folder disappear

### ISSUE THREAD

**Issue by breckin** [Atmosphere-NX/Atmosphere#732]
### What's the issue you encountered?

I will run a mod for some time and after a little bit the whole titleid in titles will disappear, but the mod still runs and I need to reinstall to revert it
Multiple reinstalls, yes.
Added titles folder for mods

### How can the issue be reproduced?

Add titles folder add titleid (I ran splatoon 2), add the mod, play the mod go, to change the mod, then the titleid is gone

### Crash Report

None

### System Firmware Version

9.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: fusèe
- Official release or unofficial build: official 0.10.0
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed: new to this so I don’t know

### Additional context?

- Additional info about your environment: none

**Comment by SciresM** [comment]
Atmosphere no longer uses the titles folder. Mods now go in the contents folder. What you're seeing is atmosphere automatically moving folders from the titles folder to the contents folder when it can.
