### ISSUE TITLE
Unable to identify package1 

### ISSUE THREAD

**Issue by RoyallyOblivious** [Atmosphere-NX/Atmosphere#734]
I had posted earlier about the fusee-secondary file not being read, now it is saying that it is unable to to identify package1

**Comment by SciresM** [comment]
@RoyallyOblivious it really sounds to me like you're not actually using the latest release fusee-primary + fusee-secondary. Please make sure you're using the latest release binaries...

**Comment by RoyallyOblivious** [comment]
I am using Tegra to go into CFW, is that an issue?

**Comment by NWPlayer123** [comment]
You need the latest payload, along with the latest Atmosphere release. I'd recommend
* backing up SD:/atmosphere and SD:/sept
* deleting those folders
* deleting your old Tegra atmo payload
* grabbing zip + fusee-primary from https://github.com/Atmosphere-NX/Atmosphere/releases/tag/0.10.0
* extracting the whole zip to your SD card to get the latest atmo/sept files
* using latest fusee-primary with Tegra

**Comment by RoyallyOblivious** [comment]
@NWPlayer123 

What's atmo and I'm using the recent release of Tegra to load the CFW, I already have entered the RCM on the switch, but I'm having no luck

**Comment by NWPlayer123** [comment]
latest version of Atmosphere. You need to update sd:/atmosphere, sd:/sept, and the xxx.bin file you use with Tegra *every time an update comes out*
![Screenshot_426](https://user-images.githubusercontent.com/3280345/70400698-6f15de80-19e9-11ea-92c4-298f898e0365.png)
![Screenshot_429](https://user-images.githubusercontent.com/3280345/70400914-6eca1300-19ea-11ea-987e-b1d4ef60e77d.png)
![Screenshot_428](https://user-images.githubusercontent.com/3280345/70400835-18f56b00-19ea-11ea-9dbc-374c2652cb66.png)

**Comment by RoyallyOblivious** [comment]
I got the atmosphere screen up and then it goes to the nintendo logo after it loads, is that normal, what else should i do? This is the farthest I have gotten, so now what else do I need to do?

**Comment by NWPlayer123** [comment]
That's normal, after that it should just boot same as a normal Switch. Did it pop up with a crash log or make a file or something?

**Comment by RoyallyOblivious** [comment]
@NWPlayer123 nope, so what do I do to access the home brew and to edit my game data?
