### ISSUE TITLE
Error Code: 2162-0002 (0x4a2)

### ISSUE THREAD

**Issue by EnriqueJuarez918** [Atmosphere-NX/Atmosphere#735]
I installed the new atmosphere release for 9.1.0 with the new files and fusee- primary but now it wont boot to cfw. the error code above shows up and now it doesnt even load to the main menu. something im doing wrong?

**Comment by SciresM** [comment]
Use the issue templates.

**Comment by SciresM** [comment]
(Please do not create reports about error codes without uploading the crash reports, too)
