### ISSUE TITLE
2168-0002 ox4a8

### ISSUE THREAD

**Issue by BNWEIN** [Atmosphere-NX/Atmosphere#743]
### What's the issue you encountered?

Regularly getting error 2168-0002 ox4a8 </br>

No changes made to Atmosphère itself? </br>

### How can the issue be reproduced?

HB App Store, then clicking on Retro Arch, and then trying to download. 2 seconds into the download i get the error above

### Crash Report

https://gist.github.com/BNWEIN/7fc066ab9f19acc4a057a4eebf53c1d2
</br>

### System Firmware Version

9.0.1

### Environment?

- Hekate Bootloader
    - Ex: Kosmos' distribution of Atmosphère 
- Do you have additional kips or sysmodules you're loading: No
- Homebrew software installed:  None

**Comment by SciresM** [comment]
"HB App Store"

Not an atmosphere issue, also homebrew app store is not supported.
