### ISSUE TITLE
(Help) [ERROR] Fatal error: Failed to stat stage2 (atmosphere/fusee-secondary.bin)!

### ISSUE THREAD

**Issue by ziraw** [Atmosphere-NX/Atmosphere#745]

**Comment by ziraw** [comment]
oh it glitched i wanted t owrite something but anyway:
so i forgot to put my sd card in my switch and injcected the payload from TegraRcmGUI without having my sd card in now its stuck there after i out my sd card in while it was in rcmMode...
pretty stupid right?
what can i do now to boot atmosphere or even boot my switch in deafult settings? pls help
thanks in advanve to you guys

**Comment by ziraw** [comment]
aslo tegraRcm doesnt regognize my switch anymore (while in rcm)

**Comment by ziraw** [comment]
It suddenly bootet........

**Comment by ziraw** [comment]
yeah...
its stuck in rcm and its saying this found nothing that helped

**Comment by optimism247** [comment]
I can boot with fusee-primary.bin, but I can't launch in with the Hetake "Launch" function.

**Comment by lamecake** [comment]
Had the same problem, the SD Card was not formatted properly (with the partition set to Primary and as FAT32), that fixed it for me.

**Comment by ziraw** [comment]
yeah i havbe save files from a year ago on there so i cant format it :/

**Comment by optimism247** [comment]
Can you not copy those files over? Or are they not saved onto the Switch itself?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ziraw** [comment]
yeah probably..
can copy them over then install atmosphere and then copy them back?

**Comment by ziraw** [comment]
I just want acustom background thats it btw 
no harder modding

**Comment by SciresM** [comment]
This is a user error. Seek help in the reswitched discord

**Comment by ziraw** [comment]
wt*? what?

**Comment by SciresM** [comment]
GitHub issues are for fixing atmosphere bugs, not for providing support.

**Comment by ziraw** [comment]
so where am i supposed to find support?

**Comment by el-emmo** [comment]
The ReSwitched Discord would be a place to ask (as Scires mentioned above).
