### ISSUE TITLE
Atmosphère 0.10.0 cheats always enabled and confused about the new setting structures

### ISSUE THREAD

**Issue by wisnumurti1993** [Atmosphere-NX/Atmosphere#746]
I just updated my switch to Atmosphère 0.10.0. In the previous version system_settings.ini I disable dmnt_cheats_enabled_by_default = u8!0x1 to dmnt_cheats_enabled_by_default = u8!0x0 so the cheats not enabled by default. But in Athmosphere 0.10.0 my cheats always enabled by default. I tried to change the system_settings.ini in /atmosphere/config_templates directory and copy it to /atmosphere/config but the cheats still enabled by default. I tried to put it in /atmosphere folder but still the same. Are they anything that I can do to override the default setting? Thanks

**Comment by SciresM** [comment]
Edit /atmosphere/config/system_settings.ini.
