### ISSUE TITLE
Cheats

### ISSUE THREAD

**Issue by RoyallyOblivious** [Atmosphere-NX/Atmosphere#747]
I copied the cheat codes to the root, so EdiZon can read it, but it says it's there, but region and title are wrong, is there a way for it to read the cheats?

**Comment by SciresM** [comment]
Seek support for Edizon, not atmosphere. Also, use the issue templates, and also this is for reporting atmosphere bugs not for seeking support.

Make sure you're using the latest release binary.

**Comment by WerWolv** [comment]
For people having that issue in the future, update Atmosphere! This was a dmnt:cht issue but it has been fixed since. Redownload Atmosphere again!
