### ISSUE TITLE
Games don't load AT ALL in emuMMC 0.10.1.

### ISSUE THREAD

**Issue by IAmArique** [Atmosphere-NX/Atmosphere#754]
I'm running Atmosphere 0.10.1 on 9.1.0. When I try to open a physical or (legally purchased) digital game while in emuMMC, the Switch locks up and I have to force shutdown the console, and doesn't give me a crash report since I just get a blank screen every time. The same thing happens if I try loading hbmenu while selecting a game.

**Comment by fincs** [comment]
Do you have exFAT?

**Comment by IAmArique** [comment]
Yes, I have exFAT. I'm using the RCMLoader dongle to load Atmosphere rather than hooking it up to my PC every time.

**Comment by fincs** [comment]
Nintendo's exFAT driver is known to be bad & cause corruption issues. Please try with FAT32 as a troubleshooting step. Also, please answer the other questions (I edited my post, sorry if you didn't see it).

**Comment by IAmArique** [comment]
Ok, I'll try changing my card to FAT32 and see if that works. I'll edit this comment once I test it.

As for the distribution, I downloaded Atmosphere from here on the Github page. I didn't get it from anywhere else.

**Comment by fincs** [comment]
Alright. One more thing - file based emuMMC is known to be slower and less reliable. For the best chance of success, make sure you're using partition based emuMMC.

**Comment by SciresM** [comment]
This was an issue with SaltySD/ReverseNX.
