### ISSUE TITLE
Hombrew menu not lauching

### ISSUE THREAD

**Issue by Burgos91** [Atmosphere-NX/Atmosphere#757]
After Updated to 10.1 even to the recently one everytime I try to launch hombre menu i give me this message:
Error:assetsInit() failed 0x80.
press the + button to exit.

**Comment by fincs** [comment]
It looks like you have corruption of some sort. Please redownload and reextract Atmosphère direct from the official release. Also, if you have an exFAT formatted SD card, it might be related (exFAT is known to cause corruption issues), switch to FAT32 if you haven't already.

**Comment by Burgos91** [comment]
I did now im making a backup to do a clean install and see if fix the problem and my SD is a 128gb ill have to do use a program to formated right?

**Comment by fincs** [comment]
Yeah. I think Rufus can do the formatting.

**Comment by Burgos91** [comment]
ok ill report as soon I finish and see if worked

**Comment by Burgos91** [comment]
did everything you told me and it work for now thanx alot
