### ISSUE TITLE
Issue with Controls whether dmnt cheats should be toggled on or off

### ISSUE THREAD

**Issue by sakatsuku** [Atmosphere-NX/Atmosphere#764]
atmosphere 0.10.1
\atmosphere\config_templates\system_settings.ini
dmnt_cheats_enabled_by_default = u8!0x1

I set u8!0x1 to u8!0x0, but cheats still be toggled on by default

**Comment by fincs** [comment]
Copy config_templates/system_settings.ini to config/system_settings.ini.

**Comment by sakatsuku** [comment]
> Copy config_templates/system_settings.ini to config/system_settings.ini.

still don't work, all cheats be toggled on by default

**Comment by gut5** [comment]
I'm getting a possibly related issue to dmnt:cht not working correctly when cheats are enabled but working when they are individually enabled through Edizon
