### ISSUE TITLE
A fata error occurred when running Atmosphere

### ISSUE THREAD

**Issue by yoyonl** [Atmosphere-NX/Atmosphere#769]
Hi,

After accidentally pushed system update, i get:

a fatal error occurred when running Atmosphere.

Attached the error report.bin
[report_0000000005b7e6e1.txt](https://github.com/Atmosphere-NX/Atmosphere/files/3973531/report_0000000005b7e6e1.txt)

I had to change extension to txt, to use rename .txt to bin again.

Thnx

**Comment by SciresM** [comment]
You have corrupt archive bits on atmosphere folder, probably you're using macOS.

Please unset the archive bit on the directories on sdmc:/atmosphere/.

**Comment by yoyonl** [comment]
Thanks works again!

used chflags -R arch sdmc:/atmosphere
