### ISSUE TITLE
"Failed to appply 'no sigchk'" and "failed to launch HOS"

### ISSUE THREAD

**Issue by Initializist** [Atmosphere-NX/Atmosphere#772]
## Bug Report
N/A
[ * ]</br>

### What's the issue you encountered?
After I updated hekate to the latest version, whether I try to enter SYSNAND or emuMMC. The message 'Failed to appply 'no sigchk' and 'failed to launch HOS' will show on the screen.
I didn't really change anything in atomsphere except edit the override_config.ini from "[default_config] ; override_key=!L; cheat_enable_key=!L" to "[default_config]; override_key=!R; cheat_enable_key=!R"

### How can the issue be reproduced?
I don't if this change caused the issue
### System Firmware Version
9.1.0

### Environment?
- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 5.1.1
- Official release or unofficial build: 
  - Atomsphere 0.10.1 master 71b220a4
  -  Kosmos 14.2
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]
checkpoint, Edizon, gold leaf, mercury, Appstore, Kosmos toolbox/updater,sigpatch updater

### Additional context?
I am using the kosmos 14.2 but I replaced the atomsphere with the latest one. I am also using hekate 5.1.1 and replaced the bootloader file. I am also using the sigpatches from "https://gbatemp.net/threads/i-heard-that-you-guys-need-some-sweet-patches-for-atmosphere.521164/"

**Comment by fincs** [comment]
Piracy is not supported.
