### ISSUE TITLE
Complete system lockup in Mario Odyssey

### ISSUE THREAD

**Issue by j-james** [Atmosphere-NX/Atmosphere#775]
### What's the issue you encountered?

When playing Mario Odyssey, the game froze at the main screen, with the Switch unresponsive to any controls. I eventually had to force-shutdown the console by holding down power for ~15 seconds.

No changes have been made to Atmosphere itself.

### How can the issue be reproduced?

I haven't been able to reproduce this issue. 

### Crash Report

Atmosphere didn't go to a crash screen - the entire Switch just was unresponsive. Both of my crash reports in `atmosphere/crash_reports` came from an unrelated incident (me trying to launch Kosmos Toolbox as a standalone).

### System Firmware Version

9.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by?
  - fusee-primary initially, although I may have rebooted to Hekate at some point. Both were updated for Atmosphere 0.10.0.
- Official release or unofficial build
  - Official release version 0.10.1 from GitHub.
- Additional kips or sysmodules?
  - sys-con
  - sys-ftpd-light
- Homebrew software installed?
  - Checkpoint
  - Goldleaf (no sigpatches)
  - MelonDS
  - RetroArch

### Additional Context?

The symptoms of this issue seem similar to #748 and #322.

I'm unfortunately not going to be very helpful in debugging, as I don't have a way to relaunch Atmosphere right now, but I can pull files from the SD card.

**Comment by fincs** [comment]
Remove custom sysmodules, and try again.

**Comment by j-james** [comment]
SMO is physical, SD card is FAT32. 
Unfortunately, I don't have a payload injector with me, and I wasn't able to boot back to Atmosphere.

**Comment by ELY3M** [comment]
have you added any mods for the super mario odyssey?

**Comment by j-james** [comment]
No modifications have been made to the system or games.

**Comment by SciresM** [comment]
```
Additional kips or sysmodules?
sys-con
sys-ftpd-light
```

Does issue occur without additional sysmodules?

**Comment by j-james** [comment]
I'm unable to test. Unfortunately, I don't have a payload injector with me, and I wasn't able to boot back to Atmosphere.

That might be a valid enough reason to close this.

**Comment by SciresM** [comment]
Unable to boot back to ams kind of suggests there's weirder stuff going on, yeah. If you get it reproducing make a new issue?

**Comment by j-james** [comment]
Unable to boot back to AMS just means I don't have my payload injector : /

If I can reproduce, will do.

**Comment by teamjonastan** [comment]
I had the same exact issue. It happens when I accessed the Action Guide. The issue is with the sys-modules; sys-ftpd-light and sys-con. If you remove them, the game shouldn't freeze up anymore.

**Comment by joshuajaharwood** [comment]
> 
> 
> I had the same exact issue. It happens when I accessed the Action Guide. The issue is with the sys-modules; sys-ftpd-light and sys-con. If you remove them, the game shouldn't freeze up anymore.

Fixed for me just by disabling sys-con. Strange bug!
