### ISSUE TITLE
[Request] LayeredFS load mod paths from text file

### ISSUE THREAD

**Issue by puddydoo** [Atmosphere-NX/Atmosphere#776]
#### Overview:
- If a file called mods.txt is inside the atmosphere/contents/titleid directory, LayeredFS will load mods for that title from the directories listed in mods.txt.
- To use mods, the only thing that has to be inside the atmosphere/contents/titleid directory is the mods.txt. The individual mods can be installed in their own folders elsewhere on the SD card.

#### Smaller Details: 
- The order that the mods are listed in mods.txt is important. If a mod edits the same file as a previous mod, the previous mod's version of that file will be ignored.
- Maybe LayeredFS will still load the mod inside the atmosphere/contents/titleid directory, but I don't know whether it would go before or after mods.txt.
- If a line in mods.txt is commented out, LayeredFS will ignore it.

#### Nature of Request:  
- Addition

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)

### Why would this feature be useful?
- Easier to identify all the mods you have installed currently, especially if the user did not add a readme for each mod to the folder.
- Practical to distinguish which file came from which mod since they are all in separate folders.
- Possible to disable individual mods by commenting out a line of text rather than restructuring the entire folder.
- Multiple titles can use the same mod, so for example it wouldn't be necessary to install the exact same files twice for Pokémon Sword and Shield. Any version-specific files can go in separate mods.
- Cuts down on SD card writes during mod management.

**Comment by SciresM** [comment]
Closing for now, as it's not really desirable to make sd-romfs even more sparse than it currently is. Does merit consideration for the future, though. stub-files-in-romfs is higher priority, as is romfs-path-compression.
