### ISSUE TITLE
CRASH SUPER SMASH BROS. ULTIMATE v6.1.0

### ISSUE THREAD

**Issue by cherrymx89** [Atmosphere-NX/Atmosphere#778]
good afternoon, I have this crash in atmosphere v10.1-71b220a4 FW 9.1.0 

My SD card exfat32

error code: 2162-0002 (0x4a2)

Wanting to play super smash bros. ultimate v6.1.0, upon entering the character selection.

CRASH REPORT:
[01577398442_010000000000100f.log](https://github.com/Atmosphere-NX/Atmosphere/files/4003558/01577398442_010000000000100f.log)

FATAL REPORT:
[01577387632_010000000000100f.log](https://github.com/Atmosphere-NX/Atmosphere/files/4003330/01577387632_010000000000100f.log)

**Comment by SciresM** [comment]
Please re-open using issue templates. (Also, I can't locally reproduce?)

**Comment by hamsudang** [comment]
i have smae problem

**Comment by SciresM** [comment]
@hamsudang please open a new issue using the issue templates if this is a problem for you.

**Comment by xmaurox9** [comment]
I have the same problem, please letme know how you solved it!
