### ISSUE TITLE
Can't access Applet Mode

### ISSUE THREAD

**Issue by PKMWM1** [Atmosphere-NX/Atmosphere#780]
I am on the latest version of atmosphere and switch firmware. Although I can access homebrew through the standard title takeover method, I can't access homebrew through applet mode at all. Whenever I hold the R button and select album, it just shows me my pictures. I tried rebooting and re injecting the payload and it still isn't working. I can't find any notes about this online. Any help would be appreciated.

**Comment by HookedBehemoth** [comment]
From the release page:

- Default override behavior was changed.
  - By default, atmosphere will now override the album applet with hbl unless R is held.
  - By default, atmosphere will now override any application with hbl only if R is held.

**Comment by simonrb2000** [comment]
I'm on latest and mine still behaves the old way for album. As in I have to hold R to get Applet Mode. I can't run any title on tack over mode though.. Strange
