### ISSUE TITLE
Hangs system in any menu or trying to launch game card

### ISSUE THREAD

**Issue by minipretzel** [Atmosphere-NX/Atmosphere#784]
### What's the issue you encountered?

Atmosphere 0.10.1/0.10.0 hangs entire system after booting when trying to launch a game card or browsing a user profile.  Only way to shutdown is by holding power for ~10 seconds.

### How can the issue be reproduced?

Boot using payload.  Try to launch game card. Hangs system.
Boot using payload.  Enter user profile.  Move up/down through Profile/Friend List etc several times.  Press B to go back.  Hangs system.  

### Crash Report

Nothing is produced.

### System Firmware Version

4.1.0

### Environment?

bootloader: 
hekate - CTCaer mod v5.1.1 & Nyx v0.8.4
fusee-primary.bin

### Additional context?

Atmosphere 0.9.4 loads and runs without issues.
SD card is formatted as FAT32.

**Comment by SciresM** [comment]
This was fixed in 0a18c63f245d2dbf38cd966e6f40ef20396ae41f.

Wait for AMS 0.10.2, or compile master :)
