### ISSUE TITLE
crash in Atmosphere - not stable

### ISSUE THREAD

**Issue by demetom** [Atmosphere-NX/Atmosphere#786]
Hello,

I don't know exactly what to do with theses issues. I already tried so many things in order to solve this but I really don't know what to do now. I am even thinking of selling my unpatched switch as I am so frustrated now...

I have an unpatched Switch: XAJ7001373 OFW: 9.1
I installed Atmosphere 10.1 and Hekate 5.1.1 with the patches from Joonie86.
I managed to partition my SD card with Tegra Explorer and I managed to create en EMUNAND.
I also managed to launch Hekate and install NSPs with Goldleaf.
However my system appears to be unstable. Randomly I have some frozen screens when I am playing, or some crashes with 2002-2002 error code and 2002-3502 code.
I tried the tool Archive Bit of Hekate and I always have some archive bit fixed (typically 60 in the Nintendo folder) even if I use the tool several times in a row as if it wasn't correcting the archive bits (don't know if it is normal)
I tried different SD cards (SANDISK ULTRA and SAMSUNG EVO+) that appear to be genuine, I checked them with h2testw...
I am kind of desperate. If someone could help me in order to get a stable system, I would really appreciate. (For one of my friend, it works really well and it is stable)
One of my thought is that my sysnand is dirty. I used a RCM loader and I had a very weird message (like a virus message when it loaded the payload the very first time)
Is it possible that with a dirty sysnand it could create some issues like that.
I know that I should have made a clean copy of my sysnand from the beginning but it appears that the copy I made at the very beginning is not good because when I tried to restore it, I had an error message.
I used Haku33 once in order to clean my sysnand but I am wondering if it is enough to clean it completely. I was able to connect to the eshop and to download demo games from it without being banned.
Please, if anyone has an idea on what to do in order to get a stable system working, I would really appreciate. Thanks a lot

![IMG_9432](https://user-images.githubusercontent.com/53630459/71648038-68843980-2cff-11ea-9fd5-c8334a76176b.JPG)
![IMG_9433](https://user-images.githubusercontent.com/53630459/71648039-68843980-2cff-11ea-8d55-1a8a268fdfd0.JPG)
![IMG_9434](https://user-images.githubusercontent.com/53630459/71648040-68843980-2cff-11ea-8a94-03e9782307c2.JPG)
![IMG_9435](https://user-images.githubusercontent.com/53630459/71648041-691cd000-2cff-11ea-8226-dca4b52824cc.JPG)
![IMG_9436](https://user-images.githubusercontent.com/53630459/71648042-691cd000-2cff-11ea-8d00-486fcbe71283.JPG)

**Comment by SciresM** [comment]
> install NSPs with Goldleaf.

Piracy is not supported.

>2002-0002

"File not found".

>2002-3502

"Mmc device isn't active".

No idea why `es` would get this error.

I don't think this is an *atmosphere* issue from what I'm hearing.

Does issue occur using completely stock Atmosphere release build, booting with fusee and not hekate? Closing because it seems like not-ams-problem, talk to m4xw about nand weirdness maybe.

**Comment by geraldFF** [comment]
Hi! I have the same issue, did you found out the solution OP? Thank you!

**Comment by demetom** [comment]
Nope sorry, I didn’t find any solution for this but I think it is a problem of the Switch itself. 
(Maybe the card reader but I am not sure)
And it worked perfectly with an other Switch

**Comment by Neno2113** [comment]
I have the same problem and I think is card reader of the Switch

**Comment by SimoneCupo** [comment]
> I have the same problem and I think is card reader of the Switch

Did u fix it?
