### ISSUE TITLE
Cannot launch album without holding R button

### ISSUE THREAD

**Issue by tatundria** [Atmosphere-NX/Atmosphere#787]
Switch Atmosphère 0.10.2. Cannot launch album without holding R button. I changed the loader.ini and override_config.ini files and they won't work. It always launches hbmenu in applet mode. I also tried change the titleid to prevent the album to be launched. No success.

**Comment by SciresM** [comment]
1) Use issue templates

2) You're editing the wrong file. Config was moved into /atmosphere/config.
