### ISSUE TITLE
dmnt_cheats_enabled_by_default still not work

### ISSUE THREAD

**Issue by sakatsuku** [Atmosphere-NX/Atmosphere#790]
Atmosphere 0.10.2
I set dmnt_cheats_enabled_by_default to u8!0x0, but still not work
It happens on 0.10.1 and I submitted this issue too

**Comment by herman23a** [comment]
you must move your file system_settings.ini from /atmosphere/    to    /atmosphere/config/

dont know why system_setting.ini in /atmosphere/ in the first place.

**Comment by SciresM** [comment]
1) Use issue templates

2) 0.10.0 moved configuration settings per above, see release notes.

**Comment by sakatsuku** [comment]
> you must move your file system_settings.ini from /atmosphere/ to /atmosphere/config/
> 
> dont know why system_setting.ini in /atmosphere/ in the first place.

thanks，I moved system_settings.ini to /atmosphere/config/，and delete "; " in front of dmnt_cheats_enabled_by_default, it works
