### ISSUE TITLE
docs/cheats.md not updated with 0.10 changes

### ISSUE THREAD

**Issue by ShadowTS** [Atmosphere-NX/Atmosphere#791]
## Bug Report

On all the Atmo 0.10.x release the docs/cheats.md documentation does not reflect the changes done on AMS 0.10 on:
/atmosphere/titles shoud be updated with /atmosphere/contents

**Comment by SciresM** [comment]
Yeah the docs are very out of date in pretty much every way.

**Comment by hexkyz** [comment]
I'm closing down this issue in favor of issue #797
