### ISSUE TITLE
Deleting override_config.ini or values inside it does not fall back to default values at runtime

### ISSUE THREAD

**Issue by cathery** [Atmosphere-NX/Atmosphere#792]
### What's the issue you encountered?

When modifying the `override_config.ini` at runtime (through ftp or mtp servers for example), if Atmosphere cannot find the appropriate setting in the config, it does not fall back to the default value like it does during startup. This creates an issue when the user wants to delete all custom override settings in hopes of it resetting to default values.

### How can the issue be reproduced?

1. Set the value of `program_id` under `[hbl_config]` to the ID of your game
2. Observe that hbmenu now opens through your game, and doesn't open through the album
3. Without rebooting Atmosphere, remove the `program_id` setting or the ini file entirely (e.g., the user is lazy and hopes that it changes back to the album ID)
4. Observe that hbmenu still opens through your game and doesn't open through the album

### Crash Report

N/A

### System Firmware Version

Switch FW 9.1.0

### Environment?

I think it's pretty clear that this is an Atmosphere issue.
Using latest release Atmosphere 0.10.2-master-d5458960.

### Additional context?

- [The relevant function in the source code for updating the override config](https://github.com/Atmosphere-NX/Atmosphere/blob/master/libraries/libstratosphere/source/cfg/cfg_override.cpp#L294)
  - As you can see, it only changes the value if it can parse the option in the ini file. If it can't find the option, it keeps using the previous value.

**Comment by SciresM** [comment]
I regret allowing override_config.ini to be editable at runtime.
