### ISSUE TITLE
Error on boot

### ISSUE THREAD

**Issue by Boucingblade** [Atmosphere-NX/Atmosphere#796]
Fatal Error Report
What's the issue you encountered?
The following error apeers when trying to boot from Hekate atmosphere (sysnand)

A fatal error occurred when running Atmosphére.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)

Did you make any changes related to Atmosphère itself?
No

How can the issue be reproduced?
Boot to RCM and launch Hekate and then Boot Atmosphere primary or emunand

Crash Report
Not a crash report but a Fatal Error maybe the same error: https://github.com/Atmosphere-NX/Atmosphere/issues/752

System Firmware Version
8.1.0

Environment?
Bootloader: Hekate
Release: idk
Additional Kips/Sysmodules: N/A
Homebrew Installed: N/A

Additional context?
This is happening after trying to upgrading from hetake 5.0.2 to the 5.1.1.
Already re-uploaded archives, Windows user, sd card on fat32.

**Comment by SciresM** [comment]
Please upload the fatal error report. Help can't be given without it.

**Comment by EddyCR** [comment]
Have you tried the same solutions given on #752, running the both hekate's archive bit fixer?

**Comment by Boucingblade** [comment]
> Have you tried the same solutions given on #752, running both hekate's archive bit fixer?

already tried.

**Comment by Boucingblade** [comment]
> Please upload the fatal error report. Help can't be given without it.

How? what kind of upload?

**Comment by Boucingblade** [comment]
> Please upload the fatal error report. Help can't be given without it.

![JPEG_20200109_211958](https://user-images.githubusercontent.com/23247515/72190941-8dec0400-33df-11ea-8d33-fd89474d7c28.jpg)

**Comment by Boucingblade** [comment]
> Please upload the fatal error report. Help can't be given without it.

![IMG_20200109_164356](https://user-images.githubusercontent.com/23247515/72190981-a5c38800-33df-11ea-8fd3-4f6a37383d5f.jpg)

**Comment by HookedBehemoth** [comment]
> Report saved to /atmosphere/fatal_errors/report_[...].bin
Send that file.

**Comment by SciresM** [comment]
Please upload the file that is being saved to /atmosphere/fatal_errors, yes

**Comment by Boucingblade** [comment]
The Error file

**Comment by Boucingblade** [comment]
> Please upload the file that is being saved to /atmosphere/fatal_errors, yes

The error file, isnt supported:
https://drive.google.com/file/d/10PWQVWmMcvByRhD54fwqzZo5EHp9BK-0/view?usp=sharing

**Comment by SciresM** [comment]
Your PRODINFO partition is corrupted. Please seek assistance in the reswitched discord if needed, but this isn't actually an atmosphere bug.
