### ISSUE TITLE
Implement emunand.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#8]
Once #7 is resolved, actually implement. This will either involve patching up the FS module, or writing/implementing an EL2 driver. If the latter, will need support in custom TZ.

**Comment by SciresM** [comment]
Heh.

**Comment by DavidBuchanan314** [comment]
Is an EL2 based solution still being considered for the future?

**Comment by hexkyz** [comment]
@DavidBuchanan314 Yes. The goal is to have as many options as possible.
