### ISSUE TITLE
Crash report 

### ISSUE THREAD

**Issue by thelichekinge** [Atmosphere-NX/Atmosphere#800]
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]</br>

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?

Game crash after 1/5 min :/

### How can the issue be reproduced?

when i play
### Crash Report
[https://gist.github.com/thelichekinge/1910b48825bb3ac3b47c7e2a1ab1133c]
### System Firmware Version

9.1.0</br>

### Environment?
fuse-primary.bin
- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: 
  - [ Official release version x.x.x (or) unofficial build ]
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: Self-compilation ]
     - [ Ex: Kosmos' distribution of Atmosphère ]
- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: [ * ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Not actually an atmosphere problem.

Attempts to read SD card contents are receiving 2002-2096 (0x106002). This is an error related to voltage switching for SD card.

Something's wrong with your SD card. You probably need to use a different one (your current one may have hardware problems(?)).
