### ISSUE TITLE
Unknown pkg1 version Failed to boot HOS

### ISSUE THREAD

**Issue by BladeStrde** [Atmosphere-NX/Atmosphere#802]
### What is the issue:

By starting the EmuMMC from Hekate I receive an error stating unknown pkg1 version failed to launch HOS

### How it can be reproduced
Open hekate from RCM -> Launch -> CFW (EMUMMC)

### What actions have I taken

- Redownload everything including sig patches
- Use Fusee-primary (results in a black screen) 

I really am lost at the moment and can supply extra information if needed

**Comment by SciresM** [comment]
This is a hekate error, not an atmosphere error.

Update both atmosphere and hekate to the latest versions.

**Comment by BladeStrde** [comment]
Just updated both, problem still persists

**Comment by SciresM** [comment]
Seek help with hekate or in the ReSwitched support channels -- this isn't an atmosphere problem, hekate is not an atmosphere component.
