### ISSUE TITLE
fusee-primary.bin in atmosphere folder

### ISSUE THREAD

**Issue by ELY3M** [Atmosphere-NX/Atmosphere#807]
over a year ago, I read a guide that told me to copy fusee-primary.bin into atmosphere folder.  I used hekate to boot to atmosphere.  
I still have to copy the fusee-primary.bin every time I update my atmosphere files.   

I wonder why you do not add the fusee-primary.bin in atmosphere folder in your zip package?  
I am curious

**Comment by ELY3M** [comment]
this is meant to be feature request or suggestion.

**Comment by Raugo** [comment]
fusee-primary is in the atmosphere folder is the reboot_payload.bin

**Comment by james-d-elliott** [comment]
It actually does exist there. It's called reboot_payload.bin from memory.

**Comment by SciresM** [comment]
please use the issue templates, in the future.

**Comment by ELY3M** [comment]
thank you for your response.
