### ISSUE TITLE
Atmosphere Crashing While Loading emummc

### ISSUE THREAD

**Issue by DarthBelphegor** [Atmosphere-NX/Atmosphere#817]
### What's the issue you encountered?
The only change that I am aware of to atmosphere is that I changed the homebrew menu override key to ZR instead of R.
I was trying to check my album to see a screenshot I just took when it automatically opened the homebrew menu without me holding ZR. I tried this several times and it kept happening. I assumed it was an issue with me changing the override key to ZR, so I ejected the micro sd from the switch. I changed what was necessary in the loader.ini and then plugged the micro sd back into the switch and restarted the console. It went to the atmosphere menu, and so I launched the emummc again. It appeared to work, however after displaying the nintendo switch logo, it immediately went to an error screen. Not only was it an error, it was completely frozen not allowing me to reset it, but instead forcing me to completely power it down. From this it went to the stock switch screen. I attempted to retry by sending it back into the rcm mode and re-injecting hekate. This however led to the same thing happening, ending with a frozen error screen.

### How can the issue be reproduced?

Re-inject hekate and try to load the emummc.

### Crash Report
The crash report:
https://gist.github.com/DarthBelphegor/f898e43e0f21f32e5d02491508ef5928

The fatal report:
https://gist.github.com/DarthBelphegor/a5e201e4879973c92e43991d014adcc6

### System Firmware Version

9.0.1

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
   hekate
- Official release or unofficial build: 
   Official relase version 0.10.2  

- Do you have additional kips or sysmodules you're loading:
- Homebrew software installed: 

### Additional context?

- Additional info about your environment:

**Comment by SciresM** [comment]
...this isn't an atmosphere problem.

Ejecting the SD while the console is on and booted into emummc is equivalent to removing its nand normally.

I'm sure you corrupted it -- just make a fresh emummc.
