### ISSUE TITLE
Multi Language support

### ISSUE THREAD

**Issue by Philipp97714** [Atmosphere-NX/Atmosphere#82]
I would like to constribute something but don't know what. If you want to I can translate English strings to German for multi language support.

**Comment by Sonixier** [comment]
I speak german too.

**Comment by duracell** [comment]
There are many german speakers around :D

**Comment by MrMaleficus** [comment]
I can translate the English strings to French 😊

**Comment by slock83** [comment]
I can also work on the French translation (translating and/or checking)

**Comment by Strat00s** [comment]
Hell yea. I can translate strings to the most useful language ever. Czech :D

**Comment by YayIguess** [comment]
Probably know enough Russian to translate a fair bit, know some people good with Afrikaans and some other languages as well.

**Comment by thomleg50** [comment]
I can translate to french

**Comment by Philipp97714** [comment]
Can someone, who is working on the code, tell us, if a translation is possible/helpful?

**Comment by flopglop** [comment]
I could help to translate Atmosphere into Spanish

**Comment by Kleei** [comment]
i can translate to russian / romanian

**Comment by Suinkai** [comment]
I can help translating to Spanish too

**Comment by FearlessTobi** [comment]
I can help with all the German translation stuff too.

**Comment by Philipp97714** [comment]
Please don't offer any translations before we know if they are helpful

**Comment by CreedVI** [comment]
I can translate to German and Esperanto!

**Comment by frankthedead** [comment]
I can translate to Portuguese.

**Comment by SirNapkin1334** [comment]
I can do minor German translations.

**Comment by deWasbeer** [comment]
I can help with dutch!

**Comment by Deathwink** [comment]
I can translate to Italian

**Comment by hexkyz** [comment]
Appreciate the enthusiasm, but Atmosphère currently has no need for translations. If/when this changes, we will announce it.
