### ISSUE TITLE
Problema ao encontrar firmware

### ISSUE THREAD

**Issue by Wimmer1997** [Atmosphere-NX/Atmosphere#822]
Atualizei o switch para 9.1.0 pelo (choidujournx) e apertei no lugar errado e ele não encontra mais o firmware a imagem peguei na internet pra mostrar onde apertei errado quem souber o que fazer dá uma ajuda ai
![IMG-20200221-WA0015](https://user-images.githubusercontent.com/61438384/75200091-a1f78500-5743-11ea-85c6-95554ef4eb66.jpg)

**Comment by SciresM** [comment]
Please use the issue templates.

Also, I only speak English.

**Comment by Wimmer1997** [comment]
I updated the switch to 9.1.0 by choidujournx and pressed it in the wrong place and he no longer finds the firmware (the image I picked up on the internet to show where I pressed it wrong.)
