### ISSUE TITLE
pSNES and pNES controllers aren't responsive anymore.

### ISSUE THREAD

**Issue by azoreseuropa** [Atmosphere-NX/Atmosphere#829]
I have a problem with the latest atmosphere release. pNES and pSNES. The controllers aren't responsive! It was worked at 0.10.2. What I did do ? You need to copy system_settings.ini from config_templates in atmosphere and copy it to config folder and edit system_settings.ini using your favourite notepad like this:

enable_deprecated_hid_mitm = u8!0x1
[hbloader]

and save it.
I did that for 0.10.3 and it didnt work anymore.

**Comment by SciresM** [comment]
1) reopen with issue templates used if this is a real problem

2) that line needs to be uncommented and in the atmosphere section.

**Comment by azoreseuropa** [comment]
I dont understand. Where is my question going to ?

**Comment by SciresM** [comment]
"reopen with issue templates used if this is a real problem"

**Comment by azoreseuropa** [comment]
Where ? I never have done this one before.
