### ISSUE TITLE
error - when try to lanch hb menu

### ISSUE THREAD

**Issue by lpt2007** [Atmosphere-NX/Atmosphere#831]
Anyone knows what this error menas. It hapened when I call hbmenu.

![20200308_000629](https://user-images.githubusercontent.com/38924279/76153785-94da7e80-60d1-11ea-8c03-2831bc5af912.jpg)

**Comment by SciresM** [comment]
Closing because:

-This does not use the issue templates
-You are not on latest atmosphere release.

If error occurs on latest atmosphere release, please re-open using issue templates.
