### ISSUE TITLE
Atmosphere Fatal Error on Boot 

### ISSUE THREAD

**Issue by YodaGaming** [Atmosphere-NX/Atmosphere#836]
### What's the issue you encountered?

A fatal error occurred when running Atmosphére.
Title ID: 0100000000000008
Error Desc: std::abort() called (0xffe)

[ Did you make any changes related to Atmosphère itself? ]</br>

no

### How can the issue be reproduced?

Boot to RCM
Launch Hekate
Boot Atmosphere through either fusèe-primary or emunand

### Crash Report

https://github.com/YodaGaming/Bugs/blob/master/report_0000000005d3a187.bin

### System Firmware Version

0.9.2

### Environment?

Bootloader: Hekate & Nyx
Release: 5.1.2 &  v0.8.5
Additional Kips/Sysmodules: N/A
Homebrew Installed: N/A

### Additional context?

This is happening after upgrading from 9.1.0 to 9.2.0 and then updating Atmosphere and Hekate to their latest versions.

Even after using a clean SD I still get the same issue

**Comment by SciresM** [comment]
This is an atmosphere version mismatch -- your environment is not actually clean. Somehow, you are launching current boot2 under an older exosphere. 

Make sure you're actually launching with clean atmosphere.
