### ISSUE TITLE
Error Code: 2162-0002 (0x4a2)

### ISSUE THREAD

**Issue by xmagcx** [Atmosphere-NX/Atmosphere#837]
## Bug Report

Hi guys waiting to be fine I have the error 010000000000100f (attached log of the folder fatal report). As evidence it happens to me with the game super smash bros ultimate when starting both story mode or any other mode. What I have tried so far:
1- Just play the version without updates.
2- install the latest update
3- install different updates and nothing

Please I need your help I have tried and tried everything in my power

[01584409357_010000000000100f.log](https://github.com/Atmosphere-NX/Atmosphere/files/4346546/01584409357_010000000000100f.log)
![IMG_20200317_092415](https://user-images.githubusercontent.com/20447334/76917486-4cc21580-68a2-11ea-83db-47afd5bd9861.jpg)

**Comment by SciresM** [comment]
Please re-open using the issue templates.

**Comment by xmagcx** [comment]
What's the issue you encountered?

Hi guys waiting to be fine I have the error 010000000000100f (attached log of the folder fatal report). As evidence it happens to me with the game super smash bros ultimate when starting both story mode or any other mode. What I have tried so far:
1- Just play the version without updates (Smash Bross Ultimate Game).
2- install the latest update (Smash Bross Ultimate Game)
3- install different updates and nothing (Smash Bross Ultimate Game)


How can the issue be reproduced?
 

Crash Report
 
https://gist.github.com/xmagcx/3478a5e131d27b195fee164638cd1555


System Firmware Version
9.2.0
 
Environment
bootloader Atmosphère launched by: Atmosphère
Official release or unofficial build: N/A
 Official release version 0.10.4-master-e8dfe047 
 If using an unofficial build, include details on where/how you acquired the build. 
 Ex: N/A
 Ex: N/A
Do you have additional kips or sysmodules you're loading: no
Homebrew software installed:  *  atmosphere
Additional context: N/A
Additional info about your environment: N/A
 Any other information relevant to your issue: Attached image for reference error
![IMG_20200317_092415](https://user-images.githubusercontent.com/20447334/76958959-65104f80-68f7-11ea-8c84-618e25f7ac8c.jpg)
