### ISSUE TITLE
ChoiDuJourNX Crashing; System not launching in Full Memory Mode

### ISSUE THREAD

**Issue by dothackjhe** [Atmosphere-NX/Atmosphere#838]
### What's the issue you encountered?

ChoiDuJourNX crashes as soon as it was launched. 

Tried launching Full Memory Mode, but the system would not.

The most major change I did with the Switch is upgrade to Atmosphere 0.10.4.

### System Firmware Version

8.1.0

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate 5.1.2

**Comment by SciresM** [comment]
"Full memory mode"?

You didn't actually fill out the issue template, you deleted most of the questions.

Choi works over here.

**Comment by SciresM** [comment]
Re-open using the issue template properly.
