### ISSUE TITLE
SPL accepts key generation 11 on 9.0.0 (key gen 10)

### ISSUE THREAD

**Issue by HookedBehemoth** [Atmosphere-NX/Atmosphere#839]
### What's the issue you encountered?

Calling splCryptoGenerateAesKek with key generation 11 on version HOS version 9.0.0 succeeds even though the expected/supported key generation is 10.

Reading the version from BCT returns the expected version 10.

### How can the issue be reproduced?

Call splCryptoGenerateAesKek with key generation 11 on version HOS version 9.0.0.

### System Firmware Version

9.0.0

### Environment?

- bootloader: both fusèe primary and hekate
- official release 0.10.4
- no additional kips or sysmodules
- Homebrew software installed: the one I used to test this

### Additional context?

- Additional info about your environment:
- dark mode
- I use arch btw

**Comment by SciresM** [comment]
Intentional.
