### ISSUE TITLE
Luigi's Mansion 3

### ISSUE THREAD

**Issue by Linkmonster666** [Atmosphere-NX/Atmosphere#842]
After I updated Atmosphere to 10.5 Luigi's mansion fails to load. I updated sigpatches and checked the logs. There is nothing I can find about the game not loading. I have the game card and it is updated to 1.3. I'm not sure what is going on. I tried a new sd card with a clean version of Atmosphere and even tried the last version that worked. Game fails with normal error message. Thanks for any help!

**Comment by Linkmonster666** [comment]
I tested the game card on a vanilla switch and the card itself works. I also tried BOTW card and it loads on my Atmosphere switch fine.

**Comment by SciresM** [comment]
Please re-open using the issue templates.
