### ISSUE TITLE
Cannot use FTP on some systems

### ISSUE THREAD

**Issue by DiamondHousefX** [Atmosphere-NX/Atmosphere#845]
I'm using several switches with LiveHex from PkHex. Initially I had 5 Switches running with no issues prior to the update. I've built the SD cards exactly the same and now only 3 works for FTP.
I've also reformatted and purchased NEW SD cards to test for issues but same issue persists.
Also swapped the SDs from the switches that DO work and tested but it seems no be of no use at the moment.
 
- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Fusee and Hekate
- Official release or unofficial build: 10.4
- Homebrew software installed: [ FTP Snap]

I assumed this MAY be an issue with Atmosphere hence why I'm just reaching out here.

**Comment by SciresM** [comment]
Re-open using issue templates.
