### ISSUE TITLE
crash on emunand loading(after switch logo) after emunand update to 8.1.0

### ISSUE THREAD

**Issue by Kosuke-ak** [Atmosphere-NX/Atmosphere#849]
sysnand : 4.1.0
emunand : 4.1.0
Komos : last version

try to update emunand 4.1.0 to 8.1.0 with choix du jour but after rebooting hetake, when emunand is booting, just after switch logo, it crash.

I tested with factory reset option in choix du jour, all be done but 8.1.0 want to erase the sd card (it don't leave me the choise) and after doing it, the switch reboot and after rebooting hetake, when emunand is booting, just after switch logo, it crash.

**Comment by deadair3210** [comment]
is it so hard to use the issue template....

**Comment by SciresM** [comment]
Re-open using the issue templates.
