### ISSUE TITLE
black screen after accidentally updating the game

### ISSUE THREAD

**Issue by Wimmer1997** [Atmosphere-NX/Atmosphere#853]
good night, my switch was at (firm 9.1.0 atmosphere 0.10.2) or something, I downloaded a game is fifa 20 for Tinfoil and when I went to play he asked for an update I accidentally updated and he restarted the console and now  it just goes to the atmosphere logo and doesn't open the menu can someone help me?  Black screen after logos

**Comment by SciresM** [comment]
Atmosphere doesn't support piracy.

Also, you did not use the issue templates.
