### ISSUE TITLE
Error 2168-0002 (0x4A8) 

### ISSUE THREAD

**Issue by rnuno17** [Atmosphere-NX/Atmosphere#854]
## Bug Report
2168-0002 (0x4A8)(attached log of the folder crash_reports)

### What's the issue you encountered?

Error Code: 2168-0002 (0x4A8)
Program: 010000000000100d

It happens when i try to open the hombrew store app. Also all the aps on the hb menu frezes.

### How can the issue be reproduced?

1. Go to Album (hbmenu opens without pressing L)
2. Go to Hb App Store them system crashes

### Crash Report
[01585253162_010000000000100d.txt](https://github.com/Atmosphere-NX/Atmosphere/files/4389772/01585253162_010000000000100d.txt)

### System Firmware Version

9.2.0</br>

### Environment?

bootloader Atmosphère launched by: Atmosphère
Official release or unofficial build: N/A

Official release version atmosphere-0.10.5-master-b27c7552+hbl-2.3+hbmenu-3.2.0
  - [ If using an unofficial build, include details on where/how you acquired the build. ] 
     - [ Ex: N/A
     - [ Ex: N/A
- Do you have additional kips or sysmodules you're loading: yes
- Homebrew software installed:  atmosphere

### Additional context?

- Additional info about your environment: N/A

**Comment by SciresM** [comment]
this is a data abort in the homebrew you're trying to run, not an atmosphere issue. Please talk to the homebrew's developer.
