### ISSUE TITLE
Software wont boot up after update.

### ISSUE THREAD

**Issue by lajax01** [Atmosphere-NX/Atmosphere#861]
### What's the issue you encountered?
Software wont boot up, that is worked just fine previous fw version (9.1.0)
Error log attached.

### How can the issue be reproduced?
Start same software, but anything else works just fine.

### Crash Report

9.2.0 System Firmware Version 

9.2.0</br>
[01585601148_010075d00e8ba000.log](https://github.com/Atmosphere-NX/Atmosphere/files/4405396/01585601148_010075d00e8ba000.log)

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
- Official release or unofficial build: Official
  - [ Official release version x.x.x (or) unofficial build ] 0.10.5
- Do you have additional kips or sysmodules you're loading: Yes.
- Homebrew software installed: [ * ] Lots of.

**Comment by SciresM** [comment]
9.2.0 and 9.1.0 have no difference in atmosphere. The single line change is applied in both firmware versions under ams.

Does issue occur without custom sysmodules/homebrew?

**Comment by lajax01** [comment]
Yes. Usualy exefs paches, and content paches was applyed on this title, but the crash on boot occured without them either. Tesla running newly in the background, with custom overlays like sysclk, and edizone.
Could this the problem?

**Comment by SciresM** [comment]
Tesla is a custom sysmodule. I asked you to remove custom sysmodules and test without them, please.

**Comment by lajax01** [comment]
Ok, will do. Ill back in 12 hrs with the result. Thanks for your time, and cooperation! Muck appreciate!
