### ISSUE TITLE
A fatal error occurred when running atmosphere

### ISSUE THREAD

**Issue by MarioGaming298** [Atmosphere-NX/Atmosphere#865]
## Bug Report
atmosphere crashes while loading emmucc 

[ * ]</br>
[ Note: If the bug or crash you encountered is related to; ]</br>
[ - software used to make "backups", ]</br>
[ - software explicitly distributed for piracy, etc ]</br>
[ then contributors will not provide support for your issue and your issue will be closed. ]</br>

### What's the issue you encountered?
A fatal error occurred when running atmosphere
Title ID: 00ff747765616bff
Error Desc: std::abort() called (0xffe)

### How can the issue be reproduced?
launch hekate 
go to launch 
launch CFW (EMUMMC)
wait and It gives you the error
[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>

### Crash Report

https://gist.github.com/MarioGaming298/3d3601b3b016b68cd2c2d7a9a9fcda2a

### System Firmware Version

9.0.1

### Environment?

Official Hekate
- Do you have additional kips or sysmodules you're loading: no
- Homebrew software installed: [ * ]

### Additional context?

- Additional info about your environment: windows 10 and sd card is fat32

**Comment by SciresM** [comment]
This crash report is for a homebrew called "pplay" that is data aborting. This isn't an atmosphere problem, your best bet is to start over from clean atmosphere.
