### ISSUE TITLE
Black screen on second boot EMUMMC

### ISSUE THREAD

**Issue by themrheng99** [Atmosphere-NX/Atmosphere#866]
### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand.  - Follow instruction step by step from multi website still having blackscreen ]</br>
[ Did you make any changes related to Atmosphère itself?  - No ]

### How can the issue be reproduced?

[ 
1. create partition using Tegraexplorer 
2. create emummc
3. enable emummc
4. launch emummc
5. everything works fine
6. fully shutdown switch
7. boot again emummc with hekate
8. blackscreen
]

### Crash Report

[ https://github.com/themrheng99/switch/blob/master/01585986015_010000000000100d.log ]

### System Firmware Version

9.2.0

### Environment?

- Atmosphère launched by: Hekate
- Official release or unofficial build: 
  - [ Official ]
  - [ Kosmos' distribution of Atmosphère ]

- Do you have additional kips or sysmodules you're loading:
   - [ Sig patches ]
- Homebrew software installed: [ goldleaf, checkpoint ]

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by veesonic** [comment]
I have also been experiencing similar behavior. I use Kosmos and reported an issue on their github. I have a screenshot of what the log shows when attempting to boot into emummc, I also get a black screen.

https://github.com/AtlasNX/Kosmos/issues/274

(It looks like there were a couple of duplicate issues. Sorry if posting this is against rules, this comment can be deleted if needed.)
