### ISSUE TITLE
Fatal error when running Atmosphere title ID 0100000000000001

### ISSUE THREAD

**Issue by barbaralourenco** [Atmosphere-NX/Atmosphere#867]
Hi,
So i had a switch, working and hacked with atmosphere with OFW 8.(something). Done a NAND Backup. Played a lot of games.
Two days ago tried to install Animals crossing and get the error "failed to read metadata".
Read some stuff and updated OFW to 9.2. (that's my first error - i burned efuse).
Atmosphere stopped working: Inject payload and it keeps looping, logo apears and then back to hekate menu. Press launch logo apears and back to menu again.
Can't pass throw hekate menu so i press tools > Restore eMMC > eMMC BOOT0 & BOOT1. Reboot.
So thats the point my switch wont turn on anymore. no matter what i do, it simply wont turn on.
Format SD with FAT32, get a new and clean atmosphere instalation (0.10.5) inject payload fusee-primary and consola turn on. 
But now, neither fusee-primary or hekate let me acess to homebrew to install games, i always get the error after press album:

![91969754_10215450164636692_1575530519708303360_n](https://user-images.githubusercontent.com/63301605/78684763-c751e400-78e8-11ea-947b-96014ec66930.jpg)

can anyone help please?
BTW sorry about my english!

**Comment by fincs** [comment]
> tried to install Animals crossing and get the error "failed to read metadata"

Piracy is not supported.
