### ISSUE TITLE
OFW boot corrupted, really need help!!!

### ISSUE THREAD

**Issue by zzz6839** [Atmosphere-NX/Atmosphere#868]
Normal booting to OFW no response without injector(when I press the power button it shows black screen), I highly suspect the whole booting system is corrupted, RCM works fine, I can run into injected boot system(with USB dongle). but cannot boot into EMMC(cannot boot into the stock system now), I searched every existing similar problem on the internet, reformat SD card to Fat32 now, even tried different CFW, disable autoRCM and auto Boot, but nothing works when you try to boot into stock and EMMC system.

What to do..........
Rip my Switch

**Comment by zzz6839** [comment]
Only RCM works now, booting to stock or CFW would remain black screen after the NS-atmosphere logo(I tried Kosmos but also black screen after Kosmos logo appeared).

**Comment by zzz6839** [comment]
this whole thing happened when I tried to update Hbg shop. it froze when I press B to apply for the update, after waiting for a long time I decided to force shutdown my switch, and since then I've never be able to boot into the system again..... and yes I was using Exfat before.......

**Comment by bakugo** [comment]
Restore a backup, problem solved

**Comment by zzz6839** [comment]
> Restore a backup, problem solved

I have no backup, would someone send me your backup to me pls orz

**Comment by zzz6839** [comment]
> > Restore a backup, problem solved
> 
> I have no backup, would someone send me your backup to me pls orz

I know im playing with fire.......im sorry......

**Comment by deadair3210** [comment]
1. No Piracy Tools
2. Backups are console-specifc. Even if someone did send you one, it would only make things worse
