### ISSUE TITLE
Loading games with any LayeredFS mod results in fatal error

### ISSUE THREAD

**Issue by elliottbw** [Atmosphere-NX/Atmosphere#871]
### What's the issue you encountered?

I set up a LayeredFS mod for Animal Crossing: New Horizons, which replaced a music file in /Sound/Resource/Stream with a separate custom one, and moved the mod to /atmosphere/contents/[title id]/romfs. I then rebooted to the Atmosphère fusee-primary payload and loaded Animal Crossing, which resulted in a fatal error message and a reboot after hitting the power button.

I figured it was the mod causing the issue, so I changed the mod to replace the music file with the original file ripped from the game, and encountered the same issue. This same issue occurs with validated mods downloaded from Game Banana.

I haven't tested to see if the issue is specific to Animal Crossing, but given that known working mods don't work on my system, I feel like this is unlikely to be game-specific.

### How can the issue be reproduced?

Create/download any LayeredFS mod and place it in the correct location on your SD card, then try to load the game.

### Crash Report

```
A fatal error occurred when running Atmosphère.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_000000019f6a4314.bin

Press POWER to reboot
```

Here is the fatal error report:

https://github.com/elliottbw/TempAtmosphereIssueRepo/blob/master/report_000000019f6a4314.bin

Apologies for the lack of Gist - the file upload was failing me. Hopefully this should suffice.

### System Firmware Version

4.1.0 (patched Switch) for SysNAND, and 9.2.0 for EmuNAND</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: 
  - fusèe
- Official release or unofficial build: 
  - Official release version 0.10.5
- Do you have additional kips or sysmodules you're loading:
  - https://github.com/Joonie86/hekate/releases
- Homebrew software installed:
  - Goldleaf, Checkpoint, ChoiDujourNX, Edizon, Fake News Injector, HB App Store, Incognito, Kefir Updater, ldnmitm cfg, nxdumptool, nxmtp, Reboot to Payload, RetroArch, Tinfoil

### Additional context?

- Additional info about your environment:
  - As stated above, it's a patched Switch with firmware 4.1.0 running an EmuMMC at 9.2.0.

**Comment by SciresM** [comment]
You are not using the official release build of 0.10.5. That report was generated by a 0.10.3 copy of the sysmodule responsible for atmosphere.
