### ISSUE TITLE
[dmntcht] Expose svcContinueDebugEvent and svcBreakProcess functions

### ISSUE THREAD

**Issue by olliz0r** [Atmosphere-NX/Atmosphere#874]
#### Overview:
- Extend dmntcht to allow other sysmodules/homebrew to call svcBreakProcess and svcContinueDebugEvent on the debugged process</br>

#### Smaller Details: 
- N/A</br>

#### Nature of Request:  
- Addition
  - Extending the dmntcht service by two functions, exposing the svcBreakProcess and svcContinueDebugEvent functions on the debughandle.

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - dmnt</br>

### Why would this feature be useful?
This would allow homebrew applications and other sysmodules to freeze and unfreeze the process before writing to/reading from it to guarantee, that the application does not modify the data before the operation has completed. 

Example: Using dmntcht right now it is not possible to inject a full box of pokemon in pokemon sword/shield using a sysmodule while the game is running, without the game noticing half written slots and "fixing" them, resulting in broken data (bad eggs). Going the "original" route of calling svcDebugActiveProcess, svcWriteDebugProcessMemory and CloseHandle works fine, however, because the process stays frozen during the writing.</br>

**Comment by SciresM** [comment]
https://github.com/Atmosphere-NX/Atmosphere/pull/899

**Comment by SciresM** [comment]
Please verify that this works/meets your needs, @olliz0r.

**Comment by SciresM** [comment]
Also pinging @AnalogMan151 in case he has any interest in testing.

**Comment by SciresM** [comment]
Verified to work by analogman.
