### ISSUE TITLE
The version has not changed

### ISSUE THREAD

**Issue by orelumbras** [Atmosphere-NX/Atmosphere#877]
I transferred the Atmosphere Files 0.10.5 files to my SD card with the hack but after that nothing happened. I restored the backup I did because nothing happened. The version wasn't updated. What can I do? (I have atmosphere 0.8.3)
Maybe I didn't do the process well either? Can you send how to update? 
Thx :)

**Comment by nostone123** [comment]
did you happen to update your system firmware to version 10? if you did then you need to wait for a new update for atmosphere, this was for version 9.2

**Comment by orelumbras** [comment]
My previous program is 8.1.0 and the atmosphere is 0.9.3.  Is there an update to my atmosphere version or should I wait?

**Comment by orelumbras** [comment]
@nostone123 
My program firmware is 8.1.0.  The atmosphere is 0.9.3.  Is there an update to my atmosphere version or should I wait?

**Comment by nostone123** [comment]
Oh should have worked then(the latest release thats currently out), are you using the current fusse-primary.bin file to inject?

**Comment by orelumbras** [comment]
Oh, need to use it?  Can you list me step by step how to update? Because I'm new with the atmosphere and no one explained to me how to update...

**Comment by nostone123** [comment]
What method do you use to inject your payloads?

**Comment by orelumbras** [comment]
How can I check it?

**Comment by orelumbras** [comment]
I know I have a pegascape caffeine, and I'm not allowed to be online

**Comment by orelumbras** [comment]
And atlasNX KOSMOS

**Comment by SciresM** [comment]
Reopen with issue templates and full sentences.
