### ISSUE TITLE
I can’t install the latest atmosphere 

### ISSUE THREAD

**Issue by orelumbras** [Atmosphere-NX/Atmosphere#878]
Hi, I have 0.9.3 AMS and my firmware is 8.1.0.
I know I use pegascape caffeine and atlasNX KOSMOS.

(I don't know where to write it. So I wrote it in Issues..)

Can anyone send how to update step by step? 
🙏 Thanks

**Comment by 46620** [comment]
Downloaded the latest release from the [releases tab](https://github.com/Atmosphere-NX/Atmosphere/releases), extract the zip to your SD card and overwrite any files that it asks you to.
