### ISSUE TITLE
atmosphere isn't booting up and the backlight turns on.

### ISSUE THREAD

**Issue by uwusans** [Atmosphere-NX/Atmosphere#880]
my switch auto installed the newest update (10.0.0) and now when trying to run fusee. nothing shows on the screen and the backlight turns on.

**Comment by uwusans** [comment]
also i have the latest release of atmosphere on my sdcard

**Comment by ReignOfComputer** [comment]
The latest release of Atmosphere doesn't support 10.0.0 yet. It JUST got released. Be patient.

**Comment by uwusans** [comment]
aight
