### ISSUE TITLE
Software Closes while on new 0.11.0

### ISSUE THREAD

**Issue by ReZeroEmiria** [Atmosphere-NX/Atmosphere#881]
Accidentally updated my Switch to 10.0 yesterday, updated Atmosphere to 0.11.0 now to try it out, it boots fine however when I play Animal Crossing shortly after getting into the game it will close the game out and say the software has stopped due to an error. No error code or anything.

Trying to play animal crossing now without Atmosphere running and it seems to work, I've been here much longer without getting booted from the game.

**Comment by SciresM** [comment]
Could you try re-downloading the release build? I've seen some other reports like this but the errors don't make very much sense.

I disabled kernel loader as a preventative measure "just in case" it's causing problems in some way I don't understand, so I'm interested in whether the new build still exhibits the problem.

The build with the "just in case" fix is `-0775c788`.

**Comment by stallionoid** [comment]
That seemed to fix it for me, idk about OP.

**Comment by SciresM** [comment]
Sadly, it seems super random (per-boot-of-the-game?).

**Comment by stallionoid** [comment]
At least if it's inconsistent rebooting can be a temporary bandaid fix? At least until a real fix is found

**Comment by ReZeroEmiria** [comment]
Going to test playing some with the new build, before it booted me out every time at different intervals, though it became really severe after like 2 tries (1 min of playtime and boot)

**Comment by SciresM** [comment]
This is an exosphere issue. I am unclear how it is, but it cannot be anything else -- I reproduced a crash booting completely stock other than exosphere.

**Comment by johnnycanal** [comment]
I too have the crash on games like animal crossing new horizons sometimes on boot sometimes when connection online

**Comment by ReZeroEmiria** [comment]
I've heard of exosphere being in the works from your streams and such but am not very familiar with what it is exactly. Is it necessary to use this exosphere that is causing the problem or can you release a build without it temporarily while the issue is worked on?

**Comment by SciresM** [comment]
Heh. Unfortunately, exosphere is the one component that I literally cannot swap out, no.

**Comment by ReZeroEmiria** [comment]
I see, so then there's some sort of interaction between it and the new 10.0 firmware causing this? I'm assuming the exosphere component was also in the previous build of Atmosphere.

**Comment by SciresM** [comment]
No, the issue also occurs on < 10.0.0.

**Comment by ReZeroEmiria** [comment]
So then it's just an issue with the new build?  hmm

**Comment by lludu** [comment]
also having this issue, seems more common when trying to connect online into a game.

**Comment by ThatAnarchyDude** [comment]
I can't even get it to boot the CFW.
I get the usual crash screen right after the Switch logo.
![image](https://user-images.githubusercontent.com/60860646/79290062-14115e00-7e99-11ea-8bbe-3b8af6c462fb.png)

**Comment by Lorenzooone** [comment]
Don't know if this can help, however with the old update I had issues with flickering textures in AC:NH. (Before it crashed)

**Comment by Lorenzooone** [comment]
Update: the crashes still happen with the new download.

**Comment by johnnycanal** [comment]
Just wait for an update and be patient thats why its still in pre release obviously its not to 100% the dev already took notice and are working on it

**Comment by Lorenzooone** [comment]
It's not about being impatient. The more info a dev gets, the better. If the crashes still happen with the new build, it's better that they know.

**Comment by ReZeroEmiria** [comment]
> Don't know if this can help, however with the old 0.11.0 update I had issues with flickering textures in AC:NH. (Before it crashed)

What were you doing when the flickering textures were occuring? Where were you in game?

**Comment by SciresM** [comment]
fwiw, a lot of diagnosing has been going on on discord instead of in the issue tracker. Flickering textures are easily seen with blathers in AC.

**Comment by ThatAnarchyDude** [comment]
Where is the Discord, please?
I thought I saw a link around somewhere while I was researching issues with the new updates, but I can't find it now.

**Comment by SciresM** [comment]
there is a link in the issue templates.

**Comment by oceanmaster41** [comment]
Best way to use as of now to downgrade 0.9.2. And using of 0.10.5 cfw. Very easy to do.

**Comment by SuperN0va** [comment]
I‘m using the latest release, and the ACNH crushed after loading, then jumps out the error said the game data broken’
