### ISSUE TITLE
Atmosphere crashing upon attempting to load the home menu.

### ISSUE THREAD

**Issue by Nova2127u** [Atmosphere-NX/Atmosphere#882]
So i updated everything to the latest version (Atmosphere, my Switch, and the payload) but after it loading into the home menu the Switch just crashes, i can load my Switch just fine without Atmosphere but when i try to use Atmosphere to load through it just crashes. i had custom themes but i have removed them from the sd card when this happened. Any help would be apperciated.
![image0](https://user-images.githubusercontent.com/63681247/79280339-216d1f00-7e7e-11ea-8d85-bd20e974126b.jpg)

**Comment by SciresM** [comment]
This is caused by your custom theme. Please remove it.

**Comment by Nova2127u** [comment]
How can i remove it? i do not see anywhere on how to remove it.

**Comment by SciresM** [comment]
Delete the /atmosphere/contents/0100000000001000 folder.

**Comment by Nova2127u** [comment]
Alright, Thank you.
