### ISSUE TITLE
10.0.0 Failed to apply nosigchk / launch HOS!

### ISSUE THREAD

**Issue by Tatsunya** [Atmosphere-NX/Atmosphere#885]
Just tried out new Atmosphere release with Switch OS 10.0.0 injecting with newest hekate 5.1.4
Everything works fine but in the log during boot get the error after trying to patch kernel and kips, that it failed to apply nosigchk and thus failed to launch HOS.

Tried patch of 
https://github.com/Joonie86/hekate/releases
and https://gbatemp.net/threads/i-heard-that-you-guys-need-some-sweet-patches-for-atmosphere.521164/
but no luck.

Am I doing anything wrong? Switching from Kosmos to Atmosphere.

**Comment by fincs** [comment]
Piracy is not supported.
