### ISSUE TITLE
Cannot boot to CFW "Failed to apply 'nosigchk"

### ISSUE THREAD

**Issue by Godcranberry** [Atmosphere-NX/Atmosphere#886]
Just updated Hekate to 5.1.4.bin in Tegrea

Just updated Atmosphere to the latest version - my bootloader, Sept, Atmosphere,Switch folders have all been updated with the new files and I have brought over the new hbmenu.nro 

I get the following error: 

"Failed to apply 'nosigchk"
Failed to launch HOS!
Press any key

I have been doing this for a long time and have never had this issue so unsure if I did something wrong or if I spotted a bug somehow? I have a day one switch.

**Comment by fincs** [comment]
Piracy is not supported.

**Comment by Godcranberry** [comment]
What? I have never pirated anything?

**Comment by fincs** [comment]
"nosigchk" is a patch used exclusively for installing warez.
