### ISSUE TITLE
Ring Fit Adventure crashed while entering settings of the game

### ISSUE THREAD

**Issue by Cration** [Atmosphere-NX/Atmosphere#889]
## Bug Report

Ring Fit Adventure crashed while entering settings of the game.

Error Code: 2002-4742 (0x250c02)
Program: 010000000000100F
Firmware: 9.2.0 (Atmosphere 0.10.5)   (also crashed in 0.11.0 pre-released)
bootloader: hekate 5.1.3 (also crashed with 5.1.4)

game: Ring Fit Adventure (1.2.0)

Other games work fine for this console. However, when I tried to enter the settings of Ring Fit Adventure, it crashed and showed a blue screen.

**Comment by AnalogMan151** [comment]
Try with 0.11.1, may be a related issue.

**Comment by Cration** [comment]
Problem solved. Thanks so much.
