### ISSUE TITLE
An error after latest Atmosphere update.

### ISSUE THREAD

**Issue by Arathriel** [Atmosphere-NX/Atmosphere#890]
### What's the issue you encountered?

It's the first time for me seeing this bug and I'm using Atmopshere for 3-4 months already. After Atmopshere logo etc i have a black screeen for couple secs and an error.

### How can the issue be reproduced?

- Downloaded latest 0.11.1 update for Atmosphere, including fusee-primary.bin
- Copied every file to SD card, fusee-primary.bin to atmosphere folder.
- When asked if I want to overwrite files, I did that.
- Plugged in SD card,
- Turning on console with RCM loader and jig installed

### Crash Report

A fatal error occurred running Atmosphere.
Title ID:    010000000000002b
Error Desc: std : : abort ( )   called   (0xffe)
Report saved to /atmosphere/fatal_errors/

[Error.zip](https://github.com/Atmosphere-NX/Atmosphere/files/4480220/Error.zip)

### System Firmware Version

10.0.0

### Environment?

- Atmosphere launched by HEKATE, provided from RCM loader's manufacturer.
- https://www.xkit.xyz/

### Additional context?

- Additional info about your environment:
N/A

**Comment by masagrator** [comment]
You should also mention used sysmodules.

**Comment by Jboy93** [comment]
I have a similar issue. Updated hekate to 5.1.4 and atmosphere to 0.11.1 with my switch on 10.0.0 but can't seem to get past the atmosphere boot logo after choosing the fusee primary bin file. All I get is a black screen and nothing is happening.....all my sd files are up to date also the bootloader files etc.

**Comment by meizano** [comment]
see "Black screen #883"

**Comment by RockStar8757** [comment]
I have the same issues after updating everything, all i get is a black screen after the atmosphere boot logo

**Comment by fincs** [comment]
Piracy is not supported.
