### ISSUE TITLE
Create an emunand management tool.

### ISSUE THREAD

**Issue by SciresM** [Atmosphere-NX/Atmosphere#9]
We'll need a tool to back up a sysnand to emunand, and to format an SD card to contain the dumped NAND sectors.

Generally, this should be a NAND dump/restoration tool.

**Comment by Huskatron** [comment]
Hurry up.

**Comment by deadair3210** [comment]
> Hurry up.

Because rushing someone doing work for free always ends well.....

**Comment by Huskatron** [comment]
😭

**Comment by Brawl345** [comment]
Can you stop spamming this issue? It's done when it's done.

**Comment by SciresM** [comment]
"Hekate"
