### ISSUE TITLE
unable to load atmosphere after boot into emummc

### ISSUE THREAD

**Issue by JuicyBerger** [Atmosphere-NX/Atmosphere#901]
Failed To Apply 'nosigchk' Failed to Launch HOS!

### What's the issue you encountered?

After updating to Atmosphere 11.1 I decided to update switch firmware to 10.0, after doing so, When attempting to run emummc I Get the texts 'Failed To Apply 'nosigchk' Failed to Launch HOS!'

### How can the issue be reproduced?
Update to atmosphere 11.1 and update system firmware to 10.0. then attempt to run emummc 
[ * ]</br>
[ Include a detailed step by step process for recreating your issue. ]</br>
1. update atmosphere to latest firmware
2. update system firmware to 10.0
3. attempt to boot emummc
4. all logos come up and switch hard powers off after the atmosphere logo
### System Firmware Version

10.0.0</br>
[ Replace X's with system firmware version at time of crash. ]</br>
[ You can find your firmware version in the Settings -> System, under "System Update". ]</br>
[ If it says "Update Pending", you can clear the pending update by rebooting to Maintenance Mode. ]</br>

### Environment?
n/a

### Additional context?
n/a

**Comment by fincs** [comment]
> nosigchk

Piracy is not supported.

**Comment by jdfalk** [comment]
Or you could not be a jerk and just answer that the person should remove the kip1patch=nosigchk from hekate_ipl.ini. Which disables piracy and solves his problem, but sure why not be a jerk instead.

**Comment by JuicyBerger** [comment]
Awww thank you Johnathan Falk :) I had already figured it out a couple
hours later but thank you for actually coming to a helpful conclusion
you’re so sweet :3

**Comment by deadair3210** [comment]
The whole point of something not getting supported is it doesn't get answered or talked about......
