### ISSUE TITLE
[Request] Breakpoint/Watchpoint support for dmntcht

### ISSUE THREAD

**Issue by menoanie** [Atmosphere-NX/Atmosphere#907]
#### Overview:
Breakpoint/Watchpoint support for dmntcht to be able to set a bp/wp on a running game process.

#### Smaller Details: 
- N/A

#### Nature of Request:  
- Addition
  - Allow dmntcht to set/unset and list all the enabled bp/wp

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - dmnt</br>

### Why would this feature be useful?
At the moment there are no (at least public) way/tool to set a breakpoint/watchpoint, this would help a lot in game reverse engineering.

**Comment by SciresM** [comment]
No.

Atmosphere will have a real debugging api eventually, this is still blocked on cross platform usb.

I am emphatically not adding bp/wp to the cheat api, which is not for debugging.
