### ISSUE TITLE
Cannot open HBMenu in applet mode whild running a title

### ISSUE THREAD

**Issue by OldGnashburg** [Atmosphere-NX/Atmosphere#914]
### What's the issue you encountered?

[ While running a title such as Bayonetta and then launch the Album applet to get it the HB Menu to launch Edizon the Switch crashes with yellow text saying:
Panic occurred while running Atmosphere

Title ID: 010041544D530000
Error Desc: std::abort() (0xFFE)]</br>
[ Just System modules like Tesla and sigpatches for using Homebrew NSP's built with NRO2NSP ]</br>
[ I have Tesla, Fizeau, ldm_mitm, Sys-clk, Sys-tune, SaltyNX and a bunch of overlays installed but I have turned off Fizeau, and ldn_mitm. ]</br>

### How can the issue be reproduced?
[ I launch Bayonetta, make sure I'm in game, and press the HOME Button, move to and press A over the Album Applet. ]</br>

### System Firmware Version

[10.0.0]</br>

### Environment?
  - [ Official Atmosphere 0.11.1 EmuNAND Launched from Hekate]

### Additional context?

- [ Not sure if this is a memory related issue because of System modules,]

**Comment by OldGnashburg** [comment]
[report_03238780e.zip](https://github.com/Atmosphere-NX/Atmosphere/files/4507651/report_03238780e.zip)

**Comment by fincs** [comment]
> sigpatches for using Homebrew NSP's built with NRO2NSP

Piracy is not supported. The only supported way to run homebrew is through nx-hbloader processes.

> I have Tesla, Fizeau, ldm_mitm, Sys-clk, Sys-tune, SaltyNX and a bunch of overlays installed but I have turned off Fizeau, and ldn_mitm.

As usual, custom system modules depleting system resources (especially memory) and causing random crashes.

**Comment by basvijfwinkel-cinarra** [comment]
This issue also happens with legally purchased games.
I deleted sys-clk and sys-con and then the issue was solved.
