### ISSUE TITLE
Opening homebrew menu from album or games gives me 

### ISSUE THREAD

**Issue by DitDitGitHub** [Atmosphere-NX/Atmosphere#915]
Hi all,
After updating multiple apps, whenever I open the homebrew menu it gives me a fatal error which crashes my Switch. I'm on 0.11.1 This is the report: 
[71792941139_01005de00d05c000.log](https://github.com/Atmosphere-NX/Atmosphere/files/4518021/71792941139_01005de00d05c000.log)
All help is appreciated.

**Comment by JKakaofanatiker** [comment]
Same here. R on startup doesn't work either.

**Comment by SciresM** [comment]
1) Use the issue templates, please. 

2) Does the error occur if you delete atmosphere/hbl.nsp, /hbmenu.nro and replace them with the ones in the latest release zip?

**Comment by DitDitGitHub** [comment]
> * Use the issue templates, please.
> * Does the error occur if you delete atmosphere/hbl.nsp, /hbmenu.nro and replace them with the ones in the latest release zip?

I didn’t get a template... sorry. I will try to delete the two files. Thanks!

**Comment by DitDitGitHub** [comment]
Still not working... have updated both files. When I open the menu, it stays open for a couple of seconds before crashing.

**Comment by SciresM** [comment]
@DitDitGitHub The crash report you posted is corrupted. Can you see if there are any other crash reports which aren't corrupted?

**Comment by DitDitGitHub** [comment]
> @DitDitGitHub The crash report you posted is corrupted. Can you see if there are any other crash reports which aren't corrupted?

These are the others... I'm not sure if they are corrupted or not.
[77018863778_01005de00d05c000.log](https://github.com/Atmosphere-NX/Atmosphere/files/4518466/77018863778_01005de00d05c000.log)
[13266312791_01005de00d05c000.log](https://github.com/Atmosphere-NX/Atmosphere/files/4518467/13266312791_01005de00d05c000.log)
I think they are the same error...

**Comment by masagrator** [comment]
Both are corrupted. Have you tried to use different sdcard? Are you using exFAT or FAT32? Emummc or sysnand? 
Etc

**Comment by DitDitGitHub** [comment]
> Both are corrupted. Have you tried to use different sdcard? Are you using exFAT or FAT32? Emummc or sysnand?
> Etc
I haven't used a different sdcard, I'm on Fat32 and Sysnand. Just had an idea, going to try removing all hbmenu apps. It started once I updated them so it might be one of them? I have no idea what I'm doing lol

**Comment by DitDitGitHub** [comment]
So after deleting all the apps I get a new error:
[00527960916_430000000000000b.log](https://github.com/Atmosphere-NX/Atmosphere/files/4518584/00527960916_430000000000000b.log)

**Comment by DitDitGitHub** [comment]
And I get the same error while opening some games

**Comment by masagrator** [comment]
Sys-botbase is crashing. Delete it.

**Comment by DitDitGitHub** [comment]
Thank you! The problem is fixed!
