### ISSUE TITLE
Crash when accessing Album to load into HBMenu

### ISSUE THREAD

**Issue by HairyMilkshakes** [Atmosphere-NX/Atmosphere#917]
Getting the following error code when trying to launch into the HBMenu from album icon: Error Code: 2345-0033 (0x4359)

All files are obtained from sdsetup.com and so I would assume they are all updated. Firmware is 9.2.0 Atmosphere 0.11.1

**Comment by masagrator** [comment]
https://github.com/Atmosphere-NX/Atmosphere/issues/new?template=bug_report.md

Template

**Comment by HairyMilkshakes** [comment]
Thanks, didn't see that before. It's not generating a crash report inside the directory in Atmosphere, for some odd reason.

**Comment by HairyMilkshakes** [comment]
I deleted the files inside atmosphere/contents and replaced them with the defaults from sdsetup and it appeared to function again. not sure which module is crashing and will advise.

**Comment by fincs** [comment]
"sdsetup"

Care to elaborate?

**Comment by deadair3210** [comment]
It's a website where you can select items and it will build the SD card folder for you

**Comment by HairyMilkshakes** [comment]
Resolved. No longer an issue after I did this: https://github.com/Atmosphere-NX/Atmosphere/issues/917#issuecomment-618208140

**Comment by kkirby** [comment]
I think the issue is with sys-con. Just a heads up for anyone else having issues.
