### ISSUE TITLE
Error when i try to compile Atmosphere

### ISSUE THREAD

**Issue by aldone1** [Atmosphere-NX/Atmosphere#919]
This is the error where is the problem? Anyone can help me?
**/opt/devkitpro/Atmosphere-master/exosphere/src/configitem.c: In function 'configitem_get':
<command-line>: error: invalid suffix "x" on integer constant
<command-line>: note: in definition of macro 'ATMOSPHERE_RELEASE_VERSION_HASH'
/opt/devkitpro/devkitA64/base_rules:18: recipe for target 'configitem.o' failed
make[1]: *** [configitem.o] Error 1
Makefile:130: recipe for target 'build' failed
make: *** [build] Error 2**

**Comment by HookedBehemoth** [comment]
That constant is defined in [here](https://github.com/Atmosphere-NX/Atmosphere/blob/master/exosphere/Makefile) based on the git hash

You'll need to compile on a git repo. Downloading the zip won't do.

**Comment by aldone1** [comment]
Ok, thank you very much
