### ISSUE TITLE
0.11.1 not working with 10.0.1

### ISSUE THREAD

**Issue by user466** [Atmosphere-NX/Atmosphere#920]
So I'm running Atmosphere 0.11.1 and my switch updated through the system settings to 10.0.1 and now it doesn't want to boot up past the sept, and I've already deleted the atmosphere, Sept, and and homebrew file and reinstalled them again but it still doesnt boot up.

**Comment by astroavenger9** [comment]
i'm having the same problem. my switch updated to 10.0.1 and now it won't boot past the sept screen. also made sure that i got the latest verson of atmosphere.

**Comment by user466** [comment]
UPDATE: So I booted in through normal and it says I need a system update to use the MicroSD but my system is already up to date

**Comment by deadair3210** [comment]
You are missing the exfat update likely

**Comment by astroavenger9** [comment]
@user466 i did that too and said i needed to update as well. but when i click on update it says i have the latest version.

@deadair3210 what do you mean?

**Comment by deadair3210** [comment]
If your SD card is formatted to exfat, you require a small update to install the driver so the switch can read the card. If your SD card is formatted to exfat, or for some reason the switch thinks it is, and you don't have that update, the switch will say that you need a update to read the card

**Comment by fincs** [comment]
There's something really odd going on here, because if your card was formatted as exFAT but your firmware is the FAT32-only variant, Atmosphère would not have been able to boot at all, since Atmosphère relies on accessing the SD card filesystem from very early on in the Horizon OS bootup sequence. Please make sure you have Atmosphère correctly installed (and use fusée instead of e.g. hekate to verify that you are not in fact booting up to stock firmware); as the expected result should have been a boot failure.

**Comment by astroavenger9** [comment]
@deadair3210 my sd card is indeed formatted to exfat. my switch does say it need to be updated(when booted normaly) but when i click on update it says there nothing to update.

@fincs as far as i know i have atmosphere correctly installed. i'll aslo note that my switch was booting up just fine before i installed the 10.0.1 update and as soon as i updated it stoped booting up all the way.

**Comment by astroavenger9** [comment]
would reformatting my sd card fix the problem because this sounds like a formating problem. don't really want though because i got a lot of games on there and its going to take forever to back everthing up and then put back on.

**Comment by fincs** [comment]
Since you have exFAT, it's very possible that you have filesystem corruption. You might want to get that SD card reformatted as FAT32 anyway.

**Comment by astroavenger9** [comment]
@fincs sigh i'll try that then

**Comment by SciresM** [comment]
Closing, reopen with issue templates if the error occurs post reformat.

**Comment by astroavenger9** [comment]
ok once i backed everything up and tried to format it FAT32 wasn't availble. so i also tried booting up the switch normally without atmosphere and getting my switch to format my sd card. when i did it said i needed a system update. so when i clicked update it said i already got the latest update. so i'm kind of stuck. also i've been playing on my switch with my sd card in exfat format for months with it working just fine. why am i haveing problems now. i did try formatting my sd card keeping it in exfat  and installing atmosphere on agian and it still doesn't booot up all the way. it show the booting screens but thats it. what am i doing wrong.

**Comment by fincs** [comment]
Try using Rufus to format your SD card; that lets you format big cards as FAT32 even if Windows doesn't let you.

**Comment by astroavenger9** [comment]
hhhhggh
