### ISSUE TITLE
Fatal error (Bad SVC)

### ISSUE THREAD

**Issue by UnderRev0lved** [Atmosphere-NX/Atmosphere#924]
### What's the issue you encountered?

I didn't change ams and used vanilla from release on Github.
While playing "PC Building Simulator", a fatal error screen appeared with "Bad SVC" error
Edit while playing FUZE 4 it appeared too.

### How can the issue be reproduced?

Playing PC building simulator and going fast in step.

### System Firmware Version

9.2.0</br>
</br>
</br>
</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by:
Fusée
- Official release or unofficial build: 
Official 0.11.1
 
- Do you have additional kips or sysmodules you're loading:
Not sure
- Homebrew software installed: 
No

### Additional context?

- Additional info about your environment:
- [ Any other information relevant to your issue. ]

**Comment by SciresM** [comment]
Please upload the relevant crash report...?

**Comment by UnderRev0lved** [comment]
Can't find it

**Comment by UnderRev0lved** [comment]
I'm searching it

**Comment by SciresM** [comment]
Was it an atmosphere fatal error (black screen, report dumped to fatal errors dir) or a game fatal (e.g. ams fatal screen displayed by fatal sysmodule?)

Also can't really do anything without knowing what program id it occurred in lol

**Comment by UnderRev0lved** [comment]
[report_000000068bfad0de.zip](https://github.com/Atmosphere-NX/Atmosphere/files/4552870/report_000000068bfad0de.zip)
Error report of Bad SVC 0x301 while playing FUZE4

**Comment by UnderRev0lved** [comment]
As seen on DIscord, the problem is from the switch itself.
Issue closed

**Comment by Thebrianzard** [comment]
Hello Ghost, how did you fix this issue?
