### ISSUE TITLE
Black screen after updating to 0.12.0

### ISSUE THREAD

**Issue by idmew** [Atmosphere-NX/Atmosphere#925]
Hi, I just updated to the latest release and I'm getting a black screen after the Atmosphere logo.
Everything was fine before and I never had any problems updating.
Was on 0.11.1 and 9.2 firmware.
Can someone help me please?

**Comment by i4s33u** [comment]
I have this issue too :(

**Comment by daniele728** [comment]
Same issue here, FW 9.2 , previous atmo 10.4.
Tried to turn back with 10.4, black screen after atmo logo screen.

**Comment by idmew** [comment]
I was able to make it work by deleting the Atmosphere folder entirely and copy the new one over.

**Comment by AbuYo** [comment]
I tried deleting Atmosphere folder and copying the new one over too and it successfully booted up, but I could not run any installed applications, it always shows the error "Could not start the software"

**Comment by idmew** [comment]
> I tried deleting Atmosphere folder and copying the new one over too and it successfully booted up, but I could not run any installed applications, it always shows the error "Could not start the software"

Same thing happened to me, you have to add the patches from here: [https://gbatemp.net/threads/atmosphere-patches-es-fs-and-loader-fusee_primary-only.562812/](url).

After I did that everything went back to normal.

**Comment by fincs** [comment]
Piracy is not supported.
