### ISSUE TITLE
Local wireless no longer works

### ISSUE THREAD

**Issue by sacreduniverse** [Atmosphere-NX/Atmosphere#928]
Updated atmosphere and everything else and then pulled new firmware to the switch and now I’m unable to use local wireless (an L shows up next to the wireless icon) in any game, or at least Mario kart or animal crossing.

Booting to stock firmware does fix this problem so I assume something got weird or corrupted but I tried reloading files and that didn’t seem to help either.

**Comment by annson24** [comment]
You might have ldn_mitm enabled. Disable it first, reboot, then try again.

**Comment by sacreduniverse** [comment]
> You might have ldn_mitm enabled. Disable it first, reboot, then try again.

That was it! Thank you so much!
