### ISSUE TITLE
Software will not start after updating to Atmosphere 0.12.0

### ISSUE THREAD

**Issue by trixter06** [Atmosphere-NX/Atmosphere#931]
Updated Switch FW to 10.0.1 and Atmosphere to 0.12.0 and now I receive the message "Could not start the software" when trying to run any games?

Any advice or tips on how to solve this issue or do I need to downgrade my Switch FW?

**Comment by evertonstz** [comment]
Are those legit games? If not, you probably won't get support for piracy here, you'll have more luck in a forum like gbatemp.

**Comment by fincs** [comment]
This really smells of piracy/breakage after sysupdate+ams update. Otherwise it's filesystem corruption, which can be fixed with a SD card format + redownload of games from eShop.
