### ISSUE TITLE
Move the contents folder from /atmosphere to root

### ISSUE THREAD

**Issue by IISAKNIFE** [Atmosphere-NX/Atmosphere#932]
#### Overview:
- Moving contents folder to outside of the atmosphere folder.</br>

#### Smaller Details: 
- N/A</br>

#### Nature of Request:  
- Change

### What component do you feel this would best fit within?
- N/A</br>

### Why would this feature be useful?
 This feature would be useful for clean installs. Several times, I have deleted my mods in the contents folder because there are times that a clean install is used to make atmosphere work. It can make games like Skyrim unplayable until I get the folder back to the way it was. This feature would prevent accidental deletion of game mods due to needing to clean install atmosphere.</br>

**Comment by deadair3210** [comment]
Problem with moving the contents to keep it from being affected by clean installs is, half of the time, the contents folder being cleaned out and reset to a known state is most of the reason to do a clean install, as sysmodules usually cause the most issues
