### ISSUE TITLE
Error 20001-0123 (0xf601)

### ISSUE THREAD

**Issue by PauchardThomas** [Atmosphere-NX/Atmosphere#936]
## Bug Report
Hi,

### What's the issue you encountered?

Atmosphere crash after playing <1min at PKMN Sword. However, I tried on Mario Kart, Pokemon Lets go for instance and no crash. Maybe a RAM , memory issue ??

### How can the issue be reproduced?

* Obtain EmuNAND running on 8.0.1
* Install a fresh copy of Atmosphere 0.11.1-master-d81a3bdc
* Boot into EmuNAND using Hekate
* Launching Pokemon sword
* Wait around 1min
* Error is produced (Error 20001-0123 (0xf601))

### Crash Report

Got 2 crash reports at same time :
 * [report 1](https://gist.github.com/PauchardThomas/8db44fe17d77a32f4f85d243cb717d5c)
 * [report 2](https://gist.github.com/PauchardThomas/95125af7b67366c44ead30dabd11208d)

### System Firmware Version

* Sysnand 8.0.1
* Emunand 8.0.1|AMS 0.11.1|E</br>

### Environment?

- What bootloader (fusèe, hekate, etc) was Atmosphère launched by: Hekate v5.1.4
- Homebrew software installed: [ * ]

### Additional context?

N/A

**Comment by SciresM** [comment]
This is caused by (outdated(?)) ldn.mitm, remove it.

**Comment by PauchardThomas** [comment]
Hi @SciresM  can you be more expressive ? How to remove this "ldn.mitm" ? Thanks

**Comment by SciresM** [comment]
You installed a custom system module. To remove it, remove the atmosphere/contents/4200000000000010/ folder.

**Comment by PauchardThomas** [comment]
Thank you so much
