### ISSUE TITLE
Panic error when opening hbmenu via the album.

### ISSUE THREAD

**Issue by bcoliver** [Atmosphere-NX/Atmosphere#947]
I'm new to the Switch CFW scene, so bear with me here.

Today I installed Atmosphere through the homebrew guide, and everything worked fine to begin with. However, I noticed that when I would try and launch a game through my emuMMC, I would get an error about necessary game data being missing. I copied the Nintendo folder on the root of my SD card and merged it with the one contained within the emuMMC folder.

This did allow me to play my games on the emuMMC but for whatever reason, opening hbmenu returns a panic error. I then reverted the changes to the Nintendo folder in an effort to fix it, but now games will not launch and the panic error persists when I open hbmenu.

I've attached an error log below, any help would be much appreciated.

(P.S. -- If there's a way for me to fix the issue with my games I would appreciate a solution to that too, so I don't mess anything up next time.)

Thanks!

**Comment by SciresM** [comment]
Heh...happy to try to help resolve this, but please re-open using the issue templates. They ask for important information for diagnosis (and give me the info I need in a formatted way).

Also you didn't attach error log.
