### ISSUE TITLE
"A fatal error occurred when running Atmosphere"

### ISSUE THREAD

**Issue by gravelydesired** [Atmosphere-NX/Atmosphere#949]
Bug Report
A fatal error occurred when running Atmosphere.
Title ID: 010041544d530000
Error Desc: std::abort() called (0xffe)
Report saved to /atmosphere/fatal_errors/report_00000000619404a.bin

What's the issue you encountered?
When playing on my Switch today, my device told me that an update was available. I was going to install it with ChoiDujour later, but accidentally pressed "Update" instead of "Start Software" to get into a game. The Switch restarted, and this error comes up when trying to start Atmosphere, even after updating Kosmos to the latest version.

How can the issue be reproduced?
Boot to RCM
Launch Hekate
Boot Atmosphere through either fusèe-primary or emunand

Crash Report
https://github.com/gravelydesired/bugs/blob/master/report_000000000619404a.bin

System Firmware Version
10.0.0 before, 10.0.2 after.

**Comment by SciresM** [comment]
Your SD card is formatted as exFAT, but your console does not have exFAT FIRM installed.

Reformat your SD card as FAT32, not an atmosphere error.
