### ISSUE TITLE
Readme file change suggestion & People request

### ISSUE THREAD

**Issue by PyroFlareX** [Atmosphere-NX/Atmosphere#96]
For people like me who want to see and learn how this is done, but are annoyed and confused about how projects like these are structured, I say this:

Please include a readme section (or another text file) in how this project is structured rather than people like me wasting time reading C/C++ code and reading up again on switch stuff to find out what each does.

All in just an idea, and thank you for reading this as well as making this.

Also, I ask what people like me with basic programming practice (C#, python), can do to help?

**Comment by encounter** [comment]
>rather than people like me wasting time reading C/C++ code and reading up again on switch stuff

Both of those things are necessary to contribute to the project, and would not be a waste of time.
Unfortunately there's not much here that doesn't require a deep understanding of Switch internals.

**Comment by Sorixelle** [comment]
If you're still interested in contributing, the [Projects](https://github.com/Atmosphere-NX/Atmosphere/projects) tab has a brief overview of the components.

**Comment by PyroFlareX** [comment]
k thanks then! Thank you again for your hard work at this!

**Comment by huangya90** [comment]
Yes. Looking forward to more documents besides https://github.com/Atmosphere-NX/Atmosphere/projects

**Comment by hexkyz** [comment]
The current Projects tab provides an amount of information proportional to the current project's state. After an usable build is released, better documentation will follow.
