### ISSUE TITLE
atmosphere 0.12.0 Not working on switch 10.0.2

### ISSUE THREAD

**Issue by Davillion11** [Atmosphere-NX/Atmosphere#961]
when it try to use atmosphere, the screen on the switch goes blank and don't load

**Comment by jvkhriz27** [comment]
Instale el fusee-primary.bin de la version atmosphere 0.12.0 . No me funciono en la version switch 10.0.2. The screen on the switch goes black and don't load

**Comment by jvkhriz27** [comment]
Install the fusee-primary.bin from version atmosphere 0.12.0. It didn't work on switch version 10.0.2. The screen on the switch goes black and don't load.

**Comment by SciresM** [comment]
Please use the issue templates.

Also, this usually indicates user did not actually extract fusee-secondary or sept properly.
