### ISSUE TITLE
Add single press of a key for type 8 cheat command

### ISSUE THREAD

**Issue by igoticecream** [Atmosphere-NX/Atmosphere#963]
#### Overview:
- I'd like to suggest a feature of code type 8 of the cheat module (key press to execute) to execute only 1 time while the key is on hold and reset when its released. Currently it executes N times.

#### Nature of Request:
- Addition of a more customizable type 8 command. Currently it offers 'if key is on hold', with this, a new option 'if key is pressed' is added.

### What component do you feel this would best fit within?
- [Stratosphère](https://github.com/Atmosphere-NX/Atmosphere#components)</br>
    - The dmnt_cheat_vm custom sys-module.

### Why would this feature be useful?
I'm creating a cheat on ACNH that duplicates whatever is on the first slot of the inventory to the next available free slot, its working but if i hold the key too long (measured in milliseconds), it duplicate several times if theres more than an empty slot

**Comment by SciresM** [comment]
We very intentionally do not allow the passing of any state from cheat VM execution A to cheat VM execution B.

However, even more basically -- the cheat engine does not have any way to detect continuous button presses between executions.
