### ISSUE TITLE
Underclocking

### ISSUE THREAD

**Issue by cualquiercosa327** [Atmosphere-NX/Atmosphere#99]
Hi.I would suggest if the cpu/gpu frecuences can be underclocked (an example i think than games as puyo puyo tennis doesnt need full frecuency speed for running and this would make the batery give extra time) as we can do on psp.
Thanks

**Comment by cualquiercosa327** [comment]
i found than it can be set to 200 mhz.I think than it would be perfect for some homebrews and emulators than doesnt need so much frecuency.(As example nds and psp has a lot of emulators and most run on this (psp case,also 333 mhz) or lower frecuency )

**Comment by adamnock** [comment]
I would suspect there is already a battery management system running which takes care of the majority of what this would achieve. (maybe not, I dont know).

Still, if there's any difficulty in having Homebrew utilise such a system, it might have benefit.

**Comment by hexkyz** [comment]
Invalid issue
